### ISSUE TITLE
Improvement on virtual

### ISSUE THREAD

**Issue by dy0nysos** [tomav/docker-mailserver#10]
Hi,

Once again, thanks for your job. It's pretty amazing to get a full working postfix + clamav + spamassassin server.

Is it possible to separate virtual and vmailbox configuration?

I need to have a contact email that relays its email on several other adresses (such as gmail, outlook etc.). To do this, I didn't find any other way than connect me on the container and modify the virtual file.
Then postmap it and reload postfix configuration.

The problem is that the virtual file is recreated each time I start the container.

Is there a way to make a new conf file (added in the postfix folder on the host machine) to set the virtual emails ?

**Comment by tomav** [comment]
@dy0nysos, a new file will work.
But perhaps we can improve `accounts.cf` llike this: 

    # real account
    user@domain.tld|mypassword|alias1,alias2
    # relay account
    user@domain.tld|RELAY|user@external1.com,user@external2.com

With this solution, `accounts.cf` will remain the same.
You just have to improve `start-mailserver.sh` to add the parsing of `RELAY` accounts correctly.

It's an open discussion, let me know what you think.

**Comment by tomav** [comment]
Hmm, an advantage of your solution with a new file is that it will separate `accounts.cf` and `redirects.cf` (or other name) and could avoid errors.

**Comment by dy0nysos** [comment]
The question is, do we need to remove aliases from `accounts.cf` and set up all aliases in `redirects.cf` (or whatever is its name) or mixing both aliases config.

My opinion is that we should separate accounts and aliases config. With this split, you could set only virtuals or only accounts, and an error in one of these file does not break the entire container.

Moreover, it could be a first step to mailiing lists or this kind of advanced mail features.

**Comment by tomav** [comment]
So `accounts.cf` will only contain mail accounts and passwords.
Both aliases and redirect will be managed by `redirect.cf`.
This is ok for me.

Note that it will break backward compatibility.

**Comment by dy0nysos** [comment]
Seems good to me too.
