### ISSUE TITLE
strange error on client

### ISSUE THREAD

**Issue by scher200** [tomav/docker-mailserver#100]
Hi men,

I got it running with SSL letsencrypt but now I get the following error in my thinderbird:

```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIMsgAccountManager.createIncomingServer]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://messenger/content/accountcreation/verifyConfig.js :: verifyConfig :: line 60"  data: no]
```

if you like i can mail you the credentials of my mailserver so yo can try it yourself.
I used the following settings:
![settingsmailtvial](https://cloud.githubusercontent.com/assets/9550429/13607956/d707230c-e552-11e5-87eb-921ea0fbb7cc.png)

Greets Jeroen

**Comment by scher200** [comment]
Hi Tomav,

did it work, with you server and thinderbird?

**Comment by philhansen** [comment]
I recently set up the container and I access my mail over IMAP using Thunderbird.  Those are the same settings I use.  Initially I had some troubles with the SSL connection and this command was helpful for debugging:

openssl s_client -showcerts -connect mail.sg20.com:995

In my case there was a path issue with the letsencrypt generated cert.  Trying the SSL connection directly gave me the necessary clue (the error message in Thunderbird was not helpful).

**Comment by scher200** [comment]
thanks Phil I am going to check it.

2016-03-15 1:33 GMT+01:00 Phil Hansen <notifications@github.com>:

> I recently set up the container and I access my mail over IMAP using
> Thunderbird. Those are the same settings I use. Initially I had some
> troubles with the SSL connection and this command was helpful for debugging:
>
> openssl s_client -showcerts -connect mail.sg20.com:995
>
> In my case there was a path issue with the letsencrypt generated cert.
> Trying the SSL connection directly gave me the necessary clue (the error
> message in Thunderbird was not helpful).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/tomav/docker-mailserver/issues/100#issuecomment-196586089
>



-- 
[image: FreeLaunching - Jeroen Schermer] <http://freelaunching.nl/>

**Comment by tomav** [comment]
@scher200 it works with Thunderbird on my server with the same configuration you have.

**Comment by tomav** [comment]
@scher200 You tried with another mail client? Are you sure it's not related to SSL configuration / certs?

**Comment by scher200** [comment]
@tomav I am able to try it tomorrow I will let you know

2016-03-22 12:01 GMT+01:00 Thomas VIAL <notifications@github.com>:

> @scher200 <https://github.com/scher200> You tried with another mail
> client? Are you sure it's not related to SSL configuration / certs?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tomav/docker-mailserver/issues/100#issuecomment-199756118>
>



-- 
[image: FreeLaunching - Jeroen Schermer] <http://freelaunching.nl/>

**Comment by tomav** [comment]
Closed due to inactivity. Reopen if needed.
