### ISSUE TITLE
Uses of explicit domains within documentation and configuration files

### ISSUE THREAD

**Issue by StrayLightning** [tomav/docker-mailserver#1000]
Doing a search on the docker-mailserver for e.g. "domain.com" results in a number of uses of "domain.com", "my-domain.com", etc.  Most notably "domain.com" is in the default .env file.  You may have permission to use these already, but it would be better to use e.g. "example.com" per RFC 2606 (https://www.rfc-editor.org/rfc/rfc2606.txt)

**Comment by johansmitsnl** [comment]
Could you provide a PR for this?

**Comment by StrayLightning** [comment]
I'm sorry, but I've given up trying to get docker-mailserver to work.

**Comment by johansmitsnl** [comment]
Why did you give up?
