### ISSUE TITLE
Impossible to start relay only with no account

### ISSUE THREAD

**Issue by blackholegalaxy** [tomav/docker-mailserver#1001]
## Context
Using this image as a mail relay. I only need SMTP. And I wont configure any account. I use advanced by domain and by sender rules to dispatch to the proper relay.

## Expected Behavior
I should be able to run the image as a relay without any account.

## Actual Behavior
Due to the bug #801 we cannot start the image with `SMTP_ONLY=1` since it triggers amavis errors and restart loop.

Starting with `SMTP_ONLY=` and only relay configured triggers:

```
Initializing setup
Checking configuration
Configuring mail server
grep: /tmp/docker-mailserver/postfix-accounts.cf: No such file or directory
Error: Unless using LDAP, you need at least 1 email account to start the server.
Error: Please fix your configuration. Exiting...
2018-07-08 17:44:02,292 INFO exited: mailserver (exit status 1; not expected)
```

## Possible Fix
Fix 801, or allow starting without account if relay is defined.

## Your Environment

* Amount of RAM available: `16GB`
* Mailserver version used: `latest`, 8th july 2018
* Docker version used: `18.03.1-ce`

**Comment by johansmitsnl** [comment]
Could you provide a PR to solve this issue?

**Comment by johansmitsnl** [comment]
You can use the `SMTP_ONLY=1` option.
But this might be can issue #801

**Comment by blackholegalaxy** [comment]
As stated it's indeed an issue with #801
