### ISSUE TITLE
Cannot send or receive emails

### ISSUE THREAD

**Issue by weiluntong** [tomav/docker-mailserver#1002]
I am using RainLoop for my client, and I can login to the account, "webmaster@fancydomain.tld" I created using the `setup.sh` script provided from this repository. However, I cannot send or receive emails. Within Rainloop, trying to send a test email to my gmail account results in, "Authentication Failure" despite logging into "webmaster@fancydomain.tld" and sending an email from my gmail account to "webmaster@fancydomain.tld" does not show up in the RainLoop client.
## Context

I was trying to follow this tutorial: https://www.davd.eu/byecloud-building-a-mailserver-with-modern-webmail/

I made some changes to the docker-compose.yml to use letsencrypt for SSL and nginx for my reverse proxy rather than Caddy. That can be found here: https://pastebin.com/ZfAAbMN5

My domain is managed by GoDaddy so I added DNS records there for SPF and DKIM. I also uploaded that: https://imgur.com/a/YhgS5zN

And I setup port forwarding. All the relevant forwarding rules point to 192.168.1.5 and the others are just other devices I'm using for something unrelated: https://imgur.com/a/jshh97T

After this I started the container with `docker-compose up -d` and successfully reached the RainLoop client via mail.fancydomain.tld.

I also checked checktls.com. Oddly, if I put "mail.fancydomain.tld" into the "eMail Target" everything passes, but if I put "fancydomain.tld" the "Cert" fails and I don't know what that means, but here's that:
https://imgur.com/a/bI7lP1F

I proceeded to "mail.fancydomain.tld/?admin" and logged into the admin console with RainLoop's default administrator account (admin) and password (12345).

I setup the domain as instructed by the tutorial previously mentioned, Here are images of my settings: https://imgur.com/a/JKIBS4v

With that I was able to go back to "mail.fancydomain.tld" and login with email (webmaster) and password (fancypassword). However, I could not send an email, as I get an "Authentication Failure" https://imgur.com/a/W1my2N5

With this I thought I'd try and find an smtp test, and mxtoolbox.com was the first on Google search results. Again, I tried both "fancydomain.tld" and "mail.fancydomain.tld" but this time they both had the same results. Results which I don't really know how to interpret the errors it gives: https://imgur.com/a/JngH8jS

## Expected Behavior

I was hoping I'd be able to send and receive emails after following the previously mentioned tutorial, though it's pretty vague on whether or not that's the next step at the end (it does not explicitly say we can send and receive emails after following the guide).

## Actual Behavior

I illustrated the actual behavior above, but in terms of sending from my personal email to webmaster@fancydomain.tld, gmail says it was sent without giving me the postmaster email that notifies me that no such email exists, but I don't see it arrive on RainLoop.

## Your Environment

* Amount of RAM available: 8GB
* Mailserver version used: latest
* Docker version used: 17.12.1-ce, build 7390fc6
* Environment settings relevant to the config: I have the entire docker-compose.yml available above

**Comment by weiluntong** [comment]
Just as an update, I changed my mx record to point to "mail.fancydomain.tld" instead of just "mail" and it seems to have fixed the issue of receiving, however, I still cannot send emails as I still get an authentication failure.

**Comment by weiluntong** [comment]
Solved. Was indeed a RainLoop issue. My solution was, don't "use short login" for SMTP settings referenced on step 8 in RainLoop configurations.

**Comment by skylord123** [comment]
If this is solved you should close the issue.
