### ISSUE TITLE
bashrc exported env vars are not quoted

### ISSUE THREAD

**Issue by scintill** [tomav/docker-mailserver#1007]
target/start-mailserver.sh exports variables to /root/.bashrc, but it does not quote them, resulting in multi-word values being truncated to the first word.

## Context
I don't know much about the real implications of this issue, or why variables are written to .bashrc. I just noticed after spending some time trying to figure out why my variables were wrong, when I ran an interactive bash shell in the container.

## Expected Behavior (mail_mail_1 is a running instance of the image)
```
# docker exec -t mail_mail_1 bash -i -c env | grep POSTGREY_TEXT
POSTGREY_TEXT=Delayed by postgrey
```

## Actual Behavior (mail_mail_1 is a running instance of the image)
```
# docker exec -t mail_mail_1 bash -i -c env | grep POSTGREY_TEXT
POSTGREY_TEXT=Delayed
```

Note that the environment is correct, if bash doesn't parse bashrc. bashrc is missing quotes.

```
# docker exec -t mail_mail_1 sh -c "env; cat /root/.bashrc" | grep POSTGREY_TEXT
POSTGREY_TEXT=Delayed by postgrey
export POSTGREY_TEXT=Delayed by postgrey
```

I'm wondering if the bashrc writing is even needed. Maybe @alinmear can shed some light on that.

**Comment by johansmitsnl** [comment]
This is indeed wrong, could you provide a pr?
