### ISSUE TITLE
chmod -R /var/mail

### ISSUE THREAD

**Issue by artb1sh** [tomav/docker-mailserver#1008]
Когда делаю нового пользователя у меня  начинает делать chmod -R /var/mail и вышибает все диски LA под 200, HELP

**Comment by artb1sh** [comment]
If i addmailuser in my container, LA in my server go to 100, i see what hi duing, he make chmod -R /var/mail/
HELP!!!

**Comment by johansmitsnl** [comment]
This is a local permission issue. Read https://github.com/tomav/docker-mailserver/wiki/Installation-Examples for how to install it.
