### ISSUE TITLE
Add z-push / Activesync

### ISSUE THREAD

**Issue by Gymnae** [tomav/docker-mailserver#101]
Do you think it would be a good idea to also integrate push functionality, or to keep it seperate?
There is a container for making use of z-push, but maybe it could be integrated directly:

https://github.com/fmbiete/Z-Push-contrib/tree/master/docker

**Comment by tomav** [comment]
Note : I like the idea, I used `zpush` on my mail server before I moved to docker.

**Comment by Gymnae** [comment]
I have not worked with your package `docker-mailserver `yet - Right now I'm spinning up my single private node and got into Alpine Linux. I'm waiting if you might change your mind about rebasing, if not, I'll pull your package as it is and will see if `z-push` could be added.
The thing I thought about if integrating it would go against the docker manifest. `docker-mailserver` is already a collection of services in one, but a collection of tightly connected services. Would z-push be considered close enough? 
It might be easier to spin up a Alpine based `z-push` container and link it. Not sure.

Also, I've found out about [SoGo](https://github.com/JensErat/docker-sogo) Groupware, which includes real, true ActiveSync - this could go well with your package.

**Comment by Gymnae** [comment]
I'm working on a z-push image and will report back once it works, so far things are promising.
I should be very well linkable to your image

**Comment by tomav** [comment]
Hi @Gymnae, this issue is still Work In Progress?
If not let me know, I'll close it.
Thanks.

**Comment by Gymnae** [comment]
I actually have an image which needs testing. I haven't migrated my mailserver yet and plan to to so once your v2 is released - then I'll continue working on my z-push container.
The repo is [here](https://github.com/Gymnae/docker-zpush). It might already work, it might burn down your house and steal your wife. Dunno. Will continue working on it once I've got a dockerized mailserver running :)

**Comment by Dunky13** [comment]
Any updates on this feature?

**Comment by thiesschneider** [comment]
Would be awesome!

**Comment by dumblob** [comment]
In the newer thread https://github.com/docker-mailserver/docker-mailserver/issues/622 it was demonstrated, that z-push is too simplistic to cover the usual use cases and that IMAP "push" is not (and will not be) supported on Apple devices (because it's too power hungry) unlike activesync.

So my question is whether there is any plan to support activesync in docker-mailserver?

Be it indirectly or directly.
