### ISSUE TITLE
Can't send mail

### ISSUE THREAD

**Issue by Wqrld** [tomav/docker-mailserver#1010]
I am able to receive emails but email sent using windows mail (and other programs likely) are never receieved.

## Expected Behavior
I should be able to send and receive mail
## Actual Behavior
I can only receive

## Possible Fix
-

## Steps to Reproduce
1. Fresh install of the container
2. Add mx record to the main domain in cloudflare

## Your Environment
* Amount of RAM available: 12GB
* Mailserver version used: Newest as of today
* Docker version used: newest as of today
* Environment settings relevant to the config: I enabled pop3 but that's it
* Any relevant stack traces ("Full trace" preferred): (where can i find this?)

**Comment by johansmitsnl** [comment]
Check the output logs of your docker when sending information
Your ISP might block port 25

**Comment by Wqrld** [comment]
Output looks fine, no errors. I am hosting on OVH with port 25 unblocked everywhere

**Comment by johansmitsnl** [comment]
Can you post some log?
When sending for example.

**Comment by Wqrld** [comment]
https://hastebin.com/xozafocoyu.php

**Comment by johansmitsnl** [comment]
What does the log says?

* Did you send a email from your own client to your server, did you use the SMTP port 587?
* Is it a email from outside your domain receiving?
* There is only one email delivered to `amavis@mail.feroxmc.ga`.
* Why is you amavis restarting?

please write the flow according with the log file so we can check it

**Comment by Wqrld** [comment]
This seemed to be a multi-part issue with one DNS and 2: The windows mail client being weird.
