### ISSUE TITLE
config in docker volume not working

### ISSUE THREAD

**Issue by GiganteX** [tomav/docker-mailserver#1014]
So I created a volume like so;
docker volume create mailserver_data

but using setup sh like this doesn't work:
./setup.sh  -p mailserver_data email add test@test.se

as the setup script expects the CONFIG_PATH to be a local folder or a mount (not volume)

this is how the container should be run with a volume:

docker run -v mailserver_data:/tmp/docker-mailserver...
or preferably
docker run --mount source=mailserver_data,target=/tmp/docker-mailserver...

I could get it working by modifying the setup.sh script but it would be nice if it would support volumes.

**Comment by johansmitsnl** [comment]
Can you provide a PR with the fix?

**Comment by johansmitsnl** [comment]
@danielpanteleit can you provide a PR?
