### ISSUE TITLE
AMAZING SCRIPT.... took me 15 minutes to have it running.

### ISSUE THREAD

**Issue by inglesuniversal** [tomav/docker-mailserver#1015]
Now, since I was in such a hurry, i only set up the DNS to target to that particular server from AWS.

I am only using the INBOX per say, since on ThunderBird for Mac the outgoing email is setup through AWS SES.

I am getting some warning on my iPhone about NOT having the proper certificate for the incoming email... Where should I look for to get that info.

Thanks

**Comment by johansmitsnl** [comment]
Check the wiki: https://github.com/tomav/docker-mailserver/wiki/Configure-SSL
