### ISSUE TITLE
Problem recieving mail

### ISSUE THREAD

**Issue by GiganteX** [tomav/docker-mailserver#1016]
I have setup tvial/docker-mailserver. Created an account firstname.lastname@domain.com with the setup script. Did the DKIM thing.

Could not recieve mail due to "User unknown in local recipient table"

So I created a local user firstname.lastname@domain.com

Still got the same response.

I then created local user firstname.lastname (without the @domain.com)

That went better, I can see "delivered to mailbox" in the logs.

But I can't see it in the mailbox. 

I docker exec into the container, in /tmp/docker-mailserver.

In the subfolder /domain.com/firstname.lastname@domain.com folder I can see the catalog structure but no emails.

But there is a file in /tmp/docker-mailserver/ named firstname.lastname that contains the emails I sent to the account. But the account is firstname.lastname@domain.com so what's going on?

How can I get my emails?

**Comment by newmindJP** [comment]
I have exactly the same issue - I created an alias of "postmaster@domain,com" to "username@domain.com"  - with this I get the error <username@domain.com>: unkown user "username"
It seems that the domain is somehow filtered - I can sent emails, but cannot receive - receiving always leads to an error.
Can it be an issue that my hostname "host.domain.com" is also my email domain "first,last@host.domain.com"?

**Comment by johansmitsnl** [comment]
Please read the wiki: https://github.com/tomav/docker-mailserver/wiki/Installation-Examples
If you still encounter issues reopen this issue.

**Comment by barrer** [comment]
@GiganteX 
@newmindJP 
@johansmitsnl 
Here you can solve your problem: https://github.com/tomav/docker-mailserver/issues/968#issuecomment-409102650. Because the author did not try to send the same domain mailbox to each other.
