### ISSUE TITLE
How to disable SPF?

### ISSUE THREAD

**Issue by GiganteX** [tomav/docker-mailserver#1017]
When sending to my account from another mailsystem I get this:
domain.com couldn't confirm that your message was sent from a trusted location.

and 

"This error occurs when Sender Policy Framework (SPF) validation for the sender's domain fails. If you're the sender's email admin, make sure the SPF records for your domain at your domain registrar are set up correctly. Office 365 supports only one SPF record (a TXT record that defines SPF) for your domain. Include the following domain name: spf.protection.outlook.com. If you have a hybrid configuration (some mailboxes in the cloud, and some mailboxes on premises) or if you're an Exchange Online Protection standalone customer, add the outbound IP address of your on-premises servers to the TXT record."

So that's a problem with sending server. Well, changing anything there is not an option. 

I need to fix this on my tvial/docker-mailserver installation, by disabling this SPF check.

How can I do that?

**Comment by johansmitsnl** [comment]
It can't be disabled by a param.

You can do a override I guess: https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration
