### ISSUE TITLE
Relaying mail on port 465. requires wrappermode?

### ISSUE THREAD

**Issue by GiganteX** [tomav/docker-mailserver#1018]
I am using tvial/docker-mailserver.

My ISP has blocked port 25 so I am sending through their mailserver. Getting this;

Aug  8 16:07:57 6a6b607d4e74 postfix/smtp[1621]: SMTPS wrappermode (TCP port 465) requires setting "smtp_tls_wrappermode = yes", and "smtp_tls_security_level = encrypt" (or stronger)

Where do I edit these values? They can not be sent into the container using an environment variable?

**Comment by johansmitsnl** [comment]
Please read: https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration
