### ISSUE TITLE
First setup with docker-mailserver: receiving and sending mail fails. 

### ISSUE THREAD

**Issue by kzpm** [tomav/docker-mailserver#1022]
## Context
After running the docker cmd `docker up -d mail` and setting up the mailconfiguration parameters in Sylpheed mailclient, the mailclient is not able to receive or send mails.

I could not figure out to debug the problem, however every fraction of a second `docker logs mail` shows the following output in very rapid iterations:
```
2018-08-18 12:09:52,967 INFO success: saslauthd_pam entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-08-18 12:09:52,971 INFO success: fetchmail entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-08-18 12:09:52,971 INFO exited: saslauthd_pam (exit status 0; expected)
2018-08-18 12:09:52,973 INFO spawned: 'saslauthd_pam' with pid 32411
2018-08-18 12:09:52,973 INFO exited: fetchmail (exit status 5; not expected)
2018-08-18 12:09:52,975 INFO spawned: 'fetchmail' with pid 32412

```
The command `hostname` returns `mx`, the command `hostname -f` returns `mx.example.com`

I registered the domain example.com, with the following DNS settings:
![dns_setup](https://user-images.githubusercontent.com/42388719/44300063-519e9c00-a2f0-11e8-803b-9e620e28bcb9.png)

Maybe you noticed in the dns settings I used the docker autodiscovery container created by @johansmitsnl.
The IP address 1.2.3.4 resolves to my public ip, as assigned by my ISP.

## Expected Behavior
I was expecting to receive and send mails.

## Actual Behavior
When I tried to setup the mailaccount, I am not able to rebuild the folder tree (message: Rebuilding of the folder tree failed.), which is necessary for setting up an account in Sylpheed.

`docker inspect mymailserver` shows 

```
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "3e498ff8816481fce47b85eadcba05884735b2ef7d779c3b16038e5280212b15",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/3e498ff88164",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "mailserver_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "987d99ccce99",
                        "mail"
                    ],
                    "NetworkID": "bbe8292f5818cdfd41d5b8a30edfc2af8008fbfc68af3687728909f9646fa12d",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }

```

## Possible Fix
I don't know, maybe it helps when I install Postfix, Dovecot onto my system? But I think that is opposed to the art of containerization..?

## Steps to Reproduce

1. Set up mailaccount in client
2. Try to connect

## Your Environment

- Debian 9 Stretch

* Amount of RAM available:
8 gB

* Mailserver version used:
I can't say. `docker inspect mymailserver | grep Postfix` did not provide versioning details about Postfix

* Docker version used:

1. Docker version 18.06.0-ce, build 0ffa825
2. com.docker.compose.version": "1.22.0"

* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by johansmitsnl** [comment]
Sounds like mis configuration. Please read: https://github.com/tomav/docker-mailserver/wiki/Installation-Examples
