### ISSUE TITLE
Plain text access failed

### ISSUE THREAD

**Issue by libyron** [tomav/docker-mailserver#1026]
Hi, I've already added 

ssl = yes
disable_plaintext_auth=no

to config/dovecot.cf.

But I still can't get access to mail server.

I got log "A002 NO [PRIVACYREQUIRED] Plaintext authentication disallowed on non-secure (SSL/TLS) connections."

Someone help?

**Comment by johansmitsnl** [comment]
I don't know if this case could work. Use SSL always to secure your connection!
