### ISSUE TITLE
mailserver forced exited

### ISSUE THREAD

**Issue by variamus** [tomav/docker-mailserver#1027]
## Context
Whenever I run the mailserver docker, supervisorctl reports me that every services are stopped and mailserver is stopped as soon as it is launched:
amavis                           STOPPED   Not started
changedetector                   STOPPED   Not started
clamav                           STOPPED   Not started
cron                             STOPPED   Not started
dovecot                          STOPPED   Not started
fail2ban                         STOPPED   Not started
fetchmail                        STOPPED   Not started
filebeat                         STOPPED   Not started
mailserver                       EXITED    Aug 23 03:08 PM
opendkim                         STOPPED   Not started
opendmarc                        STOPPED   Not started
postfix                          STOPPED   Not started
postgrey                         STOPPED   Not started
postsrsd                         STOPPED   Not started
rsyslog                          STOPPED   Not started
saslauthd_ldap                   STOPPED   Not started
saslauthd_mysql                  STOPPED   Not started
saslauthd_pam                    STOPPED   Not started
saslauthd_rimap                  STOPPED   Not started
saslauthd_shadow                 STOPPED   Not started

## Expected Behavior
Mailserver should be running

## Actual Behavior
Mailserver is forced exited

## Your Environment

* Amount of RAM available: 2GB
* Mailserver version used: docker-mailserver/latest
* Docker version used: Docker version 18.06.0-ce, build 0ffa825

## Possible answers to you issue
* ClamAV keeps restarting:
  https://github.com/tomav/docker-mailserver#requirements

* Email seen as spam:
  https://github.com/tomav/docker-mailserver/wiki/Configure-SPF
  https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM

* Creating new domains and accounts
  https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts

* Use a relay mail server
  https://github.com/tomav/docker-mailserver/wiki/Configure-AWS-SES
  The variable name can be used for other email servers.

* FAQ and tips
  https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips

* And the WIKI
  https://github.com/tomav/docker-mailserver/wiki

* Open issues
  https://github.com/tomav/docker-mailserver/issues
-->

**Comment by johansmitsnl** [comment]
The uid can't be set and thats why you have these errors.
This is NFS related.
