### ISSUE TITLE
Mailbox quota

### ISSUE THREAD

**Issue by Kuppit** [tomav/docker-mailserver#1028]
Hi,
Is it possible to add a quota to a mailbox?

**Comment by johansmitsnl** [comment]
No there is not, could you provide a PR?

**Comment by robbalmbra** [comment]
I'm trying to work this out as well however it may be easier than I thought, you could add something like `userdb_quota_rule=*:storage=200M` to /etc/dovecot/userdb for each user, or alternatively alter the setup.sh script to allow the use of defining quota when setting up or updating a user account.

The script `/usr/local/bin/check-for-changes.sh` creates userdb, so you could define some quota rules within that. https://github.com/tomav/docker-mailserver/blob/7dbc96e908c579fb2cbfa18db08d980e72aea759/target/check-for-changes.sh#L104

Specifically refer to https://wiki2.dovecot.org/Quota/Configuration.

**Comment by wernerfred** [comment]
Is there any progress/PR from your side @robbalmbra?
Would really appreciate using quotas. Is there currently any chance to see the size of a mailbox beside using a terminal to find out the size of the corresponding directory?

**Comment by robbalmbra** [comment]
Yes, I did work it out. By using sql as the method of storing username and password. I was able to define individual quotas for each user. I altered files from a Pull Request, though I can't seem to find it, looks like its been deleted

**Comment by robbalmbra** [comment]
Add mysql through this fork https://github.com/julianhille/docker-mailserver/tree/dovecot-mysql

I would suggest diffing it (https://github.com/tomav/docker-mailserver/compare/master...julianhille:dovecot-mysql) and you'll be able to define quotas, username, passwords, etc.. in a mysql db. Or just pull it and use that.

**Comment by erik-wramner** [comment]
Well, the referenced fork is a bit outdated (110 commits behind) and this image is not using SQL, so if someone could implement quotas within the current framework (i.e. with the config files) that would be nice. Dovecot does support quotas with extra attributes in the password file.

**Comment by robbalmbra** [comment]
Yes that's why I added the changes manually, works fine while running the lates version of docker-mailserver

**Comment by youtous** [comment]
Resolved with https://github.com/tomav/docker-mailserver/pull/1469.
