### ISSUE TITLE
can't volume postfix-main.cf

### ISSUE THREAD

**Issue by lilarcor** [tomav/docker-mailserver#1030]
I use docker-compose and try to map the ./docker/mail/postfix:/etc/postfix , so I can edit /etc/postfix/main.cf to add 192.168.0.0/16 to mynetwork which can allow my other internal hosts to relay mail, but I got so many errors saying "system can't create /etc/postfix

I guess the folder hasn't been existed when starting up. Is it a bug ?

**Comment by johansmitsnl** [comment]
This is not supported, it depends on a "clean" postfix dir.
Read the wiki for modifying https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration

**Comment by lilarcor** [comment]
Thank you. According to the wiki, https://github.com/tomav/docker-mailserver/wiki/Override-Default-Dovecot-Configuration, it shows mapping dovecot is possible, but I also got error .
