### ISSUE TITLE
No shared cipher(postfix)

### ISSUE THREAD

**Issue by gartia** [tomav/docker-mailserver#1031]
So our system admin upgraded all our certs recently and i believe he made them more secure i'm not too sure, but  when i try to send mail from thunderbird/IOS mail app i get this error 

`mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: connect from [**userip**]
mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: SSL_accept error from [**userip**]: -1
mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:1404:
mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: lost connection after STARTTLS from [**userip**]
mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: mail    | Sep  7 18:38:01 mail postfix/submission/smtpd[5384]: disconnect from [**userip**] ehlo=1 starttls=0/1 commands=1/2`

I can send mail from outlook fine. also when i tried to send email to my self i from gmail i get this error 

`mail    | Sep  7 18:41:35 mail postfix/postscreen[5915]: CONNECT from [209.85.222.46]:44123 to [172.18.0.2]:25
mail    | Sep  7 18:41:35 mail postfix/dnsblog[5923]: addr 209.85.222.46 listed by domain list.dnswl.org as 127.0.5.0
mail    | Sep  7 18:41:35 mail postfix/dnsblog[5918]: addr 209.85.222.46 listed by domain dnsbl.sorbs.net as 127.0.0.6
mail    | Sep  7 18:41:35 mail postfix/postscreen[5915]: PASS NEW [209.85.222.46]:44123
mail    | Sep  7 18:41:35 mail postfix/smtpd[5927]: connect from mail-ua1-f46.google.com[209.85.222.46]
mail    | Sep  7 18:41:35 mail postfix/smtpd[5927]: SSL_accept error from mail-ua1-f46.google.com[209.85.222.46]: -1
mail    | Sep  7 18:41:35 mail postfix/smtpd[5927]: warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:1404:
mail    | Sep  7 18:41:35 mail postfix/smtpd[5927]: lost connection after STARTTLS from mail-ua1-f46.google.com[209.85.222.46]
mail    | Sep  7 18:41:35 mail postfix/smtpd[5927]: disconnect from mail-ua1-f46.google.com[209.85.222.46] ehlo=1 starttls=0/1 commands=1/2`

I also can get mail from internal sources such as amavis, but nothing from the outside seems to being delivered. I was seeing someone said to make 'config/postfix-main.cf', but i didn't see it their so i was going to make it myself i just don't know too much of what to put in it.

**Comment by mwlczk** [comment]
Are you using a macOS? Your apps are using the built-in SSL-library. Which is ancient unless you are on the last major release. 
Older macOSes are not capable of anything better than TLS1.0

**Comment by johansmitsnl** [comment]
Checkout the changelog: https://github.com/tomav/docker-mailserver/blob/master/CHANGELOG.md#500

**Comment by gartia** [comment]
Is their any examples of how to set custom ciphers or something? Like where would i put the line for customizing postfix's 'tls_high_cipherlist'

**Comment by gartia** [comment]
Okay so i can send email now i'm not too sure what i didi to fix that and i can receive email from outlook it seems like, but gmail is still a nogo...
