### ISSUE TITLE
Multiple domains cause spf problems

### ISSUE THREAD

**Issue by robbalmbra1** [tomav/docker-mailserver#1038]
## Context

I have multiple mail servers to this container. When I setup the primary server everything worked fine, spf, dkim, DMARC. I added another server and when I send an email it says received from my primary server. It therefore failea erverything.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by johansmitsnl** [comment]
Does you SPF record of the other domain contain the correct details?
You can test here if correctly set up: http://www.appmaildev.com/en/dkim

**Comment by robbalmbra1** [comment]
Yes. I’ve had this problem before on a non docker server. I do remember I had to dynamically set postfix goat name so that hosts receiving don’t get confused.

**Comment by johansmitsnl** [comment]
Thats not nessesary. Just configure the SPF correctly on the domain.

Example:
Server dns = `mail.example.com`
* domain1.com mx 10 mail.example.com
* domain2.com mx 10 mail.example.com

Both have a SPF with `v=spf1 mx -all`

That should do it. The reverse dns of the IP should match `mail.example.com`

**Comment by robbalmbra1** [comment]
Sorted. Was a configuration issue. Though DMARC isn’t applying, only on the primary domain.

**Comment by johansmitsnl** [comment]
You need to enable it for DMARC. All other domains can be supported to.
