### ISSUE TITLE
Problem with TLS

### ISSUE THREAD

**Issue by Mick00** [tomav/docker-mailserver#1050]
So I am trying to set up an STMP server using docker-mailserver. I did the setup from the README. I can receive mails successfully, but I can't send from it.

Directly after setup I tried to send an email with it, but it did not work. 

I tried to do a TLS check everything is fine except for this part:

```
  Certificate 1 of 1 in chain: Cert VALIDATION ERROR(S): self signed certificate
   So email is encrypted but the recipient domain is not verified
  Cert Hostname DOES NOT VERIFY (mail.domdom.net != d63bc82ef7ca \| DNS:d63bc82ef7ca)
  So email is encrypted but the host is not verified
```

So then I tried to configure ssl with a custom certificate like in the wiki (https://github.com/tomav/docker-mailserver/wiki/Configure-SSL), but even after a restart it still looks like the server is using a self signed certificate. I am actually not even sure if this section concerns TLS.

I am using cloudflare as DNS server and DDOS protection. I have my domain domdom.net which is routed trough their service and the mail.domdom.net domain which is not (points directly to my server). I have generated a ssl certificate for *.domdom.net (with cloudflare).

I want to set it up mainly to use it with wordpress, so I do not know if there is something more to add, but it basically always fails when I try to send email.

In the following pastebin you can see the logs of the docker at first when I try to send an email with my wordpress website and then a check with checktls, which seems to be fine.
[https://pastebin.com/b6rb7bTv](url)

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, open a PR based on the current master branch so we can review it.
