### ISSUE TITLE
new install, and email bouncing

### ISSUE THREAD

**Issue by Eli-the-Bearded** [tomav/docker-mailserver#1059]
I've just installed this following the directions and I feel like a lot of the settings could use a bit more documentation. After I first installed it, I could `telnet localhost 25` but the connection would be instantly dropped. After changing `PERMIT_DOCKER=host` to `network` that was resolved. But now if I do that and try to send email, it gets rejected.

## Context

```
root@qaz:/var/docker-mailserver# ./setup.sh email add demo@qaz.red [real-password-here]
User "demo@qaz.red" already exists
root@qaz:/var/docker-mailserver# docker-compose restart 
Restarting qazred ... done
root@qaz:/var/docker-mailserver# telnet localhost smtp
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 qaz.red ESMTP Postfix (Debian)
HELO qaz.red
250 qaz.red
MAIL From: demo@qaz.wtf
250 2.1.0 Ok
RCPT TO: demo@qaz.red
550 5.1.1 <demo@qaz.red>: Recipient address rejected: User unknown in local recipient table
QUIT
221 2.0.0 Bye
```

The mail.log has this to say:
```
Oct 19 18:30:30 mail postfix/smtpd[1373]: NOQUEUE: reject: RCPT from unknown[172.18.0.1]: 550 5.1.1 <demo@qaz.red>: Recipient address rejected: User unknown in local recipient table; from=<demo@qaz.wtf> to=<demo@qaz.red> proto=SMTP helo=<qaz.red>
```

## Expected Behavior
I expect that adding an address means it can receive email. I'm guessing, but have not inspected the setup.sh script, that it does the rough equivalent of the process here:  https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts

## Actual Behavior
Adding an address is not sufficient to receive email.

## Possible Fix

I suspect there's some documentation missing or not where I expect to find it.

## Your Environment

* Amount of RAM available: 0.5 G
* Mailserver version used: `63fe17856de6        tvial/docker-mailserver:latest   "/bin/sh -c 'supervi…"   37 hours ago        Up About a minute   0.0.0.0:25->25/tcp, 110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:587->587/tcp, 465/tcp, 995/tcp, 0.0.0.0:993->993/tcp, 4190/tcp   qazred`
* Docker version used: `Docker version 18.06.1-ce, build e68fc7a`
* Environment settings relevant to the config: https://qaz.wtf/tmp/qazred.env

**Comment by johansmitsnl** [comment]
Due to you memory, did you disable clamav?
https://github.com/tomav/docker-mailserver#requirements

**Comment by Eli-the-Bearded** [comment]
It's right there in the env file link: `ENABLE_CLAMAV=0`

That is disabled, right? The template does not document that setting. (I also rather think the symptoms of the problem are inconsistent with clamav ever being involved.)

**Comment by Eli-the-Bearded** [comment]
Nevermind. I've given up trying to use this project.

**Comment by barrer** [comment]
@Eli-the-Bearded 
This is a great project, here you can solve your problem: https://github.com/tomav/docker-mailserver/issues/968#issuecomment-409102650. Because the author did not try to send the same domain mailbox to each other.
