### ISSUE TITLE
Hit and miss mail delivery  

### ISSUE THREAD

**Issue by IwateKyle** [tomav/docker-mailserver#106]
### First
Wow, thank you for such a great contribution to those of us who want to operate their own mail servers.  I actually have gotten this to work - even though I am experiencing a problem.  I have also attached a question at the bottom.  Wasn't sure if I should have made two different issues or not.  Please advise.

### Problem - Hit and Miss mail delivery
I have a couple accounts setup in my accounts.cf  I have run the server and have successfully  received mail.  I tested by sending mail from my Gmail account.  So, I have witnessed it work.  

However, It doesn't always receive mail.  I don't know where to start testing.  

Sometimes emails take a long time to get delivered, but finally get delivered.  I'm using an email client connecting to the server using IMAP.

All of the emails have been test emails.  So, I imagine they look spam-ish.  I was wondering if spamassasin has something to do with it.  But, again, I don't know how to check.  It seems that if Spam Assassin were involved, it would put my incoming emails into a junk folder or something.  But, there is NO clue of delivery.  Any suggestions on where to begin?

### Question - Multi Domain (accounts / virtual)
I currently have two domains that I am trying to setup.  However, I discovered that the accounts.cf file will only deliver mail to domains that are the same as the registered domain in the docker-compose.yml file.  

So, I added my other domain account to virtual.  However, I had to forward my mail from a virtual account to a login account which meant that if I replied to an email, the reply-from email address wasn't the same.  Am I confusing you, yet?  Just wait.

_Example Config:_

accts:
`kyle@my_FIRST_domain.com|secret_password
`

virtual:
`kyle@my_SECOND_domain.com kyle@my_first_domain
`

_Result_
When I email to the virtual account  _SECOND_ domain, and reply to it, my reply is sent from my _FIRST_ domain.  

Is this just the way it is?  or, is there something I'm missing to complete a mail conversation to appear as though my virtual account were a real account?

I was struggling last night trying to find a way to run a reverse proxy and just run two of your mailservers, which is fine, too.  But the reverse proxy was a whole can of worms in itself.  If you want to make a reverse proxy docker, I'll definitely use it.  :)

**Comment by tomav** [comment]
Hi @IwateKyle, and thanks for using `docker-mailserver`.
Regarding your mail delivery issue, have you changed a DNS configuration recently? Few users had this problem as you can see in issues. 
If not, have a look to container logs (they're from `/var/log/mail.log`). You will see which mails `PASSED CLEAN` and also `SPAM`. 

> However, I discovered that the accounts.cf file will only deliver mail to domains
> that are the same as the registered domain in the docker-compose.yml file.

No this is wrong: `accounts.cf` can manage multi-domain as you can see in documentation and tests files. It will configure postfix for these domain names. 

Each `accounts.cf`creates a mailbox or mail user with their own mail folders.
`virtual`allow to redirect / forward other username to existing mailbox or external email address.

Hope this helps.
Let me know.

**Comment by tomav** [comment]
Close du to inactivity. Reopen if necessary.
