### ISSUE TITLE
Rapid container growth with fresh/barebones install

### ISSUE THREAD

**Issue by rwarren** [tomav/docker-mailserver#1060]
I've set up a dedicated Ubuntu 18.4 machine that *only* has docker on it for the purpose of running docker-mailserver.

After a fresh install, the mailserver works well, and is doing some light duty (It currently is only serving as the mailserver for a Jira instance to use for outgoing email notifications... maybe 1000 small notofication emails per day).

Even though the load is light, the server is growing quite quickly, as can be seen in the monitoring below (the mailserver was turned on, after installing basic server elements like docker, somewhere around the red marker line).

![image](https://user-images.githubusercontent.com/2751728/47244129-6536b380-d3c2-11e8-9378-c3a74419c8d7.png)

Nothing else is running on this machine except docker and the docker-mailserver image.

Space seems to be getting added in bursts on a regular 5 minute cycle. See the bandwidth chart below for what I mean):

![image](https://user-images.githubusercontent.com/2751728/47244789-c8c1e080-d3c4-11e8-8673-5ee29282cce4.png)

What could be causing the rapid/bursty growth?

## Your Environment
```
Ubuntu 18.04 LTS
Docker 18.06.1-ce
Docker-compose 1.22.0
3 GB RAM
```

**Comment by johansmitsnl** [comment]
You could enter the container and do a `du -sh` / and after a day or so do it again to see where the data went.

**Comment by erik-wramner** [comment]
Is this still relevant or can we close? I would guess a combination of logs and e-mails (perhaps unwanted ones).

**Comment by erik-wramner** [comment]
We would need a lot more details to find out if something is wrong, so in that case I'll close it. If you want to report it again later please check what directories or files that are responsible for the growth. You can enter the container and run `find` to locate files changed during the recent hour, for example, and `du` to find disk usage per folder. If you repeat the same `du` command once per hour it is easy to see the trend.
