### ISSUE TITLE
Mail delivery being deferred, amavis not functioning properly

### ISSUE THREAD

**Issue by ChromoX** [tomav/docker-mailserver#1062]
I can receive email no problem, but that email ends up sitting in the delivery queue forever and sometimes on a reboot a few will sneak through amavis. I have many errors that look like this:
> external1 postfix/smtp[1882]: E627978A6: to=<email@domain.com>,  
> relay=127.0.0.1[127.0.0.1]:10024, delay=284198, delays=282998/0.02/0.01/1200, dsn=4.4.2, 
> status=deferred (conversation with 127.0.0.1[127.0.0.1] timed out while sending end of data -- 
> message may be sent more than once)```

On a restart of the container I get the queue manager output saying the queue is attempting to be processed then I get
> postfix/smtpd[1175]: connect from localhost[127.0.0.1]```
> postfix/smtpd[1175]: timeout after CONNECT from localhost[127.0.0.1]
> postfix/smtpd[1175]: disconnect from localhost[127.0.0.1] commands=0/0

Sending email is no problem and goes through amavis seemingly without issue.

I've looked in all the logs I could find in ```/var/log/mail``` and ```/var/log/supervisor``` and haven't found anything of interest. Any other ideas?

The problem seemed to stem from having items in the mail queue on startup. The only way I have gotten the system working again is by clearing the state directory.

## Context

Amavis is in some sort of deadlocked state, which is preventing mail delivery. I have turned off ClamAV as I was having issues there. Sometimes with a restart of the amavis service I can get a few messages through, but it quickly halts again. 

As an aside opendkim also times out looking up a foreign DKIM key, but I can easily dig for it in the command line inside the container. ```/etc/resolv.conf``` is set to the proper DNS server. If I add ```Nameservers <name server ip>``` to the ```/etc/opendkim.conf``` file it works no problem.

## Your Environment

* Amount of RAM available: 4GB
* Mailserver version used: 6.1
* Docker version used: 18.03.1-ce
* Environment settings relevant to the config:
   - PERMIT_DOCKER = network
   - OVERRIDE_HOSTNAME = hostname.mine
   - ENABLE_CLAMAV = 0
   - ENABLE_FAIL2BAN = 1
   - ENABLE_MANAGESIEVE = 1
   - ENABLE_SPAMASSASSIN = 0
* Running in a Rancher Kubernetes environment.
* Ports mapped using docker host networking setting.

**Comment by ChromoX** [comment]
I think I found the root cause. Anytime an attachment that is an encrypted zip file tries to be sent it has the possibility to completely stop the Postfix queue. Restarting multiple times I can get all messages to run through except for messages that contain an encrypted zip file. Below are the logs from amavis:

```
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) 2822.From: <chromox@address.com>
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) lookup [local_domains] => undef, "aperson@gmail.com" does not match
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) lookup [bypass_virus_checks] => undef, "aperson@gmail.com" does not match
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) lookup [bypass_banned_checks] => undef, "aperson@gmail.com" does not match
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) lookup [bypass_spam_checks] => undef, "aperson@gmail.com" does not match
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Extracting mime components from a file
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Issued a new file name: p001
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Issued a new file name: p002
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Issued a new file name: p003
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Issued a new file name: p004
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Issued a new pseudo part: p005
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) p005 1 Content-Type: multipart/mixed
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Issued a new pseudo part: p006
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) p006 1/1 Content-Type: multipart/alternative
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Charging 395 bytes to remaining quota 314572800 (out of 314572800, (0%)) - by mime_decode
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) p001 1/1/1 Content-Type: text/plain, size: 395 B, name: 
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Charging 1373 bytes to remaining quota 314572405 (out of 314572800, (0%)) - by mime_decode
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) p002 1/1/2 Content-Type: text/html, size: 1373 B, name: 
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Charging 468321 bytes to remaining quota 314571032 (out of 314572800, (0%)) - by mime_decode
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) p003 1/2 Content-Type: application/zip, size: 468321 B, name:  SomeEncryptedZipFile.zip
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Charging 2460 bytes to remaining quota 314102711 (out of 314572800, (0%)) - by mime_decode
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) p004 1/3 Content-Type: application/pgp-keys, size: 2460 B, name: pEpkey.asc
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) decode_parts: level=1, #parts=6 : p001, p002, p003, p004, p005, ...
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) lookup [map_full_type_to_short_type] => true,  "ASCII text" matches, result="asc", matching_key="(?^i:^(ASCII|text)\\b)"
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) File-type of p001: ASCII text; (asc)
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) lookup [map_full_type_to_short_type] => true,  "HTML document, ASCII text" matches, result="asc", matching_key="(?^i:\\btext\\b)"
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) File-type of p002: HTML document, ASCII text; (asc)
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) lookup [map_full_type_to_short_type] => true,  "Zip archive data, at least v2.0 to extract" matches, result="zip", matching_key="(?^i:^Zip archive\\b)"
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) File-type of p003: Zip archive data, at least v2.0 to extract; (zip)
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) lookup [map_full_type_to_short_type] => true,  "PGP public key block Public-Key (old)" matches, result="dat", matching_key="(?^:^)"
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) File-type of p004: PGP public key block Public-Key (old); (dat)
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) decompose_part: p001 - atomic
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) decompose_part: p002 - atomic
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Expanding 7-Zip archive p003
Oct 31 18:54:54 mail-0 amavis[28059]: (28059-02) Charging 515241 bytes to remaining quota 314100251 (out of 314572800, (0%)) - by do_7zip-pre
Oct 31 18:59:54 mail-0 postfix/smtpd[28248]: timeout after END-OF-MESSAGE from localhost[127.0.0.1]
Oct 31 18:59:54 mail-0 postfix/smtpd[28248]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 commands=4
```

**Comment by johansmitsnl** [comment]
Make sure when you stop and start the container that you remove it. A stop start might reuse the pid's that where left and that might cause an issue.

**Comment by ChromoX** [comment]
@johansmitsnl Thanks for the idea.

I've been simply jumping inside the container and manually restarting amavis, and using postqueue, and postsuper to get things moving when they stop. I was looking for more permanent fixes if they exist

**Comment by johansmitsnl** [comment]
The docker images does not get restarted somehow or the machines is rebooted?
Do you what causes this?

**Comment by ChromoX** [comment]
@johansmitsnl I'm a little confused as to what you are asking.

I jump inside the container to restart because I've made some modifications to the Docker container to increase amavis logging and so I don't want to destroy the container. But on the containers own it never gets restarted automatically or fails it just simply continues to act like nothing is wrong, but your postfix queue is just growing over time.

> Do you [know?] what causes this?

Anytime a message containing an encrypted zip file tries to be sent it has the possibility to completely stop the Postfix queue. Restarting multiple times I can get all messages to run through except for messages that contain an encrypted zip file. The log file is in my second comment of the thread above.

**Comment by johansmitsnl** [comment]
Could it be a lack of memory?
What does the log of amavis says when such email arrives?

**Comment by ChromoX** [comment]
@johansmitsnl This docker container has 4GB dedicated to it. The zip file that was capable of stopping everything is 450 bytes. The log of amavis processing that zip file is above in my second comment.

**Comment by erik-wramner** [comment]
@ChromoX is this still relevant, or can we close the issue? Did you report it to amavis?

**Comment by ChromoX** [comment]
I have not run into this issue again. I did not report to amavis.
