### ISSUE TITLE
Send mails through container on server

### ISSUE THREAD

**Issue by futur22de** [tomav/docker-mailserver#1064]
Hello,

I'm a noob, so sorry for that. But I can send and receive mails using Thunderbird. But other applications (PHP, crontab etc.) on the server cannot send mails. How can I use the docker container for sending mails from the server globally?

Thanks!

**Comment by mborko** [comment]
Have you checked your ``/etc/postfix/main.cf`` in the docker instance? I was missing those two lines:

```bash
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
```
Hopefully the admins can check the setup process and fix this issue!

**Comment by johansmitsnl** [comment]
Do you use the correct port 587 for email delivery?

**Comment by mborko** [comment]
Yes, I do! Have you checked why those two lines are not included in the ``/etc/postfix/main.cf`` file after the setup process?

**Comment by erik-wramner** [comment]
@futur22de (and @mborko) can we close this or is it still relevant?

As far as I can tell the main.cf file works as is in the current image versions (latest/stable). The original issue sounds more like missing authentication or trust to me. If the problem remains, please post the relevant parts of the configuration as well as an example of code that fails to send mail and the mail logs for the failure.

**Comment by futur22de** [comment]
@erik-wramner: I don't use this anymore.
