### ISSUE TITLE
configomat.sh missing

### ISSUE THREAD

**Issue by peter-hartmann** [tomav/docker-mailserver#1066]
## Context
```Dockerfile``` and ```start-mailserver.sh``` both reference ```target/configomat.sh``` but there is no such file.  Running ```docker build  .``` fails.

I'd expect ```docker build  .``` creates the final image without getting stuck but this error occurs instead:
```
Step 46/52 : COPY ./target/check-for-changes.sh ./target/start-mailserver.sh ./target/fail2ban-wrapper.sh ./target/postfix-wrapper.sh ./target/postsrsd-wrapper.sh ./target/docker-configomat/configomat.sh /usr/local/bin/
lstat target/docker-configomat/configomat.sh: no such file or directory
```

**Am I missing anything?**

Steps to Reproduce:
1. ```git clone [repo]```
2. ```docker build docker-mailserver```

On Ubuntu 16.04.5 LTS.

**Comment by johansmitsnl** [comment]
You have to initialize the git submodules. Use `git clone --recurse-submodules`.

**Comment by peter-hartmann** [comment]
Yes that did the trick, thx!
