### ISSUE TITLE
Fetchmail configuration

### ISSUE THREAD

**Issue by tbool** [tomav/docker-mailserver#1067]
After upgrading docker-mailserver from version 2.3 to version 6.1 I noticed that there are now quite some additional log-messages in mail.log coming from Fetchmail. In version 2.3 I got no log-messages at all from Fetchmail, but in version 6.1 I get about 30 log-messages per mailaccount that it checks.

I have Fetchmail fetching the mails from 3 external mail-accounts, checking them every minute. This gives me now about 100 log-messages in mail.log every minute. This makes the mail log rather useless now, as it consists for 99% of almost identical Fetchmail messages.

I saw in supervisor-app.conf that Fetchmail is now run in "Verbose mode". Running Fetchmail in verbose mode may be usefull when debugging Fetchmail, or at initial setup, but once everything works there is no use for this anymore.

So I would like to request that the -v option is dropped from the Fetchmail startup command in supervisor-app.conf, or that at least there comes a possibility for the user to switch this mode on or off.

**Comment by johansmitsnl** [comment]
Could you provide a PR for this?

**Comment by AlbrechtL** [comment]
I have the same issue. Is there is any workaround?

**Comment by tbool** [comment]
I do have a solution / workaround that I am using myself that works pretty well. I have defined a new environment variable FETCHMAIL_VERBOSE, which by default is set to 0 causing supervisor to start Fetchmail in non-verbose mode, and when the user sets it to 1 supervisor will start Fetchmail in verbose mode.

I have the files available if anybody wants them. I just don't know how to create a PR...

**Comment by dmcgrandle** [comment]
It's not tremendously difficult.  Good guide here:

https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940

:D

**Comment by AlbrechtL** [comment]
@tbool I can do the pull request if you like. Can you provide the files that you mentioned, please?

**Comment by barcomoon** [comment]
Just want to mention that I’m also interested in the solution / workaround to avoid the additional fetchmail logging.

**Comment by aendeavor** [comment]
What's the status @tbool ?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
