### ISSUE TITLE
LDAP_START_TLS and DOVECOT_TLS not having default values?

### ISSUE THREAD

**Issue by mpanneck** [tomav/docker-mailserver#1071]
As written in the README [LDAP_START_TLS](https://github.com/tomav/docker-mailserver#ldap_start_tls) and [DOVECOT_TLS](https://github.com/tomav/docker-mailserver#dovecot_tls) should have default values when they have empty values in .env file.
Actually they have either no default value or an invalid default value.

If you empty the value of DOVECOT_TLS in the .env file and start the docker-container with docker-compose you get the following error when some user wants to connect:
`mail    | Nov  2 03:40:56 mail dovecot: auth: Fatal: ldap /etc/dovecot/dovecot-ldap.conf.ext: Error in configuration file /etc/dovecot/dovecot-ldap.conf.ext line 6: Invalid boolean`

dovecot-ldap.conf.ext looks like this:
1. `base = ou=users,dc=example,dc=com`
2. `default_pass_scheme = SSHA`
3. `dn = cn=admin,dc=example,dc=com`
4. `dnpass = 12345678`
5. `hosts = openldap`
6. `tls =`
7. `ldap_version        = 3`
8. `pass_attrs          = uniqueIdentifier=user,userPassword=password`
9. `pass_filter = (&(objectClass=PostfixBookMailAccount)(uid=%n))`
10. `user_attrs          = mailHomeDirectory=home,mailUidNumber=uid,mailGidNumber=gid,mailStorageDirectory=mail`
11. `user_filter = (&(objectClass=PostfixBookMailAccount)(uid=%n))`

As you can see in line 6 there is missing a value. It should be either yes or no - not empty.

Currently you can fix this by commenting out the env var (DOVECOT_TLS) in docker-compose.yml; then line 6 looks like this:
`tls = no`
Of cause you can set env var DOVECOT_TLS explicitly to *yes* or *no* which will cause the config file to have a valid value.

Same happening for LDAP_START_TLS (just in another file).

**Comment by johansmitsnl** [comment]
Could you provide a PR for this?
