### ISSUE TITLE
Enable_Managesieve does not work

### ISSUE THREAD

**Issue by tamueller** [tomav/docker-mailserver#1077]
Hi just set up my mailserver and got things to work. However, when i add ENABLE_MANAGESIEVE=1 to my .env file and restart the image, managesieve does not work.

When i use docker ps it seems to route port 4190, but when i telnet to 4190 i get a connection refused. I temporarily disabled the firewall, but the problem persists. Telnet (and imap) to 143 works fine.

This is a pretty fresh installation, so i don't have any dovecot.cf file in my config folder.

I also looked in /var/log/mail but couldn't find any helpful messages. Is there any more info i could provide to help?

Thanks for helping me :-)

**Comment by tamueller** [comment]
Ah, never mind..i found out that i also have to add the port to the docker-compose.yml. Would it make sense to add a short warning to the documentation in .env that the port still needs to be added, or add the port automatically?

**Comment by johansmitsnl** [comment]
You can create a PR to improve documentation. It can't open the port automatically.

**Comment by wernerfred** [comment]
The corresponding [Wiki Entry](https://github.com/tomav/docker-mailserver/wiki/Configure-Sieve-filters#manage-sieve) has exactly that point of information:

>ManageSieve runs on port ```4190``` and needs to be enabled using the ```ENABLE_MANAGESIEVE=1``` environment variable.
>
> ```
> (docker-compose.yml)
> ports:
>  - ...
>  - "4190:4190"
> environment:
>  - ...
>  - ENABLE_MANAGESIEVE=1
> ```

Can this issue be closed then or would you like to update the readme nevertheless?
