### ISSUE TITLE
Password prompt of `setup.sh email update` and `setup email add` without immediate password argument do not escape password correctly.

### ISSUE THREAD

**Issue by ksze** [tomav/docker-mailserver#1081]
Calling `setup.sh email update <address>` or `setup.sh email add <address>`, without an immediate password argument, will cause a non-echoing password prompt to be shown. However, a password that is input into that prompt is not escaped correctly.

## Context
I initially added an email account by running `setup.sh email add 'foo@example'`, which showed me a non-echoing password prompt. I typed a password that contains the "`\"`" sequence of characters - e.g. "`foo\"bar`". When I tried to login to that e-mail account, I couldn't. I thought I made a typo at the `setup.sh` password prompt, so I ran `setup.sh email update 'foo@example.com'`, without an immediate password argument. At the password prompt, I re-typed the same password, but I still couldn't login.

## Expected Behavior
Be able to log with the "`foo\"bar`" password afterwards.

## Actual Behavior
I couldn't login with "`foo\"bar`". I had to use "`foo"bar`" instead.

Suspecting that it's a string escape issue, I ran `setup.sh email update 'foo@example.com'` again, but inputting "`foo\\\"bar`" instead this time. Then I was able to login using the "`foo\"bar`" password.

## Possible Fix
Properly escape the input of that prompt. If that's not an option, maybe document it somewhere.

**Comment by 501st-alpha1** [comment]
I've hit the same issue.  I'll note that escaping the backslash seemed to fix it; I didn't have to escape any other characters.  (In your example, `foo\\"bar` may work.)  [Obligatory xkcd.](http://xkcd.com/1638)

**Comment by aendeavor** [comment]
`setup.sh` has been reworked, though I'm not sure this issue was resolved. Could you please reach back to me with this matter @ksze or @501st-alpha1 ?

**Comment by aendeavor** [comment]
This should have been taken care of by #1601 where I refactored `setup.sh`. Please re-open this issue if the issue still exists,
