### ISSUE TITLE
Missing /etc/postfix/vhost

### ISSUE THREAD

**Issue by oliversturm** [tomav/docker-mailserver#1082]
I can see amavis dying and being restarted endlessly:

```
2018-11-14 14:38:42,795 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-11-14 14:38:42,806 INFO exited: amavis (exit status 2; expected)
2018-11-14 14:38:43,811 INFO spawned: 'amavis' with pid 2830
2018-11-14 14:38:44,254 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-11-14 14:38:44,268 INFO exited: amavis (exit status 2; expected)
2018-11-14 14:38:45,235 INFO spawned: 'amavis' with pid 2844
```

In `/var/log/supervisor/amavis.log` I see this:

```
Error in config file "/etc/amavis/conf.d/60-dms_default_config": Can't open file /etc/postfix/vhost for reading: No such file or directory at /usr/sbin/amavisd-new line 4204.
```

`/etc/postfix/vhost` does not exist.

I suspect this has to do with my specific setup. I have SMTP_ONLY=1, and I'm also not using LDAP. I'm mentioning these because I checked `start-mailserver.sh` and it seems to me that a `/tmp/vhost` file is only created if dovecot or ldap are used (or in some scenario involving an alias setup I don't have).

I'm not sure why amavis requires this file. I also don't think I really need amavis - I have clamav and spamassassin deactivated, but I don't see a way to switch off amavis. In any case I guess the scenario I have is an edge case and if amavis requires `/etc/postfix/vhost`, it should probably be created. Bug?

**Comment by rroblik** [comment]
Simple workaround when using `SMTP_ONLY=1` :+1: 
On host 
```bash
touch empty
```

Then mount this file as a volume as `./empty:/etc/postfix/vhost` (in docker-compose file or in command line)

Amavis stop to exit itself with a status `2` :)

**Comment by johansmitsnl** [comment]
@rroblik does this sounds like a real fix?
If so could you make a PR to add this to the startup script?

**Comment by rroblik** [comment]
@johansmitsnl No I don't think that is a real fix, just a workaround...
I saw some others probleme when enabling `SMTP_ONLY` ; with auth, notably...

**Comment by oliversturm** [comment]
FWIW, I'm running my system now  with SMTP_ONLY=1 and I simply created my own dockerfile that adds `/etc/postfix/vhost` with the domain name inside. The server doesn't use any auth mechanisms so I can't speak to issues in that area, but everything else seems to work correctly.

**Comment by robertheessels** [comment]
With SMTP_ONLY=1 on, I struggled for 7 hours to get it all working. (And I'm still happy with this repo and thankful for all the hard work, guys).

It is absolutely essential that you add /etc/postfix/vhost somehow, otherwise Postfix will not work.
For example, create a local empty file postfix_vhost and then add to docker-compose.yml:
```
     volumes:
    - ./postfix_vhost:/etc/postfix/vhost
```

Also the only way I got authentication working is by using SASL rimap. In .env:
```
ENABLE_SASLAUTHD=1
SASLAUTHD_MECHANISMS=rimap
SASLAUTHD_MECH_OPTIONS=<the IP of my imap server>
```
And then using credentials that are valid on my imap server.

**Comment by erik-wramner** [comment]
@oliversturm, @robertheessels, is this still a problem with the latest image? If so I'd like to classify it as a bug and fix it. If not I'd like to close the issue.

There are tests for SMTP_ONLY and I know there are people using SMTP_ONLY so it can't be all broken, but the tests don't cover everything. Perhaps they don't verify amavis.

**Comment by oliversturm** [comment]
The specific issue is fixed - with the latest image, using my existing setup, I get `/etc/post/vhost` created without any tricks. 

Incidentally I have now encountered authentication issues, as reported in #1247

**Comment by erik-wramner** [comment]
Good, then I'll close this. Thanks!
