### ISSUE TITLE
Empty SSL_TYPE environment variable doesn't disable SSL

### ISSUE THREAD

**Issue by green-anger** [tomav/docker-mailserver#1083]
## Context
Greetings. I'm not an expert in networks and stuff like DNS, SSL/TLS, Postfix, Dovecot, etc. So I was trying to play with the mail server container in my home-brewed lan server with no fancy security stuff. And I disabled as much as I could with a target on plain unsecured password "protection".

## Expected Behavior
Setting `SSL_TYPE=` in `docker-compose.yml` will allow to use plain unsecured password.

## Actual Behavior
Server refuses login attempts, it just aborts connection.

## Possible Fix
Update description/wiki to reflect current behavior.

## Steps to Reproduce
Just follow the [README.md](https://github.com/tomav/docker-mailserver/blob/master/README.md).
Update `docker-compose.yml` with:
```yaml
environment:
  - ENABLE_SPAMASSASSIN=0
  - ENABLE_CLAMAV=0
  - ENABLE_FAIL2BAN=0
  - ENABLE_POSTGREY=0
  - ONE_DIR=1
  - DMS_DEBUG=1
  - SSL_TYPE=
  - ENABLE_SRS=0
```

## Your Environment

* Amount of RAM available: ~5G
* Mailserver version used:  release-v6.1.0
* Docker version used: 18.09.0, build 4d60db4
* Environment settings relevant to the config:

## Steps to get it working
Yes, there is a wiki section on [plain text access](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL#plain-text-access) which I overlooked in the beginning and overrode two dovecot config files `10-auth.conf` and `10-ssl.conf` with:
```
ssl = no
disable_plaintext_auth=no
```

## Thoughts
My point is that README.md is the first place the user will see and information there should be as accurate as possible. Currently https://github.com/tomav/docker-mailserver/blob/0fb4a6d082cc0a3c8a5d3ff6193d1032329d11d4/target/start-mailserver.sh#L855-L856
has no default option, so emptying SSL_TYPE does nothing. You have to manually disable SSL.

## Off topic
While we're there, I'm not a native English speaker, but I believe there's a typo in [SSL_TYPE section](https://github.com/tomav/docker-mailserver/blob/master/README.md#ssl_type): `manual => Let's you manually specify...` should have `Let you` or maybe even better `Allow you`.
Just didn't want to raise a separate issue on such a small matter.

**Comment by johansmitsnl** [comment]
These days SSL certificates are free (letsencrypt) and securing the internet with TLS makes it a lot better. So by security and privacy first the project focus on this by default.

It seems you have some debugging skils, could you provide a PR for the `SSL_TYPE = disabled` option?

You can include the README improvement to.

**Comment by green-anger** [comment]
> These days SSL certificates are free (letsencrypt) and securing the internet with TLS makes it a lot better. So by security and privacy first the project focus on this by default.

I totally agree with you. My point it that for a person with insignificant skills in mail server field (like myself) it's too complicated to get it all working in one go. I definitely aim to have my personal secure mail server with SSL/TLS. But complicated work must be done in small steps and having insecure plain password server is the first of them.

> It seems you have some debugging skils, could you provide a PR for the `SSL_TYPE = disabled` option?

Well, I think a try will not harm and you will just reject if it proves to be rubbish. But clarification is needed. Do you want to get `start-mailserver.sh` updated that will include modified `10-ssl.conf` for Dovecot with `disable_plaintext_auth=no` field? Or did you mean something different?

> You can include the README improvement to.

That I can do easily and include in the same PR when we've agreed on exact changes.

**Comment by johansmitsnl** [comment]
The `start-mailserver.sh` does the checking and manipulation.
You can do the proper manipulation of the files needed for the solution. I'll review them and request changes if needed.

**Comment by green-anger** [comment]
OK, deal.
