### ISSUE TITLE
Problem connecting, sending, receiving mails 

### ISSUE THREAD

**Issue by Issvn** [tomav/docker-mailserver#1086]
Hi !, 
Actually I've some problems about the connection t omy mailserver using Thunderbird. 
When I wanna send a mail through my personnal email adress, the result is a 502 Bad Gateway error.

I've generated the dkim key and added to my domain name provider (OVH) but I'm blocked, if someone can help me I'll be happy.
Thanks in advance.
(sorry if my english isn't correct at 100%)

**Comment by johansmitsnl** [comment]
Provide some proper logging and maybe we can assist.
