### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by kr0gh** [tomav/docker-mailserver#1089]
Not sure where to post this - but I have a question regarding the functionality.

Are there any rate limiting on the outgoing flow? I need to conduct a (legal) phishing test, but I want to get it right the first time, and am a bit worried that half my mails are going to be blocked.

**Comment by johansmitsnl** [comment]
No rate limiting available.

**Comment by kr0gh** [comment]
Meaning, there is no limits defined per. default, which is a positive thing i my scenario?

**Comment by johansmitsnl** [comment]
No rate limiting in any situation. The only limit is the hardware and internet connection.
