### ISSUE TITLE
postfix changes the domain to the primary one and thus the cert failed

### ISSUE THREAD

**Issue by helmutundarnold** [tomav/docker-mailserver#1090]
postfix changes the domain to the primary one and thus the cert failed
## Context

When I run  `posttls-finger example2.com` i can see that 
`
posttls-finger: < 220 2.0.0 Ready to start TLS
posttls-finger: mail.example2.com[123.123.123.123]:25: subjectAltName: mail.example1.com
posttls-finger: mail.example2.com[123.123.123.123]:25 CommonName mail.example1.com
`
So it looks like incoming connects with example2.com will be redirected to mail.example1.com  by the function **subjectAltName**.  And thus the sender cert example2.com ist tls-handshaked against example1.com which failed. 

I've setup 2 domains example1.com example2.com, having same ip, but different MX-Records. Certs create with certbot. Certification for exampl1.com - the primary is working properly. Mailboxes from example2.com are responding and working fine - but only if accepting the security-exception.
`
dig -t MX exampel1.com
example1.com.	86400	IN	MX	100 mail.example1.com.

dig -t MX example2.com
example2.com.	5365	IN	MX	100 mail.example2.com

server:/etc/postfix# grep virtual_mailbox_domains main.cf
virtual_mailbox_domains = /etc/postfix/vhost

server:/etc/postfix# cat /etc/postfix/vhost
example2.com
example1.com

## Expected Behavior

Accepted certs from various letsencrypt domains.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by johansmitsnl** [comment]
There can be only 1 certificate. If you want to use multiple host names  then the certificate should contain multiple hostnames in the certificate.

**Comment by helmutundarnold** [comment]
Okay - I've learned the keyword is SAN = Subject Alternate Name = one single cert for multiple domains.
