### ISSUE TITLE
Add configuring relay_domains

### ISSUE THREAD

**Issue by jidckii** [tomav/docker-mailserver#1091]
Sender only and relay_domains  

## Context
I use this server as a sender in `my-domain.net` domain  

There is a service account `no-relay@my-domain.net`  
I send an email to this user  
real.user@my-domain.net  
user should receive mail from gsite server  
but the sender is trying to deliver mail locally.  

#### example log:￼
```
Dec 14 08:15:12 mail postfix/lmtp[19468]: 0965B121B6C: to=<support.testing@my-domain.net>, relay=my-domain.net[/var/run/dovecot/lmtp], delay=0.03, delays=0.01/0.01/0.01/0.01, dsn=5.1.1, status=bounced (host mail.motorsportlive.com[/var/run/dovecot/lmtp] said: 550 5.1.1 <support.testing@my-domain.net> User doesn't exist: support.testing@my-domain.net (in reply to RCPT TO command))
```

I am manual add config  
```
relay_domains = my-domain.net  
relay_transport = hash:/tmp/docker-mailserver/transport
transport_maps = hash:/tmp/docker-mailserver/transport

cat /tmp/docker-mailserver/transport
my-domain.net  smtp:aspmx.l.google.com

postmap /etc/postfix/transport
postfix reload
```
now everything works as it should
#### example log:￼
```
Dec 14 15:53:57 mail postfix/smtp[19935]: CBE00121B72: to=<support@my-domain.net >, relay=aspmx.l.google.com[172.217.197.26]:25, delay=0.18, delays=0.01/0.02/0.09/0.07, dsn=2.0.0, status=sent (250 2.0.0 OK 1544802837 q45si431687qte.344 - gsmtp)
```

How can this configured not manually?

**Comment by johansmitsnl** [comment]
Check the WIKI: https://github.com/tomav/docker-mailserver/wiki/Configure-Relay-Hosts

**Comment by jidckii** [comment]
> Check the WIKI: https://github.com/tomav/docker-mailserver/wiki/Configure-Relay-Hosts

I saw this documentation.
It doesn't work with my script.

**Comment by erik-wramner** [comment]
@jidckii this seems to have stalled. If it is still relevant we need more details. What did you try? Why/how didn't it work? Have you tried with the current version, after all there have been quite a few changes since 2018?

Alternatively if it is no longer relevant I'd like to close the issue.

**Comment by jidckii** [comment]
I don't remember how, but i solved a problem. Thank you.
