### ISSUE TITLE
Is there a way to have logwatch and pflogsum added and act/deactivated by an Environment var?

### ISSUE THREAD

**Issue by helmutundarnold** [tomav/docker-mailserver#1093]
Is there a way to have logwatch and pflogsum added and act/deactivated by an Environment var?

## Context

Currently I'm using logwatch and pflogsum to monitor my mailserver. The way I'm installing it is using some docker-exec and docker cp after creating and running the container. 

It would be nice to have them both added in the default-image.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by helmutundarnold** [comment]
Hello Johan, do you mean its okay to rais a PR to implement  it? If yes I will try  - would be my first one :).

I would update https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh
and the the Dockerfile for installation - right?

**Comment by johansmitsnl** [comment]
Both yes

**Comment by erik-wramner** [comment]
@helmutundarnold is this still relevant? If you can't make a PR but still would like to get this done I think the chances would increase if you shared the docker exec/cp commands you are using now and of course the config files. Or if it is no longer relevant, can we close this?

**Comment by helmutundarnold** [comment]
Hello Erik,

this would be the Environment Variables

```
# pflogsummReport
PFLOGSUMMREPORT_ENABLED=[true|false]   # empty = false
PFLOGSUMMREPORT_SENDER_ADDRESS=<sender@example.com>
PFLOGSUMMREPORT_RECIPIENTS_ADDRESS=<email1>,<email2>...

# logwatch report
LOGWATCHREPORT_ENABLED=[true|false]  # empty = false
LOGWATCHREPORT_SENDER=<sender@example.com>
LOGWATCHREPORT_RECIPIENTS_ADDRESS=<email1>,<email2>...
```

This is my current function for pflogsummReport
```
  if [[ $PFLOGSUMMREPORT_ENABLED != true && $PFLOGSUMMREPORT_ENABLED != 1 ]] 
    then
        echo "pflogsummReport not enabled"
        return
    fi
    
    # first clean up 
    docker exec -it $MAIL_CONTAINER_NAME rm -rf /root/pflogsummReport
    
    # set PFLOGSUMMREPORT_SENDER + RECIPIENT
    sed  -i s/SENDER=.*$/SENDER=$PFLOGSUMMREPORT_SENDER_ADDRESS/ \
       $APPS_DIR/resources/pflogsummReport/root/pflogsummReport/pflogsummReport_yesterday.sh

    sed  -i s/RECIPIENTS=.*$/RECIPIENTS=$PFLOGSUMMREPORT_RECIPIENTS_ADDRESS/ \
       $APPS_DIR/resources/pflogsummReport/root/pflogsummReport/pflogsummReport_yesterday.sh
    
    sed  -i s/SENDER=.*$/SENDER=$PFLOGSUMMREPORT_SENDER_ADDRESS/ \
       $APPS_DIR/resources/pflogsummReport/root/pflogsummReport/pflogsummReport_today.sh

    sed  -i s/RECIPIENTS=.*$/RECIPIENTS=$PFLOGSUMMREPORT_RECIPIENTS_ADDRESS/ \
       $APPS_DIR/resources/pflogsummReport/root/pflogsummReport/pflogsummReport_today.sh
    
    echo "copy the preconfigured pflogsummReport into the container"
    inSRC="$APPS_DIR/resources/pflogsummReport/root/pflogsummReport"
    inDST="$MAIL_CONTAINER_NAME:/root"
    docker cp $inSRC $inDST
    docker exec -it $MAIL_CONTAINER_NAME chown -R root.root /root/pflogsummReport
    
    echo "update the cron.d"
    docker exec -it $MAIL_CONTAINER_NAME rm -rf /etc/cron.d/pflogsummReport
    inSRC="$APPS_DIR/resources/pflogsummReport/etc/cron.d/pflogsummReport"
    inDST="$MAIL_CONTAINER_NAME:/etc/cron.d"
    docker cp $inSRC $inDST
    docker exec -it $MAIL_CONTAINER_NAME chown root.root /etc/cron.d/pflogsummReport    
    docker exec -it $MAIL_CONTAINER_NAME chmod 644 /etc/cron.d/pflogsummReport 
```

The script that will be triggered by the cron is pflogsummReport_yesterday.sh . For maintainance reason I also created a script pflogsummReport_today.sh  which sends a report from todays logs.

```
[admin@triton904 pflogsummReport]$ cat pflogsummReport_yesterday.sh
#!/bin/sh

MAILLOG_DIR=/var/log/mail
WORK_DIR=/root/postfixTools
REPORT_FILE=$WORK_DIR/mail_repo_$(date '+%Y-%m-%d_%H%M%S').txt
SEND_HOST=$(uname -n)

RECIPIENTS=$PFLOGSUMMREPORT_RECIPIENTS_ADDRESS
SENDER=$PFLOGSUMMREPORT_SENDER_ADDRESS

BODY=$(/usr/sbin/pflogsumm $MAILLOG_DIR/mail.info -d yesterday)

/usr/sbin/sendmail -t <<EOF
From: $SENDER
To: $RECIPIENTS
Subject: pflogsumm for $SEND_HOST from yesterday sent on $(date '+%Y-%m-%d_%H%M%S')
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8
$BODY
EOF
```

For the Logwatch its similar
But logwatch must be added in the dockerfile
```
/usr/bin/apt-get update -y
/usr/bin/apt-get install logwatch -y
```

and the logwatchReport_yesterday.sh looks like
```
SEND_HOST=$(uname -n)
RECIPIENTS=$PFLOGSUMMREPORT_RECIPIENTS_ADDRESS
SENDER=$PFLOGSUMMREPORT_SENDER_ADDRESS

/usr/share/logwatch/scripts/logwatch.pl --hostname $SEND_HOST --range Yesterday --detail Med --mailto $RECIPIENTS

```

Would be nice if this could be added.

**Comment by erik-wramner** [comment]
@helmutundarnold I just noticed that pflogsumm is included already. It is enabled with REPORT_RECIPIENT and there are also REPORT_SENDER and REPORT_INTERVAL options. Does that report work for you, or (if not) what is missing?

That doesn't cover logwatch of course.

**Comment by helmutundarnold** [comment]
Hello Erik,
unfortunately this implemented Report is triggered by logrotate and not 
by a regular daily cron. And thus the report relays on the entire 
logfile.  I would like to use that "yesterday" option to make sure I 
have a summary from yesterday.

If you/Mailsever team implents a second report with logwatch I thought 
it would be good to have similar Variables and it would be more flexible 
for the future.

Best Regards
          Helmut

Am 16.08.19 um 11:23 schrieb Erik Wramner:

**Comment by erik-wramner** [comment]
See #1262.

**Comment by helmutundarnold** [comment]
Hello Erik,
thanks for implementing and update with pflogsum and logwatch. I'm 
looking forward of how it will work.

Regards
         Helmut

Am 15.09.19 um 18:25 schrieb Erik Wramner:
