### ISSUE TITLE
.dovecot.sieve change header subject

### ISSUE THREAD

**Issue by stkac** [tomav/docker-mailserver#1095]
# dovecot sieve redirect copy and change header subject

## Steps to Reproduce

1. vim .dovecot.sieve
```
require ["copy", "editheader"];

addheader "Subject" "MANAGER HAVE A NEW MAIL";
redirect :copy "user@mail-demo.com";
```

Thank in advance,

**Comment by johansmitsnl** [comment]
You can sievemanage to make your rules.
