### ISSUE TITLE
I am unable to create email accounts 

### ISSUE THREAD

**Issue by yilkalargaw** [tomav/docker-mailserver#1098]
I am unable to create email accounts after running the docker container

Right after 
```
docker-compose up -d mail
```
when I run
```
/setup.sh email add user@domain
```
and insert the password
I get the error 
```
/usr/local/bin/addmailuser: line 34: /tmp/docker-mailserver/postfix-accounts.cf: Permission denied
``` 
right after entering the password

I am using Fedora 29 and the latest image for docker-mailserver

**Comment by reyx7** [comment]
Me to

**Comment by johansmitsnl** [comment]
Could it be SE linux?

**Comment by reyx7** [comment]
Centos 7

**Comment by yilkalargaw** [comment]
I also think it might be SE linux related because it worked for me on ubuntu

**Comment by svenyonson** [comment]
did you try with sudo? Works on my ubuntu system

**Comment by ashtonhong** [comment]
centos 7 
when add user, show some error infomation: 
/usr/local/bin/addmailuser: line 34: /tmp/docker-mailserver/postfix-accounts.cf: Permission denied

**Comment by yilkalargaw** [comment]
tried it it worked.
