### ISSUE TITLE
Add DOVECOT_PASS_ATTR and DOVECOT_USER_ATTR variables to the documentation

### ISSUE THREAD

**Issue by phish108** [tomav/docker-mailserver#1099]
The ```DOVECOT_PASS_ATTR``` and the ```DOVECOT_USER_ATTR``` are needed for configuring dovecot properly for handling LDAP attributes. These **extremely** useful environment variables are not documented. 

## Context

Not all LDAP directories use the attributes as hardcoded in the ```dovecot-ldap.conf.ext``` config. For these directories dovecot has to use different attributes. I managed to configure dovecot for using the correct attributes by setting the ```DOVECOT_PASS_ATTR``` and the ```DOVECOT_USER_ATTR``` environment variables to the desired values (see Wiki). 

It took me a day to pinpoint a solution by reading the ```setup.sh``` script, because the obvious solution is undocumented :(

I added a working example to the end of the LDAP wiki-page.

## Expected Behavior

README.md documents the ```DOVECOT_PASS_ATTR``` and the ```DOVECOT_USER_ATTR``` environment variables. 

## Actual Behavior

README.md does not mention the ```DOVECOT_PASS_ATTR``` and the ```DOVECOT_USER_ATTR``` environment variables. 

## Possible Fix

Add the documentation with a reference to the wiki

## Steps to Reproduce

1. Open  README.md
2. search for DOVECOT_PASS_ATTR and find 0 results
3. search for DOVECOT_USER_ATTR and find 0 results

**Comment by johansmitsnl** [comment]
Please provide a PR for the documentation and I'll merge it.

**Comment by phish108** [comment]
Took me a while. PR #1112 has been tested with our setup.
