### ISSUE TITLE
Issue with combined.pem from LE certificates

### ISSUE THREAD

**Issue by DominikTrenz** [tomav/docker-mailserver#110]
I had many problems getting the courier server running with LE certificates. After a while i found the problem:

The .pem files from LE are merged into "combined.pem" and when there is no newline at the end of the LE files this happens:
`-----END CERTIFICATE----------BEGIN CERTIFICATE-----`
Which causes the imap server to fail.

Changing Line 129 in start-mailserver.sh to:
`( cat "/etc/letsencrypt/live/$(hostname)/cert.pem"; echo""; cat "/etc/letsencrypt/live/$(hostname)/chain.pem"; echo ""; cat "/etc/letsencrypt/live/$(hostname)/privkey.pem"; echo ) > "/etc/letsencrypt/live/$(hostname)/combined.pem"`
solves the problem

**Comment by tomav** [comment]
Hi @DominikTrenz, do you want to submit a PR?

**Comment by chadyred** [comment]
How do you create the LE certificate ? 

On many case I use the URL /well-known URL when I have a web server running/ I don't have this possibility to do that, so I don't know how generate a certificate with LetEncrypt with a mail server.

**Comment by DominikTrenz** [comment]
@tomav Maybe i will do so the next days. Thanks for this awesome image btw :)
@chadyred I use following docker images for automatic LE certificates:
```
jwilder/nginx-proxy
jrcs/letsencrypt-nginx-proxy-companion  
```
The proxy-companion sets up the well-known urls in nginx and renews the certificates which are shared the email server.

**Comment by chadyred** [comment]
Yes, I alse use them, but to generate certificate jrcs/letsencrypt-nginx-proxy-companion and particulary lets encrypt, use an URL for ACME challenge is needed and mail server container don't have one. 

My idea : 

Create a container with nginx which could receive /well-known link to mail server
So the certificate is generate and I shared this one to my mail container in the /etc/letsencrypt/live
folder.

**Comment by DominikTrenz** [comment]
The ACME challenge should be received just fine if you mounted the /usr/share/nginx/html volume from nginx in the letsencrypt container. At least it works fine with my setup. I also had to modify the letsencrypt image to generate all the necessary certificate files for the mailserver.

**Comment by chadyred** [comment]
Thanks for help, I will re-open an issue if I have more problem more developed.

**Comment by Reldeis** [comment]
PR #111 fixes the Problem

For further reference: my PR in in `jrcs/letsencrypt-nginx-proxy-companion` got merged recently. So if you use this container, like Dominik does, all you have to do is add its generated files to the mailserver. (You may need to rename key.pem to privkey.pem)
