### ISSUE TITLE
Certs SMTP multidomains

### ISSUE THREAD

**Issue by vl3004** [tomav/docker-mailserver#1100]
Environment:
- 3 domains , say domain1.com, domain2.com, domain3.com
- one public IP 
-  domain1.com is principal , mail.domain1.com  is the mail server (the only one serving all 3 domains)

Can't get certs working  correctly for domain2 and domain3. 

e.g. in checktls.com it says cert failed for domain2 &3 
message: 
"Cert Hostname DOES NOT VERIFY (mail.domain1.com != mail.domain2.com | DNS:mail.domain1.com)
So email is encrypted but the host is not verified"

Also mxtoolbox.com complains: 
" warning - Does not support TLS "  also fails for the above 2 domains

The emails are working from/to those domains hosted on the mail.domain1.com, however it takes 2-3 minutes from one domain to another (on the same server), slighlty more from/to gmail 

What i tried 👍 
1./
docker run --rm -ti -v $PWD/log/:/var/log/letsencrypt/ -v $PWD/etc/:/etc/letsencrypt/ -p 80:80 deliverous/certbot certonly --standalone -d mail.domain1.com -d domain1.com -d domain2.com -d domain3.com 

the certs are generated ok but still the same error in checkTLS

2./ i have tried to combine (used the certs ) with  jrcs/letsencrypt-nginx-proxy-companion , nginx-gen, nginx-web  (whcih are runnign for another project)- still the same err. 

Any thoughts ? 
Many thanks ...

**Comment by johansmitsnl** [comment]
See #1090
