### ISSUE TITLE
LDAP alias mail forwarding, search filter usage unclear

### ISSUE THREAD

**Issue by rs-development** [tomav/docker-mailserver#1101]
I am using the an OpenLDAP server together with the tomav-mailserver and i would like to get the addresses from the ldap server instead of the postfix-virtual.cf.

## Context
It made some experiments with the LDAP filters in the .env file but i am not sure weather this is possible what i would like to do or not. I have a testuser with the following attributes:

Using the ldap_search command to query the database i can find the user via the mail adress.

`ldapsearch -x -H ldap://localhost -b ou=user_test,dc=domain,dc=de -D "cn=readonly,dc=domain,dc=de" -w readonlypassword "(&(mail=test.user@domain.de)(mailenable=TRUE))"`

> Test User, user_test, domain.de
> dn: cn=Test User,ou=user_test,dc=domain,dc=de
> givenName: Test
> sn: User
> cn: Test User
> uid: test.user
> mailalias: testmail@gmail.com
> mailenable: TRUE
> objectClass: InetOrgPerson
> objectClass: top
> objectClass: mailAccount
> mail: test.user@domain.de`
> 
>  search result
> search: 2
> result: 0 Success
> 
> numResponses: 2
> numEntries: 1

## Expected Behavior
I assume it is possible to query the ldap server from the mailserver with an appropiate filter to get the `aliasmail` for a given `mail` received by the mailserver.

## Actual Behavior
Using this filter `LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailenable=TRUE))` the mailserver does the following searches in the ldap database:

> 5c2cb3a0 conn=1063 op=1 SRCH base="ou=test_user,dc=domain,dc=de" scope=2 deref=0 filter="(&(mailalias=live.de)(mailenable=true))"
> 5c2cb3a0 conn=1063 op=1 SRCH attr=mail
> 5c2cb3a0 conn=1063 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
> 5c2cb3a0 conn=1063 op=2 SRCH base="ou=test_user,dc=domain,dc=de" scope=2 deref=0 filter="(&(mailalias=domain.de)(mailenable=true))"
> 5c2cb3a0 conn=1063 op=2 SRCH attr=mail

- It does not even search with the `LDAP_QUERY_FILTER_USER`
- While searching for alias with this filter `LDAP_QUERY_FILTER_ALIAS=(&(mailalias=%s)(mailenable=TRUE))` only the hostname is used instead of the complete mail

Is this a expected behavior? Maybe someone can take me back on the route :)

## Your Environment
* Amount of RAM available: 32GB
* Mailserver version used: latest
* Docker version used: Docker version 18.06.1-ce, build e68fc7a
  https://github.com/tomav/docker-mailserver#requirements

**Comment by johansmitsnl** [comment]
There are 3 parts of the search query:

```yaml
      - SASLAUTHD_LDAP_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%U))
      - SASLAUTHD_MECHANISMS=ldap
      # <<< SASL Authentication
      # >>> Postfix Ldap Integration
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=ldap
      - LDAP_SEARCH_BASE=dc=domain,dc=net
      - LDAP_BIND_DN=cn=admin,dc=domain,dc=net
      - LDAP_QUERY_FILTER_ALIAS=(&(mailAlias=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))
      # <<< Postfix Ldap Integration
      # >>> Dovecot Ldap Integration
      - DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(|(uniqueIdentifier=%n)(mail=%u)))
      - DOVECOT_PASS_FILTER=(&(objectClass=PostfixBookMailAccount)(|(uniqueIdentifier=%n)(mail=%u)))
      # <<< Dovecot Ldap Integration
```

Hope this is helpful.

**Comment by erik-wramner** [comment]
@rs-development is this still relevant? If you solved the issue perhaps you can add a short note and we can close it?

I'm not using the LDAP connection myself so I'm afraid this is out of my depth.

**Comment by rs-development** [comment]
I skipped LDAP usage for now, but I would still like to implement it. Please keep it open, I will come back later this year when I am trying it again.

**Comment by erik-wramner** [comment]
Right, we'll leave it open for you then.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, **please feel free to re-open it**. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
