### ISSUE TITLE
How can I handle 2 domain names at the same time?

### ISSUE THREAD

**Issue by inglesuniversal** [tomav/docker-mailserver#1108]
I am amazed by its perfomance.

Only one question though... 

How can I handle 2 domain names at the same time?

Since I was not able to figure that out, my host name right now is the IP address of my Docker Server, however, lots of emails we send out are being received from us into the SPAM folder of our users.

Any idea or reference guide on how to accomplish this?

Or would it work better on two separate servers? I am using an AWS LightSail Bitnami Ubuntu Server

Regards

**Comment by johansmitsnl** [comment]
2 domains is simply adding 2 users for each domain:
* User@domain1.com
* User@domain2.net

But of course with correct names. 
For spam:
* https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM
* https://github.com/tomav/docker-mailserver/wiki/Configure-SPF

**Comment by inglesuniversal** [comment]
Sorry if I didn't make myself clear.

What I meant was...

I am pointing to this Email Server with an IP address (eg. 22.22.22.22) so, since I needed two domain names to share the same email server, I couldn't find a better way to fix this.

BUT... some customers or users either don't get my emails, they are sent to their spam list, or when they send an email from their server my email appears as NOT valid.

how can I create the doman names (for two sites) and SSL at the same time for your script, and SET it up.

mail.mydomain1.com

mail.mydomain2.com


I hope this explanations helps you understand my needs.

Thanks

**Comment by johansmitsnl** [comment]
Check  #1100

**Comment by inglesuniversal** [comment]
So, bottom line... If I am understanding correctly... to avoid all the fuzz of additional settings or configurations... it is just simply better to have a small server for each domain name?

**Comment by johansmitsnl** [comment]
No, Just set the spf and dkim correctly for each domain and your done.

**Comment by johansmitsnl** [comment]
Did you solve it?

**Comment by inglesuniversal** [comment]
I will let you know very soon. I'm packing an app that needs to be published this week.
