### ISSUE TITLE
Adding all envionment variables to the docker file?

### ISSUE THREAD

**Issue by cofilippo** [tomav/docker-mailserver#1109]
## Context
So I noticed only a couple of environment variables are actually in the docker file, but they're all mentioned in the compose file. I'm trying to use your container with Cockpit

## Expected Behavior
All of the environment variables are listed when starting a container in packages like Cockpit (and possibly others)

## Actual Behavior
Only the variables listed in the docker file are listed.

## Possible Fix
Include ENV declarations for all variables

## Steps to Reproduce
* download and install cockpit, cockpit-docker
* download tomav/docker-mailserver in Cockpit UI
* Try to start container

## Your Environment
* Amount of RAM available: 4GiB
* Mailserver version used: latest
* Docker version used: 1.13.1
* Environment settings relevant to the config: all variables not currently included.
* Any relevant stack traces ("Full trace" preferred): N/A

**Comment by johansmitsnl** [comment]
Could you provide a PR?

**Comment by cofilippo** [comment]
I'm not very experienced with docker beyond simple definitions and the execution of containers, but I'll give it a go.

Do you happen to know what docker does with ENV declarations with no value?

**Comment by cofilippo** [comment]
I've run into a small snag in that Cockpit doesn't have any way to handle a hostname parameter. As far as I can tell this means that the conversion is not as straight forward as I first thought.

I'll have a look again in the near future, but in the coming weeks there's some more important stuff I need to take care of first.

**Comment by erik-wramner** [comment]
Also note that there are cases where the startup script treats a real value, a blank value and no value differently! For example the security type (manual, custom etc). Setting an ENV parameter will create it even if it is blank, so that may break some code. Not sure if it matters, just pointing it out.

**Comment by erik-wramner** [comment]
@cofilippo is this still relevant or should we close the issue? I'm trying to reduce the number of open ones to a manageable level and this seems to have stalled?

**Comment by cofilippo** [comment]
Sorry, I don't have time to work on this and it depends on how Cockpit implements it's stuff. I think it is best closed tentatively. (perhaps I can come back to it once Cockpit has changed the way they handle environment variables)
