### ISSUE TITLE
Migration from docker container to mail hoster - save mails?

### ISSUE THREAD

**Issue by qwertz22** [tomav/docker-mailserver#1111]
Hello,

can you give me advice for a migration from this docker mailserver to a mail hoster?

The mails are stored in docker container in /var/mail/.
How can I migrate them so import these mails into thunderbird or outlook? I don't have a connection to the docker container anymore, so I have to do it in CLI.

Thanks.

**Comment by johansmitsnl** [comment]
It is just a maildir. You can tar it and extract it on the new location. You might have to tweak the uid's on the new location.

Also see https://serverfault.com/questions/105804/how-can-i-migrate-dovecot-from-one-server-to-another
