### ISSUE TITLE
How to enable ipv6 docker-mailserver?

### ISSUE THREAD

**Issue by perry-amsterdam** [tomav/docker-mailserver#1115]
How do i enable ipv6 for docker-mailserver without modifying the container ?
I am using the latest version.

Note that 
# docker run -it busybox ifconfig 
actually gives me an IPv6 address here (from the --fixed-cidr subnet which is assigned to the default bridge network)

Greeting from Amsterdam,
Perry

**Comment by perry-amsterdam** [comment]
I have installed ipv6nat and its running.
The docker interface has a ipv6 address that i can ping from the internet.
How do i now enable ipv6 on the docker-mailserver ?

**Comment by perry-amsterdam** [comment]
[root@server01 mail-server]# docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by johansmitsnl** [comment]
Just access on the up the server.

**Comment by perry-amsterdam** [comment]
There is no ipv6 interface on de the container. When i try to config a ipv6 ipaddress on eth0 ik get RTNETLINK answers: Permission denied.

**Comment by perry-amsterdam** [comment]
When i start the container with the following command:
docker run -it tvial/docker-mailserver bash
It gets a two ipv6 addresses, one link local en a global ipv6.

**Comment by perry-amsterdam** [comment]
With the following change i get ipv6 addresses within the container.
[root@server01 mail-server]# diff -uNr docker-compose.yml.orig docker-compose.yml
--- docker-compose.yml.orig	2019-01-28 21:51:57.772722654 +0100
+++ docker-compose.yml	2019-01-28 21:52:12.565151049 +0100
@@ -18,6 +18,7 @@
     - /etc/letsencrypt/:/etc/letsencrypt/:ro
     - /etc/localtime:/etc/localtime:ro
     - /lib/modules:/lib/modules:ro
+    network_mode: bridge
     environment:
     - DMS_DEBUG=${DMS_DEBUG}
     - ENABLE_CLAMAV=${ENABLE_CLAMAV}

**Comment by johansmitsnl** [comment]
`network_mode:bridge` did it.
:+1: so it is solved? Please close if it is.
