### ISSUE TITLE
Allow to use Spamassassin's shortcircuit bayes_99 and bayes_00 feature

### ISSUE THREAD

**Issue by phish108** [tomav/docker-mailserver#1118]
Spamassassin allows administrators to give their Bayes databases greater emphasis by short circuiting the analytical process. 

This is normally configured in /etc/spamassassin/local.cf at the very end. However, it is rather annoying, to edit this file with every update of the container.

Having two environment variables to configure this would be very helpful.

Proposal: 

- ```SA_SHORTCIRCUIT_BAYES_SPAM``` - if set to 1, then it will activate ```shortcircuit bayes_99 spam```
- ```SA_SHORTCIRCUIT_BAYES_HAM```- if set to 1, then it will activate ```shortcircuit bayes_00 ham```

**Comment by johansmitsnl** [comment]
Can you provide a pull request for this?

**Comment by phish108** [comment]
Sure, it is on already. See PR #1119

**Comment by johansmitsnl** [comment]
Sorry missed that, will have a look asap

**Comment by evlist** [comment]
These variables do uncomment the relevant lines in local.conf, but these lines are within a conditional block and are only applied if the Shortcircuit plugin is active which is *not* the case by default which is very misleading !

When set we should thus also enable this plugin or, maybe better, add environment variables to enable and disable plugins...

**Comment by phish108** [comment]
Thanks @evlist for the remark.

I opened PR #1443 to tackle this problem. 

I think enabling a plugin if a specific feature is requested, is smarter and more intuitive than having an additional config option.  Of course this only makes sense, if there is a related configuration ENV.
