### ISSUE TITLE
fail2ban and iptables question

### ISSUE THREAD

**Issue by 00angus** [tomav/docker-mailserver#112]
It would be useful to have Fail2ban not started by default, IMHO. In my case, for example, I prefer to filter on the host by looking at the container logs. And usually  I don't like privileged containers :o

What do you think?

**Comment by gegere** [comment]
I agree with not having Fail2ban start by default. There is often valid IMAP requests with the incorrect password often enough and Fail2ban would block it.

**Comment by KyleOndy** [comment]
Could be have this configurable via an environmental variable? That way its easy to have one way or the other.

**Comment by 00angus** [comment]
Yes, something like ENABLE_FAIL2BAN. I've implemented it for my own purposes: just a few more tests and I'll pull a request to see also @tomav opinion.

BTW we could also implement it as DISABLE_* if this make more sense to you, but for general concordance with the rest of the project ENABLE_*  is a better solution IMHO.

**Comment by tomav** [comment]
I agree, use an env to enable it.

**Comment by 00angus** [comment]
BTW - by looking at the integration tests for fail2ban I've found the following:

     @test "checking fail2ban: localhost is not banned" {
      run docker exec mail_fail2ban /bin/sh -c "fail2ban-client status sasl | grep 'IP list:\s*127.0.0.1'"
      [ "$status" -eq 1 ]
    }

Here the grep will match '127.0.0.1' only when it's the first IP listed. So for example here will not match:

     - IP list:       1.2.3.4 188.188.188.188 127.0.0.1

I think this is not the intended behaviour, right? It should match even in this case because we want to be sure that localhost is not banned. 
I'm including a change for this in my next PR. @tomav have a look at it to check it is ok.

**Comment by tomav** [comment]
Fixed by #114
