### ISSUE TITLE
Why sending mail to Gmail and Hotmail going into spams Question

### ISSUE THREAD

**Issue by Kubilai12** [tomav/docker-mailserver#1126]
Hi
I use this project and test my domain with this 2 tools : 

- https://www.mail-tester.com/
- http://www.appmaildev.com/en/dkim

All test are good but when i send mail to gmail user or hotmail user my mails going into spams is there something to do for have a normal way ?

Thanks

**Comment by johansmitsnl** [comment]
Their spam filters are tight. If you have DKIM, SPF and reverse DNS set-up correctly there is not much you can do.
I believe for hotmail you can request whitelisting of your server ip. Gmail I don't know though.

**Comment by Kubilai12** [comment]
Ok thanks you confirm i can t do more than i did before, because all mail server test i found say me good configuration
