### ISSUE TITLE
Running docker-mailserver on portainer.io self hosted?

### ISSUE THREAD

**Issue by voordev** [tomav/docker-mailserver#1128]
My goal after extensive searching is to deploy the docker-mailserver on a docker compatible OS.
Since I need monitoring and magagement UI I found out Portainer.io is the best option to proceed.
Has anyone setup docker-mailserver on a portainer instance locally?
And is anyone willing to share some details on how to approach this best?
I have currently running portainer and a local docker registry which is setup in portainer.
The docker-mailserver runs as an image inside this.

Any thoughts from the team or anyone with first hand experience in this regard?
Could be an interesting method and im willing to fully document my processes as a a contribution to the wiki entry for further reference if anyone can point me in the right direction!

Kind regards.

The Portainer UI allows to add the docker-compose.yml so that would be fixed.
It allows adding ENV but only 1 by 1 the complete list without comments is:

```
HOSTNAME=mail
DOMAINNAME=domain.com
OVERRIDE_HOSTNAME=
DMS_DEBUG=0
ONE_DIR=0
POSTMASTER_ADDRESS=
PERMIT_DOCKER=
TLS_LEVEL=
SPOOF_PROTECTION=
ENABLE_SRS=0
ENABLE_POP3=
ENABLE_CLAMAV=0
ENABLE_FAIL2BAN=0
ENABLE_MANAGESIEVE=
POSTSCREEN_ACTION=enforce
SMTP_ONLY=
SSL_TYPE=
VIRUSMAILS_DELETE_DELAY=
ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
POSTFIX_DAGENT=
POSTFIX_MAILBOX_SIZE_LIMIT=
POSTFIX_MESSAGE_SIZE_LIMIT=
REPORT_RECIPIENT=0
REPORT_SENDER=
REPORT_INTERVAL=daily
ENABLE_SPAMASSASSIN=0
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=6.31
SA_SPAM_SUBJECT=***SPAM*****
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
ENABLE_LDAP=
LDAP_START_TLS=
LDAP_SERVER_HOST=
LDAP_SEARCH_BASE=
LDAP_BIND_DN=
LDAP_BIND_PW=
LDAP_QUERY_FILTER_USER=
LDAP_QUERY_FILTER_GROUP=
LDAP_QUERY_FILTER_ALIAS=
LDAP_QUERY_FILTER_DOMAIN=
DOVECOT_TLS=
DOVECOT_USER_FILTER=
DOVECOT_PASS_FILTER=
ENABLE_POSTGREY=0
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_TEXT=Delayed by postgrey
POSTGREY_AUTO_WHITELIST_CLIENTS=5
ENABLE_SASLAUTHD=0
SASLAUTHD_MECHANISMS=
SASLAUTHD_MECH_OPTIONS=
SASLAUTHD_LDAP_SERVER=
SASLAUTHD_LDAP_SSL=
SASLAUTHD_LDAP_BIND_DN=
SASLAUTHD_LDAP_PASSWORD=
SASLAUTHD_LDAP_SEARCH_BASE=
SASLAUTHD_LDAP_FILTER=
SASLAUTHD_LDAP_START_TLS=
SASLAUTHD_LDAP_TLS_CHECK_PEER=
SASL_PASSWD=
SRS_SECRET=
DEFAULT_RELAY_HOST=
RELAY_HOST=
RELAY_PORT=25
RELAY_USER=
RELAY_PASSWORD=
```
So this is quite the work and error prone, 

Then we have the issue with the setup.sh . @tomav do you think I could setup the docker container according to your docker then lateron hook it to portainer? 

As far As I see the portainer is just a wrapper and I could follow the regular documentation steps provided in your documentation. Then only having to 'import' the container in portainer.io would be the most simple option, also providing the setup.sh option to add accounts.

Any thoughts on above? 
Im more than willing to document every step to get it working to the WIKI as a thank you for creating the server and the future reference if anyone could point me in the right direction.

**Comment by voordev** [comment]
So far I found this blogpost:

https://foundries.io/insights/2018/05/08/using-docker-compose.yml-with-portainer/

But I think there will be some work on to make this compatible.
For example the setup.sh script needs to be run from somewhere

Any thoughts @tomav did you ever came across portainer and could point me in right direction on how to approach on this?

**Comment by fbartels** [comment]
Hi,

ultimately Portainer is just a web gui over everything you can do through the commandline already. So if you are struggeling to start this container through the gui you could also start it from the cli and then use the gui to check on its status every once in a while. 

> But I think there will be some work on to make this compatible.
For example the setup.sh script needs to be run from somewhere

Your linked blog also includes a solution for this. What they recommend is to create a small intermediary container that is then used to execute docker-compose. You could do the same with a checkout of this git repo and then also execute the setup script from inside this container.

**Comment by voordev** [comment]
Like @fbartels stated except for the setup.sh there are no problems
