### ISSUE TITLE
Insert my one CA certificate

### ISSUE THREAD

**Issue by ilneofita** [tomav/docker-mailserver#1129]
Hi,
this is not an issue, however, I was wondering which is the best way to import myown CA for the self sign certificate for the openldap.
I have included using docker batch mode.

**Comment by erik-wramner** [comment]
This is certainly not an authoritative answer, but I think the bundled ldap server is meant for the integration tests rather than as a full-blown supported LDAP server (@tomav?). You will probably get a better answer on https://stackexchange.com/ or in a project focused on the LDAP project.
