### ISSUE TITLE
loggings

### ISSUE THREAD

**Issue by 00angus** [tomav/docker-mailserver#113]
I'd like to suggest to put mail.* logs inside a specific folder instead of the more general /var/log. In this way it's easy to provide let's say a -v mail-log:/var/log/mailserver where only mail logs are made available on the host.
I use that approach together with a fail2ban modification to filter incoming connections directly on the host, for example.

What do you think?

**Comment by tomav** [comment]
I agree.
`/var/log/mail` could be a good place to be (not `mailserver`, project could change in v2 milestone)

**Comment by 00angus** [comment]
@tomav Ok, `mailserver` is not ok. I'm thinking of putting inside this directory also the `clamav` logs, so all relevant server logs (apart from fail2ban) could be made easily available on the host. 
In this case `mail` could still be adopted for that directory, I think. Ok?

**Comment by 00angus** [comment]
I'm going to do a PR for that issue. I've changed the way fail2ban jail.con get updated (from perl to awk) because there are now several changes to be managed and awk was simple IMHO,  but if you think perl is better please let me know.
Moreover there was an annoying message when no spamassassin rule file was not provided l, so I've added a simple check.

**Comment by gegere** [comment]
I have been using a external logging service called LogEntries.com would this be something to consider? I have been using their service for about a year and have been quite happy even with the free tier. I have about 10 containers logging at any given time and can easily search across all logs. You simply pass the API call into the containers that are built and you don't need to worry about storing or managing the logs via the container.

Here is more details on this: https://logentries.com/doc/docker/

**Comment by 00angus** [comment]
@gegere I personally prefer to locally manage (on the host) the logs, but probably logentries.com is a good service. Anyway I've not configured such a service so I cannot be of help.

**Comment by gegere** [comment]
We all have our tools for the job. It has been really challenging to merge
logs locally for 5 containers spread across 5 datacenter locations, so
external logging was a proper solution and I can choose to keep logs for a
short or long duration per the storage provider.

Using this service is very easy and if the idea grows I will lend my
support.

**Comment by tomav** [comment]
Out of the box, it should work locally. Using an external tool can't be a default but could be an option.
@00angus do you want to PR the folder modification (we should add test on it)

**Comment by 00angus** [comment]
@tomas as for the tests I'll add a check.
Unfortunately yesterday evening I've mistaken the commit comment
(referencing ENABLE_FAIL2BAN when instead I was committing changes on log
path changes!). So yes, in the next PR I'll also add the reference to the
path modification.

**Comment by 00angus** [comment]
@tomav PR done, pls let me know if it's ok.

**Comment by tomav** [comment]
Yeah nice. Thank you @00angus
