### ISSUE TITLE
@commonName@ certificate?

### ISSUE THREAD

**Issue by voordev** [tomav/docker-mailserver#1130]
Trying to implement the SSL certificates for the mailserver with lots of problems.

_I have re-read the docs 4x times but it fails every time. The certificate recieved by the mail client is invalid and has @commonname@ in the title. With thunderbird im able to view the certificate:

<img width="592" alt="screenshot 2019-02-17 at 23 50 38" src="https://user-images.githubusercontent.com/34578028/52920617-e66d6b00-330e-11e9-8094-be8e930b6f67.png">_

What Did I miss? How to resolve this and create a 'real certificate' 
Anyone can please suggest how this could be resolved?

I had some DNS acme records added previously which i now have removed.

Followed the instructions in the wiki

1. Create certificate for mail.domain.ltd
/server/letcencrypt is my folder to store letsencrypt in.

```
   docker run --rm -ti -v $PWD/log/:/var/log/letsencrypt/ -v $PWD/etc/:/etc/letsencrypt/ -p 80:80 deliverous/certbot certonly --standalone -d mail.domain.ltd
```

This correctly it seems write to /server/letsencrypt/etc/live/domain.ltd 

2. Booting up the containers and linking volumes

```
    docker run --detach \
        --name nginx-proxy \
        --restart always \
        --publish 80:80 \
        --publish 443:443 \
        --volume /server/letsencrypt/etc:/etc/nginx/certs:ro \
        --volume /etc/nginx/vhost.d \
        --volume /usr/share/nginx/html \
        --volume /var/run/docker.sock:/tmp/docker.sock:ro \
        jwilder/nginx-proxy

    docker run --detach \
      --name nginx-proxy-letsencrypt \
      --restart always \
      --volume /server/letsencrypt/etc:/etc/nginx/certs:rw \
      --volumes-from nginx-proxy \
      --volume /var/run/docker.sock:/var/run/docker.sock:ro \
      jrcs/letsencrypt-nginx-proxy-companion      

    docker run --detach \
      --name webmail \
      --restart always \
      --env "VIRTUAL_HOST=mail.domain.ltd" \
      --env "LETSENCRYPT_HOST=mail.domain.ltd" \
      --env "LETSENCRYPT_EMAIL=info@domain.ltd" \
      nginx  

```

**Comment by voordev** [comment]
CheckTLS.com gives below output:

```
Trying TLS on domain.ltd[206.189.243.252:25] (10):

seconds		test stage and result
[000.081]		Connected to server
[000.718]	<-- 	220-mail.domain.ltd ESMTP Postfix (Debian)
220 mail.domain.ltd ESMTP Postfix (Debian)
[000.718]		We are allowed to connect
[000.718]	 -->	EHLO www6.CheckTLS.com
[000.798]	<-- 	250-mail.domain.ltd
250-PIPELINING
250-SIZE 10240000
250-ETRN
250-STARTTLS
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
[000.799]		We can use this server
[000.799]		TLS is an option on this server
[000.799]	 -->	STARTTLS
[000.879]	<-- 	220 2.0.0 Ready to start TLS
[000.879]		STARTTLS command works on this server
[001.053]		Connection converted to SSL
SSLVersion in use: TLSv1_2
Cipher in use: ECDHE-RSA-AES256-GCM-SHA384
**Certificate 1 of 1 in chain: Cert VALIDATION ERROR(S): self signed certificate
So email is encrypted but the recipient domain is not verified
Cert Hostname DOES NOT VERIFY (domain.ltd != ff4a106323a4 | DNS:ff4a106323a4)
So email is encrypted but the host is not verified**
cert not revoked by CRL
cert not revoked by OCSP
serialNumber=a3:65:23:37:17:62:70:20
subject= /CN=ff4a106323a4
issuer= /CN=ff4a106323a4
[001.054]	 ~~>	EHLO www6.CheckTLS.com
[001.136]	<~~ 	250-mail.domain.ltd
250-PIPELINING
250-SIZE 10240000
250-ETRN
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
[001.136]		TLS successfully started on this server
[001.136]	 ~~>	MAIL FROM:<test@checktls.com>
[001.227]	<~~ 	250 2.1.0 Ok
[001.228]		Sender is OK
[001.228]	 ~~>	QUIT
[001.308]	<~~ 	221 2.0.0 Bye
```

**Comment by voordev** [comment]
Using Thunderbird to view the certificate

mail.domain.ltd it gives a valid certificcate
mail.domain.ltd:143 gives @commonname@ invalid certificate.

**Comment by johansmitsnl** [comment]
Did you read the wiki about how to set this up?

https://github.com/tomav/docker-mailserver/wiki/Configure-SSL

**Comment by voordev** [comment]
@johansmitsnl 
Yes I followed the instructions there, my docker commands are from the nginx-proxy so they differ a little bit ( more clean syntax but they basically do the same if im correct).
I also tried it with exactly the same commands to create the docker containers from the wiki page which result in the same error.

**Comment by voordev** [comment]
Also mail.domain.ltd is running correctly the nginx browser showing a 'welcome to nginx'

reallly lost on this, i have some basic knowledge of linux administration but this one i have been unable to resolve so far.

**Comment by voordev** [comment]
I will try to setup mail on windows tomorrow see of it works there.

Still unresolved :( 

After all the work i might need to consider another mail docker for testing. Really need my mailbox to be up if updates to this container break mailbox is not something i can afford.

Anyone of the "core team" can investigate this?

Can i get an older docker container of say a few releases back ? That way we can pinpoint if the cause is because how the mailserver behaves or if the problem lies within the letsencrypt cert creation.

**Comment by johansmitsnl** [comment]
The problemen is not the docker container. I do maintain the project. Your issue is the certificate.

Send me a message on gitter.

**Comment by voordev** [comment]
Hi Jonathan,

Thank you for your reply.
How do I reach you on Gitter?

Kind regards

**Comment by voordev** [comment]
With the help of Johan I was able to resolve this issue.
For future reference the issue was inside my docker-compose.yml

- /server/letsencrypt:/etc/letsencrypt/
had to become
  **- /server/letsencrypt/etc:/etc/letsencrypt/live**

**Comment by smitpatelx** [comment]
Same Here. I got this error in my gmail client. SSL certificate generated by letsencrypt shows this error:
```
Certificate Not Trusted
Subject: @commonName@
Issuer: @commonName@
```
