### ISSUE TITLE
Mail backup, possible to store the docker's /var/mail outside docker?

### ISSUE THREAD

**Issue by voordev** [tomav/docker-mailserver#1132]
Looking true the wiki and issue tracker i did not found a solution for storing mails inside the docker container , outside, the container.

I solved this by mounting the /var/mail folder outside the docker container, and would like to ask it this is a solid solution that would not break.

So I have:
```
/server/mailserver/config
/server/mailserver/var/mail <= new folder
```

Inside docker-compose.yml im adding below line like this:
```
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - /server/mailserver/var/mail:/var/mail
```

**Comment by johansmitsnl** [comment]
This is normal docker stuff. 
https://docs.docker.com/storage/volumes/

You can remove the mounts with maildata and state and point them to a position on your server.
