### ISSUE TITLE
Mailserver can have multiple domain name ?

### ISSUE THREAD

**Issue by Kubilai12** [tomav/docker-mailserver#1133]
Hi

Is it possible for one mailserver to have multiple domain name ?

For example i want use only one server but i want domain1.com and domain2.com use different name to contact same server

mail.domain1.com
mail.domain2.com

**Comment by johansmitsnl** [comment]
Please read the wiki before opening issues.

 https://github.com/tomav/docker-mailserver/wiki/Configure-Aliases

**Comment by Kubilai12** [comment]
No you don t understand i don t speak about alias, i speak about mail server himself

**Comment by Kubilai12** [comment]
For multiple domain do i need to use same MX entry like "mail.domain.com" redirect to IP 1.2.3.4 on each domain ?

or can i use : 
- for domain1.com the MX record mail.domain1.com redirect to IP 1.2.3.4
- for domain2.com the MX record mail.domain2.com redirect to IP 1.2.3.4

That mean i need for each domain  DMARC and DKIM dns entry and letsencryp cert

**Comment by johansmitsnl** [comment]
Check  #1100 and #1108
