### ISSUE TITLE
Dovecot handles emails case-sensitive

### ISSUE THREAD

**Issue by fleaz** [tomav/docker-mailserver#1134]
## Context

Hi,

when using the `setup.sh` to create new mail addresses, they get created in Dovecot with the same capitalization as provided via the CLI. So if you enter `setup.sh email add FooBar@domain.tld secretpassword" you get a mailbox for the user `FooBar`.

I know that the official RFC tells you that local user parts of an email address are case sensitive but literally nobody in the world handles them like this. And even the RFC tells you in the next paragraph that for interoperability reasons you also shouldn't do this. 

## Expected Behavior
The user `FooBar@domain.tld` gets an email when I write to `foobar@domain.tld`

## Actual Behavior
Postfix happily accepts the mail, hands it over to Dovecot, but Dovecot throws an "550 User unknown" because it handles them case-sensitive and only accepts `FooBar` and not `foobar`

## Possible Fix
As already stated in #174 the configuration should tell Dovecot to treat usernames as all-lowercase. This would imho be a sane default.

## Steps to Reproduce

1. Run `setup.sh email add FooBar@domain.tld secretpassword`
2. Write a email to `foobar@domain.tld`
3. Receive a 'returned to sender' message containing a "550 User unknown" error  

## Your Environment

* Amount of RAM available: 1G
* Mailserver version used: 'latest' from a few months ago... *cough*
* Docker version used: 18.09.1

**Comment by johansmitsnl** [comment]
Can you provide a pr for this fix?

**Comment by fleaz** [comment]
I'm current on a business trip but I will try to implement this when I'm back in the office next week :)

**Comment by erik-wramner** [comment]
If you do provide a PR for this I'd like to have it configurable. I think following the RFC and the default Dovecot configuration is a sane default as most users previously familiar with Dovecot would expect us to stay close to the default configuration.

Is this still relevant?

**Comment by fleaz** [comment]
Hi,
I tried to start working on this back then but had trouble executing the test suite and didn't wanted to commit something untested and then decided to just recreate the mailbox with an all lowercase address to quickly "fix" the problem because we were hosting this for a customer and they complained about not receiving all of their mails.

Currently we aren't using this container anymore, wherefore I forgot about this issue. And sadly I think I don't have the spare time to provide a fix for this at the moment.

**Comment by erik-wramner** [comment]
Right, I'll close this in the meantime then. Thanks.

**Comment by MohammedNoureldin** [comment]
Any news on this?
