### ISSUE TITLE
fail2ban too strict

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#1135]
## Context
fail2ban is too strict, resulting in clients unable to connect over IMAP and POP3 (timeout).
(Didn't notice at first that there is a fail2ban inside the mail server container).

## Expected Behavior
fail2ban ideally blocking/banning only attacking/misbehaving clients.

## Actual Behavior
Legitimate clients get sudden connection timeouts, notably SMTP and IMAP.

## Possible Fix
Use less strict fail2ban rules.

## Steps to Reproduce
- Connect with more than one mail client over IMAP.
- Few (2-3) attempts to log into IMAP/SMTP server (failed or not).

It would be nice if fail2ban is much more lenient because these blocks/bans happened while 
the mailserver was used realistically in real world.

**Comment by erik-wramner** [comment]
Personally I would recommend running with fail2ban disabled and would like to get rid of it from docker-mailserver; it should run on the host or possibly in a specialized container with access to the mail logs. Giving the mail container access to control the firewall feels wrong. As you didn't notice it at first it seems you didn't plan to use it from the start, so perhaps you can just turn it off?

If you do turn it off don't forget to remove the NET_ADMIN capability, it is only needed by fail2ban.

**Comment by j-marz** [comment]
@strarsis you can customise your fail2ban jail config by creating `fail2ban-jail.cf` in your config directory. https://github.com/tomav/docker-mailserver/wiki/Configure-Fail2ban
This file translates to `jail.local`. You can increase retry count using something like this:
```
[postfix]
maxretry = 10
```

@erik-wramner i think each app/service should be in it's own container tbh - clamav, fail2ban, dovecot, etc

**Comment by erik-wramner** [comment]
@j-marz that would be cleaner, but perhaps harder to deploy as most services are tightly coupled. However, I think fail2ban is something of a special case as it needs extra privileges to change the firewall rules. The other services are less demanding. Good that you found a solution!
