### ISSUE TITLE
[Question]: Does SpamAssasion learn from mails in a Spam/Junk folder?

### ISSUE THREAD

**Issue by swiesend** [tomav/docker-mailserver#1139]
Does SpamAssassin (SA) learn from mails in a Spam/Junk folder or tagged as spam in the current configuration of `docker-mailserver`? Is `sa-learn` used in the docker image?

Can someone give a brief overview on the data flow of `docker-mailserver` for spam mails?

## Context
Recently I receive a lot of spam with widely varying senders and content.

## Expected Behavior
* If a user tags a mail as spam, then SpamAssassin should recognize this and use them as training examples for spam. Vice-versa SA should remove mails which are not tagged as spam from the training examples for spam.

## Actual Behavior
* I don't know what the current behaviour is like.

## Your Environment
```docker-compose
$ cat docker-compose.yml
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: ***
    container_name: mail
    restart: always
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt/:/etc/letsencrypt/
    - /var/log/letsencrypt/:/var/log/letsencrypt/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - SA_TAG=2.0
    - SA_TAG2=6.31
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - POSTGREY_DELAY=10
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

**Comment by johansmitsnl** [comment]
Yes and no. Read https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-make-spamassassin-learn-spam

**Comment by swiesend** [comment]
Thanks!

**Comment by gszr** [comment]
> Yes and no. Read [Wiki: FAQ and Tips (how can i make spamassassin learn spam) (tomav/docker-mailserver)](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-make-spamassassin-learn-spam)

Updating the link: https://docker-mailserver.github.io/docker-mailserver/latest/faq/#how-can-i-make-spamassassin-better-recognize-spam
