### ISSUE TITLE
Override Default Postfix Configuration

### ISSUE THREAD

**Issue by boldt** [tomav/docker-mailserver#1140]
The [documentation is bit unclear.](https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration) You write:

>The Postfix default configuration can easily be extended by providing a `config/postfix-main.cf` in postfix format

What is the correct location for this file, e.g., mount point for the docker container, e.g.,

```bash
docker run -v postfix-main.cf:/???/config/postfix-main.cf....
```

I mean, it is not `/etc/postfix/main.cf`, since this file is generated while starting the server.

**Comment by boldt** [comment]
Is it `/tmp/docker-mailserver/postfix-main.cf`?

**Comment by johansmitsnl** [comment]
Yes: https://github.com/tomav/docker-mailserver/blob/7dbc96e908c579fb2cbfa18db08d980e72aea759/target/start-mailserver.sh#L1027

Please suggest changes to the documentation if unclear.

**Comment by boldt** [comment]
I just understood the whole concept. The `docker-compose.yml` has the following volume mount:

```
- ./config/:/tmp/docker-mailserver/
```

Thus the local `config/postfix-main.cf`will be mounted as `/tmp/docker-mailserver/postfix-main.cf`.

**Comment by boldt** [comment]
It works well. Thanks!
