### ISSUE TITLE
add hostname and domainname to env.

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [tomav/docker-mailserver#1142]
If you use the control panels, without these parameters you cannot successfully start the server.

**Comment by johansmitsnl** [comment]
This is set by the compose file: https://github.com/tomav/docker-mailserver/blob/7dbc96e908c579fb2cbfa18db08d980e72aea759/docker-compose.yml.dist#L6

**Comment by Pomazan-Bogdan** [comment]
If i build docker from https://www.portainer.io/ (rancher/etc), i have only env

**Comment by johansmitsnl** [comment]
Check the readme https://github.com/tomav/docker-mailserver/blob/master/README.md#override_hostname
