### ISSUE TITLE
Some postfix config can't be overriden when using RELAY_HOST

### ISSUE THREAD

**Issue by jedateach** [tomav/docker-mailserver#1143]
## Context

I'm wanting to deliver to different relay hosts, where one host is unencrypted. It's a local container running [mailhog](https://github.com/mailhog/MailHog) on internal network. It does not currently support TLS delivery.

## Expected Behavior

The documentation states you can override default postfix configuration: https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration

I want to set `smtp_tls_security_level = may`, so that my local relay host can receive messages  via un-encrypted transport.

I'd expect the configuration to supersede all other configuration, including when using a RELAY_HOST.

## Actual Behavior

The setup script appears to overwrite the config that I'm overwriting myself.
It ends up setting the postfix main configuration to be `smtp_tls_security_level = encrypt`, as seen in https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L1173

## Possible Fix

Re-order the `_setup_postfix_override_configuration` below the two different calls to `_setup_postfix_relay_hosts` in start-mailserver.sh.

## Steps to Reproduce

1. Set the `RELAY_HOST` environment variable
2. Add `smtp_tls_security_level = may` as per https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration
3. Create a relay host configuration using both encrypted an unencrypted methods
4. Try to email the host that doesn't support encryption

## Your Environment

* Amount of RAM available:
* Mailserver version used: latest, as of 9 Mar 2019
* Docker version used: 18.09.2
* Environment settings relevant to the config: RELAY_HOST, RELAY_PORT
* Any relevant stack traces ("Full trace" preferred):

**Comment by erik-wramner** [comment]
#1263

**Comment by erik-wramner** [comment]
This should be fixed in master/latest now, please reopen or submit a new issue if it doesn't help.
