### ISSUE TITLE
Enable "only" SSLv3 for testing?

### ISSUE THREAD

**Issue by boldt** [tomav/docker-mailserver#1145]
Unfortunately, my HP printer **HP LaserJet 200 colorMFP M276n** cannot deliver scans to the `docker-mailserver` ([German HP forum](https://h30492.www3.hp.com/t5/Drucker-und-AiO-Installation-und-Inbetriebnahme/SSL-TLS-f%C3%BCr-quot-Print-to-PDF-quot-konfigurieren/td-p/562314)). The log shows the following error:

> Mar 7 17:34:34 docker postfix/submission/smtpd[7447]: warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:1419:

Wrt. to #705 , the printer only tries SSLv3and noch TLSv1*. I would like to verify this, by only activating SSLv3 in a testing environment. I cannot see an option to do so.

**Comment by johansmitsnl** [comment]
Read https://github.com/tomav/docker-mailserver/blob/master/README.md#tls_level
