### ISSUE TITLE
DNS setup examples

### ISSUE THREAD

**Issue by iannazzi** [tomav/docker-mailserver#115]
@tomav 
Do you have any examples or references for setting up DNS? I have your docker image running in a digital ocean droplet. I have my domains registered through namecheap. I am assuming I need to point the nameserver records in namecheap to digital ocean, and in digital ocean possibly setup  mx records, however I am trying to follow & apply the [mail-in-a-box digital ocean setup tutorial](https://www.digitalocean.com/community/tutorials/how-to-run-your-own-mail-server-with-mail-in-a-box-on-ubuntu-14-04) which seems a bit off.

Thanks!

**Comment by KyleOndy** [comment]
I was actually thinking about getting some documentation written up. I'll put a PR together.

**Comment by iannazzi** [comment]
I would suggest including dns/mx entries in the readme install section. I would also modify the docker-compose.yml to be in a separate code block and include the ssl by default as in the docker-compose example in the FAQ. I think that would reduce some of the install issues that I had.

In the meantime, any hints on those mx entries?

**Comment by iannazzi** [comment]
you guys might also get a ton of love if you wrote an install guide specifically for digital ocean on [digitialocean.com](digitialocean.com), it seems like a couple other mail box creators have done so.

**Comment by iannazzi** [comment]
This is my setup
Namecheap: nameserver points to ns1.digitalocean.com, ns2,ns3....
Digital ocean: craiglorious.com: 
A record `mail` points to mail droplet IP (45.55.111.111)
MX entry points to `mail.craiglorious.com.` priority of 1
Digital ocean: craigiannazzi.com: 
A record `mail` points to mail droplet IP (45.55.111.111)
MX entry points to `mail.craigiannazzi.com.` priority of 1

accounts.cf:
```
craig@craiglorious.com|secret
me@craigiannazzi.com|secret
```

Docker container:
`cd13bdb01127        tvial/docker-mailserver   "/bin/sh -c /usr/loca"   2 hours ago         Up 2 hours          0.0.0.0:25->25/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:587->587/tcp, 110/tcp, 0.0.0.0:993->993/tcp, 995/tcp   root_mail_1`

Testing in mac mail:
IMAP hostname mail.craiglorious.com
IMAP path prefix: INBOX
Port 993 use ssl

Which gives me 'unable to verify account name or password'

Likewise for mail.craigiannazzi.com

Thanks Again!

**Comment by KyleOndy** [comment]
what are you trying to use as account name in mac mail?

**Comment by iannazzi** [comment]
craig@craiglorious.com <mailto:craig@craiglorious.com> and me@craigiannazzi.com <mailto:me@craigiannazzi.com>

I am going in to try gmail as sometimes mac mail is odd....

**Comment by KyleOndy** [comment]
It looks like you have DNS setup right for the craiglorious.com domain, confirmed by that fact that you are getting an `unable to verify account name or password` error. The login should be the full username, as you tried.

I don't see the DNS setup for craigiannazzi.com.

I would try getting one or the other working, then mirror the setup.

**Comment by iannazzi** [comment]
OK, digging through the closed issues I did find [http://checktls.com/](http://checktls.com/) which hints to me ssl is not installed which it is not, I skipped over that part of the docs. I will go through your ssl docs
