### ISSUE TITLE
How to forward mail. Not an alias.

### ISSUE THREAD

**Issue by wudgaby** [tomav/docker-mailserver#1151]
For example, postfix-accounts.cf defines 3 accounts.
Admin@domain.com, a@domain.com and b@domain.com
Admin@domain.com is used to receive all mail from other accounts.

If defined in postfix-virtual.cf
A@domain.com admin@domain.com
B@domain.com admin@domain.com

Then, when sent to a@domain.com or b@domain.com, admin@domain.com can receive mail.
However, there is no mail at a@domain.com and b@domain.com.
Maybe this is the role of the alias.

But the function I want is to forward the mail. This means that when sent to a@domain.com, both a@domain.com and admin@domain.com have mail.

Forwarding and aliasing should be two different functions.
So how do you set up forwarding?

**Comment by johansmitsnl** [comment]
The alias/forward rule is first and after the rule the email is not valid anymore for A and B. You can use a sieve rule for forward the email on the A and B mailbox.

**Comment by erik-wramner** [comment]
Can this be closed, or do we need to do something?

**Comment by fbartels** [comment]
@erik-wramner sounds like a resolved question to me
