### ISSUE TITLE
Certbot on host machine

### ISSUE THREAD

**Issue by realkarmakun** [tomav/docker-mailserver#1153]
I have certbot on my host machine, and wanted it to work with docker-mailserver. Is there any way to do that?

**Comment by 501st-alpha1** [comment]
This shouldn't be a problem.  Did you have a specific issue with it?

I got this working by mounting `/etc/letsencrypt` in the container (or you could probably manage with just a specific subfolder, but I haven't tried that yet).  So add the following line under `volumes:` in your `docker-compose.yml`:

```
    - /etc/letsencrypt:/etc/letsencrypt
```

Then you can run certbot on your host, and next time you start your docker-mailserver it will see the certs.

I don't think I did anything else other than set `SSL_TYPE` to `letsencrypt` in my `.env`, but let me know if that doesn't work and I'll go through my configs again.
