### ISSUE TITLE
Supervisord using 100% CPU

### ISSUE THREAD

**Issue by 132ikl** [tomav/docker-mailserver#1158]
## Context
Linux 4.9.0-8-amd64
Debian 9 Stretch 

Supervisord sporadically uses 100% CPU. It seems to randomly start using 100% CPU. After restarting the container CPU usage is back to normal, and `pkill`ing supervisord does no harm either. However, it has to be with the -9 flag. (Maybe indicative of a freeze?)

## Expected Behavior

Supervisord should not use 100% CPU.

## Actual Behavior

Supervisord uses 100% CPU.
## Possible Fix

Related to this?
https://github.com/Supervisor/supervisor/issues/807
## Steps to Reproduce

Sorry, I don't know how this is reproducible.

## Your Environment

* Amount of RAM available: 512
* Mailserver version used: Latest (How do you get the actual version?)
* Docker version used: 1.23.2

**Comment by erik-wramner** [comment]
The linked issue mentions disabling supervisor logging as a workaround. Perhaps you can try to change `target/supervisor/conf.d/supervisor-app.conf` and set `stdout_logfile=NONE` for all programs (possibly stderr_logfile=NONE as well if that doesn't help? At least if that solves the problem we know the cause and if it doesn't, well then we can write that off.

**Comment by 132ikl** [comment]
I've moved to a different server since this issue, and the problem no longer exists for me, so I can't test. Sorry.

**Comment by 132ikl** [comment]
I've moved to CentOS from Debian since I've made this issue, and haven't had this problem since, so I can't test it. Sorry.

**Comment by erik-wramner** [comment]
Right. Out of curiosity, did you fork the repo and build your own image based on CentOS, or do you mean that you are using CentOS as host rather than Debian as host?

**Comment by 132ikl** [comment]
The latter.

**Comment by biberino** [comment]
I had the same issue on Ubuntu 18.04 as the host os. 1 CPU core was at 100% for more than 2 days. A restart of the docker container solved the issue.
