### ISSUE TITLE
Proposal: Continue with versioning

### ISSUE THREAD

**Issue by boldt** [tomav/docker-mailserver#1160]
# Proposal

Looking into the tags, the last "version" was 6.1.0 nine month ago. Since then, only the ´latest´-tag was updated.

# Why

The `latest` tag is usually the development tag. 

Thus, with versions it is easier to check, whether there is a new version, e.g., an update, available. Especially for automatic tools. Also if an update fails, it's easy to rollback to the previous version (of course with a backup)

Also your slogan is: 

> Keep it simple and versioned

**Comment by tomav** [comment]
Yep, we'll keep this.
I'll release a new version when after a clean of some issues/merge requests.
