### ISSUE TITLE
Getting Daily Spamassassin reports although Spamassassin and Daily Reports are disabled

### ISSUE THREAD

**Issue by SebastianMuskalla** [tomav/docker-mailserver#1161]
I am running the latest version of the container.
I am getting a daily report from `Cron Daemon <root@mail.MYDOMAIN.de>`
that looks as follows:

```
/etc/cron.daily/spamassassin:
Cannot open file /var/lib/spamassassin/3.004002/updates_spamassassin_org/MIRRORED.BY: No such file or directory at /usr/bin/sa-update line 1600.
May  3 05:09:45.621 [18572] dbg: logger: adding facilities: all
May  3 05:09:45.622 [18572] dbg: logger: logging level is DBG
May  3 05:09:45.622 [18572] dbg: generic: SpamAssassin version 3.4.2
...
May  3 05:09:45.917 [18572] dbg: config: read file /etc/spamassassin/v342.pre
May  3 05:09:45.917 [18572] dbg: config: using "/var/lib/spamassassin/3.004002" for sys rules pre files
May  3 05:09:45.917 [18572] dbg: config: using "/var/lib/spamassassin/3.004002" for default rules dir
config: no rules were found!  Do you need to run 'sa-update'?
run-parts: /etc/cron.daily/spamassassin exited with return code 1
```

However, my docker-compose file has  `- ENABLE_SPAMASSASSIN=0` and `- REPORT_RECIPIENT=0`   which should both disable spamassassin and the daily reports.
(Indeed, the server displays something like `spamassassin is disabled` in its log during startup).

Is this a bug?
How can I disable the reports?

**Comment by erik-wramner** [comment]
Well, this is not one of those reports but a failure notification from cron. If you are not using spamassassin I would suggest removing the `/etc/cron.daily/spamassassin` file (just delete it). Then the cron job that fails will no longer run and as you are not using spamassassin you don't need to update the spam database anyway.

Perhaps the container should be smarter about this and remove the cron job automatically when spamassassin is off. I would guess that most people want it on though.

**Comment by erik-wramner** [comment]
The spamassassin cron job should be disabled by start-mailserver.sh in the same way as the freshclam job is disabled when clamd is off. Should be simple to fix.

**Comment by erik-wramner** [comment]
See #1222.

**Comment by erik-wramner** [comment]
Please try the latest version (building now, should be out in less than an hour).
