### ISSUE TITLE
Documetation request: mailstate

### ISSUE THREAD

**Issue by boldt** [tomav/docker-mailserver#1164]
The `docker-compose.yml` contains a volume called `mailstate`. For what is it used for?

**Comment by erik-wramner** [comment]
When ONE_DIR=1 it stores all the state for the servers except for e-mails and configuration. That includes but is not limited to virus mails, the clamd virus database, dhparams files for dovecot and postfix, the spool and the postgrey database. In short everything that should survive when the container is recycled and that is not configuration or delivered e-mails.

This is (kind of) documented in the main README for ONE_DIR:

> 1 => consolidate all states into a single directory (/var/mail-state) to allow persistence using docker volumes

**Comment by tomav** [comment]
Updated FAQ => https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#what-about-mail-state-folder
