### ISSUE TITLE
Maximum number of connections from user+IP exceeded

### ISSUE THREAD

**Issue by kuba-orlik** [tomav/docker-mailserver#1165]
I have two `docker-mailserver`s set up. On both of them every day one of my email clients fails to connect with an error message saying "Maximum number of connections from user+IP exceeded".

## Expected Behavior
I'd expect the server not to throw an error and let me through :) 

## Actual Behavior
The server responds with the aforementioned  error

## Possible Fix
I'd like to configure the `mail_max_userip_connections` flag, but I'm not sure how to do this "the right way" with docker-mailserver

## Steps to Reproduce
1. Setup a mailserver the regular way
2. Connect to it with Thunderbird, mu4e and FairMail (android)
3. Wait a few hours
4. See the error

## Your Environment

* Amount of RAM available: 8G
* Mailserver version used: not sure how to check it. Here's what docker images has to say about this: `tvial/docker-mailserver       latest              6454e7290040        3 months ago `
* Docker version used: `18.09.3`
* Environment settings relevant to the config: none I could think of
* Any relevant stack traces ("Full trace" preferred): 

```
May 14 15:16:30 mail dovecot: imap-login: Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10): user=<redacted>, method=PLAIN, rip=<redacted>, lip=<redacted>, TLS, session=<redacted>
```

**Comment by johansmitsnl** [comment]
Add https://serverfault.com/a/385190 to the config file like the wiki: https://github.com/tomav/docker-mailserver/wiki/Override-Default-Dovecot-Configuration
