### ISSUE TITLE
DEFAULT_RELAY_HOST is not applied in main.cf

### ISSUE THREAD

**Issue by madmath03** [tomav/docker-mailserver#1169]
## Context

Even though the `DEFAULT_RELAY_HOST` is set, the `relayhost` in /etc/postfix/main.cf is not updated.

I was trying to configure the mailserver to use the MailJet SMTP relay. MailJet doc requires the following configuration for postfix:
* In `main.cf`:
```
relayhost = in-v3.mailjet.com
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
```
* In `sasl_passwd`:
```
in-v3.mailjet.com username:password
```

Based on the mailserver documentation [Configure Relay Hosts](https://github.com/tomav/docker-mailserver/wiki/Configure-Relay-Hosts) and what I found in `start-mailserver.sh`, I set the following environments variables:
```
      - DEFAULT_RELAY_HOST=[in-v3.mailjet.com]:25
      - RELAY_HOST=in-v3.mailjet.com
      - RELAY_PORT=25
      - RELAY_USER=username
      - RELAY_PASSWORD=password
```

## Expected Behavior

When setting `DEFAULT_RELAY_HOST`, the `relayhost` in /etc/postfix/main.cf should reflect the value.

## Actual Behavior

`relayhost` stays empty:
```
relayhost = 
```

## Your Environment

* Amount of RAM available:
* Mailserver version used: 6.1.0
* Docker version used: 18.03.0-ce, build 0520e24
* Environment settings relevant to the config: `DEFAULT_RELAY_HOST` RELAY_HOST RELAY_PORT RELAY_USER RELAY_PASSWORD
* Any relevant stack traces ("Full trace" preferred):

**Comment by rroblik** [comment]
Hi, 

Are you sure to use the `latest`version (docker `latest` tag) ?
Versioning is poor on this project, I had the same issue before realise the versioning problem here.

See https://github.com/tomav/docker-mailserver/commit/a3724fa91d84854adfa90fb20a305e308ebcfb79 

BR

**Comment by madmath03** [comment]
Hi @rroblik ,

I'm using the `6.1.0` tag, but you are right : I missed the fact that the `DEFAULT_RELAY_HOST` support hasn't been released yet (latest release is from 31 Jul 2018, while the commit you pointed out is from 19 Jan 2019).

So, this is issue is not really an issue, more like a lack of new release since almost a year now...
Thanks for pointing that out 😉 

I will close this ticket and maybe create a new one to ask for next stable release.
