### ISSUE TITLE
Feature: (optionally) include Dovecot encryption plugin or MailCrypt

### ISSUE THREAD

**Issue by alexanderadam** [tomav/docker-mailserver#1171]
I just stumbled  [over this Dovecot encryption plugin](https://github.com/posteo/scrambler-plugin) and [MailCrypt](https://doc.dovecot.org/configuration_manual/mail_crypt_plugin/) (there are also GUIs for it [like Userli](https://github.com/systemli/userli)) which allows to have encrypted mailboxes. [Userli don't have a Docker image yet](https://github.com/systemli/userli/issues/186), though.

It might be especially useful for the folks that focuses on security.

MailCrypt is an official plugin from the Dovecot maintainers, so this might be the better choice in my opinion. It has different modes. The global mode is probably much easier to implement for now but of course the user mode (i.e. in combination with Userli) is security wise even better. So if someone considers working on it, it might be better to split this issue up in
1. "global encryption" for now and 
2. "user encryption" for later or so.

There are various tutorials [howto setup MailCrypt](https://workaround.org/ispmail/buster/optional-server-based-mailbox-encryption/) and maybe it would make sense to take a look on [the implementation of mailcow](https://github.com/mailcow/mailcow-dockerized/search?q=mail+crypt&type=Commits) ([1791](https://github.com/mailcow/mailcow-dockerized/issues/1791)).

Or maybe it would even better if an approach, that's compatible to Pretty Easy privacy (p≡p), would be used.
For instance like described in [Julian's blog post](https://blog.jak-linux.org/2019/06/13/encrypted-email-storage/).

**PS:** they also have [a PGP/MIME roundcube plugin](https://github.com/posteo/show_pgp_mime)
**PPS:** is there any update regarding the [antispam plugin](https://github.com/tomav/docker-mailserver/issues/384)?

**Comment by aendeavor** [comment]
This is rather interesting; I'm surprised no one picked this up. To be fair tough, time is the critical factor. If you want this to be in upstream, you'd need to invest some time yourself, to be honest. I'll first of all flag this properly. Could you provide me with an update on the current status?

**Comment by alexanderadam** [comment]
> Could you provide me with an update on the current status?

I'm not sure which status you mean. I guess nobody did anything, since nobody commented otherwise.
Or what status do you mean?

And why is this issue related to a firewall (I'm asking because of the tag)? :thinking:

**Comment by aendeavor** [comment]
Alright, thanks. I just wanted to know whether anything was done by you.

I clicked on the firewall tag by accident.

**Comment by aendeavor** [comment]
I haven't had time to came back here the last days.

@alexanderadam I guess you're not working on this by accident? If this was the case, I would keep this issue open. But since it looks like this has never been picked up, and is older than one year, I would close this off and mark it as frozen. Anyone could pick this up again in the future then.

**Comment by alexanderadam** [comment]
No, I'm sorry. I'm not even good with email infrastructure in general.

**Comment by aendeavor** [comment]
> No, I'm sorry. I'm not even good with email infrastructure in general.

Alright, no problem.

I'll mark this as frozen. Everyone feel free to re-open if necessary.

**Comment by DavyLandman** [comment]
As I've spent quite some time trying to figure out how the "user encryption" option could be used in combination with docker-mailserver, I think I can say that the crypto plugin assumes a database (where you can on the fly create fields that pass the password to the crypto plugin to use for unlocking). 

In the global encryption option, the key has to be stored on the filesystem. and except if you make [some kind of temporary file](https://blog.onefellow.com/post/173796677183/how-to-obfuscate-dovecot-encryption-key) I do not see the benefit of encrypting your data while also storing the key next to it. (Maybe it's different if you plan to host the data volume somewhere less trusted).

**Comment by besendorf** [comment]
Yes this is exactly the point. The global option is only usefull when you store the data volume somewhere else (e.g. on Amazon S3). Only the user encryption has benefit for privacy/security if both data is on the same server. Here's a thesis comparing different solutions. Unfortunatly its in German:
https://wiki.ipv6lab.f1.htw-berlin.de/_media/public_v6/thesis/fichtner_2019.pdf

**Comment by DavyLandman** [comment]
After asking a question on the dovecot mailing list, i've managed to make it work.

@aendeavor I could share the config changes I did, but I wouldn't know the best way to integrate it into this nice configurable setup.

**Comment by aendeavor** [comment]
@DavyLandman There is currently a PR in the works (#1826). When this PR is merged, you could maybe pick a spot in the wiki and post your findings there:)

**Comment by DavyLandman** [comment]
> 
> 
> @DavyLandman There is currently a PR in the works (#1826). When this PR is merged, you could maybe pick a spot in the wiki and post your findings there:)

cool, I had to override some files (specfically `auth-passwdfile.inc`) and adding users/changing password is now more complex. So I'm wondering if it might be a future we want to include in the setup.sh as well (and some flags to enable/disable this feature)?

Since my current approach is a bit hacking around some config files, that I don't really prefer. I'll try to make it less hackity soon, but I fear that you would be a lot quicker.  If not a priority, okay I'll do my best to describe it and let other users figure it out.

**Comment by NorseGaud** [comment]
> After asking a question on the dovecot mailing list, i've managed to make it work.
> 
> @aendeavor I could share the config changes I did, but I wouldn't know the best way to integrate it into this nice configurable setup.
> 
> for people getting here when they are trying it themselves:
> 
> ```
> passdb {
> ....
>   override_fields = userdb_mail_crypt_private_password=%w userdb_mail_crypt_save_version=2
> }
> ```
> 
> this does the trick, but there is more stuff to change, but that follows from following the instructions out there. this line is the passwd-file specific thing.

Hi @DavyLandman , what file did you edit and add the passdb to? I'm cool with helping write some setup.sh code to simplify the changing of passwords for this, just need sort of a full picture of what exactly was changed to get it working.

**Comment by DavyLandman** [comment]
@NorseGaud I've just opened up the config for you, I had some other stuff I had to take care of, cool if you can pick this up!

custom mappings in docker container:
```
     - ./config/:/tmp/docker-mailserver
      - ./config/10-crypt.conf:/etc/dovecot/conf.d/10-crypt.conf:ro
      - ./config/auth-passwdfile.inc:/etc/dovecot/conf.d/auth-passwdfile.inc:ro
``` 

`config/10-cryp.conf`:
```
mail_attribute_dict = file:%h/Maildir/dovecot-attributes
mail_plugins = $mail_plugins mail_crypt
mail_debug= yes

plugin {
  mail_crypt_curve = secp521r1
  mail_crypt_save_version = 2
  mail_crypt_require_encrypted_user_key = yes
}
```

`config/auth-passwdfile.inc` (this is the one that I had to override from the default config)
```
# Authentication for passwd-file users. Included from 10-auth.conf.
#
# passwd-like file with specified location.
# <doc/wiki/AuthDatabase.PasswdFile.txt>


passdb {
  driver = passwd-file
  args = scheme=CRYPT username_format=%u /etc/dovecot/userdb
  override_fields = userdb_mail_crypt_private_password=%w userdb_mail_crypt_save_version=2
}


userdb {
  driver = passwd-file
  args = username_format=%u /etc/dovecot/userdb

  default_fields = uid=docker gid=docker home=/var/mail/%d/%u
#userdb_mail_crypt_private_password=%w userdb_mail_crypt_save_version=2

  # Override fields from passwd-file

  #override_fields = home=/home/virtual/%u
  #override_fields = userdb_mail_crypt_private_password=%{sha256:password} userdb_mail_crypt_save_version=2
 # override_fields = userdb_mail_crypt_private_password=%w userdb_mail_crypt_save_version=2

}
```

and now looking at the manuals you should be able to set it up. I also think that it would be nicer to use the `sha256` of the password as key as directly the key.
