### ISSUE TITLE
telnet mail.xxxx.xxx 993 disconnect immediately

### ISSUE THREAD

**Issue by zachary** [tomav/docker-mailserver#1173]
once docker-compose up -d
i tried to telnet mail.xxxx.xx 993 but disconnected immediately, even i tried this in the container.
please advise it.

thanks

**Comment by erik-wramner** [comment]
Well, I can telnet to 993, but as it is a TLS (SSL) port and telnet doesn't do encryption the server disconnects when the handshake fails. I think you should try:
`
openssl s_client -connect mail:993
`
That will give you a telnet-like connection that handles encryption. Does that work better?

**Comment by tomav** [comment]
@erik-wramner is right.
https://www.anta.net/useful-tips/how-to-test-an-imap-server-by-using-telnet/
