### ISSUE TITLE
No release since about one year, how about a release

### ISSUE THREAD

**Issue by metawave** [tomav/docker-mailserver#1174]
Why did you abandonned releasing every now and then? No new release since last july.

**Comment by voxsar** [comment]
maybe it has reached ultimate perfection :D :dancing_men: JK

**Comment by metawave** [comment]
@voxsar it is good, don't get me wrong! But using latest tags for images when running containers comes with it's pros and cons. I'd rather use a fixed version where I know what works and what doesn't... so I can configure it accordingly... with an ever-changing image, this seems to be a bit unstable

**Comment by metawave** [comment]
seems to be a duplicate of #1160
