### ISSUE TITLE
Enabling Dovecot's Push Notifications

### ISSUE THREAD

**Issue by Joseph310** [tomav/docker-mailserver#1181]
Hi, 
I was thinking about giving this docker a spin. I was wondering if anyone has tried integrating https://wiki.dovecot.org/Plugins/PushNotification 
Thanks

**Comment by erik-wramner** [comment]
Given the absolute silence I would guess that the answer is no.

**Comment by keitgen** [comment]
I have abandoned this entirely and moved to hosted exchange.

**Comment by Joseph310** [comment]
I have abandoned this entirely and moved to hosted exchange.
