### ISSUE TITLE
Email server is not using BATV format while sending out emails. BATV is recommended to ensure that your users do not become a victim of bounce floods.

### ISSUE THREAD

**Issue by albertoZurini** [tomav/docker-mailserver#1184]
I've tried sending an email to test [at] allaboutspam [dot] com and the only error I can't fix is this: ```Email server is not using BATV format while sending out emails. BATV is recommended to ensure that your users do not become a victim of bounce floods.```

--
## Context
This issue may cause the mail I send to be rejected by GMail or Yahoo.
SPF and DKIM have already been configured correctly.

## Expected Behavior
With BATV format email rejection should not happen.

## Actual Behavior
```Email server is not using BATV format while sending out emails. BATV is recommended to ensure that your users do not become a victim of bounce floods.```

## Steps to Reproduce
1. Install and start the container
2. Configure DNS
3. Send email to test [at] allaboutspam [dot] com
4. Wait for the test report

## Your Environment
* Amount of RAM available: 1GB
* Mailserver version used: 2
* Docker version used: 18.09.7, build 2d0083d
* Environment settings relevant to the config: none
* Any relevant stack traces ("Full trace" preferred): none

**Comment by erik-wramner** [comment]
According to https://ubuntuforums.org/showthread.php?t=2253770, BATV is only for your own protection, it will not help getting your messages delivered. It is also complex to setup, As far as I can tell it is not supported by Postfix, but has to be added as a proxy in front of it (see http://babel.de/batv.html). It could perhaps be added as an optional feature, but I'm not sure if it is worth it and if it plays nice with the other components, notably postgrey. I'm generally vary of custom scripts that are too far from mainstream use in security sensitive areas such as mail.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
