### ISSUE TITLE
Domain name doubled in Containers Hostname

### ISSUE THREAD

**Issue by n73671** [tomav/docker-mailserver#1189]
Ive created a mail docker container with these domain name settings (set in the .env) file:

>HOSTNAME=mail
>DOMAINNAME=mytestmail.com
>OVERRIDE_HOSTNAME=mail.mytestmail.com

When i login with bash into the new created container and execute the hostname command, i receive:
>mail.mytestmail.commytestmail.com

As my hostname. So the Domain Name is doubled.

## Context
Checking the mail server security with mxtoolbox.com responds that my SMTP Banner differs from the expected hostname. Some mail servers would assume this as spam.

## Expected Behavior
The hostname of the container should be mail.mytestmail.com.

## Actual Behavior
The domain name is doubled.

## Your Environment

* Amount of RAM available: 2GB
* Mailserver version used: latest (May 14, 2019 10:17 PM)
* Docker version used: 18.09.7, build 2d0083d

**Comment by semiversus** [comment]
@n73671 Always leave a comment when closing an issue. Even it was e.g. your own mis-configuration - it will help others.
