### ISSUE TITLE
Nothing listen port 25

### ISSUE THREAD

**Issue by igor-d-n** [tomav/docker-mailserver#1193]
## Actual Behavior
Nothing listening port 25
State           Recv-Q           Send-Q                        Local Address:Port                        Peer Address:Port           
LISTEN          0                128                           127.0.0.53%lo:53                               0.0.0.0:*              
LISTEN          0                128                                 0.0.0.0:22                               0.0.0.0:*              
LISTEN          0                128                                    [::]:22                                  [::]:*              
LISTEN          0                128                                       *:993                                    *:*              
LISTEN          0                128                                       *:995                                    *:*              
LISTEN          0                128                                       *:32776                                  *:*              
LISTEN          0                128                                       *:587                                    *:*              
LISTEN          0                128                                       *:143                                    *:*  

## Steps to Reproduce

1. Just install as example.
Can't understand what may be wrong. Nothing was changed. Just added dkim, some accounts and that's all.

## Your Environment

* Amount of RAM available: 2
* Mailserver version used: latest
* Docker version used: latest
* Environment settings relevant to the config:  
* Any relevant stack traces ("Full trace" preferred):

**Comment by 501st-alpha1** [comment]
What is the output of `docker-compose logs`? Are there any errors there?

**Comment by igor-d-n** [comment]
2019-07-22 12:38:24,540 CRIT Supervisor running as root (no user in config file)
2019-07-22 12:38:24,541 INFO Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
2019-07-22 12:38:24,541 INFO Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
2019-07-22 12:38:24,553 INFO RPC interface 'supervisor' initialized
2019-07-22 12:38:24,554 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-07-22 12:38:24,554 INFO supervisord started with pid 1
2019-07-22 12:38:25,558 INFO spawned: 'mailserver' with pid 8

2019-07-22 12:38:25,593 INFO success: mailserver entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

 docker-mailserver

Initializing setup
Checking configuration
Configuring mail server
Spamassassin is disabled. You can enable it with 'ENABLE_SPAMASSASSIN=1'
Starting Misc
Starting mail server
2019-07-22 12:38:29,992 INFO spawned: 'cron' with pid 117
2019-07-22 12:38:29,993 INFO success: cron entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
cron: started
2019-07-22 12:38:30,290 INFO spawned: 'rsyslog' with pid 119
2019-07-22 12:38:30,291 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
rsyslog: started
2019-07-22 12:38:30,585 INFO spawned: 'dovecot' with pid 123
2019-07-22 12:38:30,586 INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
dovecot: started
2019-07-22 12:38:30,969 INFO spawned: 'opendkim' with pid 130
2019-07-22 12:38:30,970 INFO success: opendkim entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
opendkim: started
2019-07-22 12:38:31,309 INFO spawned: 'opendmarc' with pid 138
2019-07-22 12:38:31,310 INFO success: opendmarc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
opendmarc: started
2019-07-22 12:38:31,611 INFO spawned: 'postfix' with pid 145
2019-07-22 12:38:31,612 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
postfix: started
2019-07-22 12:38:32,126 INFO spawned: 'fail2ban' with pid 205
2019-07-22 12:38:32,126 INFO success: fail2ban entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
fail2ban: started
2019-07-22 12:38:33,038 INFO reaped unknown pid 279
2019-07-22 12:38:33,068 INFO spawned: 'clamav' with pid 285
2019-07-22 12:38:33,069 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
clamav: started
2019-07-22 12:38:34,427 INFO spawned: 'changedetector' with pid 363
2019-07-22 12:38:34,428 INFO success: changedetector entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
changedetector: started
2019-07-22 12:38:35,692 INFO reaped unknown pid 247
2019-07-22 12:38:35,739 INFO spawned: 'amavis' with pid 463
2019-07-22 12:38:35,740 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
amavis: started

noreply.daichi.ru is up and running

Jul 22 12:38:37 noreply amavis[463]: starting. /usr/sbin/amavisd-new at noreply.daichi.ru amavisd-new-2.10.1 (20141025), Unicode aware
Jul 22 12:38:37 noreply amavis[463]: Net::Server: Group Not Defined.  Defaulting to EGID '111 111'
Jul 22 12:38:37 noreply amavis[463]: Net::Server: User Not Defined.  Defaulting to EUID '109'
Jul 22 12:38:37 noreply amavis[463]: Module Amavis::Conf        2.404
Jul 22 12:38:37 noreply amavis[463]: Module Archive::Zip        1.59
Jul 22 12:38:37 noreply amavis[463]: Module BerkeleyDB          0.55
Jul 22 12:38:37 noreply amavis[463]: Module Compress::Raw::Zlib 2.069
Jul 22 12:38:37 noreply amavis[463]: Module Compress::Zlib      2.069001
Jul 22 12:38:37 noreply amavis[463]: Module Digest::MD5         2.54
Jul 22 12:38:37 noreply amavis[463]: Module Encode              2.80_01
Jul 22 12:38:37 noreply amavis[463]: Module File::Temp          0.2304
Jul 22 12:38:37 noreply amavis[463]: Module IO::Socket::IP      0.37
Jul 22 12:38:37 noreply amavis[463]: Module MIME::Entity        5.508
Jul 22 12:38:37 noreply amavis[463]: Module MIME::Parser        5.508
Jul 22 12:38:37 noreply amavis[463]: Module MIME::Tools         5.508
Jul 22 12:38:37 noreply amavis[463]: Module Mail::Header        2.18
Jul 22 12:38:37 noreply amavis[463]: Module Mail::Internet      2.18
Jul 22 12:38:37 noreply amavis[463]: Module Net::LibIDN         0.12
Jul 22 12:38:37 noreply amavis[463]: Module Net::Server         2.008
Jul 22 12:38:37 noreply amavis[463]: Module Scalar::Util        1.4202
Jul 22 12:38:37 noreply amavis[463]: Module Socket              2.020_03
Jul 22 12:38:37 noreply amavis[463]: Module Time::HiRes         1.9733
Jul 22 12:38:37 noreply amavis[463]: Module Unix::Syslog        1.1
Jul 22 12:38:37 noreply amavis[463]: Amavis::ZMQ code     NOT loaded
Jul 22 12:38:37 noreply amavis[463]: Amavis::DB code      loaded
Jul 22 12:38:37 noreply amavis[463]: SQL base code        NOT loaded
Jul 22 12:38:37 noreply amavis[463]: SQL::Log code        NOT loaded
Jul 22 12:38:37 noreply amavis[463]: SQL::Quarantine      NOT loaded
Jul 22 12:38:37 noreply amavis[463]: Lookup::SQL code     NOT loaded
Jul 22 12:38:37 noreply amavis[463]: Lookup::LDAP code    NOT loaded
Jul 22 12:38:37 noreply amavis[463]: AM.PDP-in proto code loaded
Jul 22 12:38:37 noreply amavis[463]: SMTP-in proto code   loaded
Jul 22 12:38:37 noreply amavis[463]: Courier proto code   NOT loaded
Jul 22 12:38:37 noreply amavis[463]: SMTP-out proto code  loaded
Jul 22 12:38:37 noreply amavis[463]: Pipe-out proto code  NOT loaded
Jul 22 12:38:37 noreply amavis[463]: BSMTP-out proto code NOT loaded
Jul 22 12:38:37 noreply amavis[463]: Local-out proto code loaded
Jul 22 12:38:37 noreply amavis[463]: OS_Fingerprint code  NOT loaded
Jul 22 12:38:37 noreply amavis[463]: ANTI-VIRUS code      loaded
Jul 22 12:38:37 noreply amavis[463]: ANTI-SPAM code       NOT loaded
Jul 22 12:38:37 noreply amavis[463]: ANTI-SPAM-EXT code   NOT loaded
Jul 22 12:38:37 noreply amavis[463]: ANTI-SPAM-C code     NOT loaded
Jul 22 12:38:37 noreply amavis[463]: ANTI-SPAM-SA code    NOT loaded
Jul 22 12:38:37 noreply amavis[463]: Unpackers code       loaded
Jul 22 12:38:37 noreply amavis[463]: DKIM code            NOT loaded
Jul 22 12:38:37 noreply amavis[463]: Tools code           NOT loaded
Jul 22 12:38:37 noreply amavis[463]: Found $file            at /usr/bin/file
Jul 22 12:38:37 noreply amavis[463]: No $altermime,         not using it
Jul 22 12:38:37 noreply amavis[463]: Internal decoder for .mail
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .Z    at /bin/uncompress
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .gz   at /bin/gzip -d
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .bz2  at /bin/bzip2 -d
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .xz   at /usr/bin/xz -dc
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .lzma at /usr/bin/xz -dc --format=lzma
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .lrz  at /usr/bin/lrzip -q -k -d -o -
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .lzo  at /usr/bin/lzop -d
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .lz4  at /usr/bin/lz4c -d
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .rpm  at /usr/bin/rpm2cpio
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .cpio at /bin/pax
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .tar  at /bin/pax
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .deb  at /usr/bin/ar
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .rar  at /usr/bin/unrar-free
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .arj  at /usr/bin/arj
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .arc  at /usr/bin/nomarch
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .zoo  at /usr/bin/zoo
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .doc  at /usr/bin/ripole
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .cab  at /usr/bin/cabextract
Jul 22 12:38:37 noreply amavis[463]: Internal decoder for .tnef
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .zip  at /usr/bin/7za
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .kmz  at /usr/bin/7za
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .7z   at /usr/bin/7zr
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .jar  at /usr/bin/7z
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .swf  at /usr/bin/7z
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .lha  at /usr/bin/7z
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .iso  at /usr/bin/7z
Jul 22 12:38:37 noreply amavis[463]: Found decoder for    .exe  at /usr/bin/unrar-free; /usr/bin/arj
Jul 22 12:38:37 noreply amavis[463]: No decoder for       .F   
Jul 22 12:38:37 noreply amavis[463]: Using primary internal av scanner code for ClamAV-clamd
Jul 22 12:38:37 noreply amavis[463]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Jul 22 12:38:37 noreply amavis[463]: Deleting db files  in /var/lib/amavis/db
Jul 22 12:38:37 noreply amavis[463]: Creating db in /var/lib/amavis/db/; BerkeleyDB 0.55, libdb 5.3
Jul 22 12:38:39 noreply postfix/master[932]: daemon started -- version 3.1.12, configuration /etc/postfix

**Comment by igor-d-n** [comment]
I see no errors here. But still got:
State               Recv-Q               Send-Q                              Local Address:Port                               Peer Address:Port               
LISTEN              0                    128                                 127.0.0.53%lo:53                                      0.0.0.0:*                  
LISTEN              0                    128                                       0.0.0.0:22                                      0.0.0.0:*                  
LISTEN              0                    128                                          [::]:22                                         [::]:*                  
LISTEN              0                    128                                             *:993                                           *:*                  
LISTEN              0                    128                                             *:995                                           *:*                  
LISTEN              0                    128                                             *:32777                                         *:*                  
LISTEN              0                    128                                             *:587                                           *:*                  
LISTEN              0                    128                                             *:143                                           *:*   

Now I tried to see what's listening in container. Got:
State      Recv-Q Send-Q                                  Local Address:Port                                                 Peer Address:Port              
LISTEN     0      100                                                 *:993                                                             *:*                  
LISTEN     0      128                                         127.0.0.1:10024                                                           *:*                  
LISTEN     0      100                                         127.0.0.1:10025                                                           *:*                  
LISTEN     0      100                                                 *:587                                                             *:*                  
LISTEN     0      128                                        127.0.0.11:44941                                                           *:*                  
LISTEN     0      100                                                 *:143                                                             *:*                  
LISTEN     0      100                                                 *:465                                                             *:*                  
LISTEN     0      100                                                 *:25                                                              *:*                  
LISTEN     0      128                                         127.0.0.1:8891                                                            *:*                  
LISTEN     0      128                                         127.0.0.1:8893                                                            *:*                  
LISTEN     0      100                                                :::993                                                            :::*                  
LISTEN     0      100                                                :::587                                                            :::*                  
LISTEN     0      100                                                :::143                                                            :::*                  
LISTEN     0      100                                                :::465                                                            :::*                  
LISTEN     0      100                                                :::25                                                             :::*                  

Strange. At docker-compose.yml:
....
    ports:
    - 25:25
    - 143:143
    - 587:587
    - 993:993
    - 995:995
...
it must work but it do not work. wtf?) Any ideas?

**Comment by igor-d-n** [comment]
Sorry. It's stupid yml parser:
>Note: When mapping ports in the HOST:CONTAINER format, you may experience erroneous results when using a container port lower than 60, because YAML parses numbers in the format xx:yy as a base-60 value. For this reason, we recommend always explicitly specifying your port mappings as strings.
I used 25:25 and got something idiotic - 60-based number. Why yml used such strange parser i can't understand.
