### ISSUE TITLE
Question on start-mailserver.sh and SASL_PASSWORD

### ISSUE THREAD

**Issue by 00angus** [tomav/docker-mailserver#120]
I've seen that in the code of start-mailserver.sh it has been introduced the use of SASL_PASSWORD env var. However when no passwd is being provided the script outputs a warning:

> Loaded '/tmp/postfix/main.cf'
> ==> Warning: 'SASL_PASSWORD' is not provided. /etc/postfix/sasl_passwd not created.

I find this warning not necessary. Could we leave simply the message without the warning?
Or it has been left there for a specific reason? For the parsing of main.cf the warning has been removed, for example, by the PR #104 .

**Comment by tomav** [comment]
I agree. If optional, it should be an `Info`.

**Comment by tomav** [comment]
Feel free to PR.

**Comment by tomav** [comment]
Fixed.
