### ISSUE TITLE
OpenDKIM key retrieval failed - query timed out

### ISSUE THREAD

**Issue by j-marz** [tomav/docker-mailserver#1204]
## Context
OpenDKIM is not able to verify DKIM on inbound emails as it's not able to retrieve public key from DNS. The following error logs are observed in logs `key retrieval failed - query timed out`

## Expected Behavior
OpenDKIM should be able to download public key from DNS.

## Actual Behavior
OpenDKIM appears to be using root name servers instead of the name servers defined in /etc/resolv.conf. This breaks DNS in environments where outbound firewall rules restrict access to specific name servers (ie. those defined in /etc/resolv.conf).

## Possible Fix
Set the `Nameservers` parameter in /etc/opendkim.conf to the name servers defined in /etc/resolv.conf

**Comment by erik-wramner** [comment]
@j-marz please check if this can be closed now that the PR is merged?

**Comment by j-marz** [comment]
@erik-wramner just pulled the latest image and confirmed nameserver is set and key retrieval is working, so closing this issue.
