### ISSUE TITLE
Speed up docker build by moving key generation into container startup

### ISSUE THREAD

**Issue by fbartels** [tomav/docker-mailserver#1212]
While going through the Dockerfile in https://github.com/tomav/docker-mailserver/pull/1194 I noticed a few things that can be done to speedup the container build (and also improve security imho).

1. during the build freshclam is run in https://github.com/tomav/docker-mailserver/blob/2107793f7f7cf47342f4bcaa2817b946126e25f3/Dockerfile#L103
this action takes a while and also and ultimatively ends with a message that clamd could not be contacted, so maybe it does not even serve a purpose.
-> should be moved into a startup script

2. mkcert.sh creates a private key for dovecot in https://github.com/tomav/docker-mailserver/blob/2107793f7f7cf47342f4bcaa2817b946126e25f3/Dockerfile#L121
Potentially security relevant
-> should be done per installation in a startup script

3. the container build created two dhparam files (for dovecot and postfix each) in https://github.com/tomav/docker-mailserver/blob/2107793f7f7cf47342f4bcaa2817b946126e25f3/Dockerfile#L124 and https://github.com/tomav/docker-mailserver/blob/2107793f7f7cf47342f4bcaa2817b946126e25f3/Dockerfile#L184
dhparam should rather be generated per installation and therefore at container startup (which is afaik already the case for the postfix dhparam anyways, meaning that it get generated twice).
-> there should be a single dhparam for the whole container that are used from both dovecot and postfix

4. what is the purpose of regenerating dhparam via cron in https://github.com/tomav/docker-mailserver/blob/2107793f7f7cf47342f4bcaa2817b946126e25f3/Dockerfile#L185?
-> should be removed, does not feel necessary to me.

**Comment by erik-wramner** [comment]
For the first point freshclam downloads antivirus definitions. It tries to restart clamd and fails as clamd is not running, but that really doesn't matter, the antivirus definitions have been downloaded successfully. I would like to keep that in the build. If we move it to the startup script and freshclam fails (it does fail from time to time) we will be running without antivirus definitions and even if it succeeds it takes time. During that time we cannot receive messages (if we wait) or alternatively we will receive messages that we cannot check as clamd lacks its definitions.

If we rebuild the image on a daily basis (other JIRA) and run freshclam as part of the build we will always have antivirus definitions that are at most one day old from the get-go. That's not so bad and it is one thing less to do in the rather big startup script!

**Comment by erik-wramner** [comment]
@fbartels are you working on this or do you want me to grab it?

**Comment by fbartels** [comment]
@erik-wramner no I have not yet started with this. I wanted to finally close hadolint pr first. But you are welcome to take it over.

**Comment by erik-wramner** [comment]
Solved by #1220.
