### ISSUE TITLE
Can't disable amavis quarantine

### ISSUE THREAD

**Issue by jamesfryer** [tomav/docker-mailserver#1214]
Is there a way to disable the quarantine feature? I want to receive all emails. Ideally they should be marked with an X-Spam: header if they are spam or virus. I am seeing log entries such as this, and the email is placed into a file on the server:

Aug  5 14:55:47 mail amavis[22027]: (22027-09) Blocked SPAM {DiscardedInbound,Quarantined}, [...]:35863 [...] <***@***> -> <***@***>, quarantine: 7/spam-7vykgLjHGVrk.gz, Queue-ID: 23C7D524CFC, Message-ID: <D77AD57E-09C9-4208-9E18-6989E0A3E07E@***>, mail_id: 7vykgLjHGVrk, Hits: 6.642, size: 2666753, dkim_sd=***:***.uk, 9030 ms

I have looked in the documentation to no avail. Adding ENABLE_AMAVIS=0 has no effect (and isn't necessarily what I want, anyway).

**Comment by jamesfryer** [comment]
Is there perhaps a more appropriate place to ask questions such as the above?

**Comment by fbartels** [comment]
Hi @jamesfryer,

without having it tested, but I think you are looking for https://github.com/tomav/docker-mailserver/blob/8fb9a5780945cff0c8086850cc1bb1c4008f52b1/README.md#sa_kill.

**Comment by jamesfryer** [comment]
I'll give it a try, thanks.

**Comment by erik-wramner** [comment]
@jamesfryer, can you update the issue when you have tested, please? It is nice to know if it worked, plus that way we can close it if it has been answered.

**Comment by jamesfryer** [comment]
Will do -- when I see spam detected by my procmail script I will report back. I'd also suggest that the documentation for SA_KILL is enhanced. I needed to search the code, find it was passed through to sa_kill_level_deflt, and then find the docs for that. I set it to 100.0, I am not sure if there is a way to disable it altogether.

**Comment by fbartels** [comment]
Yes, looking at the code there is no way to fully disable it, so adding a very high threshold should practically prevent this behaviour.

@jamesfryer can you open a pull request with your suggested changes to the readme?

**Comment by jamesfryer** [comment]
This does seem to work. It would be nice to have a way to turn it off altogether. The background for this is that I had some client emails go to spam (they contained a link and little else). In this situation I'd rather the spam was delivered to my local machine and put into my spam folder by procmail, where I can easily find it, than to have it disappear into an obscure folder on the server. The subject lines are still marked with "***SPAM***" which I'd  prefer to avoid, but I can live with that. Thank you both and I will do a  pull request for the docs next week.

**Comment by jamesfryer** [comment]
Created the pull request, also found documentation for SA_SPAM_SUBJECT while I was doing it.
