### ISSUE TITLE
Invalid mynetworks when host interface is not named 'eth0'

### ISSUE THREAD

**Issue by sundbry** [tomav/docker-mailserver#1227]
All SMTP mail gets rejected due to an invalid mynetworks configuration when the host interface is not named 'eth0'. 

In this function, the primary interface of the host is assumed to be eth0, but it's not always named as such, and so an invalid mynetworks line gets written as ```mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64 /32``` (the /32 is invalid)

https://github.com/tomav/docker-mailserver/blob/9ac164ab648df166b5fd6d6a944af9d137ace290/target/start-mailserver.sh#L206

**Comment by erik-wramner** [comment]
Interesting. We had a discussion about interface naming not so long ago in another context. However, the start-mailserver.sh script should not run on the host but in the container and there the interface names should be more deterministic?

What do you get when you run `ip addr show eth0` in the container and what other interfaces do you have in the container? Plus how do you run the container (docker compose file)?

**Comment by sundbry** [comment]
I should have mentioned, I am using it in a hostNetworking: true context (in a Kubernetes controller).

**Comment by sundbry** [comment]
For now it is a sufficient workaround to set PERMIT_DOCKER=network in case anyone runs across this

**Comment by sundbry** [comment]
I think perhaps it would make the most sense to just deprecate that config, so the user can set MYNETWORKS directly, instead of trying to automatically determine what is the best option based on those limited "host" or "network" options?

**Comment by erik-wramner** [comment]
In some cases that is true, but that can be much harder to configure. You may not always know the networks in advance. I think it is relatively uncommon to run with host networking; I can think of several places where that could break the existing scripts and it does have security implications.

Do you want to close the issue and use the workaround, or do you have a suggestion for a better fix?

**Comment by sundbry** [comment]
Hi @erik-wramner ,

If we're just brainstorming here, perhaps adding another environment variable to specify the interface name and override "eth0" would be a more compatible alternative.

**Comment by erik-wramner** [comment]
I like that. It is a very small change and it should work in most cases.

**Comment by aendeavor** [comment]
I will have a look at that.
