### ISSUE TITLE
Problem with listening on ports

### ISSUE THREAD

**Issue by alexjub94** [tomav/docker-mailserver#1230]
Hello, i've tried to install a mailserver with this image in docker but i have a problem with the ports.

## Context
I have copy-pasted the part of the sample docker-compose in mine and i've generated the dkim keys and create a mail adress with the setup file.
I have followed this tutorial (in french) to setup the mail server : [https://homputersecurity.com/2018/02/16/guide-dinstallation-dun-serveur-mail-sur-docker/](https://homputersecurity.com/2018/02/16/guide-dinstallation-dun-serveur-mail-sur-docker/) 

Once the installation was done, i have checked the status of the ports but they are shown as "filtered" by nmap.

Why it doesn't work ?

**Comment by erik-wramner** [comment]
That is very hard to tell without more information. Perhaps you have a firewall running that blocks nmap? If so you need to configure your firewall to allow inbound connections on the ports you want to expose.

**Comment by alexjub94** [comment]
I have no firewall so i don't understand why it is shown as "filtered"
-------- Message d'origine --------De : Erik Wramner <notifications@github.com> Date : 15/08/2019  20:02  (GMT+01:00) À : tomav/docker-mailserver <docker-mailserver@noreply.github.com> Cc : alexjub94 <alexjublot@gmail.com>, Author <author@noreply.github.com> Objet : Re: [tomav/docker-mailserver] Problem with listening on ports (#1230) That is very hard to tell without more information. Perhaps you have a firewall running that blocks nmap? If so you need to configure your firewall to allow inbound connections on the ports you want to expose.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tomav/docker-mailserver/issues/1230?email_source=notifications\u0026email_token=AIMCVYGDTAEXDN4ZXGVBWZTQEWK3NA5CNFSM4IL63WYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4MRLZA#issuecomment-521737700",
"url": "https://github.com/tomav/docker-mailserver/issues/1230?email_source=notifications\u0026email_token=AIMCVYGDTAEXDN4ZXGVBWZTQEWK3NA5CNFSM4IL63WYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4MRLZA#issuecomment-521737700",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by erik-wramner** [comment]
If you are connected to the Internet without a firewall you probably have bigger issues than the mail server. Hopefully you mean that there is no firewall running on the host.

Filtered means firewalled. The mail server does have a built-in firewall if you have enabled fail2ban. If you have `ENABLE_FAIL2BAN=1` it is possible that you have managed to lock out yourself. If so change the option to `ENABLE_FAIL2BAN=0` and see if that helps. If it doesn't then the mail server should be innocent and there is something else that is firewalling the ports.

If you need more help, please post details. You skipped that part of the issue template and we are not prescient.

- What is your system configuration (details)?
- What is your Docker configuration? In particular what options have you enabled and what ports do you expose in the compose file?
- What is the output of `netstat -tan` (focus on LISTENING ports)? Are all the exposed mail ports listed?
- How do you run nmap and where? I assume you run it on the mail server host outside of docker, is that correct? If so with what options? What output do you get?
- What is the output from netstat and nmap if you run the same commands with docker-mailserver stopped?
- Is there anything that may be relevant in the mail server logs?

**Comment by alexjub94** [comment]
Hello, 

Yes the firewall will be my next task.

I have used the file on the GitHub for the docker-compose and the .env. I have checked all parameters and Fail2ban is disabled but the status is still « filtered » on nmap

Here are my tests with nmap and my iptables rules
![screen iptables1](https://user-images.githubusercontent.com/35138272/63153497-b62d2d80-c00e-11e9-9dd2-801c1d178390.jpg)
![screen iptables2](https://user-images.githubusercontent.com/35138272/63153498-b62d2d80-c00e-11e9-88c6-0bc24547733d.jpg)
![screen nmap](https://user-images.githubusercontent.com/35138272/63153499-b62d2d80-c00e-11e9-95c3-555100efca93.jpg)


I'm sorry to not have exposed my situation correctly :

- I have a VPS debian 9


Here is my docker-compose extract : 
![screen docker-compose](https://user-images.githubusercontent.com/35138272/63154008-f5a84980-c00f-11e9-8220-d8579680edd1.jpg)

When I run the nmap command with the container stopped all the ports are shown as "closed"
For netstat the mailserver ports are shown as "listening" when the server is on and are not shown when the server is off


Thanks for trying to help me

**Comment by erik-wramner** [comment]
Try running nmap with localhost (127.0.0.1). I read VPS as running in the cloud and then the cloud provider could have a firewall in place that protects the ports when you access them using the external IP that you get from the DNS name.

**Comment by alexjub94** [comment]
Yes it is the problem ! I will contact my web host to know how to unlock them.

Thanks verymuch !
