### ISSUE TITLE
Basic question if I need to change something

### ISSUE THREAD

**Issue by Elmit2015** [tomav/docker-mailserver#1232]
Forgive me to ask so simple things ;-)
I setup just with the defaults the server and it works (sort of). I need to change things.
Is it enough to change the .env file and use the command docker-compose up -d mail ?? Or do I need to remove the images too?

Most of my clients (e.g. Thunderbird) get the messages:
```You are about to override how Thunderbird identifies this site.
Legitimate banks, stores, and other public sits will not ask you to do this:

Server 
 Location: mail.jstar-ai.com:143

Certificate Status
 This site attempts toidentify itself with invalid information.

 Wrong Site
 The certificate belongs to a different site, which could mean that someone is impersonate this site.

 Unknown Identity
 
 The certificate is not trusted because it hasn't been verified as issued by a trusted authority using a secure signature.
```
I believe the fix would be to use in the .env file SSL_TYPE=letsencrypt 
What else do I need to do?

**Comment by erik-wramner** [comment]
You don't need to remove the image, but you do need to remove the container. Just run:
```
docker-compose down
docker-compose up -d mail
```

As for setting up letsencrypt I don't remember the details, I'm not using it. Please check the documentation in the README.

**Comment by fbartels** [comment]
Fyi: if you specify this value in your `.env` file, then you do not need to stop and remove the container, as a `docker-compose up -d` will do that automatically.

**Comment by erik-wramner** [comment]
For letsencrypt please see https://github.com/tomav/docker-mailserver/wiki/Configure-SSL. When you feel the question has been answered, please close it.

**Comment by Elmit2015** [comment]
Sorry for late respond, I was abroad.

I tried it, but so far failed.
I did:
```
docker run -d \
 --name webmail \
 -e "VIRTUAL_HOST=mail.jstar-ai.com" \
 -e "LETSENCRYPT_HOST=mail.jstar-ai.com" \
 -e "LETSENCRYPT_EMAIL=ronald@elmit.com" \
 -e "LETSENCRYPT_TEST=true" \
 --network=webproxy \
 library/nginx
```
I updated the lines in .env:
```
SSL_TYPE=letsencrypt
ENABLE_SPAMASSASSIN=1
```
edited docker-compose.yml
docker-compose.yml 
(add the line letsencrypt)
...
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - ./nginx-proxy/nginx-data/certs/mail.jstar-ai.com:/etc/letsencrypt/live

restarted mail:
```
docker-compose down
docker-compose up -d mail
```
The directory nginx-proxy/nginx-data/certs/mail.jstar-ai.com has been created empty.

What am I missing?

**Comment by Elmit2015** [comment]
After checking the directory nginx-proxy/nginx-data/certs/mail.jstar-ai.com, it includes:
```
nginx-data/certs/jstar-ai.com$ ls
account_key.json  cert.pem  chain.pem  fullchain.pem  key.pem
```
However, https://www.checktls.com/TestReceiver shows:
Cert failed

```
seconds |   | test stage and result
-- | -- | --
[000.195] |   | Connected to server
[006.107] | <-- | 220-mail.jstar-ai.com ESMTP Postfix (Debian)220 mail.jstar-ai.com ESMTP Postfix (Debian)
[006.107] |   | We are allowed to connect
[006.107] | --> | EHLO www6.CheckTLS.com
[006.303] | <-- | 250-mail.jstar-ai.com250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN250 SMTPUTF8
[006.303] |   | We can use this server
[006.304] |   | TLS is an option on this server
[006.304] | --> | STARTTLS
[006.499] | <-- | 220 2.0.0 Ready to start TLS
[006.499] |   | STARTTLS command works on this server
[006.915] |   | Connection converted to SSL
  |   | SSLVersion in use: TLSv1_2
  |   | Cipher in use: ECDHE-RSA-AES256-GCM-SHA384
  |   | Certificate 1 of 1 in chain: Cert VALIDATION ERROR(S): self signed certificate
  |   | So email is encrypted but the recipient domain is not verified
  |   | Cert Hostname DOES NOT VERIFY (mail.jstar-ai.com != f303489d6c8f \| DNS:f303489d6c8f)
  |   | So email is encrypted but the host is not verified
  |   | Not Valid Before: Aug  4 17:39:47 2019 GMT
  |   | Not Valid After: Aug  1 17:39:47 2029 GMT
  |   | subject= /CN=f303489d6c8f
  |   | issuer= /CN=f303489d6c8f
[006.918] | ~~> | EHLO www6.CheckTLS.com
[007.115] | <~~ | 250-mail.jstar-ai.com250-PIPELINING250-SIZE 10240000250-ETRN250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN250 SMTPUTF8
[007.115] |   | TLS successfully started on this server
[007.115] | ~~> | MAIL FROM:<test@checktls.com>
[007.324] | <~~ | 250 2.1.0 Ok
[007.324] |   | Sender is OK
[007.324] | ~~> | QUIT
[007.521] | <~~ | 221 2.0.0 Bye
```

**Comment by Elmit2015** [comment]
I checked the directories and found:
nginx-proxy/nginx-data/certs# ls -l |grep mail
```
lrwxrwxrwx 1 root root   35 Aug 23 10:57 mail.jstar-ai.com.chain.pem -> ./_test_mail.jstar-ai.com/chain.pem
lrwxrwxrwx 1 root root   39 Aug 23 10:57 mail.jstar-ai.com.crt -> ./_test_mail.jstar-ai.com/fullchain.pem
lrwxrwxrwx 1 root root   13 Aug 23 10:57 mail.jstar-ai.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   33 Aug 23 10:57 mail.jstar-ai.com.key -> ./_test_mail.jstar-ai.com/key.pem
drwxr-xr-x 2 root root 4096 Aug 23 10:57 _test_mail.jstar-ai.com
```
I don't have a directory mail.jstar-ai.com, but a _test_mail.jstar-ai.com 
They volumes pointed to mail.jstar-ai.com

**Comment by erik-wramner** [comment]
Not sure what you are doing wrong as I'm not using letsencrypt, but the mail server is using the self-signed cert:

> Cert VALIDATION ERROR(S): self signed certificate

As for the files try mapping nginx-proxy/nginx-data/certs to /etc/letsencrypt/live. Then you will get the symbolic links in the live folder which seems correct.

**Comment by Elmit2015** [comment]
It seems something changed by itself over time.
Now I do get:
```
nginx-proxy/nginx-data/certs$  ls -l |grep mail
drwxr-xr-x 2 root root 4096 Aug 26 10:14 mail.jstar-ai.com
lrwxrwxrwx 1 root root   29 Aug 23 13:11 mail.jstar-ai.com.chain.pem -> ./mail.jstar-ai.com/chain.pem
lrwxrwxrwx 1 root root   33 Aug 23 13:11 mail.jstar-ai.com.crt -> ./mail.jstar-ai.com/fullchain.pem
lrwxrwxrwx 1 root root   13 Aug 23 13:11 mail.jstar-ai.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   27 Aug 23 13:11 mail.jstar-ai.com.key -> ./mail.jstar-ai.com/key.pem
drwxr-xr-x 2 root root 4096 Aug 23 12:58 _test_mail.jstar-ai.com
```
The last line still remain. Maybe I can delete that directory now.

However, https://www.checktls.com/TestReceiver still reports:
```
seconds |   | test stage and result
-- | -- | --
[000.196] |   | Connected to server
[006.715] | <-- | 220-mail.jstar-ai.com ESMTP Postfix (Debian)220 mail.jstar-ai.com ESMTP Postfix (Debian)
[006.715] |   | We are allowed to connect
[006.715] | --> | EHLO www6.CheckTLS.com
[006.911] | <-- | 250-mail.jstar-ai.com250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN250 SMTPUTF8
[006.912] |   | We can use this server
[006.912] |   | TLS is an option on this server
[006.912] | --> | STARTTLS
[007.108] | <-- | 220 2.0.0 Ready to start TLS
[007.108] |   | STARTTLS command works on this server
[007.513] |   | Connection converted to SSL
  |   | SSLVersion in use: TLSv1_2
  |   | Cipher in use: ECDHE-RSA-AES256-GCM-SHA384
  |   | Certificate 1 of 1 in chain: Cert VALIDATION ERROR(S): self signed certificate
  |   | So email is encrypted but the recipient domain is not verified
  |   | Cert Hostname DOES NOT VERIFY (mail.jstar-ai.com != f303489d6c8f \| DNS:f303489d6c8f)
  |   | So email is encrypted but the host is not verified
  |   | Not Valid Before: Aug  4 17:39:47 2019 GMT
  |   | Not Valid After: Aug  1 17:39:47 2029 GMT
  |   | subject= /CN=f303489d6c8f
  |   | issuer= /CN=f303489d6c8f
[007.515] | ~~> | EHLO www6.CheckTLS.com
[007.712] | <~~ | 250-mail.jstar-ai.com250-PIPELINING250-SIZE 10240000250-ETRN250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN250 SMTPUTF8
[007.712] |   | TLS successfully started on this server
[007.712] | ~~> | MAIL FROM:<test@checktls.com>
[007.913] | <~~ | 250 2.1.0 Ok
[007.913] |   | Sender is OK
[007.913] | ~~> | QUIT
[008.109] | <~~ | 221 2.0.0 Bye
```
mailserver$ grep -n5 self .env
```
78-#
79-# empty => SSL disabled
80-# letsencrypt => Enables Let's Encrypt certificates
81-# custom => Enables custom certificates
82-# manual => Let's you manually specify locations of your SSL certificates for non-standard cases
83:# self-signed => Enables self-signed certificates
84-SSL_TYPE=letsencrypt
85-
86-# Set how many days a virusmail will stay on the server before being deleted
87-# empty => 7 days
88-VIRUSMAILS_DELETE_DELAY=

```

**Comment by erik-wramner** [comment]
I think you need to check your host name. The error message uses the host name generated by docker. There are several environment options for overriding that so that it matches the name in the cert. OVERRIDE_HOSTNAME is one, HOSTNAME and CONTAINER_NAME are also present. Not sure what you need to do, perhaps `OVERRIDE_HOSTNAME=mail.jstar-ai.com`?

**Comment by Elmit2015** [comment]
I tried in this order to change each time one line:
```
OVERRIDE_HOSTNAME=mail.jstar-ai.com
CONTAINER_NAME=mail.jstar-ai.com
HOSTNAME=mail.jstar-ai.com

```
Nothing changed!

**Comment by erik-wramner** [comment]
When you compare the host name in the message (f303489d6c8f) with the host names in your docker containers, which container matches? Note that the host name is likely to change. What I'm after is that it could be a config error in one of the other containers. You could also enter the container (`docker exec -it mail /bin/bash`) and check the config files in action. Does the server really use letsencrypt, or is it using self-signed certs after all? I don't like the "self-signed" part in your debug message.

**Comment by Elmit2015** [comment]
Thanks for helping.
I logged in the mail container. I don't know what I am looking for. I checked the directory /etc:
cat mailname 
jstar-ai.com    <== that should be mail.jstar-ai.com why only jstar-ai.com ?

/etc/hostname  shows mail.jstar-ai.com

I checked our DNS settings and the mail.jstar-ai.com has a MX and CNAME entry. I try to let change the CNAME to an A record. Maybe that solves the problem? Any other ideas?

**Comment by Elmit2015** [comment]
I changed the CNAME to an A record in the DNS record. I wiated for 4 hours, but It did not improve, still the same.

**Comment by erik-wramner** [comment]
You have two or three containers, right? Mail container, nginx container and perhaps a letsencrypt container if it is not the same as nginx. If the odd host name in the certificate is the name of one of the other containers then the problem may be there.

**Comment by erik-wramner** [comment]
Is this still a problem?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
