### ISSUE TITLE
DOVECOT_USER_ATTR and DOVECOT_PASS_ATTR gets ignored

### ISSUE THREAD

**Issue by CPTCAPSLOK** [tomav/docker-mailserver#1234]
If i set DOVECOT_USER_ATTR and DOVECOT_PASS_ATTR in the environment section of my docker-compose.yml file they do absolutly nothing but when i add a S (DOVECOT_USER_ATTR**S**, DOVECOT_PASS_ATTR**S**) it seems to works.

## Version
Im using the "latest" tag.

## Possible Fix
Maybe README is wrong ?

**Comment by fbartels** [comment]
Yes, it seems there is an s missing the the description of these values.

In https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L673 the startup script translates any env variables starting with DOVECOT_ into entries in `/etc/dovecot/dovecot-ldap.conf.ext`. But as you can see in https://github.com/dovecot/core/blob/master/doc/example-config/dovecot-ldap.conf.ext#L109 these options indeed have an additional s in the end.

@CPTCAPSLOK would you be open to create a pull request to update the readme?

**Comment by erik-wramner** [comment]
Fixed. @CPTCAPSLOK thanks for reporting it!
