### ISSUE TITLE
Postfix Summary not working as expected

### ISSUE THREAD

**Issue by mindrunner** [tomav/docker-mailserver#1239]
The Postfix summary Email is not being sent reliably

## Context
It seems like the mail is only sent after the container is running for at least 24 hours. Since I auto update as soon as a new image is released, I restart my container more frequently. Thus, I never receive the Postfix Summary Email.

## Expected Behavior
Email is sent every 24 hours.

## Actual Behavior
Email is only sent when the container runs for more than 24 hours.

## Possible Fix
Workaround (untested):
Mounting a volume or folder to /var/log/mail/ preserves the logs when the container restarts. This should solve the problem. Also this makes the logs permanent.

I am not sure if I am hitting a bug or using this in a wrong way. Maybe someone can elaborate and point me into the right direction?

**Comment by erik-wramner** [comment]
This is a known weakness. The report is currently triggered by logrotate, so it is tightly connected to when the logs are rotated. There is an issue about separating the report and the logrotate job. With that and a volume for the logs this should be solved. Just mounting /var/log/mail as a volume on docker-compose should be good enough to make the old approach work with frequent updates.

I'll mark the issue as a bug and we'll update the docs when the new report solution is in place.

**Comment by mindrunner** [comment]
Interesting. However, I am still waiting for my Email... How can I test/check this behaviour?

**Comment by helmutundarnold** [comment]
Hi,
AFAIK this summary report is triggered by logrotate and not a cron.


Am 22.08.19 um 20:59 schrieb lukas:

**Comment by fbartels** [comment]
https://www.shellhacks.com/logrotate-force-log-rotation/ explains how to force a logrortate run.

In the end (have not checked how exactly its implemented here) logrotate will be invoked by run and then process files that have matching "rules" .

**Comment by erik-wramner** [comment]
The main problem is that the logs are gone if you start a new container as the files are not in a volume. Add a volume for /var/logs and the existing solution should work the way it has always done.

**Comment by mindrunner** [comment]
Mounting /var/log will break other things and make some submodules unfunctional.

I mounted /var/log/mail to a local folder. The container is running since more than 2 days. There is a mail.log and a mail.log.1 (rotating works). But I never received a summary mail :(

How can I debug this?

**Comment by erik-wramner** [comment]
That is good. Then we should be able to get it working. Out of curiosity, what breaks if you make /var/log a volume?

**Comment by mindrunner** [comment]
Can't actually remember. It was one of the components (clamav, spamassasin, etc) complaining about not finding its log folder /var/log/<name>. I think if you mount /var/log and make sure, the required subfolders are there, it should work as well.

**Comment by erik-wramner** [comment]
FYI #1262 adds support for pflogsumm triggered by cron and updates the readme to suggest a log volume. I'll close this.

**Comment by mindrunner** [comment]
Cool, interesting. Will that be merged soon?

**Comment by erik-wramner** [comment]
Yes, waiting for review. Should be there within a day or two.
