### ISSUE TITLE
logfiles

### ISSUE THREAD

**Issue by awb99** [tomav/docker-mailserver#124]
What is the recommmended way how to look into smtp/imap/pop logfiles?
And where are they located?

A lot of entries I found via docker logs  mymail_mail_1. But many entries seem
to be missing also.

Is telneting into a docker container the right thing to do in order to view detailed logs?

Thanks!

**Comment by tomav** [comment]
The container log are `/var/log/mail.log`.
If you need something else:
`docker exec -ti mail tail -f /path/to/the/requested/file.log`

**Comment by awb99** [comment]
@tomav : Many Thanks
