### ISSUE TITLE
SPF

### ISSUE THREAD

**Issue by mindrunner** [tomav/docker-mailserver#1240]
The documentation suggests to use `v=spf1 mx ~all` for the SPF entry. What is the reason for provoking softfails in favor of `v=spf1 mx -all`?

**Comment by erik-wramner** [comment]
I think it is a common first step when adding SPF. Use soft fail to test the policy, then change the SPF record to use hard fail. There is nothing in docker-mailserver that depends on soft fail and I'm personally using hard fail. We could perhaps elaborate on that in the docs.

**Comment by mindrunner** [comment]
Alright, changed the docs.
