### ISSUE TITLE
maximum message size variable has no effect

### ISSUE THREAD

**Issue by rs-development** [tomav/docker-mailserver#1244]
## Context
The mail server is forwarding mails to Gmail accounts. I would like to increase the message size limit

## Expected Behavior
Messages bigger than 10MB should pass

## Actual Behavior
The messages get rejected:

## Your Environment
* Amount of RAM available: 32GB
* Mailserver version used: release-v6.1.0
* Docker version used: Docker version 18.09.4, build d14af54
* Environment settings relevant to the config:

POSTFIX_MAILBOX_SIZE_LIMIT=1024000000
POSTFIX_MESSAGE_SIZE_LIMIT=1024000000

`Aug 29 16:01:23 mail postfix/postscreen[5405]: CONNECT from [209.85.221.51]:37528 to [172.19.0.10]:25
	Aug 29 16:01:23 mail postfix/dnsblog[5409]: addr 209.85.221.51 listed by domain list.dnswl.org as 127.0.0.255
	Aug 29 16:01:23 mail postfix/dnsblog[5409]: addr 209.85.221.51 listed by domain dnsbl.sorbs.net as 127.0.0.6
	Aug 29 16:01:23 mail postfix/postscreen[5405]: PASS OLD [209.85.221.51]:37528
	Aug 29 16:01:23 mail postfix/smtpd[5415]: connect from mail-wr1-f51.google.com[209.85.221.51]
	Aug 29 16:01:23 mail postfix/smtpd[5415]: Anonymous TLS connection established from mail-wr1-f51.google.com[209.85.221.51]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
	Aug 29 16:01:23 mail postfix/smtpd[5415]: NOQUEUE: reject: MAIL from mail-wr1-f51.google.com[209.85.221.51]: 552 5.3.4 Message size exceeds fixed limit; proto=ESMTP helo=<mail-wr1-f51.google.com>
	Aug 29 16:01:23 mail postfix/smtpd[5415]: disconnect from mail-wr1-f51.google.com[209.85.221.51] ehlo=2 starttls=1 mail=0/1 rcpt=0/1 data=0/1 quit=1 commands=4/7`

**Comment by erik-wramner** [comment]
I understand if you want something more stable than latest, but I'm personally using POSTFIX_MESSAGE_SIZE_LIMIT with latest and as far as I can tell it works. At least the users stopped complaining when I increased it. Could you check if it works if you run latest instead of 6.1.0? Perhaps in a test environment, so that you don't have to mess with production?

**Comment by rs-development** [comment]
Ahh i like messing with production :dancer:

**Comment by erik-wramner** [comment]
Any news on this?

**Comment by erik-wramner** [comment]
There is now a new release (6.2.0) and a new version of stable you can try. Please see if it helps to upgrade.

**Comment by erik-wramner** [comment]
@rs-development have you tried the new stable release? If I don't hear from you soon I will assume that you have solved your problem and close this.

**Comment by rs-development** [comment]
Still busy with other stuff. You can close it if you like. If i run into problems again when fixing it, I will issue again.
