### ISSUE TITLE
Make a new release and update stable

### ISSUE THREAD

**Issue by erik-wramner** [tomav/docker-mailserver#1249]
The "latest" version is much newer than the stable version and the numbered releases. We should make a new release.

@fbartels  @tomav I would suggest promoting the current master to stable if there are no new bugs reported on it within a week. At that point we should also release it as 6.2.

I'm not sure how to do that so that the new docker images get built, but perhaps we can do it in git and see if the docker images automatically appear. @tomav when you are back in action it would be great if we could go through the build process a bit. There is another issue for getting daily builds in place as well.

**Comment by erik-wramner** [comment]
We need to fix #1251 before we update the stable image or we will break things.

**Comment by baxerus** [comment]
@erik-wramner But #1251 makes a good point for your idea. With more frequent stable releases, I would be much easier to narrow down the problem 👍

**Comment by erik-wramner** [comment]
I'll wait until next weekend. If no new issues are reported and nobody protests I will promote master into stable.

**Comment by winks** [comment]
Kind of, but not 100% related. Is there a way to see up to which last commit updates landed in the `:latest` docker hub version? Bit hard to match up "3 days ago" and git commit timestamps.
Apologies if it's somewhere and I just didn't find it.

**Comment by fbartels** [comment]
@winks we could add a label that holds the git commit has for that. I'm going to make a PR for that shortly.

**Comment by erik-wramner** [comment]
Merged master to stable and release v6.2.0.
