### ISSUE TITLE
mailserver for relay master ?

### ISSUE THREAD

**Issue by scwall** [tomav/docker-mailserver#1257]
![diagram](https://i.imgur.com/li1PUtY.jpg)

Hi, I would like to know if it is possible to create a master server to manage several "mailserver" containers? (diagram below) I currently have my services on a single vps that has only one public address. . I would like to know if my scheme is correct in the way it is done. The main container manages the sending and receiving of emails and redirects emails in relation to the "header of the received domain" in the right container. If this configuration is not possible, can you send me back to an alternative solution, another question if I use only one central server for emails from several different domains? it is necessary to generate one DKIM key per domain name for sending? and validation? Thank you in advance. :)

**Comment by erik-wramner** [comment]
Well, validating an advanced e-mail topology like that sounds more like a consulting assignment than a support question to an open source project :-). I think you can replace docker-mailserver with Postfix. If it is possible with Postifix it is probably possible with this solution and vice versa.

Based on a quick look it seems a bit complicated. If possible I would go for a single server that handles multiple domains, that is mainstream and easy to setup.

**Comment by scwall** [comment]
No worries I understand thank you for your answer. I think I will currently turn to a single server. In any case there is a possibility to proceed like that so I will look at it later in my free time to do some tests :)
