### ISSUE TITLE
full host system available on guest

### ISSUE THREAD

**Issue by awb99** [tomav/docker-mailserver#126]
I have noticed that the full host filesystem is available on the guest. The directories that are mounted like /tmp/postfix are available ON TOP of this.

I have no explanation for this really. 

I have checked with other docker images that I run, and the docker-mailserver is the only one for which this occurs. I checked it by doing exec -  "ls /home" into the container image, and I see home  directories that should exist only on the host.

It is the same behavior for both the image on dockerhub and also for builds from source from github.

This effects a lot of things I guess, because the host system also has all kind of /var/log files and /var/mail files.

**Comment by 00angus** [comment]
What's the yaml/cmdline used to start the container? Any ref to volume there?
And which filesystems of the host do you see in the container?
Also useful: the output of the following

    docker inspect -f "{{ .HostConfig.Binds }}"  <your_container_name>

**Comment by awb99** [comment]
```
docker inspect -f "{{ .HostConfig.Binds }}"  mymail_mail_1
[/usr/local/mymail/postfix:/tmp/postfix:rw /usr/local/mymail/spamassassin:/tmp/spamassassin:rw /usr/local/mymail/mail:/var/mail:rw]
```

**Comment by 00angus** [comment]
From there I don't see how your container can see those dirs.  From where did you get the image ... Are those dirs live ... or a copy?

**Comment by awb99** [comment]
The directories are live directories from the host. At first, I was working with the image I got from dockerhub. Then when I noticed this behavior, I did run make on this github project.

**Comment by tomav** [comment]
@awb99 are you using vagrant?

**Comment by awb99** [comment]
no.

**Comment by awb99** [comment]
I have now tested this and on host system ARCH all is fine. Onn host debian 8 it occurs.

Additionally soemthing else is weird: all the commands from the host system are available in the guest system as well.  For example "tree" is not installed in docker-mailserver, but is available in the docker-mailserver image via "exec".

**Comment by tomav** [comment]
I think this is not related to the image but to your host / mount points / volume / homedir folders.
I close the issue but let us know here if something is related to it.

**Comment by awb99** [comment]
@tomav you were exactly right. When I upgraded the debian kernel this strange behavior disappeared.Thanks 1000x for yourhelp. Strangely enough, this error ONLY appeared on docker-mailserver image.

**Comment by tomav** [comment]
You're welcome.
