### ISSUE TITLE
"unable to save new password"

### ISSUE THREAD

**Issue by xiao1201** [tomav/docker-mailserver#1266]
Hi I have installed poppassd inside the container and enabled the poppassd plugin in rainloop, but when I tried to changed the password from user's password page, I got "unable to save new password" error message. Any ideas please?

**Comment by erik-wramner** [comment]
Well, this is outside of my territory, perhaps you should ask the poppassd or rainloop projects? A qualified guess is that the plugin requires a SQL database though. This project stores users and passwords in configuration files. It is likely that poppassd can't handle that.

**Comment by xiao1201** [comment]
hi @erik-wramner , thanks for the reply. So the only way to change an email account password is to use the ./setup.sh email add <email> <pass> command by the admin?

**Comment by erik-wramner** [comment]
Well, you could run the setup.sh command from a script that is called from a web front. Or you could directly modify the postfix-accounts.cf file in the mounted folder from a web front. Nothing like that is included out of the box as we don't include a web server though. See #828 for inspiration.

**Comment by xiao1201** [comment]
@erik-wramner , I see, thanks for the reply.
