### ISSUE TITLE
Environment import

### ISSUE THREAD

**Issue by mindrunner** [tomav/docker-mailserver#1267]
Why are you doing:

```
    environment:
    - DMS_DEBUG=${DMS_DEBUG}
    - ENABLE_CLAMAV=${ENABLE_CLAMAV}
    - ONE_DIR=${ONE_DIR}
    - ENABLE_POP3=${ENABLE_POP3}
    - ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
    - ENABLE_MANAGESIEVE=${ENABLE_MANAGESIEVE}
    - OVERRIDE_HOSTNAME=${OVERRIDE_HOSTNAME}
    - POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS}
    - POSTSCREEN_ACTION=${POSTSCREEN_ACTION}
    - REPORT_RECIPIENT=${REPORT_RECIPIENT}
    - REPORT_SENDER=${REPORT_SENDER}
    - REPORT_INTERVAL=${REPORT_INTERVAL}
    - SMTP_ONLY=${SMTP_ONLY}
    - SSL_TYPE=${SSL_TYPE}
    - TLS_LEVEL=${TLS_LEVEL}
    - SPOOF_PROTECTION=${SPOOF_PROTECTION}
    - ENABLE_SRS=${ENABLE_SRS}
    - PERMIT_DOCKER=${PERMIT_DOCKER}
    - VIRUSMAILS_DELETE_DELAY=${VIRUSMAILS_DELETE_DELAY}
    - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=${ENABLE_POSTFIX_VIRTUAL_TRANSPORT}
    - POSTFIX_DAGENT=${POSTFIX_DAGENT}
    - POSTFIX_MAILBOX_SIZE_LIMIT=${POSTFIX_MAILBOX_SIZE_LIMIT}
    - POSTFIX_MESSAGE_SIZE_LIMIT=${POSTFIX_MESSAGE_SIZE_LIMIT}
    - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
    - SA_TAG=${SA_TAG}
    - SA_TAG2=${SA_TAG2}
    - SA_KILL=${SA_KILL}
    - SA_SPAM_SUBJECT=${SA_SPAM_SUBJECT}
    - ENABLE_FETCHMAIL=${ENABLE_FETCHMAIL}
    - FETCHMAIL_POLL=${FETCHMAIL_POLL}
    - ENABLE_LDAP=${ENABLE_LDAP}
    - LDAP_START_TLS=${LDAP_START_TLS}
    - LDAP_SERVER_HOST=${LDAP_SERVER_HOST}
    - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
    - LDAP_BIND_DN=${LDAP_BIND_DN}
    - LDAP_BIND_PW=${LDAP_BIND_PW}
    - LDAP_QUERY_FILTER_USER=${LDAP_QUERY_FILTER_USER}
    - LDAP_QUERY_FILTER_GROUP=${LDAP_QUERY_FILTER_GROUP}
    - LDAP_QUERY_FILTER_ALIAS=${LDAP_QUERY_FILTER_ALIAS}
    - LDAP_QUERY_FILTER_DOMAIN=${LDAP_QUERY_FILTER_DOMAIN}
    - LOGROTATE_INTERVAL=${LOGROTATE_INTERVAL}
    - DOVECOT_TLS=${DOVECOT_TLS}
    - DOVECOT_USER_FILTER=${DOVECOT_USER_FILTER}
    - DOVECOT_PASS_FILTER=${DOVECOT_PASS_FILTER}
    - ENABLE_POSTGREY=${ENABLE_POSTGREY}
    - POSTGREY_DELAY=${POSTGREY_DELAY}
    - POSTGREY_MAX_AGE=${POSTGREY_MAX_AGE}
    - POSTGREY_AUTO_WHITELIST_CLIENTS=${POSTGREY_AUTO_WHITELIST_CLIENTS}
    - POSTGREY_TEXT=${POSTGREY_TEXT}
    - ENABLE_SASLAUTHD=${ENABLE_SASLAUTHD}
    - SASLAUTHD_MECHANISMS=${SASLAUTHD_MECHANISMS}
    - SASLAUTHD_MECH_OPTIONS=${SASLAUTHD_MECH_OPTIONS}
    - SASLAUTHD_LDAP_SERVER=${SASLAUTHD_LDAP_SERVER}
    - SASLAUTHD_LDAP_SSL=${SASLAUTHD_LDAP_SSL}
    - SASLAUTHD_LDAP_BIND_DN=${SASLAUTHD_LDAP_BIND_DN}
    - SASLAUTHD_LDAP_PASSWORD=${SASLAUTHD_LDAP_PASSWORD}
    - SASLAUTHD_LDAP_SEARCH_BASE=${SASLAUTHD_LDAP_SEARCH_BASE}
    - SASLAUTHD_LDAP_FILTER=${SASLAUTHD_LDAP_FILTER}
    - SASLAUTHD_LDAP_START_TLS=${SASLAUTHD_LDAP_START_TLS}
    - SASLAUTHD_LDAP_TLS_CHECK_PEER=${SASLAUTHD_LDAP_TLS_CHECK_PEER}
    - SASL_PASSWD=${SASL_PASSWD}
    - SRS_EXCLUDE_DOMAINS=${SRS_EXCLUDE_DOMAINS}
    - SRS_SECRET=${SRS_SECRET}
    - DEFAULT_RELAY_HOST=${DEFAULT_RELAY_HOST}
    - RELAY_HOST=${RELAY_HOST}
    - RELAY_PORT=${RELAY_PORT}
    - RELAY_USER=${RELAY_USER}
    - RELAY_PASSWORD=${RELAY_PASSWORD}
```

instead of

```
env_file: 
  - .env
```

?

**Comment by erik-wramner** [comment]
No idea, possibly for historic reasons? I like your version if it works.

**Comment by mindrunner** [comment]
for me it works. Just replaced it in my config. Will come with a PR soon.

**Comment by fbartels** [comment]
Just one remark. I wouldn't call the file `.env` as this file will then already be sourced by docker-compose. Just drop the dot or call it by another name.

**Comment by mindrunner** [comment]
What disadvantage do you see in using the same env file for both docker-compose and the running container? If we split it up in two, everyone has to maintian two environment files. Is that what we want?

**Comment by erik-wramner** [comment]
@fbartels how about renaming the `.env` file to `docker-mailserver.env` and referencing it in this way? I have never liked the `.env` file as it is hidden and as far as I can see it only defines environment options that should be passed on. Using a visible file that is referenced explicitly is clearer in my view. Plus this is only done at installation time (or manually) so we won't break anything by the change.

**Comment by fbartels** [comment]
@mindrunner the only technical reason would be that if you share the compose file with other services and these other services also rely on .env (for variable substitution for example) you could inject more envs into docker-mailserver than it would be necessary.

**Comment by mindrunner** [comment]
Yeah I see the point, however consider this as bad-practice anyways. There is no reason for putting an unrelated service to the mailserver. Howvever, this is how I usually configure my containers and it is way more lean than copy and pasting every variable name to the docker-compose file. (or a second env file)

**Comment by fbartels** [comment]
Since this is only a mailserver there are actually a few containers that you could include in the same compose file, like a webmailer for example.

But it's also fair to say that in these cases the admin will want to write his own compose file and decide to deal with the env file on his own choosing.

**Comment by erik-wramner** [comment]
Well then, for the PR rename `.env-dist` to `docker-mailserver.env`, update the compose example files and update the readme.

**Comment by mindrunner** [comment]
There will still be an issue with the variables used by the compose file. I think, thats host and domainname at least. I will have a look into this and find a neat solution.

**Comment by mindrunner** [comment]
https://github.com/tomav/docker-mailserver/pull/1270

**Comment by fbartels** [comment]
Closing since the pr has been merged. Thanks for your contribution!
