### ISSUE TITLE
Re-using dhparams

### ISSUE THREAD

**Issue by springcomp** [tomav/docker-mailserver#1268]
I’m using this Docker image as a private mail server in order to create as many disposable mailboxes as I want with automatic forwarding. My use case involves creating mailboxes and removing mailboxes when no longer needed.

For this reason, I need to restart the container for changes to take effect.

I would like to know if it’s possible to re-use the generated dhparams which take a very long time ?

**Comment by erik-wramner** [comment]
Well, if you look at the tests they actually do that. You can mount a pre-generated dhparams file into the container. If I remember correctly just put `dhparams.pem` in your `config` folder. I may be wrong, double-check the tests or `start-mailserver.sh` if it doesn't work.

**Comment by springcomp** [comment]
Thank you, you put me on the right track.
For the record, I copied the existing dhparams file from the running image:

```
docker cp mail:/var/mail-state/lib-shared/dhparams.pem /opt/mail-server/config/lib-shared/dhparams.pem
```
An then used it in the `docker-compose.yml` file:

```
    volumes:
    - mailstate:/var/mail-state
    - ./config/lib-shared/dhparams.pem:/var/mail-state/lib-shared/dhparams.pem
```
