### ISSUE TITLE
letsencrypt certificate search path

### ISSUE THREAD

**Issue by neuralp** [tomav/docker-mailserver#1274]
**EDITED**

The root of this problem has a lot less to do with the _mydestinations_ in the main.cf file and more to do with finding the letsencrypt certificate in the proper path.  So I've changed the title and amended this on to the original report.

## Context

In the process of setting up my mail server, I am setting my environment variables to 

```
HOSTNAME=mail
DOMAINNAME=abc.com
CONTAINER_NAME=mail
OVERRIDE_HOSTNAME=abc.com
```
The override hostname is intentionally set because the letsencrypt certificate will only work for the base of the domain (abc.com) and not (mail.abc.com) and are stored in the abc.com folder when letsencrypt is mounted in the container.  In order for the container to automatically find the correct certificate, the hostname can only be of the domain.com format.

This is all fine with the exception of the virtual tables created when I add an e-mail to the database.  If I add an e-mail for 'joe@abc.com' to the container (using the setup.sh script) it will add a virtual domain and address for this.  The postfix main.cf file has the line:

```
mydestination = $myhostname, localhost.$mydomain, localhost
```
Because $myhostname has been overridden (instead of using the output of 'hostname') to get lets encrypt to work, the mydestination contains abc.com and the virtual domain tables contain abc.com.  This obviously creates a conflict and as such mail will not be delivered (in my setup anyhow).  I don't remember if this was an ERROR or a WARNING, but either way the end result is that mail is not delivered.

## Expected Behavior

I would expect there to be no conflict between 'mydestination' and the 'vritual' tables used for other domains.

## Actual Behavior
Mail is not delivered because there is a conflict between the same hostname in 'mydestination' and the 'virtual' mail tables.

## Possible Fix

Every time I download a new image of the container, I stand it up as is.  After that I log into the container and edit the main.cf in the postfix directory and remove the $myhostname from the 'mydestination=' line in the file.  I then just commit my own image and stand up containers from that.

I propose that the $myhostname be removed from the 'mydestination' configuration item.  Correct me if I am wrong, but should all email accounts exist exclusively in the virtual tables?

## Steps to Reproduce

1. set OVERRIDE_HOSTNAME=abc.com in the environment
2. add an e-mail address for the same domain as the OVERRIDE_HOSTNAME is set to
3. conflict will then exist between mydestinations and virtual tables

## Your Environment

* Amount of RAM available: 1G total for virtual server I'm running this on
* Mailserver version used: Image ID 8ae795dc146c
* Docker version used: 18.09.7, build 2d0083d
* Environment settings relevant to the config: OVERRIDE_HOSTNAME
* Any relevant stack traces ("Full trace" preferred): N/A

**Comment by erik-wramner** [comment]
I don't know Postfix well enough to know if that is safe/good, but I do have another option. Instead of logging in and editing the configuration file, why don't you simply add `mydestination `to your `config/postfix-main.cf` and let the override do its job?

**Comment by neuralp** [comment]
That was my first thought, but then that would negate any other updates that may be made to the _main.cf_ file in the future.  Maybe I'm looking at this from the wrong way, the real reason I am using the _OVERRIDE_HOSTNAME=_ in the environment is to make lets encrypt work in the container.  If the server _HOSTNAME_ and _DOMAINNAME_ are set in the environment maybe the letsencrypt script needs to drop the _mail_ and just be looking for the _abc.com_?  I don't know where the code is that handles letsencrypt, but I'll take a look and see what it does.  Maybe the issue lies there.

**Comment by neuralp** [comment]
Ok, so let's be clear, letsencrypt is the real reason for this issue.  Letsencrypt for my domain is issued for the root of the domain _abc.com_ with a SAN of _mail.abc.com_.  Maybe I am wrong in assuming that the most users will request a letsencrypt certificate with the root of their domain being the the first domain specified in certbot and a subdomain as the second or third domains.  In my case I am creating the certificate with _abc.com_ as the first domain and _mail.abc.com_ as the second domain (SAN on the certificate) as well as _www.abc.com_.  The letsencrypt portion of the startup script only checks for the full hostname to find the certificate:

``
if [ -e "/etc/letsencrypt/live/$HOSTNAME/fullchain.pem" ]; then
``

Maybe we need to check for the full hostname first for the certificate and then also check the domain name second for a certificate chain?

**Comment by erik-wramner** [comment]
I'm not using letsencrypt, so I won't comment on that, but I think you have missed how `config/postfix-main.cf` works. It contains overrides, not the full configuration. If you add your own `mydestination` to that file it will override the default value of `mydestination`, but you will still get all the other configuration options. If something changes down the line you will get it unless you have a competing option in your file. If that solves your problem it should be a safe and very easy fix.

**Comment by erik-wramner** [comment]
@neuralp please see my comment above. Does the override help?

If not feel free to submit a PR. As long as it is backwards compatible I can see no danger in also checking for just the domain name as per your suggestion.

**Comment by neuralp** [comment]
@erik-wramner Now that I understand how the overrides are supposed to work, that will definitely work in my particular case.  But since the modification of the `main.cf` was to fix an issue that I had with the lets encrypt handling, I think that I would rather go the fixing the lets encrypt route.

I will submit a PR once I can successfully compile.  I do my development on low power machines with pretty restricted memory footprints, so I am running into issues currently, but once I take care of that.

Should I close this issue, since it is technically an enhancement?

**Comment by erik-wramner** [comment]
I'm trying to get the issues down to a level where all open issues are worked on, which seems to be an impossible task, so yes please close if the problem is solved. You can still refer to the closed issue in the PR.

**Comment by neuralp** [comment]
Re-opening as I have re-based and re-worked the updates.  Testing has also been separated out into the individual files as part of the new testing plan.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
