### ISSUE TITLE
ClamAV seems to be broken

### ISSUE THREAD

**Issue by PfefferT** [tomav/docker-mailserver#1279]
Hello together,

I've successfully installed this docker container. Everything works fine, but when I enable clamav over the env file, then the clamav service is not starting. I don't know why this happens. I have more than enough memory to use.
what could be the problem?
If I try to start it manually then the following message comes:

```
root@mail:/# service clamav-daemon start
[FAIL] Foreground specified, but daemon not found ... failed!
root@mail:/#
```

**Comment by erik-wramner** [comment]
We are not using services, we are using supervisor. Try to run `supervisorctl status` in the container. You should get something like:
`
clamav                           RUNNING   pid 355, uptime 2 days, 1:52:35
`
If clamav is not running please check and possibly post your logs in `/var/log/supervisor` and `/var/log/mail`.

**Comment by PfefferT** [comment]
Okay then I am confused, because I got the error mentioned inside of the FAQ section of the wiki.
The faq says: check for memory and check whether service is started. I can say yes to both points. So what could be the problem here ?

**Comment by PfefferT** [comment]
Here is my log to that:
```
Oct  2 11:46:19 mail amavis[1022]: (01022-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
Oct  2 11:46:19 mail dovecot: imap(info@mail.domain.tld)<3648><KUrXVeqTuYdbEKP3>: Logged out in=652 out=818 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Oct  2 11:46:20 mail amavis[1022]: (01022-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
Oct  2 11:46:20 mail amavis[1022]: (01022-01) (!)ClamAV-clamd: All attempts (1) failed connecting to /var/run/clamav/clamd.ctl, retrying (2)
Oct  2 11:46:26 mail amavis[1022]: (01022-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
Oct  2 11:46:26 mail amavis[1022]: (01022-01) (!)ClamAV-clamd av-scanner FAILED: run_av error: Too many retries to talk to /var/run/clamav/clamd.ctl (All attempts (1) failed connecting to /var/run/clamav/clamd.ctl) at (eval 97) line 613.\n
Oct  2 11:46:26 mail amavis[1022]: (01022-01) (!)WARN: all primary virus scanners failed, considering backups
```

**Comment by PfefferT** [comment]
I have tested now the Eicar virus test signature for my email. The log above came, but additionally some logs later amavis says that it has detected the virus. So can I ignore the log above ?

**Comment by erik-wramner** [comment]
Not sure. The service should be running if `supervisorctl status clamav` says RUNNING. You can check for the socket as well:
```
ls -l /var/run/clam*

srw-rw-rw- 1 clamav clamav 0 Sep 21 06:51 clamd.ctl
```
I have no errors in my logs, rather:
```
Oct  2 07:22:23 mail amavis[8301]: Using primary internal av scanner code for ClamAV-clamd
Oct  2 07:22:23 mail amavis[8301]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
```

**Comment by PfefferT** [comment]
I think I've figured out the problem. the thing was that the clamav.log was not existing. I've changed the permissions and it worked :-)

**Comment by cmtonkinson** [comment]
For what it's worth, on a pretty fresh install, I had a similar issue when trying to `ENABLE_CLAMAV=1`. My logs were spammed with:

```txt
mail    | 2019-10-03 01:10:22,804 INFO spawned: 'clamav' with pid 4029
mail    | 2019-10-03 01:10:22,827 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail    | 2019-10-03 01:10:22,829 INFO exited: clamav (exit status 1; not expected)
mail    | 2019-10-03 01:10:23,832 INFO spawned: 'clamav' with pid 4033
mail    | 2019-10-03 01:10:23,854 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail    | 2019-10-03 01:10:23,856 INFO exited: clamav (exit status 1; not expected)
mail    | 2019-10-03 01:10:24,860 INFO spawned: 'clamav' with pid 4039
mail    | 2019-10-03 01:10:24,883 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail    | 2019-10-03 01:10:24,885 INFO exited: clamav (exit status 1; not expected)
mail    | 2019-10-03 01:10:25,889 INFO spawned: 'clamav' with pid 4043
mail    | 2019-10-03 01:10:25,913 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail    | 2019-10-03 01:10:25,918 INFO exited: clamav (exit status 1; not expected)
```

Turns out (thanks to `/var/log/supervisor/clamav.log`) that `/var/log/mail/clamav.log` didn't exist:

```txt
ERROR: Can't initialize the internal logger
ERROR: Can't open /var/log/mail/clamav.log in append mode (check permissions!).
ERROR: Can't initialize the internal logger
ERROR: Can't open /var/log/mail/clamav.log in append mode (check permissions!).
ERROR: Can't initialize the internal logger
ERROR: Can't open /var/log/mail/clamav.log in append mode (check permissions!).
ERROR: Can't initialize the internal logger
ERROR: Can't open /var/log/mail/clamav.log in append mode (check permissions!).
ERROR: Can't initialize the internal logger
ERROR: Can't open /var/log/mail/clamav.log in append mode (check permissions!).
```

I created that file, changed it to `660` permissions and `root:clamav` ownership, and now `clamav` is starting successfully.

**Comment by PfefferT** [comment]
In my case the  `640 ` permissions and `root:adm` ownership worked :-)

**Comment by PfefferT** [comment]
and you're right you have to create the file initial.
I will create a summup ticket afterwards with all my bugs and usecases, which should be handled by this container

**Comment by mgmfr** [comment]
I had the same probleme with clamav but in my case, i had to `chmod 777 /tmp` because the logs existed and clamav was complaining about /tmp/clamav-<token>: permission denied.
But obviously the permissions are not preserved uppon restart of the stack.
