### ISSUE TITLE
Postfix summary sent to 0@domain

### ISSUE THREAD

**Issue by jjtt** [tomav/docker-mailserver#1283]
## Context

I have the configuration set as `REPORT_RECIPIENT=0` and recently noticed that I now get bounces of the daily postfix summary reports into my spam folder. I think this changed when I updated to the image `tvial/docker-mailserver                  latest              0748e6cd5b66`

## Expected Behavior

`0` should disable the reports

## Actual Behavior

Reports sent to 0@domain which doesn't exist and I get an "Undelivered Mail Returned to Sender" sent to root@domain

## Possible Fix

I'll try switching to a `monthly` report to get less messages in spam

**Comment by erik-wramner** [comment]
Please upgrade to the latest latest (currently digest ac35b68513cd commit 0e7e586ae34d, 6 days old). I can't find 0748e6cd5b66 among the builds at docker hub, either I'm just blind or it must be old. This bug should have been fixed already.

If you still get the problem with the latest version, please post the other report-related settings as well and I'll try to reproduce it.

**Comment by jjtt** [comment]
I should have tried the latest image before submitting this bug report.

Works correctly now.

**Comment by jjtt** [comment]
BTW the image id I reported was the one produced by `docker images`.

No idea why the id is different from the digest but now running `ac35b68513cd` which according to `docker images` on my machine has image id `1978f84d3dee`
