### ISSUE TITLE
Mail clients are not connecting to the IMAP and SMTP when an alias is given instead of an full address

### ISSUE THREAD

**Issue by PfefferT** [tomav/docker-mailserver#1288]
Hello together,

I have the problem that my thunderbird is no allowing me to integrate an alias address.

I have added an alias address with the help of the setup.sh. The alias is filled into config/postfix-virtual.cf. When I try to integrate this alias-address into thunderbird, then the maillog of dovecot says that it does not know the alias-user.
I have defined the alias as follows:
```./setup.sh alias add alias@mail.domain.tld target@mail.domain.tld```

Normal users can be integrated into thunderbird as a charm, but not aliases.
What I am doing wrong here?

thx for the help.

**Comment by erik-wramner** [comment]
Perhaps I'm missing the point, but I don't see how you could add an alias to Thunderbird? The clients need to connect as users. Aliases just rewrite addresses on the server side. For example if you send an e-mail to info@example.com it could be rewritten to yourownaddress@example.com using an alias. You don't connect as info with Thunderbird, you connect as yourownaddress, but if an e-mail is sent to info it will be delivered to you.

**Comment by PfefferT** [comment]
Ahh okay then I've misunderstood the aliases itself. I thought that I am able to login to them via client-software and everything I am doing there is in the name of the origin. But okay then I was wrong :-) thx
