### ISSUE TITLE
Unneeded Sent|Trash|Drafts directories creation when adding user

### ISSUE THREAD

**Issue by gmasse** [tomav/docker-mailserver#1296]
When a new email user is created, `start-mailserver.sh` and `check-for-changes.sh` automatically add and subscribe to `Sent`, `Trash` and `Drafts` folders (part of [RFC 6154](http://www.faqs.org/rfcs/rfc6154.html) Special-Use Mailboxes).

Dovecot is configured to automatically create those folders during the first connection.

## Context
According to Dovecot configuration `/etc/dovecot/conf.d/15-mailboxes.conf`
`Drafts`, `Junk`, `Trash` and `Sent` folders will be created during the first user connection (reference documentation: https://wiki.dovecot.org/MailboxSettings)

## Expected Behavior
Remove directories and files creation in `start-mailserver.sh` and `check-for-changes.sh` and let dovecot manage that for us.

But perhaps it is deliberate to create them before dovecot.

**Comment by erik-wramner** [comment]
Good catch. I agree that it would be cleaner and anything that makes `check-for-changes.sh` simpler is good in my book. However, I wonder if `Trash` could be used by sieve rules before a user has connected? I can't find a plausible reason to create the others ahead of time.

**Comment by gmasse** [comment]
This question's raised because I am currently working to support Dovecot [ms]dbox. So I wonder if I should also manually create this folders for other mailbox format.

Good point for Sieve (or more globally, any filters). I need to dig.

**Comment by gmasse** [comment]
PR #1297 
Dovecot create folders on the fly.
Behavior has been tested for Maildirs. Sieve SPAM folder test succeed without having to create SPAM folder before.

**Comment by gmasse** [comment]
PR #1311 
Test added

**Comment by erik-wramner** [comment]
PR merged
