### ISSUE TITLE
User-Creation

### ISSUE THREAD

**Issue by ParadoxDelta** [tomav/docker-mailserver#13]
I have some issues to make my mailserver work and i think it's due to my  wrong user creation. I took your template and pasted in a new file accounts.cf under ./postfix and filled my data in there. somehow like this:

# imap
username:                  <reply-to@mydomain.com>
password:                  <mypassword>
server:                    <123.132.123.123>
imap port:                 993
imap path prefix:        INBOX
auth method:            md5 challenge-response

# smtp
smtp port:                587
username:                  <reply-to@mydomain.com>
password:                  <mypassword>
auth method:            md5 challenge-response

or is it supposed to be:

# imap
username:                  reply-to@mydomain.com
password:                  mypassword
server:                    123.132.123.123
imap port:                 993
imap path prefix:        INBOX
auth method:            md5 challenge-response

# smtp
smtp port:                587
username:                  reply-to@mydomain.com
password:                  mypassword
auth method:            md5 challenge-response

either way, i cant connect a client to the server and when i send an e-mail to it, nothing is saved under /var/mail (also did postfix reload)
i could access the ports with telnet so i'm pretty shure something is wrong with the server-setup

**Comment by ParadoxDelta** [comment]
ah, i found the example-file with user@domain.tld|password
but my problems remain the same. client wont connect and emails wont get saved even though ports are reachable. any idea what the problem might be?

**Comment by gegere** [comment]
Hello @ParadoxDelta this is a great docker instance. I thought I would share [another repo](https://github.com/htmlgraphic/Mail-Server) I have been working on maybe you can piece a few things together and get your build working.

**Comment by tomav** [comment]
@ParadoxDelta, I can help you, but I need you configurations to reproduce the problem. Do not hesitate.

@gegere, advertisement spotted! :-) Please...

**Comment by gegere** [comment]
Pretty Please? Happy to help your build anytime. Open source projects are epic!

**Comment by ParadoxDelta** [comment]
Alright but i didn't change much. Just my URL as ENV when run and one user in the account.cf
Container looks like this
bbc381af9435        tvial/docker-mailserver   "/bin/sh -c /usr/loc   15 hours ago        Up 15 hours         0.0.0.0:25->25/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:587->587/tcp, 0.0.0.0:993->993/tcp   mailserver

main.cf
# See /usr/share/postfix/main.cf.dist for a commented, more complete version

smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
biff = no
append_dot_mydomain = no
readme_directory = no

# Basic configuration
myhostname = myactualdomain.com
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
mydestination = localhost.localdomain, localhost
relayhost =
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all

# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_tls_security_level = may
smtpd_use_tls=yes
smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination
smtpd_client_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination
smtpd_sender_restrictions = permit_mynetworks
smtp_tls_security_level = may

# SASL
smtpd_sasl_auth_enable = yes
smtpd_sasl_path = smtpd
smtpd_sasl_type = cyrus
smtpd_sasl_security_options = noanonymous, noplaintext
smtpd_sasl_local_domain = $myhostname
cyrus_sasl_config_path = /etc/postfix/sasl
broken_sasl_auth_clients = yes

# Mail directory
virtual_mailbox_base = /var/mail
virtual_mailbox_domains = /etc/postfix/vhost
virtual_mailbox_maps = hash:/etc/postfix/vmailbox
virtual_alias_maps = hash:/etc/postfix/virtual
virtual_uid_maps = static:5000
virtual_gid_maps = static:5000

# Additional option for filtering
content_filter = smtp-amavis:[127.0.0.1]:10024


master.cf
#
# Postfix master process configuration file.  For details on the format
# of the file, see the master(5) manual page (command: "man 5 master" or
# on-line: http://www.postfix.org/master.5.html).
#
# Do not forget to execute "postfix reload" after editing this file.
#
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (yes)   (never) (100)
# ==========================================================================

smtp      inet  n       -       n       -       -       smtpd
submission inet n       -       n       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_sasl_authenticated_header=yes
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING
pickup    fifo  n       -       -       60      1       pickup
  -o content_filter=
  -o receive_override_options=no_header_body_checks

cleanup   unix  n       -       -       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
tlsmgr    unix  -       -       -       1000?   1       tlsmgr
rewrite   unix  -       -       -       -       -       trivial-rewrite
bounce    unix  -       -       -       -       0       bounce
defer     unix  -       -       -       -       0       bounce
trace     unix  -       -       -       -       0       bounce
verify    unix  -       -       -       -       1       verify
flush     unix  n       -       -       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       -       -       -       smtp
relay     unix  -       -       -       -       -       smtp
showq     unix  n       -       -       -       -       showq
error     unix  -       -       -       -       -       error
retry     unix  -       -       -       -       -       error
discard   unix  -       -       -       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       -       -       -       lmtp
anvil     unix  -       -       -       -       1       anvil
scache    unix  -       -       -       -       1       scache

maildrop  unix  -       n       n       -       -       pipe
  flags=DRhu user=vmail argv=/usr/bin/maildrop -d ${recipient}
uucp      unix  -       n       n       -       -       pipe
  flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
ifmail    unix  -       n       n       -       -       pipe
  flags=F user=ftn argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
bsmtp     unix  -       n       n       -       -       pipe
  flags=Fq. user=bsmtp argv=/usr/lib/bsmtp/bsmtp -t$nexthop -f$sender $recipient
scalemail-backend unix  -       n       n       -       2       pipe
  flags=R user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store ${nexthop} ${user} ${extension}
mailman   unix  -       n       n       -       -       pipe
  flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
  ${nexthop} ${user}


#
# Amavis configuraiton
#

smtp-amavis     unix    -       -       -       -       2       smtp
  -o smtp_data_done_timeout=1200
  -o smtp_send_xforward_command=yes
  -o disable_dns_lookups=yes
  -o max_use=20

127.0.0.1:10025 inet    n       -       -       -       -       smtpd
  -o content_filter=
  -o local_recipient_maps=
  -o relay_recipient_maps=
  -o smtpd_restriction_classes=
  -o smtpd_delay_reject=no
  -o smtpd_client_restrictions=permit_mynetworks,reject
  -o smtpd_helo_restrictions=
  -o smtpd_sender_restrictions=
  -o smtpd_recipient_restrictions=permit_mynetworks,reject
  -o smtpd_data_restrictions=reject_unauth_pipelining
  -o smtpd_end_of_data_restrictions=
  -o mynetworks=127.0.0.0/8
  -o smtpd_error_sleep_time=0
  -o smtpd_soft_error_limit=1001
  -o smtpd_hard_error_limit=1000
  -o smtpd_client_connection_count_limit=0
  -o smtpd_client_connection_rate_limit=0
  -o receive_override_options=no_header_body_checks,no_unknown_recipient_checks


no aliases.

Thanks for your help!

**Comment by tomav** [comment]
(edit: reformatted you comment content)

**Comment by tomav** [comment]
@ParadoxDelta these are default configuration that comes with the container, right? If yes your problem is somewhere else.
Are you using `docker` or `docker-compose`? (give me `docker-compose.yml` file)

Please run the container and paste me the container logs, from the first line to `postfix start`. We should see the problem quickly.

**Comment by ParadoxDelta** [comment]
it keeps saying "unexpected ssl conenction shutdown"
we have a quite restrictive firewall setting. Do i need open ports other than 587 and 993?
logs:

Regenerating postfix 'vmailbox' and 'virtual' for given users
/usr/local/bin/start-mailserver.sh: 10: /usr/local/bin/start-mailserver.sh: cann                                                                                                                                                             ot open /tmp/postfix/accounts.cf: No such file
/etc/courier/userdb: not found.
cp: cannot stat '/tmp/postfix/virtual': No such file or directory
Postfix configurations
postmap: fatal: open /etc/postfix/virtual: No such file or directory
cat: /tmp/vhost.tmp: No such file or directory
rm: cannot remove '/tmp/vhost.tmp': No such file or directory
Fixing permissions
Creating /etc/mailname
Configuring Spamassassin
cp: cannot stat '/tmp/spamassassin/rules.cf': No such file or directory
Starting daemons
 * Starting enhanced syslogd rsyslogd
   ...done.
 * Starting file alteration monitor FAM
   ...done.
 * Starting  saslauthd
   ...done.
 * Starting Courier authentication services authdaemond
   ...done.
 * Starting Courier IMAP server imapd
   ...done.
 * Starting Courier IMAP-SSL server imapd-ssl
   ...done.
Starting SpamAssassin Mail Filter Daemon: spamd.
 * Starting ClamAV daemon clamd
   ...done.
  The value of variable $myhostname is "bbc381af9435", but should have been
  a fully qualified domain name; perhaps uname(3) did not provide such.
  You must explicitly assign a FQDN of this host to variable $myhostname
  in /etc/amavis/conf.d/05-node_id, or fix what uname(3) provides as a host's
  network name!
Starting amavisd: (failed).
 * Starting Postfix Mail Transport Agent postfix
   ...done.
Listing SASL users
Starting...
Aug 13 14:11:13 bbc381af9435 authdaemond: Configuration error - missing 'daemons                                                                                                                                                             ' setting, using 1
Aug 13 14:11:13 bbc381af9435 authdaemond: Installing libauthuserdb
Aug 13 14:11:13 bbc381af9435 authdaemond: Installation complete: authuserdb
Aug 13 14:11:14 bbc381af9435 spamd[97]: logger: removing stderr method
Aug 13 14:11:16 bbc381af9435 spamd[99]: zoom: able to use 360/360 'body_0' compi                                                                                                                                                             led rules (100%)
Aug 13 14:11:22 bbc381af9435 spamd[99]: spamd: server started on IO::Socket::INE                                                                                                                                                             T6 [127.0.0.1]:783, IO::Socket::INET6 [::1]:783 (running version 3.4.0)
Aug 13 14:11:22 bbc381af9435 spamd[99]: spamd: server pid: 99
Aug 13 14:11:22 bbc381af9435 spamd[99]: spamd: server successfully spawned child                                                                                                                                                              process, pid 101
Aug 13 14:11:22 bbc381af9435 spamd[99]: spamd: server successfully spawned child                                                                                                                                                              process, pid 103
Aug 13 14:11:22 bbc381af9435 spamd[99]: prefork: child states: II
Aug 13 14:11:44 bbc381af9435 postfix/master[552]: daemon started -- version 2.11                                                                                                                                                             .0, configuration /etc/postfix
Aug 13 14:56:37 bbc381af9435 imapd-ssl: Connection, ip=[::ffff:104.207.83.41]
Aug 13 14:56:38 bbc381af9435 imapd-ssl: Unexpected SSL connection shutdown.
Aug 13 14:56:38 bbc381af9435 imapd-ssl: Disconnected, ip=[::ffff:104.207.83.41],

**Comment by ParadoxDelta** [comment]
is this of any help?

**Comment by tomav** [comment]
Sorry, was on vacation.
I had a look and there's a problem on the way you are mounting files into the container.

/usr/local/bin/start-mailserver.sh: 10: /usr/local/bin/start-mailserver.sh: cannot open /tmp/postfix/accounts.cf: No such file
    /etc/courier/userdb: not found.
    cp: cannot stat '/tmp/postfix/virtual': No such file or directory

As you can see, `/tmp/postfix/accounts.cf` and `/tmp/postfix/virtual` can't be found.
You have to fix your `docker` command.

As asked before, let me see how you start the container.

**Comment by ParadoxDelta** [comment]
Sorry, i didn't realise the files have to be present when you create the container. so i created blank virtual and rules.cf and an accounts.cf with one user. Now the logs look better in the beginning but then: Starting amavisd: (failed). and some ssl-alerts. do i have to create a certificate and link it in some file? i was able to connect to imap with my gmail-app but to the smtp only with the settings: Port: 587 protocoll: STARTLS (accept any certificate) and "no authentification" and some of the errors seem to point out, that this was wrong. Still can't send (internal app-error) or receive (none stored under /var/mail/myactualdomain.com/reply-to/new).
btw. is there a way to add users to the running container?


'docker run -d --name=mailserver \
        -p "25:25" -p "143:143" -p "587:587" -p "993:993" \
        -e docker_mail_domain=myactualdomain.com \
        -v /home/myusername/mailserver/spamassassin:/tmp/spamassassin/:ro \
        -v /home/myusername/mailserver/postfix:/tmp/postfix/:ro \
        --restart=on-failure:10 tvial/docker-mailserver
0d017432380aab06f7999485dd1d465f6ae3d88ad78ebb174eb6ced7532d7258
root@ubuntu:/home/myusername/mailserver# docker logs 0d0
Regenerating postfix 'vmailbox' and 'virtual' for given users
user 'reply-to' for domain 'myactualdomain.com' with password '********'
Postfix configurations
Fixing permissions
Creating /etc/mailname
Configuring Spamassassin
Starting daemons
 * Starting enhanced syslogd rsyslogd
   ...done.
 * Starting file alteration monitor FAM
   ...done.
 * Starting  saslauthd
   ...done.
 * Starting Courier authentication services authdaemond
   ...done.
 * Starting Courier IMAP server imapd
   ...done.
 * Starting Courier IMAP-SSL server imapd-ssl
   ...done.
Starting SpamAssassin Mail Filter Daemon: spamd.
 * Starting ClamAV daemon clamd
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
   ...done.
  The value of variable $myhostname is "0d017432380a", but should have been
  a fully qualified domain name; perhaps uname(3) did not provide such.
  You must explicitly assign a FQDN of this host to variable $myhostname
  in /etc/amavis/conf.d/05-node_id, or fix what uname(3) provides as a host's
  network name!
Starting amavisd: (failed).
 * Starting Postfix Mail Transport Agent postfix
   ...done.
Listing SASL users
reply-to@myactualdomain: userPassword
Starting...
Aug 17 18:04:28 0d017432380a authdaemond: Installing libauthuserdb
Aug 17 18:04:28 0d017432380a authdaemond: Installation complete: authuserdb
Aug 17 18:04:29 0d017432380a spamd[115]: logger: removing stderr method
Aug 17 18:04:30 0d017432380a spamd[117]: zoom: able to use 360/360 'body_0' compiled rules (100%)
Aug 17 18:04:32 0d017432380a spamd[117]: spamd: server started on IO::Socket::INET6 [127.0.0.1]:783, IO::Socket::INET6 [::1]:783 (running version 3.4.0)
Aug 17 18:04:32 0d017432380a spamd[117]: spamd: server pid: 117
Aug 17 18:04:32 0d017432380a spamd[117]: spamd: server successfully spawned child process, pid 119
Aug 17 18:04:32 0d017432380a spamd[117]: spamd: server successfully spawned child process, pid 120
Aug 17 18:04:32 0d017432380a spamd[117]: prefork: child states: II
Aug 17 18:04:54 0d017432380a postfix/master[570]: daemon started -- version 2.11.0, configuration /etc/postfix
Aug 17 18:05:52 0d017432380a imapd-ssl: Connection, ip=[::ffff:121.34.116.220]
Aug 17 18:05:54 0d017432380a imapd-ssl: LOGIN, user=reply-to@myactualdomain.com, ip=[::ffff:121.34.116.220], port=[27688], protocol=IMAP
Aug 17 18:05:55 0d017432380a imapd-ssl: DISCONNECTED, user=reply-to@myactualdomain.com, ip=[::ffff:121.34.116.220], headers=0, body=0, rcvd=27, sent=425, time=1, starttls=1
Aug 17 18:06:16 0d017432380a postfix/submission/smtpd[577]: connect from unknown[121.34.116.220]
Aug 17 18:06:30 0d017432380a postfix/submission/smtpd[581]: connect from unknown[121.34.116.220]
Aug 17 18:06:31 0d017432380a postfix/submission/smtpd[581]: SSL_accept error from unknown[121.34.116.220]: 0
Aug 17 18:06:31 0d017432380a postfix/submission/smtpd[581]: warning: TLS library problem: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:s3_pkt.c:1262:SSL alert number 46:
Aug 17 18:06:31 0d017432380a postfix/submission/smtpd[581]: lost connection after STARTTLS from unknown[121.34.116.220]
Aug 17 18:06:31 0d017432380a postfix/submission/smtpd[581]: disconnect from unknown[121.34.116.220]
Aug 17 18:06:55 0d017432380a postfix/submission/smtpd[581]: connect from unknown[121.34.116.220]
Aug 17 18:06:56 0d017432380a postfix/submission/smtpd[581]: lost connection after UNKNOWN from unknown[121.34.116.220]
Aug 17 18:06:56 0d017432380a postfix/submission/smtpd[581]: disconnect from unknown[121.34.116.220]
Aug 17 18:07:22 0d017432380a postfix/submission/smtpd[581]: connect from unknown[121.34.116.220]
Aug 17 18:07:22 0d017432380a postfix/submission/smtpd[581]: lost connection after UNKNOWN from unknown[121.34.116.220]
Aug 17 18:07:22 0d017432380a postfix/submission/smtpd[581]: disconnect from unknown[121.34.116.220]
Aug 17 18:07:58 0d017432380a postfix/submission/smtpd[581]: connect from unknown[121.34.116.220]
Aug 17 18:08:03 0d017432380a postfix/submission/smtpd[582]: connect from unknown[121.34.116.220]
Aug 17 18:08:12 0d017432380a postfix/submission/smtpd[583]: connect from unknown[121.34.116.220]
Aug 17 18:08:14 0d017432380a postfix/submission/smtpd[583]: SSL_accept error from unknown[121.34.116.220]: 0
Aug 17 18:08:14 0d017432380a postfix/submission/smtpd[583]: warning: TLS library problem: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:s3_pkt.c:1262:SSL alert number 46:
Aug 17 18:08:14 0d017432380a postfix/submission/smtpd[583]: lost connection after STARTTLS from unknown[121.34.116.220]
Aug 17 18:08:14 0d017432380a postfix/submission/smtpd[583]: disconnect from unknown[121.34.116.220]
Aug 17 18:10:03 0d017432380a imapd-ssl: Connection, ip=[::ffff:104.207.83.43]
Aug 17 18:10:03 0d017432380a imapd-ssl: Unexpected SSL connection shutdown.
Aug 17 18:10:03 0d017432380a imapd-ssl: Disconnected, ip=[::ffff:104.207.83.43], time=0, starttls=1
Aug 17 18:10:04 0d017432380a imapd-ssl: Connection, ip=[::ffff:104.207.83.43]
Aug 17 18:10:05 0d017432380a imapd-ssl: Unexpected SSL connection shutdown.
Aug 17 18:10:05 0d017432380a imapd-ssl: Disconnected, ip=[::ffff:104.207.83.43], time=1, starttls=1
Aug 17 18:11:22 0d017432380a postfix/submission/smtpd[577]: timeout after EHLO from unknown[121.34.116.220]
Aug 17 18:11:29 0d017432380a imapd-ssl: Connection, ip=[::ffff:104.207.83.43]
'

**Comment by tomav** [comment]
You just have to add users to `/etc/postfix/accounts.cf` and restart your container (what I do on my server), or check what is done in `start-mailserver.sh` to do it manually (not what I would do).

You should also use a data volume container for `/var/mail`.

Please have a look the last commit. I removed `docker_mail_domain ` env.
It's now more docker compliant (and easy to configure).

**Comment by tomav** [comment]
Let me know how it is going and reopen this thread if needed.
Thank you.
