### ISSUE TITLE
no crontab for root on rebuild of  image

### ISSUE THREAD

**Issue by awb99** [tomav/docker-mailserver#130]
Step 18 : RUN (crontab -l ; echo "0 1 * * * /usr/bin/freshclam --quiet") | sort - | uniq - | crontab 

I get this error when I build the new image.

I guess that this was not intended.

**Comment by tomav** [comment]
What kind of error?

Here is the log from Travis:
https://travis-ci.org/tomav/docker-mailserver/builds/122300393#L1491

**Comment by awb99** [comment]
Ups.  It says crontab (or cron) does not exist.

**Comment by tomav** [comment]
True. But it's just the output of crontab list before setting it.
Try `docker run --rm tvial/docker-mailserver crontab -l`

You should see:
`0 1 * * * /usr/bin/freshclam --quiet`

**Comment by tomav** [comment]
Will be fixed on v2.
