### ISSUE TITLE
clamd fails to start due to missing logfile permissions

### ISSUE THREAD

**Issue by KampfCaspar** [tomav/docker-mailserver#1300]
Upon starting a :latest from today, I get an infinite startup loop for clamd. 

Trying to start clamd manually, I see it cannot initialize its logger as its missing rights to /var/log/mail/clamav.log

After 'touching' /var/log/mail/clamav.log with rights for clamav:clamav, the issue is (at least temporarily) resolved.

**Comment by erik-wramner** [comment]
Are you using a volume for the logs? If so, mounted from file system or using a docker volume? And have you changed your settings, or did you just do the upgrade?

We could add a touch step, but I wonder why it is needed. I certainly don't get this problem.

**Comment by KampfCaspar** [comment]
It was a fresh install. Yes, I keep /var/mail/log in a filesystem directory, not a docker volume. The default permissions to the log directory were root write only; mail.(log|info|warn) are created as root and were therefore ok. Only clamd seems to want to create its logfile as non-root user and therefore fails.

The 'most correct' solution would probably be to check/correct permissions on the log directory upon startup. I didn't check what permissions clamd keeps up until what point.

**Comment by erik-wramner** [comment]
Indeed. This just works with volumes, but you are the second person running into this thing with a mounted directory, so I guess we should fix it.

**Comment by erik-wramner** [comment]
See #1305

**Comment by erik-wramner** [comment]
This should be fixed in latest now, please verify and close if it works.

**Comment by KampfCaspar** [comment]
Seems fine. thx
