### ISSUE TITLE
Amavis reverting to ClamScan instead of Clamd

### ISSUE THREAD

**Issue by SinisterCrayon** [tomav/docker-mailserver#1308]
Noticed that email is pretty slow of late so figured I'd start sending and receiving mail to see what's been going on.

It appears for every email now I am hitting "clamscan" for scanning my emails instead of "clamd". This means it reloads the clamav database for every email being checked which gets pretty sluggish... if I were using clamd properly then it wouldn't be a concern.

In the logs I'm seeing the following (and messages like it);

`Oct 29 22:03:41 mailserver amavis[999]: (00999-01) (!)ClamAV-clamd av-scanner FAILED: CODE(0x564aa1f9bf58) unexpected , output="/var/lib/amavis/tmp/amavis-20191029T220341-00999-wpZFF3N3/parts: lstat() failed: Permission denied. ERROR\n" at (eval 97) line 905.,
Oct 29 22:03:41 mailserver amavis[999]: (00999-01) (!)run_av (ClamAV-clamd) FAILED - unexpected , output="/var/lib/amavis/tmp/amavis-20191029T220341-00999-wpZFF3N3/parts: lstat() failed: Permission denied. ERROR\n"`

I've tried both with a permanently mapped external volume and with a temporary Docker volume but the results are the same. I can verify the folders are created properly and the contents are definitely there... the email.txt is created normally. However, clamd is never called and instead the system reverts to clamscan. The folder permissions appear consistent with what I think I'd expect; owned by amavis:amavis and with rw perms for user and r perms for group.

Additionally, these temporary folders are never cleaned up. They seem to be there indefinitely. This means the data store is constantly growing until a restart even when using a docker volume for this (or overlay).

Any thoughts or things you'd like me to look at?

**Comment by erik-wramner** [comment]
That could also explain reports about increased memory consumption. Not sure if you can test that easily, but it would be interesting to know if this is recent or if it has been there for a long time. Was it there in 6.1, for example?

**Comment by SinisterCrayon** [comment]
Erik, I can confirm that I've had to increase my memory on the host machine recently because my perception at least was that the mail server had increased in RAM usage. I can't confirm how far back it went though.

I was looking at the server in detail mostly because I'd started getting quite a few mails arriving "unchecked". I suspected that was because of memory exhaustion when running clamscan.

**Comment by SinisterCrayon** [comment]
OK... I am not sure what was going on but I just tried rebooting the host that I had the mailserver running on. I also did a complete prune/purge of all the images, containers and so on and restarted it. It now seems to be functioning normally again but I am not sure I could tell you why as I made no changes to the config.

I think I can say this is resolved.
