### ISSUE TITLE
Can I add a CI runner that I wrote supplementarily?

### ISSUE THREAD

**Issue by ColinChartier** [tomav/docker-mailserver#1309]
@tomav I wrote a CI platform and I'm trying to run it on various repositories where it might be beneficial - I've talked to Erik, who said you had the final say on things like this.

Let me know if that's something you might be interested in. The platform is at https://layerci.com - it should reduce flakiness and greatly improve speed for some commits (see #1124 's tests failing, for example)

**Comment by aendeavor** [comment]
Thank you for this interesting idea. I'm sorry but this seems to not be possible. I'm closing this in favour of #1092.
