### ISSUE TITLE
Mail attachments getting removed. How to turn it off?

### ISSUE THREAD

**Issue by JYPDWhite** [tomav/docker-mailserver#1315]
## Context
I'm receiving E-Mails sometimes with attachments and sometimes the attachments getting automatically removed.  And the following Message will be send to me (the receiver) with the original message attached to it (but without the original attachment)
```
Some parts of this message were removed because they violated your mail server's policies.
AB- Infoblatt.url.zip was removed from the message because it violates your mail server's policy.
```

## Expected Behavior
Nothing should be removed from the mail.

## Possible Fix
I think that this could be something related to amavis but a quick google search with:
```amavis removed from the message because it violates your mail server's policy.```
Doesn't gave me a hint where I should search deeper.

## Your Environment
Part of the Header of the mail:
```
X-AuditID: 0a6542d5-f0dff70000001b5f-04-5dc26bee977e
Received: from s2vg504mr02.pzd-svn.de ( [10.101.66.12])
	(using TLS with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(Client did not present a certificate)
	by s2vg504av03.pzd-svn.de (Symantec Messaging Gateway) with SMTP id E5.F7.07007.EEB62CD5; Wed,  6 Nov 2019 07:45:02 +0100 (CET)
Received: from localhost (localhost [127.0.0.1])
	by S2VG504MR02.pzd-svn.de (Amavis-Post/Sued) with ESMTP id 6FE6B89E
	for <myadress@example.de>; Wed,  6 Nov 2019 07:45:02 +0100 (CET)
X-Virus-Scanned: amavisd-new at pzd-svn.de
X-Amavis-Alert: INFECTED, message contains virus:
	MWScan/Suspicious.File.url.UNOFFICIAL
Received: from s2vg504mr02.pzd-svn.de ([127.0.0.1])
	by localhost (s2vg504mr02.pzd-dvn.de [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id f3iPIPeJ3A_0 for <myadress@example.de>;
	Wed,  6 Nov 2019 07:45:02 +0100 (CET)
Received: from S2VG502MR01.pzd-svn.de (s2vg502mr01.pzd-svn.de [10.101.65.11])
	by S2VG504MR02.pzd-svn.de (Amavis-Pre/Sued) with ESMTPS id 5A4B892F
	for <myadress@example.de>; Wed,  6 Nov 2019 07:45:02 +0100 (CET)
Received: from mail-rhu16.dresden.de (unknown [10.166.253.137])
	by S2VG502MR01-S.pzd-svn.de (Mailhub-Pre/Sued) with ESMTPS id 555FD83C
	for <myadress@example.de>; Wed,  6 Nov 2019 07:45:02 +0100 (CET)
Received: by mail-rhu16.dresden.de (Postfix, from userid 113)
	id 45A6061ECD; Wed,  6 Nov 2019 07:44:45 +0100 (CET)
Received: from RathausDD02.dresden.de (unknown [10.146.166.31])
	by mail-rhu16.dresden.de (Postfix) with ESMTP id 21B4C61ECF
	for <myadress@example.de>; Wed,  6 Nov 2019 07:44:45 +0100 (CET)
```

* Environment settings relevant to the config:
```
ENABLE_CLAMAV=0
ENABLE_SPAMASSASSIN=1
```

**Comment by erik-wramner** [comment]
Without being 100% sure I think your problem is in Symantec Messaging Gateway. See https://support.symantec.com/us/en/article.TECH230451.html. It is present in your log:
```
Received: from s2vg504mr02.pzd-svn.de ( [10.101.66.12])
	(using TLS with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(Client did not present a certificate)
	by s2vg504av03.pzd-svn.de (Symantec Messaging Gateway) with SMTP id E5.F7.07007.EEB62CD5; Wed,  6 Nov 2019 07:45:02 +0100 (CET)
```
It also says in the log that it found a virus, so perhaps it is just as well that the file got removed?

**Comment by JYPDWhite** [comment]
> Without being 100% sure I think your problem is in Symantec Messaging Gateway. See https://support.symantec.com/us/en/article.TECH230451.html. It is present in your log:
> It also says in the log that it found a virus, so perhaps it is just as well that the file got removed?

I also stumbled upon that lines in the header. But than this is more a sender than a receiver problem because I don't use Symantec Messaging Gateway.

**Comment by erik-wramner** [comment]
According to the log the message does go through Symantec Messaging Gateway, so it could well be removed there. Or can you provide another similar log where a message is stripped without going through Symantec Messaging Gateway?

**Comment by JYPDWhite** [comment]
Ok problem is kind of "solved". I notified the postmaster of the sending network and they agreed that this is a false alarm on their network and they will take care of it. So this is not a issue in docker-mailserver.

By the way thanks @tomav for the great work and all the time to put this thing together.
