### ISSUE TITLE
Add `reject_unknown_helo_hostname` to `smtpd_helo_restrictions`.

### ISSUE THREAD

**Issue by mathuin** [tomav/docker-mailserver#1320]
Currently we block invalid HELO hosts, we should also block unknown HELO hosts.

## Context

Currently the `smtpd_helo_restrictions` line includes a setting to block invalid `HELO` hosts.  The single most persistent spammer I face uses a hostname that does not resolve, which means it is unknown.  Adding `reject_unknown_helo_hostname` appears to block this spammer.

## Expected Behavior

Currently I should not be getting spam from hosts with unknown names (i.e., whose names do not resolve to the addresses from which they come)

## Actual Behavior

I am getting spam from them :-(

## Possible Fix

I am currently testing the recommended addition and it is working for me.  It may be worth adding the same flag to `smtpd_recipient_restrictions` as well.

## Steps to Reproduce

1. Fork the repo, create a new branch.
2. With the editor of your choice, open the file `target/postfix/main.cf`.
3. Modify line 45 (and possibly line 47) to include `reject_unknown_helo_hostname`.
4. Profit!

## Your Environment

* Amount of RAM available:
* Mailserver version used: latest as of today
* Docker version used: 18.06.3-ce on CoreOS 2079.3.0
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by erik-wramner** [comment]
We won't change that as it will break many domains (including some of mine). All real domains don't have valid reverse addresses. However, if you want to get rid of that spam and accept the risk of losing legitimate messages from such domains you don't need to fork the repo. Simply override the setting in config/postfix-main.cf as described in the FAQ in the Wiki and set the value you want.

**Comment by mathuin** [comment]
I'll close the issue as it won't be changed -- for good reason -- but I think this tip and explanation will be valuable for other users who come here wondering why that's not set.  Thanks!
