### ISSUE TITLE
Obsolete filebeat

### ISSUE THREAD

**Issue by gmasse** [tomav/docker-mailserver#1321]
Filebeat version in the container is pretty old (version 1.3.1 published in 2016). Some ELK providers does not support a so old version.

## Possible Fix
The new version can easily be updated in the container by fixing the Filebeat repository
(deb https://artifacts.elastic.co/packages/7.x/apt stable main).

But I am concerned about compatibility issues. What would be the best way to deal with that?

**Comment by erik-wramner** [comment]
Personally I would like to get rid of filebeat. I think the best way of running it is to use it in a standalone container that accesses the logs. Mixing filebeat into docker-mailserver feels wrong. However, it is there and I guess there are people using it. I think there are two options. One would be if the new version had an option to be backwards compatible. The other would be to do the upgrade as a major change, for example when we switch to buster.

**Comment by gmasse** [comment]
Filebeat can rely on Docker labels to autodiscover container and configure logs
(https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html). It could be an elegant way to deal with ELK. What do you think? I can make some tests and update the Wiki section accordingly.

In this case, Filebeat could be completely removed from the future major release.

**Comment by erik-wramner** [comment]
I think that would be great.

**Comment by aendeavor** [comment]
This should be done with the latest version. If this wasn't the case, please re-open this issue.
