### ISSUE TITLE
Will docker-mailserver support podman?

### ISSUE THREAD

**Issue by OrwillT** [tomav/docker-mailserver#1322]
RHEL/CentOS 8 provide podman and buildah as the default container tools. So will docker-mailserver support podman?

**Comment by fbartels** [comment]
Hi @OrwillT,

the whole podman eco-system is meant to be compatible with the Docker world, so I would suspect for it to work. But the only way to really find out is for you to try and then lets us know.

It should either fail early or not at all.

**Comment by OrwillT** [comment]
And the answer is no.
I can't deploy the docker-compse file with [podman-compose](https://github.com/containers/podman-compose), and also can't use setup.sh to visit container.

**Comment by erik-wramner** [comment]
This is a community effort and the docker image itself might run even if the compose scripts (which are only provided as a template anyway) fail. If you can make it work we'll be happy to consider a PR and/or to update the documentation! Personally I don't intend to use podman any time soon, though.

**Comment by OrwillT** [comment]
I believe I'll give it a try when I could as soon as possible.

**Comment by OrwillT** [comment]
```
Nov 21 19:11:53 los00 amavis[261]: Net::Server: Group Not Defined.  Defaulting to EGID '111 111'
Nov 21 19:11:53 los00 amavis[261]: Net::Server: User Not Defined.  Defaulting to EUID '109'
```

Is this correct?
Not only amavis have this issue, opendmarc, opendkim, dovecot have this user/group not defined issues too.

**Comment by erik-wramner** [comment]
I get that error as well with docker. I don't like it, but as you say everything seems to work regardless.

**Comment by OrwillT** [comment]
@erik-wramner  @fbartels  #1327 Here it is.
