### ISSUE TITLE
Fetchmail issue

### ISSUE THREAD

**Issue by ddldl** [tomav/docker-mailserver#1328]
Just tried to configure fetchmail apart than it's shown in the wiki - thats btw working just fine, all mails from my relay server getting fetched to the given mail user.

I'm looking for a solition, where the fetched mails are not only delivered to simply one mailbox (like *@domain.tld >> webmaster@domain.tld). I need that they are sorted to existing local mailboxes (user1@domain.tld >> mailbox: user1, user2@domain.tld >> mailbox: user2).

All mails to non existing mailboxes may deliverd to the webmaster, like user3@domain.tld (no local mailbox) >> webmaster@domain.tld (like catchall).

Does anybody have a fetchmail config solution for that purpose?

**Comment by ninkaninus** [comment]
Where did you find an answer?

**Comment by ddldl** [comment]
By reading fetchmails entire how-to.

Just config **fetchmail.cf** like this

`set_postmaster "postmaster@yourdomail.tld"`

`poll                    <yourrelayhost>`
`localdomains      <yourdomain.tdl>`
`protocol             protocol, like <IMAP>, <POP>, ...`
`envelope            "X-Envelope-To:"`
`user                    '<login at relayhost>'`
`pass                    '<pass at relayhost>'`
`to * here`
`ssl`
