### ISSUE TITLE
Support and/or document plus addressing

### ISSUE THREAD

**Issue by Yajo** [tomav/docker-mailserver#1330]
## Context

Gmail, Zoho and several other mail providers automatically forward all `myuser+whatever-i-want-to-add-here@mydomain.com` to `myuser@mydomain.com`. It is an automatic alias system that helps users have their mail boxes well ordered and is required by some softwares (such as [Odoo, which uses it to detect and process bounces](https://github.com/odoo/odoo/blob/6258c7eba905ee0d9591573dc8b0c90e6dc7111e/addons/mail/models/mail_thread.py#L911-L924)).

## Expected Behavior

This should be automatic out of the box if something like `PLUS_ADDRESSING=1` is passed.

## Actual Behavior

Still not tested. TODO.

**Comment by j-marz** [comment]
@Yajo i can confirm user+something@domain.com works out of the box - i use it with a number of my mail users.

**Comment by Yajo** [comment]
Well, that's great! Then this should be documented instead.
