### ISSUE TITLE
How to setup a catch-all mail but block specific ones

### ISSUE THREAD

**Issue by boop5** [tomav/docker-mailserver#1335]
I've one account for my mail server `root@foo.bar`

I just forward everything to this account with a virtual setup

**postfix-virtual.cf**
```
@foo.bar root@foo.bar
``` 

So I can register all my accounts like this

`amazon@foo.bar`
`github@foo.bar`
`some-random-service@foo.bar`

But how can I *block* specific *accounts*?

Lets say my `some-random-service@foo.bar` mail got leaked and I keep getting spam on it. So I want to reject all mails sent to this address. Or just delete them on receive. Doesn't really matter to me.

Is there a way I can set this up?

**Comment by gmasse** [comment]
This should work:

Create a devnull user that redirect to /dev/null
**postfix-aliases.cf**
`devnull:	/dev/null`

Then redirect your specific leaked account to devnull user:
**postfix-virtual.cf**
`some-random-service@foo.bar devnull`

**Comment by erik-wramner** [comment]
@boop5 please test and close this issue if it works. If it does work it would be nice with an update to the FAQ in the wiki as well.

**Comment by boop5** [comment]
@gmasse Thanks for your replay. That sounds very straightforward. Unfortunately it's not working. I did it even w/o alias and checked the devnull mailbox. It was nothing received. Even when I sent a mail directly to `devnull@foo.bar` nothing was received.

Of course I reloaded everything with

```
postalias /etc/postfix/aliases
newaliases
postmap /etc/postfix/virtual
postfix reload
```

**Comment by erik-wramner** [comment]
@boop5 sorry for asking, but just in case: when you write "nothing received" you mean the messages were rejected according to the server logs, or what do you mean? The whole point of using `/dev/null` is to just throw away the received messages and pretend they are saved, so if you are checking in the file system it will always be empty.

**Comment by boop5** [comment]
@erik-wramner I removed the alias and checked the inbox of **devnull@foo.bar**. it was empty. Though it was in **root@foo.bar**

**Comment by gmasse** [comment]
@boop5 just tested on a fresh install and it works as expected:

```console
$ telnet 51.91.x.y 25
Escape character is '^]'.
220 mail.mydomain.com ESMTP Postfix (Debian)
HELO mail.antipod.com
250 mail.mydomain.com
MAIL FROM: ****
250 2.1.0 Ok
RCPT TO: some-random-service@foo.bar
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
Date: Thu, 19 Dec 2019 10:16:19 +0000
From: ****
To: some-random-service@foo.bar
Subject: Test leaked account

dsqdsqdsd
dsdsqdqdsd
qqsdqsdqsds
dqsqsdqsd
.
250 2.0.0 Ok: queued as DF56B4410B
```

Container logs:
```
mail    | Dec 19 11:03:21 mail postfix/qmgr[4431]: DF56B4410B: from=<****>, size=544, nrcpt=1 (queue active)
mail    | Dec 19 11:03:21 mail postfix/smtpd[4697]: connect from localhost[127.0.0.1]
mail    | Dec 19 11:03:21 mail postfix/smtpd[4697]: CE09E4410C: client=localhost[127.0.0.1]
mail    | Dec 19 11:03:21 mail postfix/cleanup[4590]: CE09E4410C: message-id=<20191219110321.CE09E4410C@mail.mydomain.com>
mail    | Dec 19 11:03:21 mail postfix/qmgr[4431]: CE09E4410C: from=<****>, size=877, nrcpt=1 (queue active)
mail    | Dec 19 11:03:21 mail postfix/smtpd[4697]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
mail    | Dec 19 11:03:21 mail amavis[1006]: (01006-03) Passed SPAMMY {RelayedOpenRelay}, [51.91.x.z]:42248 [51.91.x.z] <****> -> <devnull@mail.mydomain.com>, Queue-ID: DF56B4410B, mail_id: aYR5pgoDLUSW, Hits: 2.066, size: 602, queued_as: CE09E4410C, 519 ms
mail    | Dec 19 11:03:21 mail postfix/smtp[4678]: DF56B4410B: to=<devnull@mail.mydomain.com>, orig_to=<some-random-service@foo.bar>, relay=127.0.0.1[127.0.0.1]:10024, delay=49, delays=49/0/0.01/0.52, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as CE09E4410C)
mail    | Dec 19 11:03:21 mail postfix/qmgr[4431]: DF56B4410B: removed
mail    | Dec 19 11:03:21 mail postfix/local[5053]: CE09E4410C: to=<devnull@mail.mydomain.com>, relay=local, delay=0.03, delays=0.01/0.02/0/0, dsn=2.0.0, status=sent (delivered to file: /dev/null)
mail    | Dec 19 11:03:21 mail postfix/qmgr[4431]: CE09E4410C: removed
```

Configuration files:
```console
$ cat config/postfix-accounts.cf
root@foo.bar|{SHA512-CRYPT}$6$VcDF9xGZfbNsHJBv$/1G6whPb4/ClPyCtIdNvHU4HY6HchWE.44.G/bQY3rpYygspCgdLyejWCf88NuNxA.JIcN07krhObPlZwAi0h0

$ cat config/postfix-aliases.cf
devnull:	/dev/null

$ cat config/postfix-virtual.cf
@foo.bar root@foo.bar
some-random-service@foo.bar devnull
```

**Comment by boop5** [comment]
Thank you for your effort. I think I had a misunderstanding of the alias concept. I've created an account with an additional alias.

Anyway this seems to work fine with the proper configuration. Thank you.

**Comment by gmasse** [comment]
> If it does work it would be nice with an update to the FAQ in the wiki as well.

@erik-wramner, 2 Q&A added to the FAQ:
https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips/_edit#how-can-i-configure-a-catch-all
https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-delete-all-the-e-mails-for-a-specific-user

**Comment by boop5** [comment]
I can do it once I find time. Likely gonna be 2020 though.
