### ISSUE TITLE
./setup.sh cannot create DKIM keys

### ISSUE THREAD

**Issue by kda406** [tomav/docker-mailserver#1336]
Using a fresh Linux server, I am following the Installation Example on this page: [https://github.com/tomav/docker-mailserver/wiki/Installation-Examples](url) and setup.sh gives an error.

When I get to bullet #5, I get the following error:
`[dock@port ~]$ ./setup.sh config dkim
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
[dock@port ~]$`

It seems like an error in the setup.sh script, and I am unsure how to proceed.

I tried adding a -a argument to the INFO= line of setup.sh to no avail (I got the idea from this post [https://github.com/tomav/docker-mailserver/issues/1252](url))

FWIW, "docker ps -a" shows nothing because mail has not run yet.  This is early setup, so it seems like I should not run the container yet, since it is not setup.  But a straight follow of the instructions gives me this error.  I have wiped the server, reinstalled Linux, and tried this twice so far to the same result.

## Environment
* Void Linux (Void is a rolling release, so it is always the latest version)
* 4GB RAM
* Docker 19.03.5

Other images like
`docker run --rm -it ubuntu:latest /bin/bash`
successfully create/run/destroy their containers on this machine.

**Comment by erik-wramner** [comment]
There was a change in setup.sh recently to support podman, my guess is that it has broken something. Could you try with the stable release and see if that works? If it does work we need to fix setup.sh in the latest release, but it would be nice to know where the error is.

**Comment by kda406** [comment]
Same issue.  I deleted all the files in the working directory.  I re-pulled the files from the stable branch:
`curl -o docker-compose.yml https://raw.githubusercontent.com/tomav/docker-mailserver/stable/docker-compose.yml.dist
curl -o .env https://raw.githubusercontent.com/tomav/docker-mailserver/stable/.env.dist
curl -o setup.sh https://raw.githubusercontent.com/tomav/docker-mailserver/stable/setup.sh; chmod a+x ./setup.sh `
(this is what you meant for me to try, yes?)

I used nano to edit the .env file and then ran setup.sh:
`[dock@port ~]$ ./setup.sh config dkim
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
[dock@port ~]$`

I attached the setup.sh file in case you think I pulled the wrong one.
[setup.zip](https://github.com/tomav/docker-mailserver/files/3951477/setup.zip)

**Comment by erik-wramner** [comment]
Sorry for the slow response, I've been rather busy. I'll try to replicate and fix this.

**Comment by erik-wramner** [comment]
This should be solved now. However, at least for me the command completed successfully in spite of the error message. Please confirm and close.

**Comment by erik-wramner** [comment]
Closing due to no response, please reopen if the problem persists.
