### ISSUE TITLE
WARNING: Your ClamAV installation is OUTDATED!

### ISSUE THREAD

**Issue by helmutundarnold** [tomav/docker-mailserver#1342]
Logwatch complains:  WARNING: Your ClamAV installation is OUTDATED!
## Context

Logwatch checks if there is a newer version for ClamAV available and if not it reports following:
```
    WARNING: Your ClamAV installation is OUTDATED!    
    WARNING: Local version: 0.101.4 Recommended version: 0.102.1    
```
I've learned that the only chance is to recompile ClamAV outside of the container and copy it back afterwards.

In worst case it can happen, that ClamAv doesn't work as expected and in consequence mails are not scanned properly.

## Expected Behavior

Always updated ClamAV and avoid complaining logwatch mails.

## Actual Behavior

Since its not update it reports something like

```
    WARNING: Your ClamAV installation is OUTDATED!   
    WARNING: Local version: 0.101.4 Recommended version: 0.102.1   
```
```
## Possible Fix
<!--- Not obligatory, but suggest a fix or reason for the issue -->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this issue include code to reproduce, if relevant -->
1.
2.
3.
4.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the issue in -->
* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

<!--- Please remember to format code using triple backticks (`)
	  so that it is neatly formatted when the issue is posted. -->


<!---
## Possible answers to you issue
* ClamAV keeps restarting:
  https://github.com/tomav/docker-mailserver#requirements

* Email seen as spam:
  https://github.com/tomav/docker-mailserver/wiki/Configure-SPF
  https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM

* Creating new domains and accounts
  https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts

* Use a relay mail server
  https://github.com/tomav/docker-mailserver/wiki/Configure-AWS-SES
  The variable name can be used for other email servers.

* FAQ and tips
  https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips

* And the WIKI
  https://github.com/tomav/docker-mailserver/wiki

* Open issues
  https://github.com/tomav/docker-mailserver/issues
-->

**Comment by erik-wramner** [comment]
I'm afraid this is a wontfix in this case. I hope that it will be solved when we upgrade to Debian Buster. In the meantime we have the latest ClamAV that is supported by Debian Stretch. I've learned the hard way that it is a bad idea to try to use an unsupported version of ClamAV.

Perhaps we could suppress the warning somehow, but the real fix is to do the upgrade. There is nothing stopping us there except time.

**Comment by erik-wramner** [comment]
It could also be that we need #1207 if the image you are pulling is outdated.

**Comment by oblitum** [comment]
Folks, this may have started to become a serious problem. Past month I've built the image without issues, now I can't, the ClamAV step states it's outdated, then the `freshclam` tries to update database but always timeouts:

```
 => [5/40] RUN echo "0 */6 * * * clamav /usr/bin/freshclam --quiet" > /etc/cron.d/clamav-freshclam &&   chmod 644 /etc/clamav/freshclam.conf &&   freshclam &&   sed -i 's/Foreground false/Foreground true/g' /etc/clamav/clamd.conf &&  32.1s
 => => # Thu Feb 20 01:23:52 2020 -> ^Local version: 0.102.1 Recommended version: 0.102.2
 => => # Thu Feb 20 01:23:52 2020 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
 => => # Thu Feb 20 01:23:52 2020 -> daily database available for download (remote version: 25728)
 => => # Thu Feb 20 01:24:22 2020 -> ^Download failed (28) Thu Feb 20 01:24:22 2020 -> ^ Message: Timeout was reached
 => => # Thu Feb 20 01:24:22 2020 -> ^getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
 => => # Thu Feb 20 01:24:22 2020 -> Trying again in 5 secs...
```

Maybe this will get solved when the Buster build arrives? Any expected timeline on that?

Regards.

**Comment by oblitum** [comment]
I have no idea why it timeouts, I can access `https://database.clamav.net/daily.cvd` with `curl` without problems.

**Comment by erik-wramner** [comment]
@oblitum I can download clamav updates, so I don't think your problem is general. Hopefully it works out if you try again later?

As for the buster release it is basically ready, but it needs testing and some documentation. If you want to be a test pilot you can get it from my docker repo (I don't have access to the docker builds for this project) or you can build it from the `next` branch in this repo.

**Comment by oblitum** [comment]
@erik-wramner it simply stopped working, I tried it over more than two days span, can't get out of timeout. Also, I'm running it on RPi3 with ARMv8 (64bit, not ARMv7/32bit as usual). I had to apply some patches to master, but moving to `next` is another complication, I've also read some reports that some parts are not yet working.

**Comment by oblitum** [comment]
>  I'm running it on RPi3 

But building from x86-64 (with `docker buildx`).

**Comment by oblitum** [comment]
I suspect that it tries to download the file (`daily.cvd`), but as my network speed is not great, it doesn't finish downloading (54 MB) as fast as freshclam expects.

**Comment by oblitum** [comment]
You may not hit the issue because your network is faster than mine.

**Comment by oblitum** [comment]
I found why this is happening:

```
❯ sudo rg -g freshclam.conf ReceiveTimeout /var/lib/docker/overlay2
/var/lib/docker/overlay2/dlsqvhnmg86xdfidpu9g9ua1i/diff/etc/clamav/freshclam.conf
18:ReceiveTimeout 30
```

It looks like standard `clamav` installation on Debian has this stupidly small timeout. I think this needs to be circumvented.

**Comment by erik-wramner** [comment]
We can try and see if it helps, though 30 seconds as a read timeout seems reasonable for getting static files. It is not for getting the whole file but closer to time to first byte.

**Comment by oblitum** [comment]
@erik-wramner I increased to 3600 and fixed my issue. Notice the problematic timeout is not regarding _connection_, but _receive_. I've left the connection timeout as-is, 30, but receive at 30s doesn't work on my network speed for a ~60MB file, and I checked network at that step, it was indeed continuously downloading the update, until it timeouts and it  enters a loop and gives up after 5 attempts.

**Comment by erik-wramner** [comment]
I don't know the internals here, but normally the receive timeout is from a call to receive on a socket until the receive returns. It does not need to read the entire file, one single byte is enough (but more commonly you'll get one network packet at least). It doesn't matter if the file is 1 byte or 1000MB it just means receive will be called more times. In that context 3600 seconds is a very long timeout. FTP is different as the control connection may time out while the data file is read. Perhaps clamav is trying to read the files with FTP in your case?

What I'm trying to say is that 3600 seconds is a very long time for the program to hang if there is a network issue. Have you tried with a more moderate value? Perhaps 90 seconds is enough?

**Comment by oblitum** [comment]
I don't think that's the issue, what you're describing doesn't fit the behavior. Doesn't it have to update the virus definitions? If it does, then it needs to download the file. The thing is, at least for me (and some other people if you google the error message), it starts to download that file and after half a minute it's canceled and starts again. Whether `ReceiveTimeout` should have meant another thing in thesis, I'm not sure, but I got that. Thing is that in practice, it's being associated to download time on I'm machine. I didn't see any mention for FTP in error message logs, I don't think it's being used (notice I've mentioned I used curl GET on the file).

**Comment by oblitum** [comment]
So, sure 3600 is bad in case of an actual hang, but safe for download time. 90 is not bad for a hang, but is still unsafe for download time. It could possibly fix, because the download would happen to finish earlier.

**Comment by oblitum** [comment]
FWIW, on my ArchLinux, the freshclam. conf doesn't have any of these timeouts set, and it works fine to get the updates.

**Comment by erik-wramner** [comment]
There is probably a default value that is used if there is no explicit configuration. How long do you need for a successful download? 90 seconds is not a holy number, but 3600 is too much to make it into the default image. Perhaps we can make it a user option in some way.

**Comment by oblitum** [comment]
I think an option is better, because the size of this update file is unknown upfront, to give you an idea, after the first 50MB download, iirc, it downloads another ~100MB update (meaning, it's not just one file). And I'm not sure how timeout is being used for each download.

**Comment by oblitum** [comment]
This issue doesn't not happen in Buster.
