### ISSUE TITLE
Spam not marked with x-header when virtual domains are served from ldap

### ISSUE THREAD

**Issue by pelicangris** [tomav/docker-mailserver#1347]
I have battled a long time with an issue where spam emails were not marked with a x-header.
Investigations have shown this is because @local_domains_maps in the amavis config files that is never populated with my virtual domains.

## Context
I am using an ldap server to configure my users, groups and emails and therefore have a config/postfix-accounts.cf file that is completely empty. This file is read to generate the content of /etc/postfix/vhost and the resulting file only contains the domain of the host and none of my virtual domains.

## Expected Behavior
As i am defining my virtual domains via LDAP_QUERY_DOMAIN, i was expecting for /etc/postfix/vhost to contain my virtual domaines.

## Actual Behavior
/etc/postfix/vhost only contains the name of the host.

## Possible Fix
I have added a user-patches.sh file that checks the content of /etc/postfix/vhost and adds my virtual domains where necessary but this is a bit hacky.

**Comment by erik-wramner** [comment]
I'm not using LDAP myself, but it sounds like something most people with LDAP should run into? I'll flag the issue "help wanted", perhaps someone has a better solution.

**Comment by aendeavor** [comment]
@pelicangris the population of this map was reworked with the refactoring of `Start-mailserver.sh`. Does this still persist?

**Comment by pelicangris** [comment]
Hi @aendeavor, I have just tried to pull the latest image and tested by removing my hacky user-patches.sh script.
/etc/postfix/vhost only lists my hostname and not my LDAP_DOMAIN so the issue still exists.

**Comment by aendeavor** [comment]
Alright @pelicangris. I'm rather confident that the population of the `vhost`s map is done correctly. I've not worked with LDAP before, therefore I cannot say anything about it really, but my suggestion would be this: Since the `vhost`s file _should_ be correct, the issue seems to be somewhere else.

What does

> @local_domains_maps

actually do and where does it point to? You also said

> `config/postfix-accounts.cf` is completely empty [...] (but) this file is read to generate the content of `/etc/postfix/vhost`

so the `vhost`'s file must be empty because `config/postfix-accounts.cf` is actually empty? Maybe some error in LDAP_QUERY_DOMAIN is causing this behavior? Have you read thorugh other issues related to LDAP in this issue tracker? If not, please do so:)

**Comment by pelicangris** [comment]
I have checked my query for domains using the below and it is returning entries so i think my LDAP_QUERY_FILTER_DOMAIN environment variable is correct.

`docker exec mail /bin/sh -c "postmap -q example.com ldap:/etc/postfix/ldap-domains.cf"`

I have had a peek at function _setup_ldap as advised and the only reference i see to a construction of /tmp/vhost.tmp is this:

`# add  domainname to vhost`
` echo "${DOMAINNAME}" >>/tmp/vhost.tmp`

This seems to build vhost using only the domain name of the container and none of the virtual domains.

Also, i do not have any postfix-accounts.cf file in /config which i sort of expect as user/passwords are stored in LDAP rather than in files.

**Comment by aendeavor** [comment]
Alright. Could you try adding the domains "by hand", i.e. `echo`-ing them manually in the`_setup_ldap` function? Then build the container and see whether this resolved it? If this is the case, we'll need to implement this in the `start-mailserver.sh` script. This way we can eliminate all possible causes one by one.

PS: This could very we'll be a big, so I've marked it appropriately:)

**Comment by pelicangris** [comment]
Alright, i have tweaked function _setup_ldap in start-mailserver.sh with the below:

`  # add  domainname to vhost`
`echo "example.com" >>/tmp/vhost.tmp`

When i run the container i now have the below content in /etc/postfix/vhost:
`docker exec -it mail cat /etc/postfix/vhost`
`example.com`

Thanks for looking into this!

**Comment by aendeavor** [comment]
Very good. We will now need to find out whether this is actually a bug or whether the `start-mailserver.sh` script should in practice add these domains to the `vhost` file. Where do you query your domains from? Are they in an environment variable?

**Comment by pelicangris** [comment]
As i was starting from a blank LDAP server when setting up my mailserver, I haven't been very imaginative so i have mirrored everything from the configuration that is available in this repo to test. I therefore have this:

`LDAP_QUERY_FILTER_DOMAIN=(&(\|(mail=*@%s)(mailAlias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))`

At the moment i have only one domain set up in my production environment.

**Comment by aendeavor** [comment]
First of all, it's nice to hear that this sort of fixed the problem, even if it is a manual fix.

But I'm now rather confident that is probably a misconfiguration, but I'm not 100% sure on this one. What value is set in the `DOVECOT_HOSTS` environment variable? Have you tried altering this, playing with it? I just cannot imagine no other LDAP users have stumbled upon this issue... Have you looked into the logs of your LDAP server?

I mean, when you are in a production environment, you will most likely use `:stable`. These releases are not that frequent, so the manual build is an easy fix. But this isn't as clean as I'd like. I'd suggest playing a bit with the LDAP configuration / environment variables.

To clarify:

> the resulting file only contains the domain of the host and none of my virtual domains

So `DOMAINNAME` is set correctly (the log should show `"Domain has been set to ${DOMAINNAME}"`)?

**Comment by pelicangris** [comment]
I'm not sure i understand your question regarding DOVECOT_HOSTS. I didn't set this as a container environment variable.
Looking into _setup_ldap, DOVECOT_HOSTS seems to be derived from LDAP_SERVER_HOST which is set to LDAP_SERVER_HOST=ldap.  Within the container, LDAP_SERVER_HOST is set correctly however DOVECOT_HOSTS appears to be empty.

Monitoring my LDAP logs when running `docker exec mail /bin/sh -c "postmap -q example.com ldap:/etc/postfix/ldap-domains.cf"` shows the query completes successfully.

I have scanned through my container logs and I do not see "Domain has been set to ..."

**Comment by aendeavor** [comment]
Alright. I'm just trying to get through all the variables here (no pun intended).

At the moment, I think that it's most likely an LDAP configuration which _should_ grab your domain but doesn't. You mentioned you just copied the LDAP configuration from the `README`. This question is kind of wide, but is everything else working fine? Is this was the case, we would somehow need to get the domains in this `vhost` file. But I really don't know how.

**Comment by pelicangris** [comment]
Everything seems to be working otherwise. I have even set up email aliases.

One thing i have noticed...
`docker exec mail /bin/sh -c "postmap -q example.com ldap:/etc/postfix/ldap-domains.cf"` returns the following:
`user1@example.com,user2@example.com`. I am going through postifx documentation but it doesn't seem right to me. I think i should have only `example.com`as a result?

**Comment by aendeavor** [comment]
Investigating there is a good idea.

**Comment by pelicangris** [comment]
Some progress, possibly. Here is the content of /etc/postfix/ldap-domains.cf:

>bind             = yes
bind_dn = cn=admin,dc=example,dc=com
bind_pw = <strongpassword>
query_filter = (&(|(mail=*@%s)(mailAlias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))
result_attribute = mail
search_base = dc=example,dc=com
server_host = ldap
start_tls        = no
version          = 3

I think result_attribute should be set to 'dc' rather than 'mail'. But how can i change this through the docker environment variables?

**Comment by aendeavor** [comment]
I don't know, but maybe @erik-wramner does?:)

**Comment by pelicangris** [comment]
I have had a look at the non ldap set up in start-mail-server.sh and it looks like if users are stored in postfix-accounts.cf then the process is to iterate through the list of users, extract the domains and add to vhost. This is not at all what is done in _setup_ldap where only one domain (DOMAINNAME) gets added to  vhost.tmp. 
Is this intended?

Regardless, it looks like DOMAINNAME is setup at the beginning of the script with the hostname. I think it should be set with the actual domain name of the container?

**Comment by aendeavor** [comment]
Whether this is intended or not I do not know, this was done before my time. Feel free to experiment with this.

The DOMAINNAME should actually work fine, at least, if it wasn't, we would see a LOT of errors...

**Comment by erik-wramner** [comment]
I haven't touched the LDAP integration, so I really can't tell. Most likely the idea is that the users are found in LDAP, not in the accounts file. If the users are never added to the file then it makes no sense to scan it for domains. That way only one domain is supported, but perhaps that is the way it is? The current logic for DOMAINNAME ought to be correct.

**Comment by pelicangris** [comment]
My point was that if users are stored in accounts files, then the set up scripts iterates through the list and add the domain names to vhost.tmp.

However, for LDAP, only the hostname of the container gets added and none of the domains that are returned by the LDAP query.

**Comment by erik-wramner** [comment]
There can certainly be bugs/omissions in the LDAP part, I haven't touched it personally and quite often people (naturally) focus on what they need. It sounds as if we could do the same thing with the LDAP users  as with the accounts file?
