### ISSUE TITLE
catchall forward+local mailbox seem impossible

### ISSUE THREAD

**Issue by mindrunner** [tomav/docker-mailserver#1355]
Assuming, I have a super simple setup. Only one domain `domain.com`, one local mailbox `mail@domain.com` and an external mailbox (e.g. Gmail) `me@gmail.com`

The goal is to catch-all emails, forward them to external as well as to the local mailbox.

```
@domain.com me@gmail.com mail@domain.com
```

Results in mails arriving twice at the external service (can see this in the logs as well).

```
mail@domain.com mail@domain.com
@domain.com me@gmail.com mail@domain.com
```
Seems to make no difference. :(

What is the solution? If there is one. Or is the duplication issue a bug?

**Comment by erik-wramner** [comment]
Not sure but perhaps https://superuser.com/questions/721917/mixing-virtual-forwards-and-virtual-mailboxes-in-postfix can help? They mention having the catch-all first (you have it last) in the comments and it seems they solved the problem. They don't mention duplicates though.

**Comment by erik-wramner** [comment]
Another idea is to use host.domain.com on the right hand side and forward to a truly local account. Forwarding someone@domain.com to someone@domain.com does look odd. Forwarding someone@domain.com to someone@mail.domain.com might work better?

**Comment by mindrunner** [comment]
Cool, I will try that out!

Is there any reason why I need to use an email address as the account-names? I personally would prefer using simple usernames. This also could eliminate the ambiguation between addresses and accounts.

**Comment by erik-wramner** [comment]
Try it. The docs said something about domain being needed when there were multiple domains, but if it works it is certainly cleaner.

**Comment by mindrunner** [comment]
It does not really help yet. But I also do not understand what they are doing in 
`
 https://superuser.com/questions/721917/mixing-virtual-forwards-and-virtual-mailboxes-in-postfix
`
>you just have to specify the domain in virtual_mailbox_domains but not in virtual_alias_domains

How do I do that in `docker-mailserver`?

> Forwarding someone@domain.com to someone@mail.domain.com might work better?

So I create another account collector@mail.domain.com and then
```
@domain.com me@gmail.com mail@domain.com
mail@domain.com collector@mail.domain.com
```
Is that what you mean? Does not work here. No mails arrive at collector@mail.domain.com account.

> Try it. 
Try what?

**Comment by erik-wramner** [comment]
With "try it" I meant try using an account name without domain.

As for the other questions I don't know, but I thought if you could get your problem fixed by editing the Postfix configuration files (directly in the container or using the overrides in the conf directory) then we could think about how to solve it in docker-mailserver later. It is easier when you know where you are trying to go. Otherwise perhaps someone who has used forwarding more can help, personally I'm only using simple forwards and that works out of the box.

**Comment by mindrunner** [comment]
> With "try it" I meant try using an account name without domain.

Ah ok :) Tried omitting the domain seems equivalent to suffixing it with mail.domain.com. It did not help either, though.

> As for the other questions I don't know, but I thought if you could get your problem fixed by editing the Postfix configuration files (directly in the container or using the overrides in the conf directory) then we could think about how to solve it in docker-mailserver later.

Ok, will have a look as soon as there is more time. I assumed this must be a basic feature which should not be such a big effort to configure. Anyways, mailservers have always been tricky for me. One of the most complicated protocols out there. (And one of the oldest ;) )

**Comment by mindrunner** [comment]
Ha, by accident I think I figured out what is going on. Need to track it down further though.
Last weeks, I was running mailserver w/o ClamAV, Spamassasin, Postgrey
---> No mail doubling

Yesterday, I turned them on all at the same time. Since then, I have the double mails again. Will test now which one is the problem and report back. Turning off ClamAV first...

**Comment by mindrunner** [comment]
Maybe related:
Spamassasin marks one of the duplicate as SPAM

![image](https://user-images.githubusercontent.com/1413542/73586461-77374b00-447b-11ea-983a-c3b43019b147.png)

**Comment by mindrunner** [comment]
Alright, I think I tracked it down. Spamassasin is the problem here. Emails arrive twice, as soon as i turn it on. Once with the Spamassasin headers, once without.

But, it does not happen so all mails. So still confused about this.

@erik-wramner any thoughts? How can we debug this and/or figure out whats going on. I think, this behaviour is not how it is supposed to be, right?

**Comment by erik-wramner** [comment]
You could try to increase logging a lot and follow a message through the system, perhaps?

**Comment by mindrunner** [comment]
Ha, should read docs first...

`DMS_DEBUG=1`, right?

**Comment by mindrunner** [comment]
I don't get it, sorry:

This is one of the duplicated messages when spamassasin is activated:
![image](https://user-images.githubusercontent.com/1413542/74155359-77a1b580-4be2-11ea-87bc-0ee4b893db1e.png)

This is my log within that time window.
```
"@timestamp",message
"Feb 10, 2020 @ 12:50:32.866","6D3BF61B9C: removed"
"Feb 10, 2020 @ 12:50:32.865","6D3BF61B9C: to=<me@gmail.com>, relay=gmail-smtp-in.l.google.com[173.194.76.27]:25, delay=1.4, delays=0.22/0.01/0.16/1, dsn=2.0.0, status=sent (250 2.0.0 OK  1581339032 w7si130546wmk.19 - gsmtp)"
"Feb 10, 2020 @ 12:50:32.847","A3D3761BB1: removed"
"Feb 10, 2020 @ 12:50:32.847","A3D3761BB1: to=<me@gmail.com>, orig_to=<mail@domain.com>, relay=gmail-smtp-in.l.google.com[173.194.76.27]:25, delay=1.2, delays=0.16/0.01/0.15/0.86, dsn=2.0.0, status=sent (250 2.0.0 OK  1581339032 o2si150723wru.286 - gsmtp)"
"Feb 10, 2020 @ 12:50:32.472","A3D3761BB1: to=<mail@domain.com>, relay=mx0.domain.com[/var/run/dovecot/lmtp], delay=0.8, delays=0.16/0.01/0.01/0.62, dsn=2.0.0, status=sent (250 2.0.0 <mail@domain.com> jFBrMpdRQV4vEAAApw0tgQ Saved)"
"Feb 10, 2020 @ 12:50:31.841","B857A60736: removed"
"Feb 10, 2020 @ 12:50:31.840","B857A60736: to=<mail@domain.com>, orig_to=<cron@domain.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=9.2, delays=1.7/0.01/0.01/7.5, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 6D3BF61B9C)"
"Feb 10, 2020 @ 12:50:31.840","B857A60736: to=<me@gmail.com>, orig_to=<cron@domain.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=9.2, delays=1.7/0.01/0.01/7.5, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 6D3BF61B9C)"
"Feb 10, 2020 @ 12:50:31.830","A3D3761BB1: from=<root@domain.com>, size=553719, nrcpt=2 (queue active)"
"Feb 10, 2020 @ 12:50:31.703","A3D3761BB1: message-id=<20200210125031.A3D3761BB1@mx0.domain.com>"
"Feb 10, 2020 @ 12:50:31.702","A3D3761BB1: client=localhost[127.0.0.1]"
"Feb 10, 2020 @ 12:50:31.669","6D3BF61B9C: from=<root@domain.com>, size=553425, nrcpt=1 (queue active)"
"Feb 10, 2020 @ 12:50:31.451","6D3BF61B9C: message-id=<20200210125031.6D3BF61B9C@mx0.domain.com>"
"Feb 10, 2020 @ 12:50:31.448","6D3BF61B9C: client=localhost[127.0.0.1]"
"Feb 10, 2020 @ 12:50:24.316","B857A60736: from=<root@domain.com>, size=551886, nrcpt=2 (queue active)"
"Feb 10, 2020 @ 12:50:24.037","B857A60736: can't parse From: header value ' Anacron <root>'"
"Feb 10, 2020 @ 12:50:23.105","B857A60736: message-id=<>"
```

Its totally unclear for me what is going on there. :(

**Comment by erik-wramner** [comment]
Me neither except that we always tend to run into issues with the accounts that use to be local (root, cron etc). Do you have specific aliases for cron@domain.com and root@domain.com?

**Comment by mindrunner** [comment]
> Me neither except that we always tend to run into issues with the accounts that use to be local (root, cron etc). 

Oh wow, that's new information for me. I do not use specifig aliases for those addresses. Will try that out!

**Comment by mindrunner** [comment]
I created `cron@...` and `root@...` for all of the domains as aliases. Does not change anything. However, I think the issue is somewhere else. It actually only happens on one domain, the main domain (`DOMAINNAME`), also on non-system-aliases. The others are without any duplicates.

**Comment by VanVan** [comment]
I had the same problem.
With my previous installation, it was simple, I added a .forward file in the user folder, and everything worked perfectly.
With this version, the easiest way is to create an email account with an unused address "notused@site.com" and add an alias "realaddress@site.com notused@site.com, external@external.com", and do the same for each alias.

But a solution should be proposed natively, as it's something very common installation, this is just a workaround.

**Comment by mindrunner** [comment]
@VanVan did you read the whole thread? Why do you think your issue is related to spamassasin?

**Comment by VanVan** [comment]
I did some quick reading.
However, with my solution, on the same domain, and spamassassassin enabled, everything works without duplicates, whereas I had the same problem of duplicates when my configuration was similar to your first message @mindrunner .

**Comment by mindrunner** [comment]
Thanks for clarification @VanVan 

> With this version, the easiest way is to create an email account with an unused address "notused@site.com" and add an alias "realaddress@site.com notused@site.com, external@external.com", and do the same for each alias.

I think I already tried this, but I am not sure. Might get back into this at some point, but not using spamassasin, thus having it disabled and therefore no problems at the moment ;)

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
