### ISSUE TITLE
Debian buster warns iptables-legacy tables present

### ISSUE THREAD

**Issue by erik-wramner** [tomav/docker-mailserver#1356]
When building the next version for Debian Buster the fail2ban tests warn about legacy IP tables, as Debian has switched from iptables to nftables (https://wiki.debian.org/iptables). Not sure what we should do with this as the right solution may depend on what is running on the host.

* We can just ignore the warning in the tests (filter with grep) and hope that it works.
* We can use `update-alternatives` in the container to select iptables, which should get rid of the warning and work well with hosts that are running iptables. Not sure what will happen if the host runs nftables though.
* We can add a new configuration option that selects the proper implementation and allow end users to select the implementation (which is passed to `update-alternatives`). Then we can support hosts with iptables and hosts with nftables, but we add a new configuration option that people need to understand.
* We can possibly try to figure out what the host is running and use the same implementation. Not sure how easy that is, but perhaps the presence of legacy rules could be enough?

Suggestions welcome! See https://github.com/docker/libnetwork/pull/2285 and https://github.com/docker/libnetwork/issues/2331. Note that this should only affect fail2ban, I don't think we use iptables for anything else.

**Comment by gmasse** [comment]
It seems very surprising there is no Docker suggested way to handle this...

To keep compatibility with host, I would continue to use iptables in the container at least until a majority of distribution move to nftables. We should document this point as a requirement for the HOST.

Also, converting iptables rules to nftables is doable with `iptables-translate`. My opinion is Docker should manage this transparently (in a future release?), and we should not try to do it inside the container (your last proposal).

As a conclusion and to be sure everything will work as expected, I would go with the `update-alternatives` way.

**Comment by erik-wramner** [comment]
I've implemented the `update-alternatives` approach for now, but it feels messy.
