### ISSUE TITLE
Missing decoders in buster

### ISSUE THREAD

**Issue by erik-wramner** [tomav/docker-mailserver#1358]
When building for debian buster I can't find the zoo or ripole packages anywhere, so amavis complains that it lacks support for .F (might be an old warning), .doc and .zoo files:
```
Jan  6 12:20:02 mail amavis[176]: No ext program for   .zoo, tried: zoo
Jan  6 12:20:02 mail amavis[176]: No ext program for   .doc, tried: ripole
Jan  6 12:20:02 mail amavis[176]: No decoder for       .F   
Jan  6 12:20:02 mail amavis[176]: No decoder for       .doc 
Jan  6 12:20:02 mail amavis[176]: No decoder for       .zoo 
```
Zoo might be old enough that we can scrap it, but it would be nice to handle doc files. Suggestions welcome.

**Comment by erik-wramner** [comment]
I'll just update the test to ignore zoo and doc. Too bad.

**Comment by casperklein** [comment]
Could adding the ``ripole`` .deb file from Stretch be an option?

**Comment by erik-wramner** [comment]
I don't think so. That would be asking for weird problems. It seems ripole has not been updated since 2016 and the old .doc format is getting less common (most people use .docx now), but I'm still surprised that there is no recommended replacement. This is not a docker-mailserver problem after all, it should affect many mail servers.

**Comment by ksaadDE** [comment]
> I don't think so. That would be asking for weird problems. It seems ripole has not been updated since 2016 and the old .doc format is getting less common (most people use .docx now), but I'm still surprised that there is no recommended replacement. This is not a docker-mailserver problem after all, it should affect many mail servers.

Having that issue with plain amavisd too.
I should inform you all, that the bad guys are still using .doc (even more than docx).
And the best information is: .docs having binary payloads, therefore it's hard to see if it's a "bad doc" or "good doc".
So your assumption is correct. 

We need to implement some fix for ripole. I'll ask around if someone would like to redevelop it. 

Greetz
