### ISSUE TITLE
_setup_postfix_override_configuration must be registered / called later

### ISSUE THREAD

**Issue by rroblik** [tomav/docker-mailserver#1360]
`_setup_postfix_override_configuration` must be registered as (near to) last function.

For example, later registered `_setup_postfix_relay_hosts` override our custom override [here](https://github.com/tomav/docker-mailserver/blob/53a344a056842d849e49258fe0d14a45587b33d0/target/start-mailserver.sh#L1134).

Thanks

**Comment by erik-wramner** [comment]
What version are you using? This bug has already been fixed (see https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh) and the fix should be present in master/latest and stable and v6.2.1. Please upgrade to one of those and you should be fine.

I'll close this, feel free to reopen or post a new issue with more details if you feel the problem remains in the latest release.
