### ISSUE TITLE
config ssl cert but not connect

### ISSUE THREAD

**Issue by github-amazingboy** [tomav/docker-mailserver#1369]
## Context
cannot connect with SSL, when i setup SSL.

## Actual Behavior
failed connection. when no ssl, it is ok.

## Steps to Reproduce
my docker-compose.yml

version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: email.amazingboy.cn
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    - "110:110"
    - "995:995"
    volumes:
    - ./etc/ssl:/tmp/ssl:ro
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    environment:
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/cert/public.crt
    - SSL_KEY_PATH=/tmp/ssl/private/private.key
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
"docker-compose.yml" 39L, 799C

the /tmp/ssl/cert/public.crt  it with cert chain, it had multi-domain and contain *.email.amazingboy.cn

-----BEGIN CERTIFICATE-----
MIIE0DCCBHegAwIBAgIQaEzBOjjE6sBYYkETc9rLYDAKBggqhkjOPQQDAjCBjzEL
MAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE
BxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5T
ZWN0aWdvIEVDQyBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMB4X
DTIwMDExNDAwMDAwMFoXDTIyMDExMzIzNTk1OVowGDEWMBQGA1UEAxMNYW1hemlu
Z2JveS5jbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKAP7vjym1SGg1dov3wY
x1WqY7aPmufEvzMgM5gax6MA5+SgeTJJ4BSWalS1RLqWV93QM9M142bny035t7Ms
pBijggMpMIIDJTAfBgNVHSMEGDAWgBT2hQo7EYbhBH0Oqgss0u7MZHt7rjAdBgNV
HQ4EFgQUGnccZj+MpLkFuKUSL8maBdWbEG4wDgYDVR0PAQH/BAQDAgeAMAwGA1Ud
EwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEkGA1UdIARC
MEAwNAYLKwYBBAGyMQECAgcwJTAjBggrBgEFBQcCARYXaHR0cHM6Ly9zZWN0aWdv
LmNvbS9DUFMwCAYGZ4EMAQIBMIGEBggrBgEFBQcBAQR4MHYwTwYIKwYBBQUHMAKG
Q2h0dHA6Ly9jcnQuc2VjdGlnby5jb20vU2VjdGlnb0VDQ0RvbWFpblZhbGlkYXRp
b25TZWN1cmVTZXJ2ZXJDQS5jcnQwIwYIKwYBBQUHMAGGF2h0dHA6Ly9vY3NwLnNl
Y3RpZ28uY29tMFMGA1UdEQRMMEqCDWFtYXppbmdib3kuY26CDyouYW1hemluZ2Jv
eS5jboIVKi5lbWFpbC5hbWF6aW5nYm95LmNughF3d3cuYW1hemluZ2JveS5jbjCC
AX0GCisGAQQB1nkCBAIEggFtBIIBaQFnAHUARqVV63X6kSAwtaKJafTzfREsQXS+
/Um4havy/HD+bUcAAAFvoqSpIwAABAMARjBEAiBdv35PeisOWX4P4eXtWvISUL6b
tF/I33uZC800L8uTYgIgWRoz40iEr8wuCfr0ZcnsG3//fT+cx+Vr2g3nGVePWWUA
dwBvU3asMfAxGdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAW+ipKkIAAAEAwBI
MEYCIQDdr+XgSyrNTz/5MKwEZ9X1tCMZ7xVgsz4EjFqDJvPVHAIhAJEKgjz7U3ij
9QO/LKBqkro8OknXPzlLdMJYNrUfnXCNAHUAIkVFB1lVJFaWP6Ev8fdthuAjJmOt
wEt/XcaDXG7iDwIAAAFvoqSpCwAABAMARjBEAiB3jmfxEOJAtkrCYJ6e42oacAk7
lQVnnSrVYIo/wuzrngIgN//AU5A878ALLNfvbsIDS4YWe/fnN776Fw67W23JOJww
CgYIKoZIzj0EAwIDRwAwRAIgIe/1wxovwwaSk1c0iYS83osF8HM8g8BCUBYkJdMw
PtQCIHtspLgZypzMadLRjLwNzPNVPKoslj7gjHWoXvfatsn4
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDqDCCAy6gAwIBAgIRAPNkTmtuAFAjfglGvXvh9R0wCgYIKoZIzj0EAwMwgYgx
CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5MRQwEgYDVQQHEwtKZXJz
ZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBOZXR3b3JrMS4wLAYDVQQD
EyVVU0VSVHJ1c3QgRUNDIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE4MTEw
MjAwMDAwMFoXDTMwMTIzMTIzNTk1OVowgY8xCzAJBgNVBAYTAkdCMRswGQYDVQQI
ExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAOBgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoT
D1NlY3RpZ28gTGltaXRlZDE3MDUGA1UEAxMuU2VjdGlnbyBFQ0MgRG9tYWluIFZh
bGlkYXRpb24gU2VjdXJlIFNlcnZlciBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEH
A0IABHkYk8qfbZ5sVwAjBTcLXw9YWsTef1Wj6R7W2SUKiKAgSh16TwUwimNJE4xk
IQeV/To14UrOkPAY9z2vaKb71EijggFuMIIBajAfBgNVHSMEGDAWgBQ64QmG1M8Z
wpZ2dEl23OA1xmNjmjAdBgNVHQ4EFgQU9oUKOxGG4QR9DqoLLNLuzGR7e64wDgYD
VR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0lBBYwFAYIKwYB
BQUHAwEGCCsGAQUFBwMCMBsGA1UdIAQUMBIwBgYEVR0gADAIBgZngQwBAgEwUAYD
VR0fBEkwRzBFoEOgQYY/aHR0cDovL2NybC51c2VydHJ1c3QuY29tL1VTRVJUcnVz
dEVDQ0NlcnRpZmljYXRpb25BdXRob3JpdHkuY3JsMHYGCCsGAQUFBwEBBGowaDA/
BggrBgEFBQcwAoYzaHR0cDovL2NydC51c2VydHJ1c3QuY29tL1VTRVJUcnVzdEVD
Q0FkZFRydXN0Q0EuY3J0MCUGCCsGAQUFBzABhhlodHRwOi8vb2NzcC51c2VydHJ1
c3QuY29tMAoGCCqGSM49BAMDA2gAMGUCMEvnx3FcsVwJbZpCYF9z6fDWJtS1UVRs
cS0chWBNKPFNpvDKdrdKRe+oAkr2jU+ubgIxAODheSr2XhcA7oz9HmedGdMhlrd9
4ToKFbZl+/OnFFzqnvOhcjHvClECEQcKmc8fmA==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIID0zCCArugAwIBAgIQdti3htHzUk/ulT5xQD2Z1TANBgkqhkiG9w0BAQwFADBv
MQswCQYDVQQGEwJTRTEUMBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFk
ZFRydXN0IEV4dGVybmFsIFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBF
eHRlcm5hbCBDQSBSb290MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFow
gYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5MRQwEgYDVQQHEwtK
ZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBOZXR3b3JrMS4wLAYD
VQQDEyVVU0VSVHJ1c3QgRUNDIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MHYwEAYH
KoZIzj0CAQYFK4EEACIDYgAEGqxUWqn5aCPnetUkb1PGWthLq8bVttHmc3Gu3ZzW
DGH926CJA7gFFOxXzu5dP+Ihs8731Ip54KODfi2X0GHE8ZncJZFjq38wo7Rw4seh
M5zzvy5cU7Ffs30yf4o043l5o4H+MIH7MB8GA1UdIwQYMBaAFK29mHo0tCb3+sQm
VO8DveAky1QaMB0GA1UdDgQWBBQ64QmG1M8ZwpZ2dEl23OA1xmNjmjAOBgNVHQ8B
Af8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zARBgNVHSAECjAIMAYGBFUdIAAwSQYD
VR0fBEIwQDA+oDygOoY4aHR0cDovL2NybC50cnVzdC1wcm92aWRlci5jb20vQWRk
VHJ1c3RFeHRlcm5hbENBUm9vdC5jcmwwOgYIKwYBBQUHAQEELjAsMCoGCCsGAQUF
BzABhh5odHRwOi8vb2NzcC50cnVzdC1wcm92aWRlci5jb20wDQYJKoZIhvcNAQEM
BQADggEBAKj1xNg9sDYxKidBNj/c2oTeyXGoRdTM+xCKNcL3m1G5ktwPZGN4cM1s
qkBE0mDacVnFEn+KSqBx+9II6+KLhPZd87pZdLb/A7JAHWgQ3ieoQO5EUcukkhj9
AHm7yElINgE1tsVm9Auv8qUxSPe2VwphjJEaGnQBsx0TJClWWKrKJ6MHK9b7xe8/
osHjU27kzB8SYrWHFMPDLF34dvYXAFR6sltJm3oFeVZeF4nXZ0Sd0RlWG6WJ+kAl
9P1PtVAq+enXgE2DzoHYTJa226pzaOYkzZRWGc+UyMLj2LhL3YyUU7g1ZKTn+l6P
Hqrg0St8Cf0U1SdbQ1S3JS9OpBv1JWM=
-----END CERTIFICATE-----

**Comment by erik-wramner** [comment]
What error do you get specifically? And for what port? Can you post the logs, please?

**Comment by theoneandonly-vector** [comment]
hey there
I got the same problem when using a manual SSL-cert

this is the "error" I get when checking with: https://www.checktls.com/TestReceiver

```
<<< TLS 1.3, Alert [length 0002], fatal handshake_failure
    02 28
SSL3 alert read:fatal:handshake failure
SSL_connect:error in error
140651941197632:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1528:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 257 bytes and written 353 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```


I only see the following in :setup.sh debug show-mail-logs
```
Feb 14 18:47:40 mail postfix/postscreen[1748]: PASS OLD [159.89.187.50]:51960
Feb 14 18:47:40 mail postfix/smtpd[1749]: connect from www6.checktls.com[159.89.187.50]
Feb 14 18:47:40 mail postfix/smtpd[1749]: SSL_accept error from www6.checktls.com[159.89.187.50]: -1
Feb 14 18:47:40 mail postfix/smtpd[1749]: warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:1419:
Feb 14 18:47:40 mail postfix/smtpd[1749]: lost connection after STARTTLS from www6.checktls.com[159.89.187.50]
Feb 14 18:47:40 mail postfix/smtpd[1749]: disconnect from www6.checktls.com[159.89.187.50] ehlo=1 starttls=0/1 commands=1/2
```

Is there a log-file related to the ssl-setup?

**Comment by erik-wramner** [comment]
@theoneandonly-vector I would prefer if you could create your own issue. This is not about a bug in docker-mailserver but about your specific configuration and your problem does not have to be the same as the one in this issue. In fact I'd like to close this as there has been no updates from the original poster for 29 days.

Having said that `warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher` sounds as if the client and server can't find common ground on supported ciphers. You could check https://www.feistyduck.com/library/openssl-cookbook/online/ch-testing-with-openssl.html for how to test with the openssl command, that may make it easier for others to understand exactly what you are doing and reproduce the tests.
