### ISSUE TITLE
Dovecot not disconnecting lost session / not reconnecting

### ISSUE THREAD

**Issue by zemiret** [tomav/docker-mailserver#1370]
As a client on my android phone, I want to use **K9**. However, I'm having a problem with it. When I disconnect the device from the network, the account is not disconnected from the dovecot server (or, put the other way, when I connect anew, the account is not reconnected, but a new connection is initiated). I have default setting of max 10 users using the same account, connecting from the same ip. So, after a few "refreshes" of my inbox in K9, I'd get error from the server, because there are too many connected accounts using the same ip.

My setup is dead simple, mostly using defaults, with one account and one alias to it. I'd be grateful if someone could point me in the direction of where I should search for the problem, or why does this happen?

I acknowledge, that it might be actually a problem with K9, as with thunderbird, the session is closed properly.

## Context

I have only 2 devices connected to the server - my notebook and my phone. Logging into the container, and executing `doveadm who`, I can see something like this:
```
username            # proto (pids)             (ips)
user@mailserver.com  14 imap  (17100 18074 17101 18075 17102 17103 20131 17104 17105 17106 6800 15800 20126 18076) (150.214.58.70 150.214.58.94)
```

## Expected Behavior

I would expect dovecot to reconnect to the lost connection or close the session properly.

## Actual Behavior

I think the session in dovecot is lost when the device disconnects.

## Your Environment

* **Docker version** 19.03.5, build 633a0ea838
* **image**: tvial/docker-mailserver:latest
* **K9** mail client on mobile
* **thunderbird** on notebook

An excerpt from the log illustrating the outcome:
```
Jan 14 10:56:47 mail dovecot: imap-login: Login: user=<user@mail.com>, method=PLAIN, rip=150.214.58.94, lip=172.20.0.2, mpid=20126, TLS, session=<6gLOchecYtSW1jpe>
Jan 14 10:56:48 mail dovecot: imap-login: Login: user=<user@mail.com>, method=PLAIN, rip=150.214.58.94, lip=172.20.0.2, mpid=20131, TLS, session=<NOfcchecZNSW1jpe>
Jan 14 10:56:59 mail dovecot: imap-login: Login: user=<reports@mail.com>, method=PLAIN, rip=150.214.58.94, lip=172.20.0.2, mpid=20167, TLS, session=<Ned6cxeccNSW1jpe>
Jan 14 10:58:01 mail dovecot: imap-login: Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10): user=<user@mail.com>, method=PLAIN, rip=150.214.58.70, lip=172.20.0.2, TLS, session=<5gUtdxecGsiW1jpG>
Jan 14 10:58:01 mail dovecot: imap-login: Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10): user=<user@mail.com>, method=PLAIN, rip=150.214.58.70, lip=172.20.0.2, TLS, session=<f0IvdxecG8iW1jpG>
Jan 14 10:58:01 mail dovecot: imap-login: Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10): user=<user@mail.com>, method=PLAIN, rip=150.214.58.70, lip=172.20.0.2, TLS, session=<80kvdxecHMiW1jpG>
```

**Comment by erik-wramner** [comment]
I think this is more a problem with the network than with the applications. If you disconnect the network for a PC running Thunderbird and then connect it again you will most likely get a new connection, just like you get with K9. It may work if you reconnect quickly so that the TCP stack can recover, but when the application (or OS) has had time to detect that the connection is broken it cannot reconnect. On the server side the connection remains open until it times out (read about half open sockets). You may be able to adjust the timeout so that the half-open connections are identified and closed faster, otherwise I think you need to increase your user limit.

Perhaps someone else has a better suggestion. I'm personally using K9 and it works quite well, but perhaps my phone loses its network connection less often.

**Comment by zemiret** [comment]
In case someone ever gets here: I ended up setting higher user+ip limit, because it turns out that imap is creating a new connection for each folder. So, if you have more than 5 folders on 2 devices, you're done. If you disconnect and reconnect, you're done, etc.
