### ISSUE TITLE
Incorrect permissions for sieve-pipe scripts

### ISSUE THREAD

**Issue by tweibert** [tomav/docker-mailserver#1376]
I'm using a sieve-pipe script to pipe incoming mail into an osTicket instance (osticket_automail.pl). As per the documentation, the script is placed into `config/sieve-pipe`, from where it gets copied over to `/usr/lib/dovecot/sieve-pipe` in the running container.

In the `_setup_dovecot()` function in `start-mailserver.sh`, there are these two lines that "fix" the permissions on all sieve configuration:

	chown docker:docker -R /usr/lib/dovecot/sieve*
	chmod 550 -R /usr/lib/dovecot/sieve*

Unfortunately this removes the executable flag on the sieve-pipe script, and dovecot will no longer call it, giving an error like this:

> Jan 21 16:56:17 mail dovecot: lmtp(xxx@xxxxx.com)<26992><cEiLHSctJ15waQAA/p0Tyw>: Error: program exec:/usr/lib/dovecot/sieve-pipe/osticket_automail.pl (28697): Forcibly terminated with signal 15

My workaround is to fix the permissions in `user-patches.sh`:

    chmod +x /usr/lib/dovecot/sieve-pipe/*

I think the issue can be easily solved by adding this line into `start-mailserver.sh` as well.

**Comment by tweibert** [comment]
Added PR with my suggested solution.

**Comment by DuncanvR** [comment]
@tweibert, since your PR has been merged, can this issue be closed?

**Comment by tweibert** [comment]
Oh yes, sure. Thank you.
