### ISSUE TITLE
master.cf customization fails

### ISSUE THREAD

**Issue by cdwertmann** [tomav/docker-mailserver#1378]
I want to use a Postfix content filter. To do that, I need to have the following config in my master.cf:

```
scan      unix  -       -       n       -       10      smtp
      -o smtp_send_xforward_command=yes
      -o disable_mime_output_conversion=yes

0.0.0.0:10026 inet  n       -       n       -       10      smtpd
      -o content_filter=
      -o receive_override_options=no_unknown_recipient_checks,no_header_body_checks,no_milters
      -o smtpd_authorized_xforward_hosts=127.0.0.0/8
```

Converting this into single-line format and adding these lines to `config/postfix-master.cf` fails. Each line in that file is added to postfix with `postconf -P` in this code:

https://github.com/tomav/docker-mailserver/blob/f6f5a28bec88d8bf44f84ece5e8e50eb79ae5485/target/start-mailserver.sh#L1168

However according to http://www.postfix.org/postconf.1.html , `-P` is only used to add service parameters. For service entries, `-M` is needed. Running the following commands inside the container works:

```
postconf -M scan/unix="scan      unix  -       -       n       -       10      smtp"
postconf -P scan/unix/smtp_send_xforward_command=yes
postconf -P scan/unix/disable_mime_output_conversion=yes
postconf -M 0.0.0.0:10026/inet="0.0.0.0:10026 inet  n       -       n       -       10      smtpd"
postconf -P 0.0.0.0:10026/inet/content_filter=
postconf -P 0.0.0.0:10026/inet/receive_override_options=no_unknown_recipient_checks,no_header_body_checks,no_milters
postconf -P 0.0.0.0:10026/inet/smtpd_authorized_xforward_hosts=127.0.0.0/8
```
However this does not survive a recreation of the container. The code needs to distinguish between entries, fields and parameters and use M, F and P respectively.

**Comment by erik-wramner** [comment]
It is not clear to me how we should detect the proper command to run, so I would suggest putting your changes in `config/user-patches.sh`. Then you can run the postconf commands yourself. It will run every time the container starts.

**Comment by cdwertmann** [comment]
@erik-wramner the workaround you suggested work well, thank you.
I thought it might be possible to write a regex that can distinguish entries, fields and parameters. Assuming that all a user would want to customise in `master.cf` is service parameters and therefore hardcoding `-P` is not ideal.

**Comment by erik-wramner** [comment]
If there is a sure-fire way to identify what goes where you could give it a try, but it feels dangerous. A slight mistake in the regexp and it could break existing installations. Another and safer approach would be to have three files, one for entries and one for fields and one for parameters. Then we know what goes where and there is no risk for breaking existing code. If you want to make a PR for that please note that the code is (sadly) duplicated in the start script and in the change detection script.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
