### ISSUE TITLE
using mda option in fetchmail?

### ISSUE THREAD

**Issue by remoe** [tomav/docker-mailserver#1381]
I try to send mails to a specific folder with following 'mda' entry in 'fetchmailrc':

```
...
mda '/usr/lib/dovecot/deliver -d %T -m test'
```

This can't work with current environment, because fetchmail run as fetchmail-user:

```
dovecot: auth: Error: client doesn't have lookup permissions for this user: userdb uid (5000) doesn't match peer uid (108) (to bypass this check, set: service auth { unix_listener /var/run/dovecot/auth-userdb { mode=0777 } })
```

but changing the config to:

```
    service auth {
      unix_listener auth-userdb {
        mode = 0777
        user = docker
        group = docker
      }
```

doesn't help:

```
 Fatal: setgid(5000(docker) from userdb lookup) failed with euid=108(fetchmail), gid=65534(nogroup), egid=65534(nogroup): Operation not permitted (This binary should probably be called with process group set to 5000(docker) instead of 65534(nogroup))
```

Does anyone know how to solve this? Thanks!

**Comment by erik-wramner** [comment]
Not sure about the best way for fixing it unless you want to build your own image, but the problem is probably in `target/supervisor/conf.d/supervisor-app.conf`:

```
[program:fetchmail]
startsecs=0
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
user=fetchmail

```
If you remove the user=fetchmail part the process will probably run as root and should have permissions. Not sure if it will break something though. You could try to patch the supervisor configuration from `start-mailserver.sh`.

**Comment by remoe** [comment]
Thanks for your hint! I've tried it, but i still have this error. I've changed the ```/etc/supervisor/conf.d/supervisor-app.conf``` to:
```ini
...
[program:fetchmail]
startsecs=0
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log

command=/usr/bin/fetchmail -f /etc/fetchmailrc -v --nodetach --daemon %(ENV_FETCHMAIL_POLL)s -i /var/lib/fetchmail/.fetchmail-UIDL-cache --pidfile /var/run/fetchmail/fetchmail.pid
```

Error:

```
dovecot: auth: Error: client doesn't have lookup permissions for this user: userdb uid (5000) doesn't match peer uid (108) (to bypass this check, set: service auth { unix_listener /var/run/dovecot/auth-userdb { mode=0777 } })
```

I don't know from where 108 (fetchmail) comes ...

**Comment by erik-wramner** [comment]
Tricky. We are on a slippery slope relaxing permissions, so I'll flag this help wanted instead. Hopefully someone that is using fetchmail can answer. There should be nothing docker-mailserver specific about this, so a general search about fetchmail with dovecot could help.

**Comment by remoe** [comment]
ok, thanks.

**Comment by remoe** [comment]
I've found the following solution:

I run fetchmail as docker user. 

dovecot.cf:

```yaml
  dovecot.cf: |
    service stats {
      unix_listener stats-reader {
        group = docker
        mode = 0666
      }
      unix_listener stats-writer {
        group = docker
        mode = 0666
      }
    }
```

user-patches.sh

```yaml
  user-patches.sh: |
    #!/bin/bash
    /usr/bin/supervisorctl stop fetchmail
    chown docker:docker /var/lib/fetchmail
    chown docker:docker /var/run/fetchmail
    chmod 700 /var/lib/fetchmail
    sed -i 's/user=fetchmail/user=docker/' /etc/supervisor/conf.d/supervisor-app.conf
    sed -i 's/chown fetchmail:root \$RC/chown docker:docker \$RC/'  /usr/local/bin/setup-fetchmail
    /usr/bin/supervisorctl update fetchmail
    /usr/bin/supervisorctl start fetchmail
```

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by remoe** [comment]
This issue is not solved with current version.

**Comment by georglauterbach** [comment]
> This issue is not solved with current version.

Please open a new issue with the new issue template :)
