### ISSUE TITLE
start-mailserver.sh can't recognize public IP

### ISSUE THREAD

**Issue by fishersbear** [tomav/docker-mailserver#1382]
In fact, the problems I met has been solved by myself slowly. Here I want to report some bugs. Here is the environment:
- docker image is up to date
- Ubuntu 18.04 with network interface **enp3s0** and public IP (VPS)
- The mailserver container created with the option '--network=host'
- (I'm newbee)

---

#bug 1. The name of network interface might be **enp3s0** not **eth0**, start-mailserver.sh doesn't consider about it. While excuting /usr/local/bin/start-mailserver.sh,
 - var 'container_ip' is set to EMPTY, because eth0 doesn't exist
 - then var 'container_network' is set to /32, so the log keeps telling me '/32 not found'(Then the log says 'temporary lookup failure', then I can't send and receive mails )

#bug 2. Even if the container_ip is a public ip, the start-mailserver.sh script takes it a local ip. So the var 'container_network' might be set to 1.2.0.0/32, (expecting 1.2.3.4/32)

---

#advice 3. the default definition of fail2ban's ignoreip only include localhost (getting my nextcloud's ip banned). I thnk it could include other local ips. PERMIT_DOCKER can also be used to define it?

**Comment by erik-wramner** [comment]
Thanks for reporting. The first one is known, it is #1227 and occurs when you are using host networking on a host that does not use the ethx naming scheme. If possible I would stay clear of host networking, but if you are stuck with it `PERMIT_DOCKER=network` might help.

Not sure about the second one, but again exposing the container with a public IP might not be a good idea from a security perspective. Solving #1227 should hopefully fix the container network.

Also not sure about the details for fail2ban, but I think you can override the default setting in `config/fail2ban-jail.cf` and define your own value for `ignoreip`. Failing that you can always use `config/user-patches.sh` to find and replace the default with your value.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
