### ISSUE TITLE
Sendmail Analyzer

### ISSUE THREAD

**Issue by mindrunner** [tomav/docker-mailserver#1385]
I am thinking of integrating this into docker-mailserver. Would that be merged to upstream?

https://github.com/darold/sendmailanalyzer

**Comment by erik-wramner** [comment]
Depends, definitely not with a web server, possibly as a scheduled report if it is available in the Debian repository. However, wouldn't it be better to run it from a separate docker image that shares the log folder as a mounted volume? Then you can have a web server running if you like and both can be started from the same compose file. As far as I can tell it only needs access to the logs, so a mounted volume should work quite well?

**Comment by mindrunner** [comment]
Yeah, that totally makes sense. I am working on two different monitoring strategies at the moment.

- Grafana with ELK and prometheus / blackbox_exporter
- sendmailanalyzer

The first one is pretty much running out of the box. I saw, you already have an ELK Dockerfile integrated. I am using my own based on the official images in favor of the `sebp` one. 
Using this Grafana Dashboard: https://grafana.com/grafana/dashboards/11293
In action:
![image](https://user-images.githubusercontent.com/1413542/73561492-1a11aa00-4427-11ea-8124-3f3059288b98.png)

Second one is working as well (sort of). I built a docker image with sendmailanalyzer and a webserver, to serve the statistics. Will ask over there to get the docker-code upstream and create an official image.

![image](https://user-images.githubusercontent.com/1413542/73561750-93110180-4427-11ea-854a-472b06b1bf60.png)


Probably needs some more work, because I need some sort of hook after log rotation to restart a process. Not sure yet, how to solve that.

I do not see where we can do some integration here (except documentation/tutorials), because it is not really related to docker-mailserver, but rather to postfix in general.

Any thoughts?

**Comment by erik-wramner** [comment]
You should be able to notice a log rotation by checking the files, perhaps? Something similar to the check for changes script but external that sees if the files change? If the main log file is smaller than it was the last iteration it must have been rotated. Or if there is a rotated file that is new (use find command with modification time and pattern).

**Comment by mindrunner** [comment]
Sounds like good ideas. Since this has no urgency for me at the moment, this month is pretty stuffed and also https://github.com/darold/sendmailanalyzer/issues/72 did not create any interest, I will put that on my backlog for now...

**Comment by Kiina** [comment]
> * Grafana with ELK and prometheus / blackbox_exporter

Do you happen to have a docker-compose file for that config that you could share?

**Comment by mindrunner** [comment]
Have a look at this:
https://github.com/deviantony/docker-elk

**Comment by aendeavor** [comment]
This is another good idea of yours @mindrunner. Feel free to re-open this if you feel like there is more to this issue. I will close this due to age and lack of activity. Good luck tough!
