### ISSUE TITLE
Can't send mails from clients like Thunderbird 

### ISSUE THREAD

**Issue by wernerfred** [tomav/docker-mailserver#1390]
I had a mailserver running for like a year without any issue. Recently i moved the project from one host to another (copied the whole configuration and mail files). After the DNS was updated everything worked like expected on the new host. Except one thing:
I can't send Mails from a client using a tool like Thunderbird

Every time when i write and send an email within thunderbird i immediately receive an email like this:

```
A message from <myuser@mydomain.de>
to: otheruser@otherdomain.de

was considered unsolicited bulk e-mail (UBE).

Our internal reference code for your message is 04499-12/ZLlB5XaNH1eJ

The message carried your return address, so it was either a genuine mail
from you, or a sender address was faked and your e-mail address abused
by third party, in which case we apologize for undesired notification.

We do try to minimize backscatter for more prominent cases of UBE and
for infected mail, but for less obvious cases some balance between
losing genuine mail and sending undesired backscatter is sought,
and there can be some collateral damage on either side.

First upstream SMTP client IP address: [XXX.211.186.169]
  p4fd3bxx9.dip0.t-ipconnect.de
According to a 'Received:' trace, the message apparently originated at:
  [XXX.211.186.169], 

Return-Path: <myuser@mydomain.de
From: Frederic  <myuser@mydomain.de>
Message-ID: <d0b7c2e9-36c5-b391-234b-1c940892ac32@mydomain.de>
Subject: Test

Delivery of the email was stopped!
```
Where ```IP address: [XXX.211.186.169]``` was the IP i got assigned that day from my ISP (Telekom) I put that IP in a blacklist checker and it was listed in some of the lists.

Everything else works like expected. I can receive mails like as previously. And all the filters and rules work like a charm.

I noticed a strange behavior that i can't completely explain why:
I am able to send mails if i am using a webmailer or my phone to send the mails. Only when sending Mails from a local Mail Client (Thunderbird/Outlook) it fails with the message above.

## Context
Here is the corresponding log output when i try to send a mail from a local mail client:
```
mail    | Feb  7 21:50:19 mail postfix/submission/smtpd[28737]: F2B847D53E: client=p4fd3bxx9.dip0.t-ipconnect.de[XXX.211.186.169], sasl_method=PLAIN, sasl_username=myuser@mydomain.de
mail    | Feb  7 21:50:20 mail postfix/sender-cleanup/cleanup[28741]: F2B847D53E: message-id=<d0b7c2e9-36c5-b391-234b-1c940892ac32@mydomain.de>
mail    | Feb  7 21:50:20 mail postfix/sender-cleanup/cleanup[28741]: F2B847D53E: replace: header MIME-Version: 1.0 from p4fd3bxx9.dip0.t-ipconnect.de[XXX.211.186.169]; from=<myuser@mydomain.de> to=<otheruser@otherdomain.de> proto=ESMTP helo=<[192.168.2.126]>: Mime-Version: 1.0
mail    | Feb  7 21:50:20 mail opendkim[287]: F2B847D53E: DKIM-Signature field added (s=mail, d=mydomain.de)
mail    | Feb  7 21:50:20 mail postfix/qmgr[1089]: F2B847D53E: from=<myuser@mydomain.de>, size=341, nrcpt=1 (queue active)
mail    | Feb  7 21:50:20 mail postfix/submission/smtpd[28737]: disconnect from p4fd3bxx9.dip0.t-ipconnect.de[XXX.211.186.169] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
mail    | Feb  7 21:50:20 mail dovecot: imap(myuser@mydomain.de)<27502><XtmYdgKeKdFP07qp>: Logged out in=1768 out=3094 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
mail    | Feb  7 21:50:20 mail postfix/smtpd[28752]: connect from localhost[127.0.0.1]
mail    | Feb  7 21:50:20 mail postfix/smtpd[28752]: DFFB37D9C7: client=localhost[127.0.0.1]
mail    | Feb  7 21:50:20 mail postfix/cleanup[28753]: DFFB37D9C7: message-id=<SSZLlB5XaNH1eJ@mail.mydomain.de>
mail    | Feb  7 21:50:20 mail postfix/qmgr[1089]: DFFB37D9C7: from=<>, size=3809, nrcpt=1 (queue active)
mail    | Feb  7 21:50:20 mail postfix/smtpd[28752]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
mail    | Feb  7 21:50:20 mail amavis[4499]: (04499-12) Blocked SPAM {BouncedOpenRelay,Quarantined}, [XXX.211.186.169]:53930 [XXX.211.186.169] <myuser@mydomain.de> -> <otheruser@otherdomain.de>, quarantine: Z/spam-ZLlB5XaNH1eJ.gz, Queue-ID: F2B847D53E, Message-ID: <d0b7c2e9-36c5-b391-234b-1c940892ac32@mydomain.de>, mail_id: ZLlB5XaNH1eJ, Hits: 7.358, size: 840, 798 ms
mail    | Feb  7 21:50:20 mail postfix/smtp[28743]: F2B847D53E: to=<otheruser@otherdomain.de>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.98, delays=0.16/0.02/0.01/0.79, dsn=2.5.0, status=sent (250 2.5.0 Ok, id=04499-12, BOUNCE)
mail    | Feb  7 21:50:20 mail postfix/qmgr[1089]: F2B847D53E: removed
```

Here is the log output when using my phone with the outlook app installed (phone using wlan from the same network the thunderbird client is located in). Keep an eye on the ```connect from unknown[XXX.125.138.24]```. So somehow the outlook app changes the IP address which in the end talks to my mailserver (because it is obviously not my dynamic assigned one like in the previous log output). Therefore the mail is accepted and delivered as the used IP is not listed anywhere:

```
mail    | Feb  8 22:34:40 mail postfix/submission/smtpd[17652]: connect from unknown[XXX.125.138.24]
mail    | Feb  8 22:34:40 mail postfix/submission/smtpd[17652]: Anonymous TLS connection established from unknown[XXX.125.138.24]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
mail    | Feb  8 22:34:40 mail postfix/submission/smtpd[17652]: DE0A27D9E5: client=unknown[XXX.125.138.24], sasl_method=LOGIN, sasl_username=myuser@mydomain.de
mail    | Feb  8 22:34:40 mail postfix/sender-cleanup/cleanup[17653]: DE0A27D9E5: message-id=<FD03986973B3CE68.5297f9c0-5fd1-4ba8-b0bf-fcc6a727f736x@mail.outlook.com>
mail    | Feb  8 22:34:40 mail postfix/sender-cleanup/cleanup[17653]: DE0A27D9E5: replace: header MIME-Version: 1.0 from unknown[XXX.125.138.24]; from=<myuser@mydomain.de> to=<otheruser@otherdomain.de> proto=ESMTP helo=<mail.outlook.com>: Mime-Version: 1.0
mail    | Feb  8 22:34:40 mail opendkim[287]: DE0A27D9E5: DKIM-Signature field added (s=mail, d=mydomain.de)
mail    | Feb  8 22:34:41 mail postfix/qmgr[1088]: DE0A27D9E5: from=<myuser@mydomain.de>, size=919, nrcpt=1 (queue active)
mail    | Feb  8 22:34:41 mail postfix/smtpd[17324]: connect from localhost[127.0.0.1]
mail    | Feb  8 22:34:41 mail postfix/smtpd[17324]: C30B47D9E6: client=localhost[127.0.0.1]
mail    | Feb  8 22:34:41 mail postfix/cleanup[17317]: C30B47D9E6: message-id=<FD03986973B3CE68.5297f9c0-5fd1-4ba8-b0bf-fcc6a727f736x@mail.outlook.com>
mail    | Feb  8 22:34:41 mail postfix/qmgr[1088]: C30B47D9E6: from=<myuser@mydomain.de>, size=1637, nrcpt=1 (queue active)
mail    | Feb  8 22:34:41 mail postfix/smtpd[17324]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
mail    | Feb  8 22:34:41 mail amavis[1089]: (01089-05) Passed CLEAN {RelayedOpenRelay}, [XXX.125.138.24]:58058 [XXX.125.138.24] <myuser@mydomain.de> -> <otheruser@otherdomain.de>, Queue-ID: DE0A27D9E5, Message-ID: <FD03986973B3CE68.5297f9c0-5fd1-4ba8-b0bf-fcc6a727f736x@mail.outlook.com>, mail_id: Y3l3071d2Plc, Hits: 2.923, size: 1417, queued_as: C30B47D9E6, 774 ms
mail    | Feb  8 22:34:41 mail postfix/smtp[17318]: DE0A27D9E5: to=<otheruser@otherdomain.de>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.95, delays=0.16/0/0.02/0.77, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as C30B47D9E6)
mail    | Feb  8 22:34:41 mail postfix/qmgr[1088]: DE0A27D9E5: removed
mail    | Feb  8 22:34:41 mail dovecot: imap-login: Login: user=<myuser@mydomain.de>, method=LOGIN, rip=XXX.125.138.24, lip=172.18.0.2, mpid=17661, TLS, session=<FWAkRhee/qU0fYoY>
mail    | Feb  8 22:34:42 mail dovecot: imap(myuser@mydomain.de)<16631><5CJeNheeRuk0fYoY>: Logged out in=1583 out=14968 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=395 body_count=1 body_bytes=213
mail    | Feb  8 22:34:49 mail postfix/smtp[17660]: connect to mail.otherdomain.de[IP6:4f8:d0a:6403::2]:25: Cannot assign requested address
mail    | Feb  8 22:34:52 mail postfix/smtp[17660]: Trusted TLS connection established to mail.otherdomain,de[IP4.44.218.17]:25: TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
mail    | Feb  8 22:34:59 mail postfix/smtp[17660]: C30B47D9E6: to=<otheruser@otherdomain.de>, relay=mail.otherdomain.de[IP4.44.218.17]:25, delay=18, delays=0/0.02/11/6.8, dsn=2.0.0, status=sent (250 OK id=1j0Xkf-0001Dj-If)
mail    | Feb  8 22:34:59 mail postfix/qmgr[1088]: C30B47D9E6: removed
mail    | Feb
```

So it seems like amavis blocks Mails which are sent from a client at home (from a dynamic IP) as SPAM and therefore i receive the mail above. This would explain why it works if i use a webmail tool to send mails because then its a static IP that is not reported or listed anywhere.

Can anyone help me to identify what the problem is and why all mails i want to send from a mail client are marked as SPAM and not delivered?

Did i miss something important? Is this the expected behavior? If I can understand why this happens i can continue finding a solution how to fix it for me.

## Expected Behavior
I should be able to send a mail regardless of the tool/client i use

## Actual Behavior
I can only send mails using a webmailer or my phone with mail app (outlook)

## Steps to Reproduce
1. Pull docker container and configure it like listed in my environment
2. Write an email from a local mail client that uses the dynamic ip from the ISP

##  Environment
* Amount of RAM available: 2GB
* Mailserver version used: 2.6.1 (stable)
* Docker version used: Docker version 19.03.4, build 9013bf583a
* Environment settings relevant to the config:
I have pretty every setting on the default value except for these:
```
ONEDIR=1
ENABLE_CLAMAV=0
ENABLE_MANAGESIEVE=1
```
Obviously i have also set the hostname variables etc.

Do you need any further information? Thanks in advance!

**Comment by erik-wramner** [comment]
You should probably try to get your IP off the spam list(s). Otherwise your messages are likely to get rejected by other servers. However, apart from that I wonder if you really need to send from the public IP? If your mail client uses the internal network inside the firewall instead you can mark that network as trusted and bypass the tests. Finally I think it should be possible to make authenticated messages bypass the tests (which would be ideal here), but I don't remember how to do it. Perhaps someone else can help?

**Comment by wernerfred** [comment]
I think you missunderstood something.

I tried to visualize it:
```
+--------------------+
| VPS in Cloud       |    Blocked SPAM {BouncedOpenRelay,Quarantined},
| Running mailserver +--->[XXX.211.186.169]:53930 [XXX.211.186.169]
| Static IP          |    <myuser@mydomain.de> -> <otheruser@otherdomain.de>
+----+---------------+
     ^
     |
     | F2B847D53E: client=p4fd3bxx9.dip0.t-ipconnect.de[XXX.211.186.169]
     |
     |
+----+-------------------------+
| Home PC                      |
| Thunderbird                  |
| Dynamic assigned IP from ISP |
+------------------------------+

```

So i guess this is the "normal" setup. One rents a VPS in the Cloud with a public static IP and runs its mailserver on it. 
So if i try to write an email from the PC at home with thunderbird, thunderbird connects to the mailserver which is seen in the logs (```p4fd3bxx9.dip0.t-ipconnect.de``` is the dynamic public ip my router got assigned that day). It is normal up to this point. But then amavis comes into play and blocks this mail as SPAM before it can be processed further.

> You should probably try to get your IP off the spam list(s)
Thats is nearly impossible as it is the dynamically assigned ip drom the ISP changing daily. Next to that it is the same condition as with every mail provider regardless of hosting by its own or not

> Otherwise your messages are likely to get rejected by other servers.
That is not true in my opinion, bc other mail servers see the ip of my mail server (which is clean) only my mailserver sees the clients dynamic ip and blocks it.

**Comment by erik-wramner** [comment]
Fair enough. What port are you connecting to? Could it be 25?

**Comment by wernerfred** [comment]
I configured the mailserver with certificates and Thunderbird with the STARTTLS option. So Thunderbird is using 587 for smtp and 143 for imap

**Comment by erik-wramner** [comment]
Right. You should not use 143 (plain text), but that is not the problem here. As you copied the configuration perhaps something is different from how it was? You could perhaps enable `DMS_DEBUG` and run the two tests again to get more verbose logs? It would also be interesting to see your other options. You can of course obfuscate sensitive ones.

**Comment by wernerfred** [comment]
So i should use 993 for IMAP and 465 for SMTP? (Thanks for the hint!)

I will set ```DMS_DEBUG=1``` and run the test again when i am back home and then provide the output here.

For the meantime here is the content of my ```docker-compose.yaml```:

```
# Ansible managed: File is managed by Ansible. Manual changes will be overwritten!
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:stable
    restart: always    
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "4190:4190"
    volumes:
      - ./data/maildata:/var/mail
      - ./data/mailstate:/var/mail-state
      - ./data/config:/tmp/docker-mailserver/
      - /etc/letsencrypt:/tmp/ssl:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SSL_CERT_PATH=/tmp/ssl/live/mail.****/fullchain.pem
      - SSL_KEY_PATH=/tmp/ssl/live/mail.****/privkey.pem
      - DMS_DEBUG=0
      - ENABLE_CLAMAV=0
      - ONE_DIR=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_MANAGESIEVE=1
      - POSTMASTER_ADDRESS=****@****
      - REPORT_RECIPIENT=1
      - REPORT_INTERVAL=daily
      - SSL_TYPE=manual
      - SPOOF_PROTECTION=1
      - POSTFIX_MAILBOX_SIZE_LIMIT=2147482548
      - POSTFIX_MESSAGE_SIZE_LIMIT=52428800
      - ENABLE_SPAMASSASSIN=1
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SA_KILL=6.31
      - SA_SPAM_SUBJECT=****SPAM****
      - ENABLE_POSTGREY=1
      - POSTGREY_DELAY=240
      - POSTGREY_MAX_AGE=35
      - POSTGREY_AUTO_WHITELIST_CLIENTS=2
      - POSTGREY_TEXT=Delayed by postgrey
    hostname: mail
    domainname: ****
    container_name: mail
    dns: 1.1.1.1
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

Thanks!

**Comment by wernerfred** [comment]
Sorry for late response. As mentioned above i migrated the project from one host to another. It seems like i copied some host specific configuration files (or my previous configuration just had issues i never faced before) that were causing the error.
I refactored the configuration (basically started from zero again) and cleaned out the old file.
Since then the issue disappeared and i was not able to reproduce it again.

Thanks for the help in the meantime. I will close the issue for now (hoping to never need to open it again).
