### ISSUE TITLE
Troubleshooting: what steps to take after changing env-mailserver file

### ISSUE THREAD

**Issue by hanscees** [tomav/docker-mailserver#1393]
## Context

This is a question. I am setting up a new mailserver and learning on the job. While troubleshooting I sometimes find that some variables are wrong, or I just want to enable different things. 

So my question is: if I have a working mailserver and want to shut down for instance spamassassin, or I want to enable it. What are the steps to take? 

Is it ok to:

1- adjust env-mailserver
2- do a docker-compose down (this will destroy the container but not the config files in docker volumes)
3- do a docker-compose up -d mail

Will the script you made then change the config correctly? Also if that config outlives the container? (which it doesnt if you follow your yml file)

Or alternatively:
1- Once you have a working mailserver, you should either 
-   adjust config files by hand if you store them in a docker volume and therefore they survive the destruction of the container 
- destroy all volumes with config. If you do that all changes in env-mailserver will be processed
  

I quess your script does not expect the main.cf to survive the destruction of a container?

**Comment by erik-wramner** [comment]
Please follow the first method and let the scripts generate the configuration based on the selected options AND the override files in your `config` directory. Configuration changes that are not supported by options can usually be supplied in the override files. If you want to do something even more exotic you can apply changes in `config/user-patches.sh`. It runs late during startup.

As for "correctly" I hope so, but there can certainly be corner cases where there are bugs and if you have added your own volumes that make files that are normally generated at startup persistent you are on shaky ground!

**Comment by hanscees** [comment]
OK, thats clear, thank you. 

you document override here:
https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration

Am I correct to assume I can use this to change existing lines, but not to add parameter to an existing line right?

**Comment by erik-wramner** [comment]
Well yes, you can overwrite an option, but as you need to specify the full option in the config file you can't add to the existing ones. You will overwrite them. If you need to patch you'll have to use `user-patches.sh` and play with `sed` and friends.
