### ISSUE TITLE
Support for two ssl certificates

### ISSUE THREAD

**Issue by sla100** [tomav/docker-mailserver#1395]
The current SSL configuration (e.g. by `SSL_CERT_PATH` and `SSL_KEY_PATH` varaibles) is a common for all services.

In my case, SMTP-MTA serice on port 25 using "uggly" hostaname provided by the ISP as `ip_fourth_octet.ip_third_octet.isp_name.com` which also has a correct PTR record.

My `pretty.example` domain name has MX records that point to an "ugly" domain address and A records with my IP.

The current configuration works fine, but the mail client using imaps/993 and smtps/465 must known this `ip_fourth_octet.ip_third_octet.isp_name.com` address.

I would prefer to have `mail.pretty.example`.

Could you expand the SSL configuration to support 2 certificates?

**Comment by erik-wramner** [comment]
Not that I know. Feel free to make a suggestion if you think it is possible.
