### ISSUE TITLE
Proper postgrey usage

### ISSUE THREAD

**Issue by mindrunner** [tomav/docker-mailserver#1398]
I see some issues here: 

- According to the manpage, we are supposed to use `https://postgrey.schweikert.ch/pub/postgrey_whitelist_clients` per default. I cannot find this anywhere in docker-mailserver.
Edit: found the files in `/etc/postgrey`, but according to https://linux.die.net/man/8/postgrey the default filepath is `/etc/postfix/postgrey_whitelist_clients` and I cannot see this being overridden anywhere in docker-mailserver.  

- Logging seems weird. See #1276 

- Why is there no `/var/spool/postfix/postgrey` database in my running container? I would like to persist it.

I would like to start a discussion about this here and then fix things up...

**Comment by wernerfred** [comment]
Hi,
for information have a look at the ```start-mailserver.sh``` script:
https://github.com/tomav/docker-mailserver/blob/7f3fe45a838715ea82bb449eb14b50ca6861c2b9/target/start-mailserver.sh#L761

You can add a ```whitelist_clients.local``` file to your config directory that is mounted into the container (See [Wiki](https://github.com/tomav/docker-mailserver/wiki/List-of-optional-config-files-&-directories)) which is then copied to ```/etc/postgrey/``` on container startup.

Nevertheless this doesn't answer your question about the directory (```postgrey``` vs ```postfix```) and the logging issue you referenced.

Cheers

**Comment by erik-wramner** [comment]
With `ONE_DIR=1` I get `/var/mail-state/lib-postgrey` with the database files persisted. If you don't want to use `ONE_DIR` you need to find out where the files are and manage your own volumes.

**Comment by wernerfred** [comment]
To answer your initial questions

1.  "the default filepath is /etc/postfix/postgrey_whitelist_clients"
As this image is based on debian take a quick look at the [postgrey man page of debian](https://manpages.debian.org/stretch/postgrey/postgrey.8):
``` --whitelist-clients=FILE     default: /etc/postgrey/whitelist_clients``` So no need to change this path as it is the distributions default-
Use the ```whitelist_clients.local```file as described in my previous comment to add your own definitions.

2. "Logging seems weird"
See the issue you referenced. For now there is no solutions for the missing timestamps. Possible fixes and further information should be discussed there.

3. "I would like to persist it."
See @erik-wramner comment. Use ```ONE_DIRE=1``` with the proposed volume ```- mailstate:/var/mail-state```to persist that data. (I initially thought that doesn't work properly but this was related to moving my setup to another host and loosing that data due to permission and ownership problems. Can confirm it works now).

I think this issue can be closed then.

**Comment by mindrunner** [comment]
Agree with almost everything!

> According to the manpage, we are supposed to use https://postgrey.schweikert.ch/pub/postgrey_whitelist_clients per default. I cannot find this anywhere in docker-mailserver.

This is still unclear to me. Is docker-mailserver using this as a default or am I supposed to add this manually?

**Comment by erik-wramner** [comment]
> You can add a whitelist_clients.local file to your config directory that is mounted into the container (See Wiki) which is then copied to /etc/postgrey/ on container startup.

Add it in your config directory if you want to edit it.

**Comment by mindrunner** [comment]
thanks

**Comment by mindrunner** [comment]
Mmmh, I think I am not happy with that yet. It seems that  docker-mailserver uses an outdated postgrey version and therefore also an outdated whitelist

```
root@mx0:/etc/postgrey# postgrey --version
postgrey 1.36
```
```
root@mx0:/etc/postgrey# cat whitelist_clients
# postgrey whitelist for mail client hostnames
# --------------------------------------------
# put this file in /etc/postgrey or specify its path
# with --whitelist-clients=xxx
#
# postgrey version: 1.36, build date: 2015-09-01
```

i suppose, the old postgrey version is due to the fact, that the update to debian 10 hasn't happened yet, right?

But how about integrating the more recent whitelist? Would make sense, right?

**Comment by wernerfred** [comment]
If you take a look at the [debian postgrey page](https://tracker.debian.org/pkg/postgrey) (or [madison](https://qa.debian.org/madison.php?package=postgrey)) you will see that between stretch (the current stable image) and buster is not even a minor version step of postgrey

```
 postgrey | 1.32-6.1       | squeeze           | source, all
 postgrey | 1.33-3~bpo60+1 | squeeze-backports | all
 postgrey | 1.34-1.1       | wheezy            | source, all
 postgrey | 1.35-1         | jessie            | source, all
 postgrey | 1.36-3+deb9u2  | stretch           | source, all
 postgrey | 1.36-5.1       | buster            | source, all
 postgrey | 1.36-5.1       | bullseye          | source, all
 postgrey | 1.36-5.1       | sid               | source, all
```

Used in the container (confirm the list above):
```
root@mail:/etc/postgrey# apt-cache policy postgrey
postgrey:
  Installed: 1.36-3+deb9u2
  Candidate: 1.36-3+deb9u2
  Version table:
 *** 1.36-3+deb9u2 100
        100 /var/lib/dpkg/status
```

I installed the buster package of postgrey on a separate machine to check the differences in postgreys ```whitelist_clients```:
```
wernerf@BETA:~$ apt-cache policy postgrey
postgrey:
  Installiert:           1.36-5
  Installationskandidat: 1.36-5
  Versionstabelle:
 *** 1.36-5 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```
The content (head):
```
wernerf@BETA:~$ head /etc/postgrey/whitelist_clients
# postgrey whitelist for mail client hostnames
# --------------------------------------------
# put this file in /etc/postgrey or specify its path
# with --whitelist-clients=xxx
#
# postgrey version: 1.36, build date: 2015-09-01
```
I even put it into a diff tool, but the only difference was the command i used to list the content:
![diff_postgrey](https://user-images.githubusercontent.com/20406381/74718281-32106880-5232-11ea-9192-d64dc5b26345.JPG)

So you cannot expect a newer version of ```whitelist_clients``` even if the image will be  updated to buster in future.

If you personally have a newer whitelist then feel free to add it like shown in my previous answer:

> You can add a `whitelist_clients.local` file to your config directory that is mounted into the container (See [Wiki](https://github.com/tomav/docker-mailserver/wiki/List-of-optional-config-files-&-directories)) which is then copied to `/etc/postgrey/` on container startup.

This will not override the default whitelist but add your additional entries.

Any further questions?

**Comment by mindrunner** [comment]
> If you take a look at the debian postgrey page (or madison) you will see that between stretch (the current stable image) and buster is not even a minor version step of postgrey

Yeah, I never understood debian's super conservative update strategy. I mean, why holding back an update which was released more than 3 years ago? 

> So you cannot expect a newer version of whitelist_clients even if the image will be updated to buster in future.

I haven't tried the most recent postgrey version yet, but with the updated whitelist, my experience is way way better. This is why I was suggesting integrating the more recent whitelist into `docker-mailserver` automatically. 

I know, this project is aiming for stability and does not want to integrate new things quickly, but I think the world moves too fast to hang out with 3 years old software ;) 

Anyways, if there is any interest on the maintainer's side here, I am happy to provide pull requests ;)

**Comment by wernerfred** [comment]
> but with the updated whitelist, my experience is way way better.

Can you link to the whitelist you are talking about? I am interested myself and want to check the differences to the version ```1.36-5.1``` which is default in debian/buster.

Can you also tell how you define better? I mean we are talking about a whitelist here, not a blacklist. Do you have so many cases where the initial mail contact gets delayed?

Cheers

**Comment by mindrunner** [comment]
> Can you also tell how you define better?
It's my impression. Not waiting for emails since using the 2019 whitelist.

>I mean we are talking about a whitelist here, not a blacklist. 
Don't get the point. It's annoying to wait for emails, especially 2FA codes and stuff. 

> Do you have so many cases where the initial mail contact gets delayed?
Yes, this is why I am creating this topic. Trying to improve the overall experience.

> Can you link to the whitelist you are talking about?
http://postgrey.schweikert.ch/pub/

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
