### ISSUE TITLE
Unable to add internal networks: please add variable for networks

### ISSUE THREAD

**Issue by hanscees** [tomav/docker-mailserver#1399]
## Context

I am using this mailserver to send and receive email for 4 internal domains. The mailserver sits behind the firewall and has 2 interfaces. 

End-users are all in a local network like 192.168.0.0/24. 
Also a seperate web-mailserver connects to the tomav mailserver via and internal ip  192.168.0.x 

As far as I can see I cannot add the internal network 192.168.0.0/24 to the tomav config.

the env-mailserver has these options: 

```
# Set different options for mynetworks option (can be overwrite in postfix-main.cf)
# empty => localhost only
# host => Add docker host (ipv4 only)
# network => Add all docker containers (ipv4 only)
PERMIT_DOCKER=
```
but that gives no option to add internal networks.

The tomav server simply is unusable:
- dkim does not work (no singing)
- internal users email is stopped (relaying)
and so on

## Expected Behavior

Well if an internal networkj is added internal users should be able to use their email-clients as expected.

## Actual Behavior

The tomav server simply is unusable:
- dkim does not work (no singing)
- internal users email is stopped (relaying)
and so on

## Possible Fix

Please add a variable like "Internal-networks" that can hold multiple internal networks

The script should add these to:
```
/etc/postfix/main.cf
 mynetworks = 
/etc/opendkim/TrustedHosts
   192.168.0.0/24
/etc/spamassassin/local.cf   
   clear_trusted_networks
   trusted_networks 192.168.0.0/24
/etc/fail2ban/jail.conf
    ignoreip = 127.0.0.1/8, 192.168.0.0/24
```

## Steps to Reproduce

This is some dkim logging failing signing:

Feb 14 21:29:50 mail opendkim[243]: 6D30E80C92: [192.168.0.2] [192.168.0.2] not internal
Feb 14 21:29:50 mail opendkim[243]: 6D30E80C92: not authenticated
Feb 14 21:29:50 mail opendkim[243]: 6D30E80C92: no signature data

**Comment by hanscees** [comment]
Oh, and you cant hack the files yourself easily because some of these files are re-written after a reboot of the tomav server. (fail2ban and dkim trusted hosts at least)

Which makes the absense of the variable really unusable in a situation with internal networks. 

But please do  enlighten me if there is a way to add internal networks I overlooked: that would be great!

**Comment by hanscees** [comment]
made a script to do all this automatically. 
But how to run it after a reboot? 

```
#!/bin/bash

## add internal network to 
# postfix main.cf
# opendkim TrustedHosts
# fail2ban jail.conf
# spamassassin local.cf

my_internal_networks="192.168.0.0/24" 

#adjust main.cf
postfixcheck=`egrep "mynetworks.*$my_internal_networks" /etc/postfix/main.cf`
#echo  $postfixcheck
#adjust main.cf
if [ ! -n "$postfixcheck" ] ;
then  
 ##mynetwork needs to be added
 echo yo need to act
 #sed -i "/^mynetworks / s|$| $my_internal_networks|" /etc/postfix/main.cf ## dont use / cause its in var too
fi

##adjust opendkim 
opendkimcheck=`egrep "$my_internal_networks" /etc/opendkim/TrustedHosts`
if [ ! -n "$opendkimcheck" ] ;
then  
   ##mynetwork needs to be added
   echo "yo need to act, my network is $my_internal_networks"
   echo "$my_internal_networks" >> /etc/opendkim/TrustedHosts
   supervisorctl restart opendkim
fi

##adjust fail2ban
fail2bancheck=`egrep "ignoreip.*$my_internal_networks" /etc/fail2ban/jail.conf`
if [ ! -n "$fail2bancheck" ] ;
then  
   ##mynetwork needs to be added
   echo "yo need to act, my network is $my_internal_networks"
   sed -i "/^ignoreip / s|$| $my_internal_networks|" /etc/fail2ban/jail.conf
   #supervisorctl restart fail2ban
fi
#sed -i "/^ignoreip / s|$| $my_internal_networks|" /etc/fail2ban/jail.conf

##adjust spamassassin
spamascheck=`egrep "$my_internal_networks" /etc/spamassassin/local.cf`
if [ ! -n "$spamascheck" ] ;
then  
   ##mynetwork needs to be added
   echo "yo need to act, my network is $my_internal_networks"
   echo "clear_trusted_networks" >> /etc/spamassassin/local.cf
   echo "trusted_networks $my_internal_networks" >> /etc/spamassassin/local.cf
   #supervisorctl restart amavis
fi
```

**Comment by erik-wramner** [comment]
You can run your script in `config/user-patches.sh`. It will run before the services are started, so you don't need to restart anything.

There may be another option as well, I haven't had time to check.

**Comment by hanscees** [comment]
> You can run your script in `config/user-patches.sh`. It will run before the services are started, so you don't need to restart anything.
> 
> There may be another option as well, I haven't had time to check.

thats good to know, so I can get rid of all the supervisorctl lines. I missed the dmarc variable, so I will add that too.

**Comment by hanscees** [comment]
I have produced an example user-patches.sh script I have tested . 
You can find it here: https://github.com/hanscees/dockerscripts/blob/master/scripts/tomav-user-patches.sh

I will add the example to the FAQ.
It implements some changes to anti-spam variables
and also adds internal networks to a number of whitelist files

I have constructed the script so it will only fire changes if you set ENV variables for docker. 

So in my docker-compose.yml it looks like this
```
environment:
    - SPAM_BANNED_DESTINY=D_REJECT
    - SPAM_FINAL_DESTINY=D_PASS
    - WHITELIST_INT_NETWORKS="192.168.0.0/24 10.0.0.2/32"

```

**Comment by hanscees** [comment]
added the example to the faq. Closing this issue.
Still think there should be a whitelist-internal-network env  var be built in.
