### ISSUE TITLE
exec: "doveadm": executable file not found in $PATH

### ISSUE THREAD

**Issue by t94j0** [tomav/docker-mailserver#141]
I am trying to add a user using the way found on dockerhub (because storing encrypted passwords is much more secure 😄),  but when doing so, I am getting the error `exec: "doveadm": executable file not found in $PATH`. I guess dovecot is not getting installed? I have no idea, and would love some help.

**Comment by tomav** [comment]
Hi @t94j0, I suppose you're using `latest` tag and not `v2`.
Only `v2` (currently in beta) supports dovecot.

**Comment by tomav** [comment]
```
➜  docker-mailserver git:(v2) docker run --rm tvial/docker-mailserver:v2 doveadm help
usage: doveadm [-Dv] [-f <formatter>] <command> [<args>]
```
