### ISSUE TITLE
PERMIT_DOCKER=host but how do I make it work from the host?

### ISSUE THREAD

**Issue by realgeek** [tomav/docker-mailserver#1413]
## Context
My host system was using postfix to relay messages to a Gmail account. Now that docker-mailserver is installed (and it's awesome - thank you!), I don't know how to send from the host. I'm sorry - it feels like it should be obvious, but postfix must be turned off to avoid port conflict with the container. As I stated in the title, I have PERMIT_DOCKER=host. So now what?

## Expected Behavior
Mail relayed to container.

## Actual Behavior
Mail isn't sending from the host.

## Your Environment

* Amount of RAM available: 1GB (I have disabled ClamAV)
* Mailserver version used: 
* Docker version used: 18.09.7, build 2d0083d
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by Rillke** [comment]
You need an MTA for relaying your messages from the host to the container, for instance `ssmtp` or `msmtp` or even postfix (with `inet_interfaces = loopback-only`) and the container bound to you public interface.

Here is what I did:
```
$ apt install –no-install-recommends mailutils msmtp-mta msmtp
```

and configure `~/.msmtprc` for each user. See `man msmtp` or [The ArchLinux Wiki](https://wiki.archlinux.org/index.php/Msmtp#Send_mail_with_PHP_using_msmtp) or [this one](https://marlam.de/msmtp/msmtp.html). Questions about `msmtp`, I would ask them on ServerFault or Unix & Linux SE might be helpful, too.

**Comment by Rillke** [comment]
Also ensure you did not create an open relay as mentioned in #1405 - this is likely true if the host the container is running has enabled IPv6 but Docker hasn't. You don't need `PERMIT_DOCKER=host` if you use password auth with either `ssmtp` or `msmtp`.

**Comment by Rillke** [comment]
Another option (which I didn't try) would be probably adding a bash script in place of `/usr/sbin/sendmail` that does a `docker exec CONTAINER_NAME bash -c 'sendmail "$@"'`. Would be interesting to know whether someone succeeded in doing that.

**Comment by realgeek** [comment]
@Rillke thanks very much!! A non-daemon MTA is just what I needed. Ubuntu continues to have ssmtp in their Universe repo, and after a bit of configuration, it's now working nicely.

**Comment by casperklein** [comment]
You can also take a look at [nullmailer](https://wiki.debian.org/nullmailer). I use it to forward all local mails to docker-mailserver.

**Comment by erik-wramner** [comment]
It sounds as if you have a solution, so I'll close this. Please reopen if needed.
