### ISSUE TITLE
Potential race between clamav and amavis / Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory

### ISSUE THREAD

**Issue by funkypenguin** [tomav/docker-mailserver#1416]
On a fresh container start, amavis can't connect to clamav because of

```
Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
```

However, execing into the pod shows that:
1. clamav is running correctly, and 
2. `/var/run/clamav/clamd.ctl` exists as it should.

There are several existing issues with these symptoms, but what's unique about this issue is that clamav is in fact running correctly, and restarting amavis alone solves the issue.

I've done some debugging as follows:

1. Restart amavis with `supervisorctl restart amavis`. Problem does not recur on restart of amavis
2. Stop clamav with `supervisorctl stop clamav`, then restart Amavis with `supervisorctl restart amavis`. Problem occurs (_as expected, since clamav is not running_)
3. After step 2 (_above_), start clamav with `supervisorctl start clamav`. Problem still occurs. (_i.e., Amavis doesn't seem to realize that clamav is now available_)

My conclusion is that clamav has not fully started by the time amavis starts, and so the socket has not yet been created. (_In my logs, there's a 2 sec gap between starting clamav and starting amavis_)

## Context

This happens in a Kubernetes environment, where container resources are restricted. I've not been able to reproduce the issue on a docker-compose setup, but the docker test was done on a host with significantly more resources vs the Kubernetes node.

## Expected Behavior

If the user _wants_ to use clamav, we should wait for clamav to be confirmed started (_perhaps ensuring that the socket exists_), before starting amavis

## Actual Behavior

Amavis starts before clamav has created its socket, and as a result amavis can't use clamd to scan emails.

## Possible Fix

As above, make amavis wait for clamav socket to appear

## Steps to Reproduce

(Explained above in debugging steps)

## Your Environment
* Amount of RAM available: 4GB
* Mailserver version used: 6.2.1
* Docker version used: Kubernetes platform using containerd

**Comment by erik-wramner** [comment]
I'm not 100% sure but I don't think this is a problem and if it is we can't easily solve it. The race condition exists when the container starts, but it can also happen later if clamav is restarted, for example to apply updates. It is thus something that can happen during normal operations both for docker-mailserver and for a normal mail server without docker.

The good things is that (as such) the server seems to handle it. If you look closely at the logs it falls back to running clamav manually when it can't connect to the socket. That is not as efficient of course, but it works. Then when the socket is available it is used.

Feel free to correct me if I'm wrong, but I think this works the way it is and that we won't gain anything by keeping the mail server stopped until clamav is online.

**Comment by erik-wramner** [comment]
Closing due to inaction. Feel free to reopen if needed.
