### ISSUE TITLE
email messages to aliases being rejected

### ISSUE THREAD

**Issue by giodegas** [tomav/docker-mailserver#1417]
I would like to receive emails to my aliases addresses.

## Context

I defined my aliases in 
    config/postfix-aliases.cf

with the syntax

    alias1@domaain:     mymailbox@domain
    alias2@domain:     mymailbox@domain

It does not work.

## Expected Behavior

I want mail sent to `alias1|2@domain` will be read in my `mailbox@domain` together wil other messages sent directly to  `mailbox@domain` .

## Actual Behavior

email rejected.

## Possible Fix

no idea, everything done as documented (I think)

## Steps to Reproduce
1. edit the `config/postfix-aliases.cf`
2. restart the container
3. send email to alias address
4. cannot deliver

## Your Environment

* Amount of RAM available: 4Gb
* Mailserver version used: installed the container in January 2020
* Docker version used: `Docker version 19.03.6, build 369ce74a3c`
* Environment settings relevant to the config:cannot find one specific
* Any relevant stack traces ("Full trace" preferred):

In logs:

`Mar  2 08:55:51 vps postfix/lmtp[1585]: 1AB6D7017BF4: to=<alias1@....>, relay=....[/var/run/dovecot/lmtp], delay=0.06, delays=0.02/0.02/0.02/0.01, dsn=5.1.1, status=bounced (host ...[/var/run/dovecot/lmtp] said: 550 5.1.1 <alias1@...> User doesn't exist: alias1@... (in reply to RCPT TO command))
`
(actual names hidden)

How can I debug aliases delivery?

**Comment by giodegas** [comment]
I have to report also that I edited the `postfix-aliases.cf` after run of the `setup.sh`, which I hope is correct. Afterwards I did:

    docker mail stop
    docker mail start

**Comment by erik-wramner** [comment]
Try to recreate the container instead of stopping and starting it:
```
docker-compose down
docker-compose up -d mail
```
The `postfix-aliases.cf` file should either be processed when the container is started the first time by the startup script or by another script that checks for changes. Re-creating the container will make sure that it is picked up.

If it still doesn't work, please check the logs to see if there are errors when the aliases are processed or if there are other errors or warnings later. You could also enable debug logging with `DMS_DEBUG=1` to get even more logs.

**Comment by giodegas** [comment]
What will happen to the users maildir if I use 

    docker-compose down

I would like not to loose users emails since they access through IMAP

**Comment by giodegas** [comment]
apparently they are saved in the host folder `/var/mail/<username>` , correct?

**Comment by giodegas** [comment]
done, no way same things. "User does not exists" in logs.

**Comment by casperklein** [comment]
> apparently they are saved in the host folder /var/mail/<username> , correct?

Depends on your setup. If you used ``docker-compose.yml.dist`` to get started, then emails are saved in docker volumes, which probably are located somewhere in ``/var/lib/docker/volumes/`` on the host.

>I edited the postfix-aliases.cf

Aliases are defined in ``config/postfix-virtual.cf``.

Or just use: ``setup.sh alias add alias1@domain mymailbox@domain``

**Comment by giodegas** [comment]
no way, same problem, tried both ways.

Now in `config/postfix-virtual.cf` I have:

    alias1@mydomain    myuser

but I try to send to `alias1@mydomain` I alwaws get `"User doesn't exists"`

**Comment by casperklein** [comment]
Did you restart the container?

**Comment by giodegas** [comment]
yes, actualy giving the `docker-compose up/down` command

**Comment by casperklein** [comment]
You could verify the aliases in the container while it's running with: ``docker exec mail cat /etc/postfix/virtual``.

**Comment by giodegas** [comment]
Yes, it correctly contains:

    alias1@domain  myuser

**Comment by casperklein** [comment]
I am out of ideas whats going wrong in your setup. As @erik-wramner already wrote, you could enable debugging and check the relevant logs.

One last thing: You wrote ``myuser``? Is that correct? In the examples I provided you have to use a complete email address such as ``myuser@domain.tld.``.

Did you tried that: ``setup.sh alias add alias1@domain.tld mymailbox@domain.tld``?

If nothing else works, I would start again from scratch and strictly following the readme guide.

**Comment by giodegas** [comment]
Now with 

    setup.sh alias add alias1@domain.tld mymailbox@domain.tld
works, thank you. :+1: 
I had to delete all previous aliases, like:

    setup.sh alias del alias1@domain.tld myuser
