### ISSUE TITLE
(Installation Example) Does not create DKIM keys

### ISSUE THREAD

**Issue by andre-paulo98** [tomav/docker-mailserver#1419]
Followed the Installation Example, and when was the part to setup the DKIM keys, the setup script returns nothing.

## Expected Behavior

It should create a file in config/opendkim/keys/mydomain.com/mail.txt with the keys

## Actual Behavior
Only creates the config/ folder with nothing else inside it

## Your Environment

* Amount of RAM available: 1.6G
* Mailserver version used: latest
* Docker version used: 19.03.6, build 369ce74a3c
* Environment settings relevant to the config: Ubuntu 18.04.4

**Comment by theoneandonly-vector** [comment]
try  this:
./setup.sh debug login
bash -x generate-dkim-config
generate-dkim-domain DOMAIN.TLD
exit

**Comment by andre-paulo98** [comment]
That has worked, but it requires the machine to be up and running (which the step to turn it on is 3 after the one I was stuck on)

**Comment by theoneandonly-vector** [comment]
so this can be closed?

**Comment by andre-paulo98** [comment]
If this is how it supposed to work, then probably the Installation Example needs updating

**Comment by erik-wramner** [comment]
The setup command should not need the container to be up and running. It will start its own temporary container instead. There have been some relatively recent changes in the setup script to support podman, perhaps they are guilty here? Feel free to try from scratch again to see if you can reproduce the issue and ideally detect what goes wrong, perhaps by logging the commands as they run (https://stackoverflow.com/questions/2853803/how-to-echo-shell-commands-as-they-are-executed).
