### ISSUE TITLE
mail dovecot: auth: Error: passwd-file

### ISSUE THREAD

**Issue by aguerrave** [tomav/docker-mailserver#142]
This is my docker-compose

`mail:
  image: tvial/docker-mailserver:v2
  hostname: mail
  domainname: alge.net.ve
  cap_add:
  - NET_ADMIN
  ports:
  - "25:25"
  - "143:143"
  - "587:587"
  - "993:993"
  volumes:
  - ./spamassassin:/tmp/spamassassin/
  - ./postfix:/tmp/postfix/
  - ./mails:/var/mail/
  - ./letsencrypt/:/etc/letsencrypt/
`

>  Apr 20 00:55:25 mail opendmarc[437]: trusted authentication services: mail.alge.net.ve
mail_1 | Apr 20 00:55:25 mail postfix/master[532]: daemon started -- version 2.11.0, configuration /etc/postfix
mail_1 | Apr 20 00:55:25 mail dovecot: auth: Error: passwd-file: open(/etc/dovecot/userdb) failed: No such file or directory
mail_1 | Apr 20 00:55:25 mail dovecot: auth: Error: passwd-file: open(/etc/dovecot/userdb) failed: No such file or directory
mail_1 | Apr 20 00:55:25 mail dovecot: auth-worker(537): Error: passwd-file: open(/etc/dovecot/userdb) failed: No such file or directory
mail_1 | Apr 20 00:55:25 mail dovecot: auth-worker(537): Error: passwd-file: open(/etc/dovecot/userdb) failed: No such file or directory
mail_1 | Apr 20 00:55:25 mail dovecot: auth-worker(537): Error: open(/etc/dovecot/userdb) failed: No such file or directory

**Comment by tomav** [comment]
Hi @aguerrave, your `docker-compose.yml`and probably your accounts file is wrong.
Have a look to v2 documentation, there are breaking changes.
https://github.com/tomav/docker-mailserver/tree/v2

**Comment by aguerrave** [comment]
Perfect!!!
