### ISSUE TITLE
trouble setting up with newer version

### ISSUE THREAD

**Issue by inglesuniversal** [tomav/docker-mailserver#1420]
Hi, it's been about 2 year that I had installed your docker-mailserver app on a bitnami server from AWS and had no issues.

Now that I want to recreated all the steps I followed back then... I'm not getting the results I want

I created a MX file with: mail.mydomain.com   so my main settings look like this:

HOSTNAME=mail
DOMAINNAME=mydomain.com
CONTAINER_NAME=mail

How can I setup for 143 for incoming Email... The email gets created and I am able to open it with ThunderBird but only email is kept in the output bin, but I am not getting any mail nor do my test receipients are getting mail neither.

Do i need to create a SSL cert ?

How can I add two domains?

Thanks and congratulations for your amazing work.

**Comment by erik-wramner** [comment]
Those were many questions and a bit high-level. I would suggest reading the README and the Wiki texts and experimenting a bit. That is the beauty with Docker after all, you can try things quickly with a very low investment.

Port 143 is for unencrypted IMAP and should not be used. You should use encrypted IMAP instead, I think it is 993. IMAP is for reading mail; when you send mail you use port 25 (other external sites send to you) or 465 or 587 (you send to others).

Yes, you need a certificate for SSL/TLS. There is a self-signed certificate included for testing, but for a real server you need a real certificate. Please check the README for alternatives.

Adding two domains is trivial, just add accounts for two domains with the setup tool. You probably want to create DKIM records for both and you definitely need to configure them in your DNS as well.

Good luck!
