### ISSUE TITLE
How to build Dockerfile?

### ISSUE THREAD

**Issue by funkypenguin** [tomav/docker-mailserver#1422]
I'm working on a PR (#1421), but Docker builds are failing.

## Context

I forked the repo, cloned locally, and attempted to build from either master or v6.2.1 branch. I used either `docker build` or `make`.

## Expected Behavior

Docker image succesfully built for local testing

## Actual Behavior

Build errors with:

```
Step 51/57 : COPY ./target/helper_functions.sh ./target/check-for-changes.sh ./target/start-mailserver.sh ./target/fail2ban-wrapper.sh ./target/postfix-wrapper.sh ./target/postsrsd-wrapper.sh ./target/docker-configomat/configomat.sh /usr/local/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder216340645/target/docker-configomat/configomat.sh: no such file or directory
make: *** [build] Error 1
```

1. `git clone https://github.com/tomav/docker-mailserver.git`
2. `cd docker-mailserver`
3.`docker build . -t test`
4. `make`

## Your Environment

* Mailserver version used: master or v6.2.1 branch
* Docker version used: Docker version 19.03.5, build 633a0ea

Am I holding it wrong? :)

D

**Comment by fbartels** [comment]
You have to check out submodules as well

**Comment by funkypenguin** [comment]
Sorted with 'git submodule update --init --recursive', thank you :)
