### ISSUE TITLE
Permission Issues/Question

### ISSUE THREAD

**Issue by angdigi** [tomav/docker-mailserver#1423]
Hello - Running into an issue trying to open certain files, specifically mail.txt and mail.log. I'm sure I can change permissions of the files but wondering if this is normal or perhaps my setup is incorrect.

Here is my docker run command

`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='mailserver' --net='br1.99' --ip='192.168.99.2' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'ENABLE_SPAMASSASSIN'='1' -e 'ENABLE_CLAMAV'='1' -e 'ENABLE_FAIL2BAN'='1' -e 'ENABLE_POSTGREY'='1' -e 'ONE_DIR'='1' -e 'DMS_DEBUG'='1' -v '/mnt/user/appdata/mailserver/var/mail/':'/var/mail':'rw' -v '/mnt/user/appdata/mailserver/var/mail-state':'/var/mail-state':'rw' -v '/mnt/user/appdata/mailserver/var/log/mail':'/var/log/mail':'rw' -v '/mnt/user/appdata/mailserver/tmp/docker-mailserver/':'/tmp/docker-mailserver':'rw' --env-file=/mnt/user/appdata/mailserver/tmp/docker-mailserver/.env --dns=192.168.99.1 'tvial/docker-mailserver' `

Here are permissions of two files that I cannot open/edit

`# ls -l
total 8
-rw------- 1 root root 1675 Mar  6 13:52 mail.private
-rw------- 1 root root  503 Mar  6 13:52 mail.txt
`

**Comment by erik-wramner** [comment]
I think you are confusing the files? The files `mail.private` and `mail.txt` are DKIM records. They should indeed be protected. The file `mail.log` on the other hand should be readable, albeit you probably need to be root.

Where are you trying to open the files? Inside the container (`docker exec -it ...`) or outside? And what are you trying to do exactly?

**Comment by angdigi** [comment]
I need to open mail.txt so I can update my DNS record

> Now the keys are generated, you can configure your DNS server by just pasting the content of config/opendkim/keys/domain.tld/mail.txt in your domain.tld.hosts zone.

Also, I'm trying to open the file(s) outside the container either via SMB to the container volume or another container called Krusader which has root access to the host.
