### ISSUE TITLE
Q: Optimize settings? (SPAM)

### ISSUE THREAD

**Issue by white-rabbit07** [tomav/docker-mailserver#1425]
Hi.
I used the docker-mailserver to send an eMail to "mail-tester.com". After an analysis of the output there were several "problems" leading to a score of 2.1/10. I think this will be a problem when I try to send an eMail this way to an "official" mail-Server as it will be seen as Spam, right?
Is there a way to optimize the settings of the docker-mailserver?
Simply try it yourself and send an eMail to: https://mail-tester.com

**Comment by casperklein** [comment]
> After an analysis of the output there were several "problems" leading to a score of 2.1/10

Without knowing what "problems" exactly leads to your score, it's pretty hard to give any advices. The website informs you, why you may have a deduction of points in some categories.

fyi: The website does not only check the mail configuration such as SPF, DKIM etc., but also the mail content. So if you send an email just with the content "test", you'll get a bad rating..

**Comment by white-rabbit07** [comment]
Ok, I got this score -- the messages are german. I used a translator ... hope that it's no denglish?

`
You are not fully authorized

We check whether the server you are sending from is authenticated

-1

[SPF] linux.meine-domain.de does not allow your 9x.xxx.xxx.xxx server to use <login> @ linux.meine-domain.de

-1

Your message is not signed by DKIM

You do not have a DMARC record

Your reverse DNS entry does not match the sending domain

-3

We did not find a mail server (MX record) behind your domain name ** linux.meine-domain.de **.

Your hostname ** mail.linux.meine-domain.de ** is assigned to a server. -> OK!

and also something from SpamAssassin:
-2.5 NO_FM_NAME_IP_HOSTN NO_FM_NAME_IP_HOSTN
`
I'm not sure if it's possible to optimize these settings in the docker host or not ...

**Comment by casperklein** [comment]
That states pretty clear what the "problems" are: Missing DNS records.

``SPF/DKIM/DMARC`` records are optional, however if they exist, they must be valid.
A ``MX`` record is not optional and required to receive emails.

You sent the email from something@linux.meine-domain.de. However, there are no DNS records at all for that zone.

**Comment by erik-wramner** [comment]
I think the answer from @casperklein is good and this is clearly not an issue with docker-mailserver but with the configuration. Closing.
