### ISSUE TITLE
Can't make DKIM work

### ISSUE THREAD

**Issue by Hamsterman** [tomav/docker-mailserver#1429]
First of all it seems impossible for me to do the installation steps.
Why are they even needed? - Why can't I just start the docker container as I can with most other images?

Anyways I created the DKIM key with another tool (tried both online and another docker image).
But the thing is that I keep getting the "no DKIM keys was found" - Why not write in the log what the files are called that you look for?

All I need is a simple SMTP server that supports DKIM.

**Comment by erik-wramner** [comment]
E-mail is actually quite complex and it is not one-size-fits-all. Your configuration needs to be correct and needs to match your DNS records. If you truly need only the SMTP server then you can set the option `SMTP_ONLY=1` to get just that. However, the beauty with docker-mailserver is that you get a full stack with smtp, imap, antispam/antivirus and much more that works with some configuration but much less work than if you were to set it up yourself.

If you don't want to use the setup script for creating the keys you can always check the script to see where it puts them. However, I would recommend spending a few hours reading about the available options, planning your configuration and trying it out before going live for real. That small investment can save you time and problems down the line.

If you feel you need something even simpler then perhaps this is not the project for you.

**Comment by Hamsterman** [comment]
I am using the SMTP_ONLY=1 and it's not that I don't want to use the install scripts. I can't make them work. I get this error: "No Support Container Runtime Interface Detected."

But you might be right - if I can't make it work I need to find another project for my needs. I would just advice you to make it work much more out of the box in future

**Comment by erik-wramner** [comment]
What platform are you on? The supported host platform is Linux. That doesn't mean you can't use other platforms, but the tests work only on Linux, so it is definitely the safest option.

The setup script tries to find docker or podman. Your error is displayed if it can't find either (shortened):
```
  if [ ! -z "$(command -v docker)" ]; then
    CRI=docker
  elif [ ! -z "$(command -v podman)" ]; then
    CRI=podman
  else
    echo "No Support Container Runtime Interface Detected."
    exit 1
  fi
```
In the top of the script CRI is defined as empty. If you know that you are using docker, for example, you can set it to docker and see if that helps. You can also run the tests (`command -v docker`) manually to see what they return.
