### ISSUE TITLE
Q: Want to change some settings -- but how?

### ISSUE THREAD

**Issue by white-rabbit07** [tomav/docker-mailserver#1432]
Hi.
I want to change some settings such as:
mydomain = shortname.de (instead of "very-long-domain-name.de"
myorigin = $mydomain

But in my docker-compose.yml I just have:
domainname: very-long-domain-name.de
Is there a way to change the domainname this way?

The other question is how to change the eMail-address when it comes from a LDAP/AD-Server.
There's a setting in ldap-users.cf and ldap-aliases.cf like:
query_filter = (samaccountname=%s)
result_attribute = samaccountname
Is it possible to change this? 

At the moment I got eMail-Adresses like
login@very-long-domain-name.de but I'd like to have
givenname.surname@shortname.de

Can you give me a hint?
Thanks.

**Comment by JustAnother1** [comment]
Do you own the domains "very-long-domain-name.de" and "shortname.de" ?If you have not registered "shortname.de" then you can not use it. Or did I get something wrong?

**Comment by white-rabbit07** [comment]
Hi. 
I own the domain shortname.de and the "very-long-domain-name.de" is a subdomain of shortname. So it's like: _subdomain.shortname.de_ and just the shorter form _shortname.de_ ... I'd like to use the shorter form for the email-addresses. 
But moreover the mail-server runs in our school. The domain-name there is _subdomain.shortname.de_ -- nevertheless it would be better if the mail-adress could be _prename.surname@shorname.de_ and not _login@subdomain.shorname.de_ ...

**Comment by JustAnother1** [comment]
I have a similar setup. I made it working like this:
In  ".env"  define "HOSTNAME=subdomain" and "DOMAINNAME=shortname.de"
You have to have a MX record in the DNS entry of "shortname.de" as "subdomain.shortname.de"

You can then define the "givenname.surname" email accounts the same way you defined the "login" email.

Viel Erfolg!

**Comment by white-rabbit07** [comment]
Hi. 
Oh, german, too. Can I contact you via PM -- easier to explain it in our first language....

**Comment by erik-wramner** [comment]
Can we close this, or is it still open?

**Comment by JustAnother1** [comment]
This can be closed.
