### ISSUE TITLE
Activate Shortcircuit plugin if short circuiting is requested by the user

### ISSUE THREAD

**Issue by phish108** [tomav/docker-mailserver#1442]
@evlist remarked on #1118 that the configuration is inactive, because the respective plugin is not loaded. 

The correct fix would be to uncomment the plugin in `/etc/spamassassin/v320.pre` if short circuiting is requested by the user.

**Comment by phish108** [comment]
@erik-wramner the 6.2.2 release lacks this additional fix for #1118. maybe a small subsequent patch release before 7.0?

**Comment by erik-wramner** [comment]
It is in master (which is now basically 7.0) and I have cherry-picked the commit to stable for those who want to stay with 6.x for a while. We can make a version of stable later. I want to wait in case there are critical bugs that need to be fixed in 6.x. Otherwise the focus now should be on 7.x.
