### ISSUE TITLE
Split /tmp/docker-mailserver into two different directories

### ISSUE THREAD

**Issue by evlist** [tomav/docker-mailserver#1444]
## Context
There are two different approaches for handling config files in Docker containers:

* Config files can be copied into the docker images and are either not edited (or edited in a reproducible way at runtime).
* They can also be stored in persistent volumes where they can be edited by admins.

These approaches are more or less exclusive because config files found in Docker images do not override existing files in persistent volumes (they are copied into the volumes when the volume is created but if they are modified afterwards these modifications are not applied in containers even if the image is rebuilt).

If I understand correctly, docker-mailserver mixes these approaches in 3 different ways:

* A limited number of config files are stored in the /tmp/docker-mailserver and copied during the server startup where they belong into /etc/
* A number of config files are modified in /etc/ by the startup script according to the values of environment variables passed to the container.
* Other config files can be copied into /etc/ in the image itself using standard Docker commands.

The first two bullet points correspond to features which are most frequently customized.

## Expected Behavior
It should be possible to decide whether you prefer to edit config files directly in persistent volumes or if you prefer to copy updates into Docker images and rebuild your container.

This should be possible by simply mounting /tmp/docker-mailserver on a persistent volume or not.

## Actual Behavior
The issue is that currently /tmp/docker-mailserver contains both fixed config files such as default sieve rules and "variable" config files edited by the container itself such as DKIM keys or postfix accounts.

This means that if you don't mount /tmp/docker-mailserver as a persistent volume you'll loose important stuff such as your entire user database while if you do mount it as a persistent volume you'll loose the ability to define (and update) configuration options such as sieve rules through Docker images.

And, BTW, it is not possible to simply omit to defined default sieve rules in /tmp/docker-mailserver and just copy them where they belong within /etc because the startup script deletes them if they do not exist in /tmp/docker-mailserver.

## Possible Fix

A simple fix would be use two separate directories for "admin defined" config files and for "container managed" config files.

It would be possible to keep backward compatibility by testing whether or not these directories are split (and maybe printing a deprecation message if they are not).

**Comment by erik-wramner** [comment]
If you decide to proceed with this, please target the next image rather than master. We will switch soon so when it gets time to merge we will almost certainly be running next.

**Comment by evlist** [comment]
OK, thanks !

**Comment by chikamichi** [comment]
Very interesting idea @evlist :+1:

Were you able to make in progress on this?

**Comment by evlist** [comment]
@chikamichi 
> Were you able to make in progress on this?

No, not yet. To be honest once you get a config working it's not a big issue and it has become a low priority for me.

If there is some interest I can spend more time on this, though.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
