### ISSUE TITLE
SSL certificate not working anymore

### ISSUE THREAD

**Issue by flexwie** [tomav/docker-mailserver#1449]
I have been running this mailserver for a little over 3 months now, so far without issues. 
Now I needed to renew my certificates and start to run into errors. I obtained certs frm letsencrypt like I do with normal SSL websites. The certificates are correctly mounted into the container and testtls.com shows no errors. But when I try to connect from nodemailer, I'm getting an error:

```ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:252```

Same error comes up when I try to run

```openssl s_client -crlf -connect ***.***.***.***:587```

to verify. Outlook on the other hand is just telling me that the certificate is still the old one and therefore expired. Is this a problem with nodemailer or am I not using the letsencrypt certificates correctly? Sorry if this is a stupid problem, I'm not really firm with certificates and mailservers.

## Your Environment

* Amount of RAM available: 16GB
* Mailserver version used: latest
* Docker version used: Docker version 19.03.5, build 633a0ea838

**Comment by casperklein** [comment]
docker-mailserver version 7 was released some days ago. So if you are using `docker-mailserver:latest`, you are probably on Debian 10 (buster) now. I think, SSLv3 is now disabled via postfix config:

`smtpd_tls_protocols = !SSLv2,!SSLv3`

You could go back to version 6.2.2, to verify if your setup is working again:

1. `docker-compose down`
1. Change `image: tvial/docker-mailserver:latest` to `image: tvial/docker-mailserver:6.2.2` in your `docker-compose.yml`.
1. `docker-compose up`

If that works, it's probably an issue with SSLv3. Afaik SSLv3 was deprecated around 2014/2015. So you really should think of switching to a newer TLS version.

**Comment by erik-wramner** [comment]
Another possibility is if you haven't restarted the container (down/up). New certificates are not picked up automatically, so you need to restart when they have changed.

**Comment by flexwie** [comment]
> Another possibility is if you haven't restarted the container (down/up).

This will most likely be the problem!

**Comment by erik-wramner** [comment]
Good, please close the issue if that helped. If it didn't help we need more details.
