### ISSUE TITLE
Unable to send email [help wanted]

### ISSUE THREAD

**Issue by Danissss** [tomav/docker-mailserver#1453]
Hi, I tried to send the email but it gave me the error

```
2020-04-15T06:11:20.871610214Z Apr 15 06:11:20 mail postfix/submission/smtpd[19311]: lost connection after STARTTLS from unknown[104.131.210.243]
2020-04-15T06:11:20.871635143Z Apr 15 06:11:20 mail postfix/submission/smtpd[19311]: disconnect from unknown[104.131.210.243] ehlo=1 starttls=0/1 commands=1/2
2020-04-15T06:11:20.871645401Z Apr 15 06:11:20 mail postfix/submission/smtpd[19622]: connect from unknown[104.131.210.243]
2020-04-15T06:11:20.890960544Z Apr 15 06:11:20 mail postfix/submission/smtpd[19622]: lost connection after EHLO from unknown[104.131.210.243]
2020-04-15T06:11:20.891689957Z Apr 15 06:11:20 mail postfix/submission/smtpd[19622]: disconnect from unknown[104.131.210.243] ehlo=1 mail=0/1 commands=1/2
```

I checked the issue with www.checktls.com
here is the error part:
```
Certificate 1 of 1 in chain: Cert VALIDATION ERROR(S): self signed certificate
--
  |   | So email is encrypted but the recipient domain is not verified
  |   | Cert Hostname DOES NOT VERIFY (mail.sample.ca != 2d5296e1d9a6 \| DNS:2d5296e1d9a6)
  |   | So email is encrypted but the host is not verified
```

After I checked here https://github.com/tomav/docker-mailserver/wiki/Configure-SSL, I think I miss the certification. 

I have nginx and let's encrypt certification on server (not on docker container).

So, should I mount my let's encrypt certification on docker container with something like this?
```yml
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/

    - /server/letsencrypt/etc:/etc/letsencrypt/live/sample.ca/privkey.pem

    
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local

```

Also, should I also configure the `env-mailserver` with following setting:
```
# Please read [the SSL page in the wiki](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL) for more information.
#
# empty => SSL disabled
# letsencrypt => Enables Let's Encrypt certificates
# custom => Enables custom certificates
# manual => Let's you manually specify locations of your SSL certificates for non-standard cases
# self-signed => Enables self-signed certificates
SSL_TYPE=letsencrypt
```

From #900, he setup with `SMTP_ONLY=1`, but I am not sure the difference between all daemons start and only launch postfix smtp.

Thank you for your help!

**Comment by erik-wramner** [comment]
I'm not using letsencrypt, but hopefully someone that does will answer. If not check the wiki, there should be fairly detailed examples on this.

**Comment by evlist** [comment]
I am using letsencrypt. I have just been following the wiki and my volume is mounted as:

```yaml
    volumes:
.../...
      - '/var/lib/proxy/certs/:/etc/letsencrypt/live/:ro'
```

Hope this helps.

**Comment by casperklein** [comment]
I've no experience with the _letsencrypt_ option. However, the _manual_ option should work with any kind of certificate:

`docker-compose.yml`:

    volumes:
    - /path/to/public.crt:/tmp/ssl/public.crt:ro # should also include intermediate certificate (You are probably looking for fullchain.pem or similar)
    - /path/to/private.key:/tmp/ssl/private.key:ro

    environment:
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/public.crt
    - SSL_KEY_PATH=/tmp/ssl/private.key

I use this with a letsencrypt certificate.

**Comment by Danissss** [comment]
Thanks for the helps! Both methods work!
