### ISSUE TITLE
Catch-all catches all, also from existing mailboxes

### ISSUE THREAD

**Issue by Dubbeldrank** [tomav/docker-mailserver#1454]
I made a catch-all for my domain with setup.sh which ended up in postfix-virtual.cf. The catch-all seems to work, but it catches all mail also from mailboxes that exist. 

postfix-accounts.cf:
> user1@domain.tld password
> user2@domain.tld password

postfix-virtual.cf:
> @domain.tld user1@domain.tld

The problem is that mail for user2@domain.tld ends up in the inbox of user1@domain.tld. The catch-all should ignore mail for mailboxes that exist. What am i doing wrong?

**Comment by erik-wramner** [comment]
See https://serverfault.com/questions/560906/postfix-virtual-aliases-and-catchall-for-undefined-addresses, perhaps that helps?

**Comment by Dubbeldrank** [comment]
> 
> 
> See https://serverfault.com/questions/560906/postfix-virtual-aliases-and-catchall-for-undefined-addresses, perhaps that helps?

So if i get this correctly i should alias all my accounts to itself and add a catch-all after that to an account i prefer?

**Comment by Dubbeldrank** [comment]
That seems to have solved the issue, thanks!

**Comment by Jule-** [comment]
In fact, a right approach would have been to add the catch-all address in the `vmailbox` file, but it seems that it is auto-generated by `postfix-accounts.cf`, and this is not allowing to redirect all un-match recipients to an existing mailbox from another account.

A working `vmailbox` example is:
```
user1@domain.tld domain.tld/user1/
user2@domain.tld domain.tld/user2/
@domain.tld domain.tld/user1/
```

@georglauterbach I am not sure if this could be done in another way with the actual DMS setup script!?

**Comment by georglauterbach** [comment]
It could be and probably should be. But I got to be honest here: the alias code needs a complete rework. Therefore, I am hesitant towards changing something there as one would be messing inside parts of code that actually need a bigger re-write.

If you're willing to invest some time and effort, the maintainers team (including me) would welcome the help and support you. We are currently very much involved in getting out tests updated, which is a lot of effort. Hence, we cannot do too many things at once.

**Comment by Jule-** [comment]
Thanks for the quick answer! I am afraid I won't have the time to do such a rework... But I can try to see if I could add a few lines to handle this specific case in the actual code if you can point me somewhere.

As a quick workaround, could a `user-patches.sh` amend the `vmailbox` file, or will it mess stuff up?

**Comment by Jule-** [comment]
Like somewhere here:
https://github.com/docker-mailserver/docker-mailserver/blob/b60b4015ab74d9a1b2cba47213919bfa8c2413fb/target/scripts/helpers/accounts.sh#L40-L95

**Comment by georglauterbach** [comment]
> Thanks for the quick answer! I am afraid I won't have the time to do such a rework... But I can try to see if I could add a few lines to handle this specific case in the actual code if you can point me somewhere.

Definitely! We encourage everyone to participate :)

> As a quick workaround, could a `user-patches.sh` amend the `vmailbox` file, or will it mess stuff up?

I think I remember that change-detection code could override your changes from user patches.

---

The link you provided to the `accounts.sh` helper seems good! Make sure to checkout the related helpers and feel free to ask me.

---

Please also open a new issue because this thread has already been closed :) This provides other maintainers with the ability to help too.

**Comment by Jule-** [comment]
Yes thanks, I will. I would like to be sure it deserves a new issue before opening one! :wink:  :+1:

**Comment by Jule-** [comment]
Here you go: #3022 

Let me know your thoughts. 🙂
