### ISSUE TITLE
User DB Discussion

### ISSUE THREAD

**Issue by auguster** [tomav/docker-mailserver#146]
It's not really an issue but I wanted to discuss about the new encrypted password db thing. I find the idea great but I think it's missing something.

The accounts.cf still have to be kept somewhere to be able to add or remove a new user, so the clear password are still somewhere. But I guess it's easier to keep this file safe if it's left on the host (or somewhere else).

The problem is that the user is tempted to create accounts.cf, run
`docker run -ti --rm -v "$(pwd)"/postfix:/tmp/postfix -h mail.domain.com -t tvial/docker-mailserver generate-user-databases`
and then delete the `accounts.cf` file to be able to boot the mail server. Thus loosing any hope of adding a new user without facing be problems. So far the script recreates the whole DB from scratch.

I tried to mount the file `accounts.cf` separatly using a command such as:
`docker run --rm -v "$(pwd)"/accounts.cf:/tmp/postfix/accounts.cf -v "$(pwd)"/postfix:/tmp/postfix -h mail.domain.com -t tvial/docker-mailserver generate-user-databases`
(btw, "-it" can be omitted, there are no interactions)

The issue is that mounting a file by itself doesn't please `sed` and creates a ghost empty file in `/tmp/postfix` that you still have to delete.

So I guess the best practice would be to use a separate folder such as `/tmp/config` and `/tmp/postfix`, the `config/` folder would be only used at initialization and could be kept safe somewhere for maintenance.

**Comment by 00angus** [comment]
Ok let's think about your suggestion.
What would then be the expected user workflow?
**setup**
docker run -v config:/tmp/config <image > generate-user-database
The config path provides only accounts.cf.

**runtime**
docker run <image >
No accounts.cf provided: and it keeps being archived in a well known path not accessible from container.

For me it's OK.

**Comment by auguster** [comment]
Almost, I would do something like that instead:

**setup**
`docker run -v config:/tmp/config -v postfix:/tmp/postfit image generate-user-database`

Maybe it could be a good place to launch something like "image setup" that calls various setup scripts like `generate-user-database`

**runtime**
`docker run -v postfix:/tmp/postfit image`

**Comment by auguster** [comment]
another way to do that would be to add a Dockerfile for deploy that extends `tvial/docker-mailserver` and set's everything up for the user. It would hold all the configurations and password DB. The set-up image can be stored on a private registry.

**Pro**
It's more robust to breaking change we could do on it. Such as forbidding the presence of `accounts.cf`at launch.

**Cons**
The image might not be updated at all and would stay behind and vulnerable to attack.
It would be a pain to update (rebuild, push to private registry).

I prefer the earlier proposal but for argument sake I prefer to expose this solution. It's the path that took the [Discourse forum](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md).

**Comment by tomav** [comment]
Closed due to inactivity. Reopen if needed.
