### ISSUE TITLE
Dovecot error, socket failed

### ISSUE THREAD

**Issue by ArnaudTa** [tomav/docker-mailserver#1460]
The mail server fail to start, I can't receive mail or connect to IMAP (connection refused)

## Context
I don't know when it happened but my last mail is 14 day old. I cannot connect to mail server with clients and external mail server can't reach it.

## Expected Behavior
Dovecot should listen on port 993

## Actual Behavior
Just after the launch logs are full with the error messages, it loops indefinitively.

## Possible Fix
I read it may be related to IPv6 configuration

## Steps to Reproduce
1. Just launch server `dc up -d`

## Your Environment
* Amount of RAM available: many GB available 
* Mailserver version used: latest (0392858ff6cd)
* Docker version used: 19.03.8
* Environment settings relevant to the config: I wished to know the config to edit...
* Any relevant stack traces ("Full trace" preferred):

```mail    | 2020-04-19 22:56:52,588 INFO spawned: 'dovecot' with pid 1422
mail    | 2020-04-19 22:56:52,617 INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail    | Apr 19 22:56:52 mail dovecot: master: Error: socket() failed: Address family not supported by protocol
mail    | Apr 19 22:56:52 mail dovecot: master: Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
mail    | Apr 19 22:56:52 mail dovecot: master: Error: socket() failed: Address family not supported by protocol
mail    | Apr 19 22:56:52 mail dovecot: master: Error: service(imap-login): listen(::, 993) failed: Address family not supported by protocol
mail    | Apr 19 22:56:52 mail dovecot: master: Fatal: Failed to start listeners
mail    | 2020-04-19 22:56:52,619 INFO exited: dovecot (exit status 89; not expected)
```

* FAQ and tips
  https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips

**Comment by erik-wramner** [comment]
What have you changed? It does look like an IPv6 feature, but why did it start?

**Comment by ArnaudTa** [comment]
Oh yeah i remember now, yesterday it was too late to think correctly, I disabled IPv6 on the Ubuntu server few days ago. 

I fixed the problem by editing `main.cf`directly in container (yeah I know, very bad practice ! )
`inet_protocols = ipv4` didn't see the any environment variable to set it, may be it could be a feature to implement.

**Comment by casperklein** [comment]
> didn't see the any environment variable to set it, may be it could be a feature to implement.

Already implemented: https://github.com/tomav/docker-mailserver/blame/master/README.md#L387-L393
