### ISSUE TITLE
Daily cron mail

### ISSUE THREAD

**Issue by casperklein** [tomav/docker-mailserver#1465]
## Problem

Every day, I receive an email from docker-mailerservers cronjob.

**Subject**: `Cron <root@mail> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )`
**Message**: `invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.`

I think, that is similar to https://github.com/tomav/docker-mailserver/issues/792.

What I know so far:

- Cronjob calls /etc/cron.daily/logrotate
- Logrotate process /etc/logrotate.d/rsyslog
- Postrotate calls /usr/lib/rsyslog/rsyslog-rotate
- rsyslog-rotate executes `invoke-rc.d rsyslog rotate > /dev/null`, which then outputs `invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.`

## Expected Behavior
No output / mail should be generated

## Actual Behavior
Output / mail is generated

## Root cause?

Since Debian 10, the following line does not work anymore:

https://github.com/erik-wramner/docker-mailserver/blob/7df3c32e1cd0280b2fd39be3157c07f01522dad3/Dockerfile#L230

## Possible Fix

- Maybe something like: https://github.com/erik-wramner/docker-mailserver/commit/e8a0cdc5561917f042af835701a27352e31963cc
- Or fix the "sed" line mentioned above. However, that only silence the warning if I understand correctly. So the file is still not rotated?

## Your Environment

* Mailserver version used: docker-mailserver:7.0
* Docker version used: 19.03.8

**Comment by erik-wramner** [comment]
Me as well, the fix didn't work. I just haven't had time to dig into it. I think the error is in postrotate, so probably rotation still works. Not sure though as I thought I had fixed it. I'll check when I get some time.

**Comment by casperklein** [comment]
You are right. The file rotates, however no new file is created. Your `/usr/bin/supervisorctl signal hup` approach fixed that.
