### ISSUE TITLE
Applying Limits/Quotas to Outbound Mail

### ISSUE THREAD

**Issue by charles-m-knox** [tomav/docker-mailserver#1476]
## Context

I have a functional docker-mailserver environment, but I want to know if it's possible (maybe via SpamAssassin?) to apply a daily/hourly/monthly limit to the number of outbound emails from the server. If so, can the limit be applied per user?

## Expected Behavior

* Configure an outbound quota per user/month/hour/etc
* The MTA respects the configured quotas

## Actual Behavior

N/A

## Possible Fix

N/A

## Steps to Reproduce

N/A

## Your Environment

N/A

**Comment by youtous** [comment]
Using [PostFWD](https://github.com/postfwd/postfwd), it should be achievable.
As a dirty hack, you could overwrite the entrypoint and install PostFWD and add it to supervisorctl services.
I would recommend forking this image and adjust it to your needs.

According to **PostFWD** documentation, the postfix integration uses check_policy:
```conf
127.0.0.1:10040_time_limit   = 3600
smtpd_recipient_restrictions = permit_mynetworks
                               reject_unauth_destination
                               check_policy_service inet:127.0.0.1:10040
```

[This message](https://www.howtoforge.com/community/threads/limit-outgoing-emails-postfwd.71328/#post-335629) from howtoforge forum is a good starting point for your rules. It does apply limitations per mailbox.

**Comment by charles-m-knox** [comment]
@youtous , thank you for the response! I'll see if I can follow the guidance you've given me and make it happen. I appreciate it.

**Comment by charles-m-knox** [comment]
So @youtous I've taken your advice and integrated PostFWD, and it seems to be promising so far. However, I'm having problems configuring Postfix. No matter what steps I try, I can't get Postfix to load my configuration properly.

I have created the file `./config/postfix-main.cf`

```
10.5.0.6::10040_time_limit      = 3600
smtpd_recipient_restrictions    = permit_mynetworks
                                  reject_unauth_destination
                                  check_policy_service inet:10.5.0.6::10040
smtpd_sender_restrictions       = permit_mynetworks
                                  reject_unauth_destination
                                  check_policy_service inet:10.5.0.6::10040
```

*The static IP mapping throughout this comment may be unnecessary, but I've done it to remove DNS issues as a suspect*

Here's docker-compose.yml:

```yaml
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "4190:4190"
    volumes:
    - /mnt/data/infra/mail/maildata:/var/mail
    - /mnt/data/infra/mail/mailstate:/var/mail-state
    - /mnt/data/infra/mail/maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    - /mnt/data/infra/letsencrypt/etc:/etc/letsencrypt
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
    networks:
      mailnet:
        ipv4_address: 10.5.0.5
  postfwd:
    image: postfwd/postfwd:stable
    environment:
      - PROG=postfwd2
      - CACHE=0
      - EXTRA=-vv --no_parent_dns_cache --summary=600
      # - EXTRA=-vv --no_parent_dns_cache --noidlestats --summary=600
    restart: always
    # port mapping may not be necessary since they're on the same network
    # ports:
    #   - 127.0.0.1:10040:10040
    networks:
      mailnet:
        ipv4_address: 10.5.0.6
    volumes:
      - ./postfwd.cf:/etc/postfwd/postfwd.cf:ro
networks:
  mailnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
```

The contents of `postfwd.cf` are valid, here's a snippet:

```
id=ip_msg_10min
  action=rate(client_address/30/600/421 4.7.1: $$client_address: sending too fast.)
id=ip_msg_3hr
  client_address!=127.0.0.1
  action=rate(client_address/120/10800/421 4.7.1: $$client_address: too many messages, try later.)
id=ip_msg_24hr
  client_address!=127.0.0.1
  action=rate(client_address/150/86400/421 4.7.1: $$client_address: too many messages, try later.)
id=ip_msg_72hr
  client_address!=127.0.0.1
  action=rate(client_address/300/259200/421 4.7.1: $$client_address: too many messages, try later.)
```

I also take the extra steps to use `postconf` on the command line, and I can't load the config lines for PostFWD+Postfix:

```
mail       | postconf: fatal: missing '=' after attribute name: "reject_unauth_destination"                                                                      
mail       | postconf: fatal: missing '=' after attribute name: "check_policy_service inet:10.5.0.6::10040"                                                      
mail       | postconf: fatal: missing '=' after attribute name: "reject_unauth_destination"
mail       | postconf: fatal: missing '=' after attribute name: "check_policy_service inet:10.5.0.6::10040"
```

If I try and condense these into something that Postfix *doesn't* complain about via `postconf`, nothing happens at all:

```bash
$ docker exec -it mail bash
root@mail:/# postconf smtpd_recipient_restrictions="permit_mynetworks","reject_unauth_destination","check_policy_service inet:10.5.0.6::10040"
root@mail:/# postconf -P | grep -i smtpd_recipient
127.0.0.1:10025/inet/smtpd_recipient_restrictions = permit_mynetworks,reject
root@mail:/# postconf smtpd_recipient_restrictions="reject_unauth_destination"
root@mail:/# postconf -P | grep -i smtpd_recipient
127.0.0.1:10025/inet/smtpd_recipient_restrictions = permit_mynetworks,reject
```

You can see that it doesn't seem to set the values for the current Postfix config. Am I missing something here? Do you have any thoughts? I appreciate it.

**Comment by youtous** [comment]
This image uses one line per configuration KV parameter.
https://github.com/tomav/docker-mailserver/blob/master/target/postfix/main.cf#L47

I suspect https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L1213 trying to load each line of `./config/postfix-main.cf` as an individual parameter.

Could you try something like:

*./config/postfix-main.cf*
```
10.5.0.6::10040_time_limit = 3600
smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination, check_policy_service inet:10.5.0.6::10040
smtpd_sender_restrictions = permit_mynetworks, reject_unauth_destination, check_policy_service inet:10.5.0.6::10040
```

**Comment by charles-m-knox** [comment]
Thanks again @youtous. It seems that your suggestion has helped me get closer to my goal, but PostFWD doesn't seem to be doing anything.

I've got a special test rule to restrict more than 1 email message from coming from the same IP over the last 10 minutes below:

```
id=ip_msg_10min
  action=rate(client_address/1/600/421 4.7.1: $$client_address: sending too fast.)
```

I send a test email to another account on the server, with a mail client located at an external IP. I don't see any logging in PostFWD at all and I was able to send many mails through.

The good news is that I've verified that the rule has been applied by running `docker exec -it mail bash` and inspecting `/etc/postfix/main.cf`:

```
main.cf:smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, check_policy_service inet:10.5.0.6::10040, reject_un
auth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net
main.cf:smtpd_client_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, reject_unauth_pipelining,check_policy_service inet:10.5.0.6::10040
main.cf:smtpd_sender_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unknown_sender_domain, check_policy_service inet:10.5.0.6::10040
```

For reference, I updated the values in `postfix-main.cf` to:

```
10.5.0.6::10040_time_limit=3600
smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, check_policy_service inet:10.5.0.6::10040, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net
smtpd_client_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, reject_unauth_pipelining,check_policy_service inet:10.5.0.6::10040
smtpd_sender_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unknown_sender_domain, check_policy_service inet:10.5.0.6::10040
```

I based these values off of the template values in https://github.com/tomav/docker-mailserver/blob/master/target/postfix/main.cf#L47 and basically added a `check_policy_service` action in the spots that I thought looked best.

So, it seems the config is definitely working, Do you think it's possible I've misconfigured the order of these `check_policy_service` configuration parameters maybe? Any suggestions? You've been very helpful, I really can't thank you enough for your help.

**Comment by charles-m-knox** [comment]
I may have gotten it working @youtous !! It turns out that I had two colons in the inet addresses and that was a syntax error. Example:

```
10.5.0.6::10040_time_limit=3600
```

should be

```
10.5.0.6:10040_time_limit=3600
```

It appears my rule has been processed and run, and it _did_ actually throttle a message successfully. I'll report back if I run into any other problems...

**Comment by charles-m-knox** [comment]
Ok, so this took some tedious work but I finally figured out how to limit outbound emails from my users - example error message from Thunderbird:

```
An error occurred while sending mail. The mail server responded:
450 4.7.1 <user@domain.com>: Sender address rejected: sorry, max 2 requests per hour.
Please check the message recipient "recipient@domain.com" and try again.
```

In order to ensure that the PostFWD rules _even get run_, you have to check that the order of operations in your `postfix-main.cf` are valid for what you want. For example, if `permit_mynetworks` is in front of your `check_policy_service` action, it won't run. This is what was happening to me - calls to PostFWD were not running when sending mail with one of my accounts, but it _was_ running when I was receiving mail from an external domain (such as gmail).

I had to shuffle the `check_policy_service` call high up in the list for each of the options. See my `postfix-main.cf` below:

```
10.5.0.6:10040_time_limit=3600
smtpd_recipient_restrictions=reject_unauth_pipelining,check_policy_service inet:10.5.0.6:10040,permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination,check_policy_service unix:private/policyd-spf,reject_invalid_helo_hostname,reject_non_fqdn_helo_hostname,reject_unknown_recipient_domain,reject_rbl_client zen.spamhaus.org,reject_rbl_client bl.spamcop.net
smtpd_client_restrictions=reject_unauth_destination,reject_unauth_pipelining,check_policy_service inet:10.5.0.6:10040,permit_mynetworks,permit_sasl_authenticated,
smtpd_sender_restrictions=reject_unknown_sender_domain,check_policy_service inet:10.5.0.6:10040,permit_sasl_authenticated,permit_mynetworks
smtp_tls_security_level=encrypt
```

And my `postfwd.cf` now _only has one rule_ to keep things simple:

```
id=limit_rate ; protocol_state==RCPT
                action=rate(client_address/2/3600/450 4.7.1 sorry, max 2 requests per hour)
```

From the reading I've done and my limited understanding of Postfix/PostFWD, `reject_unauth_pipelining` has to go before the `check_policy_service` action. Aside from that, the `check_policy_service` call to PostFWD is the next immediate action for each of the `smtp_*_restrictions` config options above.

Some of these options may not be needed, or could potentially be in dangerously wrong order. Please, anyone reading this, correct my rules if you see anything scary. I'll be refining the rules as time goes on, but this is what I've got for now. Thanks again @youtous for all the help.

**Comment by charles-m-knox** [comment]
It's worth noting that this was the thread that helped figure out the postfix rule ordering issue: https://serverfault.com/a/810085

**Comment by youtous** [comment]
> For example, if permit_mynetworks is in front of your check_policy_service action, it might not run since the result of permit_mynetworks returns OK. This is what was happening to me - calls to PostFWD were not running when sending mail with one of my accounts, but it was running when I was receiving mail from an external domain (such as gmail).

Good to know! Thank you.

Interesting use case and your explanations are well detailed!

**Comment by frugan-it** [comment]
My 2 cents.

<details>
<summary>docker-compose.yml</summary>

```yml
version: '3.9'
services:
  ...
  postfwd:
    image: docker.io/postfwd/postfwd:stable
    container_name: postfwd
    environment:
      - PROG=postfwd2
      #- CACHE=0
      #- EXTRA=-vv --no_parent_dns_cache --noidlestats --summary=600
    restart: always
    volumes:
      - ${PWD}/postfwd/conf/postfwd.cf:/etc/postfwd/postfwd.cf:ro
      - ${PWD}/postfwd/conf/file:/etc/postfwd/file
  ...
```
</details>

<details>
<summary>postfix-main.cf</summary>

```cfg
#http://www.postfix.org/SMTPD_ACCESS_README.html
#https://postfwd.org/doc.html
#https://github.com/docker-mailserver/docker-mailserver/issues/1476
#https://wiki.zimbra.com/wiki/How-to-restrict-ssl-login
#https://documentation.n-able.com/mail-assure/userguide/Content/Integration/conf-incoming-postfix.htm
#https://serverfault.com/a/604329/377751
postfwd:10040_time_limit = 3600

# added `check_policy_service inet:postfwd:10040` before `permit_sasl_authenticated`
smtpd_recipient_restrictions = check_recipient_access texthash:/tmp/docker-mailserver/postfix-receive-access.cf, check_policy_service inet:postfwd:10040, permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, check_policy_service inet:localhost:65265, reject_rbl_client zen.spamhaus.org, check_policy_service inet:127.0.0.1:10023

smtpd_end_of_data_restrictions = check_policy_service inet:postfwd:10040
```
</details>

<details>
<summary>postfix-master.cf</summary>

```cfg
# 587
submission/inet/smtpd_authorized_xclient_hosts=1.2.3.4,[1111:1111:2222:2222:3333:3333:4444:4444],5.6.7.8,[5555:5555:6666:6666:7777:7777:8888:8888]

#https://serverfault.com/a/765140
#https://serverok.in/postfix-smtp-530-5-7-0-must-issue-a-starttls-command-first
#https://github.com/docker-mailserver/docker-mailserver/issues/302#issuecomment-244443352
submission/inet/smtpd_tls_security_level=may

#https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/
#submission/inet/smtpd_upstream_proxy_protocol=haproxy

# 465
smtps/inet/smtpd_authorized_xclient_hosts=1.2.3.4,[1111:1111:2222:2222:3333:3333:4444:4444],5.6.7.8,[5555:5555:6666:6666:7777:7777:8888:8888]

#https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/
#smtps/inet/smtpd_upstream_proxy_protocol=haproxy
```
</details>

<details>
<summary>postfwd.cf</summary>

```cfg
#https://postfwd.org/doc.html
#https://postfwd.org/ratelimits.html
#http://www.postfix.org/access.5.html
#https://woodpecker.co/blog/email-sending-limits/
#https://vinters.com/blog/rate-limit-outbound-mail-in-postfix/
# Protocol states are CONNECT, EHLO, HELO, MAIL, RCPT, DATA, END-OF-MESSAGE, VRFY or ETRN;
# these are the SMTP protocol states where the Postfix SMTP server makes an OK/REJECT/HOLD/etc. decision.
#
# Lists will be evaluated in the specified order. This allows to place faster expressions at first.

# RCPT
# rate() with `protocol_state==RCPT` check every single recipient, before $recipient_count action.
# So a client could trigger $recipient_count REJECT action and still cause rate() counter increase.
#FIXME - not working:
# client_address!=file:/etc/postfwd/file/client_address_local.cf
# client_address=!!(10.0.0.0/8); client_address=!!(172.0.0.0/8);
# client_address=~!!( /^(10|172)\./ );
id=RATE-IN-MINUTE-1;
    protocol_state==RCPT;
    client_name==!!(unknown);
    action=rate(client_address/10/60/450 4.7.1 sorry, maximum 10 incoming messages per minute - you've reached $$ratecount hits)
id=RATE-IN-MINUTE-2;
    protocol_state==RCPT;
    client_name==!!(unknown);
    action=rate(sender/10/60/450 4.7.1 sorry, maximum 10 incoming messages per minute - you've reached $$ratecount hits)

id=RATE-OUT-HOUR-1;
    protocol_state==RCPT;
    sasl_method==XCLIENT;
    sasl_username=~file:/etc/postfwd/file/sasl_username_1.cf;
    action=rate(sasl_username/500/3600/450 4.7.1 sorry, maximum 500 outgoing messages per hour)
id=RATE-OUT-DAY-1;
    protocol_state==RCPT;
    sasl_method==XCLIENT;
    sasl_username=~file:/etc/postfwd/file/sasl_username_1.cf;
    action=rate(sasl_username/1000/86400/450 4.7.1 sorry, maximum 1000 outgoing messages per day)


# END-OF-MESSAGE
# rate() with protocol_state==END-OF-MESSAGE check only single message, maybe after $recipient_count action.
# So a client could send X messages with Y recipients each, where Y <= $recipient_count, X <= rate() counter, but (X*Y) > rate() counter.
id=RCPT-OUT-1;
    protocol_state==END-OF-MESSAGE;
    sasl_method==XCLIENT;
    sasl_username=~file:/etc/postfwd/file/sasl_username_1.cf;
    recipient_count>50; action=REJECT sorry, maximum 50 recipients - you've $$recipient_count recipients)


# catch-all rule for debug
#id=DEFAULT;
#    action=dunno
```
</details>

<details>
<summary>sasl_username_1.cf</summary>

```cfg
/.*@domain\.tld$/
```
</details>

<details>
<summary>client_address_local.cf</summary>

```cfg
10.0.0.0/8
172.0.0.0/8
```
</details>

Keep in mind that:

- my mail servers are behind nginx mail proxies
- mail proxies have IPs of the type `1.2.3.4`, `1111:1111:2222:2222:3333:3333:4444:4444`, `5.6.7.8`, `5555:5555:6666:6666:7777:7777:8888:8888`, etc.
- customers send mails via XCLIENT sasl method
- communication between mail servers and mail proxies is protected by firewall
- `$client_address` variables detected by PostFWD relating to mail proxies are of the type `10.0.0.0/8`, `172.0.0.0/8`
- `$client_name` variable detected by PostFWD relating to mail proxies is `unknown`
- I also tried integrating PostFWD in `postfix-main.cf` via `smtpd_restriction_classes` (see INTEGRATION section here https://postfwd.org/doc.html), but it seems to me that it is more efficient to move the per-user logic to PostFWD (see `sasl_username_1.cf`)

Some issues need to be managed better:

- the detection of only incoming mail (rules `RATE-IN-MINUTE-1` and `RATE-IN-MINUTE-2`) is to be improved, as it is based on the variable `$client_name` (`client_name==!!(unknown)`), that could have an `unknown` value even for some external senders
- I tried to use other more efficient methods based on `$client_address` (`client_address!=file:/etc/postfwd/file/client_address_local.cf`, `client_address=!!(10.0.0.0/8); client_address=!!(172.0.0.0/8)`, `client_address=~!!( /^(10|172)\./ )`), but they don't seem to work (also this warning appears on PostFWD logs `warning: Use of uninitialized value $this_ip in string lt at /usr/share/perl5/vendor_perl/Net/CIDR/Lite.pm line 310`)
- I have not yet tested well which rules are used when a customer sends to himself or to another customer within his own company
- I didn't get to grips with the `$recipient_count` issue, which also makes the `rate()` counter increment (see `postfwd.cf` comments for more explanations)

I hope it can be of help to someone.. and obviously any suggestion is welcome! :wink:
Maybe you could put some parts or information about PostFWD in the documentation, or not?!
