### ISSUE TITLE
amavis blocking signed Office documents

### ISSUE THREAD

**Issue by lokipo** [tomav/docker-mailserver#1477]
## Context
When using amavis, signed MS-Office documents are blocked due to being recognized as executables.

## Expected Behavior
Files should not cause false positives.

## Actual Behavior
Mails are quarantined.

## Possible Fix
add:

``# allow trash sections of docx files
  [ qr'^\[trash\]/[0-9a-f]{4}\.dat$' => 0 ],   # allow [trash]hhhh.dat in docx files``

to amavis config.

## Steps to Reproduce
Send a signed .docx-file while having amavis enabled.

## Your Environment
Bounce:

No viruses were found.

Banned name: .exe,.exe-ms,0001.dat
Content type: Banned
Internal reference code for the message is 30329-04/rlLTtU5Wo0ym

First upstream SMTP client IP address: [xxx]
some.domain
According to a 'Received:' trace, the message apparently originated at:
 [xxx], 

Return-Path: <does@notmatter.com>
From: John Doe <does@notmatter.com>
Message-ID: <04CC57C4-F62D-4619-A0C1-CA93EA9065F0@notmatter.com>
Subject: Some cool subject and a .docx file
The message has been quarantined as: r/banned-rlLTtU5Wo0ym

The message WAS NOT relayed to:
<randomaddress@notmatter.com>:
  250 2.7.0 Ok, discarded, id=30329-04 - BANNED: .exe,.exe-ms,0001.dat

Return-Path: <does@notmatter.com>
Date: Thu, 30 Apr 2020 07:58:23 +0200
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=notmatter.com;
	s=mail; t=1588236310;
	bh=0IHCaZje/Vkxiw0IVvjgaY7f6s2s1Arm02P0DGTlME4=;
	h=Subject:From:To:References:In-Reply-To;
	b=LBc5bd7Yau+Jzo36ly/2REqPLPrKHVYwuMXyW4y/qbwWSbvqLFx02V2oc9RMOIhiX
	 gE3OFG0FXFMajQ7uMTWXanmubwauPfOgGr9Qy3NkZpKW2MLRuG8RtQZYTE1I9uKhFK
	 c3aLwSC35y+dHHAcHzhfQT0lkkXqnM8yeCiUCCqPiYuH2yHvHH/3ET0feklTWUEMn0
	 f/0TM6Mc+Qn4YQwugaFW9US/M0QNlpDQmI4M1c4DBC6XenTfDtRaZo6AJUx66MUoov
	 n3/hlL3opIG/SQUZkTXgHeKRS1PF20XmnQZNIG4l3ZWtSkdiL4Fg3FWAlyzTKF9Vck
	 mWHVvXbuUFYCw==
Subject: Some cool subject and a .docx file
From: John Doe <does@notmatter.com>
To: Jane Doe <randomaddress@notmatter.com>
Message-ID: <04CC57C4-F62D-4619-A0C1-CA93EA9065F0@notmatter.com>
Thread-Topic: Some cool subject and a .docx file
References: <6EAB48B2-52D7-4F3D-A586-EC533319F218@notmatter.com>
<c792453cf1d84f4885b658b9e07aeafb@grohe.com>
<DC767FAE-9C62-40B2-B5A7-ABC872D71A1D@notmatter.com>
<51733553be234ad3bec07c80095bf404@grohe.com>
In-Reply-To: <51733553be234ad3bec07c80095bf404@yyy.com>
Mime-Version: 1.0
Content-type: multipart/mixed;
	boundary="B_3671078303_765886828"
## Possible answers to you issue
* ClamAV keeps restarting:
  https://github.com/tomav/docker-mailserver#requirements

* Email seen as spam:
  https://github.com/tomav/docker-mailserver/wiki/Configure-SPF
  https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM

* Creating new domains and accounts
  https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts

* Use a relay mail server
  https://github.com/tomav/docker-mailserver/wiki/Configure-AWS-SES
  The variable name can be used for other email servers.

* FAQ and tips
  https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips

* And the WIKI
  https://github.com/tomav/docker-mailserver/wiki

* Open issues
  https://github.com/tomav/docker-mailserver/issues
-->

**Comment by erik-wramner** [comment]
@lokipo it is possible to override the amavis configuration by creating the file `config/amavis.cf` in the directory where you have your compose file. That file will be copied as an amavis user override file. Can you try adding the changed option and restarting (down/up) to see if it solves the problem? Then you have a quick fix and we know if it works before changing the image itself.

**Comment by lokipo** [comment]
@erik-wramner 
Hi,
I already did that, thank you!
Solution works, I just wanted to suggest changing the default behaviour as this will be a problem for others, too.
Should have mentioned the amavis.cf, sorry for that!

**Comment by erik-wramner** [comment]
Absolutely. Please see existing config files in `target/dovecot`. If it is possible to adapt one of them (or add a new file there) that might be cleaner than using `sed` in the `Dockerfile`.

**Comment by aendeavor** [comment]
I can understand this issue, but I feel like this default behavior is a good measure, especially looking at [**Emotet**](https://en.wikipedia.org/wiki/Emotet). I know this sounds very defensive, but especially for smaller companies which may use this Mail Server, this is good thing (I talking from _experience_). But even for personal use, I cannot recommend this to anyone anymore.

I must admit, I don't know what impact signing these documents has, but I'm confident checking for the signature is non-trivial. Please correct me here if I'm wrong.

Feel free to adapt this in the documentation.

As this issue was waiting for contributor action since May, I will close it and mark it as frozen. _If you feel like there is more and this issue needs to be re-opened, please do so!_
