### ISSUE TITLE
Quota (missing status service) causing emails to be rejected with "Recipient address rejected: Server configuration problem;"

### ISSUE THREAD

**Issue by ddp526** [tomav/docker-mailserver#1478]
## Context
Recently after an update, external email coming into my domain started failing with "Recipient address rejected: Server configuration problem;"
Just before this log error, postfix also logged:

```ESC[36mmail              |ESC[0m Apr 29 14:16:25 mail postfix/smtpd[1701]: warning: connect to localhost:65265: Cannot assign requested address
ESC[36mmail              |ESC[0m Apr 29 14:16:25 mail postfix/smtpd[1701]: warning: problem talking to server localhost:65265: Cannot assign requested address
ESC[36mmail              |ESC[0m Apr 29 14:16:26 mail postfix/smtpd[1701]: warning: connect to localhost:65265: Cannot assign requested address
ESC[36mmail              |ESC[0m Apr 29 14:16:26 mail postfix/smtpd[1701]: warning: problem talking to server localhost:65265: Cannot assign requested address
ESC[36mmail              |ESC[0m Apr 29 14:16:26 mail postfix/smtpd[1701]: NOQUEUE: reject: RCPT from a24-22.smtp-out.us-west-2.amazonses.com[54.240.24.22]: 451 4.3.5 <xxxxxx>: Recipient address rejected: Server configuration problem; from=<202004282324576eb0deaab3b74590baa2e583a710p0fe-C1ZKMDNDSKBPJD@bounces.amazon.com> to=<xxxxxx> proto=ESMTP helo=<a24-22.smtp-out.us-west-2.amazonses.com>
```

Cannot receive email from external sources

## Expected Behavior
I should be able to receive emails from external sources

## Actual Behavior
My mail server rejects the email instead.

## Possible Fix
I dug through the configs, and believe this is all related to the recent addition to support quotas.  The /etc/postix/main.cf includes this line:
```
smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, check_policy_service inet:localhost:65265, reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net
```

The check_policy_service inet:localhost:65265 is failing as there is nothing running on this port.   Digging through the change on git, I can see the quota-service should be running on this port, but in my setup, there is no file including the quota in the plugins, and no service running.

So I think the if statement below in start_mailserver.sh needs to factor in no quotas, and not assume the service is running?
 
```
 if [ "$SMTP_ONLY" = 1 ]; then
      sed -i "s/check_policy_service inet:localhost:65265//g" /etc/postfix/main.cf
    else
      sed -i "s/reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org/reject_unknown_recipient_domain, check_policy_service inet:localhost:65265, reject_rbl_client zen.spamhaus.org/g" /etc/postfix/main.cf
    fi
```

## Steps to Reproduce

1. I am not really sure, for me it seem docker pull was the actual trigger.

## Your Environment
My env has the following file:
```
root@mail:/# ls -l /etc/dovecot/conf.d/90-quota.conf.disab 
-rw-r--r-- 1 root root 1316 Apr 29 07:15 /etc/dovecot/conf.d/90-quota.conf.disab
```
e.g. there is no output for these commands from inside the mail container.
```
root@mail:/# grep -r quota /etc/dovecot/ | grep plugin
root@mail:/# 
root@mail:/# find . -name dovecot-quotas.cf
root@mail:/# 
```

I have my users stored in openldap, and have SASL auth in use as well.   
If it helps, sending email from my local domain to another user on my local domain somehow delivers without issue, and I can imap in to receive the email, so ldap, etc. seems to be working fine (and was prior to the update).

**Comment by youtous** [comment]
> I have my users stored in openldap, and have SASL auth in use as well.
That's a use case I've not covered. 
The bug is related to:
https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L665

Copying this line at https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L639 should solve the bug.

I'll submit a PR for fixing this.

Thank you!

**Comment by youtous** [comment]
Tests are running, if they pass @erik-wramner  could you merge? Thanks

**Comment by erik-wramner** [comment]
@youtous sure but I think there is a bug. At least in the git diff it looks as if there is an if-statement that should be closed earlier. Please check.
