### ISSUE TITLE
DKIM for new domain

### ISSUE THREAD

**Issue by ghnp5** [tomav/docker-mailserver#1486]
Hello,

If I have already generated DKIM keys for my domains, which are currently running well,
and have now a new domain, introduced recently, that I want to generate DKIM key for,
can I generate DKIM **only** for that new domain, using either the "docker" command or "setup.sh" ?

From my understanding, if I run any of those, it will re-generate/overwrite the existing DKIM keys for the existing domains.

Thank you.

**Comment by erik-wramner** [comment]
Make a backup copy of your old files first just in case, but looking at `target/bin/generate-dkim-config` it is supposed to be possible to run it several times. It should not overwrite existing domains, but should add missing files for new domains.

Again, please backup your files first in case there is a bug in the script. One can't be too careful.

**Comment by ghnp5** [comment]
Thanks very much! Good to know (might be worth putting that in the documentation).
If any issues, I'll let you know.
