### ISSUE TITLE
Support comments in postfix-accounts.cf

### ISSUE THREAD

**Issue by ghnp5** [tomav/docker-mailserver#1487]
I ran the following command and got a few errors like:

> mkdir: invalid option -- 'e'
> Try 'mkdir --help' for more information.
> Unknown option: c
> opendkim-genkey: usage:
> generate-dkim-config: cannot create

I did get some keys generated at the end (the "mail.txt" exists for all domains), but this doesn't seem like it did what it wanted to...

```
[root@server mailserver]# cd /path/to/mailserver
[root@server mailserver]# docker run --rm -v "$(pwd)/config":/tmp/docker-mailserver -ti tvial/docker-mailserver:latest generate-dkim-config 2048
mkdir: invalid option -- 'e'
Try 'mkdir --help' for more information.
Creating DKIM private key /tmp/docker-mailserver/opendkim/keys/domain.tld -e MAIL_PASS=mypassword -ti tvial/docker-mailserver:latest /bin/sh -c 'echo "/mail.private
Unknown option: e
Unknown option: i
Unknown option: c
Unknown option: e
Unknown option: i
Unknown option: c
opendkim-genkey: usage: opendkim-genkey [options]
        --append-domain        include domain name in zone file stub
        --bits=n               use n bits to generate the key
        --directory=path       leave output in the named directory
        --domain=name          generate data for the named domain [domain.tld]
        --hash-algorithms=list limit to use of the named algorithm(s)
        --help                 print help and exit
        --note=string          include specified note in zone data
        --restrict             restrict key to email use only
        --selector=name        selector name [mail]
        --subdomains           allow signing of subdomains
        --testmode             indicate key is in test mode
        --verbose              increased output
        --version              print version and exit
Creating DKIM KeyTable
/usr/local/bin/generate-dkim-config: 52: /usr/local/bin/generate-dkim-config: cannot create /tmp/docker-mailserver/opendkim/KeyTable: Directory nonexistent
Creating DKIM SigningTable
/usr/local/bin/generate-dkim-config: 63: /usr/local/bin/generate-dkim-config: cannot create /tmp/docker-mailserver/opendkim/SigningTable: Directory nonexistent
Creating DKIM private key /tmp/docker-mailserver/opendkim/keys/FIRST_DOMAIN.tld/mail.private
Creating DKIM KeyTable
Creating DKIM SigningTable
Creating DKIM private key /tmp/docker-mailserver/opendkim/keys/SECOND_DOMAIN.tld/mail.private
Creating DKIM private key /tmp/docker-mailserver/opendkim/keys/THIRD_DOMAIN.tld/mail.private
Creating DKIM TrustedHosts

```

**Comment by ghnp5** [comment]
Any ideas about this? :) thanks!

**Comment by erik-wramner** [comment]
Please provide more information. What is your setup, including host platform and enabled options? What should we do to reproduce this from scratch? And are you really running docker directly, if so why don't you use the documented `setup.sh` script?

**Comment by ghnp5** [comment]
I simply followed these steps...
https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM

There's no mention of the "setup.sh" script there.

Enabled options is Postfix, Dovecot, Spamassassin, Fail2ban, One-Dir and LetsEncrypt.

Volumes:
    - /mailserver/data:/var/mail
    - /mailserver/state:/var/mail-state
    - /mailserver/logs:/var/log/mail
    - /mailserver/letsencrypt:/etc/letsencrypt
    - ./config/:/tmp/docker-mailserver/
    - /etc/localtime:/etc/localtime:ro

**Comment by erik-wramner** [comment]
Right. Perhaps it is outdated, please check https://github.com/tomav/docker-mailserver. In summary from scratch (simplified please read the full text in the link):
```
docker-compose up -d mail
./setup.sh email add user@domain password
./setup.sh config dkim
```
Does that work better? If not, what platform are you using? Linux? With docker or podman?

**Comment by ghnp5** [comment]
Thank you.

Same thing happens.

I am on CentOS 7 using Docker.


```
[root@server mailserver]# ./setup.sh config dkim
mkdir: invalid option -- 'e'
Try 'mkdir --help' for more information.
Creating DKIM private key /tmp/docker-mailserver/opendkim/keys/domain.tld -e MAIL_PASS=mypassword -ti tvial/docker-mailserver:latest /bin/sh -c 'echo "/mail.private
Unknown option: e
Unknown option: i
Unknown option: c
Unknown option: e
Unknown option: i
Unknown option: c
opendkim-genkey: usage: opendkim-genkey [options]
        --append-domain        include domain name in zone file stub
        --bits=n               use n bits to generate the key
        --directory=path       leave output in the named directory
        --domain=name          generate data for the named domain [domain.tld]
        --hash-algorithms=list limit to use of the named algorithm(s)
        --help                 print help and exit
        --note=string          include specified note in zone data
        --restrict             restrict key to email use only
        --selector=name        selector name [mail]
        --subdomains           allow signing of subdomains
        --testmode             indicate key is in test mode
        --verbose              increased output
        --version              print version and exit
[root@server mailserver]#

```

**Comment by ghnp5** [comment]
By looking at the code,




```
domainname=$1

mkdir -p /tmp/docker-mailserver/opendkim/keys/$domainname

if [ ! -f "/tmp/docker-mailserver/opendkim/keys/$domainname/mail.private" ]; then
    echo "Creating DKIM private key /tmp/docker-mailserver/opendkim/keys/$domainname/mail.private"
    opendkim-genkey --subdomains --domain=$domainname --selector=mail -D /tmp/docker-mailserver/opendkim/keys/$domainname
fi
```


Seems like $domainname is equal to this:

"domain.tld -e MAIL_PASS=mypassword -ti tvial/docker-mailserver:latest /bin/sh -c 'echo "/"

**Comment by ghnp5** [comment]
Ah ok! I see what's happening...

The script looks into "postfix-accounts.cf", but does not ignore the comments :)


I have a comment on that ".cf" file that the script is trying to parse:


> # docker run --rm -e MAIL_USER=user1@domain.tld -e MAIL_PASS=mypassword -ti tvial/docker-mailserver:latest /bin/sh -c 'echo "$MAIL_USER|$(doveadm pw -s SHA512-CRYPT -u $MAIL_USER -p $MAIL_PASS)"'

The script should ignore all lines beginning with #

Thanks!

**Comment by erik-wramner** [comment]
Great, then I'll close this.

**Comment by ghnp5** [comment]
Ok - so you're not willing to fix this issue, then?

**Comment by erik-wramner** [comment]
Sorry, I thought your problem was solved. Anyway, as far as I know we have no documentation that says you can use comments in the accounts file? I don't really see this as a bug, it is simply something that is not supported.

Having said that it would be a nice thing to have. If you want to make a PR I'll gladly merge it. However, if we are to support comments in that file they must be supported everywhere, so you would have to fix the setup script, the change detector script and the start script.

**Comment by youtous** [comment]
> so you would have to fix the setup script, the change detector script and the start script.

It seems `start-mailserver.sh` is already supporting `postfix-accounts.cf` postfix comments: https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L706

> The script looks into "postfix-accounts.cf", but does not ignore the comments :)

Using the logic from `start-mailserver.sh`:
```
while IFS=$'|' read login pass
do
  domain=$(echo ${login} | cut -d @ -f2)
  echo ${domain} >> /tmp/vhost.tmp
done < /tmp/docker-mailserver/postfix-accounts.cf
```
Could be written as: (_the PR should include a test case with comments in this file_)
(_**I've not tested this snippet**_)
```
grep -v "^\s*$\|^\s*\#" /tmp/docker-mailserver/postfix-accounts.cf | while IFS=$'|' read login pass
do
    domain=$(echo ${login} | cut -d @ -f2)
    echo ${domain} >> /tmp/vhost.tmp
done 
```


>  However, if we are to support comments in that file 

If comments in `postfix-accounts.cf` are going to be supported,  for consistency I would recommend supporting comments in any  `.cf` config file , indeed, `postfix-virtual.cf` is either not supporting comments.

**Comment by youtous** [comment]
Identified files to change:
-` generate-dkim-config `(L10, L19)
- `listalias` (filter comments)
- `listmailuser` (filter comments)
- `check-for-changes.sh` (`if [ -f /tmp/docker-mailserver/postfix-sasl-password.cf ]; then` L.93,105,168)
- `start-mailserver` (L. 943)
