### ISSUE TITLE
Support for TLS upgrade over smtp port (25) worth it ?

### ISSUE THREAD

**Issue by init-js** [tomav/docker-mailserver#1489]
Looking again at master.cf, I noticed that if TLS is enabled in my docker config,  then both submission (587) and smpts (465) require encryption (i.e. 587 will upgrade with STARTTLS and smtps starts in wrapper-mode from the get go). But it looks like the default server-to-server ports don't enable SSL or even allow the option.

Is there no benefit in allowing the server to receive mail on a TLS channel if the certificates are setup correctly?

## Context

Trying to harden the server.

## Expected Behavior

When receiving mail from other mail servers, connections should enable ssl if possible.

## Possible Fix

Just toggle `smtpd_tls_security_level = may` for the smtpd block in `master.cf`.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by erik-wramner** [comment]
I think this is already in place. Looking at the runtime settings of my server:

```
root@mail:/# postconf | grep tls_security_level
smtp_tls_security_level = may
smtpd_tls_security_level = may
```

And furthermore connecting to port 25 followed by STARTTLS works:

```
openssl s_client -connect localhost:25 -starttls smtp
```

Does this not work for you?

**Comment by init-js** [comment]
Ah you're absolutely correct. Apologies for the spurious alarm. I get the same.

The manual states that it should be OFF by default, which doesn't appear to be the case.

> _Enabling TLS in the Postfix SMTP server_
>
> By default, TLS is disabled in the Postfix SMTP server, so no difference to plain Postfix is visible. Explicitly switch it on with "smtpd_tls_security_level = may" (Postfix 2.3 and later) or "smtpd_use_tls = yes" (obsolete but still supported). 

from the [manual](http://postfix.cs.utah.edu/TLS_README.html)

**Comment by erik-wramner** [comment]
Great, I'll close this then.
