### ISSUE TITLE
Add X-Spam-Report header

### ISSUE THREAD

**Issue by ghnp5** [tomav/docker-mailserver#1492]
Hello,

Using Docker on CentOS 7.

I have the following headers being added to emails (as expected):

```
X-Spam-Flag: YES
X-Spam-Score: 5.401
X-Spam-Level: *****
X-Spam-Status: Yes, score=5.401 tagged_above=-999 required=5
	tests=[DKIM_SIGNED=0.1, DKIM_VALID=5, DKIM_VALID_AU=-0.1,
	DKIM_VALID_EF=-0.1, HTML_MESSAGE=0.001, KAM_NUMSUBJECT=0.5,
	SPF_PASS=-0.001, URIBL_BLOCKED=0.001] autolearn=no autolearn_force=no
```
(I'm forcing DKIM_VALID=5 intentionally - you can ignore that :-) )

However, I'd like to have this one added too:

```
X-Spam-Report: Spam detection software, running on the system "mail.domain.tld",
 has identified this incoming email as possible spam.  The original
 message has been attached to this so you can view it or label
 similar future email.  If you have any questions, see
 root\@localhost for details.
 Content analysis details:   (5.9 points, 5.0 required)
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
  0.8 KAM_COUK               Scoring .co.uk emails higher due to poor registry
                             security.
  0.0 FREEMAIL_FROM          Sender email is commonly abused enduser mail
                             provider
                             [email@domain.tld]
 -0.0 SPF_HELO_PASS          SPF: HELO matches SPF record
 -0.0 SPF_PASS               SPF: sender matches SPF record
  0.0 HTML_MESSAGE           BODY: HTML included in message
  5.0 DKIM_INVALID           DKIM-Signature header does not exist or is not
                             valid
  0.0 KAM_SHORT              Use of a URL Shortener for very short URL
```

But I seem to be totally unable to do this.

I've tried to add to SpamAssassin rules:

> report_safe 0
> add_header all Report \_REPORT\_

I've also added to amavis config (50-user):

> use strict;
> @local_domains_acl = ( [ '.domain1.com', '.domain2.com' ] );
> $sa_spam_report_header = 1;
> $allowed_added_header_fields{lc('X-Spam-Report')} = 1;
> 1;

But I'm still unable to get the X-Spam-Report header added!

Any ideas?

Thank you very much.

**Comment by aendeavor** [comment]
Sorry there wasn't much help to be found here. Any news on this?

**Comment by ghnp5** [comment]
Hello. Unfortunately not :(

**Comment by aendeavor** [comment]
It seems like we do not have the resources right now, sadly. I just refactored 2500 lines Bash and need to tend to something else now. I am very sorry, but the truth is: For the moment, it seems like you need to re-try / try it on your own.

I find your request reasonable. So, if you manage to get it working, please feel free to open  a PR :)

**Comment by ghnp5** [comment]
Thank you.
I'm not actively looking into resolving this, as I'm also very busy with other things and "I can live" without this feature.

However, whenever someone is able to resolve this, I'll be more than happy to know the solution :)
Have a great day.

**Comment by aendeavor** [comment]
Alright. Thanks for letting me know.

I will close this issue as `frozen`. Please, feel free to re-open it any time you feel like to have solved it or you deem it necessary.
