### ISSUE TITLE
Using without docker compose?

### ISSUE THREAD

**Issue by Merith-TK** [tomav/docker-mailserver#1493]
IS there a way to use this without docker-compose?
## Context
I use a control panel to manage my docker containers, [Portainter](https://www.portainer.io/)
and i need a way to do this without using docker-compose so that i can easily control the image

this is all i can use when i access my control panel. 
![image](https://user-images.githubusercontent.com/10422110/81017151-ab256200-8e16-11ea-857e-d97b58d951e5.png)

**Comment by erik-wramner** [comment]
It is certainly possible to use the image without docker-compose, you just need to do a lot more work on your own. Check the Makefile or the integration tests. There you have for example:

```
	docker run --rm -d --name mail \
		-v "`pwd`/test/config":/tmp/docker-mailserver \
		-v "`pwd`/test/test-files":/tmp/docker-mailserver-test:ro \
		-v "`pwd`/test/onedir":/var/mail-state \
		-v "`pwd`/test/config/user-patches/user-patches.sh":/tmp/docker-mailserver/user-patches.sh \
		-e ENABLE_CLAMAV=1 \
		-e SPOOF_PROTECTION=1 \
		-e ENABLE_SPAMASSASSIN=1 \
		-e REPORT_RECIPIENT=user1@localhost.localdomain \
		-e REPORT_SENDER=report1@mail.my-domain.com \
		-e SA_TAG=-5.0 \
		-e SA_TAG2=2.0 \
		-e SA_KILL=3.0 \
		-e SA_SPAM_SUBJECT="SPAM: " \
		-e VIRUSMAILS_DELETE_DELAY=7 \
		-e ENABLE_SRS=1 \
		-e SASL_PASSWD="external-domain.com username:password" \
		-e ENABLE_MANAGESIEVE=1 \
		--cap-add=SYS_PTRACE \
		-e PERMIT_DOCKER=host \
		-e DMS_DEBUG=0 \
		-h mail.my-domain.com -t $(NAME)
```

This is just an example, it is **NOT** the recommended use. However, based on the compose file and env file and these examples you should be able to come up with a docker command that launches the container with the options you want. Note that you must also configure networking or port forwarding, please see the official Docker documentation for details on that. The ports you need to forward are documented in the readme and in the compose file.

When you have the docker command it is probably possible to adapt it to your GUI, provided that the GUI supports all the needed options of course. Good luck!

**Comment by youtous** [comment]
For simplicity I would recommend you to use the Stack mode. It requires enabling docker-swarm (docker swarm on a single node is possible https://github.com/portainer/portainer/issues/2054#issuecomment-526056083). The library used by portainer for docker-compose is deprecated (see https://github.com/portainer/portainer/issues/3750).

This solution only works **if you don't need privileged modes options (required for fail2ban in docker-mailserver)**. For my part, I manage fail2ban on the host.

**Comment by Merith-TK** [comment]
> It is certainly possible to use the image without docker-compose, you just need to do a lot more work on your own. Check the Makefile or the integration tests. There you have for example:
>
>.... 
> 
> This is just an example, it is **NOT** the recommended use. However, based on the compose file and env file and these examples you should be able to come up with a docker command that launches the container with the options you want. Note that you must also configure networking or port forwarding, please see the official Docker documentation for details on that. The ports you need to forward are documented in the readme and in the compose file.
> 
> When you have the docker command it is probably possible to adapt it to your GUI, provided that the GUI supports all the needed options of course. Good luck!
IF I run it via command, portainer will beable to see it and then manage it. Will use my Dev server for testing. 


> For simplicity I would recommend you to use the Stack mode. It requires enabling docker-swarm (docker swarm on a single node is possible [portainer/portainer#2054 (comment)](https://github.com/portainer/portainer/issues/2054#issuecomment-526056083)). The library used by portainer for docker-compose is deprecated (see [portainer/portainer#3750](https://github.com/portainer/portainer/issues/3750)).
> 
> This solution only works **if you don't need privileged modes options (required for fail2ban in docker-mailserver)**. For my part, I manage fail2ban on the host.

I actually have two servers on the same network. I use main-server for the things I display to the clearnet and private data, Dev-server is used for testing, so a swarm config may or may not work for me, WI check it out.

**Comment by okainov** [comment]
>If i get it to show up in any listing via the docker command, i should beable to manage it from portainer

Even if container is run via `docker-compose`, it is still shown in all `docker` commands, you know that, right?

**Comment by erik-wramner** [comment]
@Merith-TK can we close this or do you have remaining questions?

**Comment by Merith-TK** [comment]
We can close this,
