### ISSUE TITLE
amavis pyzor terminated signal 15 on sending mail

### ISSUE THREAD

**Issue by mwlczk** [tomav/docker-mailserver#1500]
## Subject

* [x] I would like some feedback concerning a use case

## Description
I upgraded today (20200508 1000 GMT) to :latest
everything goes smooth but i see these messages about Amavis / pyzor terminating while sending (not receiving) mails. Is this anything to worry about?

May  8 10:45:09 mail amavis[1716]: (01716-04) ESMTP :10024 /var/lib/amavis/tmp/amavis-20200508T103122-01716-QbtagR1j: <some@mail> -> <some.other@mail> SIZE=13167 Received: from mail.server ([127.0.0.1]) by localhost (mail.server [127.0.0.1]) (amavisd-new, port 10024) with ESMTP for <some.other@mail>; Fri,  8 May 2020 10:45:09 +0000 (UTC)
May  8 10:45:09 mail amavis[1716]: (01716-04) Checking: tdZg5yjxsczq [so.me.ip.nr] <some@mail> -> <some.other@mail>
May  8 10:45:09 mail amavis[1716]: (01716-04) Open relay? Nonlocal recips but not originating: some.other@mail
May  8 10:45:09 mail amavis[1716]: (01716-04) p004 1 Content-Type: multipart/mixed
May  8 10:45:09 mail amavis[1716]: (01716-04) p005 1/1 Content-Type: multipart/related
May  8 10:45:09 mail amavis[1716]: (01716-04) p006 1/1/1 Content-Type: multipart/alternative
May  8 10:45:09 mail amavis[1716]: (01716-04) p001 1/1/1/1 Content-Type: text/plain, 7bit, size: 150, SHA1 digest: c8ea045ee5d8df47a8527f8e1a03f6b731e76f0d
May  8 10:45:09 mail amavis[1716]: (01716-04) p002 1/1/1/2 Content-Type: text/html, 7bit, size: 304, SHA1 digest: 27fc0f3f9a9168186ddd84e3d5d3723f8d903608
May  8 10:45:09 mail amavis[1716]: (01716-04) p003 1/1/2 Content-Type: application/octet-stream, 7bit, size: 5556, SHA1 digest: 308b063ccb464245fc5fc5ab06e172b9e188c8a4, name: keydata.asc
May  8 10:45:09 mail postfix/submission/smtpd[2737]: disconnect from unknown[so.me.ip.nr] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 noop=1 quit=1 commands=9
May  8 10:45:21 mail amavis[2755]: (01716-04) SA info: util: setuid: ruid=112 euid=112 rgid=114 114 egid=114 114 
May  8 10:45:25 mail amavis[1716]: (01716-04) SA info: pyzor: [2755] error: TERMINATED, signal 15 (000f)

**Comment by youtous** [comment]
Signal 15 `pyzor` is usually triggered when pyzor_timeout has been reached. It could be due to pyzor network downtime, or network issues.

Could you try http://know.mailsbestfriend.com/fixing_pyzor_error_terminated_signal_15-1072333902.shtml?

**Comment by erik-wramner** [comment]
@mwlczk can we close this? If not please get back with more information. Did you try @youtous suggestion?

**Comment by mwlczk** [comment]
I did not try this. But It might have been a hickup with local DNS giving timeouts on name resolution.
