### ISSUE TITLE
Daily cron error mail

### ISSUE THREAD

**Issue by Dubbeldrank** [tomav/docker-mailserver#1502]
I get a mail daily with this error with the following subject:

> Cron <root@mail> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )

And this as content:

> /etc/cron.daily/logrotate:
> invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.

Any idea how to fix this? Restarting the container or rebooting the host as a whole doesn't solve it.

**Comment by youtous** [comment]
Similar to https://github.com/tomav/docker-mailserver/issues/1465

Are you using the **latest** version.

**Comment by erik-wramner** [comment]
As @youtous says that error should have been fixed, I used to get it but for me it is gone. If you still get it with the latest version we need to know what options you have enabled so we can reproduce.

**Comment by Dubbeldrank** [comment]
I updated about 20 days ago, so i have 7.0.0

**Comment by erik-wramner** [comment]
There is no release yet, only "latest". I'll make a new numbered release this week if things are stable.
