### ISSUE TITLE
How to configure DMARC?

### ISSUE THREAD

**Issue by okainov** [tomav/docker-mailserver#1511]
## Subject

* [ x ] I would like to configure a not documented mail server use case

## Description

Seems like there is DMARC support, however no documentation how to configure it (if needed at all?). I'm quite a newbie in this things, so it would be really great either to have a wiki page explaining what to do or just a single-line statement somewhere in the main readme "dmarc is configured already, nothing to do for you"

**Comment by Dubbeldrank** [comment]
The server part should already been configured, you just need a TXT record in your DNS settings of your domain. A good way to start is by taking a look at this site which has a generator.

https://dmarc.globalcyberalliance.org/

**Comment by youtous** [comment]
A guide for DMARC: https://github.com/internetstandards/toolbox-wiki/blob/master/DMARC-how-to.md

**Comment by okainov** [comment]
Thanks @Dubbeldrank @youtous, I made it working, also created a wiki entry for dummies like myself :)

https://github.com/tomav/docker-mailserver/wiki/Configure-DMARC

**Comment by youtous** [comment]
Don't forget to test it! https://mecsa.jrc.ec.europa.eu/ ;)

**Comment by ofsahin** [comment]
hello,

i set up dmarc on my dns settings with my mail address but then i wondered if instead of my own mail address, should i have set dmarc mail as a predefined mail address if opendmarc in this docker image is parsing it?

any idea?
