### ISSUE TITLE
CLAMAV memory

### ISSUE THREAD

**Issue by edgeux** [tomav/docker-mailserver#1513]
im running the v7 mailserver on raspberry pi 4 on ubuntu 20.04. all seems fine except that using clamav increases the memory requirement by almost 1GB  ... does that sound about right to you?

**Comment by erik-wramner** [comment]
Yes unfortunately, see [FAQ](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#which-system-requirements-needs-my-container-to-run-docker-mailserver-effectively). ClamAV reads the virus database into memory and it is almost 1G.
