### ISSUE TITLE
beginner help needed: cannot start server

### ISSUE THREAD

**Issue by nattyluke** [tomav/docker-mailserver#1519]
## Situation
I'm trying to set up a mailserver on my virtual server with 2gb ram.
Lets say my domain is: example.com
I'm a beginner in the Mailserver topic. I set the MX Record to:
mail.example.com. (set a dot at the end)

So my .env file looks like this:
HOSTNAME=mail
DOMAINNAME=example.com
CONTAINER_NAME=mail

## Current Situation
`docker-compose up mail`
does output the following:
ERROR: for mail  Cannot start service mail: driver failed programming external connectivity on endpoint mail (0de6bf11eb65dddfba1c9991ee5f285785b23fa47a2be594fca0d670224aceb8): Error starting userland proxy:

Can you help me? Do I have to make other preparations, what am i missing? 
Thank You

**Comment by youtous** [comment]
> driver failed programming external connectivity on endpoint

This is a docker error indicating docker is not able to bind the ports.
See https://github.com/docker/compose/issues/3277

- Please check ports used on your system using `sudo netstat -nlp` (grep target ports).

If your ports are not already used by an other service, you can try to restart docker.

**Comment by erik-wramner** [comment]
If your host is running Windows then this is a very common problem with the Windows docker implementation. Restarting docker usually helps. In other cases it sounds more like a port conflict.

Please update the issue and close it if you find a solution or provide more information if not.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
