### ISSUE TITLE
Timeout with the port 25

### ISSUE THREAD

**Issue by rwanito** [tomav/docker-mailserver#1524]
Hi,

This is not a bug with docker mail server but a question ?
I'm using livebox by Orange as router. But, I've learned that Orange blocks the port 25. (No solution found... apart a relay from orange...)

 So I get :
`mail                    | May 25 20:40:11 mail postfix/smtp[52683]: connect to aspmx.l.google.com[74.125.140.27]:25: Connection timed out
mail                    | May 25 20:40:11 mail postfix/smtp[52683]: connect to aspmx.l.google.com[2a00:1450:400c:c00::1b]:25: Cannot assign requested address
mail                    | May 25 20:40:41 mail postfix/smtp[52683]: connect to alt1.aspmx.l.google.com[209.85.233.26]:25: Connection timed out
`

`
mail                    | May 25 20:44:41 mail postfix/qmgr[854]: 745372A6A57: from=<sender@mail.com>, size=1298, nrcpt=1 (queue active)
mail                    | May 25 20:44:41 mail postfix/qmgr[854]: C639D2A6A42: from=<sender@mail.com>, size=1245, nrcpt=1 (queue active)
mail                    | May 25 20:44:42 mail postfix/smtp[53710]: connect to aspmx.l.google.com[2a00:1450:400c:c00::1a]:25: Cannot assign requested address
mail                    | May 25 20:45:12 mail postfix/smtp[53710]: connect to aspmx.l.google.com[74.125.140.27]:25: Connection timed out
mail                    | May 25 20:45:12 mail postfix/smtp[53709]: connect to aspmx.l.google.com[74.125.71.27]:25: Connection timed out
mail                    | May 25 20:45:12 mail postfix/smtp[53709]: connect to aspmx.l.google.com[2a00:1450:400c:c08::1a]:25: Cannot assign requested address
mail                    | May 25 20:45:42 mail postfix/smtp[53710]: connect to alt2.aspmx.l.google.com[142.250.4.27]:25: Connection timed out
mail                    | May 25 20:45:42 mail postfix/smtp[53710]: connect to alt1.aspmx.l.google.com[2a00:1450:4010:c03::1a]:25: Cannot assign requested address
mail                    | May 25 20:45:42 mail postfix/smtp[53710]: connect to alt2.aspmx.l.google.com[2404:6800:4003:c06::1a]:25: Cannot assign requested address
mail                    | May 25 20:45:42 mail postfix/smtp[53709]: connect to alt2.aspmx.l.google.com[142.250.4.27]:25: Connection timed out
mail                    | May 25 20:45:42 mail postfix/smtp[53709]: connect to alt1.aspmx.l.google.com[2a00:1450:4010:c03::1a]:25: Cannot assign requested address
mail                    | May 25 20:45:42 mail postfix/smtp[53710]: C639D2A6A42: to=<receiver@mail.com>, relay=none, delay=15251, delays=15191/0.03/60/0, dsn=4.4.1, status=deferred (connect to alt2.aspmx.l.google.com[2404:6800:4003:c06::1a]:25: Cannot assign requested address)
mail                    | May 25 20:46:12 mail postfix/smtp[53709]: connect to alt1.aspmx.l.google.com[209.85.233.27]:25: Connection timed out
mail                    | May 25 20:46:12 mail postfix/smtp[53709]: 745372A6A57: to=<receiver@mail.com>, relay=none, delay=673, delays=582/0.04/90/0, dsn=4.4.1, status=deferred (connect to alt1.aspmx.l.google.com[209.85.233.27]:25: Connection timed out)
`

I would like to know why google use the port 25 ?
In my mail settings in my client I've specified starttls with port 587 not 25 ?
Is google needs to go on the port 25 ?

There is any solution to avoid this ? Keep right port ?

Thanks !

**Comment by erik-wramner** [comment]
The ports have different roles. It is covered in the readme and wiki I believe, but in short port 25 is typically used when one mail server delivers mail to another mail server. Port 587 is used when a client submits mail to a server for delivery locally or remotely.

In other words when I send an e-mail from my client it connects to my server on port 587. My server accepts the mail and if it is to a Google user it will connect to the Google mail server on port 25 to make the delivery.

It is possible to run a mail server without access to port 25, but then you basically need to cooperate with another mail server that relays your messages. Your server can connect to the other server and ask it to deliver your messages. It acts as a relay for you. I don't have any experience with that myself and unless your volume is quite low it will probably not be free.

**Comment by rwanito** [comment]
Ok, big thanks to you for your reply !
You completly answered to my question.

I will find a little VPS to store my email server. It's the only one solution I think !

If I found a solution to bypass Orange, I tell you !
Thanks !
