### ISSUE TITLE
Allow for auth_bind LDAP authentication (here: Dovecot)

### ISSUE THREAD

**Issue by guardiande** [tomav/docker-mailserver#1526]
## Is your feature request related to a problem?
Currently it is not possible to allow for `auth_bind` authentication for Dovecot by simple container configuration.

## Describe the solution you'd like
For security reasons (https://wiki.dovecot.org/AuthDatabase/LDAP/AuthBinds) it is recommended to use BIND authentication against the LDAP server.

I think that configomat should allow for easy implementation of that feature.

## Alternatives you've considered
Going with the password lookup. It works for most people (but then I think Active Directory does not allow password lookups).

## Who will that feature be useful to?
All users looking into more secure setup and maybe AD users.

## What have you done already?
I just started into implementing a container based mail setup and I'm in progress of evaluating the available options. So I did not yet implement this solution.

## What are you going to contribute?
I'm neither an export on Dovecot nor LDAP. But of course I'll do the testing.

**Comment by aendeavor** [comment]
What's the current status here @guardiande ?

**Comment by guardiande** [comment]
@aendeavor Should be fixed by #1557.
