### ISSUE TITLE
Cron: Cannot make/remove an entry for the specified session

### ISSUE THREAD

**Issue by casperklein** [tomav/docker-mailserver#1528]
## Problem

I saw the following cron errors in my configured daily Logwatch mails:

    --------------------- Cron Begin ------------------------ 
    
     **Unmatched Entries**
     Jun  3 00:18:01 mail CRON[30693]: Cannot make/remove an entry for the specified session
     Jun  3 03:18:01 mail CRON[7001]: Cannot make/remove an entry for the specified session
     Jun  3 06:18:01 mail CRON[15603]: Cannot make/remove an entry for the specified session
     Jun  3 09:18:01 mail CRON[24652]: Cannot make/remove an entry for the specified session
     Jun  3 12:18:01 mail CRON[842]: Cannot make/remove an entry for the specified session
     Jun  3 15:18:01 mail CRON[9785]: Cannot make/remove an entry for the specified session
     Jun  3 18:18:01 mail CRON[18698]: Cannot make/remove an entry for the specified session
     Jun  3 21:18:01 mail CRON[27279]: Cannot make/remove an entry for the specified session
     
    ---------------------- Cron End -------------------------

    --------------------- Connections (secure-log) Begin ------------------------ 
   
    
    **Unmatched Entries**
       CRON: pam_loginuid(cron:session): Error writing /proc/self/loginuid: Operation not permitted: 1 Time(s)
       CRON: pam_loginuid(cron:session): set_loginuid failed: 1 Time(s)
    
    ---------------------- Connections (secure-log) End ------------------------- 

I could not identify any negative impact by this, beside the error messages.

Looking for that error I found:

* https://stackoverflow.com/questions/43323754/cannot-make-remove-an-entry-for-the-specified-session-cron
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=726661
* https://stackoverflow.com/questions/21391142/why-is-it-needed-to-set-pam-loginuid-to-its-optional-value-with-docker

## Possible fix

I commented out the following line in `/etc/pam.d/cron`:

    session    required     pam_loginuid.so

After restarting cron with `supervisorctl restart cron` the error messages are gone.

## Questions

Can someone confirm theses errors? `grep Cannot /var/log/syslog`
Is it safe to uncomment that line?

**Comment by casperklein** [comment]
I've recreated the container in the meantime, which also wiped my "fix". Since then however, it did not happen again. I am still wondering what triggered it.

**Comment by erik-wramner** [comment]
Shall we close and reopen if you can reproduce it, perhaps?

**Comment by casperklein** [comment]
I still get this cron errors. After a container start, it randomly takes some hours or days for the first message to appear. But sooner or later they start appearing and then onwards in a 3h rhythm.

Anyone else experiencing the same?

**Comment by erik-wramner** [comment]
I haven't seen it. It would be nice if you could add some debugging to isolate the root cause. Plus it could depend on your environment, what kind of host do you have? Are you using any specific security options in your compose file?

As far as I can tell it should be safe for us to disable pam_loginuid, but I'm not an expert. I'd rather leave it in place in the container if you are the only one getting this.

**Comment by casperklein** [comment]
I found out, that the errors are triggert by ``/etc/cron.d/amavisd-new`` which runs every 3 hours:

    18 */3  * * *   amavis  test -e /usr/sbin/amavisd-new-cronjob && /usr/sbin/amavisd-new-cronjob sa-sync

If I change the `amavis` user to e.g. `root` no error is produced. However, the script needs to be run as `amavis`.

I don't understand, why it works flawless after container start and at a random time, it starts failing (forever). Restarting the container or disabling `pam_loginuid` fixed it.

>I'd rather leave it in place in the container if you are the only one getting this.

Yes. I really like to find out the root cause for that, instead of disabling something that seems to work for everyone else.

**Comment by casperklein** [comment]
As this didn't happen again for a while now, I am closing this.
