### ISSUE TITLE
I would like to use docker-mailserver as local delivery server only

### ISSUE THREAD

**Issue by adamchabin** [tomav/docker-mailserver#1529]
## Is your feature request related to a problem?
Yes. I would like to use docker-mailserver as local delivery server only.

## Describe the solution you'd like
I would like to setup one or more local email domains like: localhost.locadomain and few email accounts like noreply@localhost.locadomain, user1@localhost.locadomain, user2@localhost.locadomain. Next I would like to send emails from one user to another WITHOUT ability to deliver mail to any "real" internet domain (like google.com etc).

## Who will that feature be useful to?
Feature will be useful to one who needs to setup email server for testing purposes and want to be sure that no email will be send to domain not configured in docker-mailserver.

## What have you done already?
I've tried to configure pure postfix with:
default_transport = error
relay_transport = error

but I need also IMAP etc.

## What are you going to contribute?
Yes, I can help with that.

## Additional context
None.

**Comment by erik-wramner** [comment]
Sorry for slow response. For a development server like that I wouldn't trust the configuration, I would firewall it. No Internet connection (or at least no port 25), no outbound messages. Simple as that.
