### ISSUE TITLE
The script setup.sh have «relay» function, but not in the documentation

### ISSUE THREAD

**Issue by pleer-video** [tomav/docker-mailserver#1530]
Hello.
What does this function do?

```
  relay:

    ./setup.sh relay add-domain <domain> <host> [<port>]
    ./setup.sh relay add-auth <domain> <username> [<password>]
    ./setup.sh relay exclude-domain <domain>

```

Not info: https://github.com/tomav/docker-mailserver/wiki/Setup-docker-mailserver-using-the-script-setup.sh

**Comment by casperklein** [comment]
There is a wiki page about it: https://github.com/tomav/docker-mailserver/wiki/Configure-Relay-Hosts
