### ISSUE TITLE
newbie DNS question

### ISSUE THREAD

**Issue by lonnietc** [tomav/docker-mailserver#1531]
Hello,

I am a newbie trying to set up a smtp server in a docker container that I can run on my server and have been able to follow all of the steps up until the last part where I "paste" the contents into a DNS record.

past the content of config/opendkim/keys/domain.tld/mail.txt in your domain.tld.hosts zone

I have a domain name setup at Godaddy and can access my DNS records, but am not sure what parts of the mail.txt goes where.

the "mail.txt" files has 3 main lines:

mail._domainkey IN      TXT     ( "v=DKIM1; h=sha256; k=rsa; "
and two long RSA signature keys

My Godaddy DNS records allow for me to choose a

Type:  TXT
Host:  ????
TXT Value: ????

Which parts of the mail.txt go in the "Host" and "TXT Value" fields?

Thanks in advance

**Comment by casperklein** [comment]
Host: `mail._domainkey`
TXT: the three lines from mail.txt

PS: Setting up DKIM is optional and not necessary for sending/receiving e-mails.

**Comment by erik-wramner** [comment]
@lonnietc did it work so we can close?

**Comment by lonnietc** [comment]
Thanks for the info on this and we can close now.
