### ISSUE TITLE
vhost only shows tld

### ISSUE THREAD

**Issue by codejamninja** [tomav/docker-mailserver#1532]
My vhost file only shows the tld. Is this correct?

```sh
cat /etc/postfix/vhost
-> co
```

My hostname looks like the following . . .
```sh
hostname
-> mailserver5-mailserver-mailserver-5bf6b7778f-6bmr4
```

The following environment variables are set . . .

| Env | Value |
| ---    | ---      |
| `OVERRIDE_HOSTNAME` | `siliconhills.co` |
| `SRS_DOMAINNAME` | `siliconhills.co` |

I have an MX record pointing to `mail.siliconhills.co`.
I have a certificate for `mail.siliconhills.co`.
My docker image is running on `mail.siliconhills.co`.

Is this setup correct?

**Comment by m-a-v** [comment]
```
# => Specify a fully-qualified domainname to serve mail for.  This is used for many of the config features so if you can't set your hostname (e.g. you're in a container platform that doesn't let you) specify it in this environment variable.
OVERRIDE_HOSTNAME=
```

Shouldn't it be something like `mail.siliconhills.co` ?

**Comment by codejamninja** [comment]
Ah, ok thanks. You answered another question I just published.

https://github.com/tomav/docker-mailserver/issues/1533

**Comment by erik-wramner** [comment]
Does that mean this is OK so we can close?

**Comment by codejamninja** [comment]
Yes, this can be closed.
