### ISSUE TITLE
NO [UNAVAILABLE] Temporary authentication failure.

### ISSUE THREAD

**Issue by codejamninja** [tomav/docker-mailserver#1534]
I am getting the following error when trying to authenticate with dovecot over telnet.

```
. LOGIN user pass
```
```
. NO [UNAVAILABLE] Temporary authentication failure. [mailserver5-mailserver-mailserver-665c6b4bfd-7qsr6:2020-06-11 13:56:19]
```

The server gives me the following logs.
```
Jun 11 13:56:54 mailserver5-mailserver-mailserver-665c6b4bfd-7qsr6 dovecot: auth: Error: LDAP: binding failed (dn cn=admin,dc=siliconhills,dc=dev): Invalid credentials
```

I am using an LDAP connection. SMTP authentication works fine.

I am using the Postfix Book Schema.

I have the following environment variables set.

```sh
export DOVECOT_USER_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
export DOVECOT_PASS_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
```

I left `DOVECOT_USER_ATTRS` and `DOVECOT_PASS_ATTRS` empty.

My LDAP server (openldap) gives me the following log.
```
5ee23922 conn=1218 fd=15 ACCEPT from IP=10.42.5.26:35440 (IP=0.0.0.0:389)
5ee23922 conn=1218 op=0 BIND dn="cn=admin,dc=siliconhills,dc=dev" method=128
5ee23922 conn=1218 op=0 RESULT tag=97 err=49 text=
5ee23922 conn=1218 op=1 UNBIND
5ee23922 conn=1218 fd=15 closed
```

**Comment by erik-wramner** [comment]
I'm not using LDAP, so I don't know. You have checked the wiki? I'll flag it help wanted.

**Comment by aendeavor** [comment]
Any news on this?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
