### ISSUE TITLE
System error: exec: "generate-user-databases": executable file not found in $PATH

### ISSUE THREAD

**Issue by t94j0** [tomav/docker-mailserver#154]
I'm using v1 because I wasn't able to get v2 to work. When I try to create an account, it fails giving this error: `System error: exec: "generate-user-databases": executable file not found in $PATH`

**Comment by tomav** [comment]
````
➜  docker-mailserver git:(v2) ✗ docker run --rm tvial/docker-mailserver:latest which generate-user-databases
/usr/local/bin/generate-user-databases
➜  docker-mailserver git:(v2) ✗ docker run --rm tvial/docker-mailserver:latest echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tvial/Applications
```

**Comment by tomav** [comment]
@t94j0 please provide more information on version used, configuration.
If we're blind, we can't help you.
Thank you.
