### ISSUE TITLE
[Question] Contributing to the documentation

### ISSUE THREAD

**Issue by wernerfred** [tomav/docker-mailserver#1540]
## Subject

* [x] I would like to contribute to the project (code, documentation, advocacy, integration, ...)

## Description

First of all, insane job on the "new" wiki sites/structure, especially the "Mailserver 101" (mostly thanks to you @chikamichi i think).

Now my question:
I would like to contribute to the documentation and describe some use cases that are not listed right now (e.g. create alias with multiple recipients) or update some hints (fail2ban commands from debugging also in fail2ban or at least mentioned).
How is the procedure here? As far as i see i can simply edit the wiki pages. Is it desired that i open an issue for that changes to be approved?

Keep up the good work.
Cheers!

**Comment by erik-wramner** [comment]
I haven't seen any rules about who can edit the wiki, so just make sure that you know what you are doing (test first!). You don't need to open issues. Thanks for helping!
