### ISSUE TITLE
SpamAssassin reports DKIM invalid when email contains attachment

### ISSUE THREAD

**Issue by ghnp5** [tomav/docker-mailserver#1541]
Hello,

I've been noticing that pretty much every email that contains an attachment, even if coming from @outlook.com or @gmail.com, for example, is marked with DKIM invalid.

The emails are 100% legit, because I reply to them and receive a reply. And, the emails without attachment are marked as DKIM valid.

I'm just wondering... could this be a problem with my setup? A bug with docker-mailserver? Or, a problem with SpamAssassin or OpenDKIM?

Thanks!

**Comment by m-a-v** [comment]
How are you validating the DKIM?

I noticed something similar. When I send an email with attachement from a Google Account via Thunderbird, the Thunderbird plugin for DKIM validation shows an error. If I send the email directly via Google Webservice, then I don't get an error. Within the e-mail, both e-mails have dkim=pass.

**Comment by nunoperalta** [comment]
I was mentioning about received emails, not sent by me. Most of emails I send are through AWS SES, so I hope they work fine.

I use the Mail::SpamAssassin::Plugin::DKIM extension of SpamAssassin, which adds DKIM_INVALID & DKIM_SIGNED to the X-Spam-Status header.



```
  header	__DKIM_EXISTS	exists:DKIM-Signature
  
  meta	   DKIM_INVALID	!__DKIM_EXISTS || !DKIM_VALID
  describe DKIM_INVALID	DKIM-Signature header does not exist or is not valid
  score    DKIM_INVALID 5.0
```

**Comment by nunoperalta** [comment]
I was mentioning about received emails, not sent by me. Most of emails I send are through AWS SES, so I hope they work fine.

I use the Mail::SpamAssassin::Plugin::DKIM extension of SpamAssassin, which adds DKIM_INVALID & DKIM_SIGNED to the X-Spam-Status header.



```
  header	__DKIM_EXISTS	exists:DKIM-Signature
  
  meta	   DKIM_INVALID	!__DKIM_EXISTS || !DKIM_VALID
  describe DKIM_INVALID	DKIM-Signature header does not exist or is not valid
  score    DKIM_INVALID 5.0
```


And the emails do have DKIM header, but SpamAssassin sees them as invalid:

```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=outlook.com;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
...
```

**Comment by m-a-v** [comment]
I also mentioned the received emails that were not sent by the Docker mail server.

**Comment by ghnp5** [comment]
I was mentioning about received emails, not sent by me. Most of emails I send are through AWS SES, so I hope they work fine.

I use the Mail::SpamAssassin::Plugin::DKIM extension of SpamAssassin, which adds DKIM_INVALID & DKIM_SIGNED to the X-Spam-Status header.



```
  header	__DKIM_EXISTS	exists:DKIM-Signature
  
  meta	   DKIM_INVALID	!__DKIM_EXISTS || !DKIM_VALID
  describe DKIM_INVALID	DKIM-Signature header does not exist or is not valid
  score    DKIM_INVALID 5.0
```


And the emails do have DKIM header, but SpamAssassin sees them as invalid:

```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=outlook.com;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
...
```

```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:references:in-reply-to:from:date:message-id:subject:to;
...
```

**Comment by ghnp5** [comment]
> I also mentioned the received emails that were not sent by the Docker mail server.

Oh ok. I see.
It is not Thunderbird that generates the DKIM headers - it's Gmail/Outlook themselves.
So this does seem like a bug with SpamAssassin, as I doubt both Gmail and Outlook would be generating invalid DKIMs when emails have attachments.

**Comment by m-a-v** [comment]
>It is not Thunderbird that generates the DKIM headers - it's Gmail/Outlook themselves.
That's obvious. 

I use a DKIM verifier plugin for Thunderbird (https://addons.thunderbird.net/de/thunderbird/addon/dkim-verifier). Probably SpamAssassin and this plugin are not able to check the DKIM correctly ...

**Comment by m-a-v** [comment]
Perhaps there is a correlation with ARC (https://en.wikipedia.org/wiki/Authenticated_Received_Chain)?

**Comment by ghnp5** [comment]
Thank you very much.
(sorry for the many dup messages above - I obviously completely messed up here, doing a number of different tasks simultaneously)

I submitted a report in SpamAssassin: https://bz.apache.org/SpamAssassin/show_bug.cgi?id=7827


Unfortunately I'm not aware of ARC. Is there anything I can check in logs or so?

**Comment by m-a-v** [comment]
I do not know enough about the subject. It was just a wild guess with the ARC.

**Comment by ghnp5** [comment]
Bug marked as invalid with following response:


> 1. This cannot be considered a SpamAssassin bug unless you have some other
> trustworthy DKIM signature verifier which validates a signed message that SA
> deems invalid.
> 
> 2. Mail systems routinely make harmless changes to email which break DKIM
> signatures. This can include an encoding change that may be necessary to
> transport a binary attachment over Internet email. 
> 
> 3. It is literally impossible to diagnose your problem without a specific
> UNMODIFIED complete example. 
> 
> 4. This is the sort of probable non-bug problem which should be better
> addressed on the SpamAssassin Users mailing list. 
> 
> 5. Redefining & rescoring DKIM_INVALID as you have done is deeply unwise. The
> definition in the default ruleset only hits on signed messages whose signature
> does not validate and it is scored at 0.1 because of the common problem of DKIM
> signatures breaking in transit. Marking every unsigned email and every signed
> email with a broken signature as spam (i.e. with a 5.0 score as your rule does)
> is a choice to intentionally mislabel mail.
