### ISSUE TITLE
XX.XX.XX.XX.list.dnswl.org: Host or domain name not found

### ISSUE THREAD

**Issue by ghnp5** [tomav/docker-mailserver#1542]
Hello,

I have several of these warnings in "mail.warn" log:

```
Jun 14 08:53:43 server postfix/dnsblog[27951]: warning: dnsblog_query: lookup error for DNS query 4.3.2.1.list.dnswl.org: Host or domain name not found. Name service error for name=4.3.2.1.list.dnswl.org type=A: Host not found, try again
Jun 14 08:58:49 server postfix/dnsblog[29690]: warning: dnsblog_query: lookup error for DNS query 9.8.7.6.list.dnswl.org: Host or domain name not found. Name service error for name=9.8.7.6.list.dnswl.org type=A: Host not found, try again
```

Do you know where these come from?
There are many IPs - I suppose they are the IPs of the senders.
However, I'm not sure if it's correct that it's trying so many DNS lookups like these, as obviously all of them are failing.

**Comment by m-a-v** [comment]
https://github.com/tomav/docker-mailserver/issues/948

**Comment by m-a-v** [comment]
dnswl.org is actually a white list. Therefore the score for the `postscreen_dnsbl_sites` is negative.

The warning message `Host or domain name not found` could be a valid output for a mail server which is not listed on the DNS white list.

The response for a `nslookup` query is different depending on the DNS. When using Google DNS (e.g. 8.8.8.8) the return value is `REFUSED`. When using `1.1.1.1` the return value is `SERVFAIL`. Only 9.9.9.9 seems to work. It returns a return value of `NXDOMAIN` (non-existent domain).

The question is if it is possible to suppress this warning messages in case of a return value with `NXDOMAIN`?

**Comment by m-a-v** [comment]
@ghnp5 Probably we should reopen this question?

**Comment by ghnp5** [comment]
The warnings seemed to have disappeared when I changed DNS to 1.1.1.1, but I see they're still happening, now that I looked again.

I never heard about 9.9.9.9. Is this a DNS server I can trust?

Happy to re-open this issue, if you think something can be done to improve this... :)

**Comment by m-a-v** [comment]
You can find more information about Quad9 here: https://en.wikipedia.org/wiki/Quad9

I hope someone else can help :-)

**Comment by ghnp5** [comment]
Hey,

This is how you override the DNS server, right?

    env_file:
    - .env
    - env-mailserver
    dns: 9.9.9.9
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE


I had tried with 1.1.1.1 and now 9.9.9.9,
restarted the mailserver (with "docker-compose stop; docker-compose up -d"),
but I'm still getting the same warnings...

Any ideas? :)

**Comment by m-a-v** [comment]
Not all mail servers are on the white list from dnswl.org! So NXDOMAIN this is a valid output.

**Comment by ghnp5** [comment]
Oh ok! I think I understand now.
This is an expected warning, then. I see.

And you were asking whether we should suppress the messages... I'd say so, just to reduce the noise (since it IS expected for this to happen).

Please note I'm not seeing "NXDOMAIN" anywhere, even with the config to 9.9.9.9.
I still see "Host or domain name not found." as I saw seeing before.
(not sure if the warning message was supposed to change)

Thanks!

**Comment by m-a-v** [comment]
As I've written above you get the return value when using `nslookup`. In the warning message I also can't see the detailed return value in the warning message.

**Comment by nunoperalta** [comment]
Thank you very much for the clarification.
Have a good day.

**Comment by ghnp5** [comment]
Thank you very much for the clarification.
Have a good day.

**Comment by erik-wramner** [comment]
Can this be closed?

**Comment by m-a-v** [comment]
I am not sure. Is there a way to filter the false negative results? If yes, this would be great. Otherwise the warning logs could confuse (new) users.

**Comment by erik-wramner** [comment]
First I would not advocate the use of a public DNS. In my view the best option would be to have a local caching DNS that is called. It can then call one of the public DNS servers, but since it is under your control you know what it will return in each case plus you won't get errors when you send queries too often.

Second about the warnings, feel free to see if you can come up with something, but just suppressing them seems wrong to me. Upstream (postfix/dnsblog) obviously thinks it is worth logging them, so even if they can be ignored in your case they may perhaps be valuable in another situation? You could also create an issue in upstream and ask how they think this should be handled. If it gets fixed in upstream we will get it as well.

**Comment by m-a-v** [comment]
Sure, best is to use a local caching DNS. I just wanted to show with a comprehensible example that the return value is different depending on the provided DNS server for the `nslookup` call, but the warning in the logs is identical.

Perhaps it is difficult to suppress these warnings. And yes, perhaps it should be left as it is. 

I think it's just important to know that certain warnings are valid with dns_blog and do not necessarily indicate an error. Maybe this issue will help some people to understand this.

If no one else has better ideas, that can be closed.
