### ISSUE TITLE
Dockerhub image for release-v7.0.1

### ISSUE THREAD

**Issue by george-angel** [tomav/docker-mailserver#1543]
It has been almost 30 days since the release-v7.0.1 was tagged, but there is no image at https://hub.docker.com/r/tvial/docker-mailserver/tags

Usually images follow releases pretty quickly. Has this process changed?

Thank you

**Comment by erik-wramner** [comment]
Not that I know, but I don't have access to that part. @fbartels do you know?

**Comment by megawebmaster** [comment]
As the image is already up I think this issue should be closed, right?
