### ISSUE TITLE
Every night at 4:00 AM I'm getting error mail about virus-wiper

### ISSUE THREAD

**Issue by JYPDWhite** [tomav/docker-mailserver#1545]
Since I setup this server I get an error mail on 4:00 AM about virus-wiper which fails to run.

## Context
```
The mail have this content:
find: invalid argument `+' to `-mtime'
Try 'find --help' for more information.
```

### *What* is affected by this bug?
I see nothing apparently not working.

### *When* does this occur?
Every night at 4:00.

## *How* do we replicate the issue?
I can't really reproduce because all the other server running a mailserver are not showing this behavior. I'm on the :stable tag from docker hub.

## Your Environment

* Amount of RAM available: 6GB
* Mailserver version used: tvial/docker-mailserver:stable
* Docker version used: Docker version 19.03.8, build afacb8b7f0
* Environment settings relevant to the config: I don't really know which environment variables should affect this.

**Comment by casperklein** [comment]
`/usr/local/bin/virus-wiper` is called at 4am by cron:

    find /var/lib/amavis/virusmails/ -type f -mtime +$VIRUSMAILS_DELETE_DELAY -delete

I guess, the variable `$VIRUSMAILS_DELETE_DELAY` is not properly set. The default value should be `7`.

**Comment by JYPDWhite** [comment]
this is the part of the .env file
```
# Set how many days a virusmail will stay on the server before being deleted
# empty => 7 days
VIRUSMAILS_DELETE_DELAY= 30
```
I now removed the whitespace between = and 30. Thanks for your hint. I will report if this was the error

**Comment by casperklein** [comment]
Don't forget to restart the container.

**Comment by JYPDWhite** [comment]
I did it already ;-), but thanks for the remember

**Comment by JYPDWhite** [comment]
Okay the error was indeed the whitespace between = and 30. Thanks for your support @casperklein
