### ISSUE TITLE
Remove Spamcop from the list of Blacklists which should be queried.

### ISSUE THREAD

**Issue by JYPDWhite** [tomav/docker-mailserver#1548]
## Howto remove Spamcop from the list of blacklists which are used? Or how to add a sender domain to a never reject list?

* [X] I would like to configure a not documented mail server use case

## Description
I have the setup running for a while now. And some users often fails to send e-mails to my users (they are sending from t-online.de which is sometimes listed on Spamcop). So I want to remove Spamcop or set the sender domain @t-online.de to a whitelist. So that emails from this domain are not getting rejected (or get a negative SpamAssasin score to begin with, so that this e-mails are not getting marked as Spam so likely)
Thanks for your support in advance.

**Comment by casperklein** [comment]
Take a look at: https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration

Try something like this in config/postfix-main.cf:

    # 'reject_rbl_client bl.spamcop.net' removed
    smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by JYPDWhite** [comment]
> Take a look at: https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration
> 
> Try something like this in config/postfix-main.cf:
> 
> ```
> # 'reject_rbl_client bl.spamcop.net' removed
> smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org
> ```

Thats indeed the correct solution, thanks for the hint and sry for the really late response.
