### ISSUE TITLE
Enabling submission on port 465 with implicit TLS

### ISSUE THREAD

**Issue by F0Xde** [tomav/docker-mailserver#1552]
## Subject
* [x] I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description
I just started setting up the mailserver, so this will probably be a stupid newbie question, but I somehow couldn't find the right information.

As far as I understood using port 465 as a submission port with implicit TLS is regarded the "best" and recommended way for submission as of [RFC 8314](https://tools.ietf.org/html/rfc8314), but the wiki also states that 
> It does not enable Implicit TLS Outward Submission on port 465 by default. One may enable it through simple custom configuration, either as a replacement or (better!) supplementary mean of secure Submission.

So I am wondering, what do I specifically have to configure to enable submission on port 465? Or is there a drawback to doing so and I should stick with STARTTLS on port 587?

**Comment by casperklein** [comment]
There is nothing special you have to configure for the submission port 465. Just make that port available for the clients.
I am not aware of any drawback. Personally I would use 465 over 587 with STARTTLS.
