### ISSUE TITLE
How to migrate all my emails from cpanel to docker-mailserver

### ISSUE THREAD

**Issue by blueray453** [tomav/docker-mailserver#1554]
## Subject

* [x] I would like some feedback concerning a use case

## Description

I decided to change my hosting provider.

When I asked the prospective providers to transfer my emails, they said and I quote -

> We offer free data migration service if you are using cPanel control panel with your current hosting company (most companies use cPanel, such as GoDaddy/HostGator/etc) and are planning to purchase any of our cPanel packages (Linux Shared, VPS/Cloud with cPanel control panel).

I have CPanel in my current hosting, however I am feeling a little locked down as the prospective provider is saying that I must have CPanel. 

Now, I want to migrate all my cpanel email to docker-mailserver (installed in a VPS). How can I do that?

**Comment by erik-wramner** [comment]
I don't think there is an easy answer. As far as I know cPanel is just an administration console; there can most likely be different types of setups behind it?

This project primarily uses the standard Maildir format for e-mail. In addition we use configuration files for e-mail accounts and aliases and such. To migrate you will need to get your existing e-mails in Maildir format. You will have to create configuration files for your existing users and create the container; then you need to copy the Maildir files into the container volume.

I don't believe they can help you with this out of the box, but one never knows. Good luck!

**Comment by casperklein** [comment]
Given you use IMAP, why don't you just use an email program of your choice and export the mails to your local computer. Then configure the new IMAP account and upload the mails you've exported before. That should work I think, however I don't use IMAP myself - so no guarantee ;-)

**Comment by erik-wramner** [comment]
Copying messages with IMAP should work well for a single account, but is messy if you need to migrate an entire server.

**Comment by m-a-v** [comment]
Probably, imapsync could be a solution for your problem. I've used it when I migrated years ago to dovecot.

https://github.com/imapsync/imapsync

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
