### ISSUE TITLE
How To Add Web Interface 

### ISSUE THREAD

**Issue by zackprod** [tomav/docker-mailserver#1555]
I want to Add A web interface

**Comment by erik-wramner** [comment]
That has been asked many times. You probably want to use another mail server project for that. The goal for this project is:

> A fullstack but simple mail server (smtp, imap, antispam, antivirus...). Only configuration files, no SQL database

It would be possible to add a web interface as a separate container that updates the configuration files in a shared volume, but not optimal and you would have to write it. All the existing user interfaces that I have seen assume that there is a database.

Now, that is if you are talking about a web interface for _administration_. If you want to have a web interface for reading mail then you can for example use RoundCube in a separate container and point it to docker-mailserver. That works quite well.

**Comment by aendeavor** [comment]
@zackprod You can use [RoundCube Docker](https://github.com/roundcube/roundcubemail-docker) for that. You don't need to configure a database, just the IMAP and SMTP server.
