### ISSUE TITLE
Document Azure stealth blocking port 25

### ISSUE THREAD

**Issue by VictorKoenders** [tomav/docker-mailserver#1556]
When trying to run docker-mailserver on azure, I found out that azure has a hidden block on port 25 for all VMs.
https://docs.microsoft.com/en-us/azure/virtual-network/troubleshoot-outbound-smtp-connectivity

This can be solved by opening a Ticket:
```
To make a request, open a support case by using the following issue type:
Technical > Virtual Network > Connectivity > Cannot send email (SMTP/Port 25).
```

In my case, the system automatically enabled all traffic on port 25, before the ticket was submitted to their system. After stopping and starting the VM (not restarting, that doesn't work), the traffic on port 25 worked and I could send emails.

Thanks for this project and all the effort you have put into this!

**Comment by erik-wramner** [comment]
Thanks, that is useful. Perhaps you can add it to the wiki?

**Comment by VictorKoenders** [comment]
Added it to the wiki: https://github.com/tomav/docker-mailserver/wiki/Debugging

I'm actually surprised I can edit that without permissions

**Comment by erik-wramner** [comment]
Thanks, looks good. So far the open Wiki has worked well, there have been no vandalism that I know of (fingers crossed!).
