### ISSUE TITLE
HowTo migrate mailboxes from bare metal postfix/dovecot server?

### ISSUE THREAD

**Issue by salderma** [tomav/docker-mailserver#1561]
## Subject

* [ x ] I would like some feedback concerning a use case

## Description

Hi, I am evaluating using this container project for "refreshing" my "friends and family" mailserver.  I'm currently running on CentOS 6, using postfix, dovecot (IMAP only), clam, amavis, spamassassin, TLS with an public SSL cert (not letsencrypt), but it's all tied together with mysql.  I'm not running sieve, opendmarc, or opendkim, but am interested to have those features, as well as running on a modern platform like docker.

The server's been functioning around 9-10 years, we've got about 10GB of mail in /var/mail/virtual, and I'm very interested to get off this bare-metal and into a more modern solution.

I'd like to get an idea of how I might migrate my users mailboxes, aliases and such into this container platform to make the transition as seamless as possible.

P.S.   On a side note, I would also be interested to know how people might be deploying this in a public way...e.g. I was thinking about using a digital ocean droplet, perhaps CentOS 8 with tight hardening (selinux, auditd, etc.), but am looking for opinions from experience ppl that might use this container system.  Thanks!

**Comment by erik-wramner** [comment]
I've migrated two setups from bare metal CentOS 7. Moving the mailboxes was just a matter of copying files and fixing ownership/permissions. You will probably have to setup the user accounts and aliases manually. That can be a chore, depending on how many you have, but hopefully not that bad.

As for hosting there are many options, not sure if I can recommend one in particular over the others. CentOS 8 probably means podman rather than docker, which is cool and should work, but not as mainstream. That is always risky.

Good luck!

**Comment by salderma** [comment]
@erik-wramner thanks for the reply.  I'm looking toward CentOS 8, despite the issues with docker (which can be worked around) because I'm a fan of tight selinux and auditd policies on internet facing systems.  I don't have enough experience with that stuff on debian/ubuntu to have a solid comfort level.

Can you speak to the ownership/permissions issue?  I assume you mean UID/GID deviations between the old server and volume mounted to the container.  All mailboxes on the current system reside under `/var/mail/virtual/<domain>` and are owned/grouped to a username specified in `/etc/dovecot/conf.d/10-master.conf`.  Does this container do similar, and I just have to chown/chmod the old files to match the container's config?

I am also curious about how to configure where the volume(s) reside.  I had planned to setup a block volume on the host just for the mail container project directory and volumes.  My thought with using a dedicated block volume on the host was to keep everything related to this container (code and data) kept in one place that is easily mounted on another node, snapped, grown in size later, and etc.  In the `docker-compose` files you have named volumes, but not indication of specifying a hostpath.  Is there a recommended configuration here?  Should I locally modify the compose file to hard code the hostpaths for the volumes?

Again, thanks for your answers.

**Comment by erik-wramner** [comment]
You're right about the ownership, all mail files are owned by the same user (docker) and reside under /var/mail.

As for the volumes many users are mapping host paths. There are pros and cons. The main advantage with volumes is that it "just works", with host paths there can sometimes be permission issues. On the other hand you know what you get with a host path, there have been bugs with docker volumes after all. You can certainly change the compose file to map host paths if you like.

**Comment by salderma** [comment]
Hi again,

So what is the best practice for mapping the host paths to the volumes?  I've tried a few ways, and they always end up under `/var/lib/docker`.  The cloud node I'm deploying will have a block storage volume mounted.  I "could" put that in `/var/lib/docker`, but I'd rather have it mounted as something like `/data/mailserver` and also have the compose file and env files on it.

Is there a good example available?

**Comment by erik-wramner** [comment]
Well, the main template in the readme actually includes an example (partial extract):
```

    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local

```
Here you have three docker volumes that will end up in /var/lib/docker and one local folder (config) that is mapped directly. The folder has no mapping in the second volumes group and is a path. Please refer to the docker documentation for detailed syntax.

**Comment by salderma** [comment]
I have taken the route of removing the named volumes section from the docker-compose file and hard coding the volume paths into the container volumes.  This seems to work just fine.

My hardware server had my domain setup as a virtual domain, so I had to adjust the source and destination paths appropriately and set ownership permissions to what the container is using as you mentioned.

All seems well, closing.
