### ISSUE TITLE
How to send vacation autoresponse messages (Investigate fuglu instead of amavis)

### ISSUE THREAD

**Issue by chongma** [tomav/docker-mailserver#1564]
## Is your feature request related to a problem?

Fuglu was recommended by the spamassassin mailing list as an alternative to Amavis

## Describe the solution you'd like

Maybe fuglu could be a nice and possibly simpler alternative to amavis

## Alternatives you've considered

I have been using Amavis in my last mail server but have found it difficult to configure and was considering fuglu as an alternative

## Who will that feature be useful to?

Fuglu has a vacation message feature which looks nice but might require a database

## What have you done already?

Have not built anything.  I am new to this project and looking forward to attempting to install

## What are you going to contribute?

If I can get the docker mailserver up and running and understand the configuration then I might be able to attempt a Fuglu switch out

**Comment by erik-wramner** [comment]
Replacing Amavis is a big thing, so if we are to do that you need to make a good argument. In particular I do not want to switch until Fuglu is proven and somewhat mainstream. This should be a stable offering, more boring than bleeding edge. Still, you're welcome to make your case!

**Comment by chongma** [comment]
Amavis is fine with me if the config is handled well by docker compose.  Evaluating Fuglu it is written in python and seems to have more plugins and it is recommended on the spamassassin mailing list is the only reason I mentioned it.  With docker-mailserver what is the best way to tackle vacation messages?

**Comment by erik-wramner** [comment]
I would use sieve, see https://wiki.dovecot.org/Pigeonhole/Sieve/Examples (found it by searching, not sure if it is good). That should be supported out of the box.

**Comment by chongma** [comment]
yes sieve is what i am currently using.  it doesn't seem to be fit for purpose.  for example how is an admin supposed to turn on and off a vacation filter and update the email body for an individual user?  it has a rather complex syntax.  fuglu offers a simple database driven alternative

**Comment by erik-wramner** [comment]
If you read the mission statement for this project it says "Only configuration files, no SQL database". That means fuglu is out if it needs a database. Perhaps you should look into one of the other mail server projects that already have database backends? Perhaps you can find one that fits your needs better.

**Comment by chongma** [comment]
do you have an example how an administrator can turn on a vacation message for a single user with sieve?

**Comment by erik-wramner** [comment]
There was an example in the link I sent (just scroll down or search for vacation). Not tested, I'm not using that feature myself.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by MohammedNoureldin** [comment]
If you still need help or example for this, I will be glad to help. I have just got it working.

**Comment by georglauterbach** [comment]
> If you still need help or example for this, I will be glad to help. I have just got it working.

If you like, you could add this to the documentation, so all readers can read it without needing to resort to this issue. That'd be great!:)

**Comment by chongma** [comment]
@MohammedNoureldin Thanks.  I can set up vacation messages using a sieve client, such as in roundcube, but i don't know how to do it programatically from the command line.  I have looked into several libraries but they are so archaic it is impossible to use.  Any attempt I make to edit a sieve file results in losing the comments in the file which are needed for roundcube to work properly

**Comment by MohammedNoureldin** [comment]
Hi @georglauterbach, I will provide an example how this can be done (probably today) with simple two explanations, one for Nextcloud, and one for Thunderbird.

**Comment by chongma** [comment]
@MohammedNoureldin I am looking for a script that would allow adding a vacation message at the command line like
```
setup.sh vacation <domain> <username> <subject> <body> <enabled>
setup.sh vacation example.com joey.chestnut "I am on vacation" "Please contact xyz@abc.com while I am away"
```
That way I could have simple control over the vacation messages.  But most sieve clients mess up the comments which are created by roundcube which prevents me from being able to do this.
