### ISSUE TITLE
Container image tag missing for 7.0.1 on dockerhub

### ISSUE THREAD

**Issue by clssn** [tomav/docker-mailserver#1568]
The above mentioned container image is presumably built and pushed with the stable tag, but the convention to also provide release version tags seems to be broken with this release.

### *What* is affected by this bug?

Users of the docker image who want to have tight control of their dependency bumps and thus prefer to refer to the release version tags instead of "stream" tags like "latest" or "stable".

### *When* does this occur?

Looking in https://hub.docker.com/r/tvial/docker-mailserver/tags

## *How* do we replicate the issue?

1. Browse https://hub.docker.com/r/tvial/docker-mailserver/tags
2. Look through pages of tags to find out 7.0.1 is missing

## Actual Behavior
Recent container image is available with tag "latest", but no clue what version that is.
A little less recent image is available with tag "stable", but I can only guess what version that is.

## Expected behavior (i.e. solution)
Container image of version 7.0.1 should be tagged as such, just like the versions before.

## Your Environment
n/a

**Comment by erik-wramner** [comment]
I agree. @fbartels / @tomav any idea why version 7.0.1 was not pushed to docker hub? @tomav also note that I can no longer manually trigger rebuilds in Travis, not sure if it is related but I used to be able to do that.

**Comment by fbartels** [comment]
@erik-wramner sorry. Totally missed that mention. No unfortunately there are not really ways to debug this (at least afaik).

Builds are triggered on push and looking through the build history on the Docker hub the 7.0.1 tag is really missing there. Maybe a small hickup on the Docker side? Apart from creating a new tag I don't think there is a good way to test/repair this.

**Comment by clssn** [comment]
Thanks for the info @fbartels. If you are positive that this was only a glitch and the next tag should trigger a build, then you may close the issue. For completeness' sake you could re-tag the 7.0.1 though and see whether it gets built.

**Comment by erik-wramner** [comment]
I didn't find a good way to do this, but eventually I deleted the tag and pushed it again. That seems to have done the job. Hopefully the build succeeds this time.
