### ISSUE TITLE
HowTo Disable PLAIN text, unencrypted AUTH in Postfix?

### ISSUE THREAD

**Issue by salderma** [tomav/docker-mailserver#1569]
* [ x ] I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

Sorry if I've not picked the right thing above.  I have setup a test domain for a simple setup.  There are just 2 mailboxes, no aliases, no relays, and nothing else complex.  I am able to send/receive email between the mailboxes and to/from external addresses.

I think everything is working, but I'm confused about how Postfix and Dovecot use SASL and work or don't work when `ENABLE_SASLAUTHD=0` or `ENABLE_SASLAUTHD=1`.  Is `ENABLE_SASLAUTHD=1` all that needs configured to make things work?  I seemed to have trouble logging into IMAP when it was set, but I'm not entirely sure that was the culprit.

That said I'm also wondering if getting the SASL setup correct has anything to do with resolving this low risk Nessus report for [plugin #54582](https://www.tenable.com/plugins/nessus/54582) with the following:
```
The SMTP server advertises the following SASL methods over an
unencrypted channel :

  All supported methods : LOGIN, PLAIN
  Cleartext methods     : LOGIN, PLAIN
```

The `env-mailserver` file has the following, excluding comments and variables with no value set:
```
DMS_DEBUG=0
ONE_DIR=0
TLS_LEVEL=modern
SPOOF_PROTECTION=1
ENABLE_SRS=1
ENABLE_CLAMAV=0
ENABLE_FAIL2BAN=0
POSTSCREEN_ACTION=enforce
SSL_TYPE=letsencrypt
REPORT_RECIPIENT=0
REPORT_INTERVAL=daily
POSTFIX_INET_PROTOCOLS=all
ENABLE_SPAMASSASSIN=1
SPAMASSASSIN_SPAM_TO_INBOX=1
MOVE_SPAM_TO_JUNK=1
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=6.31
SA_SPAM_SUBJECT=***SPAM*****
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
DOVECOT_TLS=yes
DOVECOT_MAILBOX_FORMAT=maildir
ENABLE_POSTGREY=1
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_TEXT=Delayed by postgrey
POSTGREY_AUTO_WHITELIST_CLIENTS=5
ENABLE_SASLAUTHD=0
SRS_SENDER_CLASSES=envelope_sender
RELAY_PORT=25
```

**Comment by erik-wramner** [comment]
First of all we support two different authentication methods. The normal option is to authenticate with Dovecot and then `ENABLE_SASLAUTHD` should be 0. That is probably what you want. Read the docs if you want more details on the other option.

Second I think (but feel free to test and perhaps prove me wrong) that our configuration is safe. The way it should work is that the server should require STARTTLS before it accepts a login. Then the connection will be encrypted. That is on port 587, port 465 is encrypted from the get-go. If you are worried you can expose port 465 and use that for submission, there is no need to use 587 at all. Port 25 accepts anything as it is intended for external servers from other domains. Your own users should always use port 465 or 587.
