### ISSUE TITLE
smtp_header_checks removes the "User-Agent" field from e-mails and breaks DKIM/DMARC

### ISSUE THREAD

**Issue by isorin** [tomav/docker-mailserver#1575]
**Use case:**
Sending e-mail from Gmail account (through Thunderbird) to Postfix server (running version 7.0.1) which redirects it to another Gmail account.

E-mail header contains these fields (look at the "User-Agent" field, I've changed some of the other fields for privacy):
```
To: User <user@mydomain.com>
From: Gmail User <user@gmail.com>
Subject: test
Message-ID: <d47540f0-cf17-9410-46ba-03f17ff09a70@gmail.com>
Date: Fri, 17 Jul 2020 22:20:58 +0100
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101
 Thunderbird/68.10.0
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit
Content-Language: en-US
```

Received e-mail on Gmail doesn't contain a "User-Agent" field (which is one of fields Gmail signs):
```
[...]
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=fail header.i=@gmail.com header.s=20161025 header.b=YRcDpA7l;
       spf=pass (google.com: domain of user@mydomain.com designates 1.2.3.4 as permitted sender) smtp.mailfrom="user@mydomain.com";
       dmarc=fail (p=NONE sp=QUARANTINE dis=NONE) header.from=gmail.com
[...]
To: User <user@mydomain.com>
From: Gmail User <user@gmail.com>
Subject: test
Message-ID: <d47540f0-cf17-9410-46ba-03f17ff09a70@gmail.com>
Date: Fri, 17 Jul 2020 22:20:58 +0100
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit
Content-Language: en-US
```

Commenting out the "smtp_header_checks" line in /etc/postfix/main.cf fixes the issue.
(this is the line)
```
cat /etc/postfix/main.cf
[...]
# Remove unwanted headers that reveail our privacy
smtp_header_checks = pcre:/etc/postfix/maps/sender_header_filter.pcre
[...]
```

/etc/postfix/maps/sender_header_filter.pcre states it should IGNORE the "User-Agent" but it doesn't seem to do so.
```
cat /etc/postfix/maps/sender_header_filter.pcre
/^\s*Received:.*with ESMTPSA/       IGNORE
/^\s*Received:.*amavisd-new/        IGNORE
/^\s*X-Originating-IP:/             IGNORE
/^\s*X-Mailer:/                     IGNORE
/^\s*Mime-Version: 1.0.*/           REPLACE Mime-Version: 1.0
/^\s*User-Agent/                    IGNORE
/^\s*X-Enigmail/                    IGNORE
/^\s*X-Mailer/                      IGNORE
/^\s*X-Originating-IP/              IGNORE
/^\s*Received: from.*127.0.0.1/     IGNORE
```

**Comment by aendeavor** [comment]
Sorry for the late response.

Have you investigated and found something?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by isorin** [comment]
This still happens but it's not a bug.
I misunderstood the meaning for "IGNORE" - the field is removed which seems to be what IGNORE does.
I am glad I found it as I now use a different file for "/etc/postfix/maps/sender_header_filter.pcre" which doesn't break DKIM/DMARC for the use case I described above.

**Comment by m-a-v** [comment]
@isorin I had observed the same thing. How does your file `sender_header_filter.pcre` look now?

**Comment by aendeavor** [comment]
> This still happens but it's not a bug.
> 
> I misunderstood the meaning of "IGNORE" - the field is removed which seems to be what IGNORE does.
> 
> I am glad I found it as now I use a different file for "/etc/postfix/maps/sender_header_filter.pcre" which doesn't break DKIM/DMARC for the use case I described above.

I'm glad this could be solved.

**Comment by isorin** [comment]
> @isorin I had observed the same thing. How does your file `sender_header_filter.pcre` look now?

I have tried two options:
1) the original file but I removed the "User-Agent" line from it..

2) I didn't like the fact that the original file removes some of the "Received: from" lines so now I'm using this:
--------
/^\s*(Received: from \[)[^\n]*(.*with ESMTPSA.*)/  REPLACE ${1}127.0.0.1] (localhost [127.0.0.1])${2}
--------
(which anonymizes the sender IP address without removing the "Received" header)

It's a work in progress...
