### ISSUE TITLE
Possible problems with firewalld/iptables?

### ISSUE THREAD

**Issue by salderma** [tomav/docker-mailserver#1577]
Hi again,

I've only been running this container in the wild for about a week.  I'm using CentOS/8 with firewalld, iptables (not nftables), and docker-ce (installed to work correctly, as far as I'm aware).  The Default Zone for the server's interface is the system provided "drop" zone...all connections are dropped except those specifically permitted and the ports published by docker.

I'm noticing in the mail logs that all the log entries for postfix receiving mail show the docker network's gateway IP address... 172.[16-20].0.1 as the source of the connection.  I'm wondering if I've got something wrong with the firewall.
1.  It would seem having the RFC1918 IP as the source will effectively make fail2ban a denial of service.
2.  It also seems to be messing with some SPF checking.  e.g. sender's SPF record uses `-all` causes the email to be rejected.

Any ideas here?  Do I need to make firewalld source nat packets going into the docker networks?

**Comment by erik-wramner** [comment]
You do need to NAT somewhere and as you noticed some things won't work unless you can preserve the real remote address for inbound connections. Still, that part should just work if your host has a public IP with a direct connection. Does it? If not, how do your clients connect?

**Comment by salderma** [comment]
It's public IP.  This is for hosting a family/friends email domain.  Ppl access it from gmail, thunderbird or their phones.

Anyway, I've tried a couple of things but no progress.  Everything is still showing up in the docker logs as 172.18 or 172.20 client IP (seems like docker switches between these 2 subnets depending on whether docker or docker-compose starts the container).

Ultimately, I guess I could try to mount my data volume onto an ubuntu or centos7 node.  Maybe this is an issue with CentOS 8, I'll work on refactoring my ansible code to configure the host for centos7.  I was hoping to use 8 for its longevity.

**Comment by salderma** [comment]
So here's a simple example of what shows in the docker container logs - 

```
Jul 28 18:26:28 mail dovecot: imap-login: Login: user=<joe@mydomain.com>, method=PLAIN, rip=172.18.0.1, lip=172.18.0.2, mpid=3333, TLS, session=<Fvblk4Sr2oOsEgAB>
```
You can see the REAL IP is the docker network gateway IP.  If the user had failed authentication and fail2ban was up, it would be result in a denial of service.  I'm guessing this should be the real client's IP, right?

**Comment by salderma** [comment]
So I've tinkered with my ansible code to setup the host.  I used vagrant to build a centos7 vm, forward 8XXX ports to all relevant mail ports (e.g. localhost:8025 -> vm:25) and apply the ansible config.  Copied my mailserver container files from my cloud server to the VM, changed the host/domain name, changed how the certs are used, enabled fail2ban, added 2 email accounts.

I setup a test with each of the accounts from thunderbird, one with correct password, the 2nd with bad password.  After the bad password account fails enough to trigger fail2ban, I get this from a root shell on the vagrant vm running docker -
```
[root@mail mailserver]# ./setup.sh debug fail2ban
Banned in dovecot: 172.19.0.1
Banned in postfix: 172.19.0.1
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
```
Now, neither the thunderbird from the vm host through the forwarded ports nor openssl s_client from the VM itself can connect to any ports b/c of the fail2ban.

How is this supposed to work if docker bans the docker0 interface IP?

**Comment by erik-wramner** [comment]
Disable fail2ban (you can run it on the host instead) or use https://github.com/tomav/docker-mailserver#permit_docker to trust the network. The real solution should be to get the actual remote addresses working though!

I suspect that your actual issue is with firewalld and how it is configured to do NAT. What happens if you spin up a web server in docker, for example nginx? Use any port and connect from somewhere else. Does nginx show the correct remote address in the web server log? If it doesn't perhaps that is an easier test case. Fewer moving parts. When you have it working you can apply the same configuration for docker-mailserver.

**Comment by salderma** [comment]
So it looks like the recommended firewalld config for CentOS/8 and Docker-CE to `--add-masquerade` to your active zone in order to enable docker's internal dns to function correctly is the issue.  I was under the impression that the docker masquerade was in the outbound direction.  Hopefully, this won't create a dns lookup issue inside the mail container.

While CentOS/7 seems not to have the same issue with firewalld and docker, adding the masquerade produced the same results inside the container.

...closing...
