### ISSUE TITLE
Hosting on ECS?

### ISSUE THREAD

**Issue by NorseGaud** [tomav/docker-mailserver#1580]
Hello! Thanks for putting together this amazing project. I'm going to be contributing for sure, just need to get up to speed. 

One problem I have is that the setup script only works on the host running docker. However, I plan on running my docker containers on ECS/Fargate/EFS and don't have a host to log into. I could probably re-write the script so it would SSH into the container using the IP amazon gives me to do its changes... But I wonder what y'all think before I do.

**Comment by erik-wramner** [comment]
Interesting. Presumably the people who are using Kubernetes have similar problems, but the [wiki](https://github.com/tomav/docker-mailserver/wiki/Using-in-Kubernetes) is not crystal clear on the solution.

The good thing with this project is that we are only using files. That means you should be able to run setup locally to generate the configuration and when you are done you can copy the files to your runtime environment. In Kubernetes they can be mounted from secrets or configmaps. You probably have something similar in ECS?

**Comment by NorseGaud** [comment]
Yep, either Kubernetes or ECS would experience this problem. Good point!

I've been digging into things and the check-for-changes.sh looks like half of the battle. I'll keep playing with the setup.sh and see what I can get working. I run an EC2 instance temporarily which mounts the EFS volume where I'll keep all of the configs. So I can run the setup.sh there if it's only updating the files and doesn't need container access.

Thanks! I'll follow up with a report of how things go

**Comment by erik-wramner** [comment]
The setup.sh script calls commands in a container that it will start, but when it is done only the files are used. It shouldn't matter if you run the script on the actual host to generate files in-place or if you run it on your laptop and copy the files afterwards. Good luck!

**Comment by NorseGaud** [comment]
Ah, so if I just run a docker container on the EC2 instance where the EFS mount is, perform the actions, then just copy the files from the container's volume into the EFS, that should work? I'll give that a shot!

**Comment by nanbelle** [comment]
@NorseGaud did you manage using ECS for this dockerfile?
