### ISSUE TITLE
Replying from aliases

### ISSUE THREAD

**Issue by 3dc0deR** [tomav/docker-mailserver#1581]
Firstly, thanks for this awesome project! I have learnt a lot from this project about mail servers and finally I have one of my own running smoothly.

However, I have a question about aliases.

If I have a alias in my mail server pointing to some email address like:
alias@mydomain.com => admin@mydomain.com

Is it possible to reply from the alias address alias@mydomain.com when a new mail is received?

I don't want an individual mailbox for alias@mydomain.com. I just want it to be forwarded to admin@mydomain.com but be able to reply from alias@mydomain.com

Is such a thing possible?

Thanks in advance.

**Comment by casperklein** [comment]
Yes, it's possible. Just do it ;-)

**Comment by 3dc0deR** [comment]
> Yes, it's possible. Just do it ;-)

Could you kindly elaborate a bit ? 

When replying to an email from my mail client, I can only choose the logged in account. How can I send it with an arbitrary email address?

Also I have spoof protection enabled.

**Comment by casperklein** [comment]
> Also I have spoof protection enabled.

That should be no problem.

My setup is similar. I've got one account and a lot of aliases pointing to that:

alias1@domain.tld -> postmaster@domain.tld
alias2@domain.tld -> postmaster@domain.tld

In your mail program, configure the login credentials (in my case postmaster@domain.tld + password) as you would normally do and then set your alias as sender address. Using MS Outlook that could look like:

![setup](https://user-images.githubusercontent.com/590174/89325509-30741900-d689-11ea-8088-d8a39b107a39.PNG)

**Comment by 3dc0deR** [comment]
Oh great! I just tested and it works flawlessly. Thanks a lot. :)
