### ISSUE TITLE
How to get mail messages from host ?

### ISSUE THREAD

**Issue by euri10** [tomav/docker-mailserver#1582]
## Subject

* [x] I would like some feedback concerning a use case

## Description

I have the docker-mailserver running fine on my desktop. Host is debian buster.

I installed [apticron](https://packages.debian.org/fr/buster/apticron) on the host to get notified by email of potential packages upgrades.

`apticron` requires `bsd-mailx` on the host which in the end install `exim4-daemon-light`

I sometimes get these mail messages on host mail:

```
Date: Sat, 01 Aug 2020 06:25:01 +0200
From: root <root@hostname>
To: root@hostname
Subject: exim paniclog on hostname has non-zero size

exim paniclog /var/log/exim4/paniclog on hostname has non-zero size, mail system might be broken. The last 10 lines are quoted below.

2020-05-16 12:15:24 socket bind() to port 25 for address 127.0.0.1 failed: Address already in use: daemon abandoned
2020-05-16 12:16:59 socket bind() to port 25 for address 127.0.0.1 failed: Address already in use: daemon abandoned
```

The mail addresses setup in the docker container work fine, no complains, I just wondered if I should just ignore those mail errors from exim4 complaining or if there was a way for the host to use the mail system of the container and avoid this what seems to be a port conflict.

**Comment by casperklein** [comment]
I use [nullmailer](https://wiki.debian.org/nullmailer) for that purpose. It forwards all local mails to docker-mailserver and doesn't require to bind port 25.

**Comment by euri10** [comment]
> I use [nullmailer](https://wiki.debian.org/nullmailer) for that purpose. It forwards all local mails to docker-mailserver and doesn't require to bind port 25.

You rock @casperklein it's exactly what I was looking for, thanks !
