### ISSUE TITLE
'Cannot access certificate' error after changing to Traefik's acme.json

### ISSUE THREAD

**Issue by dmuensterer** [tomav/docker-mailserver#1585]
## Subject
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description
I had docker-mailserver running for quite a while now and am very satisfied so far.
Today, I wanted to switch from using letsencrypt manually to using letsencrypt via Traefik V2.
I am mounting the acme.json file into the container and can also access it from within the container without problems.
Still, I get the error message:
`* Cannot access '/etc/letsencrypt/live/mail.mydomain.net/fullchain.pem' or '/etc/letsencrypt/live/mydomain.net/fullchain.pem'`
I have the following SSL relevant flags in my docker-compose.yml:

```
- ../letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
environment:  
  - SSL_TYPE=letsencrypt
```

What am I doing wrong?

**Comment by erik-wramner** [comment]
I'm not using letsencrypt, so I'll flag this "help wanted". Hopefully one of the experts will step in. Please check the example in the wiki if you haven't already done that.

**Comment by dmuensterer** [comment]
Thank you. My config does not differ to the example config displayed. I am already using Traefik for many services except docker-mailserver yet.
Any help is much appreciated as it seems to me that the container only looks for the /etc/letsencrypt/live/ folder instead of only the acme.json

**Comment by dmuensterer** [comment]
I found out what's the problem: The example docker-compose.yml is wrong, as the "stable" tag is used, even though the current "stable" tag in the docker hub does NOT support the feature yet. I have opened another issue with more details. #1587
