### ISSUE TITLE
Add environment for using other network interface than `eth0`

### ISSUE THREAD

**Issue by osddeitf** [tomav/docker-mailserver#1588]
I have a Kubernetes cluster, and for whatever reason, I have to running on `hostNetwork` mode.
And, at the node `docker-mailserver`'s running, there's not `eth0` interface.
If I leave it as is, I cannot send mail, with error logs like:
```
...
postfix/smtps/smtpd[3793]: warning: non-existent:/32 is unavailable. open file /32: No such file or directory
...
postfix/postscreen[1210]: error: open file /32: No such file or directory
...
```
I think, it's better for user to have the ability to use different network interface, like `PERMIT_DOCKER_INET`, but currently at [start-mailserver.sh:1194](https://github.com/tomav/docker-mailserver/blob/f206ad7ee145ab72b5edcf0c70d3bd666305c78d/target/start-mailserver.sh#L1194), `eth0`'s present:
```bash
function _setup_docker_permit() {
	notify 'task' 'Setting up PERMIT_DOCKER Option'

	container_ip=$(ip addr show eth0 | grep 'inet ' | sed 's/[^0-9\.\/]*//g' | cut -d '/' -f 1)
	container_network="$(echo $container_ip | cut -d '.' -f1-2).0.0"
	container_networks=$(ip -o -4 addr show type veth | egrep -o '[0-9\.]+/[0-9]+')
```

**Comment by erik-wramner** [comment]
There is a very old bug for this, see #1227. I'm closing this as a duplicate. If you have time you could read the discussion in #1227 and submit a PR.
