### ISSUE TITLE
/etc/dovecot/userdb not generated correctly

### ISSUE THREAD

**Issue by stonemaster** [tomav/docker-mailserver#159]
I am using the **v2** of the container.

I think that the `/etc/dovecot/userdb` isn't generated correctly. I have a `postfix-accounts.cf` with two users (just posting one as example).

`
test@test.com|{CRAM-MD5}0..[65 bytes total]..f
`

During startup of the container I see the message

`
mail_1     | user 'test' for domain 'test.com' with password '********'
`

.. which seems to indicate that everything is fine and the users are created. But the file `/etc/dovecot/userdb` contains an incorrect user line:

`
:5000:5000::/var/mail/test.com/test::2...[MD5 bytes]f
`

Note the `:` at the beginning where username and password should be set. At the end of a line is some MD5 string which is a **part** of the MD5 password hash (last 52 bytes).

I looked at the startup code and everything looks great. I am totally clueless.
Do you have an idea what is going wrong?

**Comment by Niklv** [comment]
Have same issue.

**Comment by Niklv** [comment]
@stonemaster found that file config/postfix-accounts.cf has CLRF line endings.
I recreate this file with LF endings and it fork fine for me.

You can check endings:

```
root@mail:/# file /tmp/docker-mailserver/postfix-accounts.cf
/tmp/docker-mailserver/postfix-accounts.cf: ASCII text
```

**Comment by tomav** [comment]
`CLRF` is windows format, and we're on a linux docker image :-)
That said, it's possible to add a check on that using:

    tr -d '\r' < input.file > output.file

or

    sed 's/$'"/`echo \\\r`/" input.txt > output.txt

(should probably be adapted)

By the way, how did you generate your `postfix-accounts.cf`? Using:
- command line with password and `>> config/postfix-accounts.cf`
- command line without password pasted manually in the file (I suppose this one)

Thanks.

**Comment by tomav** [comment]
I added the tip regarding line endings in the FAQ.

**Comment by stonemaster** [comment]
I am unsure how I actually added the accounts. But that's it. It's just about the wrong line endings. I would suggest adding some check in the script because this is an evil one if you don't know what happens and the file actually **looks** good :-)

**Comment by Niklv** [comment]
@tomav @stonemaster I generate file on my linux VPS using this command from README.md:
````
docker run --rm \
  -e MAIL_USER=user1@domain.tld \
  -e MAIL_PASS=mypassword \
  -ti tvial/docker-mailserver:v2 \
  /bin/sh -c 'echo "$MAIL_USER|$(doveadm pw -s CRAM-MD5 -u $MAIL_USER -p $MAIL_PASS)"' >> config/postfix-accounts.cf
````

**Comment by tomav** [comment]
Tested and reproduced. I will push:
- `test/config/postfix-accounts.cf` generation from the command (and not from a static file anymore)
- check in `start-mailserver.sh` to covert line endings

**Comment by tomav** [comment]
Done. Build in progress.

**Comment by tomav** [comment]
@stonemaster, @Niklv, image available on hub. You can pull and re-test.
