### ISSUE TITLE
shellcheck & setup.sh

### ISSUE THREAD

**Issue by aendeavor** [tomav/docker-mailserver#1590]
## Subject

**Other - `setup.sh` may be prone to errors.** Related to #1228 and #1258.

## Description

Shellcheck (`v0.7.0`) is complaining alot about `setup.sh`. You may wan't to have a look:

![shellcheck_complains](https://user-images.githubusercontent.com/44545919/90148268-731dab80-dd83-11ea-9778-40f62bb731e3.png)

**Comment by erik-wramner** [comment]
There is already a PR for this in #1258 but it is stuck. If you have the skills and time please feel free to continue that work or by all means start fresh. If you do start over, please check the PR first to avoid double work and mistakes.

**Comment by aendeavor** [comment]
Done with the merge of #1595.
