### ISSUE TITLE
Please Help - Connect to private/auth failed: No such file or directory

### ISSUE THREAD

**Issue by michaelAdewunmi** [tomav/docker-mailserver#1597]
## Subject

* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [ ] Other

## Description
I am trying to use gmail as my relay server. I seem to get the postfix mail daemon starting but when I try to send a test email from the client, I get the response `could not read mail` on the client while the log entry in the container is shown below.

```
Aug 25 10:58:32 mail postfix/master[775]: daemon started -- version 3.4.10, configuration /etc/postfix

Aug 25 10:59:01 mail postfix/submission/smtpd[855]: error: open database /etc/postfix/vmailbox: No such file or directory

Aug 25 10:59:01 mail postfix/submission/smtpd[855]: connect from client_container.mail[192.16X.XX.X]

Aug 25 10:59:01 mail postfix/submission/smtpd[855]: Anonymous TLS connection established from client_container.mail[192.16X.XX.X]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256

Aug 25 10:59:01 mail postfix/submission/smtpd[855]: warning: SASL: Connect to private/auth failed: No such file or directory

Aug 25 10:59:01 mail postfix/submission/smtpd[855]: fatal: no SASL authentication mechanisms

Aug 25 10:59:02 mail postfix/master[775]: warning: process /usr/lib/postfix/sbin/smtpd pid 855 exit status 1

Aug 25 10:59:02 mail postfix/master[775]: warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling
```

Below is my docker-compose.yml
```
version: '3.7'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: localdomain.local
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./maildata:/var/mail
    - ./mailstate:/var/mail-state
    - ./maillogs:/var/log/mail
    - ./config:/tmp/docker-mailserver/
    env_file:
    - .env
    - env-mailserver
    environment:
      - PERMIT_DOCKER=network
      - SMTP_ONLY=1
      - DEFAULT_RELAY_HOST=smtp.gmail.com
      - RELAY_HOST=smtp.gmail.com
      - RELAY_USER=myemail@gmail.com
      - RELAY_PASSWORD=mygmailpassword
      - POSTFIX_INET_PROTOCOLS=ipv4
      - DOVECOT_TLS=yes
      - SASL_PASSWD=[smtp.gmail.com]:587 myemail@gmail.com:mygmailpassword
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
    networks:
      mail:
networks:
  mail:
    name: mail
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```
I think I am doing something wrong. I am using docker desktop with wsl2 on windows through ubuntu 20.04LTS. 

I later adjusted my `enironment` options  and set `ENABLE_SASLAUTHD=1`. However this gave me an error similar to **[this issue1247](https://github.com/tomav/docker-mailserver/issues/1247#issuecomment-527368819)**. The `saslauthd_pam `keeps entering and exiting. The Log is shown below too.

```
2020-08-25 11:37:03,609 INFO spawned: 'saslauthd_pam' with pid 3268

2020-08-25 11:37:03,630 INFO success: saslauthd_pam entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2020-08-25 11:37:03,630 INFO exited: saslauthd_pam (exit status 0; expected)

2020-08-25 11:37:03,633 INFO spawned: 'saslauthd_pam' with pid 3269

2020-08-25 11:37:03,666 INFO success: saslauthd_pam entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2020-08-25 11:37:03,666 INFO exited: saslauthd_pam (exit status 0; expected)

2020-08-25 11:37:03,669 INFO spawned: 'saslauthd_pam' with pid 3270

2020-08-25 11:37:03,694 INFO success: saslauthd_pam entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2020-08-25 11:37:03,705 INFO exited: saslauthd_pam (exit status 0; expected)

2020-08-25 11:37:04,709 INFO spawned: 'saslauthd_pam' with pid 3274

2020-08-25 11:37:04,724 INFO success: saslauthd_pam entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2020-08-25 11:37:04,726 INFO exited: saslauthd_pam (exit status 0; expected)

2020-08-25 11:37:04,728 INFO spawned: 'saslauthd_pam' with pid 3275

2020-08-25 11:37:04,754 INFO success: saslauthd_pam entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2020-08-25 11:37:04,764 INFO exited: saslauthd_pam (exit status 0; expected)

2020-08-25 11:37:04,785 INFO spawned: 'saslauthd_pam' with pid 3276
```

Please I will be very glad to get some help or pointers. Thanks a lot.

**Comment by erik-wramner** [comment]
Hm, I really don't know. Windows as a host doesn't work, but it might work when you are using wsl2. Not sure. More to the point, are you sure that gmail supports acting as a relay like this? I know they have that option as part of gsuite, but it needs to be configured. Most people don't need ENABLE_SASLAUTHD (we use Dovecot for SASL by default).

**Comment by michaelAdewunmi** [comment]
Hello Eric! Thanks for taking the time to reply. I'll like to comment on some of your thoughts.

>...I really don't know. Windows as a host doesn't work, but it might work when you are using wsl2.

I initially configured postfix on the Ubuntu 20.04LTS (using wsl2) and was able to use it to send emails by relaying emails to my own Gmail account. This was the reason I thought it will work in this docker image too. Although sending of emails on the Ubuntu host suddenly stopped working a few days ago. I didn't change a thing. It just stopped working and I couldn't figure out why. I adjusted many things too but none worked.

> are you sure that gmail supports acting as a relay like this? I know they have that option as part of gsuite, but it needs to be configured

I also am not sure of this. I googled about it but didn't see any detailed information as regards how Gmail handles relayng (or the restrictions placed on it). I was actually hoping someone might point it out in this issue since we have more knowledgable and experienced folks here.

> Most people don't need ENABLE_SASLAUTHD (we use Dovecot for SASL by default).

I sudo into the docker container and saw that this is true and really, there should be no need for the ENABLE_SASLAUTHD for most cases. I am actually somewhat new to email server configuration and only started getting the hang of things after few days of reading the wiki and other resources. So, I am not too confident about how I do things. This is the reason I raised this issue (I wanted to be sure that I am not doing anything wrong in my configuration).

Thank you once again for your reply. I will keep digging around and trying other things. If I find anything, I'll post it here. Thanks.

**Comment by erik-wramner** [comment]
There are too many unknowns. I would suggest closing one at a time. Start with a plain installation as close to the README as possible without any relay to gmail, for example. Or start with a postfix installation without docker and without dovecot to see if you can get the relay working and how. Or start by moving it into a Linux VM (you can run one locally, it will just be dead slow) to address the Windows/WSL question. Good luck!

**Comment by aendeavor** [comment]
Could you make some progress @michaelAdewunmi ?

**Comment by michaelAdewunmi** [comment]
Hello @erik-wramner. I did as you said and these are the things I noticed.
1. Using the bare minimum from the README (without relaying to Gmail) works fine. There was no problem of any sort.

2. A postfix installation without docker also works when I am not relaying to Gmail. When relaying to Gmail, it wasn't working. It kept exiting with an error similar to "...cannot get a response from Gmail."

I couldn't run a Linux VM. So I couldn't check with a Linux VM. 

The issue arises when I want to make Gmail act as a relay. Probably Gmail doesn't support this (except with some configuration using Gsuite). I also read somewhere that it might be my IP address. Unfortunately, Gmail doesn't support whitelisting IP Addresses.

Altogether, what I can deduce is that the error could most likely be from gmail and it's probably not from the configuration.

I have decided to work without using Gmail as a relay. I would have loved to run a Linux VM to check but my laptop isn't a high config type and I am low on memory. Also creating the time for this might be a bit difficult for me this week because I have my plate full already. I might give it a try later though if I can free up some space.

Thanks @erik-wramner. I don't really know if its good to close this issue. If it is, then you should probably close it.  If I come across anything useful or I get it to work, then I can reopen it.

Thanks once again.

**Comment by aendeavor** [comment]
Alright. Thanks for the quick response and explanation. As you said, feel free to re-open this if you deem it necessary. Good luck!
