### ISSUE TITLE
SMTP responds different for local to local mail as sending to remote

### ISSUE THREAD

**Issue by JoelOnGithub** [tomav/docker-mailserver#1600]
## SMTP responds different for local to local mail as sending to remote

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [X] Other

## Description
Hello,

I was trying to check for open relay using telnet. `domain1.com` and `domain2.com` are hosted using docker-mailserver on my NAS. I found out that when sending email from local email to local email it behaves differently. Can someone explain me why this is?

`550 5.7.23 <email@domain2.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=domain1.com;ip=172.18.0.1;r=<UNKNOWN>` versus `554 5.7.1 <email@remote-domain.com>: Relay access denied`

This is the response when I use telnet to send from 1 local email to another local email:
```
me@laptop ~ % telnet domain1.com 25
Trying <ip-masked>...
Connected to domain1.com.
Escape character is '^]'.
220 domain1.com ESMTP
EHLO domain1.com
250-domain1.com
250-PIPELINING
250-SIZE 10240000
250-ETRN
250-STARTTLS
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
MAIL FROM:email@domain1.com
250 2.1.0 Ok
RCPT TO:email@domain2.com
550 5.7.23 <email@domain2.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=domain1.com;ip=172.18.0.1;r=<UNKNOWN>
```

This is the repsonse when trying to send something from a local email to a remote. (This is also what I was expecting for local to local).

```
me@laptop ~ % telnet domain1.com 25
Trying <ip-masked>...
Connected to domain1.com.
Escape character is '^]'.
220 domain1.com ESMTP
EHLO domain1.com  
250-domain1.com
250-PIPELINING
250-SIZE 10240000
250-ETRN
250-STARTTLS
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
MAIL FROM:email@domain1.com
250 2.1.0 Ok
RCPT TO:emailn@remote-domain.com
554 5.7.1 <email@remote-domain.com>: Relay access denied
```

**Comment by erik-wramner** [comment]
In both cases you are connecting to port 25, so you are simulating a remote e-mail server.

In the first case it tries to send mail to your server from your server, but the mail is not originating with you (you are not using the submission port with authentication). Thus Postfix checks if the remote server (that is the host running your telnet command) is allowed to send mail for your domain according to the SPF record. It is not, so the message is rejected.

In the second case you are sending from your domain to a remote domain. However, as you are not using the submission port but acting as a foreign mail server this is denied. The server will not relay mail to external domains.

Both actions are correct.

**Comment by JoelOnGithub** [comment]
Okay, that is great! Thank you so much for explaining so quickly.

I have been accidentally transmitting 21110 emails for viagra in just a few hours time, so I figured out that I better check everything properly configured this time :D
