### ISSUE TITLE
readlink: illegal option -- f on master setup.sh

### ISSUE THREAD

**Issue by gilkatz64** [tomav/docker-mailserver#1602]
I downloaded setup.sh master and tried to run it in ubuntu & mac with the same results
readlink: illegal option -- f
usage: readlink [-n] [file ...]
ERROR occured :: source (hint) ./setup.sh ; line 21 ; exit code 1 ;;

## *How* do we replicate the issue?

1. ./setup.sh email list
2.
3.
4.

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by aendeavor** [comment]
This is an abstract of the official `manpage` for `readlink`.

``` TXT
Name

readlink - print value of a symbolic link or canonical file name
Synopsis

readlink [OPTION]... FILE
Description

Print value of a symbolic link or canonical file name

-f, --canonicalize
canonicalize by following every symlink in every component of the given name recursively; all but the last component must exist

```

What version of Bash are you using? Can you try readink on its own on a symlink?

**Comment by gilkatz64** [comment]
In my mac it is GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

In the Jenkins slaves 
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
The ubuntu is 16.04.5 LTS (GNU/Linux 4.4.0-1099-aws x86_64)

**Comment by aendeavor** [comment]
Updated the original answer. Can you try it?

**Comment by aendeavor** [comment]
I will discuss this with @fbartels and @erik-wramner 

In the meantime, use the fix I provided that works without `readlink`. Attention: Symbolic links are not supported now.

Now to the matter at hand:

I can implement a rather simple fix in `setup.sh` which tries different path resolution methods. This would just add another function, but would make macOS for `setup.sh` functional again. I'd just push it in #1601.

**Comment by aendeavor** [comment]
This in now in #1601.
