### ISSUE TITLE
Error in setup.sh

### ISSUE THREAD

**Issue by gawindx** [tomav/docker-mailserver#1603]
this is not really an issue, but rather a return to an error in the setup.sh script.

on line 42:
VOLUME = $ (docker inspect "$ {CONTAINER_NAME}" \

should be :
VOLUME = $ ($ {CRI} inspect "$ {CONTAINER_NAME}" \

because in the case of podman, the script fails on this line, docker not being used here

**Comment by aendeavor** [comment]
You're absolutely right. I'll tend to it.
