### ISSUE TITLE
Get rid of ELK

### ISSUE THREAD

**Issue by aendeavor** [tomav/docker-mailserver#1606]
Seeing from #1475:

> Yes, your changes should make it into latest automatically. As for elk, I think we dropped that one in 7.0 when we upgraded Debian version. The elk build should be from the 6.x release, so it is quite old. Ideally we should stop building it.

_Originally posted by @erik-wramner in https://github.com/tomav/docker-mailserver/pull/1475#issuecomment-690188309_

I don't know how exactly. What do we do about this?

EDIT: I assigned @tomav too, as I deemed it appropriate here.

**Comment by tomav** [comment]
Fully agree with @erik-wramner. We should drop it, or maintain it in another repo.

**Comment by aendeavor** [comment]
@tomav how do we drop it?
