### ISSUE TITLE
ssl: bad certificate problem

### ISSUE THREAD

**Issue by adares2** [tomav/docker-mailserver#1607]
## Subject
* [x] I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

my .env file
```
HOSTNAME=mail
DOMAINNAME=example.com
CONTAINER_NAME=mail
```

I have a docker setup with a running Nginx Server. This Server runs without problems with a SSL Certificate.
First i try to use the same SSl Certificate For the docker-mailserver. 

When i try to connect with Thunderbird i get this error:
 
`TLS handshaking: SSL_accept() failed: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca: SSL alert number 48`

Then i stopped the server and created a letsencrypt certificate with this code:
`sudo certbot certonly --standalone -d mail.example.com`
`
then i mount letsencrypt with

`- /etc/letsencrypt/:/etc/letsencrypt/`

and i get this error:
`TLS handshaking: SSL_accept() failed: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate: SSL alert number 42`

so i changed the entries in /etc/postfix/main.cf 
```
smtpd_tls_cert_file=/etc/letsencrypt/live/mail.example.com/fullchain.pem
smtpd_tls_key_file=/etc/letsencrypt/live/mail.example.com/privkey.pem
```

and in /etc/dovecot/conf.d/10-ssl.conf

```
ssl_cert = </etc/letsencrypt/live/mail.example.com/fullchain.pem
ssl_key = </etc/letsencrypt/live/mail.example.com/privkey.pem
```

when i try to send an Email via php i got this error:
`Connection could not be established with host "ssl://smtp.example.com:465": stream_socket_client(): Peer certificate CN=mail.example.com did not match expected CN=smtp.example.com`

when i check my server on https://ssl-tools.net/mailservers i get a Hostname Mismatch error.

What am I doing wrong?

**Comment by aendeavor** [comment]
Could you post your compose file(without your personal data of course)? Have you searched for `TLS handshaking: SSL_accept() failed: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate: SSL alert number 42`? Could you try with `SSL_TYPE=manual`?

**Comment by aendeavor** [comment]
Could you solve this issue? If so, please close this issue. If not, report back the current status. If there is no answer, I will need to close this issue due to inactivity.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
