### ISSUE TITLE
High CPU load with fail2ban in escaped docker processes

### ISSUE THREAD

**Issue by andig** [tomav/docker-mailserver#1623]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [x] I would like some feedback concerning a use case
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [ ] Other

## Description

I've recently had to restore a backup from Synology NAS where mail container is running. Opening the backup took ages and investigation showed high CPU load of >25. After stopping all docker containers including mail, problem persisted. `ps aux` and `top` showed that main culprit was _still_ fail2ban from the mail container. Apparently fail2ban and other mail processes had survived stopping the docker container (I can confirm it was stopped and docker service shutdown).

Not sure if this is a problem with configuration of supervisord, supervisord itself or the docker version running on Synology but it would. be great if processes could be secured against escaping from container. fail2ban itself is useless in my case as it totally kills the machine.

**Comment by erik-wramner** [comment]
If the processes survive stopping the container that sounds like a docker bug to me? Not much we can do about that as far as I know. As for fail2ban, don't run it if you don't need it. I don't run it personally, I prefer to run that kind of thing on the host. You can always mount the log files so that they can be accessed from the host.

If you have a suggestion for fixing this I'm all ears. If not I would suggest closing and checking if there is a bug fix for your docker version (or file a bug for it yourself).

**Comment by aendeavor** [comment]
Like @erik-wramner said, I too cannot image this to be a bug in the mailserver but rather a very rare bug in Docker itself. Can you kill `fail2ban` and restart the processes and redo what you described again to verify that this is reproducible?

**Comment by andig** [comment]
>  I too cannot image this to be a bug in the mailserver but rather a very rare bug in Docker itself. 

As I've said, might very well be supervisord or docker itself: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

> Can you kill fail2ban and restart the processes and redo what you described again to verify that this is reproducible?

Killing fixed the problem, I'll try to repro  when I  find time.

**Comment by aendeavor** [comment]
Alright. Please report back here.

**Comment by erik-wramner** [comment]
@andig that was an interesting link. It was from 2015 though, so hopefully the Docker team has solved it by now. Let us know if you can reproduce the error. If so it would be nice with full versions for everything (OS, Docker, ...) as well.

**Comment by andig** [comment]
Closing for time being. Have not observed this since.
