### ISSUE TITLE
Operation mode with no outgoing SMTP

### ISSUE THREAD

**Issue by matejak** [tomav/docker-mailserver#1624]
## Is your feature request related to a problem?

It is not easy to share a particular mailserver setup e.g. as a demo, or for the purpose of debugging clients.
There is a great risk that such server could be abused by spammers.

## Describe the solution you'd like

To disable `postfix` at startup would probably fix this, but I think that it could also impact mail delivery, so such demo setup could not be able to receive e-mails.

## Alternatives you've considered

Not publishing the SMTP port could help, but I think that the mail server can send outgoing e-mails even without the SMTP port.

## Who will that feature be useful to?

The ability to fine-tune which features to switch on or off increases security, as setups that don't need to send e-mails can disable this feature.

## What are you going to contribute?

If somebody tells me how to achieve this by means of postfix configuration, I can propose a PR that will implement this `ENABLE_OUTGOING_SMTP` config option.

**Comment by erik-wramner** [comment]
I wouldn't trust this, but perhaps that is just me. My solution would be to nail down the network connectivity. A demo server should not be connected to the Internet. Trusting the server itself to do the right thing is, well, optimistic. A firewall in front of the demo environment is so much safer. For example, if you don't want to send mail you can drop all outgoing connections to port 25. If you don't want to receive mail, drop all inbound connections to port 25. Problem solved!

**Comment by matejak** [comment]
> I wouldn't trust this, but perhaps that is just me.

Do you mean that you wouldn't trust this setting as a user of the container, or that you don't trust that it is possible to configure Postfix to operate in such mode without workarounds?
The container already requires quite a lot of trust, but I would understand uncertainty regarding bulletproof configuration.

What you describe is the safest and conceptually simplest solution, but it is not trivial to correctly configure the firewall for a running container. What about this? Would this work?

**Comment by erik-wramner** [comment]
It is certainly trivial to setup a single drop rule for a fixed port compared to configuring Postfix with its thousands of options in a foolproof way. As for the comment about a running container, the firewall should of course not be in the container but in front of the host or (worst case) on the host.

It is quite possible that you can find a way to do what you want by configuring Postfix, but again I personally would not trust it if my job was on the line ;-).

If you find a way using the existing configuration options (user patches script or configuration files in config) we can always document that in the wiki with disclaimers about possible loop-holes.

**Comment by aendeavor** [comment]
This seems to have stalled. I will close this due to inactivity. Feel free to re-open if this isn't the case or if there is more.
