### ISSUE TITLE
Support for shared mailboxes

### ISSUE THREAD

**Issue by matejak** [tomav/docker-mailserver#1625]
## Is your feature request related to a problem?

Shared mailboxes are a standard IMAP feature, and the container setup doesn't make it easy to configure this feature.

## Describe the solution you'd like

Minor restructuring of config files, so users can add a shared mailbox setup by providing additional configuration content or defining env variables without having to alter existing configuration.

## Who will that feature be useful to?

Enterprisey setup are likely to benefit from this.

## What have you done already?

I have modified existing configuration, and got a shared mailbox setup working.

## What are you going to contribute?

If this feature is appreciated, I can contribute changes that are needed, I will just need feedback and review.

**Comment by aendeavor** [comment]
This sounds like a very interesting addition @matejak. I especially agree that this would benefit, you said "enterprisey", users. I would like to mention that we will need to preserve some backwards compatibility. What I mean to say is that we cannot immediately introduce breaking configuration changes. I'm not sure whether these breaking changes must exist, I just wanted to mention it.

Furthermore, I would like to hear @erik-wramner's perspective too. Having feedback from more people is in many cases better than from one.

**Comment by erik-wramner** [comment]
@matejak as long as the change is backwards compatible (at least when disabled) it sounds great!

**Comment by m-a-v** [comment]
@matejak Do you have a fork where we can see the needed changes?

**Comment by matejak** [comment]
I have come up with a draft, I expect to polish it more over the weekend, so it may be worth to postpone looking at it for a couple of days.

**Comment by aendeavor** [comment]
Closed due to migration to [docker-mailserver/docker-mailserver](https://github.com/docker-mailserver/docker-mailserver). Please re-open over there :D
