### ISSUE TITLE
Can't login in to POP3 server

### ISSUE THREAD

**Issue by benebsiny** [tomav/docker-mailserver#1631]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [X] Other

## Description
I've followed the instruction to build the mail server, and add mail account by setup.sh, and I can connect to POP3 server, but I can't login.

The following is the detail about what I do to configure the mail server:
1. I set **ENABLE_POP3** to `1` in `env-mailserver`.
2. I set **HOSTNAME** to my computer's name (I seached for my computer's name by `hostname` command), and set **DOMAINNAME** to `"localhost"` in `.env`.
3. I added `110:110` to export port in `docker-compose.yml`.
4. I created an account by `./setup.sh email add hello@localhost 123456`.
5. `./setup.sh config dkim`.
6. `docker-comose up -d mail`.
7. I was using telnet to connect to the pop3 server:
```
$ telnet localhost 110
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
+OK Dovecot (Debian) ready.
USER hello
+OK
PASS 123456
-ERR [AUTH] Authentication failed.
Connection closed by foreign host.
```
I can't login to the POP3 server. I was wondering that what was wrong. Thank you!

**Comment by aendeavor** [comment]
Hey @benebsiny. This is most likely a configuration error on your side, or other would report this too. Therefore I'll flag this as priority 3, just so you know.

My first guess would be to use `./setup.sh email add account@<HOSTNAME>.localhost`.

What do you think @erik-wramner?

**Comment by benebsiny** [comment]
I just found what's wrong, I have to login with username `hello@localhost` instead of `hello`. Sorry for my stupid question. I'm sorry.

**Comment by aendeavor** [comment]
> I just found what's wrong, I have to login with username `hello@localhost` instead of `hello`. Sorry for my stupid question. I'm sorry.

Glad you could fix it!
