### ISSUE TITLE
Recipient address rejected: User unknown in local recipient table

### ISSUE THREAD

**Issue by benebsiny** [tomav/docker-mailserver#1633]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [X] Other

## Description
I've create two account which are `hello@mail.benny.com` and `hello2@mail.benny.com` repectively by setup.sh. I try to send mail from `hello@mail.benny.com` to `hello2@mail.benny.com`,  an error occurred with message `550 5.1.1 <hello2@mail.benny.com>:  Recipient address rejected: User unknown in local recipient table`. What's wrong? Am I forgot to configure something?
(P.S. I've configured `/etc/hosts` by adding `127.0.0.1 mail.benny.com`)

**Comment by aendeavor** [comment]
Which `/etc/hosts` did you configure?

**Comment by benebsiny** [comment]
I configured it in host

**Comment by aendeavor** [comment]
Have a look [here](https://serverfault.com/questions/179419/postfix-recipient-address-rejected-user-unknown-in-local-recipient-table). This error does not seem to be related to a bug in Docker-Mailserver.

Furthermore, we'll need more logs and configuration settings from you.

**Comment by benebsiny** [comment]
Thanks for the link, I followed https://serverfault.com/a/999944 , running `newaliases` in docker container to solve this problem.

**Comment by gitfeber** [comment]
I had the same problem. For me this comment helped: https://serverfault.com/a/347658
The default config of docker-mailserver looks like this: 
`mydestination = $mydomain, localhost.$mydomain, localhost`
Just removed the first var so theres only these left:
`mydestination = localhost.$mydomain, localhost`

This worked for me!
