### ISSUE TITLE
Add account without restart container

### ISSUE THREAD

**Issue by pyy** [tomav/docker-mailserver#1639]
## Subject

* [x] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
## Description

Hello, I would like to ask if this is the correct way to add/update/del an email account without `docker-compose down && docker-compose up -d`? Is this enough? Thank you.

```
./setup.sh email add <email> <password>
./setup.sh debug login supervisorctl restart dovecot
./setup.sh debug login supervisorctl restart postfix
```

I would like to add the answer to wiki:
https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-to-alter-the-running-mailserver-instance-without-relaunching-the-container

##
By the way,  what service is "mailserver" in supervisorctl list?

```
# supervisorctl
amavis                           RUNNING   pid 422, uptime 0:05:40
...
dovecot                          RUNNING   pid 1244, uptime 0:05:28
fail2ban                         RUNNING   pid 338, uptime 0:05:42
fetchmail                        STOPPED   Not started
mailserver   <--                    RUNNING   pid 8, uptime 0:05:49
opendkim                         RUNNING   pid 284, uptime 0:05:43
opendmarc                        RUNNING   pid 292, uptime 0:05:43
postfix                          RUNNING   pid 1102, uptime 0:05:29
....
```

Thank you

**Comment by aendeavor** [comment]
I'm giving this question to @erik-wramner, I'm into Bash, but not Dovecot :)

**Comment by erik-wramner** [comment]
You just add the account (email add), no need to restart. There is a script running inside the container that checks for changes. It should react and update the postfix/dovecot files after a while. It will also restart postfix/dovecot as needed without restarting the entire container.

As for mailserver it is the start script. It is responsible for changing configuration files on startup and starting all the other daemons.

**Comment by pyy** [comment]
Thank you @erik-wramner . How about other commands from `setup.sh` script, should I restart the container to take it effect?

**Comment by erik-wramner** [comment]
In general the answer is no. I think you need to restart for dkim/ssl changes and possibly for relay configuration as well.
