### ISSUE TITLE
blocked using zen.spamhaus but domain is not in the list

### ISSUE THREAD

**Issue by s0ftcorn** [tomav/docker-mailserver#1640]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [x] Other

## Description

mout-xforward.web.de gets blocked using zen.spamhaus.org but when i look it up on spamhaus its not in their list. What is going on here?

**Comment by aendeavor** [comment]
`mout-xforward.web.de` really does not seem to be in the list. Have you read SpamHouses message regarding the case when it is not listed, but you are still being blocked` Here is the [link](https://www.spamhaus.org/faq/section/DNSBL%20Usage). Please read this thoroughly and report back here what you found.

This could be a configuration error as well? Are you 100% sure you are being blocked on this domain?

**Comment by s0ftcorn** [comment]
Forgot to mention: i dont own this domain. The problem is receiving mails. We are getting important e-mails from a handful of people who have their mail adress there. So nearly every morning i get:

> message reject detail
> ---------------------
>   RCPT
>     Relay access denied (total: 3)
>            2   hostwindsdns.com
>            1   156.96.46.125
>     blocked using zen.spamhaus.org (total: 3)
>            2   mout-xforward.web.de
>            1   62.76.75.186

And as far as i know i cant just put the e-mails on the whitelist, because their outgoing mailserver would still get blocked

**Comment by aendeavor** [comment]
Alright, I researched and found that you're actually wrong, it's in the list, but in another way:)
You can do the following:

``` BASH
$ dig mout-xforward.web.de
```

The result contains:

``` BASH
;; ANSWER SECTION:
mout-xforward.web.de.	274	IN	A	82.165.159.45
mout-xforward.web.de.	274	IN	A	82.165.159.4
mout-xforward.web.de.	274	IN	A	82.165.159.34
mout-xforward.web.de.	274	IN	A	82.165.159.35
mout-xforward.web.de.	274	IN	A	82.165.159.3
mout-xforward.web.de.	274	IN	A	82.165.159.2
```

Already the first IPv4 address is listed:

![Screenshot_2020-10-04 The Spamhaus Project - Blocklist Removal Center Results](https://user-images.githubusercontent.com/44545919/95022500-fcf93f00-0677-11eb-947e-8f8aba5b31f9.png)

So it actually is listed, just as an IP (I didn't think of looking this up earlier). We cannot do something about this, you must talk with the people you're receiving these E-Mails from to remove these blocks.

As this has been solved and is not related to a bug in docker-mailserver, I'll close this.
