### ISSUE TITLE
Postfix do not relay disposition-notification messages

### ISSUE THREAD

**Issue by salviof** [tomav/docker-mailserver#1644]
Im using postfix with  relay variables, and sends thats works fine.
But when show mailq  i found some messages in queue , with Content-Type: message/disposition-notification,
https://tools.ietf.org/html/rfc8098

All queue emails got this error:  Connection timed out -> (My scenario works only with relay)

Thats generate garbage in server and crash the rfc8098 notification solution

### *What* is affected by this bug?
the disposition-notification are not working 

### *When* does this occur?
When Postfix try send a disposition-notification, and ignore relay config

## *How* do we replicate the issue?
1.Define a relay service like Simple mail service from amazon
2.Receve mails whos use   rfc8098 notification s
3.check mailq on mailserver docker instance (must not be able to send without relay
4.

## Your Environment

* Amount of RAM available: NOT APPLICABLE
* Mailserver version used: NOT APPLICABLE 
* Docker version used: NOT APPLICABLE
* Environment settings relevant to the config: 

OVERRIDE_HOSTNAME=
DMS_DEBUG=0
ONE_DIR=0
POSTMASTER_ADDRESS=suporte@xxxxxxxxxxHidden
PERMIT_DOCKER=connected-networks
TLS_LEVEL=
SPOOF_PROTECTION=1
 further explanation.
ENABLE_SRS=0
ENABLE_POP3=1
ENABLE_CLAMAV=1
ENABLE_FAIL2BAN=1
ENABLE_MANAGESIEVE=1
POSTSCREEN_ACTION=enforce
SMTP_ONLY=
SSL_TYPE=letsencrypt
VIRUSMAILS_DELETE_DELAY=
ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
POSTFIX_DAGENT=
POSTFIX_MAILBOX_SIZE_LIMIT=
POSTFIX_MESSAGE_SIZE_LIMIT=282400000
REPORT_RECIPIENT=1
REPORT_SENDER=
REPORT_INTERVAL=daily
ENABLE_SPAMASSASSIN=0
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=6.31
SA_SPAM_SUBJECT=***SPAM*****
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
ENABLE_LDAP=
# empty => no
# yes => LDAP over TLS enabled for Postfix
LDAP_START_TLS=
LDAP_SERVER_HOST=
LDAP_SEARCH_BASE=
LDAP_BIND_DN=
LDAP_BIND_PW=
LDAP_QUERY_FILTER_USER=
LDAP_QUERY_FILTER_GROUP=
LDAP_QUERY_FILTER_ALIAS=
LDAP_QUERY_FILTER_DOMAIN=
DOVECOT_TLS=
DOVECOT_USER_FILTER=
DOVECOT_PASS_FILTER=
DOVECOT_MAILBOX_FORMAT=maildir
ENABLE_POSTGREY=0
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_TEXT=Delayed by postgrey
POSTGREY_AUTO_WHITELIST_CLIENTS=5
ENABLE_SASLAUTHD=0
SASLAUTHD_MECHANISMS=
SASLAUTHD_MECH_OPTIONS=
SASLAUTHD_LDAP_SERVER=
SASLAUTHD_LDAP_SSL=
SASLAUTHD_LDAP_BIND_DN=
SASLAUTHD_LDAP_PASSWORD=
SASLAUTHD_LDAP_SEARCH_BASE=
SASLAUTHD_LDAP_FILTER=
SASLAUTHD_LDAP_START_TLS=
SASLAUTHD_LDAP_TLS_CHECK_PEER=
SASL_PASSWD=
SRS_EXCLUDE_DOMAINS=
SRS_SECRET=
DEFAULT_RELAY_HOST=
RELAY_HOST=email-smtp.uXXXXXXXXXXXhidden
RELAY_PORT=uXXXXXXXXXXXhidden
RELAY_USER=uXXXXXXXXXXXhidden
RELAY_PASSWORD=uXXXXXXXXXXXhidden

atly formatted when the issue is posted.

**Comment by aendeavor** [comment]
Thanks for submitting an issue. Please fill in the **Actual Behavior** and **Expected Behavior** fields.

I'm not an expert when it comes to relays. Since this looks very much like a bug in `docker-mailserver`, I will tag it appropriately.

@erik-wramner can you see the problem here?

**Comment by erik-wramner** [comment]
I'm not using relay either, but I agree that this is a bug. Not sure if the bug is in docker-mailserver (i.e. bad configuration) or upstream though. We'll have to investigate.

**Comment by aendeavor** [comment]
@salviof Because of missing resources, you'd need to investigate in this yourself.
