### ISSUE TITLE
have an ENV variable for recipient_delimiter

### ISSUE THREAD

**Issue by solariane** [tomav/docker-mailserver#1649]
Would like to be able to set multiple recipient_delimiter @once with having to manually change conf files…

actually I tried but don't really get why it failed ( chg done in postfix/main.cf + dovecot/conf.d/90-plugin.cf…even tried 90-sieve.cf ). probably need to change something in master.cf too…

**Comment by aendeavor** [comment]
Hey @solariane. Thanks for opening an issue which would make _docker-mailserver_ better. Sadly, with your description, we cannot help you, as we have no logs, no configuration files, and no used template.

CONTRIBUTING.md clearly states one must use the issue template. This is done so we can manage this issue tracker. Please follow this guide by either changing this issue or creating a new one.

In case you chose the pormer, please re-open this issue, I will take care of the labels.
