### ISSUE TITLE
LDAP. Recipient address rejected: User unknown in virtual mailbox table; 

### ISSUE THREAD

**Issue by shulenkov-roman** [tomav/docker-mailserver#1650]
Greetings. I had a problem with working LDAP.
If I use a configuration without LDAP I have no errors. This configuration allows me to send and receive mail.

version: '3.8'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail         
    domainname: mydomain.com  
    container_name: mail    
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
      - SSL_TYPE=letsencrypt
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:
This configuration completely works for me. But I need docker-mailserver with LDAP.

If I use LDAP configuration I have problems.

version: '3.8'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail          
    domainname: domain.com  
    container_name: mail    
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
       - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
      - SSL_TYPE=letsencrypt
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0    

      # >>> Postfix Ldap Integration
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=mydomain.com
      - LDAP_SEARCH_BASE=ou=people,dc=mydomain,dc=com
      - LDAP_BIND_DN=cn=admin,dc=mydomain,dc=com
      - LDAP_BIND_PW=MyPassword
      - LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_ALIAS=(|(&(mailAlias=%s)(objectClass=PostfixBookMailForward))(&(mailAlias=%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE)))
      - LDAP_QUERY_FILTER_DOMAIN=(|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailAlias=*@%s)(objectClass=PostfixBookMailForward)))
      # <<< Postfix Ldap Integration

       <<< Dovecot Authentication   
      - DOVECOT_PASS_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
      - DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
      - DOVECOT_USER_ATTRS=mailHomeDirectory=home,mailUidNumber=uid,mailGidNumber=gid,mailStorageDirectory=mail   
      # <<< Dovecot Authentication

      # >>> SASL Authentication
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=mydomain.com
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=mydomain,dc=com
      - SASLAUTHD_LDAP_PASSWORD=MyPassword
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=mydomain,dc=com
      - SASLAUTHD_LDAP_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%U))
      # <<< SASL Authentication

      #- POSTMASTER_ADDRESS=postmaster@mydomain.com
      #- POSTFIX_MESSAGE_SIZE_LIMIT=100000000
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:

With this configuration of the mail server, I can send mail to other mail services (for example, Google mail). I can send mail and receive mail inside my service. But I cannot accept mail from another mail service. If I send mail from another mail server I get an error:  Oct 14 15:20:40 mail postfix/smtpd[2108]: NOQUEUE: reject: RCPT from xxxxxx .... Recipient address rejected: User unknown in virtual mailbox table;   when submitting, I use the view of the sender field: user@mydomain.com. If I use user@mail.mydomain.com. I get postfix/smtpd[2108]: NOQUEUE: reject: RCPT from ..... recipient address rejected: User unknown in local recipient table;

root@mail:/etc/postfix# cat main.cf | grep virtual
virtual_transport = lmtp:unix:/var/run/dovecot/lmtp
virtual_mailbox_domains = /etc/postfix/vhost, ldap:/etc/postfix/ldap-domains.cf
virtual_mailbox_maps = ldap:/etc/postfix/ldap-users.cf
virtual_alias_maps = ldap:/etc/postfix/ldap-aliases.cf, ldap:/etc/postfix/ldap-groups.cf
virtual_mailbox_limit = 0

root@mail:/etc/postfix# cat ldap-domains.cf       
bind             = yes
bind_dn = cn=admin,dc=mydomain,dc=com
bind_pw = MyPassword
query_filter = (|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailAlias=*@%s)(objectClass=PostfixBookMailForward)))
result_attribute = mail
search_base = ou=people,dc=mydomain,dc=com
server_host = mydomain.com
start_tls        = no
version          = 3

root@mail:/etc/postfix# cat ldap-users.cf   
bind             = yes
bind_dn = cn=admin,dc=mydomain,dc=com
bind_pw = MyPassword
query_filter = (&(mail=%s)(mailEnabled=TRUE))
result_attribute = mail
search_base = ou=people,dc=mydomain,dc=com
server_host = mydomain.com
start_tls        = no
version          = 3

who can help me?

**Comment by aendeavor** [comment]
This could be related to #1647, where Dovecot is not working on `stable`.

**However, please use the issue template for bug reports and format the YAML correctly**. This way we can help you a lot better, as it's easier to spot mistakes. Please re-format your issue.

**Comment by shulenkov-roman** [comment]
I found a mistake, one field in the LDAP schema has a different name. Everything is working. Thanks for the answer.
