### ISSUE TITLE
Relaying based on recipient domain

### ISSUE THREAD

**Issue by lukecyca** [tomav/docker-mailserver#1652]
## Is your feature request related to a problem?
My mail server delivers most mail directly. I've spent years cultivating an IP with good reputation, keeping it off blacklists, etc. However there is one (major) host that has blocked an entire range. I've tried to request them to whitelist me but to no avail.

## Describe the solution you'd like
Despite great philosophical regret, I am ready to give up and just send these emails through a 3rd party relay like SES or Sendgrid. I would really like to continue to send most email directly, and just use the relay for specific recipient domains. Is this possible?

## Alternatives you've considered
1. Send everything through a relay. This would work but would require a larger paid plan with the relay. It also gives up the good IP reputation I've cultivated, and undermines the distributed nature of how email ought to function.

2. Move to another host. This would be very disruptive in that I would get a brand new IP with no reputation. It may fix this problem would be likely create several new ones.

## Who will that feature be useful to?
As independent email server operators, we all suffer from the spam-fighting arms race. Many of us probably just send everything through one of the big relays. This feature would allow us to have a compromise.

## What have you done already?
I've looked at [this page](https://github.com/tomav/docker-mailserver/wiki/Configure-Relay-Hosts) and found that it's possible to do this based on sender, but not based on recipient.

## What are you going to contribute?
I can contribute research, implementation, testing, etc. At this point consider this a request for comments. Does anyone have this problem? Does anyone think this would be a useful solution?

**Comment by aendeavor** [comment]
Hey @lukecyca. I ca see your point and consider this feature worth adding:)

However, you'd need to implement this yourself, since other contributors, including me, do not have time. If that's not a problem for you, we will happily review this, when it's done.

**Comment by cottonthread** [comment]
> ## Is your feature request related to a problem?
> My mail server delivers most mail directly. I've spent years cultivating an IP with good reputation, keeping it off blacklists, etc. However there is one (major) host that has blocked an entire range. I've tried to request them to whitelist me but to no avail.
> 
> ## Describe the solution you'd like
> Despite great philosophical regret, I am ready to give up and just send these emails through a 3rd party relay like SES or Sendgrid. I would really like to continue to send most email directly, and just use the relay for specific recipient domains. Is this possible?
> 
> ## Alternatives you've considered
> 1. Send everything through a relay. This would work but would require a larger paid plan with the relay. It also gives up the good IP reputation I've cultivated, and undermines the distributed nature of how email ought to function.
> 2. Move to another host. This would be very disruptive in that I would get a brand new IP with no reputation. It may fix this problem would be likely create several new ones.
> 
> ## Who will that feature be useful to?
> As independent email server operators, we all suffer from the spam-fighting arms race. Many of us probably just send everything through one of the big relays. This feature would allow us to have a compromise.
> 
> ## What have you done already?
> I've looked at [this page](https://github.com/tomav/docker-mailserver/wiki/Configure-Relay-Hosts) and found that it's possible to do this based on sender, but not based on recipient.
> 
> ## What are you going to contribute?
> I can contribute research, implementation, testing, etc. At this point consider this a request for comments. Does anyone have this problem? Does anyone think this would be a useful solution?

Maybe my thread can help you: https://github.com/tomav/docker-mailserver/issues/1470#issuecomment-619367183

**Comment by aendeavor** [comment]
@cottonthread Thanks, I did not remember. @lukecyca could you try this and report back?

**Comment by aendeavor** [comment]
Closed due to inactivity.
