### ISSUE TITLE
Flagging incoming mails for DKIM/SPF mismatch and external networks

### ISSUE THREAD

**Issue by dmuensterer** [tomav/docker-mailserver#1656]
Is there currently functionality to flag incoming mails if they are from an external mail delivery agent or if there are DKIM/SPF mismatches?

## Is your feature request related to a problem?

It is great security practice to flag mails from external networks to make the user aware of it.
This can prevent social engineering like CEO fraud or phishing.

Additionally, it would be great to offer the opportunity to flag mails whose domain-name's SPF record does not check out.
Fail (e.g. `-all`) and softfail (e.g. `~all`) according to RFC 7208 should have the possibility to be flagged. 

## Describe the solution you'd like

Changing the mail subject to be prefixed by a customizable flag according to the severity.
This could for example be `[EXTERNAL NETWORK, CAREFUL WITH LINKS AND ATTACHMENTS]` or `[WARNING: IP POSSIBLY UNAUTHORIZED]`

## Alternatives you've considered

As an alternative, the above mentioned flags could be added in the beginning of the mail instead of in the subject.

## Who will that feature be useful to?

An external flag will add a great layer of defense to any user working in a business environment.
SPF/DKIM flags add a security layer for every user, as there should be no SPF/DKIM mismatch for any mail server configuration.

**Comment by aendeavor** [comment]
I really like this idea, especially since you mentioned

> It is great security practice [...] This can prevent social engineering like CEO fraud or phishing.

and I think you're totally correct there. Can you implement something like this?

**Comment by dmuensterer** [comment]
I am glad you like the idea!
Until now, I haven't found any possibility to implement this in the pre-existing modules used in docker-mailserver.
My gut tells me, this should be done at a SpamAssassin level, expecially because SpamAssassin already has existing [measures to check for SPF,DKIM and external network behaviour](https://spamassassin.apache.org/full/3.2.x/doc/Mail_SpamAssassin_Conf.html).
I need to say that I am a little surprised even that this was never implemented in SpamAssassin as it is actually quite common practice in the corporate world.

Also, when modifying the message body we need to be careful not to mess up the signature.

**Comment by aendeavor** [comment]
Very true @dmuensterer. Reach back to all the contributors you can find here. The reason you have to this on your own right now is that all of us have something to work on (see the PRs). I guess you proposed a feature like this for the first time, but there are some people here which may be able to help you. Sadly. I am not (more of a Bash and Systems Programming Languages guy myself), but we're not in a hurry. If this ends up merged, I may need to change to `:latest` for a while until this is in `:stable` :)

**Comment by aendeavor** [comment]
This issue has become stale. What's the current status?

**Comment by aendeavor** [comment]
I tried to look for a solution yesterday. Postfix's `check_headers` was a bummer since it is impossible to accomplish the goal of this issue with it. SpamAssasin I think offers a solution, but this is not without _a bit_ of work. At the moment, I'd advise to do the following of SPF/DKIM really is a concern:

Create a user-patches file as documented in the `README` and put

``` BASH
cat >/etc/postfix/maps/header_checks.pcre << EOI
# /^Received-SPF: Fail.*/ REJECT SPF failures are rejected
# /^Authentication-Results:.*spf=fail .*/ REJECT SPF failures are rejected
/^Authentication-Results:.*dkim=fail .*/ REJECT DKIM failures are rejected
/^Authentication-Results:.*dmarc=fail .*/ REJECT DMARC failures are rejected
EOI

sed -i -E 's/(.*-o receive_override_options=no_header_body_checks.*)/# \1 # commented by user-patches.sh/' /etc/postfix/master.cf
```

in it. This will block DKIM/DMARC mismatches, but let SPF mismatches through. This is not as nice as the original solution, but very easily implemented. If you come back to this issue @dmuensterer I will gladly re-open this issue if you found a solution. But I will close this off for now since it has become stale.
