### ISSUE TITLE
Dovecot killed by Supervisor without restarting

### ISSUE THREAD

**Issue by erdos4d** [tomav/docker-mailserver#1659]
I've had supervisor kill dovecot many times and it never restarts it. I will get a message from someone about roundcube not connecting to the server anymore, then when I log in and check the output I will find a line similar to this:

`INFO reaped unknown pid {SOME_PID}`

When I check the mail logs, I will find this in mail.warn:

`mail dovecot: master: Warning: Killed with signal 15 (by pid=1 uid=0 code=kill)`

And that's it. This has been happening on a production server so I have been restarting ASAP and looking for answers later, so I don't know if traces of what is happening are being left behind in the container, but I haven't noticed any other logs that seem related to the issue. It has happened about 5 times now and each time I can't find anything odd that precipitated it either. What is also strange is that supervisor never restarts dovecot. Does anyone have any ideas?

**Comment by aendeavor** [comment]
This is worth investigating. Strangely enough, you could not find any log entries? That makes it orders of magnitude more difficult.

When I had a look at some Google search results, the forum entries always pointed towards monitoring software producing these errors. Since `supervisorctl` is responsible however, I'm less sure about that. Could you double check this?

Can you try to get the most verbose logging you can so we get some starting point. Without these logs, debugging this problem remotely is just luck-based guessing.

**Comment by erdos4d** [comment]
Is it safe to run with DMS_DEBUG=1 in production? If so, I will switch that on and try to catch it. It has happened at bad times until now, so I haven't had a chance to debug it any, I just have to restart. That actually could be a clue, it usually happens when people are using the server a lot. I'm running on a machine with 2GB of ram and 2GB of swap, so I really doubt it is a resources issue though. There was no monitoring software in place when it was happening too, though I added a healthcheck now and am waiting for it to happen again. I will post everything I can get when it happens. Thanks for the time on this.

**Comment by aendeavor** [comment]
Thanks. I noticed that when F2B and ClamAV are enabled, the container can use up to 1.5GiB of RAM.

**Comment by casperklein** [comment]
With `DMS_DEBUG=1`, `start-mailserver.sh` prints some more information on container start. Also `check-for-changes.sh` may use it. But no log level is changed, e.g. from postfix afaik.

**Comment by aendeavor** [comment]
That's what I actually meant @casperklein :)

**Comment by erik-wramner** [comment]
My guess is that this is the Linux OOM killer in action, not in Docker but on the host.

**Comment by aendeavor** [comment]
Yeah, that's what I think as well.

**Comment by casperklein** [comment]
If that's the case, there should be a syslog entry on the host. @erdos4d can you verify that?

**Comment by erik-wramner** [comment]
@erdos4d, any progress on this? Did you find any host logs?

**Comment by erdos4d** [comment]
@erik-wramner, @casperklein, @aendeavor many thanks for your time with this. It has not repeated itself in the week since, so I have no logs. I suspect there was some sort of issue with amavis because that was going into a restart loop around this same time, maybe it triggered the OOM killer like @erik-wramner suggested. Perhaps this was collataral damage. If you wish to close the issue, I am ok with it and will reopen if it repeats itself. Thanks again for the ideas and your time.
