### ISSUE TITLE
How to block all emails from specific domain or particular email address?

### ISSUE THREAD

**Issue by x-Felix** [tomav/docker-mailserver#1663]
I read through readme.md and wiki - Email filtering w/ Sieve. But not really find the answer I need. 

What I want to achieve is quite basic, just block emails from particular sending address or domain. 
Such as block all email from @abuse.com, or spam@abuse.com. Matched emails can be rejected or discarded. 

Is there easy way to put unwanted domains into a postfix config file at server level or I have to use Sieve email filtering?

Thanks.

**Comment by aendeavor** [comment]
I will mark this appropriately (and as `wontfix`, since this is a question not actually regarding _docker-mailserver_), but to be honest, this issue tracker is not designed to answer this kind of question, since <https://www.google.com> should be sufficient:)

**Comment by myavchik** [comment]
-  Use Postfix smtpd_recipient_restrictions
Add to config/postfix-send-access.cf
`spam@spam.com REJECT`

-  Use Spamassassin
Add to config/spamassassin-rules.cf:
`blacklist_from spam@spam.com`


-  Use Sieve (https://github.com/tomav/docker-mailserver/wiki/Configure-Sieve-filters)
Add to config/user1@domain.tld.dovecot.sieve:

```
require ["fileinto", "reject"];

if address :contains ["From"] "spam@spam.com" {
   fileinto "INBOX.spam";
} else {
     keep;
}
```

**Comment by aendeavor** [comment]
@x-Felix did the answer from @myavchik solve your issue?

**Comment by x-Felix** [comment]
Thank, it works as expected. 
`NOQUEUE: reject: RCPT from mail-oi1-f196.google.com[209.85.167.196]: 554 5.7.1 <xxx@gmail.com>: Sender address rejected: Access denied; from=<xxx@gmail.com> to=<xxx@xxx.com> proto=ESMTP helo=<mail-oi1-f196.google.com>`

**Comment by casperklein** [comment]
>I read through readme.md and wiki - Email filtering w/ Sieve. But not really find the answer I need.

Could you please add the solution to the wiki?

**Comment by kruemelro** [comment]
It could also be archived with the setup command:

`setup email restrict add send spam@spam.com`

**Comment by tinyaustralia** [comment]
> I will mark this appropriately (and as `wontfix`, since this is a question not actually regarding _docker-mailserver_), but to be honest, this issue tracker is not designed to answer this kind of question, since https://www.google.com should be sufficient:)

What a waste of pixel space this comment

**Comment by polarathene** [comment]
> * Use Postfix `smtpd_recipient_restrictions`
>   Add to `config/postfix-send-access.cf`
>   `spam@spam.com REJECT`

FWIW, this functionality is provided by the `setup email restrict add send` command as mentioned:

https://github.com/docker-mailserver/docker-mailserver/blob/cb963a9a8b68c4aa8191cf40c67162a5eb3043e0/target/bin/restrict-access#L32-L43

`setup` CLI wrapper calls the above script:

https://github.com/docker-mailserver/docker-mailserver/blob/cb963a9a8b68c4aa8191cf40c67162a5eb3043e0/target/bin/setup#L32

https://github.com/docker-mailserver/docker-mailserver/blob/cb963a9a8b68c4aa8191cf40c67162a5eb3043e0/target/bin/setup#L99

Config files are checked at startup of container and applied if found:

https://github.com/docker-mailserver/docker-mailserver/blob/cb963a9a8b68c4aa8191cf40c67162a5eb3043e0/target/scripts/startup/setup.d/postfix.sh#L91-L101

---

> It restricts a user `spam@spam.com` from sending on the host and not restrict the host from receiving emails from `spam@spam.com`

As shown above, `smtpd_` rules are for inbound mail arriving to Postfix. You can restrict by sender address or recipient address for an incoming mail.

See Postfix docs on [`smtpd_sender_restrictions`](https://www.postfix.org/postconf.5.html#smtpd_sender_restrictions) for example, where this `setup` command is adding `check_sender_access` with an [Access table](https://www.postfix.org/access.5.html) (the `REJECT` rule), which you can modify the generated config above directly.

---

> What a waste of pixel space this comment

What value did your comment contribute exactly?

Maintaining the project is volunteered time. This is a niche use-case that could be configured without DMS providing assistance. The stance was that maintainers time needs to be prioritized on what DMS actually does and concerns that have a larger impact on users overall, not as personal/free tech support.

By all means if you disagree, you are encouraged to help our community yourself and contribute to the project... but that doesn't seem to be something you do, so why would you act entitled and criticize those who give more than you do?
