### ISSUE TITLE
Possibility to disable spamhaus blocklist

### ISSUE THREAD

**Issue by s0ftcorn** [tomav/docker-mailserver#1664]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [x] Other

## Description

Is it possible to disable the usage of the spamhaus blocklist?

**Comment by casperklein** [comment]
Yes. And please use the issue/wiki search function the next time.

https://github.com/tomav/docker-mailserver/issues/1548#issuecomment-648948857 That is similar to your issue and easy to adapt.

Let us know, if that works for you.

**Comment by aendeavor** [comment]
@casperklein is correct. Re-open if there is something not related to the mentioned issue.
