### ISSUE TITLE
A question about logging information

### ISSUE THREAD

**Issue by stephenkenny** [tomav/docker-mailserver#1665]
We're using tvial/docker-mailserver at our site, it's working very nicely. There is an aspect of logging that I don't understand though.

When I look at the container's mail log files, the earliest entry is dated September 20 (that's in /var/log/mail/mail.info.4.gz).  But when I look at the logs from outside the container, using "docker logs <container_name>",  I seen logging information dating back to July.   I can't figure out where "docker logs" is pulling this information from; I'm curious to know where this information is being stored.

Thanks for any enlightenment
Stephen Kenny
skenny@scss.tcd.ie

**Comment by casperklein** [comment]
The log rotation for e.g. `/var/log/mail/mail.info` is handled by `/etc/logrotate.d/rsyslog`. The following is configured:

    rotate 4
    weekly

Logfiles are rotated _weekly_ and kept for _four_ cycles.

The logs you see using `docker logs`, are the STDOUT output of `start-mailserver.sh`, which "tails" `/var/log/mail.log` infinitely:

https://github.com/tomav/docker-mailserver/blob/451bbfdf40a47d20f9cde6a4b2ce309bf3c36cbe/target/start-mailserver.sh#L2131

**Comment by aendeavor** [comment]
@stephenkenny does this answer your question?

**Comment by stephenkenny** [comment]
I'm afraid it doesn't answer my question.  I understand how log rotation is handled, but the fact is that, in our case at least, "docker logs <mail_container_name>" displays mail log information that goes back much, much further in time than the oldest entry in /var/log/mail/mail.*.gz.  I'm trying to understand where the "docker logs" command is pulling this information from.

I appreciate very much your taking the time to respond to my queries - thanks a lot.
Stephen

**Comment by aendeavor** [comment]
Can you stop and start the container, then try `docker logs`? This should, according to the documentation of this command, only show the current `stdout` of the **new** container, i.e. a small log.

**Comment by stephenkenny** [comment]
I've done that many times - it makes no difference.  "docker logs" still reveals information much older than is currently contained in /var/log/mail/*.

**Comment by aendeavor** [comment]
That very much does not seem related to this container, since the official Docker website states

> The docker logs command batch-retrieves logs present at the time of execution.

Are you using `docker start` to start the container (again)? It seems like you're always using the same container, leading to this situation.

Don't get me wrong, I don't know your skill level, therefore I may ask very simple stuff first - from experience this will solve most of the issues:)

**Comment by stephenkenny** [comment]
No worries about the questions, I'm very grateful that you are taking the trouble to help me out here.    

Yes, I did "docker stop <container>" followed by "docker start <container>".   I guess I could try removing the container, and then running docker compose again to recreate it.

**Comment by aendeavor** [comment]
That's what I figured, haha:)

To explain: `docker stop` will stop the container, effectively "freezing" it. You can still see it with `docker container ls -a` (if you did not specify the `--rm` with `docker run`). `docker stop` will **not** delete the container. Therefore, what was in the logs stays in the logs. You can remove the container with `docker container rm <NAME>`.

On the other hand, `docker start <NAME>` will just boot up the container again, "unfreezing" it. The container **resumes** operation.

**This is very different** from `docker run --rm ...` which will **delete** the container when you're stopping it. The command to start a fresh container is `docker run ...` - you can try it with this command, this should work.

`docker-compose down` and `docker-compose up` should in theory work like `docker stop <NAME> && docker container rm <NAME>` as well as `docker run <NAME>` if nothing more is specified in the `docker-compose.yml` file.

**Comment by stephenkenny** [comment]
Well, it advanced things a bit :-)  I removed the container, and create a new container using "docker compose".   Now running "docker logs <container>"  does indeed  show only very recent logging information.    It's still a mystery as to where exactly Docker was pulling the old logging information from ...

**Comment by aendeavor** [comment]
Were you always using `docker stop`? This would explain it all actually.

**Comment by stephenkenny** [comment]
Well, maybe not everything :-)   -  the mystery of where the older logging information was being stored remains, but at least my logs are a bit shorter!   Anyhow, thank you very much for your time on this.

**Comment by aendeavor** [comment]
Glad we could help. I consider this solved and will close it:)
