### ISSUE TITLE
SMTP Connection time out

### ISSUE THREAD

**Issue by hanzou89** [tomav/docker-mailserver#1668]
mail    | Oct 27 09:06:16 mail postfix/smtp[3288]: connect to gmail-smtp-in.l.google.com[74.125.193.27]:25: Connection timed out
mail    | Oct 27 09:06:16 mail postfix/smtp[3288]: connect to gmail-smtp-in.l.google.com[2a00:1450:400b:c01::1b]:25: Cannot assign requested address

I can receive emails but I can't send.

Someone else with this problem?

**Comment by aendeavor** [comment]
Seems like a IPv6 problem on the one hand. Docker has no IPv6 support out of the box, you will need to enable it.

Can you `exec` into your container and try to connect to the domain manually, which `nc`, or with `telnet`, or maybe just look up whether your server can reach it with `ping` or `nslookup`?

**Comment by erik-wramner** [comment]
Apart from the possible IPv6 issue (second log entry) it is also quite possible that port 25 is blocked. Many ISPs block port 25, so depending on where you are hosting your mail server that could be your problem. Double-checking with nc or telnet is a good idea!

**Comment by hanzou89** [comment]
> 
> 
> Apart from the possible IPv6 issue (second log entry) it is also quite possible that port 25 is blocked. Many ISPs block port 25, so depending on where you are hosting your mail server that could be your problem. Double-checking with nc or telnet is a good idea!

You are in the correcty way, tomorrow I found that EC2 AWS block port 25.
Thank you guys for the support !
