### ISSUE TITLE
Whitelist Host/IP

### ISSUE THREAD

**Issue by s0ftcorn** [tomav/docker-mailserver#1669]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [x] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [ ] Other

## Description

Usually i would create a file /etc/postfix/rbl_override, run postmap on this file and add "check_client_access hash:/etc/postfix/rbl_override" to smtpd_recipient_restrictions.
The problem is that i would have to manually postmap everytime i restart the container, right? Is there any cleaner way to do that? whitelist_clients.local seems like a candidate but from documentation i cant quite put my finger on what this actually does.

**Comment by aendeavor** [comment]
Have you tried the `user-pathes.sh` script method?

**Comment by s0ftcorn** [comment]
To be honest i didnt know about this, since i mostly looked at https://github.com/tomav/docker-mailserver/wiki/List-of-optional-config-files-&-directories and searching the FAQ for keywords didnt hit anything up. Shoul've read it to the end.
Fixes my problem, thank you!
