### ISSUE TITLE
Post-Test-Refactoring

### ISSUE THREAD

**Issue by aendeavor** [tomav/docker-mailserver#1670]
@martin-schulze-vireso Have you had a look at the test on `master`.

``` BASH
not ok 173 wait_for_changes_to_be_detected_in_container fails when timeout is reached
# (from function `repeat_until_success_or_timeout' in file test/test_helper/common.bash, line 38,
#  from function `repeat_in_container_until_success_or_timeout' in file test/test_helper/common.bash, line 71,
#  from function `wait_for_changes_to_be_detected_in_container' in file test/test_helper/common.bash, line 184,
#  in test file test/test_helper.bats, line 169)
#   `TEST_TIMEOUT_IN_SECONDS=0 wait_for_changes_to_be_detected_in_container "${CONTAINER_NAME}"' failed
# bash: /usr/local/bin/helper_functions.sh: No such file or directory
# bash: _monitored_files_checksums: command not found
# Timed out on command: docker exec 2623cb20c5f730c0028575b27f7ef75902812b4fc9f5e2d3976919de545182c1 bash -c source /usr/local/bin/helper_functions.sh; cmp --silent -- <(_monitored_files_checksums) "${CHKSUM_FILE}" >/dev/null
# 2623cb20c5f730c0028575b27f7ef75902812b4fc9f5e2d3976919de545182c1
not ok 174 wait_for_changes_to_be_detected_in_container succeeds within timeout
# (from function `repeat_until_success_or_timeout' in file test/test_helper/common.bash, line 38,
#  from function `repeat_in_container_until_success_or_timeout' in file test/test_helper/common.bash, line 71,
#  from function `wait_for_changes_to_be_detected_in_container' in file test/test_helper/common.bash, line 184,
#  in test file test/test_helper.bats, line 196)
#   `wait_for_changes_to_be_detected_in_container "${CONTAINER_NAME}"' failed
# bash: /usr/local/bin/helper_functions.sh: No such file or directory
# bash: _monitored_files_checksums: command not found
# bash: /usr/local/bin/helper_functions.sh: No such file or directory

...
```

We should intervene here promptly.

**Comment by martin-schulze-vireso** [comment]
I'd think this is an interaction between the parallel changes on my PR and master.

_monitored_files_checksums is loaded via the test_helper.bash, I don't understand why yet, why it is not there anymore.

**Comment by martin-schulze-vireso** [comment]
Could this be the culprit: https://github.com/tomav/docker-mailserver/commit/da8171388f0116b02472d4e47b7f14ffe2abccb6#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R231

**Comment by martin-schulze-vireso** [comment]
Travis seems to have connectivity issues. The jobs only start sporadically and the one that came through failed, because could not download shellcheck.

**Comment by aendeavor** [comment]
> Could this be the culprit: [da81713#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R231](https://github.com/tomav/docker-mailserver/commit/da8171388f0116b02472d4e47b7f14ffe2abccb6#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R231)
> 
> It changes helper_functions.bash to helper-functions.bash, but the PR still references the old name: https://github.com/tomav/docker-mailserver/blob/master/test/test_helper/common.bash#L184

I should have realized this myself, thank you very much. This seems to be the issue.
