### ISSUE TITLE
Error in version of Docker-Compose file

### ISSUE THREAD

**Issue by arghyadeep-k** [tomav/docker-mailserver#1673]
### *What* is affected by this bug?

Installation through Docker Compose.

### *When* does this occur?
While starting mailserver using the docker compose file.

## *How* do we replicate the issue?

Run `docker-compose up -d mail` after downloading all the scripts in Ubuntu 20.04.

## Actual Behavior

Output received:
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

## Expected behavior (i.e. solution)

Should pull docker images and start docker container.

## Your Environment

* Amount of RAM available: 1 GB
* Mailserver version used: Latest
* Docker version used: version 1.25.0
* Environment settings relevant to the config: Ubuntu 20.04 in Oracle Cloud server
* Any relevant stack traces ("Full trace" preferred):
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Comment by arghyadeep-k** [comment]
Workaround: Updating the version as 3.3 in the docker-compose.yml seems to solve the issue.

**Comment by aendeavor** [comment]
This isn't an issue in docker-mailserver as you simply lack the latest Docker Engine (which is 19.xx for Compose 3.8).

Here is a compatibility list: <https://docs.docker.com/compose/compose-file/>
