### ISSUE TITLE
Add SNI support

### ISSUE THREAD

**Issue by martijnhiemstra** [tomav/docker-mailserver#1674]
## Is your feature request related to a problem?
Yes, some mail clients are having problems with the domain certificates

## Describe the solution you'd like
Implement SNI in postfix. Use the tls_server_sni_maps in postfix.

## Who will that feature be useful to?
Everybody implementing ssl/tls

## What are you going to contribute?
I can test the new implementation

**Comment by aendeavor** [comment]
Hey, thanks for opening this issue and contributing this idea.

You will need to implement and test this feature yourself:) When you're ready, provide a PR.
