### ISSUE TITLE
v7.2.0-stable

### ISSUE THREAD

**Issue by aendeavor** [tomav/docker-mailserver#1675]
@erik-wramner I would like to propose a merge-stop on `master` starting on 09 Nov 2020 to wait one more week and then release `v7.2.0-stable`.

What's your take on this?

**Comment by erik-wramner** [comment]
Sorry for the late response. Sounds good to me! I won't merge anything before the release.

**Comment by aendeavor** [comment]
Nice. Could _you_ then release this version?

**Comment by erik-wramner** [comment]
Sure. Preferably this or the next weekend?

**Comment by aendeavor** [comment]
I'd wait one more week, therefore choosing next weekend. Just in case an unforeseen bug appears. We can open another branch in the meantime to merge feature PRs into if this makes sense.

**Comment by erik-wramner** [comment]
The new version is now released!

**Comment by aendeavor** [comment]
Thank's @erik-wramner :)
