### ISSUE TITLE
Ability to configure fallback_transport

### ISSUE THREAD

**Issue by MurphySunset** [tomav/docker-mailserver#1676]
Hi there,

For people using multiple mail systems (let's say G Suite for some users + docker-mailserver for others), it would be nice to be able to have a way to force postfix not to use local mailboxes (`fallback_transport` ?)

Regards,

M/S

**Comment by aendeavor** [comment]
Hey @MurphySunset. Sadly, you did not use one of the issue templates, which makes it more difficult to evaluate your _feature request_ (?)

If you'd like to see this feature, please open another issue using the templates and create a PR for this change, so we can review it.
