### ISSUE TITLE
Publish multi architecture image

### ISSUE THREAD

**Issue by dragoneena12** [tomav/docker-mailserver#1678]
## Is your feature request related to a problem?

It seems to be published only amd64 image. I want to run docker-mailserver in arm64 environment like raspberrypi4.

## Describe the solution you'd like

Add multi-architecture image build workflow.
I think we can use `docker buildx`.

## Who will that feature be useful to?

Those who want to install docker-mailserver in various architectures.

**Comment by aendeavor** [comment]
Literally the second entry on Docker Hiub:

<https://hub.docker.com/r/radicand/docker-mailserver>

Have you even searched before opening this, or is there something wrong with it?

**Comment by dragoneena12** [comment]
@aendeavor I didn't know this. Thank you!

**Comment by guysoft** [comment]
That container upldates slower than ``tvial/docker-mailserver``. Its 3 days behind for some reason. 
It seems like its not automatically built like the repo here with a hook.

**Comment by aendeavor** [comment]
> That container upldates slower than `tvial/docker-mailserver`. Its 3 days behind for some reason.
> It seems like its not automatically built like the repo here with a hook.

You're right @guysoft. This image is not built on a regular basis. There was an issue related to multi-arch builds, #1092. The owner, @radicand is the creator of the ARM version.

> Its also less secure because they could be pushing anything

This could be true, but most likely isn't.

---

If you like, you could investigate this issue and provide a PR so we can build other architectures as well.

**Comment by casperklein** [comment]
btw: Using [buildx](https://docs.docker.com/buildx/working-with-buildx/), building an arm image on an amd64 plattform is no problem: `docker buildx build --platform linux/arm64 -t test .`

> Its also less secure because they could be pushing anything

@guysoft That's also the case for this repo. But you can always verify each commit yourself and then build the image locally.

**Comment by radicand** [comment]
Chiming in here as the arm64 maintainer - two things to note:

1. The arm64 image I maintain is automatic CI using Github actions - you can validate here: https://github.com/radicand/docker-mailserver/ if there are any questions around build transparency. My image lags because I have not found a way to automatically sync upstream changes without requiring me to pull/push manually. This is a hobby, so I don't do this more than a week at most.
2. I would support a long-term enhancement to move the docker build image to this repo using the same Github action I use to build arm64, which leverages buildx - but this requires upstream (here) to switch from building on Dockerhub to building on Github (using actions). It's a very simple process to adjust, but needs coordination.

**Comment by aendeavor** [comment]
@radicand Thanks for joining in. This sounds like a reasonable idea.

Please, someone here open a new **tracking issue** for what @radicand said. I would like to hear other opinions on this too. Moreover, a tracking issue would allow us to _coordinate_ this major change.

**Comment by guysoft** [comment]
> If you like, you could investigate this issue and provide a PR so we can build other architectures as well.

Hey, so I wrote a hook that if you build a ``arm32v7``, ``arm64v8`` and ``amd64`` tag it will bundle them to a single manifest as latest:

https://github.com/guysoft/BackupFriend-docker/blob/master/src/hooks/post_push

The catch is that you need 3 Dockerfiles, one for each arch, I havent found how to solve that.

So here for example 2 Dockerfiles turn in to 6:
https://github.com/guysoft/BackupFriend-docker/tree/master/src

**Comment by aendeavor** [comment]
@guysoft have a look here: <https://github.com/docker-mailserver/docker-mailserver/pull/6>

We appreciate the effort, but this was already solved.
