### ISSUE TITLE
Create docs for all DOVECOT_* environment variables

### ISSUE THREAD

**Issue by simonsystem** [tomav/docker-mailserver#1681]
## Is your feature request related to a problem?
There is no documentation of all possible `DOVECOT_` prefixed enivronment variables:
- DOVECOT_BASE
- DOVECOT_DEFAULT_PASS_SCHEME
- DOVECOT_DN
- DOVECOT_DNPASS
- DOVECOT_HOSTS
- DOVECOT_LDAP_VERSION
- DOVECOT_AUTH_BIND

Currently documented:
- DOVECOT_MAILBOX_FORMAT
- DOVECOT_TLS
- DOVECOT_USER_FILTER
- DOVECOT_USER_ATTRS
- DOVECOT_PASS_FILTER
- DOVECOT_PASS_ATTRS

## Describe the solution you'd like
Create a section for each `DOVECOT_` variable in [README.md](https://github.com/tomav/docker-mailserver/blob/master/README.md#dovecot)

## Alternatives you've considered
Describe that most `DOVECOT_` variables are injected by [configomat](https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L777) processing [dovecot-ldap.conf.ext](https://github.com/tomav/docker-mailserver/blob/master/target/dovecot/dovecot-ldap.conf.ext) on start.

## Who will that feature be useful to?
Everyone, who want to use one of these LDAP specific variables, e.g. `DOVECOT_AUTH_BIND` for better LDAP pasword features.

## What have you done already?
I figured out:
Beside `DOVECOT_MAILBOX_FORMAT`, which is used [here](https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L549), all `DEVOCOT_` variables are gerenated by configomat.

## What are you going to contribute?
I can create a PR for adding these vars to documention, soon. If someone else is faster, just do it please.

## Additional context
Its connected to the `helm-docker-mailserver` issue [#31](https://github.com/funkypenguin/helm-docker-mailserver/pull/31)

**Comment by aendeavor** [comment]
A PR from your side is very much appreciated. Thank you!
