### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by erik-wramner** [tomav/docker-mailserver#1685]
When I run `make` or `make clean all` the build fails:

```
Successfully tagged tvial/docker-mailserver:testing
/bin/bash: -c: line 0: syntax error near unexpected token `fi'
/bin/bash: -c: line 0: `[[ ! -d config.bak ]] && cp -rp config config.bak; fi'
Makefile:19: recipe for target 'backup' failed
```
I'm guessing that we should just remove the `fi` statements? I don't want to do that without asking though as nobody else seems to have encountered this problem.

**Comment by erik-wramner** [comment]
The build does work if I remove the offending fi statements. @aendeavor am I missing something or should I make a PR?

**Comment by aendeavor** [comment]
No, this is absolutely my bad. I wanted to push this to my latest PR but I was so busy that I forgot that and missed it when merging. I will correct this.

**Comment by aendeavor** [comment]
I did not run in this problem myself, but my best guess is that `make` behaves differently with different versions of `bash`. You might be running `bash4`? Even if this wasn't the case, different versions of make could influence the result. Nevertheless, this should be fixed - I provided the PR.

**Comment by aendeavor** [comment]
I hope this is fixed now. Re-open if there is more I forgot.
