### ISSUE TITLE
How to correctly mount traefiks letsencrypt certificates from named volume?

### ISSUE THREAD

**Issue by dhax** [tomav/docker-mailserver#1688]
The recommended way for using Traefik with letsencrypt is to use a named volume to save the certificates. This makes it currently impossible to mount these certificates in the way described in the documentation for docker-mailserver, i.e. one cannot use a subdirectory or file only to mount like this:
```
volumes:
    - /etc/ssl/acme-v2.json:/etc/letsencrypt/acme.json:ro
```

If I try to mount them as read-only mailserver complains about not being able to access them. The only way I got it to work was to mount the whole letsencrypt directory and not restricting it to read-only like this:
```
volumes:
    - traefik-certificates:/etc/letsencrypt
```

This seems to work fine so far. My question basically is if this could have any negative effects on security or risk losing the certificates because of docker-mailserver messing with them.

Thanks!

**Comment by aendeavor** [comment]
Could you point me to this wiki entry?

---

So you have tried

``` YAML
volumes:
    - traefik-certificates:/etc/letsencrypt:ro
```
?

---

I personally would advise again mounting this certificate file with write permissions. In theory, `docker-mailserver` is just reading this file, but you never know. I use Traefik v2 too, but without named volumes, so I can mount the `acme.json` directly and as described. If this is an option for you, do it this way. That's why I#m curious what the wiki entry says, since you're right: File-based mounting with named volumes is not possible (as far as I know).

**Comment by dhax** [comment]
I am running traefik and mailserver using docker-compose with docker-machine deploying on a remote host. Not sure about the risk to accidentally delete the named volume, also in this case the volume would just be recreated and new certs requested again when traefik restarts. I could also mount a local folder on the host, but as I went the other route and struggled to get it working and finally was wondering about negative side effects. Hope this helps other trying to do the same.

Anyhow, what I noticed now is the following behavior when creating traefik, the named volumes and mailserver for the very first time on a newly provisioned docker host:

1. Start Traefik service, the named volume get created.
2. Start tls/letsencrypt configured whoami service as workaround to obtain the certs for the mailserver domain, certs get successful retrieved. TLS is enabled in Traefik dashboard for mail.myrealdomain.org.
3. Stop and remove whoami server.
4. Start docker-mailserver first time with read-only access as in ```volumes: - traefik-certificates:/etc/letsencrypt:ro```
This gives me the following errors:
```
Configuring mail server
mail       | mkdir: cannot create directory '/etc/letsencrypt/live': Read-only file system
mail       | /usr/local/bin/helper-functions.sh: line 84: /etc/letsencrypt/live/mail.myrealdomain.org/key.pem: No such file or directory
mail       |  Error Cannot access '/etc/letsencrypt/live/mail.myrealdomain.org/fullchain.pem' or '/etc/letsencrypt/live/myrealdomain.org/fullchain.pem'
mail       | Starting Misc
mail       | ...
```
5. Remove read-only from traefik-certificates mount, recreate mailserver works without any error:
```
mail       | Configuring mail server
mail       | Cert found in /etc/letsencrypt/acme.json for mail.myrealdomain.org
mail       | Starting Misc
```
6. Add read-only again to the mount and recreate mailserver again shows this message:
```
mail       | Configuring mail server
mail       | /usr/local/bin/helper-functions.sh: line 84: /etc/letsencrypt/live/mail.myrealdomain.org/key.pem: Read-only file system
mail       | Starting Misc
```
Beside that last message by helper-function.sh everything seems to work and checktls.com says all is OK.

So the point here seems if you really need or want to use named volumes you have to mount the volume with write access as it tries to create the 'live/mail.myrealdomain.org' folder within the mounted letsencrypt folder. Not sure why it does that if  it actually should just read the acme.json file already present in the mounted letsencrypt folder.

**Comment by aendeavor** [comment]
I've had a look at the `start-mailserver.sh` script and the corresponding `helper-functions.sh`, and it makes perfect sense for the scripts to write to the volume. As the `acme.json` cannot be natively used by the mailserver, the certificates are extracted and written to the location , e.g. `/etc/letsencrypt/live/mail.myrealdomain.org/key.pem`. Therefore, the `:ro` mount does not work.

This becomes critical when Traefik issues a new certificate, which cannot be written when the `acme.json` is updated when using the named volume with read-only permissions. In theory, there shouldn't be any writes to the `acme.json`, so mounting it with a named volume without `:ro` seems to be fine, but I'm not a fan of it. If you can, use a local volume for the certificate files and mount the file directly.

I will adjust the wiki page accordingly. Thank you for noticing this!

**Comment by aendeavor** [comment]
I just had a look at the wiki, but the mount there  is _not_ a named volume:

``` YAML
volumes:
  - /etc/ssl/acme-v2.json:/acme.json
```

Where are you getting the `traefik-certificates` in

``` YAML
volumes:
    - traefik-certificates:/etc/letsencrypt
```

from?

**Comment by dhax** [comment]
Hi, thanks for confirming that mailserver needs to extract and write the certificates to its local live folder.
The idea to mount a named volume is not in the mailserver wiki, it's just another docker option when setting up traefik and want to use a named volume for whatever reason. When I set up Traefik first I wasn't thinking about or even reading the mailserver wiki, so I got into this situation later...

So the problem with this named volume setup is that when traefik renews the certificates, mailserver can't renew it's extracted version in its own live folder without removing the read-only on the mount and recreating the container again. So for this reason I guess for now the only valid and future proof setup regarding certificates is to mount it like described now in the wiki, i.e. a volume on the host and only mounting the acme.json in read-only mode.

Thanks again for the fast response and this great product in general!

**Comment by 3id0** [comment]
I just encountered the exact same issue when trying the exact same setup as @dhax

I prefer named volumes too. Too bad I have to hardcode the paths to my letsencrypt directory instead of using the named volume I already have.

But is it really an issue of named volumes or is the issue that mounting the file acme.json:ro works and mounting the directory letsencrypt:ro doesn't?

Anyway, maybe a link to this issue could be added to the following section of the documentation?
https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#traefik-v2

**Comment by georglauterbach** [comment]
There were recent changes to the handling of LE certificates, but I think we still need to folder to be read-write - and for good reason. It basically comes down to missing write permissions if you mount the named volume (a directory in this case) `:ro` whereas mounting it `:wr` should in theory work - but that would be bad practice as it allows the mail server to touch the certificate.

> Anyway, maybe a link to this issue could be added to the following section of the documentation?

Feel free to open a PR.
