### ISSUE TITLE
Write to file instead of send outbound

### ISSUE THREAD

**Issue by dextermb** [tomav/docker-mailserver#1689]
## Subject
* [x] I would like to configure a not documented mail server use case
* [x] I would like some feedback concerning a use case

## Description

Hi

I want to create a _blackhole_ SMTP server where outbound emails will be written to file and not sent. Is it possible to configure the image this way?

Thanks in advance

Edit: Potentially being able to set up something like [this][example] would be good.

[example]: https://serverfault.com/questions/451240/how-do-i-set-up-postfix-to-store-e-mail-in-a-file-instead-of-relaying-it

**Comment by aendeavor** [comment]
Hey:) This is a _rather_ special use case. I think this might be perfectly possible. The default mail services could write to a file or directory which is a volume, so you can access it from the outside.

Getting through this procedure however is something **_way_** out of bounds for this issue tracker and would blast the capabilities and resources available for this project. I'm very sorry for this inconvenience.

I will not close this off early but I would like you to consider doing so, as there might pop up some small tips here and there, but definitely not something thorough and complete in its explanation.

**Comment by dextermb** [comment]
If anyone comes across this issue and wants to achieve the same thing I've written up an SMTP logger using Node and Docker ([dextermb/smtp-logger](https://github.com/dextermb/smtp-logger)).

I still need to finish writing documentation, but feel free to post on the issues there if you have any questions.
