### ISSUE TITLE
Possible to separate the services SMTP(frontend) / IMAP(backend)?

### ISSUE THREAD

**Issue by starfoxx82** [tomav/docker-mailserver#1692]
## Subject

* [x] I would like to configure a not documented mail server use case

## Description
I would like to separate the smtp-service (postfix-external) from the imap service (imap-backend). The smtp service should be placed on a dmz docker-host / or a dmz kubernetes cluster. The backend imap service should be placed on an internal separately docker-host / k8s cluster.

### Mailserver- external (frontend)
Postfix will receive e-mails and check the spam/virus stuff. Then, when all is alllright, the mail will be sended to the backend lmtp

### Mailserver- internal (backend)
Dovecot will receive e-mails. The internal users send the e-mails per internal smtpd service and then per mailserver- external (frontend) (maybe smarthost configuration) 

###
Is it possible or am I wrong?

thx

**Comment by aendeavor** [comment]
I guess this is certainly possible, but _a bit_ out of scope for this issue tracker. You can try, of course, but I guess _very_ few people can help you with this as this is rather special. I would suggest you try this on your own, because I'm rather sure this tracker wouldn't be of any help. I'm very sorry for the inconvenience but it's better to say this right away than weeks later:)

**Comment by erik-wramner** [comment]
I agree, it is not supported out of the box. It will be tricky to do. I would suggest looking for other docker images instead with greater separation.

**Comment by aendeavor** [comment]
This issue is marked as stale. Please report back. Otherwise this issue is closed due to inactivity.

**Comment by starfoxx82** [comment]
The separation is tricky, but makeable. I hope that this is right. I still have to test ist.

I have change the following:

# Frontend:
## k8s configmap - file
```
  ENABLE_POSTFIX_VIRTUAL_TRANSPORT: "1"
  POSTFIX_DAGENT: lmtp:inet:intern.mailserver.svc.cluster.local:24
```

# Backend: (manually)
## k8s configmap - file
```
  DEFAULT_RELAY_HOST: "[extern.mailserver.svc.cluster.local]:587"
  RELAY_HOST: extern.mailserver.svc.cluster.local
  RELAY_PORT: "587"
  RELAY_USER: send@example.com
  RELAY_PASSWORD: *************************************************************
```

## Dovecot configuration
  On the internal, i make the following changes in the file /etc/dovecot/conf.d/10-master.conf to fire up the dovecot lmtp service.
```
service lmtp {
  unix_listener lmtp {
    mode = 0660
    group = postfix
  }

  # Create inet listener only if you can't use the above UNIX socket
  inet_listener lmtp {
    # Avoid making LMTP visible for the entire internet
    address = 0.0.0.0
    port = 24
  }
}
```

# Security
A firewall rule has to be added to the security aspect ;-)

Is it possible to have such changes set by variable?

**Comment by aendeavor** [comment]
Although this does not seem like much, you're using K8S and not Compose (or Swarm). My suggestion would be to have this issue when people come across this use-case. Admittedly it's a _very_ rare use case. So

> Is it possible to have such changes set by variable?

yes, it is possible, but I would rather not implement it. The `user-patches.sh` seems to work, and we're streamlining for the common case:)

**Comment by erik-wramner** [comment]
I agree with @aendeavor, it is great that it works but if we make it a supported feature we should add comprehensive tests. Much better to handle it with user-patches.sh for now.

**Comment by starfoxx82** [comment]
I haven't know about the ```user-patches.sh``` file. When i could use this to do some magic what i want, then all right :-)

**Comment by aendeavor** [comment]
You can place a file called `user-patches.sh` in the `config/` directory. This will be executed during startup - for more details see: <https://github.com/tomav/docker-mailserver/blob/master/config/user-patches.sh.dist>

**Comment by aendeavor** [comment]
I will close this in the effort to migrate to the new repo and the clean the tracker of issues;)

**Comment by starfoxx82** [comment]
Hi, ok, do it. :-) thanks for your help

**Comment by 3nprob** [comment]
@aendeavor Curious, where is the new repo located (or is this it)?

**Comment by aendeavor** [comment]
> @aendeavor Curious, where is the new repo located (or is this it)?

This (`docker-mailserver/docker-mailserver`) is it. We migrated the old repo.
