### ISSUE TITLE
Delete email from script

### ISSUE THREAD

**Issue by SharkmanTyp** [tomav/docker-mailserver#1693]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [* ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [ ] Other

## Description

Hi,

I created a script for mass creating mailboxes. It also needs the same to remove them.
What is the command, the equivalent of this:
     docker run --rm -e MAIL_USER = $ {user} -e MAIL_PASS = $ {email} -ti tvial / docker-mailserver: latest / bin / sh -c 'echo "$ MAIL_USER | $ (doveadm pw -s SHA512- CRYPT -u $ MAIL_USER -p $ MAIL_PASS) "'>> config / postfix-accounts.cf

**Comment by casperklein** [comment]
You can use `./setup.sh email del <email>`

[setup.sh](https://github.com/tomav/docker-mailserver/blob/master/setup.sh) takes also care about aliases if configured.

Or invoke [delmailuser](https://github.com/tomav/docker-mailserver/blob/master/target/bin/delmailuser) directly.

**Comment by SharkmanTyp** [comment]
Thank you. It help.
