### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by davidconnard** [tomav/docker-mailserver#1695]
## Subject
I would like some feedback concerning a use case - running on Docker in Windows / NTFS

## Description

First - thanks for an awesome docker image here...!  Very impressive!

However, I'm struggling to run this docker container in Docker in my primary development environment, which is Windows 10 / WSL 2.  I'm wondering if anyone has verified that it works?

I have a docker-compose.yml file that works fine on a Mac, but on a Windows docker, I cannot get the mailserver to run successfully.

I have ONE_DIR=1, and the various mount points pointing to a Windows NTFS filesystem.  I have a single mail account added to the server (I had to exec into the docker container to add the users, because the setup script fails under windows ... something about TTYs, and running winpty with it doesn't help ... which is another thing that makes me suspect that it hasn't been tested under WSL).

Anyhow, the symptoms that I see are that, at startup, I see this error in mail.log:

mail | Nov 25 20:49:09 xyzz dovecot: master: Error: file_dotlock_open(/var/lib/dovecot/instances) failed: Resource temporarily unavailable

then, when I attempt to telnet to port 25 to deliver an email, I get a 451 4.3.0 Error: queue file write error, ie:

$ telnet localhost smtp
Trying ::1...
Connected to localhost.
Escape character is '^]'.
H220 xyzz.domain.au ESMTP
ELO blah
250 xyzz.domain.au
MAIL FROM: <god@example.invalid>
250 2.1.0 Ok
RCPT TO: <foo@xyzz.domain.au>
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
From: <god@example.invalid>
To: <foo@xyzz.domain.au>
Date: now
Subject: yeah yeah

dajklfd
fdajkldf

.
451 4.3.0 Error: queue file write error

... however, there are no errors from this delivery attempt in mail.log (or any other logs I can find):

mail | Nov 25 20:49:33 xyzz postfix/smtpd[892]: 3E3D6610000000122E3: client=unknown[172.30.0.1]
mail | Nov 25 20:50:03 xyzz postfix/cleanup[1020]: 3E3D6610000000122E3: message-id=<>
mail | Nov 25 20:50:03 xyzz opendkim[207]: 3E3D6610000000122E3: no signing table match for 'god@example.invalid'
mail | Nov 25 20:50:03 xyzz opendkim[207]: 3E3D6610000000122E3: no signature data
mail | Nov 25 20:50:07 xyzz postfix/cleanup[1020]: 0CB367D000000002C16: message-id=<20201125095007.0CB367D000000002C16@xyzz.domain.au>
mail | Nov 25 20:50:07 xyzz postfix/smtpd[892]: disconnect from unknown[172.30.0.1] helo=1 mail=1 rcpt=1 data=0/1 commands=3/4

... and that's it.

If I do the exact same thing on a Mac, it works, and the mail is queued into the mailbox.

My guess is that there is some problem with the volume mounts from NTFS filesystems and the file locking, and that dovecot is not starting successfully as a result.

My docker-compose is:

version: "3.8"
services:
  mail:
    image: tvial/docker-mailserver:latest
    restart: always
    hostname: xyzz                            # ${HOSTNAME}
    domainname: domain.au            # ${DOMAINNAME}
    container_name: mail                  # ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "465:465"
      - "587:587"

    environment:
      - PERMIT_DOCKER=network
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_JUNK=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_POP3=1
      - ENABLE_QUOTAS=0
      - ONE_DIR=1
      - DMS_DEBUG=1
      - POSTFIX_INET_PROTOCOLS=ipv4

    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

    volumes:
      - type: bind
        source: ./runtime/mail/maildata
        target: /var/mail

      - type: bind
        source: ./runtime/mail/mailstate
        target: /var/mail-state

      - type: bind
        source: ./runtime/mail/logs
        target: /var/log/mail

      - type: bind
        source: ./runtime/mail/config
        target: /tmp/docker-mailserver

Any help or assistance would be appreciated!!  And/or adding to the guides recommendations on how to run under Windows / WSL 2 / NTFS file systems.

Thanks!!

**Comment by aendeavor** [comment]
Hey there! You're right, this image works on Linux (and likely macOS), but we do _not_ officially support Windows, as far as I know.

I would suspect NTFS causing problems as well. We're most likely seeing this on NFS mounts with Kubernetes too.

In the end, Windows support is planned, I'm sorry.

**Comment by davidconnard** [comment]
Understood, and fair enough, I totally understand...  serves me right for using a Windows env to develop an Linux app ... :)  However,  it'd be really helpful to call this out in the docs  ... trying to solve this has cost me a heap of time so far ... finally resorting to double checking on a Mac.

I might see if I can try an alternate FS mount.

Anyhow, thank you for the confirmation.  :)

**Comment by aendeavor** [comment]
I will make sure this ends up in the docs with the next commit:)

**Comment by aendeavor** [comment]
Done with ec290acd1f92e1e44773085df8d8872f6f13cb25.
