### ISSUE TITLE
amavis uid does not match ownership of /var/mail/amavis

### ISSUE THREAD

**Issue by MakerMatrix** [tomav/docker-mailserver#1701]
I'm enjoying my shiny new mail server.  Thank you, it's terrific.  I almost went with mailu but quite by accident landed here. 
 In hindsight that was a great thing.

I was perusing the logs this evening and ran across this:

(cannot update mailbox /var/mail/amavis for user amavis. destination /var/mail/amavis is not owned by recipient)

And, indeed:

root@mail:/var/mail# id amavis
uid=112(amavis) gid=114(amavis) groups=114(amavis),110(clamav)

root@mail:/var/mail# ls -la /var/mail/amavis
-rw------- 1 docker docker 871 Dec  3 03:18 /var/mail/amavis

And from the host side:
-rw------- 1  5000           5000  871 2020-12-02 21:18 amavis

So I chowned it to 112.  Not sure what if anything of interest will show up here, but I thought I should report it.

Related:  Is there a lightweight curses-based mail client somewhere in the image?  I'm thinking along the lines of pine, so I can manage that mailbox locally, and maybe even remote in for shell-based or scripted email.

**Comment by erik-wramner** [comment]
I think you can remove `/var/mail/amavis` and instead create an alias for the amavis account (using `setup.sh`), so that you get messages sent to amavis to your postmaster account or personal account. The system sometimes sends e-mail to amavis, primarily with warnings from cronjobs owned by the amavis user. Search the issues and you will find many similar cases.

As for pine, no. Most of us probably use webmail through Dovecot. If you want pine you can always mount the mail directory in another docker image that has pine, or by all means install it from `user-patches.sh` at startup.

**Comment by aendeavor** [comment]
@erik-wramner How come that this alias-amavis thing appears for some and not for others. For me, this seems like a bug, but reading through this, is seems like it isn't?

Nevertheless, I'm all with you when it comes to putting this in a more visible location. How about the _Miscellaneous_ section in the README?

**Comment by erik-wramner** [comment]
It appears only when the system needs to send a message to amavis. That only happens when something is wrong, but it does not have to be a serious problem. What happens is that Postfix (or Dovecot) creates a mailbox for the missing user, but it is created with wrong credentials and doesn't work. Probably a mismatch between local accounts and virtual. I'll see if I can add a note somewhere.

**Comment by MakerMatrix** [comment]
It looks like it was sending a cron message about creating a spamassassin cron job?

Subject: Cron <amavis@mail> test -e /usr/sbin/amavisd-new-cronjob && /usr/sbin/amavisd-new-cronjob sa-sync

The main receive/smart relay functions are working for me now but there are still many things about the features that are unclear.  For example, it seems from the above comment that we need to create the postmaster account (or alias) manually?  Are there post-install setup docs somewhere that I missed?  I will look harder.  I'm used to defalt mail setups in full Linux distros that do the basics for out of the box, need to learn about what to do "from scratch."

**Comment by aendeavor** [comment]
Actually, I was thinking the same @MakerMatrix. This step should be automatic, it possible. That's why I was surprised at first.

**Comment by MakerMatrix** [comment]
Maybe I will change this to a feature request.

Following the principle of least surprise, I believe there should be built-in aliases that map amavis, dovecot, and postmaster to root.  Then bsd-mailx should be installed.  It's only 200KB and a strong argument can be made that it should be installed by default on any appliance that claims to manage mail.  This project attracts keyboard warriors and it is completely surprising when /bin/mail and/or /usr/bin/mail does not exist.

Every UNIX I've ever used was configured out of the box like this.  I've made my argument.  Tear it down ;-)

**Comment by aendeavor** [comment]
No need to tear anything down, you'd just need to provide a PR :D

I really like your idea and the changes, and I think you're right with what you're saying. A well reviewed PR can and will improve the current situation. I will make sure to review the changes when you're ready:)

**Comment by MakerMatrix** [comment]
Challenge accepted.  I have a lot to learn about docker and github though, will you please try answer my inevitable dumb questions?

**Comment by aendeavor** [comment]
Of course, as good as I can.

**Comment by MakerMatrix** [comment]
Does building the project require an apt-based system?  I am having issues on CentOS7.

**Comment by casperklein** [comment]
Any Linux host with docker installed should be fine.

**Comment by MakerMatrix** [comment]
The "make clean all" command dies with many dozens of "Cannot remove....:Directory not empty" lines and then:

The command '/bin/bash -o pipefail -c apt-get update -q --fix-missing &&   apt-get -y upgrade &&   apt-get -y install postfix &&   apt-get -y install --no-install-recommends   altermime   amavisd-new   apt-transport-https   arj   binutils   bzip2   ca-certificates   cabextract   clamav   clamav-daemon   cpio   curl   ed   fail2ban   fetchmail   file   gamin   gzip   gnupg   iproute2   iptables   locales   logwatch   lhasa   libdate-manip-perl   liblz4-tool   libmail-spf-perl   libnet-dns-perl   libsasl2-modules   lrzip   lzop   netcat-openbsd   nomarch   opendkim   opendkim-tools   opendmarc   pax   pflogsumm   p7zip-full   postfix-ldap   postfix-pcre   postfix-policyd-spf-python   postsrsd   pyzor   razor   rpm2cpio   rsyslog   sasl2-bin   spamassassin   supervisor   postgrey   unrar-free   unzip   whois   xz-utils   dovecot-core   dovecot-imapd   dovecot-ldap   dovecot-lmtpd   dovecot-managesieved   dovecot-pop3d   dovecot-sieve   dovecot-solr   &&   apt-get autoclean &&   rm -rf /var/lib/apt/lists/* &&   rm -rf /usr/share/locale/* &&   rm -rf /usr/share/man/* &&   rm -rf /usr/share/doc/* &&   touch /var/log/auth.log &&   update-locale &&   rm /etc/postsrsd.secret &&   rm /etc/cron.daily/00logwatch' returned a non-zero code: 1
make: *** [build] Error 1

I'm stumped.  CentOS 7 with the latest docker, docker-compose, etc. from the offical docker-ce repo.

**Comment by aendeavor** [comment]
Make is telling you two things here:

1. A command failed and `make` is unhappy, aborting early
2. The command that is failing is most likely not `make`

The `/bin/bash -o pipefail apt ...` is from the Docker Build process. I don't know why, but the build process for the Dockerfile fails. I would advise to go through the `Makefile` targets one by one, i.e. `clean`, `build`, ... and then see where things are getting rough.

To me, it also seems like the `clean` target has some issues, maybe just related to CentOS. What version of Bash have you installed? Maybe

``` MAKE
-@ [[ -d config.bak ]] && { ... ; } || : 
```

is not well-defined for Bash versions < 5.

**Comment by MakerMatrix** [comment]
Still cannot build this.  The first issue was that my CentOS 7 XFS filesystem doesn't support d_type (needed for the docker overlay FS driver).  Got that fixed by switching to the devicemapper driver.  But now 'make build' dies here:

Step 52/59 : COPY ./target/bin-helper.sh ./target/helper-functions.sh ./target/check-for-changes.sh ./target/start-mailserver.sh ./target/fail2ban-wrapper.sh ./target/postfix-wrapper.sh ./target/postsrsd-wrapper.sh ./target/docker-configomat/configomat.sh /usr/local/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder440010386/target/docker-configomat/configomat.sh: no such file or directory

Got frustrated and spun up an Ubuntu VM - it dies in the same spot.  What provides configomat.sh and why is it not found?  I poked at the Dockerfile and googled a bit - it isn't revealing itself to me.

**Comment by aendeavor** [comment]
Most likely due to missing initialisation of all submodules. You will need to initialise all four with

``` BASH
git submodule update --init --recursive
```

**Comment by MakerMatrix** [comment]
PM is #1709

**Comment by aendeavor** [comment]
Closed due to migration to [docker-mailserver/docker-mailserver](https://github.com/docker-mailserver/docker-mailserver). Please re-open over there :D
