### ISSUE TITLE
Allow to specify specify ldap_tls_cacert_file or/and ldap_tls_cacert_dir

### ISSUE THREAD

**Issue by williamdes** [tomav/docker-mailserver#1704]
https://github.com/tomav/docker-mailserver/blob/3780783145d3fe118f446b850b6cdb22d5146de0/target/start-mailserver.sh#L935

Source: https://blog.sys4.de/cyrus-sasl-saslauthdconf-man-page-en.html
And https://github.com/winlibs/cyrus-sasl/blob/master/saslauthd/LDAP_SASLAUTHD#L215
```
ldap_tls_check_peer (default: no)
Require and verify server certificate. If this option is yes, you must specify ldap_tls_cacert_file or ldap_tls_cacert_dir.
```

Seems to come from https://github.com/tomav/docker-mailserver/pull/980

IMO, the options should be provided to the user

**Comment by erik-wramner** [comment]
Feel free to submit a PR. Alternatively (if you just need to fix this for your server) you can use `user-patches.sh` to set the options at startup.

**Comment by williamdes** [comment]
Hi !
Done in https://github.com/tomav/docker-mailserver/pull/1708 :)
