### ISSUE TITLE
Disable virus/spam checks only for outbound messages

### ISSUE THREAD

**Issue by marcinkunert** [tomav/docker-mailserver#1713]
## Disable virus/spam checks only for outbound messages

* [x] I would like to configure a not documented mail server use case

## Description

Yesterday I've send my first newsletter using this software. It went pretty slow (about 1-2 msg/sec) until I've disabled Spamassasin (ENABLE_SPAMASSASSIN=0). After this change the speed imporoved to something like 50 mails/sec. In the future I also plan to use this image as my incoming mail solution. This would require enabling spamassassin for incoming mails. Is it possible?

**Comment by aendeavor** [comment]
That's a good question, and one I cannot answer. But if I guesses, I would say: yes. I will mark this appropriately, so if someone comes across this, he or she will notice it better.

**Comment by erik-wramner** [comment]
@marcinkunert how do you send the messages? Do you use port 25 by any chance? If you do, try using 587 or 465 with authentication instead. I still think we do virus checks for outbound messages sent that way, but I don't think we do spam checks.

**Comment by marcinkunert** [comment]
@erik-wramner I'm using 587. The name "ENABLE_SPAMASSASSIN" suggests that it's spam check. Nevertheless I've changed the title of this issue.

**Comment by erik-wramner** [comment]
Right. I'm pretty sure it is possible, but I don't know the options. If you can find out how to do it with Postfix it should be easy to add it to docker-mailserver, for example using `user-patches.sh` to tweak the configuration files at startup.
