### ISSUE TITLE
Custom SMTP Milters

### ISSUE THREAD

**Issue by nekrondev** [tomav/docker-mailserver#1714]
## Is your feature request related to a problem?
I am using a custom milter to prevent spam and server probing. Currently I need to fork the base image and patch master.cf to get my milter included.

## Describe the solution you'd like
Add some option to setup.sh to add custom SMTP milter IP/DNS.

## Alternatives you've considered
None.

## Who will that feature be useful to?
Users with custom SMTP milters.

## What have you done already?
- Forked base image
- Patched milter into main.cf

## What are you going to contribute?
- Milter is currently closed source but will see if it can be made public.

## Additional context
None.

**Comment by aendeavor** [comment]
I am not sure about this one, but can't you use `user-patches.sh` to patch `master.cf`?

**Comment by erik-wramner** [comment]
I agree with @aendeavor that a patch from `user-patches.sh` makes the most sense. This is exactly the kind of thing it is there for.

**Comment by nekrondev** [comment]
Thanks for the hint! I think this is a valid solution for my problem and I will modify master.cf that way.
