### ISSUE TITLE
FreeIPA Integration with Forwarding

### ISSUE THREAD

**Issue by laubed** [tomav/docker-mailserver#1720]
## Subject
* [*] I would like to configure a not documented mail server use case

## Description
I try to integrate the docker mailserver with an existing freeipa server. So far things work out great except for one usecase: forwarding mail by specifying a mail inside the users ldap entry which is not on my domain.

The issue is that the mail attribute contains the mail address of the user as well:
uid: user1
mail: user1@mydomain.tld
mail: forwardmail@otherdomain.tld

I want to configure the server to only accept mails in the form of uid@mydomain.tld. I did so by specifiying
```
LDAP_QUERY_FILTER_USER=(&(objectClass=inetorgperson)(uid=%u)).
LDAP_QUERY_FILTER_ALIAS=(&(objectClass=inetorgperson)(uid=%u))
LDAP_QUERY_FILTER_DOMAIN=(nothing=nothing)
```

doing so delivers the mail to a local mailbox and forwards the mail TWICE to the other domain. 

Could you please help me integrating the container with freeipa and forwarding.

Thank you in advance

Daniel

**Comment by aendeavor** [comment]
Sadly only few maintainers use LDAP. I hope that nevertheless someone reads this issue and helps you:)

**Comment by Nudelsalad** [comment]
Hi @dlux95, would you be interested in sharing your dms configuration? I can not find any example of dms config with freeipa and I am stuck with the authentication...

**Comment by vapaa** [comment]
Hi @Nudelsalad Do you have a working configuration with freeipa?

**Comment by Nudelsalad** [comment]
Hey @vapaa , 
No not yet, i decided to wait for the major release 14 as there have been some improvements on the ldap side. I will try again and let you know if I have sth. If you acheived sth in the meantime i could benefit from pls let me know too:)

**Comment by polarathene** [comment]
I am planning to get some LDAP refactoring in for a v15 release of DMS later this year. Which should help with making LDAP easier to configure for, along with much better docs on our feature support for that.
