### ISSUE TITLE
pipe ${sasl_username} is not forwarded, am I missing something?

### ISSUE THREAD

**Issue by tnup** [tomav/docker-mailserver#1729]
## Subject
* [x] I would like some feedback concerning a use case

## Description

I am using this hook to forward to a php file. 
the first three arguments are passed, but the sasl_username is not. Am I missing a setting?
myhook     unix  -       n       n       -       -       pipe flags=F user=xxx argv=/xxx.php ${sender} ${size} ${recipient} ${sasl_username}

docker-compose.yml part:
```
environment:
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - ENABLE_POP3=0
    - ONE_DIR=1
    - DMS_DEBUG=1
    cap_add:
    - NET_ADMIN
```

**Comment by aendeavor** [comment]
Due to sheer coincidence I came across something very related yesterday - it was a forum post about Postfix's `header_checks` and it's limits. There was something about Postfix Pipes where it stated that only `${sender} ${size} ${recipient}` are passed by default. But I can't find that post right now...

**Comment by tnup** [comment]
Thank you for you anwser @aendeavor.

The link you've posted leads to stuff that goes a little over my head (and time atm). 

What you are basically saying is that this is a 'bug/feature' at PostFix that leads to a limitation only forwarding these three parameters? And that there is no 'quickfix'  or update to solve this?

**Comment by aendeavor** [comment]
> What you are basically saying is that this is a 'bug/feature' at PostFix that leads to a limitation only forwarding these three parameters? And that there is no 'quickfix' or update to solve this?

I'm afraid, yes. I don't want to say that it's impossible, but I don't know how to fix it.
