### ISSUE TITLE
How does the code for DOVECOT_TLS work ?

### ISSUE THREAD

**Issue by williamdes** [tomav/docker-mailserver#1733]
I am working on a full ssl/tls version at https://github.com/desportes/infrastructure and for now I managed to have the services work as they do in production using a letsencrypt test certificate (**not trusted**)

And because it is not trusted I have some settings to adjust and so on.

I would like to implement more settings to set tls files for dovecot to connect to the ldap server like it seems possible here:
https://github.com/dovecot/core/blob/941668f5a0ca1733ceceae438092398bc08a7810/doc/example-config/dovecot-ldap.conf.ext#L47

Could you please let me know by what magic the dovecot config code works ?
And how I can make a PR to add new variables ?

It sets the value from DOVECOT_TLS as it can be seen [here](https://github.com/desportes/infrastructure/runs/1615088659?check_suite_focus=true#step:8:157) but searching with GitHub I could not find where the magic happens: https://github.com/tomav/docker-mailserver/search?q=DOVECOT_TLS&type=code

**Comment by williamdes** [comment]
I used user-patches to workaround this https://github.com/desportes/infrastructure/commit/3910be8ce2790938ed96a5e4b0850eefbbeb9aee

**Comment by aendeavor** [comment]
I wiuld really like to help you with this one, but I don't know the answer. I'll label it, maybe other maintainers can help you.

**Comment by williamdes** [comment]
I think the recent migration did re-write the code for that.

**Comment by polarathene** [comment]
@williamdes I take it you did not identify where this ENV was relevant/implemented?

[I found this PR from Nov 2018](https://github.com/docker-mailserver/docker-mailserver/issues/1071), but checking out the commit and searching the env `DOVECOT_TLS` gave nothing relevant :/

**EDIT:** Did a search on `dovecot-ldap.conf.ext` and identified code using `configomat.sh` on `DOVECOT_`.
