### ISSUE TITLE
The dkim key generator does not work for ldap setups

### ISSUE THREAD

**Issue by williamdes** [tomav/docker-mailserver#1735]
The dkim key generator does not work for ldap setups

An option should be provided to the `generate-dkim-config` script for ldap setups to force domain names
Relying on files makes no sense for ldap setups

**Comment by aendeavor** [comment]
Completely with you here. As I'm not using LDAP, could you provide a PR? This seems like a "small" change, i.e. not too large, but as already mentioned in the context of LDAP. I'll happily merge it. Thank you for pointing this out:)

---

As a starting point, checking for `ENABLE_LDAP=1` as a already set environment variable should do the trick.

**Comment by williamdes** [comment]
Fixed in https://github.com/tomav/docker-mailserver/pull/1736

I finally did think we should not include any ldap logic because ldap can be complicated and very custom

This is the command I use to fetch domain names
```sh
# from my workstation
LDAPTLS_REQCERT=never ldapsearch -LLL -Z -h localhost -D "${LDAP_BIND_DN}" -w "${LDAP_BIND_PW}" "(mail=*)" -b "${LDAP_BASE_DN}" mail mailAlias | sed -n 's/^[ \t]*\(mail\|mailAlias\):[ \t]*.*@\(.*\)/\2/p'
```

**Comment by aendeavor** [comment]
Closed due to migration to [docker-mailserver/docker-mailserver](https://github.com/docker-mailserver/docker-mailserver). Please re-open over there :D
