### ISSUE TITLE
Migrating tons of emails into docker-mailserver, how can we generate the emails in bulk?

### ISSUE THREAD

**Issue by IbrahimS2** [tomav/docker-mailserver#1738]
Migrating tons of emails into docker-mailserver, how can we generate the emails in bulk rather than going one by one using setup.sh?

```
[root@os docker-mailserver]# ./setup.sh email add ibrahim@domain.com [test$#@4328]
User "ibrahim@domain.com" already exists
```

Need to have all the emails created beforehand so we can utilise imapsync to migrate our emails into docker-mailserver.

**Comment by aendeavor** [comment]
I guess, utilising the `setup.sh` script, maybe you could write a small Bash script to extrapolate your mail accounts and then add them via `setup.sh`.
