### ISSUE TITLE
User Unknown with uppercase letters in mail address

### ISSUE THREAD

**Issue by Slind14** [tomav/docker-mailserver#174]
``` 
May  1 14:01:53 mail postfix/pipe[596]: B77E3745: to=<noReply@domain.tld>, relay=dovecot, delay=0.06, delays=0.04/0/0/0.01, dsn=5.1.1, status=bounced (user unknown)
```

**Comment by 00angus** [comment]
What you want is making 'NoReply' user from 'domain.tld' be recognized as 'noreply' user for the same domain, if I'm right. That could be wrong from the authentication point of view as the mailserver is running in a unix server where the case matter (you CAN have two different users NoReply and noreply).
In fact email addresses are used to **authenticate** users (in our case via the userdb created for dovecot). 
From [RFC 2821](https://www.ietf.org/rfc/rfc2821.txt) of IETF 

>    The local-part of a mailbox
>    MUST BE treated as case sensitive.  Therefore, SMTP implementations
>    MUST take care to preserve the case of mailbox local-parts.  Mailbox
>    domains are not case sensitive.

However if you want to implement anyway that behaviour, you will need to configure dovecot **auth** to authenticate users lowercase with:

>          auth_username_format = "%Lu"

This [page](http://wiki.dovecot.org/Variables) may give more help.

**Comment by Slind14** [comment]
hmm, ok. Might be good to be fixed with the container it self. I moved along by now, thanks anyways :)
