### ISSUE TITLE
Disable fetchmail verbose log

### ISSUE THREAD

**Issue by davide966** [tomav/docker-mailserver#1740]
In [supervisor-app.conf](https://github.com/brainkiller/docker-mailserver/blob/master/target/supervisor/conf.d/supervisor-app.conf#L100) fetchmail starts in daemon mode.

It  would be useful to have an ENV variable to set/unset the **-v** option.

something like:
`
command=/usr/bin/fetchmail -f /etc/fetchmailrc %(ENV_FETCHMAIL_VERBOSITY) --nodetach --daemon %(ENV_FETCHMAIL_POLL)s -i /var/lib/fetchmail/.fetchmail-UIDL-cache --pidfile /var/run/fetchmail/fetchmail.pid
`

As a temporary workaround I use a volume overwriting existing supervisor-app.conf whith a custom one without the -v flag.

Thanks.

**Comment by aendeavor** [comment]
1. Not using the feature-request template will result in closing you issues according to the contributing guidelines
2. This is easily fixed with the `user-patches.sh` script,  described in the README
