### ISSUE TITLE
warning: dnsblog_query: lookup error for DNS query

### ISSUE THREAD

**Issue by leonfilser** [tomav/docker-mailserver#1742]
## Subject

* [x] Other

## Description

I noticed that i didn't receive some mails. When looking in the logs i found the following:

> Jan  6 18:41:28 mail postfix/postscreen[1774]: CONNECT from [167.89.108.242]:35203 to [172.29.0.2]:25
> Jan  6 18:41:34 mail postfix/postscreen[1774]: PASS OLD [167.89.108.242]:35203
> Jan  6 18:41:38 mail postfix/dnsblog[1775]: warning: dnsblog_query: lookup error for DNS query 242.108.89.167.bl.spamcop.net: Host or domain name not found. Name service error for name=242.108.89.167.bl.spamcop.net type=A: Host not found, try again
> Jan  6 18:41:38 mail postfix/postscreen[1774]: warning: dnsblog reply timeout 10s for bl.spamcop.net
> Jan  6 18:41:38 mail postfix/postscreen[1774]: warning: dnsblog reply timeout 10s for b.barracudacentral.org
> Jan  6 18:41:38 mail postfix/postscreen[1774]: warning: dnsblog reply timeout 10s for bl.mailspike.net
> Jan  6 18:41:38 mail postfix/postscreen[1774]: warning: dnsblog reply timeout 10s for bl.spameatingmonkey.net
> Jan  6 18:41:38 mail postfix/postscreen[1774]: warning: dnsblog reply timeout 10s for list.dnswl.org
> Jan  6 18:41:38 mail postfix/postscreen[1774]: warning: dnsblog reply timeout 10s for zen.spamhaus.org
> Jan  6 18:41:38 mail postfix/postscreen[1774]: warning: dnsblog reply timeout 10s for dnsbl.sorbs.net
> Jan  6 18:41:38 mail postfix/postscreen[1774]: warning: dnsblog reply timeout 10s for psbl.surriel.com
> Jan  6 18:41:38 mail postfix/dnsblog[1776]: warning: dnsblog_query: lookup error for DNS query 242.108.89.167.b.barracudacentral.org: Host or domain name not found. Name service error for name=242.108.89.167.b.barracudacentral.org type=A: Host not found, try again
> Jan  6 18:41:38 mail postfix/dnsblog[1777]: warning: dnsblog_query: lookup error for DNS query 242.108.89.167.bl.mailspike.net: Host or domain name not found. Name service error for name=242.108.89.167.bl.mailspike.net type=A: Host not found, try again
> Jan  6 18:41:38 mail postfix/dnsblog[1778]: warning: dnsblog_query: lookup error for DNS query 242.108.89.167.bl.spameatingmonkey.net: Host or domain name not found. Name service error for name=242.108.89.167.bl.spameatingmonkey.net type=A: Host not found, try again
> Jan  6 18:41:38 mail postfix/dnsblog[1779]: warning: dnsblog_query: lookup error for DNS query 242.108.89.167.list.dnswl.org: Host or domain name not found. Name service error for name=242.108.89.167.list.dnswl.org type=A: Host not found, try again
> Jan  6 18:41:38 mail postfix/dnsblog[1780]: warning: dnsblog_query: lookup error for DNS query 242.108.89.167.zen.spamhaus.org: Host or domain name not found. Name service error for name=242.108.89.167.zen.spamhaus.org type=A: Host not found, try again
> Jan  6 18:41:38 mail postfix/dnsblog[1781]: warning: dnsblog_query: lookup error for DNS query 242.108.89.167.dnsbl.sorbs.net: Host or domain name not found. Name service error for name=242.108.89.167.dnsbl.sorbs.net type=A: Host not found, try again
> Jan  6 18:41:38 mail postfix/dnsblog[1786]: warning: dnsblog_query: lookup error for DNS query 242.108.89.167.psbl.surriel.com: Host or domain name not found. Name service error for name=242.108.89.167.psbl.surriel.com type=A: Host not found, try again

Does anyone know why this is happening and how to solve it?

**Comment by aendeavor** [comment]
Your DNS resolver cannot lookup these queries. I use:

``` YAML
service:
  mail:
    dns:
      - 9.9.9.9
      - 8.8.8.8
      - 1.1.1.1
      - 1.0.0.1
```

This should fix your issue.
