### ISSUE TITLE
450 4.1.8 Sender address rejected: Domain not found;

### ISSUE THREAD

**Issue by leonfilser** [tomav/docker-mailserver#1744]
## Subject
* [x] Other

## Description
I noticed that i couldn't receive some Mails (e.g. from [Erxes registration](https://erxes.io/magic-link) or [PhantomJS registration](https://dashboard.phantomjscloud.com/dash.html?_ga=2.11898480.599656662.1609951527-1698409285.1609951527#/signup?_k=l72idy))

In my logs i see the following:

> Jan  6 23:48:02 mail postfix/postscreen[1055]: CONNECT from [167.89.108.242]:36524 to [192.168.48.2]:25
> Jan  6 23:48:02 mail postfix/dnsblog[1060]: addr 167.89.108.242 listed by domain list.dnswl.org as 127.0.0.255
> Jan  6 23:48:02 mail postfix/postscreen[1055]: PASS OLD [167.89.108.242]:36524
> Jan  6 23:48:02 mail postfix/smtpd[1089]: connect from xtrwscfn.outbound-mail.sendgrid.net[167.89.108.242]
> Jan  6 23:48:03 mail postfix/smtpd[1089]: Anonymous TLS connection established from xtrwscfn.outbound-mail.sendgrid.net[167.89.108.242]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
> Jan  6 23:48:03 mail postfix/smtpd[1089]: NOQUEUE: reject: RCPT from xtrwscfn.outbound-mail.sendgrid.net[167.89.108.242]: 450 4.1.8 <bounces+19390322-d49f-info=filser-webdesign.de@em7169.erxes.io>: Sender address rejected: Domain not found; from=<bounces+19390322-d49f-info=filser-webdesign.de@em7169.erxes.io> to=<info@filser-webdesign.de> proto=ESMTP helo=<xtrwscfn.outbound-mail.sendgrid.net>
> Jan  6 23:48:03 mail postfix/smtpd[1089]: disconnect from xtrwscfn.outbound-mail.sendgrid.net[167.89.108.242] ehlo=2 starttls=1 mail=1 rcpt=0/1 quit=1 commands=5/6

If i am getting this right the problem is not from my mailserver but from theirs. (Please correct me if i am wrong)
Is there a way to configure postfix so that these emails are still allowed through or end up in the spam folder?

Thanks in advance for any help!

**Comment by aendeavor** [comment]
From <https://kb.intermedia.net/article/35595>:

> indicates that the email is rejected because the sender's domain is unable to be resolved properly [...]

I guess you can configure Postfix that way. Asking Google yields this: <https://www.howtoforge.com/community/threads/postfix-gateway-sender-address-rejected-doman-not-found.42664/>

**Comment by leonfilser** [comment]
Thanks i deactivated it by removing `reject_unknown_sender_domain` from `smtpd_sender_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unknown_sender_domain`.

Doesn't this have any negative effects, such as less spam being filtered out?

**Comment by aendeavor** [comment]
Sorry, I accidentally edited your comment instead of quote-replying - damn mobile app.

> Doesn't this have any negative effects, such as less spam being filtered out?

Of course. If you'd like to hear my opinion: Only disable it if you _really_ need to. I'd advise against it.

Always make sure that the `A`, `PTR` and `MX` record is properly set.

On my system, I only allow servers that set these records correctly. The reason being that I don't want mails from people/companies that cannot setup a server properly:)

**Comment by leonfilser** [comment]
> I don't want mails from people/companies that cannot setup a server properly
Totally agree.

I will leave it like this for now and will keep an eye on my spam. When it becomes too much i will set it back to default settings.
