### ISSUE TITLE
Security certificate for email server

### ISSUE THREAD

**Issue by KyleDuPlessis** [tomav/docker-mailserver#1745]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [x] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [x] Other

## Description

We are in the process of procuring a security certificate for the email server to work. My question is do we require **both** MX and SPF records to be created (or just MX record)? Please let me know as soon as possible.

**Comment by aendeavor** [comment]
> We are in the process of procuring a security certificate for the email server to work. My question is do we require **both** MX and SPF records to be created (or just MX record)? Please let me know as soon as possible.

I cannot image a well-defined security **withou** `SPF` records.

From my POV, only having an SPF record is _not_ enough, you will also need an DKIM and DMARC record.
