### ISSUE TITLE
Disable encryption on port 587

### ISSUE THREAD

**Issue by Dominilk** [tomav/docker-mailserver#1746]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [x] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [ ] Other

## Description
Hi!
I would like to disable encryption on port 587 completely as it will only be used from within the container's network and I don't want to go through the whole encryption setup for no reason. How would I go about doing this?

Best Regards
Dominik

**Comment by aendeavor** [comment]
Use port 25 instead of 587? The README has got you covered.

The Postfix configuration is provided by Google I guess.

**Comment by Dominilk** [comment]
Okay, I thought 25 was a port responsible for something else. Still, thanks!
