### ISSUE TITLE
Fluctuating respond time

### ISSUE THREAD

**Issue by leonfilser** [tomav/docker-mailserver#1749]
## Subject
* [x] Other

## Description

While monitoring my mailserver with [MXToolBox](https://mxtoolbox.com/SuperTool.aspx) i noticed that the response time fluctuated a lot. 
Sometimes the server needs only a few milliseconds to respond but when I try again directly after that it takes over 7 seconds to respond although the ping is constant at 20ms.
I am using a [Strato](https://www.strato.de/) V Server with 8 cores and 32GB Ram.
Is there anything I can change in the settings to speed up the response time?

**Comment by aendeavor** [comment]
> Is there anything I can change in the settings to speed up the response time?

No, this is the experience for (nearly) everyone and **in no way** concerning.

**Comment by casperklein** [comment]
There are two options that can influence the response time:

- [postscreen](http://www.postfix.org/POSTSCREEN_README.html)
- [postgrey](https://postgrey.schweikert.ch/) (disabled by default in docker-mailserver)

Postgrey can be easily disabled with `ENABLE_POSTGREY=0`.

Disabling postscreen cannot be done via an env variable. You have to use a [custom postfix config](https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration).

But I recommend leaving postscreen enabled. It's used for DNS blacklists and more.
