### ISSUE TITLE
Nameserver inside the container

### ISSUE THREAD

**Issue by diiigle** [tomav/docker-mailserver#175]
I propose to setup a local full resolving nameserver inside the container in order not to rely only on the server of the host.

Background:

I tried using a whitelist for my postfix configurations (https://www.dnswl.org/), but unfortunately my namerservers are already blocked for quering the whitelist (too many lookups i suppose). 

Pretty much the same problem as in [here](http://postfix.1071664.n5.nabble.com/DNSWL-with-Postfix-td75466.html)

**Comment by manthis** [comment]
Well, that would defeat the purpose of a mail server. I suggest you create your own compose file and add the dns as a service.

**Comment by tomav** [comment]
I do agree with @manthis. Note that this can be added in the Wiki to help other users to do it.

**Comment by diiigle** [comment]
@manthis why should this defeat the purpose of a mailserver? Could you clarify your comment a bit?

**Comment by manthis** [comment]
@diiigle Maybe "defeat" is not appropriate. I mean a DNS server is clearly not in the scope of an email server. So it has no reason to be integrated into the mail server container whose only purpose is to receive/send emails. It's better if it is integrated as a service in a docker compose file.

**Comment by diiigle** [comment]
@manthis okay, that sounds reasonable to me. I'll do my best and try the docker compose approach. 
I'll keep you updated.

**Comment by manthis** [comment]
Awesome. Thanks @diiigle

**Comment by tomav** [comment]
Closed due to inactivity. Reopen if needed.
