### ISSUE TITLE
Emails coming from relay fail SPF checks after modifying envelope-from

### ISSUE THREAD

**Issue by Hashfastr** [tomav/docker-mailserver#1751]
Emails coming from my relay are rejected by SPF after envelope-from is set.

## Context
Since my ISP blocks port 25 I use no-ip's alternate port smtp relay that relays incoming mail from port 25 to port 26 and vice versa.

### *What* is affected by this bug?

Email being received from a relay after grey-listing.

### *When* does this occur?

When an email that looks like potential spam is grey-listed by my email relay and the envelope-from field is set in the form of `<bounces+5929922-66fc-username=domain.com@original-sender-domain.com>`.

## *How* do we replicate the issue?

1. Have an email relay
2. Have the incoming email come from the email relay, and have the envelope from field be set to something along the lines of: `<bounces+5929922-66fc-username=domain.com@original-sender-domain.com>`

## Actual Behavior
SPF checks fail thinking that the relay is acting as the proper sender for original-sender-domain.com

## Expected behavior (i.e. solution)
SPF checks do not fail and the relay is treated as a relay

## Your Environment

* Amount of RAM available: 4GBs
* Mailserver version used: Latest
* Docker version used: `19.03.8, build afacb8b7f0`
* Environment settings relevant to the config: Email relay configured with SASL authentication
* Any relevant stack traces ("Full trace" preferred): N/A

When receiving emails from my email relay it appears it sets the envelope-from field in the form of `<bounces+5929922-66fc-username=domain.com@original-sender-domain.com>` but when the mail server receives this email it checks if the ip address of my relay is in the spf configuration for `original-sender-domain.com`.
I've tried adding my relay as an [excluded domain](https://github.com/tomav/docker-mailserver/wiki/Configure-Relay-Hosts
) and my relay is configured properly otherwise.
This only seems to be the problem when my domain greylists an incoming email, namely email verification emails for when I create a new account somewhere, which has so far happened on intel.com and securitytrails.com.

Below is the log output for when I receive on of these emails, I've redacted personal information to follow the generic pattern shown above:

```
Jan 12 21:28:56 mail postfix/postscreen[18826]: CONNECT from [8.23.224.50]:24153 to [172.18.0.2]:25
Jan 12 21:28:56 mail postfix/postscreen[18826]: PASS OLD [8.23.224.50]:24153
Jan 12 21:28:56 mail postfix/smtpd[18838]: connect from mail1.no-ip.com[8.23.224.50]
Jan 12 21:28:57 mail policyd-spf[18848]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=bounces+5929922-66fc-username=domain.com@original-sender-domain.com;ip=8.23.224.50;r=<UNKNOWN>
Jan 12 21:28:57 mail postfix/smtpd[18838]: NOQUEUE: reject: RCPT from mail1.no-ip.com[8.23.224.50]: 550 5.7.23 <username@domain.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=bounces+5929922-66fc-username=domain.com@original-sender-domain.com;ip=8.23.224.50;r=<UNKNOWN>; from=<bounces+5929922-66fc-username=domain.com@original-sender-domain.com> to=<username@domain.com> proto=ESMTP helo=<mail1.no-ip.com>
Jan 12 21:28:58 mail postfix/smtpd[18838]: disconnect from mail1.no-ip.com[8.23.224.50] ehlo=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=4/6
```

I also have SPF and DKIM properly configured, and have added my relay to my SPF.

**Comment by Hashfastr** [comment]
Feel like an idiot and didn't do the full report, fixing now

**Comment by aendeavor** [comment]
Hey @Hashfastr 

This actually seems to be expected and is not a bug in `docker-mailserver`. Look here: <https://www.validity.com/how-to-explain-spf-in-plain-english/>

which states:

> SPF breaks when a message is forwarded.

We cannot affect how SPF works, but this is the way iit works. I'd suggest using DKIM and DMARC.
