### ISSUE TITLE
Rainloop Integration

### ISSUE THREAD

**Issue by manthis** [tomav/docker-mailserver#177]
Hi,  

I was thinking that a webmail such as Rainloop would be awesome. We could just integrate it in the docker compose file as a second service. Let me know if you'd be interested and I'll see how I can contribute. If you prefer to keep your project simple as it is, I can still fork it to include these two features

**Comment by tomav** [comment]
I highly recommend to use an external image for this in order to simplify maintenance of both mailserver and webmail, and also for service isolation and respect of docker philosophy.
But I'd be happy if you you want to add a page on the wiki regarding the necessary `docker-compose` setup in order to do that.

Let me know.

**Comment by manthis** [comment]
Well, I'm actually building a Dockerfile and a docker-compose.yml file in order to to that. I'll keep you posted with my progress.

**Comment by tomav** [comment]
Thank you @manthis

**Comment by nathema** [comment]
Also interested in rainloop integration based on seperate image.

**Comment by tomav** [comment]
Hi @manthis, any update on this?

**Comment by Krishath** [comment]
I've made this container [here](https://github.com/Krishath/docker-rainloop) which also has SSL support. I use it with this mailserver image without any issue. Let me know if this helps in any way.

**Comment by tomav** [comment]
I think @Krishath makes us move forward.
I close this thread as it not an issue and we have a solution for that.

As usual, feedback welcome. If they're positive, I'll be happy to link @Krishath's project in the `README`.
