### ISSUE TITLE
Letsencrypt via DNS challenge

### ISSUE THREAD

**Issue by manthis** [tomav/docker-mailserver#179]
Hi,

Was wondering why you actually use the letsencrypt certificates of the host while you could just install letsecnrypt and issue certificates on the fly. Is there any reason why you don't do it? If there is not, I'd like to work on it. I'm actually already doing the same implementation for the rainloop container I'm working on so it could benefit everyone.

**Comment by tomav** [comment]
How do you do that if a webserver is already running on the server?

**Comment by manthis** [comment]
Not sure to understand what would be the issue caused by a web server on the host.

**Comment by tomav** [comment]
I'm clearly not a LE expert, but I think that certificates automatic generation uses HTTP or HTTPS protocoles to validate that you really own the domain and expects to find some files for that.
There are options to do that, but most of them have an impact on both containers (mail and web).

What do you have in mind to do that?

**Comment by manthis** [comment]
Well me neither but in my comprehension of things letsencrypt just validates you own the domain by checking the ip address issuing the request and comparing with the ip address declared at your registrar. But I might be wrong. I'll give it a try with my container and I'll let you know if it works (even in case of a web server already present on host).

**Comment by manthis** [comment]
Besides, with the present configuration, how do you do when you don't have any installed web server with ssl configured with letsencrypt? So the more I think about it, the more I think letsencrypt should create the certs inside of the container.

**Comment by tomav** [comment]
Just had a look to LE, and you're right, they added DNS validation in late january 2016 while we added the feature in december 2015. So the workflow could be like this:
- if `SSL_TYPE` is `letsencrypt` check if files are provided (current setup)
- if file are not provided, generate them and configure the server

Or something like that. Let's talk about that.

**Comment by manthis** [comment]
Yep, that would be great. As soon as I have the procedure I integrate it and make a pull request.

**Comment by manthis** [comment]
Actually, this is the recommended docker use to generate certificates with letsencrypt: [https://letsencrypt.readthedocs.io/en/latest/using.html#running-with-docker](https://letsencrypt.readthedocs.io/en/latest/using.html#running-with-docker).

**Comment by tomav** [comment]
That's the one I personaly use but with HTTP validation. I'll have to check how it works with DNS challenge.

**Comment by tomav** [comment]
Can't find information on how DNS challenge works with LE client.

**Comment by tomav** [comment]
Let's reopen this when a clear answer can be provided according to LetsEncrypt client.
