### ISSUE TITLE
Filesystem notification initialization error, check for configuration error with the FAM/Gamin library

### ISSUE THREAD

**Issue by zx2015** [tomav/docker-mailserver#18]
Get notification message after configured mail on outlook
Filesystem notification initialization error -- contact your mail administrator (check for configuration errors with the FAM/Gamin library)

Command for run the docker
docker run --name mail -v "/data/mail/postfix":/tmp/postfix -v "/data/mail/spamassassin":/tmp/spamassassin -p "25:25" -p "143:143" -p "587:587" -p "993:993" -h mail.1day.cn -t tvial/docker-mailserver

**Comment by tomav** [comment]
I suppose you see this problem when a user connects to IMAP?
I'll have a look.

**Comment by tomav** [comment]
Ok, this error is not server side, but client side.
I can't see it on the server, but can see it when trying to login with `telnet` on this imap server.

    $ telnet 192.168.59.103 143
    Trying 192.168.59.103...
    Connected to 192.168.59.103.
    Escape character is '^]'.
    * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION STARTTLS] Courier-IMAP ready. Copyright 1998-2011 Double Precision, Inc.  See COPYING for distribution information.
    a1 LOGIN user@domain.tld mypassword
    * OK [ALERT] Filesystem notification initialization error -- contact your mail administrator (check for configuration errors with the FAM/Gamin library)
    a1 OK LOGIN Ok.

Strange. Seems to work correctly. I'll have a deeper look.
Any help appreciated.

**Comment by tomav** [comment]
I'm gonna push a fix.

**Comment by tomav** [comment]
Build in progress: https://hub.docker.com/r/tvial/docker-mailserver/builds/bgz2nzryn6s5yyxup7a2yz4/

**Comment by tomav** [comment]
Found an issue generated with this fix.

**Comment by tomav** [comment]
Ok. I pushed it on my server and made some test.
Everything seems fine with latest `btasyhoyubo58zacehaishu` build.

Hope this helps, and let me know.

**Comment by zx2015** [comment]
Thank you for your quit action. The old problem is solved. But I got a new problem. It looks like the STMP server can not work. During outlook configuring, smtp is not reachable.

Sep 12 23:36:23 d098b9451d15 postfix/smtpd[654]: connect from unknown[172.17.42.1]
Sep 12 23:36:27 d098b9451d15 postfix/smtpd[654]: warning: SASL authentication failure: Couldn't find mech login
Sep 12 23:36:27 d098b9451d15 postfix/smtpd[654]: warning: unknown[172.17.42.1]: SASL login authentication failed: no mechanism available

Is there any change other than gamin?

**Comment by zx2015** [comment]
Sorry, it look like my client problem. Use another client can connect smtp successful

**Comment by zx2015** [comment]
There is still one problem. When I try to send email outside with outlook, there is always an error message.
554 5.7.1 <xxxxx@163.com>: Relay access denied
And mail is not send out yet.

I checked internet, the possible cause might be auth for SMTP is missing. Recv side server might reject such mail without auth to prevent spam mail.

But it look strange that my iphone works fine and can send email to outside mailbox.

**Comment by tomav** [comment]
@zx2015, could you open another issue for this new one?
And if you can send me a private message with an address on which we could do tests, it would be glad.
Otherwise, it will be hard for me to reproduce the problem, and help.

Thank you.

**Comment by tomav** [comment]
I documented about [How to fix the Gamin/FAM issue](http://tvi.al/how-to-fix-the-gamin-fam-issue/) on my blog to let people know how to do.
