### ISSUE TITLE
SSL Documentation + Wiki

### ISSUE THREAD

**Issue by KyleOndy** [tomav/docker-mailserver#183]
I finally swapped my mailserver over to `docker-mailserver` last night and while getting my ssl cert setup I noticed a handful of spots where both the documentation and wiki could be updated.

Later today I'll submit a PR with the changes.

**Comment by dragonito** [comment]
Perhaps you can add some information about letsencrypt and the correct hostname. I got some problems with it in issue #184

**Comment by tomav** [comment]
It's already in the documentation: https://github.com/tomav/docker-mailserver/wiki/Configure-SSL

> the certs folder name located in letsencrypt/live/ must be the fqdn of your container responding to the hostname command.

**Comment by KyleOndy** [comment]
I've never worked with github's wiki before. Is there a way to clone it locally and edit it, or does everything need to be done via the web ui?

**Comment by Josef-Friedrich** [comment]
https://github.com/tomav/docker-mailserver.wiki.git

**Comment by KyleOndy** [comment]
My searching tells me its not possible, but I wanted to verify.

Is there no way to make a PR again the wiki?

**Comment by tomav** [comment]
Wiki can be directly modified using your browser. Do not hesitate to improve it.
