### ISSUE TITLE
Additional config options to postfix main.cf

### ISSUE THREAD

**Issue by dragonito** [tomav/docker-mailserver#185]
Hi,

is it possible to add additional config options to main.cf?

I would to increase message_size_limit to 50mb.

Thx a lot 

Robin

**Comment by tomav** [comment]
Yep, there's a feature (not documented for that).

Check this: https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L196-L206

You have to mount a `postfix-main.cf` in the same folder of your accounts.
Each postfix variable will be loaded. With this, you can add configurations and override default.

This should be documented win a new Wiki page. If you have 20 minutes to do that ;-)

**Comment by dragonito** [comment]
Thanks a lot! I´ll try it!
