### ISSUE TITLE
CA Certificate

### ISSUE THREAD

**Issue by skaren** [tomav/docker-mailserver#186]
I use this docker container with custom ssl certificates (`SSL_TYPE=custom`). To use my own certificates I create a pem file from crt and key like this: 
```
cat mail.domain.tld.crt mail.domain.tld.key > config/ssl/mail.domain.tld-full.pem
```

Is there a way to add the CA Certificate?

The option for postfix in `/etc/postfix/main.cf` is `smtpd_tls_CAfile = path_to_cert`.

**Comment by tomav** [comment]
Hi,

I never tried this myself, this feature begin added by a contributor but:
- have a look to https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L135-L153. It should do the trick except is something is missing (should be a good test)
- if it doesn't work, best thing is to try to fix and document this part
- last option is to configure it manually using what I explained [here](https://github.com/tomav/docker-mailserver/issues/185)

Let me know.

**Comment by tomav** [comment]
Perhaps @emazzotta can help. (cf. [this PR](https://github.com/tomav/docker-mailserver/pull/90))

**Comment by emazzotta** [comment]
Hi @skaren 

The idea with the custom "full" certificate, is that it contains everything necessary, so you don't need to reference anything else.

I use startssl and my script to generate the "mail.domain.tld-full.pem" looks something like this:

```sh
cat << EOF > private.key
-----BEGIN RSA PRIVATE KEY-----
my_key...
-----END RSA PRIVATE KEY-----
EOF
cat << EOF > my_cert.crt
-----BEGIN CERTIFICATE-----
my_cert....
-----END CERTIFICATE-----
EOF

echo "$(cat my_cert.crt)\n$(curl --silent https://www.startssl.com/certs/class2/sha2/pem/sub.class2.server.sha2.ca.pem)" > unified.crt
openssl x509 -in unified.crt -out unified.pem -outform PEM
openssl rsa -in private.key -out private_unlocked.key
echo "$(cat private_unlocked.key)\n$(cat unified.pem)\n$(curl --silent https://www.startssl.com/certs/ca-bundle.pem)" > mail.domain.tld-full.pem
```

So the first curl request gets the intermediate certificate and the second request gets the whole ca-bundle. Depending on the CA you get your certificates from, this may vary.

If this helps, you're free to put this in the readme where appropriate @skaren / @tomav

**Comment by skaren** [comment]
I use StartSSL too. I get the following error, if I create the certificate with your script and test it on https://www.checktls.com/TestReceiver.

```
[001.175] Certificate 1 of 3 in chain:
          subject= /CN=mail.domain.tld
          issuer= /C=IL/O=StartCom Ltd./OU=StartCom Certification Authority/CN=StartCom Class 1 DV Server CA                                                          
[001.201] Certificate 2 of 3 in chain:
          subject= /CN=mail.domain.tld
          issuer= /C=IL/O=StartCom Ltd./OU=StartCom Certification Authority/CN=StartCom Class 1 DV Server CA                                                            
[001.243] Certificate 3 of 3 in chain:
          subject= /CN=mail.domain.tld
          issuer= /C=IL/O=StartCom Ltd./OU=StartCom Certification Authority/CN=StartCom Class 1 DV Server CA                                                              
[001.244] Cert NOT VALIDATED: unable to get local issuer certificate
[001.244] this may help: What Is An Intermediate Certificate
[001.244] So email is encrypted but the domain is not verified
[001.244] Cert Hostname DOES NOT VERIFY (123.456.789.12 != mail.domain.tld)
[001.245] So email is encrypted but the host is not verified
```

I get another problem with your script. It write the character \n instead of a line break. For the tests I removed this manualy.

```
-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----
```

Kind regards
Skaren

**Comment by emazzotta** [comment]
That's interesting, I tested it and it works fine for me. Are you sure you're using the correct intermediate certificate?

With the line breaks, try replacing the two `echo`-statements with `echo -e`

**Comment by skaren** [comment]
`echo -e` works well.

I used the class 1 intermediate certificate from https://www.startssl.com/certs/class1/sha2/pem/sub.class1.server.sha2.ca.pem

**Comment by emazzotta** [comment]
Clearly something is wrong with your certificate, are you sure you ran this correctly?

Try this again, I already changed it to be class 1:

```
cat << EOF > private.key
-----BEGIN RSA PRIVATE KEY-----
my_key...
-----END RSA PRIVATE KEY-----
EOF
cat << EOF > my_cert.crt
-----BEGIN CERTIFICATE-----
my_cert....
-----END CERTIFICATE-----
EOF

echo "$(cat my_cert.crt)\n$(curl --silent https://www.startssl.com/certs/class1/sha2/pem/sub.class1.server.sha2.ca.pem)" > unified.crt
openssl x509 -in unified.crt -out unified.pem -outform PEM
openssl rsa -in private.key -out private_unlocked.key
echo "$(cat private_unlocked.key)\n$(cat unified.pem)\n$(curl --silent https://www.startssl.com/certs/ca-bundle.pem)" > mail.domain.tld-full.pem
```

**Comment by skaren** [comment]
I don't know where the problem lies.

Now I use let's encrypt. It's realy simple.

Thanks for the help!
