### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by georgehrke** [tomav/docker-mailserver#187]
I think it would be a huge enhancement if one could simply link a docker container containing a LDAP server against the docker-mailserver container and use existing LDAP accounts instead of `config/postfix-accounts.cf` while preserving the alias capabilities. :)

**Comment by tomav** [comment]
This will be a mix of configuration file and external authentication. Could be strange to maintain but should work.
Dovecot supports `LDAP` authentication: http://wiki2.dovecot.org/AuthDatabase/LDAP

Are you planning working on it?

**Comment by tomav** [comment]
@georgehrke let us know please. Thank you.

**Comment by georgehrke** [comment]
Sorry, somehow missed your first answer.

I would just be a nice enhancement but really not something that's mandatory for me.
Given that I'm running short on time right now and that I'm no expert in this topic I'll probably not be able to work on this anytime soon.

**Comment by kopax** [comment]
+1 for this feature. I am also looking to add this feature. I don't have experience with mail server yet, but I can help you.

**Comment by kopax** [comment]
I started working on this. This feature seems not too hard to add.

https://wiki.gandi.net/fr/hosting/using-linux/tutorials/debian/mail-server-ldap

I will start to implement it for my own use. If you guys have idea's of configuration/usage/implementation. Please just share the specs here and I will do my best to implement the code.

**Comment by omigeot** [comment]
Just my 2 cents here, but I just discovered your project while trying to build something similar. On the "external userdb" front (e.g. LDAP), I was thinking about adding a thin layer of abstraction between LDAP and the mail services.

Both Postfix and Dovecot are more or less able to get their userdatabases from either shell-scripts/commands and/or simple telnet-like services. Given that, wouldn't it be better to implement that kind of support in docker-mailserver, and then let external userdb/auth be pluggable?

For instance, dovecot/postfix could talk to another container, which would in turn be able to either : ask LDAP, read local file, ask SQL db, ...

**Comment by tomav** [comment]
Yep, I think only connector should go in docker-mailserver and use external pre-existing LDAP (or equivalent) images.

**Comment by omigeot** [comment]
Pluggability has an added advantage : it'd allow to plug non-docker user sources. Think "pre-existing LDAP/AD", "owncloud SQL db", ...

**Comment by kopax** [comment]
As I told @tomav, I did it already.
I will now submit a PR with LDAP, somebody needs to take care of the regression test and documentation.

**Comment by citec** [comment]
We could add and environment var to define which auth method will be used and the start script would set everything up.
For me is almost mandatory to have a db of users and aliases so an external  database container would be great. This way each deployment will have the auth method that suits its needs and, for example, no more container restarts when adding an email account. Also external db would allow the use of GUIs for managing users

**Comment by kopax** [comment]
@citec, what do you mean? 
Two containers, one for mailserver, second for managing users accounts ?
This is exactly what we are talking about by adding authentication through LDAP using a different postfix configuration. 
LDAP is an ISO database for distributed directory information services over an Internet Protocol.
https://en.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol

**Comment by citec** [comment]
no, I mean to specify, by using env vars, when the user accounts are stored. Give different options to user. For example I don't use ldap, but I would like to use mysql or postgres. @tomav likes more files and you like ldap, so all of us can use the stack, but each one of us use different user account storage.
ldap container can be external, not in the project, mysql too, no need to be local, but also possible if user wants to be.
