### ISSUE TITLE
Problems with relaying

### ISSUE THREAD

**Issue by StianOvrevage** [tomav/docker-mailserver#188]
I have a problem relaying mails from another container via docker-mailserver. Because of certificates I use the FQDN and public-ip when connecting to docker-mailserver, and I guess that means the client is not using a 172.17.0.0/16 address but the public IP of the server.

So as far as I can see I have three options:
Add an entry in the local hosts file so that mail.domain.xx resolves to localhost. - I don't really like this approach. Easy to forget that hosts file when doing other changes.

Remove permit_mynetworks from smtpd_relay_restrictions. I assume that clients will still have to be authenticated with correct username and password, but it is a less secure option.

Add my public IP to mynetworks, but that is hard to maintain.

Is there any other way of getting this working with minimal ongoing maintenance?

**Comment by StianOvrevage** [comment]
For implementing option #2 I suggest this code added in start-mailserver.sh so that the option can be set via env-vars in docker-compose.yml

```
if [ "$ALLOW_AUTHENTICATED_RELAY_FROM_OTHER_NETWORKS" != 1 ]; then
  # We are removing the requirement of having to be in mynetworks ACL. Users still have to be authenticated with username and password.
  sed -i -r 's/smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination/smtpd_relay_restrictions = permit_sasl_authenticated defer_unauth_destination/g' /etc/postfix/main.cf
fi

```

**Comment by StianOvrevage** [comment]
It turns out I grossly underestimated how many changes are required to get relay working. So the above snippet is not enough. Still working on getting relay to work in Postfix.

**Comment by tomav** [comment]
Why not using authentication from the outside world?

Note that you can override default postfix configuration out of the box:
https://github.com/tomav/docker-mailserver/wiki/Override-default-postfix-configuration

**Comment by StianOvrevage** [comment]
Thanks. I have tried everything to get Postfix to accept relay from authenticated clients outside of mynetworks without luck. I will have another stab at this next week.

**Comment by tomav** [comment]
What kind of services are running into your other containers? Web applications?

**Comment by tomav** [comment]
@StianOvrevage any update on this?

**Comment by StianOvrevage** [comment]
I ended up adding my public ip to "mynetworks" in the postfix configuration. Not a good solution but it'll work for now. It's probably a postfix problem as well and not a docker-mailserver problem.
