### ISSUE TITLE
I have to enable pop3 for imap?

### ISSUE THREAD

**Issue by schoentoon** [tomav/docker-mailserver#189]
Hi,

I kind of only want IMAP access and I didn't see an ENABLE_IMAP for this so assumed it would work. But after sometime I figured out that this would only work with ENABLE_POP3=1, which quite frankly doesn't make any sense. And of course, then I have both pop3 (which I don't want) and imap. This by itself is not that much of an issue as I can just close the pop3 port. Still, ENABLE_POP3 for imap is just odd.

**Comment by Josef-Friedrich** [comment]
IMAP support is enable by default. I use `docker-mailserver`without POP3 and the IMAP access to my mail folders works great.

**Comment by tomav** [comment]
Hi @schoentoon, @Josef-Friedrich is right. `IMAP` is enable by default.
`POP`is optional that's why we added a var to enable it or not.
