### ISSUE TITLE
Don't always fix permissions on start-up

### ISSUE THREAD

**Issue by tve** [tomav/docker-mailserver#190]
Fixing permissions on startup https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L220 takes many minutes on my (perhaps a bit wimpy) mail server with many GB of messages stored in maildir format. Please either check whether the dirs already have the right perms or provide an option to skip the check. Thanks for an excellent docker image!

**Comment by tomav** [comment]
Thanks @tve 
Would you submit a PR for that?

**Comment by tve** [comment]
Implemented in #194
