### ISSUE TITLE
Persist spool directories

### ISSUE THREAD

**Issue by tve** [tomav/docker-mailserver#191]
As far as I can tell, restarting the container looses the postfix spool directories. IMHO these should be mapped to a volume in the sample docker-compose file so they persist.

**Comment by tomav** [comment]
Here again, if you want to modify the wiki / `README.md`, feel free to do it.

I think we should do the same for spamassassin database.

**Comment by tomav** [comment]
The folder for spamassassin is `/var/lib/amavis/`

**Comment by Josef-Friedrich** [comment]
I tried to mount this folders outside:

* `/var/lib/spamassassin`
* `/var/lib/fail2ban`
* `/var/lib/amavis`
* `/var/lib/clamav`

**Comment by tve** [comment]
I see two options here. One is to mount a slew of volumes onto all the directories with state. The other is to mount one or two volumes and move where the various daemons put their data onto the volume using symlinks or config changes.

Mounting a slew of volumes is cleaner is a way in that it exposes what's going on and avoids mysterious symlinks and locations. But it doesn't allow for a nice backup model by mounting "the" volume onto a backup container. Having one volume with everything or perhaps two volumes (one for user mailboxes and one for "spool" stuff) makes the backup story simpler.

Thoughts?

**Comment by Josef-Friedrich** [comment]
I prefer the one (two) volume backup solution.

**Comment by 00angus** [comment]
That's a very good idea to allow persistence at least for emails spool.
The approach involving "a slew of volumes" is - IMHO - preferable as it makes explicit what will be shared with the host. After all once you have put all the relevant config in a docker-compose or a script it doesn't matter, I think.
Af for the convenience of the backup, if the slew of volumes come from the same base path ... it's the same :)
