### ISSUE TITLE
Remove SORBS from RBL

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#197]
I noticed that some mails coming from gmail were blocked because of SORBS blacklisted 209.85.217.172 which is Google IP.

It's not the first time and it's very annoying...

I suggest to remove SORBS from the RBL list.
Let me know what you think about that.

Thank you.

**Comment by netgusto** [comment]
Exactly the same problem for me. A lot of gmail emails being refused : 

```

May 26 05:38:34 mail postfix/smtpd[2923]: connect from mail-io0-f196.google.com[209.85.223.196]
May 26 05:38:45 mail postfix/smtpd[2923]: NOQUEUE: reject: RCPT from mail-io0-f196.google.com[209.85.223.196]: 554 5.7.1 Service unavailable; Client host [209.85.223.196] blocked using dnsbl.sorbs.net; Currently Sending Spam See: http://www.sorbs.net/lookup.shtml?209.85.223.196; from=<schneider.jerome@gmail.com> to=<contact@netgusto.com> proto=ESMTP helo=<mail-io0-f196.google.com>
May 26 05:38:45 mail postfix/smtpd[2923]: disconnect from mail-io0-f196.google.com[209.85.223.196]
```

**Comment by netgusto** [comment]
Fixed (I believe) by putting this line of conf in my `./config/postfix-main.cf`:
(removed the sorbs entry on the third line):

```
smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination,
    reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain,
    reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net
```

**Comment by dominikwinter** [comment]
Yes, i had same problem with SORBS. Sometimes it rejects mails from big mail providers:
> Gmail, Hotmail, web.de, freenet.de, GMX, Strato and T-Online
> -- https://de.wikipedia.org/wiki/SORBS

**Comment by tomav** [comment]
It seems that emails finally arrived but with a huge delay.

I'm gonna remove SORBS in the next minutes.
