### ISSUE TITLE
Amavis problem?

### ISSUE THREAD

**Issue by cjharding** [tomav/docker-mailserver#199]
The mail server is up and running in a Bluemix container. I can connect to it via IMAP but don't see any mail, although mail appears to be reaching it. A log is attached showing a re-start and initial transaction. From this, it looks as though amavis may not be starting. Is there something I should fix in the configuration, please?
[mail-log.txt](https://github.com/tomav/docker-mailserver/files/291281/mail-log.txt)

**Comment by tomav** [comment]
`You must explicitly assign a FQDN of this host to variable $myhostname`

It seems that your config is not correct. If you use `docker-compose`, please check thase lines:

````
    domainname: domain.com
    container_name: mail
```

Have a look to the `README`.

**Comment by cjharding** [comment]
Thanks for the quick response! Tried to avoid docker-compose as only need 1 container. Am now trying again using docker-compose - hopefully it will work.

**Comment by dsummersl** [comment]
Thank you, that did it for me too - without docker-compose (using ansible).
