### ISSUE TITLE
smtpd_proxy_filter - rejecting bad stuff and telling the sender about it

### ISSUE THREAD

**Issue by Bwooce** [tomav/docker-mailserver#20]
See http://www.postfix.org/SMTPD_PROXY_README.html

It's possible to configure postfix and amavis to pre-process email and reject it back, rather than the more standard way of accepting it and then deleting/tagging it.

It does have some con's - mainly around the max throughput. This isn't generally a problem on modern servers for small domains, but then again who knows who'll use your image. So it might not be appropriate.

So can you consider it? It's quite satisfying to reject spam at the outset, and it has the nice side-effect of bounce messages being sent back by the initiating mail server/person so a false positive has a better chance of being noticed.

**Comment by tomav** [comment]
If you'll submit a PR, I'll be happy to merge it.
Note that backward compatibility should not be broken, but I assume that postfix experts don't use default config.

**Comment by tomav** [comment]
Hi @Bwooce, will work on it? Do you need help?

**Comment by Bwooce** [comment]
I am working, slowly, on it -- I have it working on my own mail server now I just need to remember how/why I configured it this way. Shall I make it optional? Switch config files based on an environment variable maybe?

**Comment by tomav** [comment]
You have to remember that this image provided a default set of postfix config files. The question is: "this should be enable or not by default?".
If yes, it can go the default config. (purpose of your issue)
If no, it will be enabled using a custom config file.
I don't really think that we should add complexity in this code to support all possible use cases.

**Comment by tomav** [comment]
@Bwooce, I close this issue since there's no update on it. Feel free to repoen or push your enhancement when needed.
