### ISSUE TITLE
Training Spamassassin's classifier

### ISSUE THREAD

**Issue by cgorman** [tomav/docker-mailserver#203]
First off, thanks for this project. I was dreading upgrading my server after the last time I did it and this saved my skin.

Anywho, my previous setup used sa-learn to train its classifier on my different folders. I think I set it up to be just spam in JUNK and ham everywhere else. Is there any way to use that with this container, or do we just not need to do that? I only ask because I migrated everything yesterday and immediately got a couple spam e-mails in my inbox.

**Comment by Josef-Friedrich** [comment]
I had the same problem:

I changed the value of SA_TAG2

```
- SA_TAG2=2.0
```

**Comment by tomav** [comment]
I added cron on my server to launch `sa-learn` every day, like on classic postfix/amavis/spamassassin stack.

**Comment by cgorman** [comment]
Thanks for the info, this is my first foray into the Docker world so I wasn't sure what the best practices would be. I ended up writing a script that runs sa-learn and adding it to crontab, then committing the image. Seems to be working!

**Comment by cutec-chris** [comment]
Is it possible to add this script to this image here ?
