### ISSUE TITLE
Use a stronger Password hash algorithm

### ISSUE THREAD

**Issue by Crafter6432** [tomav/docker-mailserver#205]
I would propose to use SHA512 or SHA256 in your examples in order to protect the users passwords better in case of an database leak.

Other available algorithms: http://wiki.dovecot.org/Authentication/PasswordSchemes

**Comment by arielelkin** [comment]
>md5 and sh1 are both clearly broken
[Sauce](https://books.google.de/books?id=rZhgtN90rIIC&pg=PA199&lpg=PA199&dq=%22md5+and+sha1+are+both+clearly+broken%22&source=bl&ots=o7HI4AVhGx&sig=GnP3jXEbSvjH4uiAtmNJ6tcVqg4&hl=en&sa=X&ved=0ahUKEwiZ36X11pXNAhWBWxQKHfzxD50Q6AEIJjAC#v=onepage&q=%22md5%20and%20sha1%20are%20both%20clearly%20broken%22&f=false)

**Comment by tomav** [comment]
Good idea. Any other advice regarding the recommended algorithm?

**Comment by 00angus** [comment]
@arielelkin Good idea. I'm also currently using SSHA512 so for me it's ok.

**Comment by tomav** [comment]
@Crafter6432 are you ok to adapt the doc and tests files with `SSHA512 `?

**Comment by tomav** [comment]
WIP here https://github.com/tomav/docker-mailserver/pull/210

**Comment by arielelkin** [comment]
👍

**Comment by tomav** [comment]
Fixed by https://github.com/tomav/docker-mailserver/pull/210
