### ISSUE TITLE
Specify DNS Zone record

### ISSUE THREAD

**Issue by arielelkin** [tomav/docker-mailserver#206]
> Now the keys are generated, you can configure your DNS server by just pasting the content of config/opedkim/keys/domain.tld/mail.txt in your domain.tld.hosts zone.

I guess the exact procedure varies between different DNS providers, but could you please clarify if this is equivalent to adding a DNS Zone record, and if so what would be the subdomain (e.g. `*`) and type (e.g. `A` or `TXT`)?

**Comment by tomav** [comment]
Hi @arielelkin, the answer is in the [Wiki](https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM).
