### ISSUE TITLE
A way to override master.cf?

### ISSUE THREAD

**Issue by lauri865** [tomav/docker-mailserver#207]
Not really an issue with the repo, but probably my lack of knowledge.

Is there a way to override master.cf? I want to add a hook to trigger a php script, but couldn't find a way to override or append to master.cf. Any hints would be much appreciated.

**Comment by tomav** [comment]
There's currently no such feature. But could be added, we do the same thing for some other file.

**Comment by lauri865** [comment]
Pushed a commit related to this. Please have a look if you have time. Thanks!

**Comment by lauri865** [comment]
Took a different stab at it. Should add more flexibility by enabling free execution of postconf

**Comment by tomav** [comment]
Send the PR, I'll be able to see your 2 commit merged and review it.
You should also add integration tests.
Thanks.

**Comment by tomav** [comment]
Hi @lauri865, any update? Thank you.

**Comment by tomav** [comment]
Closed due to inactivity. Reopen if needed.
