### ISSUE TITLE
Error on generate-dkim-config

### ISSUE THREAD

**Issue by Nhoty** [tomav/docker-mailserver#209]
I just follow all the stap on the readme.md file.

root@server1:/var/lib/docker# docker run --rm \
>   -v "$(pwd)/config":/tmp/docker-mailserver \
>   -ti tvial/docker-mailserver:latest generate-dkim-config
/usr/local/bin/generate-dkim-config: 6: /usr/local/bin/generate-dkim-config: cannot open /tmp/docker-mailserver/postfix-accounts.cf: No such file
/usr/local/bin/generate-dkim-config: 13: /usr/local/bin/generate-dkim-config: cannot open /tmp/docker-mailserver/postfix-virtual.cf: No such file
Creating DKIM TrustedHosts
/usr/local/bin/generate-dkim-config: 61: /usr/local/bin/generate-dkim-config: cannot create /tmp/docker-mailserver/opendkim/TrustedHosts: Directory nonexistent
/usr/local/bin/generate-dkim-config: 62: /usr/local/bin/generate-dkim-config: cannot create /tmp/docker-mailserver/opendkim/TrustedHosts: Directory nonexistent
root@server1:/var/lib/docker#

**Comment by Nhoty** [comment]
It was a permission error ...

**Comment by jesusgalvan** [comment]
@Nhoty - how did you solve it?
