### ISSUE TITLE
Imap folders

### ISSUE THREAD

**Issue by hourliert** [tomav/docker-mailserver#21]
Hi.

First of all, thanks for this docker image. It works great and it is very easy to setup!
Almost everything works on my server but I cannot create mail folders.
I am using Mail from OS X and it cannot create Sent, Drafts and Trash folders.

I tried to use `maildirmake` into /var/mail/mydomain/myaccount/ and update `courierimapsubscribed` with 
```
.Trash
.Sent
.Drafts
```
but it doesn't work.

Do you have a solution?

Thanks in advance.

**Comment by hourliert** [comment]
It seems it is a El Capitan Mail issue. Creating a new imap folder crashes the software. Moreover, the mapping between courier imap folders and the displayed tree in mail is not done automatically.

It works great with Gmail on Android.

**Comment by tomav** [comment]
Ok, let me know if you find something, but I can confirm that I can't reproduce the problem with OSX Mail on 2 servers.
