### ISSUE TITLE
[AWS] Domain Name

### ISSUE THREAD

**Issue by ttermeer-ouat** [tomav/docker-mailserver#213]
This setup requires domainname in docker compose but AWS ECS task does not have such property. Any idea how to solve this ? amavis won't start because it doesn't have a FQDN in the hostname.

**Comment by roens** [comment]
ECS may not offer the flexibility required. I'm successfully running my server on a `t2.micro` instance.

**Comment by tomav** [comment]
@ttermeer-ouat can you try without `docker-compose` using `docker run -h mail.domain.tld`?

**Comment by ttermeer-ouat** [comment]
Unfortunately EB and ECS does not expose docker run call. You have to create task definition using AWS modified version of docker property.
Here is the list of available parameters : http://docs.aws.amazon.com/fr_fr/AmazonECS/latest/developerguide/task_definition_parameters.html

**Comment by tomav** [comment]
There is a `hostname` parameter in the page you linked.

**Comment by tomav** [comment]
```
hostname
Type: string
Required: no

The hostname to use for your container. This parameter maps to Hostname in the Create a container section of the Docker Remote API and the --hostname option to docker run.

"hostname": "string"
```

**Comment by tomav** [comment]
I close this issue because it's not related to our image.
Let us know how it works on AWS with the suggested parameter.

Thank you @ttermeer-ouat
