### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by wb9688** [tomav/docker-mailserver#214]
I tried to install this following the [wiki](https://github.com/tomav/docker-mailserver/wiki), but I get an error 404:

![Screenshot](http://i.imgur.com/s9DoyYb.png)

**Comment by tomav** [comment]
Can you paste the result of:
- `cat docker-compose.yml`
- `tree`

Thank you.

**Comment by tomav** [comment]
It seems to be a docker issue, not related to this container.
You should check https://github.com/docker/docker/issues/17960
