### ISSUE TITLE
letsencrypt accept files ending with .pem and without

### ISSUE THREAD

**Issue by strothj** [tomav/docker-mailserver#215]
There is an alternative acme client which creates a similar folder structure to the official client. The only difference is that the certificates do not have the .pem extension.

https://github.com/hlandau/acme
https://github.com/hlandau/acme/blob/master/_doc/SCHEMA.md

Is there a possibility of updating the letsencrypt SSL configuration section of start-mailserver.sh to take this into account?

**Comment by keslerm** [comment]
I made symlinks (e.g. fullchain.pem -> fullchain ) as a work around if anyone else hits this.

**Comment by tomav** [comment]
Symlink is the quickest way to do it.
I close this since its not an issue but we can discuss about an enhancement to manage this.
