### ISSUE TITLE
Option to disable AV

### ISSUE THREAD

**Issue by Crafter6432** [tomav/docker-mailserver#216]
It would be really nice to have an option to disable spamassassin, amavis and clamav as these services are very resource hungry(especially memory). In my case for instance these 3 services consume 23%(~450mb) which in my opinion isn't worth it as I'm the only user and know how to deal with viruses and spam if there's any.

**Comment by tomav** [comment]
Good idea @Crafter6432!
If you want to PR this enhancement, I'll be happy to merge it into master.
Be sure to read [this page](https://github.com/tomav/docker-mailserver/wiki/How-to-contribute) before.

**Comment by ep0ch2** [comment]
Don't suppose there's an image with this feature that i could test?

**Comment by KyleOndy** [comment]
@tomav Could we just wrap the configuration and starting of each component in a check for an Env var? Similar to the existing `ENABLE_MANAGESIEVE` and such?

I will submit a PR if that sounds reasonable.

**Comment by tomav** [comment]
@KyleOndy of course. But it could have an impact on some config files, like postfix.

**Comment by tomav** [comment]
Done
