### ISSUE TITLE
Catch-All Address

### ISSUE THREAD

**Issue by QuadStingray** [tomav/docker-mailserver#217]
Hi,

when I configure an chatch-all-address all mails for an existing account will delivered to the catch-all adress and not to the account. What I`m doing wrong?

postfix-accounts.cf

`account@example.com|{SHA512-CRYPT}$6$Pi8yxp1ztD/lSkyG$kYd1NizLTUSz7Pc8y3v0b9vxcpaBROTUf0Fn3JVPrxBZftWPJfy2h3n.MhYSVAk6BzDeWfNB1cSJYftWLii.W0`

`account2@example.com|{SHA512-CRYPT}$6$Pi8yxp1ztD/lSkyG$kYd1NizLTUSz7Pc8y3v0b9vxcpaBROTUf0Fn3JVPrxBZftWPJfy2h3n.MhYSVAk6BzDeWfNB1cSJYftWLii.W0`

postfix-virtual.cf
`
@example.com account2@example.com
`

And one other question.
Can I configure that mails will send to an account and forwarded to an other email address?

**Comment by approached** [comment]
Catchall work fine with:
```
@example.com account2@example.com 
```

But you can always use like this:
```
@example.com example@gmail.com 
```

**Comment by daitangio** [comment]
So to configure a catch all rule to my account "account1" I could issue the following setup command?
`./setup.sh alias add @example.com account1@example.com`

(Thank you for this wonderful code by the way!)
