### ISSUE TITLE
Undelivered Mail Returned to Sender.

### ISSUE THREAD

**Issue by hourliert** [tomav/docker-mailserver#22]
Hi,

I have setup the docker container on my server. [Here](http://mxtoolbox.com/SuperTool.aspx?action=smtp%3amail.cnode.fr&run=toolpage) is its diagnostic.

When I am trying to send a mail to an icloud email, I always get a mail saying that my mail hasn't been delivered:

```
This is the mail system at host mail.cnode.fr.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<xxxxx@me.com>: host mx1.mail.icloud.com[17.158.8.68] said: 550 5.7.0
   Blocked - see
   https://support.proofpoint.com/dnsbl-lookup.cgi?ip=62.210.110.165:
   xxxxx@me.com (in reply to RCPT TO command)
Reporting-MTA: dns; mail.cnode.fr
X-Postfix-Queue-ID: 11227CE2
X-Postfix-Sender: rfc822; thomas.hourlier@cnode.fr
Arrival-Date: Thu,  1 Oct 2015 19:47:05 +0000 (UTC)

Final-Recipient: rfc822; xxxxx@me.com
Original-Recipient: rfc822;xxxxx@me.com
Action: failed
Status: 5.7.0
Remote-MTA: dns; mx1.mail.icloud.com
Diagnostic-Code: smtp; 550 5.7.0 Blocked - see
   https://support.proofpoint.com/dnsbl-lookup.cgi?ip=62.210.110.165:
   xxxxx@me.com
```

Do you have any idea why?

Thanks in advance.

**Comment by tomav** [comment]
@hourliert: Your IP seems to be blocked (banned) in Proofpoint RBL as you can see on the link:
https://support.proofpoint.com/dnsbl-lookup.cgi?ip=62.210.110.165

You're not listed in other RLBs (I had a look), you're not an open Relay (I also checked), but Proofpoint is used by Apple (me.com, icloud.com...)...
You should use the the form to ask for removal (this is probably a false positive).
