### ISSUE TITLE
Spam auto-removed

### ISSUE THREAD

**Issue by lnalex** [tomav/docker-mailserver#220]
Hi,

I tried to test the spam configuration with the [GTUBE](https://spamassassin.apache.org/gtube/).

I created a junk folder and a Sieve rule to move all spam flagged email to this folder but it (SpamAssassin, Amavis or Postfix ?) still remove my email.

trace log:

    mail    | Jul  2 17:23:01 mail amavis[585]: (00585-01) Blocked SPAM {DiscardedInbound,Quarantined}, [1.1.1.1]:54163 [1.1.1.1] <example@example.com> -> <example@example.com>, quarantine: g/spam-g6Yyuff9jLdF.gz, Queue-ID: 8139A778, Message-ID: <b8e0ff83-a501-388a-8819-ee0f5e9fd16e@example.com>, mail_id: g6Yyuff9jLdF, Hits: 1000.364, size: 3706, 5233 ms

    mail    | Jul  2 17:23:01 mail postfix/smtp[594]: 8139A778: to=<example@example.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=5.6, delays=0.34/0.01/0.01/5.2, dsn=2.7.0, status=sent (250 2.7.0 Ok, discarded, id=00585-01 - spam)

    mail    | Jul  2 17:23:01 mail postfix/qmgr[582]: 8139A778: removed

How can we solve this issue ?

**Comment by wanaoishi** [comment]
Have the same problem, 
This is quite important that SPAM are not removed.

**Comment by tomav** [comment]
Hi @lnalex and @wanaoishi, there is a docker env named `SA_KILL` set by default to `6.31`. From this score and above, emails are deleted. This is an amavis/spamassassin configuration.
Your test email is `Hits: 1000.364`.

Refer to spamassassin configuration for more information.

**Comment by tomav** [comment]
Let me know.

**Comment by lnalex** [comment]
That was the point. Thanks !

**Comment by wanaoishi** [comment]
Thanks Tomav,
is there a way not to remove them but to move them to a spam box?

**Comment by lnalex** [comment]
@wanaoishi You have to create a Sieve filter for your account.

    require "fileinto";
    if header :contains "X-Spam-Flag" "YES" {
      fileinto "Spam";
    }

**Comment by wanaoishi** [comment]
Thanks
