### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by sspreitzer** [tomav/docker-mailserver#221]
Hi 

I am updating from an older version and have to heavily fight with configuration changes that where brought in.
If they where a CHANGELOG this would be much easier.

Kind regards
Sascha

**Comment by kopax** [comment]
I have opened a related [issue](https://github.com/tomav/docker-mailserver/issues/219)

+1 for changelog, did you manage to upgrade to v2?

**Comment by tomav** [comment]
@sspreitzer thanks for the PR. Merged.

@kopax: I personally upgraded changing the `docker-compose.yml` and pulling the new image.
I use LetsEncrypt certs. Nothing more.

I'll have a look to your issue, but perhaps you can start a new Wiki page on this topic with ideas you have.
