### ISSUE TITLE
Docker Compose v1

### ISSUE THREAD

**Issue by lnalex** [tomav/docker-mailserver#225]
I use Rancher for container orchestration and only accept version 1 of docker compose file.
Since 9e1c4783a81fcad6c928a2439a0c9db54f511236 it has been upgraded to version 2.

Is it possible to keep a working version 1 of docker compose file ?

**Comment by tomav** [comment]
Hi @lnalex, yes it should be possible.
Have a look to the [v1 format](https://github.com/tomav/docker-mailserver/tree/v1) and keep the paths of v2.

Let me know.

**Comment by lnalex** [comment]
Ok great I'll test it. I didn't knew if the v1 was still updated.
