### ISSUE TITLE
/etc/postfix/vhost for Domain listining

### ISSUE THREAD

**Issue by approached** [tomav/docker-mailserver#227]
hi@all

i have many domains and i will generate for these domains a alias. Like this:

/etc/postfix/vhost
```
domain1.com
domain2.com
domain3.com
```

Alias file:
```
@domain1.com fat@domain1.com
@domain2.com fat@domain1.com
@domain3.com fat@domain1.com
```

Question: How i can manage the vhost file. I will that postfix will listening other domains too.

**Comment by tomav** [comment]
Have you tried to create a user `fat@domain1.com` and add the aliases in `postfix-virtual.cf`

**Comment by approached** [comment]
Good idea.
I think it will be worked. But this would be a workaround.

**Comment by tomav** [comment]
Hi @approached, I just tried what I suggested and it works as expected.
I added `@localdomain2.com user1@localhost.localdomain` in the virtuals and sent an email to 
`wildcard@localdomain2.com`.

Mail is received and delivered to `user1@localhost.localdomain`.

```
Jul 22 20:37:35 mail postfix/smtp[701]: 04962770: to=<user1@localhost.localdomain>, orig_to=<wildcard@localdomain2.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=1.5, delays=0.22/0.01/0.06/1.2, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 7086277F)
Jul 22 20:37:35 mail postfix/qmgr[668]: 04962770: removed
Jul 22 20:37:35 mail dovecot: lda(user1@localhost.localdomain): msgid=<20160722203734.04962770@mail.my-domain.com>: saved mail to INBOX
Jul 22 20:37:35 mail postfix/pipe[706]: 7086277F: to=<user1@localhost.localdomain>, relay=dovecot, delay=0.05, delays=0.01/0/0/0.04, dsn=2.0.0, status=sent (delivered via dovecot service)
Jul 22 20:37:35 mail postfix/qmgr[668]: 7086277F: removed
```
