### ISSUE TITLE
GMail add account

### ISSUE THREAD

**Issue by galuszkak** [tomav/docker-mailserver#23]
I setup account in Thunderbird and everything works great!

But when I'm trying to attach to Gmail I got an error with authentication. I got an error something like this:
"PDE1ODM5MTAzNTAuMTM5MzI4NUBtYWlsLmNsdWJhbGwuY29tPg== code(334)"

I'm not sure what is causing that and didn't find anything in logs.

**Comment by tomav** [comment]
Hi @galuszkak, what do you mean by "attach to Gmail"?

**Comment by galuszkak** [comment]
@tomav there is option to add other e-mail account to GMail. I'm using it to have different email accounts linked in one inbox.
![screen shot 2015-10-07 at 18 35 07](https://cloud.githubusercontent.com/assets/759579/10344194/2bd48f22-6d22-11e5-8590-8c34b44d8c19.png)

**Comment by tomav** [comment]
Ok I see.
Some inputs:
* have you setup TLS/SSL?
* have you checked your certificate configuration?
* are you sure there is nothing in `/var/log/mail.log`?

I'll try to find some time to test on my server.

**Comment by galuszkak** [comment]
@tomav 
1) Yes 
2) Yes -> I have this working in Thunderbird.
3) Nothing.
```
root@mail:/# cat /var/log/mail.log
root@mail:/# 
```

**Comment by galuszkak** [comment]
@tomav  I'm happy to provide more. I'm not an expert in field of , so if you will want more information then I will be happy to help. When I'm thinking about TLS/SSL I think I have it right (I generated this into ssl/ directory). But is there any verbose output when I'm starting container that this is done right?

**Comment by tomav** [comment]
@galuszkak I can't find how to add a non-POP account to help you...

**Comment by tomav** [comment]
POP is not supported by this image. I don't know if you have enabled POP or if Gmail let you add an IMAP account, but I need more information to give it a try.
Reopen this issue if you still have a problem.
