### ISSUE TITLE
Postfix:  status=deferred (mail system configuration error) 

### ISSUE THREAD

**Issue by hitokiri8x** [tomav/docker-mailserver#230]
Hello, I'm having this error 

>     status=deferred (mail system configuration error) postfix 

while users sends email between them. (ex.   user1@example.com sends and email to user2@gmail.com and cc  user3@example.com ; user3 generate that error).
I should have set everything all-right, I tried also to set postfix's  main.cf 
>    mydestination = example.com.  (instead of blank )

but then in the log I gain the warning 
>    mail postfix/trivial warning: do not list domain  in BOTH mydestination and virtual_mailbox_domains

**Comment by tomav** [comment]
Reproduced with your test case.

**Comment by StreakyCobra** [comment]
I have the same problem with a slightly different use case:

I defined the following virtual aliases:

    info@example.com user1@example.com,user2@example.com
    sales@example.com user2@example.com

Sending a mail to `sales@example.com` works as expected, i.e. the mail is being forwarded to `user2@example.com`.

Sending a mail to `info@example.com` doesn't work as expected, i.e. the mail is not sent to any user, with this following error displayed: `(mail system configuration error)`

    Jul 20 11:47:31 mail postfix/pipe[663]: 72A62733: to=<user2@example.com>, relay=dovecot, delay=495, delays=495/0.01/0/0.08, dsn=4.3.5, status=deferred (mail system configuration error)
    Jul 20 11:47:31 mail postfix/pipe[663]: 72A62733: to=<user1@example.com>, relay=dovecot, delay=495, delays=495/0.01/0/0.06, dsn=4.3.5, status=deferred (mail system configuration error)

This warning is displayed right after the block of the failing mail in the log:

    warning: pipe flag `D' requires dovecot_destination_recipient_limit = 1

I *assume* my problem is related, but if not let me now, I'll open a new issue.

**Comment by StreakyCobra** [comment]
I confirm the issue is fixed for my use case. Thanks a lot!

**Comment by tomav** [comment]
Great!
