### ISSUE TITLE
clamav start fail

### ISSUE THREAD

**Issue by bigpigeon** [tomav/docker-mailserver#231]
when i sent mail, I found error in logs:
mail    | Jul 14 06:22:53 mail amavis[618]: (00618-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
mail    | Jul 14 06:22:54 mail amavis[618]: (00618-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
mail    | Jul 14 06:22:54 mail amavis[618]: (00618-01) (!)ClamAV-clamd: All attempts (1) failed connecting to /var/run/clamav/clamd.ctl, retrying (2)
mail    | Jul 14 06:23:00 mail amavis[618]: (00618-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
mail    | Jul 14 06:23:00 mail amavis[618]: (00618-01) (!)ClamAV-clamd av-scanner FAILED: run_av error: Too many retries to talk to /var/run/clamav/clamd.ctl (All attempts (1) failed connecting to /var/run/clamav/clamd.ctl) at (eval 136) line 603.\n

and ps aux | grep -i clam output is none:
root@mail:/# ps aux | grep -i clam
root      1021  0.0  0.0   8860   644 ?        S+   06:35   0:00 grep --color=auto -i clam

this is my docker-compose.yml:

services:
  mail:
    image: tvial/docker-mailserver:v2
    #build: .
    hostname: mail
    domainname: xxxxxxxx
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt:/etc/letsencrypt
    environment:
    - SSL_TYPE=letsencrypt
    - ENABLE_FAIL2BAN=1
    cap_add:
    - NET_ADMIN
volumes:
  maildata:
    driver: local

I sure my domainname is right

**Comment by bigpigeon** [comment]
I guess  memory was not enouth

**Comment by jmparra** [comment]
maybe is a memory issue https://github.com/tomav/docker-mailserver/issues/6

**Comment by bigpigeon** [comment]
yeah, i alse guess memory issue
my ec2 was 1GB memory

**Comment by ifolarin** [comment]
I had a situation on a DO Droplet with 1GB RAM. The system ran normaly when CLAMAV is disabled but maxed out the processor when enabled with the following output in the logs: 

>mail            | 2018-03-18 00:54:26,389 INFO spawned: 'clamav' with pid 2309
>mail            | 2018-03-18 00:54:27,392 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
>mail            | 2018-03-18 00:54:59,631 INFO exited: clamav (terminated by SIGKILL; not expected)
>mail            | 2018-03-18 00:55:00,641 INFO spawned: 'clamav' with pid 2322
>mail            | 2018-03-18 00:55:01,645 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
>mail            | 2018-03-18 00:55:21,847 INFO exited: clamav (terminated by SIGKILL; not expected)

It turns out that swap was not enabled on the VM and once I did, the issue was resolved. 
Someone might find this helpful.
