### ISSUE TITLE
usually Connection timed out

### ISSUE THREAD

**Issue by bigpigeon** [tomav/docker-mailserver#233]
when I sent large numbers mail  .i was see like this
```
mail    | Jul 19 08:03:44 mail postfix/smtp[1341]: connect to gmail-smtp-in.l.google.com[209.85.144.26]:25: Connection timed out
mail    | Jul 19 08:03:44 mail postfix/smtp[1341]: connect to gmail-smtp-in.l.google.com[2607:f8b0:400d:c0e::1a]:25: Network is unreachable
```

and the mail queue was very long

**Comment by tomav** [comment]
Seems that `ipv6` is default. This could probably be improved.

**Comment by tomav** [comment]
`inet_protocols = all` is currently being used.
Changing it to `ipv4` should do the trick.

I'm gonna check to have a feature for this.

**Comment by tomav** [comment]
@bigpigeon no need of new feature, use this : https://github.com/tomav/docker-mailserver/wiki/Override-default-postfix-configuration
