### ISSUE TITLE
Looking for contributors

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#236]
Hi guys, first of all, thanks for using this image and for all you contributions on code and the wiki which looks great.
We've now 500+ stars but, as the project become more and more used, my availability for it doesn't scale.

That's why I'm looking for 2 contributors that can help me to answer questions, improve documentation and tools, and think about new versions.

If you interested, leave a message here, tell me briefly who you are and if you have particular docker/postfix/dovecot skills. It's not an interview, you don't have to send a resume but it's more convenient to know more about each others 😄

**Comment by KyleOndy** [comment]
I'll throw my hat into the ring.

-----

As a fairly new comer to the opensource world I am looking for something other than a personal project to get involved with, I think docker-mailserver is a good fir for me. I would like to contribute to the sustained development and hopeful proliferation of this project. 

## The ~~Bad~~ Not Ideal

* I do not have any experience with postfix or dovecot (or any email system) beyond what I've figured out working with this project... but I'd like to learn.

## The Good

* I do work with docker in a professional setting, although docker is not used in a professional setting.
* I have moved the majority of my email communications to my `docker-mailserver` so I have my own skin in the game keeping the project running.

**Comment by tomav** [comment]
Thanks @KyleOndy, and by the way thanks for you additions.

@Josef-Friedrich, @00angus, also interested?

**Comment by Josef-Friedrich** [comment]
I’m interested. I can work on _“ Refactor ENV enable/disable. "Everything" should be disabled by default to let users configure their container”_

3 years ago I set up a mail environment (postfix, dovecot, fetchmail, roundcube) without docker on debian. This setup runs 3 years and now I switch to this project.

**Comment by tomav** [comment]
@KyleOndy, @Josef-Friedrich are you more Gitter or Slack?
If you're ok, we can have a chat room to synchronize each others or discuss if some points need it.

**Comment by Josef-Friedrich** [comment]
Unfortunately I have neither Gitter nor Slack. I’m a old-fashioned man. But I can create an account. That’s no problem.

**Comment by tomav** [comment]
@KyleOndy still interested?

**Comment by KyleOndy** [comment]
Sorry, I was out of the country the last ~2 weeks. I am still interested in helping out. 

I can use either Glitter or slack. No real preference.

**Comment by tomav** [comment]
Great!

**Comment by 00angus** [comment]
I'm still travelling, I've seen some of the threads but I don't know how to
help as currently I'm a little bit busy.

Great project and I'll continue to look out for any help I can give!

**Comment by tomav** [comment]
OpenSource is probably not a fulltime job for us :-)
Good to know that we could be 4 core members.
