### ISSUE TITLE
How to install signed certs, and configure sub domain for domain delivery

### ISSUE THREAD

**Issue by kopax** [tomav/docker-mailserver#24]
Hi, I am pretty new to postfix, I was using iRedmail and didn't have to care about postfix configuration.
I need to dockerize my mail server, that's why after testing a bunch of image, I choosed your configuration.

Could you provide further information for 

 - domain configuration
 - signed certs configuration

I have a mail server which is at mail.mydomain.com, I want it to be able to manage mail @mydomain.com

I also have wildcard certs from Gandi.
I want to use it for not having to confirm the security exception.
I was able to configure some nginx reverse proxy, iredmail and other SSL conf, but I will ask just for being sure because I can't make it work, if I should modify some files (eg: main.cf) and where

    # postfix/ssl/mail.my-domain.com-key.pem (used in postfix)

This one seems to be the one key

    # postfix/ssl/mail.my-domain.com-req.pem (only used to generate other files)

Don't know what it is

    # postfix/ssl/mail.my-domain.com-cert.pem (used in postfix)

Seems to be the cert

    # postfix/ssl/mail.my-domain.com-combined.pem (used in courier)

Seems to be the certs combined with gandi certs.

**Comment by tomav** [comment]
Hi @kopax, thanks for choosing this image.
I'm not a postfix expert neither, but I'll try to help you.

I think that generated certs (with the provided tool) are probably not named explicitly.
Any suggestion welcome.

Anyway, you will find a part of your answer here:
https://github.com/tomav/docker-mailserver/blob/master/bin/generate-ssl-certificate

Let me know if you can't find your answer there.

**Comment by kopax** [comment]
Well, I have decided first to try with the signed certs and I couldn't make it work.
Do I have any extra configuration to know for configuring a mail server at mail.mydomain.com to host mail to @mydomain.com ?

**Comment by tomav** [comment]
This is a postfix related question, not docker.
But I'll suggest you to use your own files in `main.cf`

        smtpd_tls_cert_file=/etc/postfix/ssl/mail.domain.com-cert.pem
	smtpd_tls_key_file=/etc/postfix/ssl/mail.domain.com-key.pem
	smtpd_tls_CAfile=/etc/postfix/ssl/cacert.pem
	smtp_tls_CAfile=/etc/postfix/ssl/cacert.pem

**Comment by tomav** [comment]
And this page should help you: http://www.postfix.org/TLS_README.html

**Comment by tomav** [comment]
@kopax I hope your certs are working as expecting. Without update from you, I close this issue.
