### ISSUE TITLE
DKIM does not respect hostname

### ISSUE THREAD

**Issue by auchri** [tomav/docker-mailserver#242]
I've set my hostname do something different than `mail`.

But generate-dkim-config still generates the key for `mail`: https://github.com/tomav/docker-mailserver/blob/master/target/bin/generate-dkim-config#L36 & https://github.com/tomav/docker-mailserver/blob/master/target/bin/generate-dkim-config#L47

I don't know if this is the correct behavior. If this works as expected, please close the issue.

**Comment by tomav** [comment]
Perhaps ask @bilak who added the feature.

**Comment by tomav** [comment]
@auchri did you try it on your server? The `selector` given is just a name (it could be default) and should work with other sub-domains of the main domain.

Let me know.

**Comment by auchri** [comment]
Yes it works, but if you have different mailservers on different subdomains it won't work.

**Comment by tomav** [comment]
Will you be able to contribute a patch for that?

**Comment by bilak** [comment]
Hi can you please investigate why it should not work?

**Comment by auchri** [comment]
@bilak Because I assume the second mailserver on a different subdomain would generate a different DKIM key at the same selector.

**Comment by bilak** [comment]
@auchri if there are different subdomains, there will be different DKIM keys (eg mail._domainkey.subdomain1.domain.com and mail._domainkey.subdomain2.domain.com). I see here two possible issues:

1. we aren't able to use custom selectors
2. if we want to be able to use dkim of parent domain in subdomains (we are using it by specifying --subdomains flag in genkey) the process should check if key for parent domain already exists and if so skip the subdomain key generation. In other scenario if at first subdomain key was generated then ???delete subdomain key and create key with parent domain name???

**Comment by tomav** [comment]
@auchri, reopen this issue if you have any other element to provide regarding @bilak explanation.
Thank you.
