### ISSUE TITLE
Account that is an alias

### ISSUE THREAD

**Issue by chrisella** [tomav/docker-mailserver#244]
Hi,
I've just gotten started using this great container you've put together. It's vastly simplified getting my mail server up, so huge thanks for that!
In the past on my mail server I had an account like that defined in postfix-accounts.cf which I/family could use to send mail as on google. You would use those credentials to add the account in the gmail settings.

Then my server would just forward all mail to their domains to their gmail account, so in postfix-virtual.cf something like xx@xx.com  xx@gmail.com

This is so close to working for me, the account can be logged on from gmail and I can send as that user/email address. The only problem is that I can't seem to get email sent to that account to be forwarded instead of sent to the mail box folder. Having a virtual alias defined that matches the account doesn't work, it seems the account take priority.

I hope I've explained my predicament well enough and I'd greatly appreciate any help anyone could lend to solving this, I don't know if it is a bug or simply a matter of me configuring it differently.

**Comment by auchri** [comment]
You could create a filter which forwards all messages: https://github.com/tomav/docker-mailserver/wiki/Configure-Sieve-filters

> require ["copy"];

> redirect :copy "user2@otherdomain.tld";

**Comment by tomav** [comment]
Hi @chrisella and thanks for your feedback.
You should separate the account and the alias. What I mean here is that, as you said, account takes priority on alias. So create another mail account, and use your alias for external forward.

The Sieve configuration that @auchri exposed could work too.

**Comment by kachkaev** [comment]
@auchri should not it be just this?
```
redirect "user2@otherdomain.tld";
```
The messages preserve in the inbox otherwise and it will eventually get full.
