### ISSUE TITLE
Feature Request: OpenSMTPD

### ISSUE THREAD

**Issue by joelchen** [tomav/docker-mailserver#245]
With [goals](https://opensmtpd.org/goals.html) similar to [Docker](https://www.docker.com/what-docker) in terms of lightweight(lean) and secure, I think [OpenSMTPD](https://opensmtpd.org) is a better fit for this project than Postfix. What do you think?

**Comment by tomav** [comment]
Hi @joelchen, I've never heard about OpenSMTPD before.
I checked online for comparaison but it seems to be "too young".
I also checked [google trends](https://www.google.com/trends/explore?cat=31&date=today%2012-m&q=opensmtpd,postfix&hl=en-US) to see the activity and discussions around it...

I can't see any advantage of such migration now.
Personally, I wouldn't change to OpenSMTPD.

Guys, what do you think about it?

**Comment by tomav** [comment]
Not planned.
