### ISSUE TITLE
Does not work with Docker Cloud

### ISSUE THREAD

**Issue by kevintraver** [tomav/docker-mailserver#248]
Is it possible to override `domainname`?

`hostname`,`domainname`, and `container_name` are not valid keys and cannot be manually set when using a Docker Cloud YAML stack file.

**Comment by tomav** [comment]
Hi @kevintraver, it seems that `hostname` and `domainname` are supported in Docker Cloud YAML doc.
https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#/single-value-keys-analogous-to-a-docker-run-counterpart

```
hostname: foo
domainname: foo.com
```

How can we help?

**Comment by kevintraver** [comment]
Ah, I did not realize that. Thanks!

**Comment by kevintraver** [comment]
It looks like there must be a different way set those properties. Regardless, this seems to be more of an issue with Docker Cloud so we can probably close this

**Comment by tomav** [comment]
True.
