### ISSUE TITLE
Multiple mail-addresses for single user

### ISSUE THREAD

**Issue by BirgerK** [tomav/docker-mailserver#249]
Is it possible that an user receives his mails by multiple mail-addresses?

For example the user `user1@domain.tld` gets all mails in his inbox when the mail was sent to:
* `user.1@domain.tld` or
* `1@domain.tld` or
* `user@domain.tld` or
* `user1@domain.tld` or
* .... I think you get it ...

Is it possible to do this? Does Dovecot can work with it?

**Comment by tomav** [comment]
Yep, create `user1@domain.tld` as an account and the other as aliases.
https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts
https://github.com/tomav/docker-mailserver/wiki/Configure-Aliases

They can on the same or different domains.

I personnally use this configuration with an account and 500+ aliases.
