### ISSUE TITLE
forward only domains are not added to vhosts

### ISSUE THREAD

**Issue by tbutter** [tomav/docker-mailserver#25]
When I add a domain in /postfix/virtual like this

test@test.com blah@example.com

The domain test.com should appear in vhosts, but it only appears if there is a user @test.com in accounts.cf.

**Comment by tomav** [comment]
You're right, we have to parse the file and move line 32 later in the script.
https://github.com/tomav/docker-mailserver/blob/master/start-mailserver.sh#L32

Are you able to do it?

**Comment by tomav** [comment]
Link to the build status:
https://hub.docker.com/r/tvial/docker-mailserver/builds/boaqlhnekjfyy3rmpaocn44/

Image will be available soon.
