### ISSUE TITLE
SMTP Relay 

### ISSUE THREAD

**Issue by peterphilipp** [tomav/docker-mailserver#252]
Hi,

thanks for this great docker image! 

One Question: I do not get how to use external Relay servers. For that I need to change "/etc/postfix/sasl_passwd" but so far I do not see how add parameters to that file. Do I overlook something, or would that be a feature request?

Best regards from Hamburg

Peter

**Comment by tomav** [comment]
Hi @peterphilipp, [this feature exists](https://github.com/tomav/docker-mailserver#sasl_passwd).
