### ISSUE TITLE
Easy config for secondary / backup MX server

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#254]
Note for later...

**Comment by citec** [comment]
+1

**Comment by tomav** [comment]
- `SERVER_TYPE` with `primary` as default, `secondary` as other possible value
- keep file generation in both modes
- synchronize recipient list from primary to secondary using `scp`

**Comment by Neikius** [comment]
What about dovecot master/master replication: http://wiki.dovecot.org/Replication ?

**Comment by tomav** [comment]
@Neikius yep why not, have you tried to?

**Comment by tronicum** [comment]
after hacking some stuff into the #254 branch. secondary and primary is ok for 2 node clusters. should we care about 3? if we do master master (#430), this naming scheme is not relevant as both are master. thinking about it.

function _setup_ha_nonprimary() {
....
}

it should act as being a master, unless it is tagged as a slave (dont like that name) 
or failover node (failover does not "work" for master/master setup as a name).

**Comment by mhf-ir** [comment]
:+1:

**Comment by tomav** [comment]
@voti is also interested in this feature in case you want to feed the discussion.

**Comment by fmax** [comment]
+1
would be greate to have a backup MX server with postfix _relayhost=_ option in main.cf
:)

**Comment by dozd** [comment]
So is setup with multiple MX records with more hosts working in some way?
I think it's a must for a mailserver

**Comment by LukeMarlin** [comment]
I'm considering trying docker-mailserver, however having no HA is a no-go for me for email. Was there any progress regarding this issue?

**Comment by erik-wramner** [comment]
It seems not. I agree that it would be useful but someone needs to invest the time and submit a PR.

**Comment by LukeMarlin** [comment]
Would poping two instances with the same shared volume for data be enough?
I suppose we'd also need to share the LDAP and configuration files right?

**Comment by erik-wramner** [comment]
Not really, a HA configuration must be able to run on separate physical machines. Docker does not support distributed read/write volumes and even if you run in some cloud solution that does there would be other issues. A dedicated backup server is probably the easiest approach.

**Comment by fbartels** [comment]
@LukeMarlin you have to be aware, though that having a backup mx is something quite different than HA (it just receives your mails for you and once your primary system is back online, relays them to it).

For replication within Dovecot one could use dsync (some more details in https://wiki.dovecot.org/Replication).

**Comment by j-marz** [comment]
Here is how i run docker-mailserver as a backup MX.

Create `postfix-main.cf` in config directory and add the following:
```
relay_domains = hash:/tmp/docker-mailserver/backupmx/relays
transport_maps = hash:/tmp/docker-mailserver/backupmx/transport
relay_recipient_maps = hash:/tmp/docker-mailserver/backupmx/relay_recipients
maximal_queue_lifetime = 14d
```

Create a directory called `backupmx` and the following files `relays`, `transport` and `relay_recipients`.

`relays` should contain the domains you would like to queue & relay mail for. E.g.
```
domain1.com OK
domain2.com OK
```

`transport` should contain the final destination mail server to relay the queued email to. E.g.
```
domain1.com smtp:mail.domain1.com
domain2.com smtp:mx1.domain2.com
```

`relay_recipients` should contain a list of valid recipients that will be accepted, queued and relayed. E.g.
```
info@domain1.com OK
user@domain2.com OK
```

For the above to work, the following commands must be run inside the container:
```
cd /tmp/docker-mailserver/backupmx/
postmap relays
postmap transport
postmap relay_recipients
```

I haven't had time to create a PR for this, but hopefully this helps someone.

**Comment by erik-wramner** [comment]
@j-marz that is excellent. Some possibly stupid follow-up questions:

1. Is this in a container with SMTP_ONLY, or what services should be running?
2. How about DKIM keys and SPF? Separate DKIM keys for each container and both servers listed as valid senders in the SPF policy?
3. Can/should the backup run postgrey, spamassassin and so on, or should it just accept everything?

**Comment by j-marz** [comment]
>     1. Is this in a container with SMTP_ONLY, or what services should be running?
No, but it should work in `SMTP_ONLY` mode. All the backup MX config is related to `postfix`, so that's the minimum required service for this to work.

>     2. How about DKIM keys and SPF? Separate DKIM keys for each container and both servers listed as valid senders in the SPF policy?
SPF and DKIM aren't required as the backup MX is only queuing and relaying mail originally destined for your domains to your primary server. It's not acting as a backup outbound SMTP server, only inbound.

Having said that, `Sender Rewriting Scheme` (SRS) should probably be enabled to avoid any potential SPF issues.

>     3. Can/should the backup run postgrey, spamassassin and so on, or should it just accept everything?
It's personal preference i guess, but I would recommend it. It will:
1. Reduce load/anti-spam processing on the primary MX (once it's back online)
2. Ensure spam is not hosted on the backup MX and made available to mail clients should you provide direct access to the backup MX server

**Comment by aendeavor** [comment]
This issue has stalled and is marked as frozen. Due to age and inactivity, I will close it off in 10 days.

**Comment by VincentSC** [comment]
Has a PR be made for this? Or is it better to make a docker-build for this?

> Here is how i run docker-mailserver as a backup MX.
> 
> ...
> 
> I haven't had time to create a PR for this, but hopefully this helps someone.

**Comment by georglauterbach** [comment]
I think there was no PR and building it yourself is a good idea :)

**Comment by dulinux** [comment]
I got it working simply by doing this. Basic idea from [here](https://www.postfix.org/STANDARD_CONFIGURATION_README.html#backup).

mailserver.env:

```
SMTP_ONLY=1
```
Don't really need dovecot running if this is just a backup mx forwarder.

docker-data/dms/config/postfix-main.cf:

```
relay_domains = thebackedupdomain.tld
smtpd_relay_restrictions = permit_mynetworks reject_unauth_destination
relay_recipient_maps = hash:/tmp/docker-mailserver/relay_recipients
```

docker-data/dms/config/relay_recipients:

```
# Forward every email
@thebackedupdomain.tld OK
```

This will forward every email, but it's best practice to maintain a list of valid recipient addresses on the backup MX host, as described in the "Relay Recipients" section [here](https://www.linuxbabe.com/mail-server/how-to-set-up-a-backup-email-server-postfix-ubuntu).

docker-data/dms/config/relay_recipients:

```
#Forward just valid recipients
user1@thebackedupdomain.tld OK
user2@thebackedupdomain.tld OK
...

```
Create the hash:

```
docker exec mailserver postmap /tmp/docker-mailserver/relay_recipients
```

Restart the container.

**Comment by kub3let** [comment]
Note: do not use `ENABLE_SRS=1` otherwise you will get `554 5.7.1 : Relay access denied`

Also it's important to configure the main mail server to disable SPF checks for the backup server https://docker-mailserver.github.io/docker-mailserver/latest/config/best-practices/dkim_dmarc_spf/#backup-mx-secondary-mx-for-policyd-spf otherwise you will miss mails for domains that have spf with hard fail enabled

Also configure DMARC for the backup if you want bounces to go back
