### ISSUE TITLE
RFC: config as named volume, not directory

### ISSUE THREAD

**Issue by mathuin** [tomav/docker-mailserver#259]
Anyone can fork a project -- I'd like my contributions to be upstream-friendly, so I don't want them to come as a complete surprise.  Before I put any effort into this idea, I wanted to ask for comments and thoughts.  

Tools like Rancher and docker-machine work well with named volumes, and less so with mounted directories.  Changing config to work as a named volume would involve the following steps:

- modifying the test suite to use a named volume instead of a directory
- fixing all the now-broken code
- updating the documentation to reflect the new tasks
- possibly adding some additional tools to add users and the like

What do you think?

**Comment by Josef-Friedrich** [comment]
Is it possible to use both mount options?: mounted directories as well as named data volumes.

**Comment by tomav** [comment]
Hi @mathuin,
Same as @Josef-Friedrich, docker offers both options. We should not constraint on that point.
Regarding your last point, have a look to https://github.com/tomav/docker-mailserver/blob/master/setup.sh

**Comment by mathuin** [comment]
The one major issue I found when using a named volume has now been addressed, and I have been using this project in production for a week or so now.  I'm okay for this to be closed, if you are.
