### ISSUE TITLE
Fetchmail

### ISSUE THREAD

**Issue by jcgruenhage** [tomav/docker-mailserver#260]
What do you think about including fetchmail?
You can use that to fetch mail from mail providers, e.g. gmail or whatever you might have been using before. You could also set up forwarding online instead, that is ugly and not supported by every mail provider.

**Comment by tomav** [comment]
Hi @jcgruenhage, must it be built-in or can it be used as another docker image?

**Comment by jcgruenhage** [comment]
I thought it could not, but because you asked I looked again and voila, there was a premade container somewhere, although that probably will not work since it is optimised for exim.

**Comment by Josef-Friedrich** [comment]
I would welcome it, if  `fetchmail` would be built in. A time ago I tried  to run fetchmail in a separate container - without success. Isn’t `fetchmail` a UNIX mail tool like `postfix` or `dovecot`, which should live in one container among their companions.

**Comment by tomav** [comment]
I accept PR and docs 😄
