### ISSUE TITLE
mynetworks missmatch container ip

### ISSUE THREAD

**Issue by Zehir** [tomav/docker-mailserver#261]
Hello, I try to send a mail with auth from the docker host but I get the error: Relay access denied

So I look the main.cf file and I see:
`smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 172.17.0.0/16`
But the ip address of eth0 of container is 172.18.0.2 so is not in 172.17.0.0/16.

This is expected?

Thank

**Comment by tomav** [comment]
Mine is `172.17.0.1`. Perhaps this could be determined when container start.
A workaround is to use authentication, no?

**Comment by Zehir** [comment]
I try to use sasl #257 ..
My docker0 ip address on host is 172.17.0.1 too but I have a a interface named br-05dccab054bd with 172.18.0.1. 
And in the container logs I see this:
`mx postfix/smtpd[1445]: warning: unknown[172.18.0.1]: SASL PLAIN authentication failed:`

so is the ip address of bridge who is used.

I do not tweak any docker config except docker-compose.yml. And I do not change anything about networking. 
You have this bridge too?

**Comment by tomav** [comment]
We should add a `PERMIT_DOCKER_NETWORK` (false by default).
When set to `1`, the docker network should be whitelisted.

**Comment by tomav** [comment]
Wanna work on it?

**Comment by Zehir** [comment]
Why not, I looking for a way to get network address.
Do you have a other container on the same host to check if his network address is the same bridge/network?

You can use this commands:
```
docker network ls
docker network inspect [NAME]
```

**Comment by Zehir** [comment]
Using this command:
`docker exec mail cat /etc/postfix/main.cf`
I get: 
`mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 172.17.0.0/16`
And with
`docker exec mail postconf -d`
I get: 
`mynetworks = 127.0.0.0/8 172.18.0.0/16 [::1]/128 [fe80::]/64`
Any idea why?

**Comment by Zehir** [comment]
after some test I see that the default conf should allow the host but not the other container
So I my mind if you add the option PERMIT_DOCKER_NETWORK you should add 172.0.0.0/8. And by default keep the default value and not this value: 
`127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 172.17.0.0/16`
by default postfix allow all ip on same network of eth0.

This seems to be correct for you?

**Comment by Zehir** [comment]
maybe we can use by default:
`mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64`
to allow only localhost

then with option `PERMIT_DOCKER_HOST` add (in my case) `172.18.0.0/16` (so the default value of postfix)
and with option `PERMIT_DOCKER_OTHER_CONTAINER` add (in my case) `172.0.0.0/8`

**Comment by tomav** [comment]
I agree on the default.
I agree on `PERMIT_DOCKER_HOST` to add host automatically.
For the last one, I would name it `PERMIT_DOCKER_NETWORK`.

**Comment by Zehir** [comment]
we must use one option at a time so maybe you should name the options like this:
PERMIT_DOCKER=HOST
PERMIT_DOCKER=NETWORK

Because 172.18.0.0/16 is included in 172.0.0.0/8

**Comment by tomav** [comment]
True.

**Comment by Zehir** [comment]
By default it should also add the IP address of the container. Although it should use 127.0.0.1.
I'm working on now, I should make a PR in the day

**Comment by tomav** [comment]
`127.0.0.1` is already listed I think.
Thanks for the PR.

**Comment by Zehir** [comment]
Yes 127.0.0.1 is already included but I talking about 172.18.0.2/32

**Comment by Zehir** [comment]
I make the pull request but the travis build fail but it's not my fault

**Comment by tomav** [comment]
Merged.
