### ISSUE TITLE
custom ssl location

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#262]
Hi, I have installed the container in production for a test domain, it is working perfect, thanks for the amazing job.
I have used custom ssl certificate and I have noticed a documentation error:
In the wiki/Configure-SSL it says $(pwd)/postfix/ssl, but then, the start-mailserver.sh tries to get the "$(hostname)-full.pem from /tmp/docker-mailserver/ssl, that is mounted from ./config, so:

That ./postfix/ssl route is wrong in the documentation, **it should be ./config/ssl**

**Comment by tomav** [comment]
Hi @citec and thanks for your message. Can you update the Wiki as it should be?

**Comment by tomav** [comment]
It seems that you modified the Wiki.
Thanks!
