### ISSUE TITLE
Monitoring tools

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#266]
Hi, have you though about integrating some monitoring tool? It good be great to have some tool (cli or gui or both) to analyce pending email queue, log statistics, etc

**Comment by tomav** [comment]
IMHO, an ELK stack, external to the project is a good option, except that it's not lightweight.
I tried few other command line tools but they don't give relevant information.

**Comment by tomav** [comment]
https://elk-docker.readthedocs.io/

**Comment by citec** [comment]
Is there any elk stack that already analyse email logs?

**Comment by haraldkoch** [comment]
Part of an ELK solution is here: https://github.com/whyscream/postfix-grok-patterns

**Comment by citec** [comment]
thanks, I will try it

**Comment by tomav** [comment]
Anybody had time to have a look to ELK?

**Comment by tomav** [comment]
@citec, @haraldkoch?

**Comment by castorinop** [comment]
HI, i working on #331, is a simple forward logs to ELK stack. 

I hope it is useful.

**Comment by tomav** [comment]
ELK is available.
