### ISSUE TITLE
imapsync

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#267]
I have created a mini-container with imapsync on it and add to the project. I don't know if you guys find it useful. But we could add imapsync to the container so users could use it to migrate accounts.

**Comment by tomav** [comment]
Hi @citec, this should be kept apart from this image because it could be used with other image than docker-mailserver, no?

**Comment by citec** [comment]
Yes, maybe it is just a bad habit I have to put always an utils folder along with the project. I will keep it in my own branch then. Thanks

**Comment by tomav** [comment]
If your imap sync can be an image, you should publish and document it.
I'll be happy to have a link a third party tools to create an ecosystem.
