### ISSUE TITLE
docker-compose.yml issues

### ISSUE THREAD

**Issue by clobercow** [tomav/docker-mailserver#268]
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

The error above is what is generated when I paste the contents of the example you have on the wiki and try to run it. I only edited the domain name section. 

Can you assist?

**Comment by payneio** [comment]
Need to update docker-compose

**Comment by tomav** [comment]
@payneio is right, you're probably using a `docker-compose` version lower than 1.6.
Could you confirm?

**Comment by mc-molo** [comment]
I've had the same issue as @clobercow. Updating docker-compose (as described here https://docs.docker.com/compose/install/ ) fixed this issue. 
Container starting up without errors.

**Comment by tomav** [comment]
Great, thank you @mc-molo.
