### ISSUE TITLE
mail proxy

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#274]
Hi, now that we can have our email infrastructure on docker, we can move the containers easily. So now comes a question to my mind: in order to make **user-transparent server migrations** of our email services, we would need an **email proxy service**. Does any of you have any experience building an imap/smtp proxy?

**Comment by egorsmkv** [comment]
Nginx support mail proxy. For example, show this project: https://github.com/jwilder/nginx-proxy

**Comment by citec** [comment]
Yes, I am using that image in some projects here already, but for web proxies, I never implemented a mail proxy, I guess it is complicated because of the certificales, auth, etc. I found this: https://www.nginx.com/resources/admin-guide/mail-proxy/
I will try it on the weekend

**Comment by egorsmkv** [comment]
Sorry, I gave wrong link.

Explore this project https://github.com/hasufell/nginx-mail-proxy, show **Dockerfile**.
