### ISSUE TITLE
Mention the requirement on docker-compose version in the REAMDE

### ISSUE THREAD

**Issue by cies** [tomav/docker-mailserver#276]
When I come to the installation step:

    docker-compose up -d mail

Then I get:

    ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

A bit of intuition and looking around and I found that I should install `docker-compose` by `curl` and not by `apt-get`ing the package from the official Docker repo.

A small note in the README might help others.

**Comment by tomav** [comment]
Hi @cies, another has been reported with exact same problem: https://github.com/tomav/docker-mailserver/issues/268
