### ISSUE TITLE
[BUG]  Recipient address verification failure

### ISSUE THREAD

**Issue by C0D3-M4513R** [tomav/docker-mailserver#2771]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Recipient address verification fails

### What happened and when does this occur?

When recieving emails, I get a email rejection, when trying to send to a registered email on my server.

`setup email list` delivers this output. (the first email is not reachable, since no mx record is defined for c0d3m4513r.com)
```
* dmarc@c0d3m4513r.com ( 0 / ~ ) [0%]

* c0d3m4513r@mail.c0d3m4513r.com ( 1.0K / ~ ) [0%]
```

### What did you expect to happen?

```Markdown
I expected to be able to recieve emails, without further configuration.
```

### How do we replicate the issue?

Download the files for release `v.11.1.0`:
```bash
DMS_GITHUB_URL='https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/v11.1.0'
wget "${DMS_GITHUB_URL}/docker-compose.yml"
wget "${DMS_GITHUB_URL}/mailserver.env"
wget "${DMS_GITHUB_URL}/setup.sh"
chmod a+x ./setup.sh
```
Add a letsencrypt mount `/etc/letsencrypt:/etc/letsencrypt:ro`. 
I configured my `OVERRIDE_HOSTNAME=mail.c0d3m4513r.com`
Set the Timezone
Enable Spoof Protection
Add a reachable email account.
Send a email to that email

### DMS version

v.11.1.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
version: "3"
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: c0d3m4513r.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```
Sep 12 21:54:20 mail postfix/postscreen[1510]: CONNECT from [212.227.15.15]:32983 to [172.25.0.2]:25
Sep 12 21:54:26 mail postfix/postscreen[1510]: PASS NEW [212.227.15.15]:32983
Sep 12 21:54:26 mail postfix/smtpd[1527]: connect from mout.gmx.net[212.227.15.15]
Sep 12 21:54:26 mail postfix/smtpd[1527]: Anonymous TLS connection established from mout.gmx.net[212.227.15.15]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-256) server-signature RSA-PSS (2048 bits) server-digest SHA256
Sep 12 21:54:26 mail postfix/trivial-rewrite[1344]: warning: do not list domain mail.c0d3m4513r.com in BOTH mydestination and virtual_mailbox_domains
Sep 12 21:54:26 mail policyd-spf[1531]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=212.227.15.15; helo=mout.gmx.net; envelope-from=insert-my-email-here@gmx.de; receiver=<UNKNOWN>
Sep 12 21:54:26 mail postfix/smtpd[1527]: NOQUEUE: reject: RCPT from mout.gmx.net[212.227.15.15]: 550 5.1.1 <c0d3m4513r@mail.c0d3m4513r.com>: Recipient address rejected: User unknown in local recipient table; from=<insert-my-email-here@gmx.de> to=<c0d3m4513r@mail.c0d3m4513r.com> proto=ESMTP helo=<mout.gmx.net>
Sep 12 21:54:26 mail postfix/smtpd[1527]: disconnect from mout.gmx.net[212.227.15.15] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=5/7
Sep 12 21:55:04 mail dovecot: imap-login: Login: user=<c0d3m4513r@mail.c0d3m4513r.com>, method=PLAIN, rip=134.147.29.208, lip=172.25.0.2, mpid=1648, TLS, session=<VnmURYDokuuGkx3Q>
Sep 12 21:57:46 mail postfix/anvil[1343]: statistics: max connection rate 2/60s for (smtps:134.147.29.208) at Sep 12 21:54:06
Sep 12 21:57:46 mail postfix/anvil[1343]: statistics: max connection count 1 for (smtps:134.147.29.208) at Sep 12 21:53:32
Sep 12 21:57:46 mail postfix/anvil[1343]: statistics: max cache size 2 at Sep 12 21:54:26
Sep 12 21:58:33 mail postfix/smtpd-amavis/smtpd[1352]: timeout after END-OF-MESSAGE from localhost[127.0.0.1]
Sep 12 21:58:33 mail postfix/smtpd-amavis/smtpd[1352]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 commands=4
Sep 12 21:58:40 mail dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=192.241.213.80, lip=172.25.0.2, TLS handshaking: SSL_accept() failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number, session=<3dl4UoDoEo/A8dVQ>
Sep 12 21:59:07 mail postfix/smtpd-amavis/smtpd[1466]: timeout after END-OF-MESSAGE from localhost[127.0.0.1]
Sep 12 21:59:07 mail postfix/smtpd-amavis/smtpd[1466]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 commands=4
```

### Other relevant information

```Markdown
I first struggled with the docker-compose file, because docker-compose refused to start my container.
After a little searching I found the `version: "3"` option. Can that (or `version: "2"`, if that works out of box) please be included by default?
```

### What level of experience do you have with Docker and mail servers?

- [X] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

Please don't wrap the response boxes in markdown code tags, but then ask the users to use code tags. Block code tags cause MASSIVE issues (because nested block code tags are not a thing). Github apparently tries to somehow fix the nested code-blocks, by removing the starting "\`\`\`" (which of course destroys the formatting of the rest of the issue template).
You can check the edit-history of this post for this.

**Comment by georglauterbach** [comment]
So your email address is `c0d3m4513r@mail.c0d3m4513r.com` but then you use `OVERRIDE_HOSTNAME=mail.c0d3m4513r.com`. To me, it seems as if you want your email address to be `c0d3m4513r@c0d3m4513r.com` and have an MX DNS entry with

``` CONSOLE
$ dig +short MX c0d3m4513r.com
10 mail.c0d3m4513r.com
```

because it seems you did not even setup an MX record. As you're using compose, you do not actually need `OVERRIDE_HOSTNAME`. This was originally intended for other container environments like Kubernetes.

**Comment by georglauterbach** [comment]
I think you got something wrong there, and you misunderstood the docs I think :) Let me explain:

You want the mail server (on most cases, and probably in yours too) to be reachable via `mail.c0d3m4513r.com` if your domain is `c0d3m4513r.com`. You will need a DNS entry that resolves the name `mail.c0d3m4513r.com` to an IP address (i.e. you need an A record). To tell others that your mail server has the name `mail.c0d3m4513r.com`, you need to set an MX record for `c0d3m4513r.com` with the content `mail.c0d3m4513r.com`, i.e. the output should look like this:

``` CONSOLE
xxx@xyz:~$ dig +short mx c0d3m4513r.com
0 mail.c0d3m4513r.com.
xxx@xyz:~$ dig +short mx mail.c0d3m4513r.com
```

Then just use `<USER>@c0d3m4513r.com` as the mail addresses in your mail server. Remove `OVERRIDE_HOSTNAME`, you don't need it.
