### ISSUE TITLE
Error when starting mail server.

### ISSUE THREAD

**Issue by aks2687** [tomav/docker-mailserver#281]
Hi 
Unable to send/receive the mails from one account to another account. I am able to create new accounts and authenticate them against the mail server. 

Following is the message seen in the logs : 
mail    | Aug 24 14:07:29 test postfix/qmgr[1313]: 4311BB2C: from=<abc@aaa.com>, size=521, nrcpt=1 (queue active)
mail    | Aug 24 14:07:29 test postfix/smtpd[1330]: disconnect from unknown[172.18.0.1]
mail    | Aug 24 14:07:29 test postfix/smtp[1336]: connect to 127.0.0.1[127.0.0.1]:10024: Connection refused
mail    | Aug 24 14:07:29 test postfix/smtp[1336]: 4311BB2C: to=<xyz@aaa.com>, relay=none, delay=20, delays=20/0/0/0, dsn=4.4.1, status=deferred (connect to 127.0.0.1[127.0.0.1]:10024: Connection refused)

Also when starting the server, I see the following error : 
starting amavisd: Error in config file "/etc/amavis/conf.d/05-domain_id": Insecure directory in $ENV{PATH} while running with -T switch at /etc/amavis/conf.d/05-domain_id line 7.
mail    | (failed).

I feel there is some configuration missing. I am new to docker, any help would be appreciated.
I am using docker-compose to run the mail server.

**Comment by tomav** [comment]
Hi @aks2687, perhaps it's related to https://github.com/tomav/docker-mailserver/pull/270

**Comment by aks2687** [comment]
I tried setting the DOCKER_PERMIT. 
If I am correct after setting the above option, I should see the following logs based on the DOCKER_PERMIT setting, when starting the mail server : 
For host: echo "Adding $container_network/16 to my networks"
For network: echo "Adding docker network in my networks"

But I do not see any of the above logs. I did a pull for the latest docker image & using the following docker-compose file : 
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:v2
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "110:110"
    - "995:995"
    volumes:
    - ./maildata:/var/mail
    - ./config/:/tmp/docker-mailserver/
    environment:
    - PERMIT_DOCKER=network
    - ENABLE_POP3=1

volumes:
  maildata:
    driver: local

Apart from the above setting in the docker-compose file, do I need to set anything else also ?

**Comment by MhdSyrwan** [comment]
I had the same problem, i found that `amavisd` was not running for unknown reason. i stopped/removed the `mail` container and then started it again, it worked then.

**Comment by tomav** [comment]
@aks2687 you still have the problem? All services are running?
Let is know.
Thank you.

**Comment by tomav** [comment]
@aks2687 reopen when you other information to provide. We'll be happy to help.

**Comment by viossat** [comment]
I had the same problem, it was impossible to send/receive emails:
```
postfix/error[14343]: 535AAAF6: to=<user@domain.tld>, relay=none, delay=10, delays=10/0.05/0/0.01, dsn=4.4.1, status=deferred (delivery temporarily suspended: connect to 127.0.0.1[127.0.0.1]:10024: Connection refused)
```
Switching to `supervisord` could be an option for better stability.

**Comment by tomav** [comment]
@viossat the problem with amavis not running?
If yes, I do agree, `supervisord` may be an interesting option.
Feel free to submit a PR with tests. I'll be happy to merge it.
