### ISSUE TITLE
Is their any Graphical User Interface thus I can manage this mail server

### ISSUE THREAD

**Issue by saydulk** [tomav/docker-mailserver#283]
Hello, i am new using this server. Is their any Graphical User Interface thus I can manage this mail server??

**Comment by egorsmkv** [comment]
Use only terminal!

**Comment by tomav** [comment]
Using an GUI won't let you understand how a mail server works.

**Comment by neonecosystem** [comment]
Hello, without GUI how any new person can use this mail server. After all we are not familiar with terminal! where is the details things to do after setup this docker-mail server? (waiting). My friend has setup & Docker is running with mail server with roundcube. But how i iwll use this to send email & otherss managements?

**Comment by tomav** [comment]
Being not familiar with a terminal and using docker sounds strange, no?

What do you want to do exactly?

**Comment by tomav** [comment]
What do you want to do exactly?

**Comment by psi-4ward** [comment]
Hey getting this up. I'm also interested in a GUI, not for the administration but more for the *resller*:
* managing accounts
* manage a simple account: autoresponder ...

@tomav Pls take a look into your "other" Folder in Facebook :)

**Comment by Casy** [comment]
Agree with @psi-4ward
