### ISSUE TITLE
Autoresponder

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#284]
It would be great to have the ability of setting up Autoresponders for some email accounts.
Here is a guide on how to set it up in for postfix: https://www.howtoforge.com/how-to-set-up-a-postfix-autoresponder-with-autoresponse
What do you think?

**Comment by Josef-Friedrich** [comment]
I would appreciate a autoresponder in `docker-mailserver`. However - the script in the tutorial is not downloadable. [Unfortunately the project `autoresponder` is deprecated](http://nefaria.com/2009/12/autoresponse-is-deprecated)

**Comment by fred727-temp** [comment]
I haven't seen anywhere a tutorial to quickly install an autosponder... In the #1564 you speek about Sieve but it seem to be difficult to configure.

Can we have a few lines in documentation to quickly make a "norely" account ?
