### ISSUE TITLE
Plaintext authentication disabled

### ISSUE THREAD

**Issue by umbrellary** [tomav/docker-mailserver#302]
Hi:

I can send the email, but i can't receive!

Log:

mailserver | Sep 2 09:24:06 mail dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=117.81.23.114, lip=192.168.16.2, session=<VtZa5II7RAB1URdy>
mailserver | Sep 2 09:24:06 mail dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=117.81.23.114, lip=192.168.16.2, session=<5cdb5II7RQB1URdy>
mailserver | Sep 2 09:24:06 mail dovecot: imap-login: Login failed: Plaintext authentication disabled: user=<>, rip=117.81.23.114, lip=192.168.16.2, session=<viRd5II7RgB1URdy>

**Comment by Josef-Friedrich** [comment]
Is your mail client configured correctly? `Dovecot` gets no user `user=<>`. A successful login should look like this log example:

```
Sep  2 17:42:13 mail dovecot: imap-login: Login: user=<jf@josef-friedrich.de>, method=PLAIN, rip=2.242.51.14, lip=172.20.0.2, mpid=13989, TLS, session=</k7D2Yk7hAAC8jMO>
```

To enable plaintext authentication (no recommended) generate a configuration file named `dovecot.cf` in `config/dovecot.cf` (not tested)

```
disable_plaintext_auth=no
```

and then 

```
docker-compose restart
```

**Comment by umbrellary** [comment]
@Josef-Friedrich I tested this morning, but the original error happened.

This is my email client:
![image](https://cloud.githubusercontent.com/assets/6939585/18221925/2dded4f6-71ba-11e6-9e05-79b037ba3fff.png)


This is my log:

root@splendidtel:/docker# docker-compose up mailserver
Creating mailserver
Attaching to mailserver
mailserver    | Checking file line endings
mailserver    | Regenerating postfix 'vmailbox' and 'virtual' for given users
mailserver    | user 'harry.zhang' for domain 'mail.umbrellary.com' with password '********'
mailserver    | ==> Warning: 'config/postfix-virtual.cf' is not provided. No mail alias/forward created.
mailserver    | No DKIM key provided. Check the documentation to find how to get your keys.
mailserver    | Postfix configurations
mailserver    | Adding docker network in my networks
mailserver    | bash: /etc/opendkim/TrustedHosts: No such file or directory
mailserver    | No extra postfix settings loaded because optional '/tmp/docker-mailserver/postfix-main.cf' not provided.
mailserver    | ==> Warning: 'SASL_PASSWD' is not provided. /etc/postfix/sasl_passwd not created.
mailserver    | Permissions in /var/mail look OK
mailserver    | Creating /etc/mailname
mailserver    | Configuring Spamassassin
mailserver    | Starting daemons
mailserver    |  * Starting enhanced syslogd rsyslogd
mailserver    |    ...done.
mailserver    |  * Starting dovecot services
mailserver    | Starting POP3 services
mailserver    | Starting SpamAssassin Mail Filter Daemon: spamd.
mailserver    |  * Starting ClamAV daemon clamd
mailserver    |    ...fail!
mailserver    | Starting amavisd: amavisd-new.
mailserver    | Starting OpenDKIM: opendkim: /etc/opendkim.conf: refile:/etc/opendkim/TrustedHosts: dkimf_db_open(): No such file or directory
mailserver    | opendkim.
mailserver    | Starting OpenDMARC: opendmarc.
mailserver    |  * Starting Postfix Mail Transport Agent postfix
mailserver    |    ...done.
mailserver    | Listing users
mailserver    | harry.zhang@mail.umbrellary.com
mailserver    | Starting...
mailserver    | Sep  3 01:34:42 mail amavis[470]: No decoder for       .tnef
mailserver    | Sep  3 01:34:42 mail amavis[470]: Internal decoder for .tnef
mailserver    | Sep  3 01:34:42 mail amavis[470]: Found decoder for    .exe  at /usr/bin/arj
mailserver    | Sep  3 01:34:42 mail amavis[470]: Using primary internal av scanner code for ClamAV-clamd
mailserver    | Sep  3 01:34:42 mail amavis[470]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
mailserver    | Sep  3 01:34:42 mail amavis[470]: Deleting db files  in /var/lib/amavis/db
mailserver    | Sep  3 01:34:42 mail amavis[470]: Creating db in /var/lib/amavis/db/; BerkeleyDB 0.54, libdb 5.3
mailserver    | Sep  3 01:34:42 mail opendmarc[481]: OpenDMARC Filter v1.2.0 starting (args: -c /etc/opendmarc.conf -u opendmarc -P /var/run/opendmarc/opendmarc.pid -p inet:54321@localhost)
mailserver    | Sep  3 01:34:42 mail opendmarc[481]: trusted authentication services: mail.umbrellary.com
mailserver    | Sep  3 01:34:45 mail postfix/master[1289]: daemon started -- version 2.11.0, configuration /etc/postfix
mailserver    | Sep  3 01:35:03 mail dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=117.81.156.13, lip=192.168.16.2, session=<2VO9dJA7lwB1UZwN>
mailserver    | Sep  3 01:35:03 mail dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=117.81.156.13, lip=192.168.16.2, session=<jA2+dJA7mAB1UZwN>
mailserver    | Sep  3 01:35:03 mail dovecot: imap-login: Login failed: Plaintext authentication disabled: user=<>, rip=117.81.156.13, lip=192.168.16.2, session=<3D2/dJA7mQB1UZwN>

**Comment by umbrellary** [comment]
I have solved the problem!
just turn off the ssl!

**Comment by GiganteX** [comment]
Adding the dovecot.cf config didn't do anything for me, still getting this:
imap-login: Login failed: Plaintext authentication disabled: user=<>, rip=10.255.0.167, lip=10.255.0.99, session=<YmzHnlJyTIEK/wCn>
And I'm not using SSL in my mailclient

**Comment by codejamninja** [comment]
@GiganteX I'm experiencing the same issue.
