### ISSUE TITLE
config/dovecot.cf doesn't get loaded

### ISSUE THREAD

**Issue by ckiszka** [tomav/docker-mailserver#307]
I have override configs for both dovecot and postfix. In the startup script, I see the postfix override config loaded, however, I do not see the dovecot override config loaded. This is solidified with missing configurations after boot.

**Comment by Josef-Friedrich** [comment]
That’s not good at all! Are you really sure that `dovecot.cf` is not loaded? For this features there are [tests](https://github.com/tomav/docker-mailserver/blob/master/test/tests.bats#L256-L262) that have not failed on the last built.

To debug your dovecot configuration you can use this command:

```sh
./setup.sh debug login doveconf | grep <some-keyword>
```

[setup.sh](https://github.com/tomav/docker-mailserver/blob/master/setup.sh) is included in the `docker-mailserver` repository.

or

```sh
docker exec -ti <your-container-name> doveconf | grep <some-keyword>
```

The  `config/dovecot.cf` is copied to `/etc/dovecot/local.conf`. To check this file run:

```sh
docker exec -ti <your-container-name> cat /etc/dovecot/local.conf
```

**Comment by ckiszka** [comment]
I'm never really sure when it comes to these things, however, I'll try not to waste your time the best I can ;). 

I looked at the log line by line and did not see the dovecot.cf loaded like I saw with the postfix. I'll run these debug steps and get back to you soon.

**Comment by ckiszka** [comment]
Sorry for the delay. I did confirm the dovecot override settings are in place with the grep filter. My problem was Dovecot was failing before it could even be applied due to no IPV6 support. I have to map host / container dovecot and postfix etc folders and edit the config files to only support IPV4. If I try to add this to the top of the override file it does not take effect and I get fatal errors. 

This is an awesome image! Thank you for providing it. Wishlist item = IPV6 Disable / Enable variable. Thanks guys!
