### ISSUE TITLE
Error while generating SSL keys/cert

### ISSUE THREAD

**Issue by jokesterfr** [tomav/docker-mailserver#31]
Hi,
I've been using your explanations to generate the certificates, with the docker container and the `generate-ssl-certificate` command. At the very end of the procedure I get:

```
Certificate is to be certified until Oct 21 13:34:19 2016 GMT (365 days)
Sign the certificate? [y/n]:y
failed to update database
TXT_DB error number 2
```

Most of my files has been generated, but the `cert.pem` file is empty:

```
drwxr-xr-x 6 root root 4096 oct.  22 15:33 demoCA/
-rw-r--r-- 1 root root    0 oct.  22 15:34 mail.mydomain.fr-cert.pem
-rw-r--r-- 1 root root 1708 oct.  22 15:34 mail.mydomain.fr-combined.pem
-rw-r--r-- 1 root root 1708 oct.  22 15:34 mail.mydomain.fr-key.pem
-rw-r--r-- 1 root root 1066 oct.  22 15:34 mail.mydomain.fr-req.pem
```

Do you have any idea where this comes from? What `openssl` command is perfomed by `generate-ssl-certificate
`? Thanks!

Jk.

**Comment by jokesterfr** [comment]
I found in the sources the openssl command:

```bash
FQDN=mail.mydomain.fr
openssl ca -out /ssl/$FQDN-cert.pem -infiles /ssl/$FQDN-req.pem
```
But it's still showing up the same error in or out of the container...

**Comment by tomav** [comment]
Hi @jokesterfr, I reproduced your issue. I'll have a look.
Tell me if you find a lead.

**Comment by tomav** [comment]
Ok, found [answer](http://nicolasjolet.blogspot.fr/2011/01/as-i-m-completly-unaware-of-openssl-use.html) and tested.

    failed to update database
    TXT_DB error number 2
    This is probably because you have generated your own signing certificate with the same Common Name (CN) information that the CA certificate that you've generated before.

I'm gonna update the `README`.

**Comment by tomav** [comment]
Hope this helps.

**Comment by jokesterfr** [comment]
Thanks a lot for the quick response!

I've just done it by-hand using [this tutorial](https://www.e-rave.nl/create-a-self-signed-ssl-key-for-postfix) it also works. 

Thanks a lot for this docker project, you saved me 2 days of email server configuration...

**Comment by tomav** [comment]
You're welcome.
