### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NathanTheGr8** [tomav/docker-mailserver#315]
I followed the read me till I got to

> Now the keys are generated, you can configure your DNS server by just pasting the content of config/opendkim/keys/domain.tld/mail.txt in your domain.tld.hosts zone.

I have the file at the specified path, but I don't understand where to put it? Is the guide assuming I am running my own DNS server? My domain is on Google Domains, and there is a section labeled `Custom Resource Records` that looks like [this.](http://i.imgur.com/xO3At1V.png) Do I need to need to make a entry there?

What I am trying to accomplish is run my own smtp sever to use with a wordpress container. The server it will run on is ubuntu 14.04 with docker 1.12.1, but I am testing it on MacOS 10.11.6 docker 1.12.1

mail.txt file generated

> mail._domainkey	IN	TXT	( "v=DKIM1; k=rsa; "
	  "p=MIGfMA0GCSqGSIb3DQEBAQUA54GNADCBiQKBgQDf84WE41u8WBF8C0tVr457TVtdc+ALPcCl7ux2mieVMqI9f6/06XvXKJ9Yb7V1VMQuC43h1zurj5T/opYzUFYO9HoD2yVevV+EMpNVXo8bLFBJQVT7U819tn/hSbiCcHUzzmBqJ3z3/g3PnRgnDlJfgPFG8lPEaDnae49SaOcZuwIDAQAB" )  ; ----- DKIM key mail for example.com

**Comment by Josef-Friedrich** [comment]
You need no own DNS server. Only what you need is a `TXT` record. I found a screenshot which illustrates that:

![Screenshot](https://657cea1304d5d92ee105-33ee89321dddef28209b83f19f06774f.ssl.cf1.rackcdn.com/Add%2520DKIM%2520DNS%2520TXT%2520Record-ffa5cdd00697dba206c568bb70c19923401e3248d9c5ddd39819998269759618.png)

Instead of `default._domainkey` write `mail._domainkey`

**Comment by NathanTheGr8** [comment]
should I have separate lines for v, k , and p? 
https://www.dropbox.com/s/zj4ha65kr1rmzss/Screenshot%202016-09-07%2009.11.54.png?dl=0

**Comment by Josef-Friedrich** [comment]
Only one line, the key-value-pairs are separated by semicolons. You can debug your TXT record with the `dig` tool.

```
dig TXT mail._domainkey.josef-friedrich.de
```
Output:

```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> TXT mail._domainkey.josef-friedrich.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39669
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;mail._domainkey.josef-friedrich.de. IN	TXT

;; ANSWER SECTION:
mail._domainkey.josef-friedrich.de. 3600 IN TXT	"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCxBSjG6RnWAdU3oOlqbUUgJKf2WC0FOUmU8uHVrzxPLW2R3yRBPGLrGO1++yy3tv6kMieWZwEBHVOdefM6uQOQsZ4brahu9lhG8sFLPX4MaKYN/NR6RK4gdjrZu+MYSdfk3THivOPvjSZiffzBVtuom9uXRy6adxf6Z78bZgSbNwIDAQAB"

;; Query time: 50 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Wed Sep 07 18:22:57 CEST 2016
;; MSG SIZE  rcvd: 310
```

**Comment by NathanTheGr8** [comment]
Awesome dig  ouputs,

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> TXT mail._domainkey.janemariedavis.com
	;; global options: +cmd
	;; Got answer:
	;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9742
	;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

	;; OPT PSEUDOSECTION:
	; EDNS: version: 0, flags:; udp: 512
	;; QUESTION SECTION:
	;mail._domainkey.janemariedavis.com. IN	TXT

	;; ANSWER SECTION:
	mail._domainkey.janemariedavis.com. 300	IN TXT	"v=DKIM"
	mail._domainkey.janemariedavis.com. 300	IN TXT	"p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDf84WE41u8WBF8C0tVr457TVtdc+ALPcCl7ux2mieVMqI9f6/06XvXKJ9Yb7V1VMQuC43h1zurj5T/opYzUFYO9HoD2yVevV+EMpNVXo8bLFBJQVT7U819tn/hSbiCcHUzzmBqJ3z3/g3PnRgnDlJfgPFG8lPEaDnae49SaOcZuwIDAQAB"
	mail._domainkey.janemariedavis.com. 300	IN TXT	"k=rsa"

	;; Query time: 30 msec
	;; SERVER: 192.168.1.1#53(192.168.1.1)
	;; WHEN: Wed Sep 07 11:53:26 CDT 2016
	;; MSG SIZE  rcvd: 331

mine are on separate lines so I will change that on my domain. I am sorry that I am using this as a support thread but final question. How might I send a test email to or from my server?

**Comment by Josef-Friedrich** [comment]
There’s a cool Thunderbird addon named [DKIM-verifer](https://addons.mozilla.org/en-US/thunderbird/addon/dkim-verifier)

**Comment by azizabdul** [comment]
I have generated mail.txt file and its content is  mail._domainkey	IN	TXT	( "v=DKIM1; k=rsa; "
	  "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCjeymHZ8Z2J23uiXDQuUeyL5YytPbj5sYDpED9go7x6WBTe+Oj4XahK540dMH0/Hh/kE6sEvEEwOPfq+caO0FsQt95li1zKIq3t9tAQj1hziFxwP0gmaTAzaqLDMKplP/EKleHZ3gKdK5hpWORE2aK/T3kNWUZgCT6a/E0LxQBcQIDAQAB" )  ; ----- DKIM key mail for ban.apac.bosch.com

I want to send mail but failed to do so.I am confused where to put this file in my localhost as I am trying to send mail from localhost in ubuntu.SMTP port is running in my local system.

**Comment by tomav** [comment]
This should go in your [DNS zone](https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM).

**Comment by viveksuhanda** [comment]
@Josef-Friedrich According to your comment on Sep 7 2016 which illustrates how to add the text record but where do we add that text record I am using AWS cloud ubuntu VM and configuring mail server in that VM. Also, I have assigned elastic IP to that VM which I have registered with a domain in route 53 and created a MX, A and PTR record for that in route 53. 
@tomav Also, I am unable to locate the DNS zone file for my registered domain can you tell where do we get that.

**Comment by johansmitsnl** [comment]
What @tomav means is that you need to add a TXT record.
