### ISSUE TITLE
Outgoing mail using external smtp service with authentication

### ISSUE THREAD

**Issue by joshuisken** [tomav/docker-mailserver#318]
Hi,

Similar to using AWS_SES_HOST / AWS_SES_PORT / AWS_SES_USERPASS I would like to use another smtp server for outgoing mail.
Is that possible?  (Somehow I cannot get mail out...)

Regards

**Comment by tomav** [comment]
Hi @joshuisken, this is a more a general Postfix question than something specific to this image.
I clearly don't think that we can manage all usage and configuration types using our `ENV` variables on top of postfix.

SASL can do the trick. Check postfix configuration.

We have a lot of work on the table, do not hesitate if you want to contribute.
