### ISSUE TITLE
[Q] best practice for white/black listing

### ISSUE THREAD

**Issue by CrystalMethod** [tomav/docker-mailserver#319]
Sometimes it happens that Github/Twitter notification will be marked as spam. So, whats the best practice for white/black listing? 

**Amavis**
in ``/etc/amavis/conf.d/50-user`` add something like the following

```@whitelist_sender_maps = (['github.com']);```

Since 02f854f4e9daeeac8581bf90a41e5debc8473386 it is possible to customize Amavis configuration.

**SpamAssassin**
in ``/etc/spamassassin/local.cf`` add something like the following

```whitelist_from_rcvd *@github.com github.net```

Customization of ``local.cf``is not yet officially supported but could easily be added.

**Sieve**
One could write a Sieve script to keep / reject messages.

**Comment by tomav** [comment]
Hi @CrystalMethod, I would use Amavis. Spamassassin is triggered by Amavis so it should be the best option IMHO.
