### ISSUE TITLE
How can I view text of e-mails to me? (Question)

### ISSUE THREAD

**Issue by Alex-Tsvetanov** [tomav/docker-mailserver#327]
How can I view text of e-mails to me?

**Comment by tomav** [comment]
I don't understand. Could you be more explicit? Thank you.

**Comment by Alex-Tsvetanov** [comment]
I send e-mail from ostrietoxxx@gmail.com to alex@tsalex.tk. How can I view content of message from alex@tsalex.tk?

**Comment by tomav** [comment]
If the question is "how can I use a mail client to read and send emails", the answers is in the [Wiki](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-configure-my-email-client).

Otherwise, I still not understand clearly what you're trying to do :-)
