### ISSUE TITLE
ERRO[0019] Handler for GET /v1.22/networks/docker_default returned error: network docker_default not found

### ISSUE THREAD

**Issue by Alex-Tsvetanov** [tomav/docker-mailserver#328]
How to fix it?

**Comment by tomav** [comment]
Hi @Alex-Tsvetanov, how can we reproduce that?

**Comment by Alex-Tsvetanov** [comment]
That is from ``sudo dockerd`` logs.

**Comment by tomav** [comment]
Is this related to `docker-mailserver` or to `docker`it self?
What do you do to have this errors?
How can we reproduce that?

Again, if you need contributors to help you, you have to be more explicit.
