### ISSUE TITLE
Server is logging to both /var/log/mail/mail.* AND /var/log/syslog

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#329]
Am I right?
Perhaps we should only keep `/var/log/mail.*` to avoid log duplication / optimize disk space.

Any thoughts?

**Comment by Josef-Friedrich** [comment]
You are right. The same issue in my container.

In `/etc/rsyslog.d/50-default.conf` `*.*;auth,authpriv.none		-/var/log/syslog` should be replaced with  `*.*;mail,auth,authpriv.none     -/var/log/syslog` (untested)
