### ISSUE TITLE
SMTP SSL (port 465) and AUTH Required (port 587) support

### ISSUE THREAD

**Issue by mastepanoski** [tomav/docker-mailserver#332]
Hi, I have tested my email server against http://emailsecuritygrader.com, and it has gotten a score of 88! great for you. However, the test report returned this:

"A secure mail server will force local users to authenticate prior to sending mail, and will use either ports 465 or 587 for message encryption and submission. Therefore we will test the following:

```
Attempt to connect to ports 25, 465 and 587 to verify that all three ports are open
Test that authentication (i.e. an AUTH command) is additionally required on port 587
```

Your score will be determined by the following criteria:

All 3 ports are open (25, 465 and 587).
Your system requires authentication (AUTH) on port 587 before the MAIL FROM command is issued If connection to either port 25 or 465 fails, you will receive a failed score"

SMTP Plain Text Authentication Test: FAILED

Risk factors:

Spammers can potentially hack users' accounts by collecting passwords that are transmitted to the server in clear text via PLAIN or AUTH LOGIN mechanisms.

What are we testing?

This test attempts to connect to the mail server on ports 25 and 465. For each connection it checks the list of available authentication (AUTH) methods.

The server will receive the lowest score if PLAIN or AUTH LOGIN are supported on port 25. The highest score is awarded if SMTP SSL is enabled, and the PLAIN and AUTH LOGIN mechanisms are not available on port 25. Note that if AUTH is not supported, your MX passes the test as plain text passwords cannot be sniffed."

Ok, that's all. May be these points would help you to improve your great container.

Thank you.

**Comment by tronicum** [comment]
So your problem is that  587 would allow non STARTTLS connections?
Or what do you want beside copy&pasting stuff?

**Comment by tomav** [comment]
Regarding `PLAIN`and `AUTH`, I added theses mechs but this was a mistake.
I'm OK to remove them because the goal of this image is to include the best practices natively.

There's probably work to do on `SSL/STARTLS` too.

Who wants to work on that?

**Comment by jrehwaldt** [comment]
What's the desired result? I secured my image with STARTTLS-only, high grade ciphers, prefer server side ciphers and a few more tweaks. Obviously, such a setup would break existing setups which use unsecured access. Is that okay for you?

**Comment by tomav** [comment]
Following emailsecuritygrader.com explanation, `PLAIN` and `LOGIN` auth mechanisms should not be available on port `25` or `143`.

**Comment by tronicum** [comment]
Sometimes you might allow it on 127.0.01 connections

**Comment by tomav** [comment]
Yes, but it's an exception that may be whitelisted.  Otherwise, we have `PEMRIT_DOCKER` env.

**Comment by tomav** [comment]
Close due to inactivity, reopen if needed.

**Comment by weaktyper** [comment]
Adding `smtpd_tls_auth_only = yes` to `config/postfix-main.cf` might help here.
