### ISSUE TITLE
Restructure start-mailserver.sh

### ISSUE THREAD

**Issue by alinmear** [tomav/docker-mailserver#338]
From my point of view it would be a big benefit, to structure the script with functions, for better maintenance. 

With this improvement it would be possible to better control the bootstrap of the container:

I would appreciate this step and would spent my time working on this.

Best Regards

**Comment by tomav** [comment]
You're right, this file is a bit messy.
Can you work on that?

All, any thoughts?

**Comment by Josef-Friedrich** [comment]
Functions for start-mailserver.sh would be great!

**Comment by alinmear** [comment]
If you merge my pull request #335 then we would have the logic for container setup with postfix as central part as mta of a full featured mailserver:

Postfix <-> User database and User Validation <-> imap/pop server
Postfix <-> dovecot/postfix local <-> dovecot
Postfix <-> dovecot/postfix ldap (dovecot ldap needs to be implemented)<-> dovecot
Postfix <-> dovecot local/postfix ldap <-> dovecot
Postfix <-> dovecot ldap (needs to be implemented)/postfix local <-> dovecot

Postfix <-> ldap/activedirectory <-> kopano/zarafa

With this in mind, i would suggest the following structure:
do_setup_postfix ()  
do_setup_opendkim()
do_setup_opendmarc()
do_setup_ssl()
do_setup_permit_docker_options()
do_setup_saslauthd()
do_setup_spamassassin()
do_setup_amavis()
do_setup_fail2ban()
do_setup_dovecot () 
do_setup_kopano () 
do_setup_container() [e.g. persistent state)
do_init () 

At the end of the script:
control section --> validating ENV-VARS with possible setup, if not valid, then throw error on container startup e.g. user dovecot and kopano or cyrus sasl and dovecot sasl. After validating and settngs configuration state of the container do_init()

**Comment by alinmear** [comment]
@tomav i will start here, when we can be sure, whether the pull request of @dennis95stumm, and also my new rebased pull request for the kopano feature has been successfully merged or not. Because both will result in some alterations of the start-mailserver script.

**Comment by tomav** [comment]
Roger that!

**Comment by tomav** [comment]
@alinmear tests are missing in your other PR by the way.

**Comment by tomav** [comment]
We should have a pre function that checks configuration to stop the execution if a configuration is provided:
* if FQDN is not provided (already exists at the top of the script)
* display configuration (alias provided or not, regexp-alias provided or not, dkim provided or not...) before it starts the server

Let me know if I can help or if you want to talk about that.

**Comment by alinmear** [comment]
Sorry for my absence, but i was very busy. 
Today i start working on this. Your last post seems to be clear and a good idea. If i can think of something else i will post here again!

**Comment by tomav** [comment]
Thank you @alinmear!

**Comment by alinmear** [comment]
@tomav i just made a pull request for this. The next step would be implementing the checks logics you mentioned. I haven't done this in this scope, otherwise the batch size of changes would be that big, that if we mess something else up here it's hard to find where we did so.

I marked some sections with @TODO where we could start with several checks.

**Comment by alinmear** [comment]
@tomav: there is also one very important thing i recognized while working on this. We have to different kinds of environment variables: task based, e.g. should we make a config step like ENABLE/DISABLE_SOMETHING and section based, e.g. what should we do withing that task.

Dealing with this we should make a convention that task based vars should always have the same form and is a conditional for registering a function/task or not (so we don't need to make several unneeded function calls here).

@Josef-Friedrich maybe you could think about this with your suggestions in #297.
