### ISSUE TITLE
generate self-signed ssl certificate - fails.

### ISSUE THREAD

**Issue by fentas** [tomav/docker-mailserver#34]
Heyho,
I follow your instructions with `docker run -ti --rm -v "$(pwd)"/postfix/ssl:/ssl -h mail.my-domain.com -t tvial/docker-mailserver generate-ssl-certificate` but it fails in the end with

```sh
Using configuration from /usr/lib/ssl/openssl.cnf
unable to load CA private key
140046222562976:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: ANY PRIVATE KEY
cat: /ssl/unite.travel-cert.pem: No such file or directory
```

Apparently it fails here
```sh
openssl ca -out /ssl/$FQDN-cert.pem -infiles /ssl/$FQDN-req.pem
```

**Comment by tomav** [comment]
Hi @fentas, I can't reproduce your issue. I used your command line and successfully generated certificates. Here's the log:

    ➜  34  docker run -ti --rm -v "$(pwd)"/postfix/ssl:/ssl -h mail.my-domain.com -t tvial/docker-mailserver generate-ssl-certificate
    CA certificate filename (or enter to create)

    Making CA certificate ...
    Generating a 2048 bit RSA private key
    ......................+++
    .....................................................................................+++
    writing new private key to './demoCA/private/cakey.pem'
    Enter PEM pass phrase:
    Verifying - Enter PEM pass phrase:
    -----
    You are about to be asked to enter information that will be incorporated
    into your certificate request.
    What you are about to enter is what is called a Distinguished Name or a DN.
    There are quite a few fields but you can leave some blank
    For some fields there will be a default value,
    If you enter '.', the field will be left blank.
    -----
    Country Name (2 letter code) [AU]:FR
    State or Province Name (full name) [Some-State]:
    Locality Name (eg, city) []:
    Organization Name (eg, company) [Internet Widgits Pty Ltd]:domain
    Organizational Unit Name (eg, section) []:
    Common Name (e.g. server FQDN or YOUR name) []:domain.com
    Email Address []:

    Please enter the following 'extra' attributes
    to be sent with your certificate request
    A challenge password []:
    An optional company name []:
    Using configuration from /usr/lib/ssl/openssl.cnf
    Enter pass phrase for ./demoCA/private/cakey.pem:
    Check that the request matches the signature
    Signature ok
    Certificate Details:
            Serial Number: 14718433766925844886 (0xcc42618787bac196)
            Validity
                Not Before: Nov 13 09:25:02 2015 GMT
                Not After : Nov 12 09:25:02 2018 GMT
            Subject:
                countryName               = FR
                stateOrProvinceName       = Some-State
                organizationName          = domain
                commonName                = domain.com
            X509v3 extensions:
                X509v3 Subject Key Identifier:
                    7B:CD:A5:58:37:42:44:5C:E8:1A:F2:68:46:4C:83:98:20:A6:15:80
                X509v3 Authority Key Identifier:
                    keyid:7B:CD:A5:58:37:42:44:5C:E8:1A:F2:68:46:4C:83:98:20:A6:15:80

                X509v3 Basic Constraints:
                    CA:TRUE
    Certificate is to be certified until Nov 12 09:25:02 2018 GMT (1095 days)

    Write out database with 1 new entries
    Data Base Updated
    Generating a 2048 bit RSA private key
    .......+++
    ............................................................................................................................................+++
    writing new private key to '/ssl/mail.my-domain.com-key.pem'
    -----
    You are about to be asked to enter information that will be incorporated
    into your certificate request.
    What you are about to enter is what is called a Distinguished Name or a DN.
    There are quite a few fields but you can leave some blank
    For some fields there will be a default value,
    If you enter '.', the field will be left blank.
    -----
    Country Name (2 letter code) [AU]:FR
    State or Province Name (full name) [Some-State]:
    Locality Name (eg, city) []:
    Organization Name (eg, company) [Internet Widgits Pty Ltd]:domain
    Organizational Unit Name (eg, section) []:
    Common Name (e.g. server FQDN or YOUR name) []:mail.domain.com
    Email Address []:

    Please enter the following 'extra' attributes
    to be sent with your certificate request
    A challenge password []:
    An optional company name []:
    Using configuration from /usr/lib/ssl/openssl.cnf
    Enter pass phrase for ./demoCA/private/cakey.pem:
    Check that the request matches the signature
    Signature ok
    Certificate Details:
            Serial Number: 14718433766925844887 (0xcc42618787bac197)
            Validity
                Not Before: Nov 13 09:25:22 2015 GMT
                Not After : Nov 12 09:25:22 2016 GMT
            Subject:
                countryName               = FR
                stateOrProvinceName       = Some-State
                organizationName          = domain
                commonName                = mail.domain.com
            X509v3 extensions:
                X509v3 Basic Constraints:
                    CA:FALSE
                Netscape Comment:
                    OpenSSL Generated Certificate
                X509v3 Subject Key Identifier:
                    B0:AF:E8:AC:96:9F:1F:65:49:2B:71:4F:8E:BD:D8:DE:89:00:7C:D9
                X509v3 Authority Key Identifier:
                    keyid:7B:CD:A5:58:37:42:44:5C:E8:1A:F2:68:46:4C:83:98:20:A6:15:80

    Certificate is to be certified until Nov 12 09:25:22 2016 GMT (365 days)
    Sign the certificate? [y/n]:y


    1 out of 1 certificate requests certified, commit? [y/n]y
    Write out database with 1 new entries
    Data Base Updated

The first time your asked for a FQDN, enter `domain.com` and the second time, the FQDN of the mail server, usually `mail.domain.com`. Do not enter the same FQDN.

Let me know if I can help.

**Comment by fentas** [comment]
Hm I guess it did not work because I didn't enter a pass phrase in the beginning.
With pass phrase it works perfectly. Thanks a lot!
