### ISSUE TITLE
Message too large for server

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#345]
Hi, i got the "Message too large for server" error when trying to send an email. How do I increase that limit?

**Comment by tomav** [comment]
Any log on the server?

**Comment by citec** [comment]
I only get this when trying to send the email:

```Oct  7 16:03:16 mail3 postfix/submission/smtpd[21588]: warning: connect to Milter service inet:localhost:54321: Connection refused```

Then I get that "Message too large for server" error message in my email client (K-@ Mail on Android)

**Comment by citec** [comment]
I restarted and the Milter error dissapeared, but still getting that size limit message on the email client

**Comment by citec** [comment]
Solved, I increased limit by adding

```message_size_limit = 102400000```

to config/postfix-main.cf

as default was 10MB:

```message_size_limit = 10240000```

**Comment by tomav** [comment]
Great!
