### ISSUE TITLE
Feature: Add (daily/weekly/...) summary of mailserver by parsing logs

### ISSUE THREAD

**Issue by chrisella** [tomav/docker-mailserver#349]
More of a feature really,
It would be nice if there was a summary (daily, weekly etc) of the server.
What I mean is including something like Pflogsumm and running it at a schedule defined in a config.

Currently I'm exec'ing into the container and manually running it to get summary information about my mail server, but if this could be included, and even send its output to a defined email address, that would be mighty handy.

**Comment by tomav** [comment]
Hi @chrisella, we also released a bridge to ELK which could give long term stats and allow to debug a lot of things.
The implementation is partial but works, this could be a better option, no?

**Comment by tomav** [comment]
https://github.com/tomav/docker-mailserver/pull/331
