### ISSUE TITLE
how to import user's imap files/directories 

### ISSUE THREAD

**Issue by patgg** [tomav/docker-mailserver#358]
hello,

i test this wonderful container. But i don't know how to import correctly an imap directory from users ?
i did a scp and all directories from users are copyied. Or is it the manifest on docker-config.yml which is bad ?  indeed when i test the IMAP or POP accounts i can't download messages. i can create new messages but my old messages aren't visible.

my .yml is ;

`version: '2'

services:
  mail:
    environment:
      - ENABLE_POP3=1
      - ENABLE_FAIL2BAN=1
    image: tomav/docker-mailserver:latest
    # build: .
    hostname: mail
    domainname: domain.com
    container_name: vir
    ports:
      - 25:25
      - 110:110
      - 143:143
      - 587:587
      - 993:993
      - 995:995
    volumes:
      - /home/vmail/domain.com:/var/mail
      - ./config/:/tmp/docker-mailserver/

volumes:
  maildata:
    driver: local` 

the user's directory are with u:g -> docker:docker

if someone can help for this problem...
thx

**Comment by tomav** [comment]
Hi @patgg, probably a permission issue. 
Compare visible email to inviable one and you'll get your answer.
Should look like `-rw-r--r--  1 docker docker`

**Comment by patgg** [comment]
indeed, it seems to be a right problem...  thx

by example : 

on the host, i ve this : 
-rw-r--r-- 1 5000 5000  813365 oct.  20 15:26 domain.com/s.toto/new/1330619646.P29670Q0M853772.mail

on the container, i ve this : 
-rw-r--r-- 1 docker docker  813365 Oct 20 13:26 /var/mail/s.toto/new/1330619646.P29670Q0M853772.mail

i modyfied in adding r to group or other, but there's no diffrences in reading messages.

by exemple, for a user : these rights on directories are  ok  ? : 

ls -lt /var/mail/s.toto/
total 64
drwxr----- 2 docker docker  4096 Oct 20 13:27 cur
-rw------- 1 docker docker   376 Oct 20 13:26 dovecot.index
-rw------- 1 docker docker 10272 Oct 20 13:26 dovecot.index.cache
-rw------- 1 docker docker   794 Oct 20 13:26 dovecot-uidlist
drwx------ 2 docker docker  4096 Oct 20 13:26 tmp
drwx------ 2 docker docker  4096 Oct 20 13:26 new
drwx------ 2 docker docker  4096 Oct 20 13:24 home
-rw------- 1 docker docker 24252 Oct 20 13:24 dovecot.index.log

**Comment by tomav** [comment]
You're welcome.
