### ISSUE TITLE
Password encryption

### ISSUE THREAD

**Issue by kopax** [tomav/docker-mailserver#36]
I wan't to know how hard would it be to have encrypted password in a file.
Just in case some users get the access to the git project.

**Comment by tomav** [comment]
You're probably talking about the `postfix/accounts.cf`.
It's possible, but you'll have to add a third col in the file to specify current encoding.
You could have `PLAIN` and `MD5`.

Then you'll have to modify [this part](https://github.com/tomav/docker-mailserver/blob/master/start-mailserver.sh#L25) to do something conditional using this new value (don't encode if already encoded).

It's a good idea.
If you want to submit a PR (with integration tests, I will help you if needed), I'll be happy to merge it.

**Comment by tomav** [comment]
Both lines 25 & 26 uses the `pass`. The first is easy to manage.
The second, I don't know right now. you have to check how `saslpasswd2` can use an already encrypted password.

**Comment by kopax** [comment]
Ok I will do it, thanks for the short explaination.

**Comment by kopax** [comment]
So I did had a look. 
I can't make the implement you discribed because of `saslpasswd2` as you said.

	saslpasswd2 -h    

	This product includes software developed by Computing Services
	at Carnegie Mellon University (http://www.cmu.edu/computing/).

	saslpasswd2: usage: saslpasswd2 [-v] [-c [-p] [-n]] [-d] [-a appname] [-f sasldb] [-u DOM] userid
		-p	pipe mode -- no prompt, password read on stdin
		-c	create -- ask mechs to create the account
		-d	disable -- ask mechs to disable/delete the account
		-n	no userPassword -- don't set plaintext userPassword property
		  	                   (only set mechanism-specific secrets)
		-f sasldb	use given file as sasldb
		-a appname	use appname as application name
		-u DOM	use DOM for user domain
		-v	print version numbers and exit

**Comment by tomav** [comment]
If it can't be done using non altered software... I think we can close the issue.
I keep in mind the need, just in case...
