### ISSUE TITLE
Confirm that we can use certbot for SSL

### ISSUE THREAD

**Issue by ppKrauss** [tomav/docker-mailserver#366]
About use of [SSL with Dovecot](http://wiki.dovecot.org/SSL) with a _**free** SSL certificate_, prepared by [`certbot`](https://certbot.eff.org/)...  It is "plug-and-play" to use it here, with *docker-mailserver*? There are a "how to" about?

-----

About techinical resources and process, suppose the following:

 1. [prepare letsencrypt (or similar) to `certbot`](https://ubuntu101.co.za/ssl/update-letsencrypt-to-certbot-on-ubuntu/) 
 2. [prepare postfix and dovecot for SSL](https://ubuntu101.co.za/ssl/postfix-and-dovecot-on-ubuntu-with-a-lets-encrypt-ssl-certificate/)

**Comment by scottstensland** [comment]
Have you read the WiKi ?

https://github.com/tomav/docker-mailserver/wiki/Configure-SSL

**Comment by ppKrauss** [comment]
ops, sorry... "letsencrypt recommended" is perfect!  @scottstensland  thanks a lot!
