### ISSUE TITLE
Mailing List Support

### ISSUE THREAD

**Issue by dbrgn** [tomav/docker-mailserver#370]
Hi. Do you have any experience with running this setup together with mailing list software (e.g. Mailman 3)?

**Comment by tomav** [comment]
Nope, but you can create basic list using virtuals.
https://github.com/tomav/docker-mailserver/issues/99

Otherwise, if you find a solution that may be documented in our wiki, feel free to contribute.

Thanks.

**Comment by sebastiangraf** [comment]
@dbrgn : I have a mailman-container working with this image: https://github.com/sebastiangraf/docker-mailman3 .
Documentation should be given in the readme, otherwise just file a bug (over there).

**Comment by pokapow** [comment]
When try de register, login or reset password, this is the error:

<a href="https://www.hostingpics.net/viewer.php?id=813466Capturedu20171222124156.png"><img src="https://img15.hostingpics.net/thumbs/mini_813466Capturedu20171222124156.png" alt="Heberger image" /></a>

But when register, le registration seems to be ok in mailman database, account are created.
