### ISSUE TITLE
How to increase mail size for smtp?

### ISSUE THREAD

**Issue by dragonito** [tomav/docker-mailserver#371]
Hi there,

how can i increase the mail size for outgoing emails?

Thanks a lot

Robin

**Comment by Josef-Friedrich** [comment]
Create a configuration file named `config/postfix-main.cf`:

For 50MB:

```
 message_size_limit=52428800
```

**Comment by tomav** [comment]
Other configuration options can be found on [postfix website](http://www.postfix.org/postconf.5.html).

**Comment by dragonito** [comment]
thx a lot

**Comment by dragonito** [comment]
Perhaps give a hint for this in the documentation?

**Comment by tomav** [comment]
@dragonito this could make sense, but the this repo and its wiki provide support on the usage of the docker image (docker specific topics) and won't replace the great postfix/dovecot documentation.
