### ISSUE TITLE
Changing the fetchmail config file has no effect.

### ISSUE THREAD

**Issue by jcgruenhage** [tomav/docker-mailserver#372]
Only the first launch of the container with fetchmail enabled changes the config file, changing it later in is impossible without manually deleting files in the container and relaunching it.

The following part should be removed from setup-fetchmail to resolve this:

```bash
if [ -f "$RC" ]; then
	echo "The Fetchmail configuration is file '$RC' is already generated."
	exit 0
fi
```

**Comment by tomav** [comment]
Merged.
