### ISSUE TITLE
"Connection timed out" on own IP/Domain

### ISSUE THREAD

**Issue by Brandl** [tomav/docker-mailserver#374]
I just looked at the logfile and it's got hundreds of lines, which are simlar to those:

    Nov  3 18:05:55 mail postfix/qmgr[1434]: 81571C2D: from=<root@mail.mydomain.com>, size=642, nrcpt=1 (queue active)
    Nov  3 18:06:25 mail postfix/smtp[1436]: connect to mail.mydomain.com[123.456.789.123]:25: Connection timed out
    Nov  3 18:06:25 mail postfix/smtp[1436]: 81571C2D: to=<root@mail.mydomain.com>, orig_to=<root>, relay=none, delay=50784, delays=50754/0.01/30/0, dsn=4.4.1, status=deferred (connect to mail.mydomain.com[123.456.789.123]:25: Connection timed out)
    Nov  3 18:10:55 mail postfix/qmgr[1434]: AA16BBDD: from=<>, size=2532, nrcpt=1 (queue active)
    Nov  3 18:11:25 mail postfix/smtp[1449]: connect to mail.mydomain.com[123.456.789.123]:25: Connection timed out
    Nov  3 18:11:25 mail postfix/smtp[1449]: AA16BBDD: to=<root@mail.mydomain.com>, relay=none, delay=309063, delays=309033/0.01/30/0, dsn=4.4.1, status=deferred (connect to mail.mydomain.com[123.456.789.123]:25: Connection timed out)

Should this concern me and what did I do wrong leading up to this?

**Comment by tomav** [comment]
Hi @Brandl, I can't reproduce the problem on my instances.
Could you send and receive mails? Everything is ok regarding firewall/network?

**Comment by tomav** [comment]
Feel free to reopen if you have more information /logs to provide.
