### ISSUE TITLE
How do I renew the letsencrypt certificates?

### ISSUE THREAD

**Issue by PhilAndrew** [tomav/docker-mailserver#375]
Mine have expired, how do I renew?

**Comment by tomav** [comment]
Hi @PhilAndrew, this is not related to this docker image.
You should check `certbot` documentation and search for `renewal`.
https://certbot.eff.org/all-instructions/

Restart your mail instance when new certs are deployed.

**Comment by jcalfee** [comment]
What is required so the new certificate can auto-load without a restart (ideally without down time)?
