### ISSUE TITLE
only allow sending to its own domain

### ISSUE THREAD

**Issue by hansbogert** [tomav/docker-mailserver#376]
Is there a toggle, i.e., environment variable option, to enable/disable sending to other domains than the mailserver's own domain? Or do I need to make my own Dockerfile which overwrites the postfix configuration files for that?

**Comment by tomav** [comment]
Hi @hansbogert, you probably need to [override postfix configuration](https://github.com/tomav/docker-mailserver/wiki/Override-default-postfix-configuration), which does NOT require a custom build.

**Comment by hansbogert** [comment]
For reference, the following postfix directive can be used:

    default_transport = error:outside mail is not deliverable
