### ISSUE TITLE
[Question] Certificates renew and restart of services

### ISSUE THREAD

**Issue by Nesousx** [tomav/docker-mailserver#377]
Hi,

I was wondering, if it was necessary  / mandatory to restart the postfix and dovecot (or in this case, our mail container) services after renewing the certificates.

If I am not mistaken, renewing a cert with nginx requires a service restart (and not just a reload). I am wondering if it is also the case with the mail stack.

Thanks in advance.

**Comment by tomav** [comment]
Hi @Nesousx, yes restart is necessary.

**Comment by strarsis** [comment]
Apparently postfix just needs to be reloaded while dovecot has to be restarted:
https://www.shivering-isles.com/lets-encrypt-free-trusted-certificates-for-postfix-and-dovecot/#reloadyourcertificatesafterrenew
