### ISSUE TITLE
Document LDAP Support

### ISSUE THREAD

**Issue by jcgruenhage** [tomav/docker-mailserver#380]
I just switched my server over to LDAP, expecting the things mentioned in the Readme to be enough, or finding a wiki page, should there be anything else I had to do. Looking into the log of the server revealed that there were additional config files, which should be created.

It would also be nice to have support in the setup.sh file to debug LDAP, like with fetchmail.

I'll try setting LDAP up now, should I succeed, I will probably write the documentation myself and send in a PR (or however that works with the wiki, never used the wiki before).

Edit: I gave up, LDAP and mail is fugly, was way easier with Nextcloud, gogs and ejabberd.

**Comment by tomav** [comment]
Let's ping @dennis95stumm and @alinmear to check if they can improve this part.

**Comment by dennis95stumm** [comment]
In the latest Version of the LDAP integration no config files are necessary. Only the environment variables specified in the README.

**Comment by jcgruenhage** [comment]
Oops, then I must have done something wrong :D
