### ISSUE TITLE
554 5.7.1 <test@example.com>: Relay access denied

### ISSUE THREAD

**Issue by diluex** [tomav/docker-mailserver#385]
The receiver mx server denies accepting emails.
telnet and also thunderbird showed this error.
receiving mail and imap login work.
also smtp login by telnet.

Did a clean install with docker-compose.yml:

version: '2'

services:
  mail:
    image: drakulix/armhf-mailserver
    # build: .
    hostname: mail
    domainname: example.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
    - SSL_TYPE=letsencrypt
    - SSL_CERT_PATH=/etc/letsencrypt/live/example.com/fullchain.pem
    - SSL_KEY_PAH=/etc/letsencrypt/live/example.com/privkey.pem
volumes:
  maildata:
    driver: local

**Comment by tomav** [comment]
Hi @diluex, have you configured your client with SMTP auth?
If no, you should.

For the rest:
- we don't have enough information here to help you
- you're using en modified version of this image and we can't support it

Thank you.

**Comment by diluex** [comment]
HI @tomav,
i'm aware of the patched docker image but should be the same for armhf architecture as it is compiled on the official source code.
your docker image shows the same error on my desktop.

i'm not sure what you're talking about the smtp auth (maybe no).
just followed your description on the codepage and adapted some settings as mentioned above.

Which information do you need? how do i configure the smtp auth?

thank you in advance!

**Comment by tomav** [comment]
You have configured IMAP (probably) with authentication.
You need to do the same for SMTP.
https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-configure-my-email-client

**Comment by diluex** [comment]
oh yeah! of course i've did. i just skipped the word 'client'.
so that was not the problem.
any ideas left?

**Comment by tomav** [comment]
I haven't been able to reproduce your problem.
Reopen this issue if you have more information / logs to provide.
