### ISSUE TITLE
dovecot: auth: passwd-file(adrien@domain.com): unknown user

### ISSUE THREAD

**Issue by abipit** [tomav/docker-mailserver#387]
Hello and thank you @tomav for this container !! 

I configured the files and started your container and I can send mail to another domain.
Example: from hotline@domain.com, I send and receive an email on adrien@gmail.com or adrien@yahoo.fr, no problem.

But if i want send email to the same domain, from hotline@domain.com to adrien@domain.com, I get the following errors : 

```Nov 23 12:34:11 mail postfix/pickup[1301]: 8DAEA5285E77: uid=0 from=<hotline@domain.com>
Nov 23 12:34:11 mail postfix/cleanup[1344]: 8DAEA5285E77: message-id=<20161123123411.8DAEA5285E77@mail.domain.com>
Nov 23 12:34:11 mail opendkim[479]: 8DAEA5285E77: DKIM-Signature field added (s=mail, d=domain.com)
Nov 23 12:34:12 mail postfix/qmgr[1302]: 8DAEA5285E77: from=<hotline@domain.com>, size=373, nrcpt=1 (queue active)
Nov 23 12:34:12 mail dovecot: lmtp(1347): Connect from local
Nov 23 12:34:12 mail dovecot: auth: passwd-file(adrien@domain.com): unknown user
Nov 23 12:34:13 mail postfix/lmtp[1346]: 8DAEA5285E77: to=<adrien@domain.com>, relay=mail.domain.com[/var/run/dovecot/lmtp], delay=4.1, delays=3.3/0.01/0.03/0.7, dsn=5.1.1, status=bounced (host mail.domain.com[/var/run/dovecot/lmtp] said: 550 5.1.1 <adrien@domain.com> User doesn't exist: adrien@domain.com (in reply to RCPT TO command))
Nov 23 12:34:13 mail dovecot: lmtp(1347): Disconnect from local: Successful quit
Nov 23 12:34:13 mail postfix/cleanup[1344]: 58CF15285E79: message-id=<20161123123413.58CF15285E79@mail.domain.com>
Nov 23 12:34:14 mail postfix/bounce[1351]: 8DAEA5285E77: sender non-delivery notification: 58CF15285E79
Nov 23 12:34:14 mail postfix/qmgr[1302]: 58CF15285E79: from=<>, size=2662, nrcpt=1 (queue active)
Nov 23 12:34:14 mail postfix/qmgr[1302]: 8DAEA5285E77: removed
Nov 23 12:34:14 mail dovecot: lmtp(1347): Connect from local
Nov 23 12:34:17 mail dovecot: lmtp(1347, hotline@domain.com): v2ZIJ8SMNVhDBQAAybULOw: msgid=<20161123123413.58CF15285E79@mail.domain.com>: saved mail to INBOX
Nov 23 12:34:17 mail postfix/lmtp[1346]: 58CF15285E79: to=<hotline@domain.com>, relay=mail.domain.com[/var/run/dovecot/lmtp], delay=3.6, delays=0.68/0/0/3, dsn=2.0.0, status=sent (250 2.0.0 <hotline@domain.com> v2ZIJ8SMNVhDBQAAybULOw Saved)
Nov 23 12:34:17 mail dovecot: lmtp(1347): Disconnect from local: Successful quit
Nov 23 12:34:17 mail postfix/qmgr[1302]: 58CF15285E79: removed
```

Remarks : I installed the package mailutils to send mails directly from the container with the command mail like that : 
mail -s $SUBJECT -a "From: hotline@domain.com" $DEST <<< $BODY

Thank you for help, I don't understand the problem.

**Comment by tomav** [comment]
Hi @abipit, are you sure user accounts / aliases are created?
`User doesn't exist: adrien@domain.com` is strange if config is good.

Have you tested with a real mail client instead of `mail` command just to be sure that this problem don't come from the tool.

**Comment by abipit** [comment]
Thanks @tomav.
Yes I confirm that the 2 accounts tested exists (I receive emails on adrien@domain.com from a real mail client, ex: from gmail).

On my server, I just test with the command mail in your container.
But I'm not sure to understand, I explain : my domain is already configured in a web hosting with a lot of emails accounts, here I just want to send email from one of these account to another on the same domain with your container.
If I test with a real mail client, it's ok on mydomain.com

**Comment by tomav** [comment]
You have 2 mail server? One with everything configured and working fine (using any mail server software) and another one in the container and you want to use it to send email to the first server?

**Comment by abipit** [comment]
One with my web hoster (nuxit.com) and yes we can send emails between accounts without problems on our _domain.com_
And the second with your container to send email from and to _domain.com_

I explain my goal : on my server I want to send email when there is a problem or If the server restart for example. So I need a mail server no ? And your container seems me perfect. I configured my _domain.com_ and I can send to my gmail.com address but error If I send to an account of my _domain.com_.
