### ISSUE TITLE
Delimiter +

### ISSUE THREAD

**Issue by chiel1980** [tomav/docker-mailserver#388]
Hi,

I am setting up delimiters for sieve filtering in /etc/dovecot/conf.d/15-lmtp.conf, 90-sieve.conf and in postfix/main.cf.
Whenever I send an email to a delimiter email adress I get the following error from Dovecot:
```
Nov 23 13:11:53 server dovecot: lmtp(1476): Connect from local
Nov 23 13:11:53 server dovecot: auth: passwd-file(mve+test@test.nl): unknown user
Nov 23 13:11:53 server postfix/lmtp[1475]: 6ECF1CF2: to=<mve+test@test.nl>, relay=server.pragmasec.nl[/var/run/dovecot/lmtp], delay=0.01, delays=0/0/0/0, dsn=5.1.1, status=bounced (host server.pragmasec.nl[/var/run/dovecot/lmtp] said: 550 5.1.1 <mve+koen@pragmasec.nl> User doesn't exist: mve+test@test.nl (in reply to RCPT TO command))
Nov 23 13:11:53 server dovecot: lmtp(1476): Disconnect from local: Successful quit
```
It seems that dovecot does not seem to strip the delimiter/detail from the username

I also had to specify the following in 10-auth.conf:
```
auth_username_chars = abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.-_@+ 
```

otherwise the address was blocked.

How can I make mve+test@test.nl work and deliver it to mve@test.nl?

**Comment by tomav** [comment]
Tested on my instance, and works as expected.
Make sure you have this line in your config:
https://github.com/tomav/docker-mailserver/blob/master/target/postfix/main.cf#L16

**Comment by chiel1980** [comment]
Ok, have you set delimiters in other places like 15-lmtp.conf, and change the username allowed characters in 10-auth.conf? Or is this the default config from the container?

**Comment by tomav** [comment]
On my side its default config (I think), I only override 2 postfix parameters but not related.

**Comment by chiel1980** [comment]
Hmm I reverted my install from a snapshot of this morning and you're right..seems to be PEBKAC ;)

**Comment by tomav** [comment]
Great!
