### ISSUE TITLE
custom rbls

### ISSUE THREAD

**Issue by tronicum** [tomav/docker-mailserver#391]
I would like to have custom rbls or at least the option to override the default selection. would supply a PR, where would I put such variable within target/postfix/main.cf (and default it to the current, so it does not break)?

**Comment by tronicum** [comment]
I would also like to have an custom "append main.cf" var, so i could add
smtpd_tls_received_header = yes 
to see detailes TLS headers, e.g.

**Comment by tomav** [comment]
Hi @tronicum, have you read the [wiki](https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration)?

**Comment by tronicum** [comment]
yes, but i just want to add custom stuff, or customize options, not replace the whole configuration

**Comment by tomav** [comment]
It's an override. It keeps default config and change only what's provided in the override config.

**Comment by tronicum** [comment]
you need to take care with newslines though (i copied the rbl lines and they need to be in one line (or mybe \ would work)
