### ISSUE TITLE
Policyd support

### ISSUE THREAD

**Issue by oozone** [tomav/docker-mailserver#392]
Would it be possible to integrate [policyd](http://wiki.policyd.org/start) support. Do you plan on doing so? If not, how would one go about this?

**Comment by tomav** [comment]
Hi @oozone, no planned currently.
What's the killer feature of Policyd?

**Comment by oozone** [comment]
Hi thanks for your reaction. With policyd one could limit the rate at which emails are sent, eg a rule could be enforced wherin a user can only send 1000 emails / month, would be great in this image. Unless you know if there's other ways to achieve the same goal?

**Comment by tomav** [comment]
Not sure a limitation on email sent is a common wanted behaviour.
Let's see what other say but policyd brings lot of features that we already have

**Comment by oozone** [comment]
Or what do you think of an Admin interface for this Docker image?
https://github.com/opensolutions/ViMbAdmin

**Comment by tomav** [comment]
Feel free to document how to use this kind of tool, but it should be not integrated into the image core.
