### ISSUE TITLE
Add Option for specifying postfix virtual_transport (in order to work with kopano as dagent)

### ISSUE THREAD

**Issue by alinmear** [tomav/docker-mailserver#394]
@tomav i already made a pull request for kopano support (#335) of this project. In order to generalize this issue i would suggest instead of only making a config step for kopano we could make this one for the virtual_transport in general. This could be useful for people that need to be more flexible regarding the configuration of the postfix lmtp client and is also much cleaner (compared to my first implementation)

to make this work we would need two more environment variables:

- ENABLE_POSTFIX_VIRTUAL_TRANSPORT (task, do this or not, see #338)
- POSTFIX_DAGENT (section)

And also for my particular needs it would be easy without double checks (see implementation of #335, check for SMTP_ONLY = 1) to integrate this into my kopano env, e.g. virtual_transport = lmtp:address-to-kopano-instance:2003.

To get an idea for this feature maybe have a look at (for a quick overview):
http://wiki.linuxquestions.org/wiki/Postfix_virtual_transport

**Comment by tomav** [comment]
You can't override config files for that? All this kopano stuff doesn't seem mainly used.

**Comment by alinmear** [comment]
@tomav, in particular this has nothing to do with kopano itself; this would implement the possibility without providing specific config files to fire up a container with a particular lmtp client (e.g. exim, postfix, sendmail, cyrus, dovecot, kopano, etc.) or to have e.g. dovecot on a different server; for this take a look at http://wiki2.dovecot.org/LMTP.

I tried to generalize the needs of my particular kopano installation, so that the whole project benefits from it.

**Comment by tomav** [comment]
Feel free to submit a PR and document this in Wiki.

**Comment by alinmear** [comment]
@tomav see #409

**Comment by tomav** [comment]
Merged.
