### ISSUE TITLE
Time mismatch between host and container

### ISSUE THREAD

**Issue by arcaine2** [tomav/docker-mailserver#397]
I had time shifted -1h versus the host and my current time. Something as simple as "      - /etc/localtime:/etc/localtime:ro" in volumes section in yml file is enough.

**Comment by tomav** [comment]
Yep, this is more docker related but its a nice trick.
I add it to the [FAQ](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-sync-container-with-host-datetime).
