### ISSUE TITLE
Fail2ban fails to start after restarting container

### ISSUE THREAD

**Issue by arcaine2** [tomav/docker-mailserver#398]
It looks like fail2ban doesn't shutdown properly and after a container restart there's still a fail2ban.sock file left in /var/run/fail2ban/ directory.

**Comment by tomav** [comment]
Hi @arcaine2, I think I already faced this problem.
A check in `start-mailserver.sh`may solve the issue.
Could you provide a patch for that?

**Comment by arcaine2** [comment]
I'm new to that (on github) so please check if haven't mess up anything but this should do.

**Comment by tomav** [comment]
Should be fixed by #404
