### ISSUE TITLE
[Question] Way to backup/preserve/restore mail?

### ISSUE THREAD

**Issue by icosahedron** [tomav/docker-mailserver#399]
This might be a docker question rather than a mail server question.

What is the best way to preserve mail or backup/restore mail in between docker run invocations?  I'd like to add some features (e.g. SSL) that I didn't add the first time.

**Comment by icosahedron** [comment]
I think this is what I'm looking for.

[Manage data in containers](https://docs.docker.com/engine/tutorials/dockervolumes/#/backup-restore-or-migrate-data-volumes).

Can someone confirm that backing up the mail data volume and then restoring it after a subsequent docker-compose will indeed restore e-mail?

**Comment by tomav** [comment]
Hi @icosahedron, if your data are stored in a volume, external data container, or on host, the answer is yes.
A backup script for your emails can be found in the [FAQ](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#what-about-backups)
