### ISSUE TITLE
Review of main.cf and master.cf by a Postfix expert

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#4]
It works, but can be improved.
If a Postfix expert could have a look, it would be nice.
Thank you.

**Comment by gegere** [comment]
Tom, in response. Your main.cf file works well but there is a more robust method to assign configuration settings. Using `postconf -e` you will be able to assign the needed variables. Also you don't need to manage the file location and placement of said file directly in the build. Your main.cf can be removed and the needed config can be directly applied within `start-mailserver.sh`

Test this:
```
postconf -e smtpd_relay_restrictions=permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination

```

I have been building and continuing to improve a Docker Postfix Project: https://github.com/htmlgraphic/Postfix

**Comment by gegere** [comment]
Hope this was helpful. :+1:
