### ISSUE TITLE
time out on port 25

### ISSUE THREAD

**Issue by keyrush** [tomav/docker-mailserver#40]
Hi,
The configuration went well, I'm able to fetch messages using STARTTLS for my different users.
But I'm unable to send any messages from some mail clients (Thunderbird can, but Evolution can't).

I'm seeing a strange behaviour of the port 25:
```
$ telnet mail.myserver.net 25
```
gets a timeout from a remote host, but works on the server itself.
Whereas,
```
$ telnet mail.myserver.net 587
Trying 94.23.54.109...
Connected to mail.myserver.net.
Escape character is '^]'.
220 mail.myserver.net ESMTP Postfix (Ubuntu)
EHLO moi
250-mail.myserver.net
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
```
is OK from a remote host.
It seems to be related to my server configuration, but I didn't find any conflicting postfix running, I didn't have any specific iptables configuration.
Did I miss something?

**Comment by tomav** [comment]
Hi @keyrush, if it works locally, it's not related to the image, but perhaps to the port exposition to the outside world. This can be docker related or iptables related.
Check that:
* your port 25 is open from the outside
* that you ISP don't block request to unknown hosts on port 25

Let us know.

**Comment by keyrush** [comment]
My server is hosted at OVH, so I guess it's not ISP related.
Here at some outputs on the server:
```
$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:imaps
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:submission
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:imap2
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:smtp

$ docker port mail
143/tcp -> 0.0.0.0:143
25/tcp -> 0.0.0.0:25
587/tcp -> 0.0.0.0:587
993/tcp -> 0.0.0.0:993

$ sudo netstat -plnt | grep ':25'  
tcp6       0      0 :::25                   :::*                    LISTEN      2477/docker-proxy
```
And for nmap from outside:
```
PORT   STATE    SERVICE
25/tcp filtered smtp
```

**Comment by tomav** [comment]
The `nmap` status should be `open` no?

    PORT   STATE SERVICE
    25/tcp open  smtp

I think your problem is related to iptables and the `DOCKER` chain.

Try to add:

iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
iptables -t nat -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
iptables -t nat -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE

And let me know.

**Comment by keyrush** [comment]
Thanks for the advice. Unfortunately it didn't work.
I agree that the state should be reported as open. It looks like something is processing the request before postfix. Could it be related to amavis/anti-virus stuff?

**Comment by tomav** [comment]
I don't think so. It's received on port 25 and forwarded to amavis.
If you don't see anything on your logs, it's because the request doesn't reach the docker image.

I had the same kind of issues when I deployed my `docker-mailserver` to production.
I know that docker can manage iptables rules:

	Do your iptables allow this particular connection? Docker will never make changes to your system iptables rules if you set --iptables=false when the daemon starts. Otherwise the Docker server will append forwarding rules to the DOCKER filter chain.

	Docker will not delete or modify any pre-existing rules from the DOCKER filter chain. This allows the user to create in advance any rules required to further restrict access to the containers.

That's why I added `--iptables=false` to my docker start options and manage the `iptables` configuration with the rules provided above in this thread.

You should really have a look to this. But...

I just read again your first post, and you wrote that it worked from the outside world with some clients? (Thunderbird). Really strange no?

**Comment by keyrush** [comment]
OK, I'll dig the iptables configuration.
It worked with Thunderbird on port 587 only. I could not manage to send any emails with Evolution. So this is another problem, probably related to the client. I could live with that, but there is still a problem somewhere with my port 25 :)

**Comment by keyrush** [comment]
I got it finally.
Even after stopping my container I still got time-outs on port 25, although no one was listening on this port any more.
A traceroute from a remote host indicated that I wasn't even passing my ISP's box.
There is indeed a setting for that (my provider is Free, and I have a Freebox v5).

For the record ("Blocage SMTP sortant" is "Block SMTP out") :
![screenshot](https://cloud.githubusercontent.com/assets/6901579/11533268/0b71a98c-9909-11e5-9e75-d738beb1bada.png)

Now I'm able to use STARTTLS on port 25 with any mail client, and by the way Evolution is now also working on port 587.
Sorry for the noise and thanks for the help. Hope that it'll be useful to someone.

**Comment by tomav** [comment]
I was still using Free few months ago (I think Bouygues has the same behaviour).
That's why it was one of my two leads.

But it's a good new!
