### ISSUE TITLE
Sending email from the server

### ISSUE THREAD

**Issue by Nesousx** [tomav/docker-mailserver#403]
Hi,

I have been using this container for a few weeks now. It is working fine. I, however, have a question. How can my server keep sending email, like reports?
On my other servers, I have sendmail running, for example, in order to send "system mails". However, since I have the container running on the same port, I had to disable sendmail...

Any idea how to fix this?

Thanks.

EDIT : I guess, I could change "outiside" port numbers on the Docker container, but I am lookng for some nicer solution than changing official service ports...

**Comment by tomav** [comment]
Hi @Nesousx, thanks for using this image.
Regarding your point, `/etc/aliases` to set email address and installing package like `ssmtp` should do the trick.

Let me know.

**Comment by tomav** [comment]
Close due to inactivity, reopen if needed.
