### ISSUE TITLE
[Question] Does Dovecot use ELK for IMAP searches?

### ISSUE THREAD

**Issue by icosahedron** [tomav/docker-mailserver#411]
If the ELK stack is installed, or if docker-mailserver is configured to use an external ELK stack, does Dovecot use this for IMAP searches or does it rely on its own indexing?

**Comment by tomav** [comment]
Hi @icosahedron, absolutely not. The mailstack forwards logs to ELK for stats/debug.
IMAP searches depend on mail client.
Not sure there's something to do, but feel free to reopen if needed.
