### ISSUE TITLE
postfix-virtual delivery duplicated

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#419]
Hi, I have configured some virtual addresses, for example:

junior@example.com   junior@example.com, produccion@example.com

I want to get a copy in junior@example.com and another one delivered to produccion@example.com, but, instead of that, I get one copy in junior@ and TWO copies in produccion@, why? maybe some recursive delivery? or am I setting it up wrong?

Thanks

**Comment by tronicum** [comment]
which file did you put that in?

**Comment by citec** [comment]
config/postfix-virtual.cf

**Comment by citec** [comment]
I need to explain here that junior@ is a real mail account in the container, but I want to receive copies in produccion@, so junior@ receives one copy and produccion@ receives another copy. Instead of that I get one copy in junior@ and two copies in produccion@

**Comment by tomav** [comment]
Hi @citec, I just tried the following viruals:

`real-account@domain.tld real-account@domain.tld,another-real-account@domain.tld`

`another-real-account@domain.tld` will receive the same mails `real-account@domain.tld` receives.

**Comment by tomav** [comment]
By the way, both will work:

```
# send a copy
account1 account1,account2

# kind of mailing list
alias account1,account2
```

But recipients have to be accounts, not aliases.
