### ISSUE TITLE
explore dovecot master/master

### ISSUE THREAD

**Issue by tronicum** [tomav/docker-mailserver#430]
What about dovecot master/master replication: http://wiki.dovecot.org/Replication ?

**Comment by tomav** [comment]
There is already a discussion about that in #254. Feel free to feed the discussion.

**Comment by tronicum** [comment]
yes, but about a different topic...

**Comment by tronicum** [comment]
if you really care about #236 you should work on your communication and leading style.

**Comment by tronicum** [comment]
i just started a branch for 254 but with that kind of bingo. have a nice christmas.

**Comment by tomav** [comment]
Thanks @tronicum, let us know.
I'll keep your advice in mind.
Merry Christmas too.
