### ISSUE TITLE
ELK Build fails

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#433]
```
Build failed: The command '/bin/sh -c gosu logstash bin/logstash-plugin install --local --no-verify logstash-filter-geoip' returned a non-zero code: 1
```

**Comment by tomav** [comment]
```
 ---> Running in 593782a71a5b
Installing logstash-filter-geoip
Plugin not found, aborting
ERROR: Installation Aborted, message: Could not find arr-pm-0.0.10 in any of the sources
The command '/bin/sh -c gosu logstash bin/logstash-plugin install --local --no-verify logstash-filter-geoip' returned a non-zero code: 1
```

https://github.com/elastic/logstash/issues/6411
https://github.com/logstash-plugins/logstash-filter-translate/issues/39

**Comment by citec** [comment]
for me it worked like a charm:

```
Step 11 : RUN gosu logstash bin/logstash-plugin install --local --no-verify logstash-filter-geoip
 ---> Running in b72c997b9240
Installing logstash-filter-geoip
Installation successful
 ---> 6a7ae7a291b5
```

**Comment by tomav** [comment]
Was not the case here: https://hub.docker.com/r/tvial/docker-mailserver/builds/
I'm gonna restart it to check if its better now.

**Comment by tomav** [comment]
Great, works now! I think a dependency has been updated.

**Comment by citec** [comment]
Hi, even building, it seems that [Logstash 5.x no longer supports .dat format Geo Databases](https://github.com/logstash-plugins/logstash-filter-geoip/issues/90)
I am changing the url on de `elk/Dockerfile` to `http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz`, the unzipped file keeps its name. I will do a PR for this

**Comment by citec** [comment]
#481
