### ISSUE TITLE
Move to supervisord

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#434]
Proposed by @viossat, good idea.

**Comment by alinmear** [comment]
What i know about supervisord, we have to take care of daemon ps without a foreground mode. A possible approach could be something like this: http://serverfault.com/questions/608069/managing-daemons-with-supervisor-no-foreground-mode-available.

Is anybody working on this?

**Comment by tomav** [comment]
I don't, but it will be more docker compliant to have it.

**Comment by LukeAllen** [comment]
@tomav I'm working on this. I'll do a PR soon.

**Comment by johansmitsnl** [comment]
@tomav ticket can be closed.
Feature is implemented.
