### ISSUE TITLE
Make POSTMASTER_ADDRESS mandatory

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#435]
And configure dovecot + `/etc/aliases` with it.

**Comment by tomav** [comment]
Just see that, when empty, it's currently statically set to `postmaster@domain.com` which is not a good idea.

**Comment by johansmitsnl** [comment]
@tomav Adding this might break a lot of deployments.
Agree to not implement it as mandatory?

**Comment by tomav** [comment]
Ok.
