### ISSUE TITLE
Authentification failed

### ISSUE THREAD

**Issue by Sabmit** [tomav/docker-mailserver#44]
Hello,

Sorry for this issue, I may be the only one which cannot get this repo working at 100%.
After building this image on a docker-machine at digitalOcean, setting up the DNS records, and setting the virtual account, I successfully get all the email forwarded and stored to /var/mail/.

Unfortunately, I didn't succeed to login to my email account.
Here's the auth.log :

```
Dec 15 10:31:56 mail saslauthd[624]: do_auth         : auth failure: [user=lol@sabmit.io] [service=login] [realm=sabmit.io] [mech=sasldb] [reason=Unknown]
```

Here's the startup script log :
```
mail_1 | Listing SASL users
mail_1 | lol@sabmit.io: userPassword
...
mail_1 | TESTING SASL
mail_1 | 0: NO "authentication failed"
```

And here's the command to try to login :
```
testsaslauthd -s login -u lol@sabmit.io -p test
testsaslauthd -u lol@sabmit.io -p test
testsaslauthd -s login -u lol -r sabmit.io -p test
```

I temporary set the auth mech to :
```
pwcheck_method: auxprop
mech_list: PLAIN LOGIN CRAM-MD5 DIGEST-MD5
allow_plaintext: true
log_level: 7
```
- User Postfix owns /etc/sasldb2

Any help would be appreciate.

**Comment by tomav** [comment]
Hi @Sabmit, I did not have a look to sasl for a long time.
I can reproduce the problem. I'll try to give an answer.
If you find something, let me know.

**Comment by tomav** [comment]
I really don't know why it doesn't work locally.
But it works from a mail client sending an email:

    mail postfix/submission/smtpd[7745]: DB150116B: client=bbox.lan[192.168.1.254], sasl_method=DIGEST-MD5, sasl_username=user@domain.tld

**Comment by tomav** [comment]
@Sabmit can you try this branch? https://github.com/tomav/docker-mailserver/pull/50

**Comment by tomav** [comment]
This line should be interesting for you: https://github.com/tomav/docker-mailserver/blob/add-plain-and-login-mech/test/test.sh#L18

**Comment by tomav** [comment]
@Sabmit I will merge today. If you can have a look to the branch before it would be appreciated.
Thank you.

**Comment by Sabmit** [comment]
Hello tomav, thanks for this PR.
It seems to be Ok, but unfortunately, I'll not be able to test this new version before this WE.
I deleted my docker-machine and I need a few hours to setup everything back.
Can't take that time at work :/

**Comment by tomav** [comment]
Ok, we're friday, I can wait, no worry :-)
Let me know this week end, just to be sure.
Thank you @Sabmit

**Comment by tomav** [comment]
Time to merge.
