### ISSUE TITLE
Use recipient_delimiter with aliases

### ISSUE THREAD

**Issue by nwolber** [tomav/docker-mailserver#442]
It is currently not possible to use the `recipient_delimiter` (by default +) with aliases configured in `config/postfix-virtual.cf`. The reason is, that dovecot doesn't know about the aliases.

Let's say you have `me@somedomain.com` configured as an account in `config/postfix-accounts.cf` and an alias `full.name@somedomain.com` in `config/postfix-virtual.cf`. When a mail with recipient `full.name+idonttrustyou@somedomain.com` gets received by the mail server, it is processed just fine by postfix. It then tries to deliver the mail to dovecot (as per `virtual_transport` in `target/postfix/main.cf`). Because dovecot is unaware of the aliases it rejects the mail with 
> User doesn't exist: full.name@somedomain.com

**Comment by tomav** [comment]
Are you sure this is possible on aliases on postfix?

**Comment by nwolber** [comment]
I think it is, I got it working for me. I just pushed the commit here: https://github.com/nwolber/docker-mailserver/commit/19c6a40e758aa56000fdb9a526a48047ef150ddb

Unfortunatly I didn't have time to write a test case yet.

**Comment by tomav** [comment]
Tes case are needed to integrate a PR. We have 100+ tests but its currently not enough.
Have you checked https://github.com/tomav/docker-mailserver/pull/409?
@alinmear any thought?

**Comment by nwolber** [comment]
I thought so. I hope to get time to write a test some time soon. When I'm done with it, I will open a PR.

**Comment by tomav** [comment]
@nwolber let us know if the use case added by @tyranron matches your expectations.
@tyranron thanks for that!
I'll merge when @nwolber will reply.

**Comment by nwolber** [comment]
Issue is resolved. Tests resulting from this issue are available in #528.
