### ISSUE TITLE
readme.md: adding accounts and generating DKIM keys, why not with setup.sh?

### ISSUE THREAD

**Issue by spock** [tomav/docker-mailserver#445]
Thanks for a great project, preparing to start using it very soon.

There exists the highly convenient `setup.sh` script, but `readme.md` is still showing "full" examples of adding email accounts and generating DKIM keys. Is this left so on purpose? If not, then I can update the readme.md to show `setup.sh` commands instead.

**Comment by tomav** [comment]
Hi @spock, a lot of things were existing in `README` but there was too much information.
We only want to keep what allows you to start a container with an email account (and a default security). "Advanced" options are detailed in wiki.

Fee free to add a note/link to the wiki for `setup.sh` if you think it's necessary.

**Comment by tomav** [comment]
Fixed by #453
