### ISSUE TITLE
CoreOS support?

### ISSUE THREAD

**Issue by rubytastic** [tomav/docker-mailserver#45]
This Repo looks great and Im in the need for setting up an easy dockerized mailservice.
But, how does this work for a coreOS read only file system. 

What would be the best way to add the mail accounts on a coreOS system where you cannot mount a filesystem on the host to the docker container?

**Comment by gegere** [comment]
Greetings! Using this with CoreOS should be of no problem at all. About a year ago I started learning Docker, Fleetd, etcd and CoreOS. 

Here is a link to service files examples: https://github.com/htmlgraphic/CoreOS/tree/master/Services

After having a working cluster I was meet with issues and maintaining / troubleshooting became a chore. The disadvantages w/ CoreOS simply out weighed the advantages. There was an issue with the disk on Digital Ocean as the CoreOS system basically destroyed the SSD. I would not recommend using CoreOS but I would recommend using Tutum.co. CoreOS was to technical to manage correctly with ease.

To answer your question you can create a data volume directly on CoreOS. You can also create data containers and have them sync across a cluster. Several options and using Docker is a great way to work with mail services. Hope this helps!

**Comment by rubytastic** [comment]
Hi Gegere, 
Thanks for your extensive reply much appreciated. I have just started with coreOS and thought it was read-only. I will investigate your suggestions. Very much appreciated. happy christmas!

**Comment by rubytastic** [comment]
@gegere 
Could you please state some more information regarding your comment on digital ocean and loosing data on a mounted data volume inside coreOs?

**Comment by rubytastic** [comment]
After reading more on the subject I think that using AWS as a cloud storage would be the best option. 
This could add also extra security if the AWS storage can be encrypted. 
Assuming this more of a docker issue and not really related to this repo perhaps it could be useful never theless. Is anyone using this docker with a data volume that is stored on AWS and what are your thoughts?

**Comment by gegere** [comment]
@rubytastic there is more information on the system having hardware boot issues. https://github.com/coreos/bugs/issues/320 (I would not recommend CoreOS)

To answer your most recent post explore [Tutum.co](http://tutum.co) I do recommend this as you can host Docker containers on Digital Ocean, Microsoft or Amazon others are also supported.

**Comment by rubytastic** [comment]
Thank you gegere
I hope there is a workaround for moving data volumes inside coreOS then again that is not an issue for this project. Digitalocean advantages falls away there if on AWS we could just mount a EC2 volume on the coreos
