### ISSUE TITLE
Adding accounts and recreating the container?

### ISSUE THREAD

**Issue by Rubytastic2** [tomav/docker-mailserver#450]
How about recreating the container from scratch after accounts where added: 

```
docker run --rm \
  -e MAIL_USER=info@actusmedia.nl \
  -e MAIL_PASS=LKsMfBsxCcVsBVLqiU4tXLJ7dQJyRtYXAEpzXL2eab94aE4Q9QZpy7zLCj3LU3Yu \
  -ti tvial/docker-mailserver:latest \
  /bin/sh -c 'echo "$MAIL_USER|$(doveadm pw -s SHA512-CRYPT -u $MAIL_USER -p $MAIL_PASS)"' >> config/postfix-accounts.cf
```
Does this need to be redone for all the email accounts or would the container just pick up from the config/postfix-accounts.cf?

**Comment by tomav** [comment]
The container uses `config/postfix-accounts.cf`. Once the file is generated, you don't have anything more to do. If you recreate the container from scratch, if the file exists and is correctly mounted, users will be recreated.
