### ISSUE TITLE
Add support for postfix check_recipient_access

### ISSUE THREAD

**Issue by ghost** [tomav/docker-mailserver#452]
The check_recipient_access config option for Postfix will enable us to determine access to specified users. For example you can reject mail to a local user (no-reply@domain.tld)

**Info**
http://www.postfix.org/RESTRICTION_CLASS_README.html
http://superuser.com/questions/573881/disable-incoming-emails-for-a-specific-virtual-user

**Comment by tomav** [comment]
Hi @extink good idea. This can already be done using postfix override I think but there's probably a better to integrate it. Wanna contribute?

**Comment by 17Halbe** [comment]
I could implement that.
But IMHO this is a feature that is not commonly used. What do you think? Is a separate optional file with permissions just for that feature desirable? 

What about a wiki entry/Howto? 

But as I said, I could do a PR which would add an additional config file.(i.e. something like postfix-recipient-access.cf?)

**Comment by johansmitsnl** [comment]
A separate file that you could manage trough the setup script would do.
