### ISSUE TITLE
Configure Apple Mail fails

### ISSUE THREAD

**Issue by Rubytastic2** [tomav/docker-mailserver#454]
Im trying to configure apple mail but it always fail to verify username and password

# imap
username:           <user1@domain.tld>
password:           <mypassword>
server:             <mail.domain.tld>
imap port:          143 or 993 with ssl (recommended)
imap path prefix:   INBOX

# smtp
smtp port:          25 or 587 with ssl (recommended)
username:           <user1@domain.tld>
password:           <mypassword>
Please use STARTTLS.

STARTTTLS is not an option mentioned in Apple mail.
Only TLS/SSL

Has anyone managed to set apple mail up correctly and could share details on how to do so?
Currently Im using automatically manage connection settings OR Authentication "Password" 

Al fails, 

The docker container runs and is accepting telnet sessions on port 25 also I created an postfix account file with encrypted password for the mailaddress

**Comment by Rubytastic2** [comment]
I also enabled letsencrypt but it gives me in apple mail a certificate that is self signed with
Default Company Ltd 

As the name. 

Again its not accepting my username and password

**Comment by tomav** [comment]
Hi added note in the [README](https://github.com/tomav/docker-mailserver/commit/cfd7fde1eafb733835945975fe98fe1d3fad8c37).

When you open an issue, there's a note regarding detail to provide.
https://github.com/tomav/docker-mailserver/blob/master/CONTRIBUTING.md

Could you start your server with `DMS_DEBUG=1` and paste the output?

**Comment by Rubytastic2** [comment]
Thank you Tomav,

Setting DMS_DEBUG=1
Does not report any errors in the terminal.
It just startups correctly the docker container.
I can also connect to it, but the username password is always invalid.
I also disabled SSL for now, same problem.

I hoped this would save me lots of time getting a mailserver up but these issues are holding me back mayor in a new server migration. 

Also nothing special in the docker container itself, inside the logs. 
Could you perhaps tell me where I could find the dovecot and postfix log files that hold authentication errors ? var/log/mail/* holds nothing special

**Comment by tomav** [comment]
Yes, it's in `/var/log/mail/mail.*`. If you don"t see anything, you're not connecting to the mail server (but somewhere else). Few people had DNS configuration/propagation issues.

**Comment by tomav** [comment]
Reopen if needed.
