### ISSUE TITLE
Some ideas  ( out of office, config script, push mail ) 

### ISSUE THREAD

**Issue by rubytastic** [tomav/docker-mailserver#46]
Perhaps a nice feature to have is an out of office feature. 
And a simple script you can run in the terminal to manage the account creation, editing , removal out of office. Although both are minor I would love to contribute to this repo and have thought of writing such a solution myself for a non dockerized mailserver setup I currently run in production. ( but plan to move to the base of this docker solution )

Auto responders would be nice:
https://www.howtoforge.com/how-to-set-up-a-postfix-autoresponder-with-autoresponse

Probably overkill:
https://www.mnxsolutions.com/scripts/postfix-dovecot-user-admin-script.html

Push email to clients:
http://mishmashmoo.com.au/blog/?p=208

**Comment by tomav** [comment]
I close this issue and wait for PR if someone wants to add some new features without doing something overkill.
