### ISSUE TITLE
Docker Data Size Increase

### ISSUE THREAD

**Issue by ttermeer-ouat** [tomav/docker-mailserver#464]
We have noticed that our AWS instances were running out of space on the docker drive after 2 weeks. We have pinpointed the problem to the docker-mailserver which seems to increase the docker data used ( in docker info ) every 6h by 200 MB.
Using "docker ps -s" doesn't show the container taking much space.

Any idea what it causing this issue ?

**Comment by tomav** [comment]
Hi @ttermeer-ouat, thanks for using this image.
What is the size of `/var/mail` and (if you're using `ONE_DIR=1`) `/var/mail-state`?

**Comment by ttermeer-ouat** [comment]
Thanks for the quick reply.
The size of /var/mail is 76k

**Comment by tomav** [comment]
Let's call this "empty". :-)

Can I see your docker-compose?
How do you monitor you mail server?

**Comment by tomav** [comment]
How many active users?

Are you sure `/var/mail` is (almost) empty?
You used `docker exec mail du -h /var/mail`?

**Comment by ttermeer-ouat** [comment]
> How many active users?

This happen on servers with no user and active users.

> You used docker exec mail du -h /var/mail?

I used du -h to check size

> How do you monitor you mail server?

Monitoring is mainly done by AWS CloudWatch. We do no monitor the mailing container in particular.
FYI, our setup is a multi-container environment and the mailing container is exclusively used to send confirmation and password reset mails.

> Can I see your docker-compose?

Here is part of the json for AWS Docker config ( Dockerrun.aws.json )

```
 {
      "volumesFrom": [],
      "memory": 305,
      "extraHosts": null,
      "dnsServers": [],
      "disableNetworking": null,
      "dnsSearchDomains": [],
      "portMappings": [
        {
          "hostPort": 143,
          "containerPort": 143,
          "protocol": "tcp"
        },
        {
          "hostPort": 587,
          "containerPort": 587,
          "protocol": "tcp"
        },
        {
          "hostPort": 993,
          "containerPort": 993,
          "protocol": "tcp"
        }
      ],
      "hostname": "mail.xxxxxxxxx.com",
      "essential": false,
      "entryPoint": [],
      "mountPoints": [            
        {
          "containerPath": "/tmp/docker-mailserver",
          "sourceVolume": "volume-2",
          "readOnly": false
        }
      ],
      "name": "xxxx_mail",
      "ulimits": null,
      "dockerSecurityOptions": [],
      "environment": [],
      "links": [],
      "workingDirectory": null,
      "readonlyRootFilesystem": false,
      "image": "tvial/docker-mailserver",
      "command": [],
      "user": null,
      "dockerLabels": {},
      "logConfiguration": null,
      "cpu": 0,
      "privileged": false
    }

**Comment by tomav** [comment]
How did you spot you mail container for this issue?
Is that a high trafic SMTP? Perhaps your log files?

**Comment by ttermeer-ouat** [comment]
We started to monitor Docker disk space usage and did some test by running a server without the mail container.

I joined below a graph showing free docker disk space from 4 different server. The red line is a server without the mail container.
![docker_space_free](https://cloud.githubusercontent.com/assets/16883817/21810928/fa37d64e-d74d-11e6-959c-af29dc861b0b.png)

I was suspecting log as well but the size increase is way too high. We don't have high traffic and the size increase happens at scheduled hours ( 6, 12 ,18 and midnight) and in a rather big size ( 200 MB )
We suspect some schedule cron job but couldn't find any in the mail container that was scheduled on a 6h delay.

**Comment by tomav** [comment]
```
root@mail:/# crontab -l
0 4 * * * find /var/lib/amavis/virusmails/ -type f -mtime +$VIRUSMAILS_DELETE_DELAY -delete
0 0,6,12,18 * * * /usr/bin/freshclam --quiet
```

**Comment by ttermeer-ouat** [comment]
Ah indeed didn't check crontab properly. So `/usr/bin/freshclam --quiet` seems to be the culprit here.

**Comment by tomav** [comment]
Hi @ttermeer-ouat, everything is ok?
Reopen if needed.

**Comment by ttermeer-ouat** [comment]
@tomav sorry forgot to update. With AWS help, we solved the issue just a few days ago. It seems to be a problem from docker that disable "online discard"
The solution taken was to run a crontab on the host that trim container's process

```
#!/bin/bash

for container in $(sudo docker ps -q);
do    container_pid=$(sudo docker inspect --format='{{.State.Pid}}' $container );
fstrim /proc/$container_pid/root;
done
```

**Comment by tomav** [comment]
Good to know, Thanks for the update @ttermeer-ouat!
