### ISSUE TITLE
Add ENABLE_AMAVIS env

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#465]
Follow-up of #386

**Comment by johansmitsnl** [comment]
@tomav what did you mean with this issue?

**Comment by tomav** [comment]
Find a way to disable Amavis :-) (and of course clamav)

**Comment by z3cka** [comment]
@tomav I think this can be done with [Environment Variables](https://github.com/tomav/docker-mailserver#environment-variables).

**Comment by Trumeet** [comment]
Same question, amavis uses lots of memory in my machine.

**Comment by erik-wramner** [comment]
As far as I can tell this very old issue is still relevant: Amavis should ideally be disabled when both clamd and spamassassin are disabled, possibly with a separate ENV variable.

**Comment by esikuriansky** [comment]
Hi all, 

Wanted to get your feedback on my approach to disabling amavis:
I disabled clamav and spamassasin via the env variables :
                -  ENABLE_CLAMAV=0, ENABLE_SPAMASSASIN=0  
And added the following line in postfix-main.cf: 
              content_filter=
It seems as if everything is running as expectedly but i am paranoid that i am shooting myself in the leg
Could this be the behaviour for ENABLE_AMAVIS=0 ?

**Comment by erik-wramner** [comment]
It sounds like a reasonable approach, but I don't know for sure. Other views?

**Comment by aendeavor** [comment]
@esikuriansky A lot of time has passed since Nov 2019. After #1605, could you try implementing the ENV variable `ENABLE_AMAVIS`. I see this the same way as @erik-wramner, this issue being old but still relevant.

**Comment by aendeavor** [comment]
I have marked this as frozen. This issue has stalled and is very old.

I'll close it in 10 days.

**Comment by Jip-Hop** [comment]
What is the recommended way to disable amavis currently?

I use docker-mailserver in my LAN as IMAP archive server (no receiving/sending of mail).
Just use it to manually move old mail over from my webhost (using a desktop email client).

I'm using these environment variables:

```
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/ssl/fullchain.pem
      - SSL_KEY_PATH=/tmp/ssl/privkey.pem
      - POSTFIX_MESSAGE_SIZE_LIMIT=102400000
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
```

I noticed `amavis` processes keep spawning:
`/usr/bin/perl -T /usr/sbin/amavisd-new foreground`

Can it be disabled when CLAMAV and SPAMASSASSIN are disabled? If so, how? Or is it still needed?

**Comment by casperklein** [comment]
There is no configuration option for that yet. You should be able to stop amavis with `supervisorctl stop amavis` (not tested).
If that works as expected (your setup is still functional), I can provide a patch.

**Comment by Jip-Hop** [comment]
I'll try! Do you recommend also to set `content_filter=` in postfix-main.cf?

**Comment by casperklein** [comment]
Probably that is needed. Just test it.

**Comment by Jip-Hop** [comment]
So far so good I'd say...
Shutdown container, added `content_filter=`, restarted. Then this:
```
root@mail:/# supervisorctl status amavis
amavis                           RUNNING   pid 8958, uptime 0:00:00
root@mail:/# supervisorctl stop amavis
amavis: stopped
root@mail:/# supervisorctl status amavis
amavis                           STOPPED   Mar 23 01:59 PM
```

Can still make new drafts, move messages, Roundcube is working. Didn't see the amavis process in the process list. So still functional :) What would be the patch you mentioned?

**Comment by casperklein** [comment]
> What would be the patch you mentioned?

Making a ENV `ENABLE_AMAVIS=0` available, to conditionally start/stop AMAVIS on container start. And if not enabled, set `content_filter=`.

If you like to contribute that, I wouldn't be angry 😄

**Comment by casperklein** [comment]
fyi: This feature will be available in the next release.
