### ISSUE TITLE
2 errors, unable to login

### ISSUE THREAD

**Issue by actusmedia** [tomav/docker-mailserver#466]
First thank you for creating this container.
I have 2 problems with the docker container.
After I login the container and cat the /var/log/mail/mail.log I get these errors;

x= removed ip data
```
Jan 10 15:55:53 mail postfix/smtpd[1365]: connect from x[x]
Jan 10 15:55:53 mail postfix/smtpd[1365]: warning: connect to Milter service inet:localhost:8891: Connection refused
Jan 10 15:55:53 mail postfix/smtpd[1365]: SSL_accept error from x[x]: lost connection
Jan 10 15:55:53 mail postfix/smtpd[1365]: lost connection after STARTTLS from x[x]
Jan 10 15:55:53 mail postfix/smtpd[1365]: disconnect from x [x]
Jan 10 15:55:53 mail postfix/smtpd[1365]: connect from x [x]
Jan 10 15:55:53 mail postfix/smtpd[1365]: warning: connect to Milter service inet:localhost:8891: Connection refused
Jan 10 15:55:53 mail postfix/smtpd[1365]: SSL_accept error from x[x]: lost connection
Jan 10 15:55:53 mail postfix/smtpd[1365]: lost connection after STARTTLS from x[x]
Jan 10 15:55:53 mail postfix/smtpd[1365]: disconnect from x[x]
```

I have run the DKIM command, created 1 mailbox, The errors appear right after trying to connect to the mail server. I get an unable to login error, under the hood, these errors are written to the log.

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.1
    hostname: mail
    domainname: my.ltd
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/opt/mailserver/
    - letsencrypt:/tmp/letsencrypt
    - /etc/localtime:/etc/localtime:ro
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=1
    #- SSL_TYPE=
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  letsencrypt:
    driver: local
```

**Comment by tomav** [comment]
Hi @actusmedia, thanks for your message.
DKIM is probably not running. [This](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#common-errors) may help.

Let me know if it worked or not.

**Comment by actusmedia** [comment]
Hi Tomav,

Running /etc/init.d/opendkim restart on the host or inside the docker container? This is not explicit mentioned. Thank you

**Comment by tomav** [comment]
This won't work
```
- ./config/:/opt/mailserver/
```

https://github.com/tomav/docker-mailserver#create-a-docker-composeyml

**Comment by tomav** [comment]
Fix the config path, must be /tmp. (cf. link above).
Everything should start normally when config are provided.

**Comment by actusmedia** [comment]
Totally missed that, excuse.

Im still getting errors after exactly following the documentation with the example docker-compose.yml
I only added ssl letsencrypt option and also added It under volumes.

```
Jan 10 16:15:47 mail postfix/smtpd[1352]: warning: connect to Milter service inet:localhost:8891: Connection refused
Jan 10 16:15:47 mail dovecot: auth: passwd-file(info@recruithero.nl,85.148.49.205): Password mismatch (SHA1 of given password: eec71d)
Jan 10 16:15:49 mail postfix/smtpd[1352]: warning: s559431cd.adsl.online.nl[85.148.49.205]: SASL PLAIN authentication failed:
Jan 10 16:15:55 mail postfix/smtpd[1352]: warning: s559431cd.adsl.online.nl[85.148.49.205]: SASL PLAIN authentication failed:
Jan 10 16:16:01 mail postfix/smtpd[1352]: warning: s559431cd.adsl.online.nl[85.148.49.205]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
```
Jan 10 16:15:47 mail postfix/smtpd[1352]: warning: connect to Milter service inet:localhost:8891: Connection refused
Jan 10 16:15:47 mail dovecot: auth: passwd-file(my@my.ltd,myip): Password mismatch (SHA1 of given password: eec71d)
Jan 10 16:16:01 mail postfix/smtpd[1352]: warning: : SASL LOGIN authentication failed: UGFzc3dvcmQ6
```

Any thoughts why this happens? 
I do not should run DKIM manually every time right? The container should start it

**Comment by tomav** [comment]
It should work out of the box. DKIM is running?
Could you start the container with `DMS_DEBUG=1` and paste the output?

**Comment by tomav** [comment]
@actusmedia reopen if needed. 
Closed due to inactivity.
