### ISSUE TITLE
SASL LOGIN authentication failed

### ISSUE THREAD

**Issue by sisso19** [tomav/docker-mailserver#47]
Hello

I am not sure if this is the same issue as https://github.com/tomav/docker-mailserver/issues/18 but Im going to report this anyways

So I am trying to set up gitlab docker containers to use this magnificent mailserver but I am unable to connect to the server.

The error that i am getting is

    Dec 31 14:10:39 mail postfix/submission/smtpd[591]: connect from unknown[172.17.0.6]
    Dec 31 14:10:39 mail postfix/submission/smtpd[591]: warning: SASL authentication failure: Couldn't find mech LOGIN
    Dec 31 14:10:39 mail postfix/submission/smtpd[591]: warning: unknown[172.17.0.6]: SASL LOGIN authentication failed: no mechanism available
    Dec 31 14:10:39 mail postfix/submission/smtpd[591]: lost connection after AUTH from unknown[172.17.0.6]
    Dec 31 14:10:39 mail postfix/submission/smtpd[591]: disconnect from unknown[172.17.0.6]

I am able to connect to the mail server and use it with a python script but not with gitlab.
The gitlab compose offers environment variables which are and set to:

    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

Is this a issue with the mailServer or gitlab it self?

**Comment by tomav** [comment]
Hi @sisso19, try to configure `MD5` instead of `LOGIN` mech on your client.
Currently it's not supported.
https://github.com/tomav/docker-mailserver/blob/master/postfix/sasl/smtpd.conf#L2

**Comment by tomav** [comment]
@sisso19 could you confirm that it is ok for you and close this issue? Thank you.

**Comment by sisso19** [comment]
@tomav, I have not been able to get this working.
There seems to be an issue with my gitlab configuration as well because the only time I am able to get a connection to the mail server it is only with "login", "plain" and "anonymous". login and plain profuce no maching mech but the anonymous seems not to work for gmail:

    Jan  9 12:47:06 mail postfix/submission/smtpd[608]: NOQUEUE: reject: RCPT from unknown[ip]: 554 5.7.1 <unknown[ip]>: Client host rejected: Access denied; from=<notifications@example.com> to=<mygmailmail@gmail.com> proto=ESMTP helo=<mail>

But anonymous is not what I want so no point in looking into that one.

I tried both digest-md5 cram-md5 but when they were configured, gitlab never sent a a request to the mail server. 

Do you have any recommendation for me what I should do next?
I also would be happy to contribute to this project with a PR by adding some authorization to be able to get this working. I am a software developer my self but I have never contributed to a open source project yet

**Comment by tomav** [comment]
You can do a PR and we'll add `login` and `plain`.

**Comment by sisso19** [comment]
@tomav, regarding your offering of help from the other issue. I have come to the conclusion that it will be greatly needed.
I have been reading about postfix and reading through this site: http://www.postfix.org/SASL_README.html

I thought that the change that I needed to do was in the smtpd.conf file. Currently my smtpd.conf file looks like this:

    pwcheck_method: auxprop
    auxprop_plugin: sasldb
    mech_list: plain login cram-md5 digest-md5
    log_level: 7

But I dont get the authorization that I want. When I try to use telnet for testing It never shows me what authentications are available. I also removed the no noplaintext from the smtpd_sasl_security_options in the main.cf file.

This has currently got me nowhere and I feel like I am only scraping the surface of mail servers in general.

Do you have any recommendations for me?

**Comment by tomav** [comment]
@sisso19 can you try this branch? https://github.com/tomav/docker-mailserver/pull/50

**Comment by sisso19** [comment]
Perfect. It worked on the first try. Thanks a million! :)

**Comment by tomav** [comment]
Great!
