### ISSUE TITLE
OpenDKIM Sign Headers

### ISSUE THREAD

**Issue by ifokeev** [tomav/docker-mailserver#470]
Hello. There is the problem with Amazon SES (if you use manual dkim) – it wants you not to sign:
* Message-ID
* Date
* Return-Path
* Bounces-To

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/manual-dkim.html

By default opendkim signs ``h=List-ID:From:To:Subject:List-Unsubscribe:Date;``.

So maybe there should be the way to override opendkim.conf if it exists or put only allowed headers to ``SignHeaders`` and ``OversignHeaders`` by default?

**Comment by tomav** [comment]
Yep, doable. Want to contribute to the project? I'll guide you if necessary.

**Comment by ifokeev** [comment]
@tomav
should I change start-mailserver.sh or some other way?

**Comment by tomav** [comment]
Perhaps the first thing to tests is mounting a dkim config folder with the modification you want.
It may work out the box.

**Comment by ifokeev** [comment]
you mean try to mount 
./config/opendkim.conf:/etc/opendkim.conf
?

**Comment by tomav** [comment]
Yep. Or the whole directory.

**Comment by ifokeev** [comment]
```
function _setup_dkim() {
	notify 'task' 'Setting up DKIM'

	mkdir -p /etc/opendkim && touch /etc/opendkim/SigningTable

	# Check if keys are already available
	if [ -e "/tmp/docker-mailserver/opendkim/KeyTable" ]; then
		cp -a /tmp/docker-mailserver/opendkim/* /etc/opendkim/
		notify 'inf' "DKIM keys added for: `ls -C /etc/opendkim/keys/`"
		notify 'inf' "Changing permissions on /etc/opendkim"
		chown -R opendkim:opendkim /etc/opendkim/
		# And make sure permissions are right
		chmod -R 0700 /etc/opendkim/keys/
	else
		notify 'warn' "No DKIM key provided. Check the documentation to find how to get your keys."
	fi
}
```

but it won't work with the entire directory because opendkim.conf location is /etc/opendkim.conf

**Comment by ifokeev** [comment]
It works with this opendkim.conf

```
AutoRestart             Yes
AutoRestartRate         10/1h
UMask                   002
Syslog                  yes
SyslogSuccess           Yes
LogWhy                  Yes
RemoveOldSignatures     Yes

Canonicalization        relaxed/simple

ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
InternalHosts           refile:/etc/opendkim/TrustedHosts
KeyTable                refile:/etc/opendkim/KeyTable
SigningTable            refile:/etc/opendkim/SigningTable

Mode                    sv
PidFile                 /var/run/opendkim/opendkim.pid
SignatureAlgorithm      rsa-sha256

UserID                  opendkim:opendkim

Socket                  inet:8891@localhost
OmitHeaders             Message-ID, Date, Return-Path, Bounces-To, Received, Comments, Keywords, Bcc, Resent-Bcc, DKIM-Signature
```

**Comment by tomav** [comment]
You just added the last line to make it work?

**Comment by ifokeev** [comment]
@tomav Yes. Now I have DKIM pass and DMARK pass via my manual DKIM setup.

**Comment by tomav** [comment]
Great! Good to know. I let you close the issue if everything is ok.

**Comment by ifokeev** [comment]
Will we add this to the default conf file? Or we need to notice it in the wiki

**Comment by tomav** [comment]
I don't know what may be the impact for existing users out of AWS. If the answer is none, yes we can. Any thought?

**Comment by ifokeev** [comment]
It will not affect on any users because we just removed ``Date`` from signed headers. 
OpenDKIM need to sign headers because SMTP can modify headers and that's only the verification. In the standard there is just ``From`` header is really MUST be present. 

RFC6376 section 5.4: https://tools.ietf.org/html/rfc6376#section-5.4

My opinion is that only ```From, To, Subject``` should be signed.

**Comment by tomav** [comment]
I'm gonna try on my instance. If its ok, I'll let you add this to the project as your first PR. Ok?

**Comment by ifokeev** [comment]
Maybe it's not so popular case so that's better just to notice that issue and configuration in the wiki =\

**Comment by ifokeev** [comment]
@tomav Ok

**Comment by tomav** [comment]
Tested to gmail.com and another domain hosted on office365 pro, it works! You can add it to https://github.com/tomav/docker-mailserver/blob/master/target/opendkim/opendkim.conf

**Comment by tomav** [comment]
Merged!
