### ISSUE TITLE
High Spam Volume: What do others do?

### ISSUE THREAD

**Issue by theomega** [tomav/docker-mailserver#473]
I replaced my custom postfix mailserver with this mailserver when I switched hosting providers.
Since the switch, I'm running into a lot more spam problems than before. Now my setup is not really comparable. Previously, I used to run postfix + policyd_weight + spamassasin which filtered out nearly everything. Now I have dozen of (untagged) spam messages in my inbox.

What I already did:
```
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - SA_TAG=-10000.0
    - SA_TAG2=5
    - SA_KILL=1000
```

This tags all messages, so one can see the spamassasin score of the spam. I also lowered the TAG2 threshold to 5. I have a high SA_KILL because I wanted to filter out the spam and not kill it.

I also have a regular cron-job running which feeds the not detected spam into `sa-learn`. 

I'm not running a high profile domain here, so my question is: What do other peoples do when using this docker image? Are there any interesting spamassassin rules which work well?

I though about adding postgrey (which seems straight forward), but I suspect I'll run into problems with the testing of this docker image.

Any recommendations / best practices?

Example Spamassasin-Reports:
```
X-Spam-Status: No, score=1.645 tagged_above=-10000 required=5
	tests=[HTML_IMAGE_ONLY_04=0.342, HTML_MESSAGE=0.001,
	HTML_SHORT_LINK_IMG_1=0.139, MPART_ALT_DIFF=0.724, PYZOR_CHECK=1.985,
	RCVD_IN_BRBL_LASTEXT=1.644, RCVD_IN_MSPIKE_BL=0.01,
	RCVD_IN_MSPIKE_L3=0.001, RP_MATCHES_RCVD=-3.199, SPF_HELO_PASS=-0.001,
	SPF_PASS=-0.001] autolearn=no autolearn_force=no
```

```
X-Spam-Status: No, score=1.986 tagged_above=-10000 required=5
	tests=[HTML_MESSAGE=0.001, PYZOR_CHECK=1.985]
	autolearn=no autolearn_force=no
```

**Comment by tomav** [comment]
I do almost the same, tagging everything but I kill spam from 5 and above.
If your server is quite new, it is probably learning with `sa-learn`. I know you're using `ONE_DIR=1` so data is kept and updated so it will be better and better.

Postgrey is clearly another good option, I created an issue for that, if you want to contribute. https://github.com/tomav/docker-mailserver/issues/255

I only added custom rules once, but never had to do it since, except blacklisting some sender via `blacklist_from *@spamer.tld`.

Let's see what other say.

**Comment by tomav** [comment]
By the way, what do you mean by "high volume"?

**Comment by theomega** [comment]
25 detected Spam + 40 undetected Spam + 10 real emails.
So relative high volume.

**Comment by tomav** [comment]
Hi @theomega, any improvement on spam detection?

**Comment by theomega** [comment]
No, but I have a question: On my old mail server, I had the bayes filtering in spamassasin turned on somehow. This gave a spam-proability score to each email which was quiet accurate.

For example see the header (for a ham-mail) from the old server:

```
X-Spam-Report: 
	* -0.0 T_RP_MATCHES_RCVD Envelope sender domain matches handover relay
	*      domain
	*  0.0 HTML_IMAGE_RATIO_06 BODY: HTML has a low ratio of text to image area
	* -1.9 BAYES_00 BODY: Bayes spam probability is 0 to 1%
	*      [score: 0.0000]
	*  0.0 HTML_MESSAGE BODY: HTML included in message
	*  0.7 MIME_HTML_ONLY BODY: Message only has text/html MIME parts
	* -5.0 RCVD_IN_DNSWL_HI RBL: Sender listed at http://www.dnswl.org/, high
	*      trust
	*      [193.41.132.132 listed in list.dnswl.org]
	*  1.4 MISSING_DATE Missing Date: header
	*  0.7 OBFUSCATING_COMMENT HTML comments which obfuscate text
```

The `BAYES_00` is part of the bayes filter. I don't have any old spam anymore, but that check was definitely helpful.

On my new server, I don't see these checks running. Does anyone know how to enable this?

**Comment by tomav** [comment]
[This](https://github.com/tomav/docker-mailserver/issues/365) may help.

**Comment by theomega** [comment]
I saw this: I'm learning my spam with the correct database, this is not the issue. My `/root/.spamassasin` is empty, but:

```
/var/lib/amavis/.spamassassin# ls -lah
total 2.2M
drwx------ 2 amavis amavis 4.0K Jan 19 20:39 .
drwxr-x--- 8 amavis amavis 4.0K Jan 19 07:21 ..
-rw------- 1 amavis amavis  12K Jan 11 23:01 auto-whitelist
-rw------- 1 amavis amavis 152K Jan 19 20:39 bayes_seen
-rw------- 1 amavis amavis 2.5M Jan 19 20:39 bayes_toks

```

So the bayes system seems to be at least party enabled, otherwise, there would be no `bayes_toks`. These could also only be from the learning. So maybe I'm only learning the mails but the filtering on it is not enabled. This would explain why the rule is missing in the header

**Comment by theomega** [comment]
I just tried to force spamassasin to enable the bayes filtering, by adding to `config/spamassassin-rules.cf`:
```
use_bayes       1
bayes_path 	/var/lib/amavis/.spamassassin/bayes
bayes_file_mode 077
```

But this doesn't change anything.

**Comment by theomega** [comment]
I just read somewhere, that the bayes filtering only starts if you added 200 spam and 200 ham mails to it. I need to check if I'm above these limits already.

**Comment by theomega** [comment]
Ok, that fixed it. Maybe we should add this to the docs somewhere. Although most people would not notice.

**Comment by tomav** [comment]
Yep add it to the Wiki: https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-make-spamassassin-learn-spam

This can be closed?

**Comment by theomega** [comment]
Updated the wiki, lets close this for now, the Bayes might really make some difference. I'll try to get my old bayes database out of the old mailserver and reuse it.

**Comment by tomav** [comment]
`ONE_DIR=1` may help to backup states.

**Comment by theomega** [comment]
I have that already, isn't that even a default?

**Comment by tomav** [comment]
Nop.
