### ISSUE TITLE
This might be a naive question, but how does one use this to send an email (from the command line)?

### ISSUE THREAD

**Issue by cavaunpeu** [tomav/docker-mailserver#476]

**Comment by theomega** [comment]
This docker image is not a perfect choice if you just require the possibility to send emails. For this use-case you only need a MTA (SMTP server).
In contrast this docker image bundles an MTA (SMTP Server, postfix) with a mail storage (Dovecot) and a lot of additional tooling for managing users, spam detection and so on.

If you still want to stay with this docker image, you have three choices:
1. If you are inside the docker-container, the `sendmail` command can be used to send emails.
2. If you are outside the docker-conainer, you need some kind of smtp client. I can suggest `mutt` or `msmtp` for this.
3. For trying out and experimenting, you can also just use `telnet` and manually execute the SMTP protocol. There are many websites explaning this, [this one](http://www.yuki-onna.co.uk/email/smtp.html) for example

**Comment by cavaunpeu** [comment]
Thanks @theomega!
