### ISSUE TITLE
Restore Emails From Manual Backup?

### ISSUE THREAD

**Issue by dodekeract** [tomav/docker-mailserver#477]
I just accidentally deleted nearly all emails from one particular sending address (failed spam deletion rule...). Fortunately the most recent ones are still there and I made a backup about a week ago.

The backup I made was essentially just a `cp -r` on the folders used by `docker-mailserver`. It seems to contain all emails.

Now I'm just wondering how I can merge them back into my inbox. Any ideas? I really need them as they contain invoices that I can exclude from tax. 😢

A non-manual way would be highly appreciated, as I have far too many emails.

Thanks for the help in advance, hope this isn't the wrong place to ask.

**Comment by theomega** [comment]
What speaks against just copying the files back? The IMAP server will automatically recompute its index, no need to even restart. As every mail is in its own file, you are not risking overwriting anything.

**Comment by dodekeract** [comment]
@theomega You mean simply `cp -r backup original` should work? That'd be nice. I'll make another backup first and try this. Sucks a bit that this will also restore other deleted mails, but whatever - that's not that much of a hassle to re-delete them.

**Comment by tomav** [comment]
And think about permissions. `/var/mail` should be owned by `docker:docker`

**Comment by dodekeract** [comment]
I'll mark it as closed for now. Don't have a lot of time this week to test it. Will re-open if needed.

**Comment by citec** [comment]
Be careful with this: if you copy your files back, and, from your original copy to now the users moved emails in some imap folders, then they would have duplicated emails in different folders.

Example:

1 - Monday: you do the backup
2 - Tuesday: a user move one email from Inbox to Archive imap folder
3 - Wednesday: you restore backup by copying back all files the project
4 - Then your user has two copies of the same email, one in Inbox and one in Archive

**Comment by dodekeract** [comment]
@citec anything I can do to avoid that issue?
