### ISSUE TITLE
Set kibana/elasticsearch data as mounted volume

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#482]
I think it would be better to put kibana and elasticsearch data folders in a volume container, so we can backup/restore it and not loose it when the container is gone

**Comment by tomav** [comment]
Could you provide a PR/documentation for that?
Note that it also relate to the missing documentation : https://github.com/tomav/docker-mailserver/issues/337

**Comment by citec** [comment]
OK, I will try to figure out how to do it, as I don't know where/how elasticsearch or kibana store its data.

**Comment by johansmitsnl** [comment]
@citec any news on the PR or a solution?

**Comment by erik-wramner** [comment]
I'll close this as there has been no answer since 2017. As for the problem itself I would suggest using the official Kibana/Elastic images that are actively maintained and well documented, perhaps with the container in this project as an example for how to configure it.
