### ISSUE TITLE
Recipient address rejected: User unknown in virtual mailbox table

### ISSUE THREAD

**Issue by AndrewMoneronGenex** [tomav/docker-mailserver#485]
Hi 

Getting the above error when trying to send mail through the smtp server:

If I send to bob@myhost.co.za, I get the error.... How do I get it to route a anything at myhost.co.za to the correct mail servers.

I can send to xyz@gmail.com perfectly fine.

I also tried SMTP only option by SMTP stopped working all together.

```
docker run -d --hostname mail.myhost.co.za \
--name mail -p 25:25 -p 143:143 -p 587:587 -p 993:993 \
-v /media/andrew/storage/mailserver/maildata:/var/mail \
-v /media/andrew/storage/mailserver/mailstate:/var/mail-state \
-v /media/andrew/storage/mailserver/config:/tmp/docker-mailserver/  \
-e ENABLE_SPAMASSASSIN=0 \
-e ENABLE_CLAMAV=0 \
-e ENABLE_FAIL2BAN=0 \
-e ONE_DIR=1 \
-e DMS_DEBUG=1 \
-e PERMIT_DOCKER=network \
--cap-add NET_ADMIN tvial/docker-mailserver
```

Regards,
Andrew

**Comment by thiesschneider** [comment]
Do you authenticate with user and password in the SMTP settings?

**Comment by AndrewMoneronGenex** [comment]
No Authentication....

Basically my needs are just and SMTP Server with DKIM setup.

**Comment by thiesschneider** [comment]
you need to authenticate with smtp in the smtp settings

**Comment by tomav** [comment]
Hi @AndrewMoneronGenex, could post info requested in [CONTRIBUTING.md](https://github.com/tomav/docker-mailserver/blob/master/CONTRIBUTING.md#open-an-issue)?

Have you created the user?

Thanks.

**Comment by tomav** [comment]
Closed due to inactivity.
Reopen if needed.
