### ISSUE TITLE
setup.sh should be built-in in the image

### ISSUE THREAD

**Issue by dragonito** [tomav/docker-mailserver#486]
Hi there,

i made a helper script for adding, perhaps someone needs it. You have to connect to the shell of the docker image (im using rancher). I just made an mailadd.sh file in root folder (chmod +x) with following content:

```
#!/bin/bash

$MAIL_USER=$1
$MAIL_PASS=$2

echo "$1|$(doveadm pw -s SHA512-CRYPT -u $1 -p $2)" >> ./tmp/docker-mailserver/postfix-accounts.cf
```

With
`
./mailadd.sh xxxx@xxxx.xx somepassword
`
you kann add the users.

Cu

Robin

**Comment by theomega** [comment]
There is already a script doing this. See the README.md where it is linked or [here](https://github.com/tomav/docker-mailserver/blob/master/setup.sh). Is there any improvement on this script? If yes, we should merge them.

**Comment by tomav** [comment]
Hi @dragonito, thanks for the tip.
We also have something similar: https://github.com/tomav/docker-mailserver/tree/master/target/bin

**Comment by dragonito** [comment]
Ahh great!! Is this directly available in docker image?

**Comment by tomav** [comment]
Not yet I think, but it should. The `Dockerfile` should be updated.

**Comment by tomav** [comment]
I'm gonna rewrite your issue title to get this script in default image.

**Comment by tomav** [comment]
This script has finally to be used outside of the docker image.
I'm gonna let it where it is.
