### ISSUE TITLE
Mounting volumes does not change container files

### ISSUE THREAD

**Issue by sisso19** [tomav/docker-mailserver#49]
I am playing around with the postfix folder and trying to change sasl/smtpd.conf file but the files in the container are not loaded to the /etc/postfix folder.

In the readme.md there is noted that all folders (expect letsencrypt) need to be mounted to the tmp folder.

> files must be mounted to /tmp in your container 

To make changes I need to rebuild the image with the changed code in the git project folder

my docker-compose file:

    mail:
      restart: always
      #image: tvial/docker-mailserver
      build: ./docker-mailserver
      hostname: mail
      domainname: host.com
      ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      volumes:
      - ./spamassassin:/tmp/spamassassin/
      - ./postfix:/tmp/postfix/
      - /etc/letsencrypt:/etc/letsencrypt
      environment:
      - DMS_SSL=letsencrypt

**Comment by tomav** [comment]
You don't need to rebuild, but restart the container.
Some files are generated at startup.
You should have a look to https://github.com/tomav/docker-mailserver/blob/master/start-mailserver.sh to understand how it works.

I use git to pull new configuration and then I `docker-compose up -d mail` to restart it using the new config.

**Comment by sisso19** [comment]
Ahh I see. I thought the start-mailserver.sh was a part of the image it self. I'll have a look at it.
Thank you

**Comment by tomav** [comment]
Let me know if I can help.
