### ISSUE TITLE
Failed build on Docker Hub for 2.1 tag

### ISSUE THREAD

**Issue by tyranron** [tomav/docker-mailserver#493]
@tomav would you be so kind to re-run build on Docker Hub for `2.1` tag? It failed [due to temporary gpg key retrieving problems](https://travis-ci.org/tomav/docker-mailserver/builds/195169499#L1274).

**Comment by tomav** [comment]
Restarted!

**Comment by tyranron** [comment]
Thanks!

**Comment by tomav** [comment]
Success
2.1
14 minutes ago
