### ISSUE TITLE
Setup issues with readme instructions 

### ISSUE THREAD

**Issue by quarterbit** [tomav/docker-mailserver#497]
I installe docker and try to follow the readme but as a beginner to docker I am totally lost by this in the readme: 

_Your configs must be mounted in /tmp/docker-mailserver/. To understand how things work on boot, please have a look to start-mailserver.sh_
I looked into the start-mailserver.sh file but that does not really help me. There is one step which may be obvious but I can't figure it out after watching tutorials.. 
Please help me.
 Do I have to cloe this repo so that the config files land in /tmp/docker-mailserver ?

**Comment by tomav** [comment]
Hi @quarterbit, you need Docker knowledge to use this image, especially `docker-compose`.
If you follow the provided example, the config will be mounted at the right place.
To help you, we need to know what kind of error you're experiencing (logs may help) and your config.

**Comment by quarterbit** [comment]
Hi tomav, thank you. I am running ubuntu14 on a hetzner vSever. Installed now docker, docker-compose and have the docker mailserver running. seem it runs as I see in the logs with 
./setup.sh debug show-mail-logs the server is up. 
It just took my a while to figure out that the docker container reaches out of it's own space into /tmp/docker-mailserver/

**Comment by quarterbit** [comment]
at the point in the readme the link to a good docker tutorial would be good. I went now tough several including some really bad or misleading youtube videos.

**Comment by quarterbit** [comment]
I start understanding this docker thing a bit better... still not fully. 
I'll continue on my own for a while... Thanks

**Comment by tomav** [comment]
Hi @quarterbit, any update on that?
