### ISSUE TITLE
Warning when configuring mail server

### ISSUE THREAD

**Issue by Holt59** [tomav/docker-mailserver#499]
I have set up your mail server with a LDAP configuration, and each time I restart it I get the following warning (error?):

```
Configuring mail server
  * 'config/docker-mailserver/postfix-accounts.cf' is not provided. No mail account created.
/usr/local/bin/start-mailserver.sh: line 489: [: argument expected
```

I tried to look at the line 489:
```
$ sed '489q;d' /usr/local/bin/start-mailserver.sh
	[ "$SASLAUTHD_MECHANISMS" = ldap -a -z $SASLAUTHD_LDAP_SEARCH_BASE ] && SASLAUTHD_MECHANISMS=pam
```

I have set `SASLAUTHD_MECHANISMS` to `rimap`.

This does not prevent the mail server from working, but it bothers me a bit...

**Comment by tomav** [comment]
Perhaps @weo, @tyranron or @alinmear may help.

**Comment by weo** [comment]
There are quotes missing around $SASLAUTHD_LDAP_SEARCH_BASE. I'm preparing a pull request ...
