### ISSUE TITLE
opendmarc crashes when no From field is specified

### ISSUE THREAD

**Issue by 42wim** [tomav/docker-mailserver#500]
Got bitten by this bug when testing the server using telnet.

See https://bugs.launchpad.net/ubuntu/+source/opendmarc/+bug/1574562
I fixed this on my (stripped down) version by using ubuntu 16.04 LTS which has newer opendmarc.

**Comment by tomav** [comment]
Upgrading to 16.04 could be a nice PR 😄

**Comment by tomav** [comment]
@42wim do you want to participate?

**Comment by 42wim** [comment]
Sorry, I don't have the time right now, maybe in a couple of weeks

**Comment by johansmitsnl** [comment]
It is merged and it state that it fixed this issue.
Closing it.
