### ISSUE TITLE
Fail2Ban blocking IPs which should not get blocked.

### ISSUE THREAD

**Issue by jcgruenhage** [tomav/docker-mailserver#501]
Evolution, Rainloop, and K9-Mail won't connect to my mail server, each of them tell me that they can not reach the server. A look in the logs reveals that some Ukrainian IPs repetitively try to login (this started today in the morning). However, I am not able to log in from my own machine now either.

Workaround: Deleting `mailstate/lib-fail2ban` and restarting the server.

docker logs mail: https://gist.github.com/jcgruenhage/a4f3e53a8a633523b89dddbdd9d5beb1

As you can see in the log, fail2ban can clearly see which ones are the bad IPs, and as they vary, blocking them one by one is not an option, but blocking everything is clearly not an option either.

**Comment by tomav** [comment]
Hi @jcgruenhage, perhaps you should whitelist some IPs in Fail2ban or disable it if it does not match your needs. Note that logs are temporary.
What do you suggest?

**Comment by jcgruenhage** [comment]
I do not exactly have a proposal, but it seemed that fail2ban blocked my IP even though I did not have any failed login attempts, not that I would not like my IP to get blocked if I did have had failed attempts.

Since this only occured once though and I can not reproduce it, I'll close this anyway.
