### ISSUE TITLE
Postfix LDAP - Add logic to provide custom configs at /tmp/docker-mailserver/ and Add global variable to specify the query_filter

### ISSUE THREAD

**Issue by alinmear** [tomav/docker-mailserver#503]
Right now we have no chance to specify the query_filter within the ldap-{user,aliases,group}.conf at /etc/postfix. I don't know why we missed to implement that. I would work on it.

I would suggest the following logic:
- Check whether config is provided or not and copy them in place
- Check whether global variables have been specified and substitute

**Comment by alinmear** [comment]
Ok, i investigated this a little bit. While restructuring the start-mailserver.sh an important part has been dropped (not on purpose):

for i in 'users' 'groups' 'aliases'; do
    **fpath="/tmp/docker-mailserver/postfix-ldap-${i}.cf"**
    **if [ -f $fpath ]; then**
        **cp ${fpath} /etc/postfix/ldap-${i}.cf**
        sed -i -e 's|^server_host.*|server_host = '${LDAP_SERVER_HOST}'|g' \                                                                                                                  
               -e 's|^search_base.*|search_base = '${LDAP_SEARCH_BASE}'|g' \
               -e 's|^bind_dn.*|bind_dn = '${LDAP_BIND_DN}'|g' \
               -e 's|^bind_pw.*|bind_pw = '${LDAP_BIND_PW}'|g' \
               /etc/postfix/ldap-${i}.cf
    else
        echo "${fpath} not found"
        echo "==> Warning: 'config/postfix-ldap-$i.cf' is not provided."
    fi  
done

**Comment by tomav** [comment]
Thanks for the feedback @alinmear, we should add more tests and doc on LDAP.
It currently seems to bring new users to the project but we're not accurate and it's still not totally plug and play.

**Comment by tomav** [comment]
@alinmear, could you submit a PR for that?

**Comment by alinmear** [comment]
yes, will. had no time so far. I will do my best, to make a pr!
