### ISSUE TITLE
Dummy Question: load balancing docker-mailserver

### ISSUE THREAD

**Issue by bilak** [tomav/docker-mailserver#51]
Hello,
this is dummy question, but it can be helpful for someone like me. I don't know much about docker even about postfix, but if I would like to install your image(s) is there way how to create some load balancing between them?

what about balancing on same host (one linux machine) and what about balancing on many hosts (many linux machines)

Thanks in advance.

**Comment by tomav** [comment]
You can use DNS to balance, using MX priority ti balance on multiple IPs.
Otherwise you have to put a load balancer in front of your mail servers but I won't be able to help you on this, sorry.
