### ISSUE TITLE
How to add vhost domain aliases using config script

### ISSUE THREAD

**Issue by techgourmet** [tomav/docker-mailserver#512]
Hi,
Can you modify the setup script so it will also read a vhost file ext to the vmailbox and virtual files?
I'd like to be able to use this docker images for multiple domains without losing the config every time I restart the container.

Thnx in advance.

**Comment by tomav** [comment]
Hi @techgourmet, "setup script" is `setup.sh`?
You can provide a user account list and a virtuals list. They are used on startup to configure the container, they're not lost.
https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts
https://github.com/tomav/docker-mailserver/wiki/Configure-Aliases

**Comment by techgourmet** [comment]
I'd like to add a similar for domains the mailserver will respond to.
a Config-Vhosts via a file in the configuration directory.

**Comment by animator013** [comment]
+1

**Comment by techgourmet** [comment]
Nevermind, this is working now using the postfix-virtual.cf and the postfix-accounts.cf
Didn't expect that but it's working well :)

**Comment by tomav** [comment]
Great!
