### ISSUE TITLE
How to create a catch-all domain? And non-plaintext login

### ISSUE THREAD

**Issue by jonbaldie** [tomav/docker-mailserver#516]
Hi there, I have two questions.

1) On my manual Postfix server with Dovecot and and Procmail, I was able to specify Postfix accounts using the Postfix variable `virtual_alias_domains` pointing to a file called `/etc/postfix/address` which was like:

```
email.com DOMAIN
@email.com jon
```

I would then use `postmap /etc/postfix/address` and reload the service, which would mean all email addresses @email.com would then get routed to my user's mail folder on the server.

Is this possible with your project?

2) I have noticed in the logs that all IMAP logins are in plaintext. I have followed your instructions in the README.md to add new Postfix accounts to `config/postfix-accounts.cf` but how do I enforce encrypted authentications?

**Comment by flole** [comment]
You can create an catch-all account by adding the following to `config/postfix-virtual.cf`:
```
@domain.tld user@domain.tld
```

**Comment by jonbaldie** [comment]
Thanks @flole, I'll give that a try.

**Comment by flole** [comment]
One addition:
In order to receive mails for other users you have to add an entry to `config/postfix-virtual.cf` for each user. So your `postfix-virtual.cf` will look like this:
```
user@domain.tld user@domain.tld
user2@domain.tld user2@domain.tld
@domain.tld user@domain.tld
```

**Comment by jonbaldie** [comment]
Thanks @flole. Do you also know how to enforce encrypted authentication? According the logs my logins are always plaintext, even when I try to specify SSL/TLS from the client end.

**Comment by flole** [comment]
In this image is the TLS logging level only activated for outgoing smtp connection.
You can enable TLS logging for incoming TLS connection by raising the following commands within your docker container:
```
postconf -e "smtpd_tls_loglevel = 1"
postfix reload
tail -f /var/log/mail/mail.log
```

If you send a mail after executing this commands you should find something like this:
```
Feb  9 20:45:02 <my server> postfix/submission/smtpd[2742]: connect from <my ip>
Feb  9 20:45:02 <my server> postfix/submission/smtpd[2742]: Anonymous TLS connection established from <my host>: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Feb  9 20:45:02 <my server> postfix/submission/smtpd[2742]: C683720F0A6: client=<my host>, sasl_method=PLAIN, sasl_username=<my mail>
```


You can also add `smtpd_tls_loglevel = 1` in `config/postfix-main.cf` to keep the TLS logging activated during container restarts.

**Comment by flole** [comment]
I just read that you are asking about unencrypted IMAP logins.

Your password should be sent as plaintext through an encrypted TLS tunnel. You can check that by looking at the dovecot imap-login line in your mail logs.
```
Feb  9 20:45:03 <my server> dovecot: imap-login: Login: user=<my mail>, method=PLAIN, <some IPs> , mpid=2753, TLS, session=<[your session id]>
```


According [this](http://wiki2.dovecot.org/Authentication/Mechanisms) site, there isn't a problem sending plaintext password over SSL/TLS tunnels.

**Comment by jonbaldie** [comment]
Ooh ok, I didn't spot the `TLS` bit in the log line. The `PLAIN` in big letters just made me worry that it was insecure. In my experience Dovecot configuration is incredibly temperamental so I didn't want to mess with that too much.
