### ISSUE TITLE
extra anti-spam options please

### ISSUE THREAD

**Issue by ghost** [tomav/docker-mailserver#524]
Feature request:

1. Please allow the blocking of domains and IP's by means of a list.
2. Please allow additional blacklists, graylisting
3. Please allow additional signatures for Clamav. (I am still getting zipped virusses through)
4. Please allow for better security (only allow an account to send if the address exists in the alias list)

1: Create a recipient hash:
smtpd_recipient_restrictions =
        ...
        check_client_access hash:/etc/postfix/blacklist 
in /etc/postfix/blacklist :
1.2.3.4 REJECT
domain.ltd REJECT
3.2.1.4 REJECT 

Also possible in spamassassin:
vi /etc/mail/spamassassin/local.cf
blacklist_from user@example.com

2. https://wiki.apache.org/spamassassin/DnsBlocklists

3. There are many projects out there. One of which: https://github.com/extremeshok/clamav-unofficial-sigs

4.     smtpd_sender_restrictions = 
        permit_mynetworks
        ... 
        check_sender_access hash:/etc/postfix/sender_access
        reject_unknown_sender_domain
        warn_if_reject reject_unverified_sender 
http://www.postfix.org/ADDRESS_VERIFICATION_README.html

I know how to configure mail servers. But I'm stil _very_uncomfortable around docker.
As we speak I run 2 docker-mailserver instances, One in production, another in test.
Once I got everything set-up in a stable manner, I'll start working on the above issues and create pull requests. Don't let this stop you from cutting in and doing something already. I'm also rather unfamiliar with git.

**Comment by tomav** [comment]
If you have some mail server experience, we can probably help on docker.
Just ask, expose the way you will tend to implement and contributors will guide/validate your proposal. Do not hesitate.

Note that for point 1, you wan override config for postfix and add your custom spamassassin rules.

**Comment by dominikwinter** [comment]
I think it's more efficient to block IP addresses via iptables. If you have a large amount of IP addresses it's maybe even better to null route them.

**Comment by johansmitsnl** [comment]
Amavis encoder are expanded in #677.
Could you suggest a PR to make it more easy to configure for other users?

**Comment by johansmitsnl** [comment]
It could be solved once #825 will be merged.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
