### ISSUE TITLE
clamav still launched despite ENABLE_CLAMAV=0 and using notable amounts of memory

### ISSUE THREAD

**Issue by JonasT** [tomav/docker-mailserver#527]
Since we don't rely much on server-side antivirus scanning and available memory on our small server is a little tight, we tried disabling clamav with ENABLE_CLAMAV=0. However, despite removing and recreating the container with this environment option the process "clamd" still pops back up requiring significant amounts of memory.

Would it be possible to fix this so that with ENABLE_CLAMAV=0 the clamav isn't just not used, but also not launched? This poses a significant memory usage issue on our server, and we don't want to use it anyway...

**Comment by tomav** [comment]
The clamav startup is registered only when ENV set to 1. Strange.
https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L177-L179

There's also an integration test on it.
https://github.com/tomav/docker-mailserver/blob/master/test/tests.bats#L104-L107

Could you try this on your server?

**Comment by JonasT** [comment]
What exactly should I try?

I used `docker exec` to get a /bin/bash in the running mail container:
```
root@mail:/# ps aux | grep clamd
clamav    1302  0.0 49.2 731796 500356 ?       Ssl  Feb23   1:00 /usr/sbin/clamd
root      2003  0.0  0.0   8868   788 ?        S+   18:01   0:00 grep --color=auto clamd
root@mail:/# env | grep CLAMAV
ENABLE_CLAMAV=0
root@mail:/# 
```
So it really doesn't seem to be working as intended here...

**Comment by JonasT** [comment]
Is the option meant to be `ENABLE_CLAMAV` (documentation and what we used) or `ENABLED_CLAMAV` (unit test you linked)?

**Comment by JonasT** [comment]
For what it's worth, I looked at the tests but my server is itself just a KVM instance, so I cannot do full virtualization myself - and since the server is in production use, I cannot really launch something that creates test containers that possibly use up actual network ports (or do other things I'm not fully aware of).

I can try setting up a new clean ubuntu VM on my local dev machine and check if it works there if you want.

**Comment by JonasT** [comment]
Any update on this? This issue causes more than 50% of the available memory on our instance to be used up which is quite problematic..

I can stop clamd with a SIGTERM from the outside of course, but I'm not sure if this causes further problems in the container.

**Comment by JonasT** [comment]
Ah, I found the problem!

We were on an older image where the option was still named `DISABLE_CLAMAV`. I updated us to the newest container image now, and it works fine. So after all, this issue was somewhat self-inflicted :-)

I would suggest adding a small remark in the README that some options were renamed: my first post appears to have gotten an upvote from someone, so maybe some people are sitting on older images running into the same problem without realizing the culprit and this could save them some confusion and filed issues. (although I fully blame ourselves for not updating the image regularly)

**Comment by tomav** [comment]
It's in the Changelog I think: https://github.com/tomav/docker-mailserver/releases/tag/2.1

**Comment by tomav** [comment]
I close the issue, feel free to ask if needed.
Thanks @JonasT

**Comment by JonasT** [comment]
I would propose a small addition for confused people like me:

> Environment variables
>
> Please check how the container starts to understand what's expected.

to something like

> Environment variables
>
> Please check how the container starts to understand what's expected. Also if an option doesn't work as documented here, check if you are running the latest image!

:smile:

**Comment by tomav** [comment]
Done.
