### ISSUE TITLE
add logic to load /etc/postfix files

### ISSUE THREAD

**Issue by RobertoPirrone** [tomav/docker-mailserver#529]
Hi, I really like your project

I badly needed to add custom versions of transport, sender_bcc_maps, recipient_bcc_maps,
so I simply:

- created a new directory under config (i.e. etc-files)
- added this small snippet to start-mailserver.sh in order to copy files in /etc/postfix

`for f in /tmp/docker-mailserver/etc-files/* ; do
        base=$(basename $f)
        echo copying $base
        cp $f /etc/postfix
done
`

It works for me, but do you suggest a better way? 
Thank you
 Roberto

**Comment by tomav** [comment]
Hi @RobertoPirrone, thanks for your message!
This can help? https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration

**Comment by RobertoPirrone** [comment]
Hi
Not exactly. I already used the config/postfix-main.cf file for other info (mydestination and the names of bcc maps files). 
But I will try to follow your advice, probably I can embed the files in a "text" type map, I will investigate. Each file is just a couple of rows, it won't be that difficult

I will report my findings, thank you

**Comment by RobertoPirrone** [comment]
"text" type map was a pipe dream. The one I was thinking of is "inline", but sadly it will be available only in postfix 3. 
So I give up, and keep the small change in start-mailserver.sh

BTW, /etc/postfix/main.cf is not overwritten, but changed whenever you restart the container. So, if you inject some error (as I did with my tests), you must either recreate the container, or manually modify the file inside the container. Not a big deal, but maybe overwrite main.cf at every container restart could be less error prone.

**Comment by johansmitsnl** [comment]
Could you paste the diff of the change you made?

**Comment by RobertoPirrone** [comment]
Actually I’ m not very proud of my, ehhm, solution. It’ ugly as sin, but it works for me.
I decided that the easiest path is just copying the files that I need at startup.
So:
under config (mapped as /tmp inside the container), I created a subdirectory etc-files, where I put the hand made files (for me these files are local_recipients  recipient_pcre  sender_pcre  transport)
inside docker-compose.yml I added the startup command:    
	command: /bin/bash -c "sleep 3; cp /tmp/docker-mailserver/etc-files/* /etc/postfix; rm /var/run/dovecot/master.pid;  /usr/local/bin/start-mailserver.sh"


hope it helps, bye

**Comment by johansmitsnl** [comment]
Thats not that elegant indeed ;-)

Could you share the config file(s) that you need so that we can implement this feature?

**Comment by RobertoPirrone** [comment]
> Il giorno Sep 10, 2017, alle ore 10:37 AM, Johan Smits <notifications@github.com> ha scritto:
> 
> Thats not that elegant indeed ;-)
> 
> Could you share the config file(s) that you need so that we can implement this feature?
> 
> 
Well, the logic behind these files is that I have an external archiver, so I had to add rules both for sender and recipient, and add a transport rule

Actually if only /usr/local/bin/start-mailserver.sh could copy the files found in ad hoc directory, that could be fine (and a little bit more elegant….)

regards

**Comment by erik-wramner** [comment]
Is this still relevant (no action since 2017)?

**Comment by RobertoPirrone** [comment]
Well, I use my workaround, it' ugly, but plain simple and works for me.
Since I'm the only one that has this problem,  I think that we can close this thread
Thanks to everybody, tomav mailserver is a beatiful project
