### ISSUE TITLE
Suggest don't mount configs in /tmp/docker-mailserver/

### ISSUE THREAD

**Issue by liwanglin12** [tomav/docker-mailserver#533]
When your system restarts, the config will be lost, including DKIM Private Key & SASL Login Config......
Don't ask me why I know this![](https://cloud.githubusercontent.com/assets/10279535/23338378/51e845de-fc44-11e6-98fc-0f7355bff70b.jpg)

**Comment by WuTianming** [comment]
When your system restart**s**, config will **be** lost, includ**ing** DKIM Private Key & SASL Login Config......
Don't ask me why I know this
(Escape away)

**Comment by kn007** [comment]
why you hook /tmp to tmpfs😂, you need backup the files immediately when you had finished configuration

**Comment by tomav** [comment]
Hi @liwanglin12, hmm that's wrong for DKIM (or I don't see which point you're talking about).
Files are copied from mount dir to `dkim` folder.
If your system restarts, the files still exists in dkim folder and will be loaded.
https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L642

Let me know. Thank you.
Could you spot the thing to enhance in `start-mailserver.sh` and let us know what you suggest to improve the current setup?

**Comment by liwanglin12** [comment]
wow, thanks.
I changed some setting by modified main.cf & master.cf, but caused by a kernel update(restart), my all settings are lost(in /tmp/...../config/)... So I'm so sad for this😂
I copy them to docker container in every start by manual, does there have any function to auto cover the origin config?
Thanks for help~

**Comment by tomav** [comment]
My advice is to use `docker-compose` with `restart: always` option, well configured like the example provided in the project. If you config files are on your host, they will be mounted where it should on restart and everything will work as expected.

I let you keep me posted and reopen this if needed.
