### ISSUE TITLE
Smaller timeout for failed outgoing emails

### ISSUE THREAD

**Issue by kachkaev** [tomav/docker-mailserver#534]
Hello,

I've been enjoying this great docker image for about half a year now and would like to ask a small question, which might be topical to other users as well. As it turns out from [Semantec security forum](https://www.symantec.com/connect/security/forums/email-securitycloud), it is often the case that "clean" private mail servers end up being in some nontransparent Semantec's internal blacklist. Just search for _501 Connection rejected by policy [7.7]_ there and you will see the same question once in a few days. I got into this trap recently too :–)

The biggest issue is that the owner of a mail server cannot know about this problem until an email has been rejected by one of the Semantec customers, the list of which is not public. Because of how the server is configured now, the bounce-back email only lands the sender's inbox in five days, during which he or she is sure that the email has been delivered and maybe some actions are being taken by the receiver.

I know it's impossible to fix the root cause of the problem as it's on Semantec's end, but I'm wondering if it is reasonable to reduce the default retry timeout from 5 days to maybe an hour? I don't know how higher the probability of errors with such a small timeout would be, but even if this change causes more messages from "MAILER-DAEMON", I still see this situation better than what's happening now. An early error will help users connect with their recipients by other means and not desperately wait for a few days only to know that their very important email was bounced back.

What do you think?

**Comment by tomav** [comment]
Hi @kachkaev, you're right. This may be changed in default settings but you can already do that using postfix override feature.
Here is a related article: http://jrs-s.net/2013/04/17/configuring-retry-duration-in-postfix/

I don't measure which value should be default, so keeping postfix config may be ok, particularly if overridable.

**Comment by kachkaev** [comment]
Thanks for the link @tomav! After reading that article and a comment to it, my `postfix-main.cf` looks like this:

```
message_size_limit=31457280
bounce_queue_lifetime = 2h
maximal_queue_lifetime = 3h
queue_run_delay = 5m
minimal_backoff_time = 5m
maximal_backoff_time = 15m
```

Will see how it behaves in the wild, will let know if any issues.
