### ISSUE TITLE
Login issue since latest update for SMTP

### ISSUE THREAD

**Issue by Holt59** [tomav/docker-mailserver#536]
I have just updated my container, and I have some login issue. Before, I could set the username to `name.surname` and it would match my LDAP entry, now I have to set it to `name.surname@domain.com` (full address). If I don't, I get the following:

> Mar  2 15:17:18 mail postfix/submission/smtpd[1480]: NOQUEUE: reject: RCPT from unknown[80.12.59.0]: 553 5.7.1 <n.m@d.com>: Sender address rejected: not owned by user n.m@mail.d.com; from=<n.m@d.com> to=<...> proto=ESMTP helo=<[10.143.109.0]>

There is a `mail.` which is added before the domain, which is likely the issue... This was not here before the update, any idea?

**Comment by tomav** [comment]
Hi @Holt59, could you add a test case for that if missing?
It may be cool to check that it's not custom config related (and will improve test coverage).
here are the existing tests: https://github.com/tomav/docker-mailserver/blob/master/test/tests.bats#L955-L995

**Comment by Holt59** [comment]
Actually I don't know what is the expected behavior so I don't want to add bad tests... 

Should I be able to login with `username` / `password` or should I have to use `username@domain.com` / `password`? I am able to login to the IMAP server using the former versions but not to the SMTP server due to this `mail` prefix being added (for whatever reason...?) - Actually I am able to login but then there is a mismatch with the address...

**Comment by tomav** [comment]
#491 may help when @alinmear will have time to do that (and perhaps he can help)
It seems there are more and more people using LDAP with this image.

**Comment by alinmear** [comment]
@Holt59 can you show use the content of /etc/postfix/ldap-users.cf. Then we can check what postfix is trying to do here.

**Comment by Holt59** [comment]
@alinmear Here is the content of `/etc/postfix/ldap-users.cf`:

```
bind = yes
bind_dn = uid=dovecot,ou=services,dc=domain,dc=com
bind_pw = ********
query_filter = (&(mail=%s)(mailEnabled=TRUE))
result_attribute = mail
search_base = ou=people,dc=typename,dc=fr
server_host = ldap.typename.fr
version = 3
```

**Comment by alinmear** [comment]
@Holt59 seems like this happens because of your `query_filter`. Because of a bug (see #503 and #522) the `query_filter` if not manually changed has the value `(&(mail=%s)(mailEnabled=TRUE))`. This means the following:

- Search the Ldap of the Entry with the Mail Value you provided. e.g. `name.surname@domain.com` 
- AND Check that the Attribute `mailEnabled=True`

I don't know, how you configured your ldap server but for instance you could write the query filter like this to use the UniqueUserID `uid`:

`query_filter = (&(uid=%s)(mailEnabled=TRUE))`

Take a look at http://blog.gnukai.com/2011/07/postfixdovecot-with-ldap/ for a  nicely written explanation on this issue (old article, focus on the till now unchanged ldap parts).

Hopefuly this helps

**Comment by tailtwo** [comment]
When I'm manually changing /etc/postfix/ldap-users.cf, the container fails at restart.

```
bind             = yes
bind_dn = cn=admin,dc=test,dc=com
bind_pw = ***
query_filter     = (&(uid=%U)(objectClass=inetOrgPerson))
result_attribute = mail
search_base = ou=test,dc=example,dc=com
server_host = ***.***.***.***
version          = 3
```

Docker logs with `DMS_DEBUG=1`

```
[...]
mail    | Starting mail server
mail    |   Starting cron  [ OK ]
mail    |   Starting rsyslog  [ OK ]
mail    |   Starting dovecot services  [ OK ]
mail    |   Starting opendkim  [ OK ]
mail    |   Starting opendmarc  [ OK ]
mail    |   Starting postgreyfalse
mail    |   *  [ FAILED ]
mail    | Error: Please fix your configuration. Exiting...
mail exited with code 1
```

Trying with postmap works tho.

```
root@mail:/etc/postfix# postmap -v -q user ldap:/etc/postfix/ldap-users.cf                             
postmap: name_mask: all
postmap: inet_addr_local: configured 2 IPv4 addresses
postmap: inet_addr_local: configured 2 IPv6 addresses
postmap: dict_ldap_open: Using LDAP source /etc/postfix/ldap-users.cf
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: server_host = ***.***.***.***
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: server_port = 389
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: version = 3
postmap: dict_ldap_open: /etc/postfix/ldap-users.cf server_host URL is ldap://***.***.***.***:389
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: scope = sub
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: search_base = ou=test,dc=example,dc=com
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: timeout = 10
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: query_filter = (&(uid=%U)(objectClass=inetOrgPerson))
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: result_format = <NULL>
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: result_filter = %s
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: domain = 
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: terminal_result_attribute = 
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: leaf_result_attribute = 
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: result_attribute = mail
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: special_result_attribute = 
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: bind = yes
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: bind_dn = cn=admin,dc=example,dc=com
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: bind_pw = ***
postmap: cfg_get_bool: /etc/postfix/ldap-users.cf: cache = off
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: cache_expiry = -1
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: cache_size = -1
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: recursion_limit = 1000
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: expansion_limit = 0
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: size_limit = 0
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: dereference = 0
postmap: cfg_get_bool: /etc/postfix/ldap-users.cf: chase_referrals = off
postmap: cfg_get_bool: /etc/postfix/ldap-users.cf: start_tls = off
postmap: cfg_get_bool: /etc/postfix/ldap-users.cf: tls_require_cert = off
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: tls_ca_cert_file = 
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: tls_ca_cert_dir = 
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: tls_cert = 
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: tls_key = 
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: tls_random_file = 
postmap: cfg_get_str: /etc/postfix/ldap-users.cf: tls_cipher_suite = 
postmap: cfg_get_int: /etc/postfix/ldap-users.cf: debuglevel = 0
postmap: dict_open: ldap:/etc/postfix/ldap-users.cf
postmap: dict_ldap_lookup: In dict_ldap_lookup
postmap: dict_ldap_lookup: No existing connection for LDAP source /etc/postfix/ldap-users.cf, reopening
postmap: dict_ldap_connect: Connecting to server ldap://***.***.***.***:389
postmap: dict_ldap_connect: Actual Protocol version used is 3.
postmap: dict_ldap_connect: Binding to server ldap://***.***.***.***:389 with dn cn=admin,dc=example,dc=com
postmap: dict_ldap_connect: Successful bind to server ldap://***.***.***.***:389 with dn cn=admin,dc=example,dc=com
postmap: dict_ldap_connect: Cached connection handle for LDAP source /etc/postfix/ldap-users.cf
postmap: dict_ldap_lookup: /etc/postfix/ldap-users.cf: Searching with filter (&(uid=user)(objectClass=inetOrgPerson))
postmap: dict_ldap_get_values[1]: Search found 1 match(es)
postmap: dict_ldap_get_values[1]: search returned 1 value(s) for requested result attribute mail
postmap: dict_ldap_get_values[1]: Leaving dict_ldap_get_values
postmap: dict_ldap_lookup: Search returned user@example.com
user@example.com
postmap: dict_ldap_close: Closed connection handle for LDAP source /etc/postfix/ldap-users.cf

**Comment by tailtwo** [comment]
Turns out the container crashed because I installed vim via apt to tweak some files. I find it a bit weird that  installing a text editor and some dependencies would kill the container but whatever.

**Comment by alinmear** [comment]
@tomav can we close this issue?

**Comment by alinmear** [comment]
@tomav, i don't know why, but tests within travis brings up some failures triggered by some of the bats unit tests. Also the main branch which i fetched from you, upstream master is having some problems.

Strangely the failures are connected to parts i not touched or even come close to it. Also the untouched main branch fails. Any clue what's going on there?:

Branch #621: https://travis-ci.org/alinmear/docker-mailserver/builds/239733394
Branch main: https://travis-ci.org/alinmear/docker-mailserver/builds/239727349
