### ISSUE TITLE
IPv6 address gets rejected by smtpd helo policy

### ISSUE THREAD

**Issue by trytuna** [tomav/docker-mailserver#537]
I am getting this nasty error:

    postfix/submission/smtpd[1499]: NOQUEUE: reject: RCPT from unknown[172.18.0.1]: 501 5.5.2 <[ffff:fff:fff:ffff:ffff:ffff:ff::]>: Helo command rejected: invalid ip address; from=<a@example.com> to=<b@example.com> proto=ESMTP helo=<[ffff:fff:fff:ffff:ffff:ffff:ff::]>

I obfuscated email and IP addresses but format was kept the same.

I got it fixed by removing `reject_invalid_helo_hostname` from `smtpd_helo_restrictions` in `/etc/postfix/main.cf`.

My question: Is it safe to do that? Is there another way to fix that problem?

Edit:
Isn't that weird that there is no number at the end of the IPv6 address?

**Comment by trytuna** [comment]
#expertneeded 😔

**Comment by tomav** [comment]
You're host is IPv6 compliant?
I remember I set `inet_protocols = ipv4` a long time ago perhaps because if these warnings, my provider not giving IPv6.

**Comment by trytuna** [comment]
Yes it is. As described earlier I fixed the problem by just changing the policy. I guess its because of the weird v6 address. It ends with ::. I don't know enough about about IPv6 to know if this is indeed a valid address. In a different location where I also connect through IPv6 it just works fine (note that at this location there is no weird looking address).

On the other side I am pretty confident that the sysadmins @ the university (where I get the address that ends with ::) know what they are doing.

**Comment by johansmitsnl** [comment]
Ending with :: means that you want to say :0:0:0 etc...
When you write the ipv6 address fully does it work?
Like ffff:fff:fff:ffff:ffff:ffff:ff:0

**Comment by trytuna** [comment]
Unfortunately I cannot change that. The IP that shows up in the logs is the IP that is trying to establish a connection to the mailserver. I just figured that for some reason it is not my computers ipv6 address. It could be a firewall thing of some sort.

**Comment by johansmitsnl** [comment]
Ok, so it is not related to the docker image?

**Comment by trytuna** [comment]
Honestly I dont know. As I described earlier it is fixable by removing `reject_invalid_helo_hostname ` from `smtpd_helo_restrictions`.

It could also be a postfix bug. I dont know if an IPv6 address that ends to `::` is valid or not.

**Comment by johansmitsnl** [comment]
Is it solved?
If yes please share and close the solution.

**Comment by trytuna** [comment]
Nope its not :(

**Comment by mathuin** [comment]
https://github.com/vdukhovni/postfix/blob/master/postfix/README_FILES/LINUX_README#L5-L23

I wonder if the other fixes mentioned here would help?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
