### ISSUE TITLE
setup.sh: Aliases

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#538]
It doesn't seem that setup.sh can be also used for managing aliases. - It would be a nice addition.

**Comment by tomav** [comment]
Yep. Wanna contribute?

**Comment by kiliant** [comment]
I'm on it

**Comment by tomav** [comment]
Done: https://github.com/tomav/docker-mailserver/wiki/Setup-docker-mailserver-using-the-script-setup.sh
https://github.com/tomav/docker-mailserver/pull/541
Thanks.
