### ISSUE TITLE
About pop3 support

### ISSUE THREAD

**Issue by crash7** [tomav/docker-mailserver#54]
Hi,

Is there any special reason about not installing pop3 (and pop3-ssl)? Seems that with the courier modules and a couple of lines in the config (TLS certs and port), it should work.

I'm asking because if you want to use the mail server with gmail pop3 check, it may not work since this only supports imap.

Great work anyway, these docker images is really helpful.

UPDATE: just saw this issue https://github.com/tomav/docker-mailserver/issues/32, sorry about the duplication.

**Comment by tomav** [comment]
Hey @crash7, thank you for your message.

If you want to add `pop3` support in this public image:
- `pop3` should be disabled by default
- enabling `pop3` could be done using an ENV variable
- don't forget to add integration tests

If you PR I'll merge. I can help you if you have any question.

**Comment by tomav** [comment]
@crash7 Let me know if you work on it or not.
Thank you.

**Comment by crash7** [comment]
Hi! 
Yes, I will try to submit this during the weekend.

**Comment by tomav** [comment]
Thanks!

**Comment by awb99** [comment]
I have ENV variable set for POP. But I cannot telnet into the pop ports. Why is this?
In docker ps it shows that the pop ports 110 and 993 arenot showing 0.0.0.0    but instead
no IP address.
