### ISSUE TITLE
Mention address tag support in the documentation

### ISSUE THREAD

**Issue by mrPjer** [tomav/docker-mailserver#542]
Address tags (the ability to redirect username+tag@example.com to username@example.com's mailbox) are a great way to avoid SPAM. Since it's supported and enabled by default in this container (the default delimiter is +), it might be a good idea to mention this feature either in the wiki or in the readme.

I was looking for a way to enable this (and found a cool guide at https://www.stevejenkins.com/blog/2011/03/how-to-use-address-tagging-usertagexample-com-with-postfix/) only to find out it's already enabled.

If you want, I can write up a description, just let me know where to put it.

**Comment by tomav** [comment]
You can do it [here](https://github.com/tomav/docker-mailserver/wiki/Configure-Aliases).
We did not write this because it's not docker related, but it's a postfix general configuration option.

**Comment by mrPjer** [comment]
>We did not write this because it's not docker related, but it's a postfix general configuration option.

I assumed this was the case. I've added a small mention of address tags to the wiki page you've mentioned. If it's ok, you can close the issue.

**Comment by tomav** [comment]
Perfect, thanks @mrPjer!
