### ISSUE TITLE
Add support for autodiscovery

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#544]
It would be a great addition if [automx](https://github.com/sys4/automx) or [email-autodiscover](https://github.com/gronke/email-autodiscover) is added so clients can autoconfigure.

**Comment by tomav** [comment]
Yep, this brings value to product.
But this also adds a webserver to the project.

**Comment by theomega** [comment]
Maybe it would make sense to keep this separate in an own docker container? In the end the shared details between the docker-mailserver and the (let's call it) "docker-autodiscover" are very limited (hostnames)

**Comment by johansmitsnl** [comment]
I agree with @theomega that adding it to the project might add more then just the mailserver functionality.
Therefore I have made a project based on the email-autodiscover.
Check here the docker [docker-email-autodiscover](https://hub.docker.com/r/jsmitsnl/docker-email-autodiscover/) project. With detailed information.

@tomav do you agree to include this in the WIKI section or do you want to add it to the readme?

**Comment by tomav** [comment]
Yep of course, if it works properly let's use it. You an create a page in the Wiki to explain how to use it if not stated in your project.

**Comment by johansmitsnl** [comment]
Added the WIKI page: [Wiki/Configure-autodiscover](https://github.com/tomav/docker-mailserver/wiki/Configure-autodiscover).

@strarsis does this fit your needs and can we close the issue?
