### ISSUE TITLE
Comments in accounts cf file not ignored

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#546]
Comments in the 'postfix-accounts.cf' file are not ignored, 
folders are created in data directory with the whole line as their name, e.g. '# a comment'.

Edit: Also the setup.sh script doesn't ignore comments and newlines and shows them on screen.

**Comment by tomav** [comment]
If it's the case, it should be fixed. A good thing to do here if provide an integration for that case.
It will allow everyone to reproduce and will improve coverage.

**Comment by tomav** [comment]
Reproduced:

````
user '# this is a comment' for domain '# this is a comment' with password '********'
/usr/local/bin/start-mailserver.sh: line 378: test: too many arguments
```

```
root@mail:/var/mail# ls -la
total 28
drwxr-sr-x  2 docker docker 4096 Mar 16 17:06 #
drwx--S---  3 docker docker 4096 Mar 16 17:06 # this is a comment
drwxrwsr-x  7 docker docker 4096 Mar 16 17:06 .
drwxr-xr-x 29 root   root   4096 Mar 16 17:06 ..
drwxr-sr-x  4 docker docker 4096 Mar 16 17:06 domain.tld
drwxr-sr-x  3 docker docker 4096 Mar 16 17:06 localhost.localdomain
drwxr-sr-x  3 docker docker 4096 Mar 16 17:06 otherdomain.tld
```

**Comment by strarsis** [comment]
Extra notes: Comments in postfix-virtual.cf aren't allowed at all, regardless of variety (; or #) - 
otherwise something will fail inside (amavis? dovecot?), a warning is also emitted.

After some issues with postfix-virtual.cf config, notably with amavis/milter, I had to actually clean out the whole state folder to make it work again.

**Comment by tomav** [comment]
Can you submit a Pull Request to fix that point?

**Comment by tomav** [comment]
Linked to #560

**Comment by tomav** [comment]
Regarding alias file, it's not parsed, but used as is. So the file must me clean.
