### ISSUE TITLE
Different UID/GID for data/ sub-directories

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#547]
Is it possible to have the directories, notably the data/ sub-directories, 
owned by a different user or at least a different group than UID/GID 5000? 
This would make it so much easier to backup the data without the need for sudo/root access

**Comment by tomav** [comment]
User 5000 is a `docker` user created for the mail server purpose.
The configuration relies on this UID/GID;
There's probably a room for improvement here.

Regarding backups : https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#what-about-backups

**Comment by strarsis** [comment]
Then I will use UID 5000 also on the host in order to access the data.
I want to use rsync or another tool than gzipping the whole data directory each time 
hence the access from the host.

**Comment by tomav** [comment]
Ok, thanks.
