### ISSUE TITLE
restart: always

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#549]
It makes sense to add `restart: always` to docker-compose.yml because this will auto-restart the mail container in case of docker service/host reboot and other issues.

**Comment by tomav** [comment]
Could you add this to the README and dist file?

**Comment by strarsis** [comment]
@tomav: PR for adding to docker-compose.yml (dist) files (also to the elk variant): https://github.com/tomav/docker-mailserver/pull/550

**Comment by tomav** [comment]
Fixed by #550
