### ISSUE TITLE
ClamAV-clamd av-scanner FAILED: run_av error: Too many retries to talk to /var/run/clamav/clamd.ctl

### ISSUE THREAD

**Issue by kgthenerd** [tomav/docker-mailserver#558]
I'm see quite a lot of these errors when a email arrives.

`Mar 23 04:30:53 mail amavis[1596]: (01596-04) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory`
`Mar 23 04:30:54 mail amavis[1596]: (01596-04) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory`
`Mar 23 04:30:54 mail amavis[1596]: (01596-04) (!)ClamAV-clamd: All attempts (1) failed connecting to /var/run/clamav/clamd.ctl, retrying (2)`
`Mar 23 04:31:00 mail amavis[1596]: (01596-04) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory`
`Mar 23 04:31:00 mail amavis[1596]: (01596-04) (!)ClamAV-clamd av-scanner FAILED: run_av error: Too many retries to talk to /var/run/clamav/clamd.ctl (All attempts (1) failed connecting to /var/run/clamav/clamd.ctl) at (eval 136) line 603.\n`
`Mar 23 04:31:00 mail amavis[1596]: (01596-04) (!)WARN: all primary virus scanners failed, considering backups`

**Comment by jalenconner** [comment]
I'm seeing the same thing. Any ideas @tomav?

**Comment by tomav** [comment]
Hi, can I get some information regarding your configuration? See https://github.com/tomav/docker-mailserver/blob/master/CONTRIBUTING.md

In the meantime, I update a server to the latest and check the log with my configuration.

Thanks.

**Comment by tomav** [comment]
Just tried to receive/send email from/to Gmail. No issue so far with this config:

```
    - ENABLE_CLAMAV=1
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - SSL_TYPE=letsencrypt
    - SA_TAG=-5.0
    - SA_TAG2=4.9
    - SA_KILL=5.0
    - ONE_DIR=1
    - DMS_DEBUG=1
```

**Comment by kgthenerd** [comment]
`root@mail:/# /etc/init.d/clamav-daemon start
 * Starting ClamAV daemon clamd
LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes).
LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes).
LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes).
LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes).
LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes).
LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes).
LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes).
LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes).
LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes).
^C`

effort to start manually leads to memory bottleneck. maybe add _mem_limit_ in docker-compose.yml or launch clamav in a seperate container what you say @tomav?

**Comment by tomav** [comment]
Hi @kgthenerd, how much memory your container can use?

**Comment by kgthenerd** [comment]
I do not see a lot of memory being used atm

<img width="882" alt="screen shot 2017-03-26 at 12 23 38 am" src="https://cloud.githubusercontent.com/assets/195539/24325247/c605e102-11ba-11e7-9080-0f9b4051fe24.png">

<img width="524" alt="screen shot 2017-03-26 at 12 23 20 am" src="https://cloud.githubusercontent.com/assets/195539/24325252/cd7c0a10-11ba-11e7-8757-52c658d043ba.png">

**Comment by tomav** [comment]
But your host can provide more? With clamav you need at least 1GB

**Comment by kgthenerd** [comment]
I'm currently testing this out on t2.micro on AWS, looks like i need a t2.small or t2.medium

**Comment by tomav** [comment]
Yep probably. Let me know once you tested it.
I just had a look on my server and Clamav itself is 500MB.

**Comment by spellingandgrammar** [comment]
Funnily enough I had the same problem. Clamd was installed as was freshclam, I actually had to apt-get install clamav-daemon, which solved the issue of the "(01596-04) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory"
Maybe give that a try

**Comment by tomav** [comment]
@spellingandgrammar `clamav-daemon` is already installed in this image.
My assumption is that not a lot of memory is used because `clamav` cannot be started.
`LibClamAV Error: mpool_malloc(): Can't allocate memory (33558528 bytes)` is really meaningful.

**Comment by spellingandgrammar** [comment]
Apologies, I was referring to the original post with the directory not existing. Good luck.

**Comment by johansmitsnl** [comment]
I can confirm that for AWS you need a t2.small to have a mail setup with clamav working.
Save to add a swap space as well.
All below the small is just to tiny and will not have sufficient memory available.
