### ISSUE TITLE
DNS question / user authentication

### ISSUE THREAD

**Issue by 3mbr4c3** [tomav/docker-mailserver#561]
hey folks,

nice project!

I stumbled upon a problem with my dns setting:

 I can't really follow how you consider the DNS should be set up. Currently the zonefile for cipherspec.net looks like this:

> [...]
> @                        IN A       46.4.72.9
> cipherspec.net           IN A       46.4.72.9
> cloud                    IN A       46.4.72.9
> www                      IN A       46.4.72.9
> @                        IN MX 10   mail.cipherspec.net
> mail._domainkey          IN TXT     "v=DKIM1; k=rsa; p=xxx"[...]

Can' really believe that they are correct like this, are they?

Thunderbirds autoconfiguration finds port etc. by himself but then, when testing username and password, he says: "Configuration couldn't be checked, is username or password wrong?".

> ➜  docker-mailserver git:(master) ✗ cat config/postfix-accounts.cf
> jhort@cipherspec.net|{SHA512-CRYPT}$6$0MBLABLABLA
> 

I created the users as stated in the documentation:

> 
> mkdir -p config
> touch config/postfix-accounts.cf
> docker run --rm \
>   -e MAIL_USER=jhort@cipherspec.net \
>   -e MAIL_PASS=andThePasswordIWontGiveYou \
>   -ti tvial/docker-mailserver:latest \
>   /bin/sh -c 'echo "$MAIL_USER|$(doveadm pw -s SHA512-CRYPT -u $MAIL_USER -p $MAIL_PASS)"' >> config/postfix-accounts.cf

Password I configured & password I added are both exactly and definitely the same.

I must oversee something, any hints?

Thanks for help and keep going :)

Greetings

**Comment by tomav** [comment]
Hi, regarding DNS configuration, here is an example:

```
$ttl 38400
domain.com.  IN  SOA ns1.domain.com. ns2.domain.com. (
  2016061502
  10800
  3600
  604800
  38400 )

; NS Records
domain.com.       IN  NS  ns1.domain.com.
domain.com.       IN  NS  ns2.domain.com.

; Default record
domain.com.   600 IN A xxx.xxx.xxx.xxx
mail          600 IN A xxx.xxx.xxx.xxx

; MX Record
domain.com.       IN  MX  1 mail.domain.com.

; SPF
domain.com. IN TXT "v=spf1 mx ~all"
domain.com. IN SPF "v=spf1 mx ~all"

; OpenDKIM
mail._domainkey IN  TXT ( "v=DKIM1; k=rsa; "
    "..." )  ; ----- DKIM key mail for domain.com
```

First:
- check that your DNS modifications are propagated (be sure that mail.cipherspec.net resolved the right IP)
- use full email as login + the given password

It should work. If no, check logs located in `/var/log/mail/mail.log`

Le me know if I can help.

**Comment by DracoMilesX** [comment]
Sorry to hijack this one but I kinda have the same issue. But if I need to create a new issue I will do it.

My DNS Settings:

> @ 3600 IN A x.x.x.x
> domain.tld 3600 IN A x.x.x.x
> mail 3600 IN A x.x.x.x
> domain.tld 3600 IN MX 1 mail.domain.tld.
> domain.tld 3600 IN SPF "v=spf1 mx ~all"
> domain.tld 10800 IN TXT "v=spf1 mx ~all"
> mail._domainkey 10800 IN TXT "( " "v=DKIM1; k=rsa; " "p=..." ")"

Now it appears to be fine since Thunderbird find the information.
IMAP and SMTP are mail.domain.tld
IMAP 143 and SMTP 587
STARTSSL on both
User@domain.tld as login
Authentication is normal password but when I do this it times out saying the IMAP server doesn't support it and choosing encrypted password just endlessly loads.

So decided to test a roundcube docker image

> -e ROUNDCUBE_DEFAULT_HOST=x.x.x.x \
> -e ROUNDCUBE_DEFAULT_PORT=143 \
> -e ROUNDCUBE_SMTP_SERVER=x.x.x.x \
> -e ROUNDCUBE_SMTP_PORT=587 \

On port 143 it gives the message can not found storage server with the error in the logs in docker that it sends a plaintext password which isn't supported on default_port=993 it times out.

> Apr 18 20:23:03 mail postfix/submission/smtpd[1436]: connect from unknown[172.18.0.1]
> Apr 18 20:23:03 mail postfix/submission/smtpd[1436]: improper command pipelining after EHLO from unknown[172.18.0.1]: QUIT\r\n
> Apr 18 20:23:03 mail postfix/submission/smtpd[1436]: disconnect from unknown[172.18.0.1]
> Apr 18 20:23:03 mail postfix/smtpd[1435]: connect from unknown[172.18.0.1]
> Apr 18 20:23:03 mail postfix/smtpd[1435]: lost connection after CONNECT from unknown[172.18.0.1]
> Apr 18 20:23:03 mail postfix/smtpd[1435]: disconnect from unknown[172.18.0.1]
> Apr 18 20:23:04 mail postfix/submission/smtpd[1440]: connect from unknown[172.18.0.1]
> Apr 18 20:23:04 mail postfix/submission/smtpd[1440]: lost connection after CONNECT from unknown[172.18.0.1]
> Apr 18 20:23:04 mail postfix/submission/smtpd[1440]: disconnect from unknown[172.18.0.1]
> Apr 18 20:23:04 mail postfix/smtpd[1441]: connect from unknown[172.18.0.1]
> Apr 18 20:23:04 mail postfix/smtpd[1441]: lost connection after CONNECT from unknown[172.18.0.1]
> Apr 18 20:23:04 mail postfix/smtpd[1441]: disconnect from unknown[172.18.0.1]
> Apr 18 20:23:04 mail postfix/submission/smtpd[1442]: connect from unknown[172.18.0.1]
> Apr 18 20:23:04 mail postfix/submission/smtpd[1442]: lost connection after CONNECT from unknown[172.18.0.1]
> Apr 18 20:23:04 mail postfix/submission/smtpd[1442]: disconnect from unknown[172.18.0.1]
> Apr 18 20:23:05 mail postfix/smtpd[1443]: connect from unknown[172.18.0.1]
> Apr 18 20:23:05 mail postfix/smtpd[1443]: lost connection after CONNECT from unknown[172.18.0.1]
> Apr 18 20:23:05 mail postfix/smtpd[1443]: disconnect from unknown[172.18.0.1]
> Apr 18 20:23:05 mail postfix/submission/smtpd[1444]: connect from unknown[172.18.0.1]
> Apr 18 20:23:05 mail postfix/submission/smtpd[1444]: lost connection after CONNECT from unknown[172.18.0.1]
> Apr 18 20:23:05 mail postfix/submission/smtpd[1444]: disconnect from unknown[172.18.0.1]
> Apr 18 20:23:05 mail postfix/smtpd[1445]: connect from unknown[172.18.0.1]
> Apr 18 20:23:05 mail postfix/smtpd[1445]: lost connection after CONNECT from unknown[172.18.0.1]
> Apr 18 20:23:05 mail postfix/smtpd[1445]: disconnect from unknown[172.18.0.1]
> Apr 18 20:24:22 mail dovecot: imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.18.0.1, lip=172.18.0.2, session=<7mFXBHVNoQCsEgAB>
> Apr 18 20:24:23 mail postfix/submission/smtpd[1436]: connect from unknown[172.18.0.1]
> Apr 18 20:24:23 mail postfix/submission/smtpd[1436]: improper command pipelining after EHLO from unknown[172.18.0.1]: QUIT\r\n
> Apr 18 20:24:23 mail postfix/submission/smtpd[1436]: disconnect from unknown[172.18.0.1]
> Apr 18 20:25:22 mail dovecot: imap-login: Disconnected (no auth attempts in 104 secs): user=<>, rip=172.18.0.1, lip=172.18.0.2, TLS handshaking: SSL_accept() syscall failed: Broken pipe, session=<oYXhB3VN6wCsEgAB>
> Apr 18 20:25:22 mail dovecot: imap-login: Disconnected: Inactivity (no auth attempts in 255 secs): user=<>, rip=172.18.0.1, lip=172.18.0.2, TLS handshaking: SSL_accept() syscall failed: Broken pipe, session=<8ofhB3VNPgCsEgAB>
> Apr 18 20:25:22 mail dovecot: imap-login: Disconnected: Inactivity (no auth attempts in 451 secs): user=<>, rip=172.18.0.1, lip=172.18.0.2, TLS handshaking: SSL_accept() syscall failed: Broken pipe, session=<v23hB3VN1wCsEgAB

Initially it looks like it can't maintain the connection.

**Comment by jodumont** [comment]
@DracoMilesX it's look like the same issue but it's probably not
In the original post @3mbr4c3 missing a DNS Entry for is mail.
`like : mail IN A 46.4.72.9`

you don't ;)
