### ISSUE TITLE
not able to receive emails

### ISSUE THREAD

**Issue by ssmlee04** [tomav/docker-mailserver#565]
I followed the steps in the wiki and configured DKIM and user accounts and get the following output but I still cannot receive any emails. I was wondering if there's something that I did wrong? Thanks.

```
dig TXT mail._domainkey.foundeal.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> TXT mail._domainkey.foundeal.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24031
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mail._domainkey.foundeal.com.	IN	TXT

;; ANSWER SECTION:
mail._domainkey.foundeal.com. 60 IN	TXT	"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDUS"

;; Query time: 30 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Wed Apr 05 04:46:30 UTC 2017
;; MSG SIZE  rcvd: 304
```

![https://i.stack.imgur.com/OjzVf.png](https://i.stack.imgur.com/OjzVf.png)
![https://i.stack.imgur.com/tXWWX.png](https://i.stack.imgur.com/tXWWX.png)

**Comment by kiliant** [comment]
Hi,
can you try to send yourself a test email and paste the output of _./setup.sh debug show-mail-logs_ ?

This would be a first step of debugging.

**Comment by ssmlee04** [comment]
I have later realized that I set the mail smtp server to be `mail.foundeal.com` but I didn't point my A record to the same ip address as @. Also I didn't set MX last time but after I made those changes now everything is working alright.
