### ISSUE TITLE
Custom changes in main.cf

### ISSUE THREAD

**Issue by marech** [tomav/docker-mailserver#566]
Hey!

Whats the proper way to make changes in main.cf file so they stay when i launch container again?
For example i want to add mydestination = example.com and bounce_queue_lifetime = 1h

**Comment by tomav** [comment]
Hi @marech, this may help: https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration

Let me know.

**Comment by marech** [comment]
Oh, wow, that's a good way to add custom options!
Thank you very much!
