### ISSUE TITLE
[Breaking Change] Mail accounts starting with a non-letter don't work anymore

### ISSUE THREAD

**Issue by xelan** [tomav/docker-mailserver#567]
Due to the change of `target/start-mailserver.sh` in 912cb5676b9538eb1c799b3c229c7e8dc9c94f40, mail accounts whose names do not start with a lowercase letter are ignored when the `postfix-accounts.cf` file is parsed during mailserver startup. As a consequence, logins for those accounts don't work anymore and the accounts are not known to the system so mail is potentially lost. Furthermore, fail2ban blocks the IP of clients which try to access.

In my case, I use a mail account which starts with a number for one of my mail addresses. Also, mailboxes starting with an uppercase letter (or even something else?) will run into problems.

Probably the correct rule would be to ignore lines which are starting with a comment (#) or are empty, but accept everything else (for backwards compatibility).

**Comment by tomav** [comment]
Hi @xelan, can you provide a PR for that?
