### ISSUE TITLE
Does it allow multiple domains?

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#57]
Hi, I have a question. Does this stack allow multiple domains? As it open the common ports, I wonder if it allows multiple domains, so I can deploy just one instance of it without the need for a proxy to separate domains.

**Comment by citec** [comment]
When I say "multiple domains" I mean: can I set account for multiple domains in the postfix/accounts.cf file? What happend then with the ssl certificate? should I put just one certificate for the main domainname configured in the docker-compose.yml or do I need a ssl cert for each account domain?
thanks

**Comment by tomav** [comment]
Hi @citec, this is more a `postfix` question than a `docker`one.

The answer is yes, postfix is multidomain.
You can manage as many domains as you want using Postfix virtual domains that is pre-configured on this docker image.
The `accounts.cf` is the key.

You also should have a look to Postfix configuration: http://www.postfix.org/VIRTUAL_README.html

Regarding your SSL question, these answer will help you: http://serverfault.com/questions/344038/virtual-domains-with-postfix-and-ssl

**Comment by citec** [comment]
Ok, I understand now: I will set the autoconfig for my clients, or tell them, to use mail.mycompany.com
Thanks
