### ISSUE TITLE
SASL_PASSWD

### ISSUE THREAD

**Issue by mholti** [tomav/docker-mailserver#572]
Hi,
i need to send my mails via an smtp-relayhost. So i set the environment SASL_PASSWD to "host user:pass". But: i have to start "postmap /etc/postfix/sasl_passwd" manually to make this work.
Would it be possible to do this a every start of the container?
Thanks
Michael

**Comment by tomav** [comment]
Hi @mholti, can you check that the link to sasl pwd file is a `texthash` in `main.cf`?

**Comment by mholti** [comment]
Hi @tomav,
thanks for the hint, i wrote it as "hash:" to main.cf. Now it works.
Thank you for the great docker image
Michael

**Comment by tomav** [comment]
You're welcome
