### ISSUE TITLE
Command to generate DKIM key doesn't work

### ISSUE THREAD

**Issue by Mathieu-R** [tomav/docker-mailserver#576]
When I run this command : 
```
docker run --rm \
  -v "$(pwd)/config":/tmp/docker-mailserver \
  -ti tvial/docker-mailserver:latest generate-dkim-config
```

I should have a dkim key generated in the `config folder` but this folder remains empty.

![image](https://cloud.githubusercontent.com/assets/16360664/25083277/77c1a6ae-2356-11e7-9453-f7fbd6ff2830.png)

**Comment by kiliant** [comment]
Hi,

have you created mail accounts yet? This is needed because DKIM keys are generated for each domain in postfix-accounts.cf.

Otherwise a folder `opendkim` should be created in your config folder.
I just tried it locally. When no account is present, no folder is generated. When an account is created, e.g. by using `./setup.sh email add test@email.com testpw` and executing 
```
docker run --rm \
  -v "$(pwd)/config":/tmp/docker-mailserver \
  -ti tvial/docker-mailserver:latest generate-dkim-config
```
, the folder is created.

**Comment by Mathieu-R** [comment]
Yes but I generated it in a `mail folder`

![image](https://cloud.githubusercontent.com/assets/16360664/25088674/51e9c390-2378-11e7-9d7d-baaf6f341c65.png)

Do I have to put it in a `config folder` ?

**Comment by kiliant** [comment]
Yes, as the [generation script](https://github.com/tomav/docker-mailserver/blob/master/target/bin/generate-dkim-config) reads from ```/tmp/docker-mailserver/postfix-accounts.cf```, the accounts have to be present there.

**Comment by Mathieu-R** [comment]
Ok I have put it in a config folder but now I have another problem.

![image](https://cloud.githubusercontent.com/assets/16360664/25091318/c97423aa-2388-11e7-9db3-b98bd00d712f.png)

But I have this in my `docker-compose.yml` 
```yml
volumes:
        - ./mail/ingoing:/var/mail
        - ./mail/state:/var/mail-state
        - ./config/:/tmp/docker-mailserver/
        - /etc/letsencrypt:/etc/letsencrypt/
```

And here's my `config directory` : 
![image](https://cloud.githubusercontent.com/assets/16360664/25091364/07f488fe-2389-11e7-8aaf-646140f9ee87.png)
