### ISSUE TITLE
Assign IP Address that E-Mail is being sent from

### ISSUE THREAD

**Issue by nylser** [tomav/docker-mailserver#578]
Hey, I'm a bit puzzled here... I have successfully managed to assign a static ip to reach the docker container - but when I send mail from any of the accounts, it just uses the other ip-address that is assigned to the server. This way my reverse DNS entries are also not valid. 
EMail delivery itself works - just the sending ip-address isn't right.
My current configuration:

    version: '2.1'

    services:
      mail:
        image: tvial/docker-mailserver:2.1
        hostname: mail
        domainname: example.net
        container_name: mail
        networks:
          net_static:
            ipv4_address: 172.22.0.10
        ports:
        - "25:25"
        - "143:143"
        - "587:587"
        - "993:993"
        - "110:110"
        - "995:995"
        volumes:
        - maildata:/var/mail
        - mailstate:/var/mail-state
        - ./config/:/tmp/docker-mailserver/
        - /etc/letsencrypt:/etc/letsencrypt/:ro
        - /etc/localtime:/etc/localtime:ro
        environment:
        - ENABLE_SPAMASSASSIN=1
        - ENABLE_CLAMAV=1
        - ENABLE_FAIL2BAN=1
        - ENABLE_POSTGREY=1
        - ENABLE_POP3=1
        - ONE_DIR=1
        - DMS_DEBUG=1
        - SSL_TYPE=letsencrypt
        - ENABLE_ELK_FORWARDER=1
        cap_add:
        - NET_ADMIN
        restart: always

    networks:
      net_static:
        driver: bridge
        ipam:
           driver: default
           config:
           - subnet: 172.22.0.1/16
        driver_opts:
           com.docker.network.bridge.host_binding_ipv4: 123.456.789.12
        
    volumes:
      maildata:
        driver: local
      mailstate:
        driver: local

**Comment by l0rda** [comment]
Docker does not have SNAT, you need to do it manually:

> docker network create NETWORK --subnet=192.168.1.0/24 --gateway=192.168.1.1 # choose an unused subnet
> iptables -t nat -I POSTROUTING -s 192.168.1.0/24 -j SNAT --to-source OUTGOING_IP # remember that Docker also edit POSTROUTING
> docker network connect NETWORK CONTAINER # or with Compose

**Comment by nylser** [comment]
So, using iptables SNAT, I also don't have to use the `host_binding_ipv4` Parameter?

**Comment by l0rda** [comment]
Yes, but you must change ports section to:
```    ports:
    - "123.456.789.12:25:25"
    - "123.456.789.12:143:143"
    - "123.456.789.12:587:587"
    - "123.456.789.12:993:993"
    - "123.456.789.12:110:110"
    - "123.456.789.12:995:995"
```
if want listen only this ip

**Comment by nylser** [comment]
Thank you very much! It worked!
