### ISSUE TITLE
Alternative username

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#579]
I know this is not so easy because of SASL/Dovecot, but is it possible to add alternative usernames that can be used instead the primary email for logging in / sending?

**Comment by johansmitsnl** [comment]
Not that I'm aware of right now.
Did you solve your issue?

**Comment by strarsis** [comment]
No, I didn't but I don't need alternative usernames now.

**Comment by johansmitsnl** [comment]
You could achieve it with ldap, you can set a different username to the email address.
When using it without the ldap database it is fixed to the email address.
Agree to close it?

**Comment by strarsis** [comment]
Yes.
