### ISSUE TITLE
own ssl certs

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#58]
Hi, I am trying to setup a container with my own ssl certificates (not self-signed, bought, signed by GeoTrust).

I have generated the files into ./postfix/ssl, combining private key and ca into mail.grupocitec.com-combined.pem and putting the key into mail.grupocitec.com-key.pem and putting cert into mail.grupocitec.com-cert.pem.
My certificate is a wildcard one for *.grupocitec.com
Then I have set, in the docker-container.yml file, this:
hostname: mail
domainname: grupocitec.com
environment:
  - DMS_SSL=self-signed

When I try to connect to the server, using a test@ account for grupocitec.com, it returns me with a certificate for common name 'localhost', why it doesn't take my certificate?

What am I doing wrong?
Thanks

**Comment by tomav** [comment]
Can you check that the SSL configuration is applied (you should see something in startup logs and check `smtpd_tls_cert_file` in `postfix/main.cf` in you running image).

**Comment by citec** [comment]
Hi, thanks to your answer, I could find where the start_mailserver.sh script was looking for the files. I was missing the cacert.pem. Now I am not getting the certificate warning, but I am getting a different error. I will open new issue for that. Thanks again.
