### ISSUE TITLE
[port closed] port 25 closed on my vps but binding included in docker-compose

### ISSUE THREAD

**Issue by Mathieu-R** [tomav/docker-mailserver#580]
I've got a problem with the port 25 (smtp).
I cannot deliver mail from outside _(eg. gmail)_, the provider send me back an e-mail telling me that the `mail server` is unreachable.

After some investigations, I noticed that the port 25 is actually closed on the vps as you can see here.

> There's **no** `port 25` open when I type `netstat -plnt`  on the vps : 
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::587                  :::*                    LISTEN      -               
tcp6       0      0 :::143                  :::*                    LISTEN      -               
tcp6       0      0 :::80                   :::*                    LISTEN      -               
tcp6       0      0 :::53                   :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 :::443                  :::*                    LISTEN      -               
tcp6       0      0 :::32768                :::*                    LISTEN      -               
tcp6       0      0 :::993                  :::*                    LISTEN      -    
```

> Here's the result of [http://www.dnsstuff.com/mstc](dnsstuff) where I can test a mail adress :     

![image](https://cloud.githubusercontent.com/assets/16360664/25278353/e263c308-26a2-11e7-8467-9df20908dd63.png)

However, I bound the port in `docker-compose.yml`, so it should be open to the outside.

```yml
mail:
   image: tvial/docker-mailserver:latest
   ...
  ports:
     - 25:25 # smtp
     - 143:143 # imap
     - 587:587 # smtp / ssl
     - 993:993 # imap / ssl
      ...
```

And the `mailserver` is running. 
> Here's a sample when I type `docker ps`. It seems to suggest that binding worked properly by the way.

```
5444bf0cfeb1        tvial/docker-mailserver:latest   "/bin/sh -c /usr/l..."   2 days ago          Up 2 days              25/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:587->587/tcp, 110/tcp, 995/tcp, 4190/tcp, 0.0.0.0:993->993/tcp,      0.0.0.0:32768->1525/tcp   woodytoys_mail_1
```

**Comment by tomav** [comment]
What about the firewall?
`sudo iptables -L`

**Comment by Mathieu-R** [comment]
I have authorized the port 25 in the firewall (ufw)

**Comment by tomav** [comment]
If you can't telnet from outside world on port 25:
- check the output `nc -z -v -w1 domain.com 25` (from the outside too)
- check that postfix process is up and running

**Comment by Mathieu-R** [comment]
In the container : 
```
root@mail:/# service postfix status
 * postfix is not running
root@mail:/# service postfix start
 * Starting Postfix Mail Transport Agent postfix                                                                                                                                                            postfix/postfix-script: fatal: the Postfix mail system is already running
```

**Comment by Mathieu-R** [comment]
But with `postfix status` : 
```
root@mail:/# postfix status
postfix/postfix-script: the Postfix mail system is running: PID: 1008
```

**Comment by tomav** [comment]
If on the container, `telnet 0.0.0.0 25` works, your issue is network related.

**Comment by Mathieu-R** [comment]
I confirm that `telnet 0.0.0.0 25` in the container works.
However `telnet localhost`on the `vps` does not work : 
```
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by Mathieu-R** [comment]
It's quiet odd but now the `port 25` is open.
I was just working on the dns container and restarted a few times the containers and suddenly as I was typing `netstat -plnt` I saw this.

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::587                  :::*                    LISTEN      -               
tcp6       0      0 :::110                  :::*                    LISTEN      -               
tcp6       0      0 :::143                  :::*                    LISTEN      -               
tcp6       0      0 :::80                   :::*                    LISTEN      -               
tcp6       0      0 :::53                   :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 :::25                   :::*                    LISTEN      -               
tcp6       0      0 :::443                  :::*                    LISTEN      -               
tcp6       0      0 :::993                  :::*                    LISTEN      -               
tcp6       0      0 :::995                  :::*                    LISTEN      -   
```

Things I have done the last few hours : 
- Activating `pop3`.
- Adding `- SASL_PASSWD` environment variable.
- Reworking the `dns` but it has nothing to do with the problem I had.

**Comment by thiesschneider** [comment]
Hey,

I had the same problem and had to downgrade to 2.2 (I was running the latest version before).
But in my netstat the port 25 was always open.
I use more than one domain. But I wonder if someone has the same problem?

**Comment by mabunixda** [comment]
Yeah also had to downgrade. AS far AS i was able to See clamav is running in foreground mode and Blocks the startup script...

**Comment by thiesschneider** [comment]
So perhaps we need to reopen the issue?

**Comment by tomav** [comment]
@Mathieu-R was running `2.2` (because 2.3 has been released 6 days after) so the latest comments should go in another thread.
I'm gonna close this one. There are other threads regarding 2.3. Feel free to add your comments there.
https://github.com/tomav/docker-mailserver/issues/586

**Comment by tomav** [comment]
@Mathieu-R that was `2.3`?

**Comment by thiesschneider** [comment]
fyi: In my case it was 2.3. So I had to downgrade to version 2.2.

**Comment by tomav** [comment]
I found that in 2.3, postfix changed some settings. http://www.postfix.org/COMPATIBILITY_README.html
I had my postfix not running on 2.3 for that reason:

```
May  6 10:36:51 mail postfix[6669]: Postfix is running with backwards-compatible default settings
May  6 10:36:51 mail postfix[6669]: See http://www.postfix.org/COMPATIBILITY_README.html for details
May  6 10:36:51 mail postfix[6669]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
```

Try to have a look on your side.

Another issue I had was related to `master.sock` file. For the moment, I disabled `ONE_DIR` and it seems ok (even if there are things to fix)

**Comment by tomav** [comment]
http://www.postfix.org/COMPATIBILITY_README.html#chroot to be more explicit

**Comment by thiesschneider** [comment]
So I need to disable ONE_DIR for now. Or should I wait until you fix it? :)

**Comment by Mathieu-R** [comment]
I used the `:latest` version. So if the `2.3` was not there. I suppose, I used `2.2`.

**Comment by tomav** [comment]
@thiesschneider I don't know how to fix it yet and don't have any time for that these days.
Want I can say, is when I look at logs, 2 or 3 errors may happen and should give good leads to find the solution.


The 3 errors to solve are:

```
May  6 12:36:14 mail postgrey[3623]: FATAL: ERROR: can't open lock file: /var/lib/postgrey/postgrey.lock#012

May  6 12:36:15 mail postfix[4414]: Postfix is running with backwards-compatible default settings
May  6 12:36:15 mail postfix[4414]: See http://www.postfix.org/COMPATIBILITY_README.html for details
May  6 12:36:15 mail postfix[4414]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"

May  6 12:36:15 mail postfix/master[4451]: fatal: open lock file /var/lib/postfix/master.lock: cannot create file exclusively: Permission denied
```

**Comment by tomav** [comment]
Let's move to #586
