### ISSUE TITLE
Spamassassin not enabled while docker-compose has ENABLE_SPAMASSASSIN=1

### ISSUE THREAD

**Issue by DracoMilesX** [tomav/docker-mailserver#581]
Latest version

In docker-compose in the environment their is ENABLE_SPAMASSASSIN=1
going to /etc/default/spamassassin in the docker machine shows ENABLED=0
It seems the environment setting is ignored?

Checked the headers to be certain and it only shows a X-Virus and not a X-Spam.

edit: a second question is it looks like my imap port 993 is not working. Trying to run the test:
docker exec mail openssl s_client -connect 0.0.0.0:993 -starttls imap -CApath /etc/ssl/certs/

but it looks like it hangs changing from /etc/ssl/certs to /etc/ssl/ where my own letsencrypt certs are shows same issue.

edit2: 
the issue with port 993

> 
> didn't found STARTTLS in server response, try anyway...
> write:errno=32
> CONNECTED(00000003)
> ---
> no peer certificate available
> ---
> No client certificate CA names sent
> ---
> SSL handshake has read 0 bytes and written 14 bytes
> ---
> New, (NONE), Cipher is (NONE)
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE

**Comment by k1ngf15h3r** [comment]
also think spamassassin is not working. can anyone confirm? only have X-Virus in headers and no X-Spam. manually enabling spamassassin in `/etc/default/spamassassin` and manually starting spamassassin does not work

**Comment by tomav** [comment]
This project uses amavis, which uses spamassassin librairies but not the daemon.

Here is the log of a recent mail I received:

```
Jun 27 12:17:40 mail amavis[4969]: (04969-01) Passed CLEAN {RelayedInbound}, [74.125.82.169]:34433 [74.125.82.169] <plop@gmail.com> -> <plop@domain.com>, Queue-ID: 3C45CA41820, Message-ID: <CAGMGVT-RpJvSC7rBm4DMZ=-CRL2TLQgdxDF-7bA5rhDZkRrRTg@mail.gmail.com>, mail_id: JZput62QqUwg, Hits: -1.519, size: 2994, queued_as: 09AF8A41844, dkim_sd=20161025:gmail.com, 1374 ms
Jun 27 12:17:40 mail postfix/smtp[8411]: 3C45CA41820: to=<plop@domain.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=2.3, delays=0.95/0.01/0.01/1.4, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 09AF8A41844)
```

you can see the `Hits` is the log. The same appears in the mail header on client side if configured correctly.
[This](https://github.com/tomav/docker-mailserver/blob/master/README.md#sa_tag) may help.

**Comment by tomav** [comment]
[This issue](https://github.com/tomav/docker-mailserver/issues/311) might also help.

**Comment by k1ngf15h3r** [comment]
Thanks for the hint 😊 do you have a hint how I can set special rules for amavis? I get much Newsletter on my account and want to filter them on arrival.

Best regards

Von: Thomas VIAL
Gesendet: Dienstag, 27. Juni 2017 14:24
An: tomav/docker-mailserver
Cc: Benjamin Hagels; Comment
Betreff: Re: [tomav/docker-mailserver] Spamassassin not enabled whiledocker-compose has ENABLE_SPAMASSASSIN=1 (#581)

This project uses amavis, which uses spamassassin librairies but not the daemon.
Here is the log of a recent mail I received:
Jun 27 12:17:40 mail amavis[4969]: (04969-01) Passed CLEAN {RelayedInbound}, [74.125.82.169]:34433 [74.125.82.169] <plop@gmail.com> -> <plop@domain.com>, Queue-ID: 3C45CA41820, Message-ID: <CAGMGVT-RpJvSC7rBm4DMZ=-CRL2TLQgdxDF-7bA5rhDZkRrRTg@mail.gmail.com>, mail_id: JZput62QqUwg, Hits: -1.519, size: 2994, queued_as: 09AF8A41844, dkim_sd=20161025:gmail.com, 1374 ms
Jun 27 12:17:40 mail postfix/smtp[8411]: 3C45CA41820: to=<plop@domain.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=2.3, delays=0.95/0.01/0.01/1.4, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 09AF8A41844)
you can see the Hits is the log. The same appears in the mail header on client side if configured correctly.
This may help.

**Comment by tomav** [comment]
Check [that page](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-manage-my-custom-spamassassin-rules). I'm sure this is widely used but you should try.

**Comment by DracoMilesX** [comment]
Thanks for the information. Guess that answers the question/issue.
