### ISSUE TITLE
Add integration for SMTP_ONLY=1 configuration option

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#583]
Check Mail send is working
Check SASL authentication is working
Check Relay is working
Check Relay with sasl authentication is working

**Comment by tomav** [comment]
Related to https://github.com/tomav/docker-mailserver/pull/556

**Comment by awb99** [comment]
I got similar problems, when I added a new user. I then had to do the following steps to get it to work again:
````  
  docker ps
  docker stop 41517ee9f89f
  docker rm mail
  ./start.sh
```

**Comment by tomav** [comment]
This is a very old bug, feel free to submit a PR if you found the issue.

**Comment by erik-wramner** [comment]
Now it is an extremely old bug. There are some tests and nobody is working on improving this. I'll close the issue.
