### ISSUE TITLE
Deleting mailstate folder solved all my connection problems

### ISSUE THREAD

**Issue by pcjmfranken** [tomav/docker-mailserver#585]
I've been having connection troubles without relevant output in server logs every time I add a mail address with the setup.sh script or change settings and restart the container. All the default services are green when this happens.

This has been going on since I started using this at version 2.0 and its still the case at version 2.3.

Removing the container, deleting the mailstate folder (**NOT** the mail*data* folder, for anyone who wants to try this) and then rebuilding the container seems to solve all my connection issues every single time.

Is this a bug or perhaps something that can be fixed, or should I just carry on doing what I'm doing?

**Comment by kuche1991** [comment]
I got a similiar Problem when updating the container.
After each pull, i have to delete the state Folder. Otherwise, the server is unreachable without any log-entry leading to this.

**Comment by theomega** [comment]
I also sometimes run into the issues that there are no logs anymore. Check #467 from me where I also propose a fix.
Although, I was always able to connect. So maybe a different issue.

**Comment by tomav** [comment]
There are permissions to fix on `2.3` regarding state folder.
Conversation should be moved there: https://github.com/tomav/docker-mailserver/issues/545
