### ISSUE TITLE
OpenDMARC configuration for DNS

### ISSUE THREAD

**Issue by matrixise** [tomav/docker-mailserver#587]
Hi,
The project is really awesome, thank you.

But, there is a command for the DKIM configuration and for the DNS server, but nothing for OpenDMARC and dmarc with DNS.

Do you have an example or a command to generate it ?

Thank you

**Comment by matrixise** [comment]
Hello,

I know that this issue is easy, but do you have a solution.

Thank you,

**Comment by jodumont** [comment]
Hi @matrixise 
You could use any DMARC Generator such as https://www.unlocktheinbox.com/dmarcwizard/

It's recommended to start with a low percentage and incrementing it week after week until 100%

A basic entry will be something like this:
```
Type Entry: TXT
Host Entry: _dmarc
Value: v=DMARC1; p=reject; rua=mailto:postmaster@YOURDOMAIN.LTD; ruf=mailto:postmaster@YOURDOMAIN.LTD

```

While a more complete setup will look like that:
```
Type Entry: TXT
Host Entry: _dmarc
Value: v=DMARC1; p=reject; rua=mailto:postmaster@YOURDOMAIN.LTD; ruf=mailto:postmaster@YOURDOMAIN.LTD; fo=0; adkim=s; aspf=s; pct=100; rf=afrf; sp=reject

```
