### ISSUE TITLE
ClueGetter intergration

### ISSUE THREAD

**Issue by arcaine2** [tomav/docker-mailserver#588]
Any plans to maybe intergrate ClueGetter into the mix? In general, i have no problem with my current setup but every once in a while i get reports about some missing e-mail, either sent or (to be) received and while most of these can be traced with logs, this would simplify this and produce more readable results.

**Comment by johansmitsnl** [comment]
Could you create a PR?

**Comment by arcaine2** [comment]
What do you mean by that? I don't feel skilled enough to integrate it, sadly.

**Comment by johansmitsnl** [comment]
PR means Pull Request.

Will add the labels for later development.
