### ISSUE TITLE
FeatureRequest: autoconfig

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#59]
Hi, if I get this working, I plan to add a web server container to render the autoconfig/mail/config-v1.1.xml files so email clients can be auto-configured.
Example of the xml file:
```
  <emailProvider id="domain.com">
    <domain>domain.com</domain>
    <displayName>My Mail</displayName>
    <displayShortName>mymail</displayShortName>
    <incomingServer type="imap">
      <hostname>mail.domain.com</hostname>
      <port>143</port>
      <socketType>STARTTLS</socketType>
      <authentication>password-cleartext</authentication>
      <username>%EMAILADDRESS%</username>
    </incomingServer>
    <outgoingServer type="smtp">
      <hostname>mail.domain.com</hostname>
      <port>587</port>
      <socketType>STARTTLS</socketType>
      <authentication>password-cleartext</authentication>
      <username>%EMAILADDRESS%</username>
    </outgoingServer>
  </emailProvider>
```
We could render that xml on the start-mailserver.sh script and share that file with the new web server, mounting it in both containers.

Do you like the idea of adding this to the project? I will have to do it anyway, so if you want I can PR it

**Comment by tomav** [comment]
Hi @citec, do you know which email client are currently supporting these xml files?

**Comment by citec** [comment]
I have been using it in thunderbird and it works great, just put email and pass, press next and it finds out everything. For outlook a different file is needed, I have never done that, but it seems easy:
https://i-mscp.net/index.php/Thread/3771-Mail-autoconfiguration-for-Thunderbird-and-Outlook/

**Comment by tomav** [comment]
Ok. Something seems to exist for Apple Mail: https://developer.apple.com/library/ios/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html

Regarding your implementation, why a webserver and not a command line tool?

**Comment by citec** [comment]
webserver because, the email clients query those files using http. Not sure about all the different email clients, buy I am sure that thunderbird does, for example. 
We could do similar as you do with start-mailserver.sh into a new container for the web server: the xml files will be rendered based on domainname, hostname and the accounts.cf file.
I prefer new container as it is a different service, even if they both share common accounts.cf file

**Comment by tomav** [comment]
I do agree, nice feature but in another image.

**Comment by tomav** [comment]
Let me know when it's done, I'll test it and link it in the documentation.
