### ISSUE TITLE
LDAP environment variables and ambiguous characters

### ISSUE THREAD

**Issue by tailtwo** [tomav/docker-mailserver#591]
Hello,

The user I use to bind to my LDAP server have a '&' character in its password. When this character is parsed, the string that correspond with the password in ldap-users.cf gets cut in two with `bind_pw          = admin`

Let's say my password is ABC&DEF:

docker-compose.yml
```bash
[...]
environment:
  - LDAP_BIND_PW=ABC&DEF
[...]
```

/etc/postfix/ldap-users.cf
```bash
[...]
bind_pw = ABCbind_pw          = adminDEF  
[...]
```

Even with quotes and double quotes, it stays the same.
Is there any way I can fix this other than entering it manually?

**Comment by alinmear** [comment]
Hello @tailtwo, 

to fix this we should have a look at the ldap method, especially the parsing of the env variables. Im pretty sure, that here this is happening.

Do you have time to investigate this?

**Comment by alinmear** [comment]
@tailtwo my pr #644 should fix the issues with the `&` within the ldap configurations. 

hopefully this helps!

**Comment by johansmitsnl** [comment]
It worked for me.

**Comment by alinmear** [comment]
Seems that there are no problems after #644. Closing ...
