### ISSUE TITLE
INTERNAL ERROR: cannot create temporary directory!

### ISSUE THREAD

**Issue by italoandrade** [tomav/docker-mailserver#593]
Hey guys, this issue I don't know if it is because of the docker-mailserver, but it only happens with it.

I already know how to "fix" this issue. I just need to free some space, and the only thing that I have in my server is this only docker (just to test it), and to free some space I have to delete the docker and recreate it, and the problem is gone.

I think this problem is because of the trash that the mailserver leaves behind. Is there anything I can do to avoid this? Like not keeping all those things (all the emails are redirected to my gmail account, so there's no problem on that).

**Comment by kiliant** [comment]
Hey,

Have you created your mail accounts as aliases? In that case I believe no mail should be stored locally.

What could be a problem, however, is the _mailstate_ folder. You can try to delete that from time to time, or disable postgrey.

**Comment by tomav** [comment]
@italoandrade could you also provide config / startup logs using `DMS_DEBUG=1`?
Thank you.

**Comment by italoandrade** [comment]
> Have you created your mail accounts as aliases? 

Yes, but I created as account too so I could use POP3 to answer.

> What could be a problem, however, is the mailstate folder. You can try to delete that from time to time, or disable postgrey.

Which one is better, like what are the downsides of disabling postgrey?

> could you also provide config / startup logs using DMS_DEBUG=1?

Sure. Here they are (if I got it right)

![config](https://cloud.githubusercontent.com/assets/19225266/25774062/3ee96264-325f-11e7-8a0e-6efe5eaa13f2.png)
[startup_log.txt](https://github.com/tomav/docker-mailserver/files/981028/startup_log.txt)

**Comment by tomav** [comment]
Hmm, cannot see any error in this startup log. What about when connecting a client? When do you see that error. We don't have any context yet to help.

**Comment by italoandrade** [comment]
> When do you see that error. We don't have any context yet to help.

Ohh, sorry. That error isn't on the log of the mailserver. It is on the machine, when the disk is full and I try to use any "docker-compose" command. As I mentioned, I don't think there is any problem with the mailserver, my problem is only the disk that is being filled by the mailserver temporary files (at least I think they are temporary, because if I turn the docker with the mailserver image down and put it back up again, the problem is "solved").
You must be wondering now why I opened an issue here. It is because I think other people might have the same problem (as I'm on a very common situation, built a machine on Amazon, installed Docker-compose, put the docker-mailserver image, and just started it. Nothing customized.

**Comment by tomav** [comment]
Ok, I close this issue then. Thanks for the update.
