### ISSUE TITLE
Modifications to master.cf

### ISSUE THREAD

**Issue by MadsRC** [tomav/docker-mailserver#594]
I haven't been able to find any build-in way to edit the master.cf in this image?

I'm in need of modifying it to allow submission of email on port 587 (Adding permit_mynetworks to client and recipient restrictions) and doing so manually is error-prone.

Does anyone have a way of doing this with this image?

If not, I'm preparing a PR allowing one to add a postfix-master.cf containing the config, in `postconf -P` format, just like adding the main.cf.

**Comment by bobbravo2** [comment]
I haven't seen any way to accomplish this yet

**Comment by tomav** [comment]
Referencing your PR https://github.com/tomav/docker-mailserver/pull/595

**Comment by MadsRC** [comment]
I'll ret to finish the integration test in the coming days - Time is in short supply at the moment though.

**Comment by tomav** [comment]
Thanks, no problem!

**Comment by johansmitsnl** [comment]
@MadsRC this issue can be closed?

**Comment by fbartels** [comment]
Should be resolved by https://github.com/tomav/docker-mailserver/pull/595
