### ISSUE TITLE
LetsEncrypt SSL Issue

### ISSUE THREAD

**Issue by nicholasball** [tomav/docker-mailserver#599]
Hi all,

Firstly, thank you for creating this project - it was very much needed!

I seem to be having issues with the mailserver using the LetsEncrypt SSL certificate option in the docker-compose.yml file:

`- SSL_TYPE=letsencrypt`

When using it, I seem to get the self-signed certificates coming up even though the location of the letsencrypt certs is correct:

`/etc/letsencrypt/live`

Does anyone know of anything I can do to debug, or even better fix this issue?

**Comment by mabunixda** [comment]
Die you Mount your /etc/letsencrypt folder to the container?

**Comment by tomav** [comment]
Yep, there's a a check on provided files. 
@nicholasball have a look to this part of the code: https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L721-L745

**Comment by nicholasball** [comment]
@mabunixda I thought I was, but maybe I'm doing it wrong. Not great with compose tbh.
I have this configured at the moment:

`certs:/etc/letsencrypt/live`

The certificates are in the certs folder on the same level as the yml file. Does this sound correct?

**Comment by mabunixda** [comment]
Hmm no you must create the certs in the host before Passing them to the container

**Comment by nicholasball** [comment]
I have the certs created, placed them both in /certs/ and in the directory where the yml config file is.  Maybe I'm missing something?

**Comment by nicholasball** [comment]
Did an inspect on the docker container and I get this configuration:

`...
            {
                "Type": "bind",
                "Source": "/home/docker-mailserver/certs",
                "Destination": "/etc/letsencrypt/live",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
...
`
And nothing from the logs indicating that the SSL cert are being used:

`
...
mail    |   Setting up DKIM
mail    |   * DKIM keys added for: XXX.com
mail    |   * Changing permissions on /etc/opendkim
mail    |   Setting up SSL
mail    |   Setting up PERMIT_DOCKER Option
mail    |   * Adding container ip in my networks
...
`

**Comment by nicholasball** [comment]
OK I got it to work. Seems as though I had an issue with the actual cert files as well as mounting them to the correct place.

Thanks all

**Comment by tomav** [comment]
Great!

**Comment by Shifter2600** [comment]
Sorry to open this back up but what was the solution. I am having the same issue. Can you share your compose yml?

**Comment by righthandman** [comment]
Yes, plz

**Comment by k1ngf15h3r** [comment]
Same Problem here! Added `/root/docker/letsencrypt/etc/letsencrypt:/etc/letsencrpyt` to volumes in the `docker-compose.yml` certs were generated on host successfully.

Can you please share the solution?!

**Comment by k1ngf15h3r** [comment]
I think I have found the solution
This:
```
docker run --rm -ti -v $PWD/log/:/var/log/letsencrypt/ -v $PWD/etc/:/etc/letsencrypt/ -p 443:443 deliverous/certbot certonly --standalone -d mail.myserver.tld
```
Must be like this:
```
docker run --rm -ti -v $PWD/log/:/var/log/letsencrypt/ -v $PWD/etc/letsencrypt/:/etc/letsencrypt/ -p 443:443 deliverous/certbot certonly --standalone -d mail.myserver.tld
```
in the wiki part ....
