### ISSUE TITLE
Starting ClamAV daemon clamd: fail!

### ISSUE THREAD

**Issue by jeroenlammerts** [tomav/docker-mailserver#6]
Using docker-compose up
Ubuntu 14.04

    mail_1 | Starting SpamAssassin Mail Filter Daemon: spamd.
    mail_1 |  * Starting ClamAV daemon clamd 
    mail_1 |    ...fail!
    mail_1 | Starting amavisd: amavisd-new.
    mail_1 |  * Starting Postfix Mail Transport Agent postfix
    mail_1 |    ...done.
    mail_1 | Listing SASL users
    mail_1 | info@mydomain.com: userPassword
    mail_1 | Starting...
    mail_1 | May 12 11:49:51 mail amavis[506]: Found decoder for    .zoo  at /usr/bin/zoo
    mail_1 | May 12 11:49:51 mail amavis[506]: No decoder for       .doc  tried: ripole
    mail_1 | May 12 11:49:51 mail amavis[506]: Found decoder for    .cab  at /usr/bin/cabextract
    mail_1 | May 12 11:49:51 mail amavis[506]: No decoder for       .tnef
    mail_1 | May 12 11:49:51 mail amavis[506]: Internal decoder for .tnef
    mail_1 | May 12 11:49:51 mail amavis[506]: Found decoder for    .exe  at /usr/bin/arj
    mail_1 | May 12 11:49:51 mail amavis[506]: Using primary internal av scanner code for ClamAV-clamd
    mail_1 | May 12 11:49:51 mail amavis[506]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
    mail_1 | May 12 11:49:51 mail amavis[506]: Deleting db files  in /var/lib/amavis/db
    mail_1 | May 12 11:49:51 mail amavis[506]: Creating db in /var/lib/amavis/db/; BerkeleyDB 0.54, libdb 5.3
    mail_1 | May 12 11:49:52 mail postfix/master[600]: daemon started -- version 2.11.0, configuration /etc/postfix

When sending to the server:

    mail_1 | May 12 11:38:00 mail amavis[602]: (00602-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
    mail_1 | May 12 11:38:01 mail amavis[602]: (00602-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
    mail_1 | May 12 11:38:01 mail amavis[602]: (00602-01) (!)ClamAV-clamd: All attempts (1) failed connecting to /var/run/clamav/clamd.ctl, retrying (2)
    mail_1 | May 12 11:38:07 mail amavis[602]: (00602-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
    mail_1 | May 12 11:38:07 mail amavis[602]: (00602-01) (!)ClamAV-clamd av-scanner FAILED: run_av error: Too many retries to talk to /var/run/clamav/clamd.ctl (All attempts (1) failed connecting to /var/run/clamav/clamd.ctl) at (eval 136) line 603.\n

**Comment by tomav** [comment]
Hi @jeroenlammerts, can I get your `docker-compose.yml` or `command line`?
Thank you.

**Comment by jeroenlammerts** [comment]
mail:
  # image: tvial/docker-mailserver
  build: .
  hostname: mail
  domainname: cloudmailer.nl
  ports:
  - "25:25"
  - "143:143"
  - "587:587"
  - "993:993"
  environment:
    docker_mail_domain: "cloudmailer.nl"
    # format is user@domain.tld|clear_password
    docker_mail_users:
      - "info@cloudmailer.nl|secret!"
      - "bounce@cloudmailer.nl|secret!"
    # format is user@domain.tld|list,of,aliases,comma,separated
    docker_mail_aliases:
      - "info@cloudmailer.nl|support"

**Comment by tomav** [comment]
@jeroenlammerts, just tried your `docker-compose.yml` with the image available on the registry and it works.

➜  docker-mailserver git:(master) ✗ docker-compose up mail
    Recreating dockermailserver_mail_1...
    Attaching to dockermailserver_mail_1
    mail_1 | Regenerating 'vmailbox' for given users
    mail_1 | user 'info' for domain 'cloudmailer.nl' with password 'secret!'
    mail_1 | user 'bounce' for domain 'cloudmailer.nl' with password 'secret!'
    mail_1 | Regenerating 'virtual' for given aliases
    mail_1 | support@cloudmailer.nl redirects to info@cloudmailer.nl
    mail_1 | Postfix configurations
    mail_1 | Fixing permissions
    mail_1 | Creating /etc/mailname
    mail_1 | Starting daemons
    mail_1 |  * Starting enhanced syslogd rsyslogd
    mail_1 |    ...done.
    mail_1 |  * Starting file alteration monitor FAM
    mail_1 |    ...done.
    mail_1 |  * Starting  saslauthd
    mail_1 |    ...done.
    mail_1 |  * Starting Courier authentication services authdaemond
    mail_1 |    ...done.
    mail_1 |  * Starting Courier IMAP server imapd
    mail_1 |    ...done.
    mail_1 |  * Starting Courier IMAP-SSL server imapd-ssl
    mail_1 |    ...done.
    mail_1 | Starting SpamAssassin Mail Filter Daemon: spamd.
    mail_1 |  * Starting ClamAV daemon clamd
    mail_1 | LibClamAV Warning: **************************************************
    mail_1 | LibClamAV Warning: ***  The virus database is older than 7 days!  ***
    mail_1 | LibClamAV Warning: ***   Please update it as soon as possible.    ***
    mail_1 | LibClamAV Warning: **************************************************
    mail_1 |    ...done.
    mail_1 | Starting amavisd: amavisd-new.
    mail_1 |  * Starting Postfix Mail Transport Agent postfix
    mail_1 |    ...done.
    mail_1 | Listing SASL users
    mail_1 | bounce@cloudmailer.nl: userPassword
    mail_1 | info@cloudmailer.nl: userPassword
    mail_1 | Starting...
    mail_1 | May 12 12:00:57 mail amavis[507]: No decoder for       .doc  tried: ripole
    mail_1 | May 12 12:00:57 mail amavis[507]: Found decoder for    .cab  at /usr/bin/cabextract
    mail_1 | May 12 12:00:57 mail amavis[507]: No decoder for       .tnef
    mail_1 | May 12 12:00:57 mail amavis[507]: Internal decoder for .tnef
    mail_1 | May 12 12:00:57 mail amavis[507]: Found decoder for    .exe  at /usr/bin/arj
    mail_1 | May 12 12:00:57 mail amavis[507]: Using primary internal av scanner code for ClamAV-clamd
    mail_1 | May 12 12:00:57 mail amavis[507]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
    mail_1 | May 12 12:00:57 mail amavis[507]: Deleting db files  in /var/lib/amavis/db
    mail_1 | May 12 12:00:57 mail amavis[507]: Creating db in /var/lib/amavis/db/; BerkeleyDB 0.54, libdb 5.3
    mail_1 | May 12 12:00:57 mail postfix/master[601]: daemon started -- version 2.11.0, configuration /etc/postfix

Could you please try with the image?
Have you modified the `Dockerfile` or another file of the git repository?

Thank you.

**Comment by jeroenlammerts** [comment]
Thanks for your quick help!

I tried this on osx and it is working there, but still have the issue on ubuntu.

I'm using a Digitalocean droplet:

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

docker version:

Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64

docker-compose 1.2.0

**Comment by jeroenlammerts** [comment]
Looks like the issue is not in your image. I have the same error as here:
https://www.digitalocean.com/community/questions/clamav-daemon-fails-to-load-due-to-memory-any-way-to-run-clamscan-on-demand-for-attachments

I appreciate your help very much!

**Comment by tomav** [comment]
Hmmm.... had a memory issue, not with docker, but with capistrano when compiling assets on Digitalocean. I resolved my issue [with this](https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04).
Hope this helps.
