### ISSUE TITLE
authentication failed

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#60]
Hi, I have set up everything, I get all green in checktls.com (my server is cepheus.grupocitec.com). The server receives ok the mails from other servers, and creates correctly the files in the mail dir, etc.
BUT: I continue getting the wrong password error. I have even tried:
`testsaslauthd -u test@cepheus.grupocitec.com -p myPlainPassword smtp`
and I get:
`0: NO "authentication failed"`
The user exists, but I cannot log in. I have tried all kinds of authentications mechanism (using all possible ones in thunderbird), but it doesn't work.

Any ideas?

**Comment by tomav** [comment]
Try like this: https://github.com/tomav/docker-mailserver/pull/50/files#diff-b8765e8e12fe5b90ee3f4f3a864b5d96R18

**Comment by citec** [comment]
thanks, but nothing, still:
` 0: NO "authentication failed"`

**Comment by citec** [comment]
could you paste here some account.cf file working? just a sample with dummy passwords or something, I suspect that I am doing something wrong in that file

**Comment by tomav** [comment]
Try with test data in `test/` folder.

**Comment by citec** [comment]
ok, I will, thanks

**Comment by tomav** [comment]
➜  docker-mailserver git:(master) make run
    # Copy test files
    cp test/accounts.cf postfix/
    cp test/virtual postfix/
    # Run container
    docker run -d --name mail -v "`pwd`/postfix":/tmp/postfix -v "`pwd`/spamassassin":/tmp/spamassassin -v "`pwd`/test":/tmp/test -h mail.my-domain.com -t tvial/docker-mailserver:
    e92bbe74e2609bd93282e38e70fb0755b7d9e44ec263580abd1a48d14cb77428
    sleep 25

    ➜  docker-mailserver git:(master) ✗ docker exec mail testsaslauthd -u user2 -r otherdomain.tld -p mypassword
    0: OK "Success."

**Comment by tomav** [comment]
#44 & #47

**Comment by citec** [comment]
ok, now the test works, maybe I had bad file encoding or something. So test as you told me to do works, but not when I try to connect from the email client from another machine 
The log is not very specific:
```
mail_1 | Jan 21 18:24:06 mail imapd: Connection, ip=[::ffff:189.76.136.83]
mail_1 | Jan 21 18:24:07 mail imapd: Disconnected, ip=[::ffff:189.76.136.83], time=1
```

**Comment by tomav** [comment]
You should see something like that when it works:

    Jan 22 09:01:07 mail imapd-ssl: Connection, ip=[::ffff:192.168.1.254]
    Jan 22 09:01:07 mail imapd-ssl: LOGIN, user=user@domain.com, ip=[::ffff:192.168.1.254], port=[55971], protocol=IMAP

Try:

    telnet mail.domain.com 143
    # then when connection is open
    a1 LOGIN user@domain.com MyPassword
    # you should see "a1 OK Logged in."

**Comment by tomav** [comment]
@citec does it work sing telnet?

**Comment by citec** [comment]
yes, it works, so I guess I am doing something wrong in the mail client

**Comment by citec** [comment]
ok, imap without sasl works from email client now. so the problem is with sasl, right ?

**Comment by citec** [comment]
how do I test sasl login with telnet ? I remember there was some username:password hash

**Comment by tomav** [comment]
Easily testable using telnet for `PLAIN` and `LOGIN`.
I'm currently adding tests so you will soon have working example.

`CRAM-MD5` and `DIGEST-MD5` are more complicated to test manually because you have to compute data sent by the server before sending it back.

I'll let you know.

**Comment by tomav** [comment]
@citec you can have a look to http://www.fehcom.de/qmail/smtpauth.html
Working examples available here: https://github.com/tomav/docker-mailserver/blob/master/test/auth/smtp-auth-login.txt and https://github.com/tomav/docker-mailserver/blob/master/test/auth/smtp-auth-plain.txt

**Comment by tomav** [comment]
BTW, pull the latest image, I fixed a bug.

**Comment by citec** [comment]
Hi, I won't have time till february now, but I will try it. Thanks very much.

**Comment by tomav** [comment]
@citec I'll let you reopen this is you have any problem.
