### ISSUE TITLE
User authentication problem ( or is it my DNS, or is it my DNS and SSL ? )

### ISSUE THREAD

**Issue by Inkimar** [tomav/docker-mailserver#600]
Hello!

I am trying to set up **docker-mailserver:2.3** in the following project ( branch = improve-1 )
https://github.com/DINA-Web/mail-docker/tree/improve-1

I am a bit of a novice when it comes to mail-servers.

In my docker-compose.yml-file I am starting up the following containers:

1. **fs_mail** ( here are my volumes)
2. **mail** (here is my  tvial/docker-mailserver:2.3 )
3.  **dnsmasq** ( for DNS )
4.  **proxy** ( proxy-server, for SSL - not provided now )

Before I start my project I do the following ( see the README.md-file )

1. pull down the 'tvial/docker-mailserver:2.3'
2. run 'make fetch-setup' - I fetch the setup.sh-script
3. run 'make setup' - I am setting up the address ( akranes@mail.dina-web.net with password = akranes ) 
4. run './dkim_setup.sh'
5. run 'make up'

I am not totally sure what the dkim brings to this ( being a novice as stated earlier, but I seem not to be able to start up the docker-mailserver without running the dkim_setup.sh-script - do I need that !? )

```
$ ./setup.sh email list
akranes@mail.dina-web.net
``` 
```
$ cat config/postfix-accounts.cf 
akranes@mail.dina-web.net|{SHA512-CRYPT}$6$27hosYwcUN5VKCMK$uXzNh3lDueDwW0QFkWWdAox01MM.4dAisKo5Uye9ETOJhHMFwvtJ6syECB7Jzf2Iq2OM7BTs0KIIy5R7.HVbS. 
```
it seems like the credentials have been set up correctly.

When the project is up and running my next step is to configure the  email akranes@mail.dina-web.net  in Mozilla Thunderbird (version 45.8.0), before I do this I have modified /etc/hosts ( adding mail.dina-web.net) and I remove my internet connection - forcing Thunderbird to go to docker-mailserver.
![2017-05-10 14-01-22_thunderbird](https://cloud.githubusercontent.com/assets/3329613/25899209/44f941e6-358f-11e7-89d5-b46c99a61b70.png)
'Looking up configuration : Mozilla ISP database' 

In my logs (_docker-compose logs -f_ ) I can see the following : 
I can see that akranes@mail.dina-web.net  is 'knocking on the mail-server door' 
Then I get some SSL errors ( TLS and SSL ) 

Then nothing more happens, the 'Looking up configuration : Mozilla ISP database'  -keeps on rolling.

So, it seems like I am near some kind of solution - but on the other hand not.
I hope that you can give me some good advice here on how to continue from my starting-point ( https://github.com/DINA-Web/mail-docker/tree/improve-1 )

Best regards, i

**Comment by tomav** [comment]
Hi @Inkimar, thanks for using this project!
Few things to share with you:
* We have identified bugs on 2.3 so you should use 2.2. The features are almost the same except the software version
* Could you share startup log (use `DMS_DEBUG=1` and connection log?

Thanks.

**Comment by Inkimar** [comment]
Hi @tomav 
Thank you for the good advice!!

I changed from version 2.3 to version 2.2.
added DMS_DEBUG=1 and got a large startup-log

Sent an email from 'akranes@mail.dina-web.net' to 'akranes@mail.dina-web.net' - 
The Thunderbird  'add security exception'-window popped up.
The email was delivered, I can see it in both the 'Sent'-box and the 'Inbox'.

I hope that you can read the linked log-files :
**Here is the startup-log** 
https://nrmowncloud.nrm.se/owncloud/index.php/s/bB3rSAV1R871T5j

**Here is the log when Thunderbird is sending** 
https://nrmowncloud.nrm.se/owncloud/index.php/s/VafMiGyUni01s0T


I have some crt and key-files ( below , the crt-files are the same and so are the key-files )

- dina-web.net.crt
- dina-web.net.key
- mail.dina-web.net.crt
- mail.dina-web.net.key

I guess I have to add them to 'nginx-proxy-certs'-directory so that I can use SSL.
Or go with your letsencrypt-route ?

So it seems that I can use this setting ?
DKIM , is that necessary ( beeing a novice in this mail-server business )

regards, i

**Comment by tomav** [comment]
Why are you using nginx? You can reach your server using SSL directly.

**Comment by tomav** [comment]
DKIM is clearly recommended.

**Comment by Inkimar** [comment]
Hi,
I have multiple servers/services in the project, that is  the reason for nginx  - I store the SSL-cert there (a star cert) , common cert for all the services handled by nginx.

-i

**Comment by Inkimar** [comment]
Hi @tomav,
Thanks for the question about nginx, it slipped into that repo (I have now removed it).
I have 'refactored' the project, now running locally and waiting for a launch in production.
https://github.com/DINA-Web/mail-docker/tree/improve-1

DKIM is there as well.

-i

**Comment by tomav** [comment]
Great!
