### ISSUE TITLE
SPF Check failed in Swarm MOde

### ISSUE THREAD

**Issue by Berndinox** [tomav/docker-mailserver#601]
Mailserver does not see incoming IP if Swarm-Mode is used

`me@berndklaus.at received a message from **10.255.0.4** from a mail server claiming to be mxout.a1telekom.at.`

The 10.255.x Range is from the Ingress Network.

How to fix / disable SPF Check?
Thanks, BR Bernd

**Comment by Berndinox** [comment]
Hy, fatal Problem in Swarm Mode still exists, any Ideas on how to disable SPF check?

**Comment by johansmitsnl** [comment]
There is no way to disable the SPF checks.
Setting the https://github.com/tomav/docker-mailserver#permit_docker doesn't work?
Not sure if your container is on the same network.

**Comment by Berndinox** [comment]
Dont know how, but Problem has resolved...

**Comment by johansmitsnl** [comment]
Ok then. I'll close the issue.
