### ISSUE TITLE
HTTP Errors

### ISSUE THREAD

**Issue by rdearman** [tomav/docker-mailserver#603]
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

I've upped the time limit to 2400 and it still didn't work? I'm running on AWS, and I don't believe I have a slow connection, so I'm at a loss. Any suggestions?

**Comment by bobbravo2** [comment]
Try running it locally first?

**Comment by rdearman** [comment]
OK, I'll give that a try. I should have mentioned that it did work for a couple of days just pulling it.

**Comment by rdearman** [comment]
I've tried to build it locally with git clone, but seem to encounter the same problem. I don't know how to setup debugging or provide you with any logs. :(

**Comment by tomav** [comment]
The build succeeded? What about testing `2.2` image locally with compose?

**Comment by tomav** [comment]
Get the example in the project and use `2.2` image.
Boot it on foreground with `DMS_DEBUG=1` env.
Paste the entire log here.

If compose does not work, it's probably not related to this image.
Try with another one.

**Comment by rdearman** [comment]
OK, the problem isn't with this container, it seems to be with docker itself having lost it's configuration file.

> docker.auth.auth.load_config: File doesn't exist

**Comment by tomav** [comment]
OK, I'm going to close this issue  but feel free to add a comment you have a solution, It may help other users
