### ISSUE TITLE
Issue when trying to add/list alias

### ISSUE THREAD

**Issue by gfediere** [tomav/docker-mailserver#606]
Hi,

I just tried this project which work pretty well so first a big thanks for your work !

I have a problem while using alias. Can't create or list those, error is:
`docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"listalias\": executable file not found in $PATH"`

It fails with command:
`docker run --rm -v /data/docker/docker-mailserver/config:/tmp/docker-mailserver -ti tvial/docker-mailserver:2.1 listalias`

If someone already met this behavior and help me with 🥇

**Comment by tomav** [comment]
Hi @gfediere, Wiki may help:
https://github.com/tomav/docker-mailserver/wiki/Setup-docker-mailserver-using-the-script-setup.sh

Let me know.

**Comment by gfediere** [comment]
Hi @tomav I used this script and get this error

**Comment by tomav** [comment]
Documented as `./setup.sh alias list`, not `list alias`, no?

**Comment by gfediere** [comment]
this is the command i ran:
```./setup.sh alias list
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"listalias\": executable file not found in $PATH".```

**Comment by johansmitsnl** [comment]
@gfediere  Is this still an issue?

**Comment by gfediere** [comment]
Hi,

It didn't work using command line, but I create aliases by hand in the config file

**Comment by johansmitsnl** [comment]
@gfediere There are tests for this feature
https://github.com/tomav/docker-mailserver/blob/97e296162f873137700ecd3776867d6f0d22c85a/test/tests.bats#L989-L993
https://github.com/tomav/docker-mailserver/blob/97e296162f873137700ecd3776867d6f0d22c85a/test/tests.bats#L994-L1001
When you run it today with the latest code it is still an issue?

**Comment by johansmitsnl** [comment]
Is it solved?
If yes please share and close the solution.
