### ISSUE TITLE
Assumes existance of eth0 device

### ISSUE THREAD

**Issue by nalt** [tomav/docker-mailserver#607]
If there is not eth0 device, setup fails with "Device eth0 not found". Some docker network configs do not have eth0.

**Comment by tomav** [comment]
True, `eth0` seems hardcoded here: https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L845

**Comment by johansmitsnl** [comment]
Could you create a PR?

**Comment by cofilippo** [comment]
I notice this issue is still open. Does this mean that I won't be able to use my bridged config properly? (br0 bridges eth0 on my machine)

**Comment by erik-wramner** [comment]
Closed in favor of #1227 (duplicate).
