### ISSUE TITLE
IMAP Port remotely not open

### ISSUE THREAD

**Issue by awb99** [tomav/docker-mailserver#609]
I just installed the new version. Imap works from localhost but not remotely. Nmap shows also remote access works. But telnet remotely does not work. Ports are napped correctly on docker. Any ideas?

**Comment by awb99** [comment]
I somehow fixed the isssue by disabling all kind of settings:
```
    environment:
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=0
    - ONE_DIR=0
    - DMS_DEBUG=1
```

**Comment by righthandman** [comment]
Same issue here disabling FAIL2BAN allowed me to telnet remotely

**Comment by ndouglas** [comment]
This apparently fixed issues for me too.  Thanks @awb99, @destinatis.

**Comment by ericblade** [comment]
Had to do this also.  Running in Windows, if that's any help.  (also had to disable SPF)
