### ISSUE TITLE
Use more secure minimal linux distro?

### ISSUE THREAD

**Issue by rubytastic** [tomav/docker-mailserver#61]
How about using a more secure minimal linux distro.
If this is to be run at CoreOS

**Comment by tomav** [comment]
Let's see what users think bout that.

**Comment by citec** [comment]
+1 , but not priority, in my opinion. I think we should put all functionality in it first (dkim, autoconfig, backup, etc)

**Comment by tomav** [comment]
Backup exists. DKIM is being upgraded to multi-domains.
Autoconfig is external. So, we're close.

**Comment by citec** [comment]
yes, agree. I would put also pop, etc. There is a lot of users still using those protocols.

**Comment by tomav** [comment]
Yes, but the goal is not have a "one size fits all" which will be another average docker image. The goal is to have clear choices on what's best and most simple.
That was my point on `pop` protocole. It could enter this image but should not be enable by default, `imap` being a better alternative.

**Comment by bilak** [comment]
I was thinking about rewriting this image to [centos](https://www.centos.org/).
If I have time next week, I will try to rewrite it.

**Comment by rubytastic** [comment]
Im still investigating a clean small linux distro to be used for all containers.
Have not found a good solution yet. Think centOS is also to full-stack.

**Comment by slintes** [comment]
have a look at Alpine Linux:
- http://www.alpinelinux.org/
- http://wiki.alpinelinux.org/wiki/Hosting_Web/Email_services_on_Alpine

**Comment by bilak** [comment]
I was working today with CoreOS and this is not OS for installation of mail-server. It's used for "containerization" - something like [Project Atomic](http://www.projectatomic.io/). Alpine linux is based on busybox and I'm affraid that there won't be all required packages for this docker.

**Comment by dominikwinter** [comment]
As has already been said by @bilak CoreOS is for the docker host.

@rubytastic What do you mean by "secure" distribution? Take the biggest one like Debian, Ubuntu or CentOS (or for enterprise: SUSE Linux, Red Hat) to get as fast as possible security patches.

**Comment by tomav** [comment]
:+1: @dominikwinter

**Comment by tomav** [comment]
The host should provide security, CoreOS being a good solution.
Currently, no plan to go from ubuntu to something else so I close this issue.
Let's check during the next months if we have good alternatives and what is the gain of such change.
Feel free to comment.

**Comment by Gymnae** [comment]
I'm currently setting up a host with CoreOS and most images based on Alpine.
Maybe I'm ignorant, but couldn't it be as simple as just to change the FROM and make sure that all packages are available in Alpine?
The only caveat I see are potentially different paths.

Alpine Linux is just 5MB and pretty quick with updates, also regarded secure.
I'll fork and see how badly I fail :)
