### ISSUE TITLE
postgrey is version 1.35, which is ancient…

### ISSUE THREAD

**Issue by kortenkamp** [tomav/docker-mailserver#616]
The problem with the 1.35 version of postgrey is that it comes with a 3 year old whitelist file. Current version of postgrey is 1.36.

An alternate solution could be to just update the whitelist_clients file, but it would be cleaner to use 1.36 directly. The 1.36 package is in Debian testing.

**Comment by johansmitsnl** [comment]
It is the version that Ubuntu ships in their LTS release.
Perhaps switching to Debian stable is a better approach because it gets more and better backports?
@tomav are there specific reasons to use Ubuntu as the base OS?

**Comment by kortenkamp** [comment]
To me it seems that getting the whitelist file from the post grey GitHub is even better – there are changes to it quite frequently, while new releases are very rare.

**Comment by johansmitsnl** [comment]
There is an option to add local entries:

https://help.ubuntu.com/community/PostfixGreylisting
> To add your own list of whitelisted clients in addition to the default ones, create the file /etc/postgrey/whitelist_clients.local and enter one host or domain per line.

With this you can mount your own file (the one from github or any other) on that place and it will solve #711 and this issue ass well.

I agree fully that Ubuntu should keep packages like this more up to date, but I also think overriding packages with "random" files is also not the way to go.

Is this a valid solution for you?

**Comment by kortenkamp** [comment]
Yes, that solution is fine for me, and actually it's what I did. But let me suggest to seed the config files with the latest postgrey whitelist, or at least add a recommendation to the Readme.md in order to let people know what they should do if they are going to use postgrey.

**Comment by mwlczk** [comment]
might be closed with this [PR](https://github.com/tomav/docker-mailserver/pull/784)

**Comment by johansmitsnl** [comment]
#784 is merged. No override should be needed. Closing the issue.

**Comment by kortenkamp** [comment]
Great, thank you @mwlczk and @johansmitsnl!
