### ISSUE TITLE
Filebeat within mailserver container needs to be updated

### ISSUE THREAD

**Issue by techgourmet** [tomav/docker-mailserver#617]
Hi,

the current version of filebeat installed is filebeat version (1.3.1).
This version however is not compatible with the current version of the elastic stack.
Can you update it to 5.x (latest)

Thanks in advance.

Best regards, 

Roy van der Linden

**Comment by MadsRC** [comment]
I have been having a few issues related to the logs parsed to my ELK stack, but haven't had the time to look more into it. Could be related to this though.

I'll have a look one day and try to see if I can get it upgrade, then do a pull request

**Comment by johansmitsnl** [comment]
@MadsRC did you manage to create a PR?

**Comment by techgourmet** [comment]
Any updates already?

**Comment by Shemeikka** [comment]
I believe this might be a small and easy change, though I haven't tested this on this image.

This line on Dockerfile

`curl https://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add - && \ echo "deb http://packages.elastic.co/beats/apt stable main" | tee -a /etc/apt/sources.list.d/beats.list && \`

should be changed to

`curl https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add - && \ echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-5.x.list && \
`

[Current Filebeat installation instructions](https://www.elastic.co/guide/en/beats/filebeat/5.6/setup-repositories.html)

**Comment by johansmitsnl** [comment]
@Shemeikka could you suggest a PR?
I have no setup for testing this.

**Comment by Shemeikka** [comment]
Hi,

I updated filebeat to latest stable version and tested this change or at least tried to test. There were few tests that failed, mainly related to accounts and logins. Nothing to do with this change.

Those failed tests caused mail to exit (Error: Please fix your configuration. Exiting...)

It's worth mentioning that filebeat 5.x is a [breaking change](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-5.0.0.html) to 1.3.1

**Comment by techgourmet** [comment]
Hi
What is the error you are getting causing the exit of the mail?

Br,

Roy

**Comment by erik-wramner** [comment]
Filebeat is now gone from the container, so this is no longer relevant. Closing.
