### ISSUE TITLE
SSL_accept error

### ISSUE THREAD

**Issue by pcjmfranken** [tomav/docker-mailserver#620]
Using latest repo version, letsencrypt certificates, no custom config except for spamhaus smtpd_recipient_restrictions.

I receive the following errors and warnings:
```
May 23 09:35:16 mail postfix/smtpd[5982]: connect from d5152ddd0.static.telenet.be[81.82.221.208]
May 23 09:35:16 mail postfix/smtpd[5982]: SSL_accept error from d5152ddd0.static.telenet.be[81.82.221.208]: -1
May 23 09:35:16 mail postfix/smtpd[5982]: warning: TLS library problem: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:s3_srvr.c:1417:
May 23 09:35:16 mail postfix/smtpd[5982]: lost connection after STARTTLS from d5152ddd0.static.telenet.be[81.82.221.208]
May 23 09:35:16 mail postfix/smtpd[5982]: disconnect from d5152ddd0.static.telenet.be[81.82.221.208] ehlo=1 starttls=0/1 commands=1/2

```

Please let me know if more information is required.

**Comment by TheReal1604** [comment]
@pcjmfranken seems that the server client / server that try to connect is using sslv3 with deprecated / unsecure ciphers, so your server is rejecting the connection.

**Comment by pcjmfranken** [comment]
Thank you for your quick reply, I have notified the sender.

I have to admit that the information on this error that I could find using Google was more than a little bit confusing.
