### ISSUE TITLE
Add z-push

### ISSUE THREAD

**Issue by thiesschneider** [tomav/docker-mailserver#622]
Hi,

there was an idea to add z-push (https://github.com/tomav/docker-mailserver/issues/101), but this issue was closed.
Are there any plans to integrate this into the image, or are there other ways to use z-push with this image?

Thx!

**Comment by alinmear** [comment]
@thiesschneider would you be interested in forking https://github.com/Gymnae/docker-zpush.git? If so, i would team up with you. 

I agree with @tomav as he mentioned in #101, that the z-push feature should be developed independently from docker-mailserver itself; but i think, that some people here would be interested in having this service available.

**Comment by thiesschneider** [comment]
Hey @alinmear,
if I could I would :) 
I would love to be able to enable the z-push functionality as an ENV like postgrey. I think this could also be optional and does provide also a comparable value. 
There are some z-push container on docker hub. If someone has experience with it we could also add some lines in the wiki?

**Comment by tomav** [comment]
Hi guys, I used z-push in 2010-2011 and from what I remember, this is a script behind a webserver that communicates with the mail backend. This should run and work in another docker container no?
Perhaps it changed in the past years, sorry I'm clearly not up to date on this.

**Comment by alinmear** [comment]
@tomav, you are right. We need for z-push a webserver. Although this schema is for kopano, you get the point what z-push is about:

![Z-Push Schema](https://appcenter.software-univention.de/meta-inf/4.2/z-push-kopano/zpush_arch.png)

---
Source: https://www.univention.de/produkte/univention-app-center/app-katalog/z-push-kopano/

**Comment by tomav** [comment]
@thiesschneider this feature does not have sense to be enabled into docker-mailserver.
I'm checking what I can propose as base project.

**Comment by tomav** [comment]
I have a plane 4AM tomorrow, have to stop here.
I started this: https://github.com/tomav/docker-z-push

Not ready for production, not tested, but basic installation / config for IMAP is almost done.

**Comment by tomav** [comment]
Feel free to contribute, I'll be off ~1week.

**Comment by alinmear** [comment]
@tomav, thx for your dedication. Have a good time!

**Comment by thiesschneider** [comment]
Awesome, thx! And have a good time

**Comment by tomav** [comment]
If somebody who wants to have this feature wanna work on the repo listed above, let me know.

**Comment by Gymnae** [comment]
Thanks for picking this up :) My attempt last year yielded a running z-push container, but stalled on connecting to a mailserver on an external host. I'm now back on the project of migrating my mail server to this docker based solution by @tomav and willl look at z-push again.

**Comment by thiesschneider** [comment]
yay :) looking forward to it

**Comment by trytuna** [comment]
yep this would be nice

**Comment by thiesschneider** [comment]
Hey @Gymnae, did you make any progress?

**Comment by Gymnae** [comment]
I did make some progress, but then stopped on the project since I found an eMail client on my mobile which uses a middleman server to push emails to the phone, thus negating the need to pursue this further.

**Comment by 17Halbe** [comment]
I gave it a try and it's working for my setup. Could you guys please give it a try?
There should only be the need to set your server domain. The ports and their configuration should work as is.
[17Halbe/z-push](https://github.com/17Halbe/z-push)

**Comment by mwlczk** [comment]
@17Halbe, how is it different from IMAP push. I didn't read much about it, but it is for Microsoft Outlook only? Or does it help with Thunderbird, k9 and other clients as well?

**Comment by johansmitsnl** [comment]
@mwlczk It is activesync https://en.wikipedia.org/wiki/ActiveSync which has support for contacts and calendars as well.
And for example iOS does not have imap push and you can get this working with the Exchange option for push events.

**Comment by 17Halbe** [comment]
Yes, I'm using to get Emails pushed to iOS. imap-push is more ressource intensive, which is why Apple unfortunately decided to not use it.. 
It would be possible to add contact, calendar sync and autodiscovery for email-settings. (You then would just have to enter your mail address and password without knowing anything else about ports or server names)
Nothing of this is implemented yet though.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by ahuse** [comment]
Has anyone tried setting up push for iOS devices recently? The repository of @17Halbe is over five years old and i wonder if it makes sense to fork and update it with the latest version of z-push.
