### ISSUE TITLE
(!)_DIE: Suicide () TROUBLE in pre_loop_hook: No TEMPBASE directory

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#623]
First I had this error
````
[...]
Error: Please fix your configuration. Exiting...
[...]
````
dovecot failing to start up.
I was able to fix it by removing the state/ directory completely (maybe because I migrated from 2.2 to 2.3?).

Then, when starting up docker-mailserver container (recent 2.3) 
I get the following error shortly after startup:
````
[...]
amavis[1689]: Using primary internal av scanner code for ClamAV-clamd
amavis[1689]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
amavis[1689]: (!!)TROUBLE in pre_loop_hook: No TEMPBASE directory: /var/lib/amavis/tmp at /usr/sbin/amavisd-new line 12742.
amavis[1689]: (!)_DIE: Suicide () TROUBLE in pre_loop_hook: No TEMPBASE directory: /var/lib/amavis/tmp at /usr/sbin/amavisd-new line 12742.
dovecot: master: Warning: Processes aren't dying after reload, sending SIGTERM.
dovecot: master: Warning: Processes aren't dying after reload, sending SIGTERM.
dovecot: master: Warning: Sent SIGTERM to 1 log processes
dovecot: log: Warning: Killed with signal 15 (by pid=428 uid=0 code=kill)
````

After removing the state/ directory completely, the following is reported during a new container startup:
````
[...]
find: '/var/mail-state/lib-amavis': No such file or directory
[...]
````
After this start up, the mail server started working again.

**Comment by tomav** [comment]
Check if `ONE_DIR=1` is expecting data to exist to proceed.
Perhaps you weed to start first with `ONE_DIR=0`, it generates all needed files, and then restart with `ONE_DIR=1`.

**Comment by strarsis** [comment]
Wouldn't it make sense to generate these needed files in any case?

**Comment by Dummyc0m** [comment]
Same issue here, did ONE_DIR=0 then 1 and I am getting the same error, plus #556 fatal: no SASL authentication mechanisms

Thank you for maintaining this fantastic project for everyone.

**Comment by johansmitsnl** [comment]
Did you solve the issue?
And if so how?

**Comment by strarsis** [comment]
> After removing the state/ directory completely, the following is reported during a new container startup:

But this doesn't solve the underlying issue. Amavisd not as milter but with reinjection makes the setup brittle and when amavis fails to start, mail flow completely goes down.

**Comment by johansmitsnl** [comment]
Are you willing to contribute with aa PR to solve the issue?

**Comment by strarsis** [comment]
This would involve installing and configuring amavis-milter, 
adding it as milter to postfix configuration and 
cleaning up the existing config of the non-milter amavis setup.
I could try to put something together when I got time.

**Comment by johansmitsnl** [comment]
Could this be combined with #465?

**Comment by strarsis** [comment]
Yes, it makes sense because the milter config part for amavis, when everything works, 
can be easily removed for turning the use of amavis off the next time postfix (re)starts.

**Comment by erik-wramner** [comment]
@strarsis can we close this issue? It is very old and it sounds fixed?

**Comment by strarsis** [comment]
@erik-wramner: But is amavis now integrated differently now or rspamd used instead?
Because otherwise the issue would persist.

**Comment by erik-wramner** [comment]
@strarsis I don't know, I wasn't here 2017. It sounded as if work was going on and then nothing, so I hoped for the best. We'll keep it open then.

**Comment by erik-wramner** [comment]
Again this has stalled. The way I see it (@fbartels, @tomav ?) the current way of doing things works. Yes, mail stops if Amavis doesn't start, but that is common in many configurations and can actually be a good thing if you want to be sure that all messages are analyzed.

Unless someone (@starsis?) is actively working on a viable and better alternative or we think there can be a bug fix within the current solution I think this should be closed, not a s a bug but as a known weakness.

**Comment by fbartels** [comment]
Yes, I agree with your view. If amavis fails to start then mails should not silently processed anyways (and av and spam scanning therefore skipped scanning).

I am wondering if there is a way in supervisord to recognise that one of the processes it manages has repeatedly stopped and then stop altogether.

**Comment by erik-wramner** [comment]
I'll close this then. Getting supervisord to abort after repeated failures is an excellent enhancement, but better placed in a separate issue.

**Comment by FSeidinger** [comment]
I'm having the same problem with current latest image (I guess it is 8.0.1). After using the image for a couple of days I switched to `ONE_DIR=1` and ran into the described startup loop.

I tried to figure out what `ONE_DIR` really does and opened a console into the running container. The mechanism to relocate to the `/var/mail-state` seems to be to create symlinks from the home directory to the externally mapped volume.

So for amavis the home directory in `/etc/passwd` is `/var/lib/amavis`. When using `ONE_DIR=1` `/var/lib/amavis` is symlinked to `/var/mail-state/lib-amavis`.

In my case the following sequence of actions fixed the problem:

1. stopping the container
2. switching back to `ONE_DIR=0`
3. starting the container
4. opening a console into the running container
5. stop amavis with `supervisorctl stop amavis`
5. copy the amavis state with `cp -ar /var/lib/amavis/. /var/mail-state/lib-amavis` to the mail state directory
6. exit console
7. stop container
8. switching to `ONE_DIR=1`
9. start container

Now everything runs fine. I guess this recipe can be used to fix this in the startup scripts. Key here is to find out that `ONE_DIR` was switched from 0 to 1 and copy the data before creating the symlinks.

**Comment by mirkomaty** [comment]
Sorry for beeing a little late to the party. But I Installed the latest version 12.1 yesterday and got exactly the same warning:

```
Sep  8 11:00:07 m2-artfoto amavis[2354]: (!!)TROUBLE in pre_loop_hook: config: no rules were found!  Do you need to run 'sa-update'?
Sep  8 11:00:07 m2-artfoto amavis[2354]: (!)_DIE: Suicide () TROUBLE in pre_loop_hook: config: no rules were found!  Do you need to run 'sa-update'?
```
I followed the steps FSeidinger described above with no success. Is there a way to just run sa-update - or any other solution to get rid of this this restart loop?

I'd be very glad for an answer.
