### ISSUE TITLE
Qnap nas support

### ISSUE THREAD

**Issue by happyhua** [tomav/docker-mailserver#624]
Would you like to support nas system like qnap container station (https://www.qnap.com/solution/container_station/en/)

Or show me the workaround to use docker mail server on nas, because I cannot install docker-compose, which is already included by container station. That will be great.

**Comment by tomav** [comment]
If you have docker, you can run the container (compose is not required).
Juste move the env variable to `-e FOO=bar -e THIS=that ...` and `--hostname` for you FQDN.
