### ISSUE TITLE
Question: Issue with hostname and multiple domains

### ISSUE THREAD

**Issue by DeKugelschieber** [tomav/docker-mailserver#626]
Hi, I'm settting up a new server so I decided to not install everything manually again. I got two questions which I couldn't find documentation or an issue for:

1. my new server has one domain at the moment: embe-it.de. I set the hostname to "mail" and I can send and receive mails. But if I send mails to my old server it does not accept the hostname because it expects embe-it.de instead of mail.embe-it.de:

```
<marvin@marvinblum.de>: host marvinblum.de[81.169.244.31] said: 554 5.7.1
    <mail.embe-it.de>: Helo command rejected: Get lost - you're lying about who
    you are (in reply to RCPT TO command)
```

This doesn't seem to be a problem for most mailservers since I can send mails to my googlemail and other servers. But can I remove the hostname? So that strict servers accept my domain? The DNS lookup and rDNS lookup both return my IP. With or without mail.* in front of it.

2. Can I configure multiple domains on the same server? I had multiple domains on my old server and the manually configured postfix server accepted all of them. I couldn't test it yet, since I still need to transfer them, but question 1 looks like it could affect this.

If you need more information please let my know :)

**Comment by thiesschneider** [comment]
Hey,

you can set the env to `--hostname=mail.mail.embe-it.de \` then it should work.
For your second question: Yes, you can set multiple domains. Just configure the DNS correctly.

I am running a similar configuration.
Hope I could help!

**Comment by DeKugelschieber** [comment]
This does not work, since the hostname is placed in front of the top level domain. So it results in:

```
<marvin@marvinblum.de>: host marvinblum.de[81.169.244.31] said: 554 5.7.1
    <mail.mail.embe-it.de.embe-it.de>: Helo command rejected: Get lost - you're
    lying about who you are (in reply to RCPT TO command)
```

I think my old postfix server is just too strict. I'll just ignore that for now and come back later, should I have issues setting up multiple domains on my server. Thanks for your help!
