### ISSUE TITLE
Using the containers crontab

### ISSUE THREAD

**Issue by MadsRC** [tomav/docker-mailserver#630]
The wiki, and @tomav in atleast one issue, mentions using the hosts crontab to, say run sa-learn regularly.

Is there any reason this can't/shouldn't be done in the container instead?
This would alleviate the risk of forgetting the cronjobs when/if you're moving the container to a new host.

I'd be happy to code it and send a pull request afterwards.

**Comment by alinmear** [comment]
@MadsRC that would be easy to and straight forward to implement, after #434 has been integrated. So maybe wait for the pr and afterwards implement this via supervisord.

**Comment by tomav** [comment]
`sa-learn` cron is not built-in because you probably want to enable it on some specific accounts.
So you have to do it manually on your host on in the container.
