### ISSUE TITLE
creating aliases, tvial/docker-mailserver:2.2

### ISSUE THREAD

**Issue by Inkimar** [tomav/docker-mailserver#634]
Hello,
I have set up at [project](https://github.com/DINA-Web/mail-docker/tree/improve-1).
Setup 2 email accounts and the address is something like myname@mail.myname.net .
Sending mails to and from  myname@mail.myname.net works.

Now I would like to use the following aliases to that address (myname@myname.net , without _mail_)
I ran the following  
`./setup.sh alias add myname@myname.net myname@mail.myname.net `
running 
`# ./setup.sh alias list`
`myname@myname.net myname@mail.myname.net,`
I guess the comma in the end is ok.

Sending mails to myname@myname.net does not work.
Is there anything more that I need to do , to get this working ?

Best regards, Ink

**Comment by tomav** [comment]
Hi @Inkimar, not sure for the comma... it should be `from@domain.tld to@domain.tld`.
Check that `/etc/postfix/virtual` is well formatted.

In these case, check and provide server logs

**Comment by Inkimar** [comment]
Hi @tomav , 
I logged in and checked the file /etc/postfix/virtual and it is empty ....

regards, i

**Comment by tomav** [comment]
If empty, there's no alias. You can add manually en entry with postfix format explained above. (from being the alias and to the email address). After that, just in case, reload postfix with `/etc/init.d/postfix reload`
Let me know.

**Comment by tomav** [comment]
And BTW, I just checked code for `setup.sh`
It adds alias to source file in tmp folder. So if you use that script, you have to restart the container to re-process the input file.
Hope this helps.

**Comment by Inkimar** [comment]
I will check this out!

-i

**Comment by johansmitsnl** [comment]
Is it solved?
If yes please share and close the solution.
