### ISSUE TITLE
How to configure sub addressing

### ISSUE THREAD

**Issue by kopax** [tomav/docker-mailserver#637]
I am trying to implement sub addressing for activating reply by email in gitlab: 

https://en.wikipedia.org/wiki/Email_address#Sub-addressing

I know I need to add in `postfix-main.cf`:

    recipient_delimiter = +

**Comment by johansmitsnl** [comment]
There is a wiki page about it: https://github.com/tomav/docker-mailserver/wiki/Configure-Aliases#address-tags-as-an-alternative
