### ISSUE TITLE
When using only ldap the vhost file for postfix is only set with the mailserver domain

### ISSUE THREAD

**Issue by johansmitsnl** [tomav/docker-mailserver#638]
When you use only mail users from the ldap with multiple email domains the vhost is only filled with the mailserver domain itself.
Therefore when you receive email on a alias domain or other domain it does not accept it.
It should check the ldap if the domain is defined and accept email for it.

It seems that the table for defining domains in the ldap is missing. What is the correct solution:
1. Expand the ldap postfixbook scheme and add it to the virtual domain lookup?
2. Create a tool that reads all mail addresses from the ldap to retrieve the domain?

**Comment by johansmitsnl** [comment]
I have made a quick patch so that my mail setup will work.
https://github.com/johansmitsnl/docker-mailserver/commit/c6d763aa671e6fc6e86b86ad60100f159b398bf2
Suggestions as asked above?

**Comment by alinmear** [comment]
@johansmitsnl Can you make a PR for this. Would be a great improvment!

**Comment by johansmitsnl** [comment]
@alinmear just created the pull request #642 that I use in my environment.
Not sure it the tests pass.
