### ISSUE TITLE
Link dead

### ISSUE THREAD

**Issue by unilynx** [tomav/docker-mailserver#64]
The link in the readme:

https://tvi.al/simple-mail-server-with-docker/

no longer works

(and is unfortunately also unavailble through web.archive.org)

**Comment by citec** [comment]
the domain name has no TLD in the link, maybe that's the reason

**Comment by unilynx** [comment]
There may be some strange email filtering going on, but if you look at the issue on github the dot is there. 'tvi.al'

It's reporting '502 Bad gateway', so it's probably either gone or just misconfigured..

**Comment by tomav** [comment]
Yep, there is a TLD, `.al` but I was on a server migration.
Website is back.
