### ISSUE TITLE
Not receiving mail from a single sender

### ISSUE THREAD

**Issue by alexandrepig** [tomav/docker-mailserver#640]
Hello,
A business is attempting to E-Mail us and we are not receiving their E-Mails. 

The error message is :
Diagnostic-Code: SMTP; 403 4.7.0 TLS handshake failed.

Thank you for your help
Alex

**Comment by VincentGuyader** [comment]
have a look at https://github.com/tomav/docker-mailserver/wiki/Configure-SSL

**Comment by johansmitsnl** [comment]
Here are some details about why it might occur:
https://bobcares.com/blog/how-to-fix-error-403-4-7-0-tls-handshake-failed/

**Comment by johansmitsnl** [comment]
Did you solve the issue or do you have an idea where to look?
