### ISSUE TITLE
Creating alias causes smtp to die

### ISSUE THREAD

**Issue by iammer** [tomav/docker-mailserver#645]
Whenever I try to create an alias using setup.sh:
```
./setup.sh alias add @domain.com user@domain.com
```

After `docker restart` smtpd dies when I try to send email:
```
Jul  4 02:23:36 mail postfix/submission/smtpd[1457]: warning: SASL: Connect to private/auth failed: Connection refused
Jul  4 02:23:36 mail postfix/submission/smtpd[1457]: fatal: no SASL authentication mechanisms
Jul  4 02:23:37 mail postfix/master[1023]: warning: process /usr/lib/postfix/sbin/smtpd pid 1457 exit status 1
Jul  4 02:23:37 mail postfix/master[1023]: warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling
```

When I remove the alias and restart it works again.

**Comment by tomav** [comment]
I think someone reported this same issue and my guess is that the script adds a comma but should not.

**Comment by tomav** [comment]
https://github.com/tomav/docker-mailserver/blob/master/target/bin/addalias#L26-L30 and sam in `delalias`

**Comment by tomav** [comment]
https://github.com/tomav/docker-mailserver/issues/634

**Comment by fbartels** [comment]
Likely resolved therefore closing.
