### ISSUE TITLE
documentation on hostname and domainname

### ISSUE THREAD

**Issue by insanebits** [tomav/docker-mailserver#65]
While trying to build image using docker-compose it some time to figure out how letsencrypt directory should be named. As far as I understand build script will contatenate hostname and domainname and when you generate letsencrypt certificates usually you will get directory with only a domain name. So when you mount start-mailserver.sh will look for invalid location.

It would be nice to have some sort of documentation how it works. 

What worked for me was just removing hostname from docker-compose.yml and then I get hostname as domainname i have given.

**Comment by tomav** [comment]
You're right, an information is missing.
