### ISSUE TITLE
Minus (-) as a recipient_delimiter characters doesn't work

### ISSUE THREAD

**Issue by timotion83** [tomav/docker-mailserver#652]
When I add the following line to postfix-main.cf

`recipient_delimiter = +-`

it doesn't work for both separators. It only works for the +. In the error case the server replies that this user doesn't exist.

Can anybody confirm this problem or knows a solution?

**Comment by johansmitsnl** [comment]
Did you made the changes like in the WIKI? You also need to modify dovecot config to.
https://github.com/tomav/docker-mailserver/wiki/Configure-Aliases#address-tags-as-an-alternative

**Comment by timotion83** [comment]
Thanks for your reply but even when I add it to the dovecot.cf I get the error message. I think the problem is when I use two characters in the config files. I use it at another mail server which I want to migrate to docker-mailserver. So in general it should work. Nevertheless  the problem can be solved by using the regexp function for mail addresses. So I will use this as a workaround.

**Comment by erik-wramner** [comment]
Closing as there is a workaround and as the problem (if any) seems to be in postfix/dovecot rather than docker-mailserver.
