### ISSUE TITLE
how to set hostname and domainname

### ISSUE THREAD

**Issue by liuziyuan** [tomav/docker-mailserver#653]
hostname: mail
domainname: domain.com

could I follow the default setting？
or I could changed any .
for example:
hostname: hello
domainname: aaa.bbb.com

**Comment by tomav** [comment]
Hi @liuziyuan, not sure I understand exactly what you mean.
But $hostname$domainname should be a [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) that will be used as host for you server.
you'll be able to add any domain / account on top of that.
