### ISSUE TITLE
Should the freshclam cron job be disabled when ENABLE_CLAMAV=0?

### ISSUE THREAD

**Issue by pkcinna01** [tomav/docker-mailserver#660]
I'm getting several emails a day about cron job failing to rotate logs and things.  Also, trying to minimize network, memory, and cpu usage by not updating clamav db.

**Comment by tomav** [comment]
Hi @pkcinna01, yes it can be disable.

**Comment by pkcinna01** [comment]
Thanks tomav.  The mailserver project is much appreciated.  I hacked together a simple script for now which is called from docker-compose "command" so I can still use the official docker image.

`if [ $ENABLE_CLAMAV -eq 0 ]
then
  echo "ENABLE_CLAMAV is zero.  Removing logrotate configs and cron job for freshclam"
  rm /etc/logrotate.d/clamav-* 
  sed -i "/\/usr\/bin\/freshclam --quiet/d" /var/spool/cron/crontabs/root
fi
echo "Launching originial start-mailserver.sh from Dockerfile CMD..."
/usr/local/bin/start-mailserver.sh
`
