### ISSUE TITLE
Daily cron warning regarding rsyslog

### ISSUE THREAD

**Issue by danielpanteleit** [tomav/docker-mailserver#661]
After an update to docker-mailserver I now receive warning every day regarding rsyslog via cron:

```
/etc/cron.daily/logrotate:
invoke-rc.d: action rotate is unknown, but proceeding anyway.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of rotate.
```

I found this thread (https://i-mscp.net/index.php/Thread/15845-etc-cron-daily-logrotate-invoke-rc-d-action-rotate-is-unknown-but-proceeding-any/) which suggests to delete `/usr/sbin/policy-rc.d` which only contains

```
#!/bin/sh
exit 101
```

Deleting this should fix the issue, but I'm not sure where this file is coming from or if it is needed elsewhere.

**Comment by therealgambo** [comment]
I have the same problem, I have adjusted `/usr/sbin/policy-rc.d` waiting to see if this does resolve it.

**Comment by spet** [comment]
@therealgambo Did your adjustment fix this error? And if so, what was your adjustment? TIA.

**Comment by therealgambo** [comment]
@spet, adjusting `/usr/sbin/policy-rc.d` did not solve this.

**Comment by danielpanteleit** [comment]
Removing the script `/usr/sbin/policy-rc.d` fixed two out of three warnings. The last warning is `could not determine current runlevel` and is emitted by the script `/usr/sbin/invoke-rc.d`. I commented out the corresponding line in the script which should fix the problem. I will let it run a couple of days and submit a PR if it works as expected.
