### ISSUE TITLE
Not able to telnet new server 

### ISSUE THREAD

**Issue by kapilm1989** [tomav/docker-mailserver#668]
Hi , 
I used instruction provided to build server .docker-compose file is given below :+1: 

version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.2
    hostname: mail
    domainname: myairflowtesting.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

started the server 
docker-compose up -d mail

tried to telnet the server but getting error 
telnet mail.myairflowtesting.com 25

telnet: mail.myairflowtesting.com: Name or service not known
mail.myairflowtesting.com: Unknown host

mail log 
Jul 23 15:26:23 mail dovecot: master: Dovecot v2.2.9 starting up
Jul 23 15:26:23 mail opendkim[148]: OpenDKIM Filter v2.9.1 starting (args: -x /etc/opendkim.conf -u opendkim -P /var/run/opendkim/opendkim.pid)
Jul 23 15:26:23 mail opendmarc[164]: OpenDMARC Filter v1.2.0 starting (args: -c /etc/opendmarc.conf -u opendmarc -P /var/run/opendmarc/opendmarc.pid -p inet:8893@localhost)
Jul 23 15:26:23 mail opendmarc[164]: trusted authentication services: mail.myairflowtesting.com
Jul 23 15:26:23 mail dovecot: ssl-params: Generating SSL parameters
Jul 23 15:26:23 mail postgrey[175]: Process Backgrounded
Jul 23 15:26:23 mail postgrey[175]: 2017/07/23-15:26:23 postgrey (type Net::Server::Multiplex) starting! pid(175)
Jul 23 15:26:23 mail postgrey[175]: Binding to TCP port 10023 on host 127.0.0.1 with IPv4
Jul 23 15:26:23 mail postgrey[175]: Setting gid to "111 111"
Jul 23 15:26:23 mail postgrey[175]: Setting uid to "107"
Jul 23 15:26:23 mail postgrey[175]: FATAL: ERROR: can't open lock file: /var/lib/postgrey/postgrey.lock#012
Jul 23 15:26:27 mail postfix/master[972]: fatal: open lock file /var/lib/postfix/master.lock: cannot open file: Permission denied
Jul 23 15:26:29 mail amavis[1003]: starting. /usr/sbin/amavisd-new at mail.myairflowtesting.com amavisd-new-2.7.1 (20120429), Unicode aware
Jul 23 15:26:29 mail amavis[1022]: Net::Server: Group Not Defined.  Defaulting to EGID '112 112'
Jul 23 15:26:29 mail amavis[1022]: Net::Server: User Not Defined.  Defaulting to EUID '108'
Jul 23 15:26:29 mail amavis[1022]: Module Amavis::Conf        2.303
Jul 23 15:26:29 mail amavis[1022]: Module Archive::Zip        1.30
Jul 23 15:26:29 mail amavis[1022]: Module BerkeleyDB          0.54
Jul 23 15:26:29 mail amavis[1022]: Module Compress::Zlib      2.06
Jul 23 15:26:29 mail amavis[1022]: Module Convert::TNEF       0.18
Jul 23 15:26:29 mail amavis[1022]: Module Convert::UUlib      1.4
Jul 23 15:26:29 mail amavis[1022]: Module Crypt::OpenSSL::RSA 0.28
Jul 23 15:26:29 mail amavis[1022]: Module DB_File             1.827

any help would be appreciable ...

**Comment by kapilm1989** [comment]
after DMS_DEBUG=1

logs:

#
#
# ENV
#
#

HOSTNAME=mail.myairflowtesting.com
DMS_DEBUG=1
VIRUSMAILS_DELETE_DELAY=7
ENABLE_CLAMAV=0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENABLE_FAIL2BAN=1
ENABLE_SPAMASSASSIN=1
PWD=/
SHLVL=1
HOME=/root
ONE_DIR=1
DEBIAN_FRONTEND=noninteractive
ENABLE_POSTGREY=1
_=/usr/bin/printenv

#
#
# docker-mailserver
#
#

Initializing setup
  Registering check,setup,fix,misc and start-daemons functions
  * _check_environment_variables() registered
  * _check_hostname() registered
  * _setup_default_vars() registered
  * _setup_dovecot() registered
  * _setup_dovecot_local_user() registered
  * _setup_postgrey() registered
  * _setup_dkim() registered
  * _setup_ssl() registered
  * _setup_docker_permit() registered
  * _setup_mailname() registered
  * _setup_amavis() registered
  * _setup_dmarc_hostname() registered
  * _setup_postfix_hostname() registered
  * _setup_dovecot_hostname() registered
  * _setup_postfix_sasl() registered
  * _setup_postfix_over_configuration() registered
  * _setup_postfix_sasl_password() registered
  * _setup_security_stack() registered
  * _setup_postfix_aliases() registered
  * _setup_postfix_vhost() registered
  * _setup_environment() registered
  * _fix_var_mail_permissions() registered
  * _fix_var_amavis_permissions() registered
  * _misc_save_states() registered
  * _start_daemons_cron() registered
  * _start_daemons_rsyslog() registered
  * _start_daemons_dovecot() registered
  * _start_daemons_opendkim() registered
  * _start_daemons_opendmarc() registered
  * _start_daemons_postgrey() registered
  * _start_daemons_postfix() registered
  * _start_daemons_fail2ban() registered
  * _start_daemons_amavis() registered
Checking configuration
  Check that there are no conflicts with env variables [_check_environment_variables]
  Check that hostname/domainname is provided or overidden (no default docker hostname/kubernetes) [_check_hostname]
  * Domain has been set to myairflowtesting.com
  * Hostname has been set to mail.myairflowtesting.com
Configuring mail server
  Setting up default variables [_setup_default_vars]
  * Set ENABLE_LDAP=0
  * Set ENABLE_FETCHMAIL=0
  * Set OVERRIDE_HOSTNAME=
  * Set ENABLE_MANAGESIEVE=0
  * Set DMS_DEBUG=1
  * Set ENABLE_POP3=0
  * Set ENABLE_SASLAUTHD=0
  * Set ENABLE_CLAMAV=0
  * Set SMTP_ONLY=0
  * Set ENABLE_FAIL2BAN=1
  * Set ENABLE_SPAMASSASSIN=1
  * Set POSTGREY_DELAY=300
  * Set POSTGREY_TEXT=Delayed by postgrey
  * Set ENABLE_POSTGREY=1
  * Set POSTGREY_MAX_AGE=35
  Setting up Dovecot
  Setting up Dovecot Local User
  * Checking file line endings
  * Regenerating postfix user list
  * user 'user1' for domain 'myairflowtesting.tld' with password '********'
  * Configuring postgrey
cp: cannot stat '/tmp/docker-mailserver/whitelist_clients.local': No such file or directory
  Setting up DKIM
  * DKIM keys added for: domain.tld  myairflowtesting.tld
  * Changing permissions on /etc/opendkim
  Setting up SSL
  Setting up PERMIT_DOCKER Option
  * Adding container ip in my networks
  Setting up Mailname
  * Creating /etc/mailname
  Setting up Amavis
  * Applying hostname to /etc/amavis/conf.d/05-node_id
  Setting up dmarc
  * Applying hostname to /etc/opendmarc.conf
  Applying hostname and domainname to Postfix
  * Applying hostname to /etc/postfix/main.cf
  Applying hostname to Dovecot
  * Applying hostname to /etc/dovecot/conf.d/15-lda.conf
  Setting up Postfix Override configuration
  * No extra postfix settings loaded because optional '/tmp/docker-mailserver/postfix-main.cf' not provided.
  Setting up Postfix SASL Password
  * Warning: 'SASL_PASSWD' is not provided. /etc/postfix/sasl_passwd not created.
  Setting up Security Stack
  * Enabling and configuring spamassassin
  * Clamav is disabled. You can enable it with 'ENABLE_CLAMAV=1'
  * Fail2ban enabled
  Setting up Postfix Aliases
  Setting up Postfix vhost
  Setting up /etc/environment
  Checking /var/mail permissions
  * Fixing /var/mail permissions
  Checking $amavis_state_dir permissions
  * Permissions in /var/mail-state/lib-amavis look OK
Starting Misc
  * Consolidating all state onto /var/mail-state
  *   Destination /var/mail-state/spool-postfix exists, linking /var/spool/postfix to it
  *   Destination /var/mail-state/lib-postfix exists, linking /var/lib/postfix to it
  *   Destination /var/mail-state/lib-amavis exists, linking /var/lib/amavis to it
  *   Destination /var/mail-state/lib-clamav exists, linking /var/lib/clamav to it
  *   Destination /var/mail-state/lib-spamassasin exists, linking /var/lib/spamassasin to it
  *   Destination /var/mail-state/lib-fail2ban exists, linking /var/lib/fail2ban to it
  *   Destination /var/mail-state/lib-postgrey exists, linking /var/lib/postgrey to it
Starting mail server
  Starting cron  [ OK ]
  Starting rsyslog  [ OK ]
  Starting dovecot services  [ OK ]
  Starting opendkim  [ OK ]
  Starting opendmarc  [ OK ]
  Starting postgrey  [ OK ]
  Starting postfix  [ OK ]
  Starting fail2ban  [ OK ]
  Starting amavis  [ OK ]

#
# mail.myairflowtesting.com is up and running
#

tail: unrecognized file system type 0x794c7630 for '/var/log/mail/mail.log'. please report this to bug-coreutils@gnu.org. reverting to polling
Jul 23 17:24:22 mail amavis[1024]: Creating db in /var/lib/amavis/db/; BerkeleyDB 0.54, libdb 5.3
[kss_admin@localhost docker-mail]$ telnet mail.myairflowtesting.com 25
telnet: mail.myairflowtesting.com: Name or service not known
mail.myairflowtesting.com: Unknown host

**Comment by danielpanteleit** [comment]
Obviously the sub-domain mail.myairflowtesting.com is not resolving. Did you buy/rent the domain and set up the sub-domain correctly? This has nothing to do with the mail server itself.

**Comment by kapilm1989** [comment]
Thanks for replying. I have not bought any domain but trying to set up this server for testing out my mail component.. Do I need to make extra configuration to make this local mail server work for mine testing only..

**Comment by danielpanteleit** [comment]
If you just want to telnet to your mail server you can just `telnet 0.0.0.0 25`.

**Comment by johansmitsnl** [comment]
Is the issue solved?
