### ISSUE TITLE
Unable to send message on OSX: SSL_accept error from unknown[82.137.11.208]: lost connection

### ISSUE THREAD

**Issue by vedtam** [tomav/docker-mailserver#672]
Hi,

I am trying to configure the default Mail client on OSX 10.10.5, I can receive emails just fine, but  it fails when sending new messages.

OSX SMTP config:

![screen shot 2017-07-28 at 10 40 16](https://user-images.githubusercontent.com/4981592/28707687-fa2a35e0-7381-11e7-85e2-898263e1e45b.png)

postfix log:

![screen shot 2017-07-28 at 10 39 50](https://user-images.githubusercontent.com/4981592/28707638-d1095826-7381-11e7-9fb5-6b3afe5e9ae5.png)

In turn, on my Android phone, receiving and sending works like a charm. What could be the problem on OSX?

**Comment by tomav** [comment]
@vedtam you found the issue?

**Comment by vedtam** [comment]
@tomav when I switch my internet connection from landline to mobile (tethered, different ISP) it sends messages without a problem. I will inspect the logs for a few days, hope to find some clues or differences when using one over the other.

**Comment by tomav** [comment]
Great, thanks.
