### ISSUE TITLE
After add new mail account - user not found

### ISSUE THREAD

**Issue by Ciangi** [tomav/docker-mailserver#678]
Hello,

i created a new e-mail account but can't log in on it.

Actually have 2 accounts. First works - created it at first time. Second not, but why, i don't know. Need help.

First account : test@example.com
Second : test2@example.com

Have content about test and test2 inside postfix-accounts.cf.
when run command:
# listmailuser
test@example.com
test2@example.com

# doveadm user test@example.com
field value
uid 5000
gid 5000
home blablabla
mail blablabla
# doveadm user test2@example.com
field valueuserdb lookup: user test2@example.com doesn't exist

Tried add acount in mail client and in mail logs got:
imap dovecot: auth: passwd-file(test2@example.com): unknown user

Tried also restart dovecot, postfix  - no change....

Help please :)

**Comment by Ciangi** [comment]
I tried add user using two commands:

outside container: docker run ......
inside container: doveadm pw -s .......

and still got that user not found

**Comment by Ciangi** [comment]
Finally works when restart container but why i need to do that? Can i got new mail accounts without restarting docker container?

**Comment by johansmitsnl** [comment]
The accounts file is loaded at startup. The only way is to restart the container.
