### ISSUE TITLE
/usr/local/bin/start-mailserver.sh: line 111: /etc/letsencrypt/live/mail.domain.tld/combined.pem: No such file or directory

### ISSUE THREAD

**Issue by konstantinj** [tomav/docker-mailserver#68]
Hi,

thanks for this awesome image.

I've tried starting it with docker-compose.yml from this repo. With my domain of course. Im getting this error at start:

> /usr/local/bin/start-mailserver.sh: line 111: /etc/letsencrypt/live/mail.domain.tld/combined.pem: No such file or directory

in line 111 in the current master is just "fi". Is the build not up2date?
I've provided the DMS_SSL=letsencrypt env. According to the start log there is no letsencrypt run.

**Comment by bilak** [comment]
Hi, 
If you have your letsencrypt certificates generated on your host just mount a volume with it `-v "$(pwd)/letsencrypt/etc":/etc/letsencrypt`. This could help you to resolve this issue.

**Comment by konstantinj** [comment]
OK, that would work. But I thought the image is creating the certs for me if missing. Still haven't looked through the sources.

**Comment by bilak** [comment]
That could be added in future, but then ports 80 and 443 should be exposed and they must be accessible to public.

**Comment by tomav** [comment]
Or using the LE manual mode.
