### ISSUE TITLE
Receiving duplicate emails to all accounts when a catch-all is in place

### ISSUE THREAD

**Issue by sk33z3r** [tomav/docker-mailserver#683]
I followed your WIKI on setting up aliases, thanks for adding the ability to read from a config file to add aliases to /etc/postfix/virtual, very handy!

However, I am running into an issue where I get duplicate emails when sending email to a non-user. Here's the reproduction:

1. Setup and run postfix with three users registered:
-- a@example.tld
-- b@example.tld
-- postmaster@example.tld
2. config/postfix-virtual.cf including the following:
`@example.tld a@example.tld, b@example.tld`
3. Once mailserver is running, check /etc/postfix/virtual inside container and confirm it prints what I have above (it does)
4. Send an email from an external address to info@example.tld

Expecting: Both 'a' and 'b' to each receive 1 email
Actual: Both 'a' and 'b' receive the email twice

Further to the actual result above, whenever user 'b' signs up for something and gives their address, user 'a' will also receive doubles of the emails intended only for user 'b' (and vice versa). If i completely disable the catch-all, then user accounts are fine and mails are not duplicated, but then I lose the ability to catch-all.

Ultimately, I just want to set it up so that _anything_@example.tld sends a single email to each 'a' and 'b', and both 'a' and 'b' still retain their separate, private inboxes under normal circumstances.

I have tried the following few ways to enable the catch-all...

All of these fail in the way that I describe above:
`@example.tld a@example.tld,b@example.tld`
`@example.tld a@example.tld, b@example.tld`
`@example.tld a@example.tld b@example.tld`

This just doesn't work at all:
```
@example.tld a@example.tld
@example.tld b@example.tld
```

This works as I expect, but of course only user 'a' receives the mails:
`@example.tld a@example.tld`

I've dug through the postfix documentation a bit, but not having any luck regarding this specific situation.

If I setup the aliases like this: `info@example.tld a@example.tld, b@example.tld`, then anything sent to info@ is working as expected. Each user only receives 1 mail and there is no other criss-cross of received emails intended for only one of the users.

I'm guessing there's some fundamental operation of catch-all that is lost on me, or there's a configuration specific to catch-all that I am missing. If this is outside the realm of the docker image and seems to be more related to postfix generically, let me know and i will look elsewhere for answers.

**Comment by mplx** [comment]
when using catchall the "real" accounts need aliases too, where the order is important aswell

maybe this solves your problem:

postfix-virtual.cf 
```
a@example.tld a@example.tld
b@example.tld b@example.tld
info@example.tld a@example.tld,b@example.tld
@example.tld a@example.tld,b@example.tld
```

**Comment by sk33z3r** [comment]
Ah! It's always one minor detail. That resolved the issue, thank you, @mplx
