### ISSUE TITLE
After host reboot (and some container restarts) dovecot fails to run correctly

### ISSUE THREAD

**Issue by justinvoelker** [tomav/docker-mailserver#686]
I have docker-mailserver setup and running, sending and receiving emails as expected, but sometimes after a server reboot, or a docker-compose restart, dovecot appears to break. The docker log gets flooded with the following lines every second until I stop or restart the container (hopefully working on the second try).

```
INFO spawned: 'dovecot' with pid 1099
INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
INFO exited: dovecot (exit status 89; not expected)
INFO spawned: 'dovecot' with pid 1101
INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
INFO exited: dovecot (exit status 89; not expected)
INFO spawned: 'dovecot' with pid 1103
INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
INFO exited: dovecot (exit status 89; not expected)
```

I also see the following line in the log at sporadic places.

```
mail dovecot: master: Fatal: Dovecot is already running with PID 203 (read from /var/run/dovecot/master.pid)
```

The strange thing is that even though it says dovecot is running, I cannot connect any accounts over IMAP.

Here is my docker-compose.yml

```
version: '2'
services:
  mailserver:
    image: tvial/docker-mailserver:latest
    restart: always
    hostname: mail
    domainname: example.com
    container_name: mail.example.com-mailserver
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
    volumes:
      - ./mailserver/maildata/:/var/mail
      - ./mailserver/mailstate/:/var/mail-state
      - ./mailserver/config/:/tmp/docker-mailserver/
      - /home/justin/docker/nginx-proxy/certificates/:/etc/letsencrypt/live
    environment:
      - ONE_DIR=1
      - SSL_TYPE=letsencrypt
      - DMS_DEBUG=1
```

**Comment by gutmensch** [comment]
I'm seeing the same respawning behavior for amavis
`2017-08-11 19:06:55,127 INFO exited: amavis (exit status 255; not expected)
2017-08-11 19:06:56,130 INFO spawned: 'amavis' with pid 25600
2017-08-11 19:06:56,681 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-08-11 19:06:56,689 INFO exited: amavis (exit status 255; not expected)
2017-08-11 19:06:57,692 INFO spawned: 'amavis' with pid 25608
2017-08-11 19:06:58,307 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-08-11 19:06:59,316 INFO exited: amavis (exit status 255; not expected)
2017-08-11 19:07:00,319 INFO spawned: 'amavis' with pid 25618
2017-08-11 19:07:00,868 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-08-11 19:07:00,876 INFO exited: amavis (exit status 255; not expected)
2017-08-11 19:07:01,879 INFO spawned: 'amavis' with pid 25626

root@mail:/# supervisorctl status
amavis                           RUNNING   pid 28255, uptime 0:00:00
clamav                           RUNNING   pid 278, uptime 13:45:24
cron                             RUNNING   pid 229, uptime 13:45:24
dovecot                          RUNNING   pid 236, uptime 13:45:24
fail2ban                         STOPPED   Not started
fetchmail                        RUNNING   pid 276, uptime 13:45:24
filebeat                         STOPPED   Not started
mailserver                       RUNNING   pid 10, uptime 13:45:28
opendkim                         RUNNING   pid 245, uptime 13:45:24
opendmarc                        RUNNING   pid 253, uptime 13:45:24
postfix                          RUNNING   pid 263, uptime 13:45:24
postgrey                         RUNNING   pid 261, uptime 13:45:24
rsyslog                          RUNNING   pid 231, uptime 13:45:24`

and it's happening appr. 1,5 days after starting up the container (so it works in the beginning). I would guess it's related to supervisor, which is creating this looping behaviour and which was merged with the last commits.

**Comment by johansmitsnl** [comment]
Each proces has a own stout log in: /var/log/supervisor/
What does it say?

**Comment by gutmensch** [comment]
Unfortunately nothing useful, just that the startup script of amavis already finds the existing process and therefore exits
```
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
The amavisd daemon is already running, PID: [19049]
```
Being a bit out of ideas I suspected some supervisor/pid problem with the amavis process and changed the app config to use pidproxy
```
[program:amavis]
startsecs=0
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
command=/usr/bin/pidproxy /var/run/amavis/amavisd.pid /usr/sbin/amavisd-new foreground
```
cannot report if that fixes anything yet, although it's a bit of a miracle to me, why supervisor kind of "loses the process" at all.

**Comment by justinvoelker** [comment]
Here is what I am seeing in the /var/log/supervisor/ logs, each repeated over and over again:

dovecot.log
```
Fatal: Dovecot is already running with PID 201 (read from /var/run/dovecot/master.pid)
```

supervisord.log
```
2017-08-13 21:18:54,348 INFO spawned: 'dovecot' with pid 14665
2017-08-13 21:18:54,368 INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-08-13 21:18:54,369 INFO exited: dovecot (exit status 89; not expected)
```

**Comment by johansmitsnl** [comment]
What happens if you set the pid file in de config file:

```ini
[program:dovecot]
startsecs=0
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
command=/usr/sbin/dovecot -F -c /etc/dovecot/dovecot.conf
pidfile = /var/run/dovecot/master.pid
```

or remove the pid file does it start then?

**Comment by FinnFrotscher** [comment]
+1

**Comment by gutmensch** [comment]
@johansmitsnl: according to the supervisor documentation at http://supervisord.org/configuration.html#program-x-section-values "pidfile" is not a valid directive for the program: section... the suggested solution I read about was instead using the pidproxy provided python wrapper (also provided by the supervisord code).

**Comment by johansmitsnl** [comment]
@gutmensch your correct, I overlook the section.
Do you known the steps to make it work again or how to reproduce it?

**Comment by gutmensch** [comment]
@johansmitsnl: Manually killing the processes and removing the pidfile and then restarting via supervisorctl "solves" the problem, but it seems to be re-occuring. I'm still testing the pidproxy change, it looks promising but I need another 1-2 days to confirm that. I have no idea how the initial issue is triggered at all (SIGx to supervisor subprocess?!). With no changes or extensions to amavis I'm seeing this behaviour every 24-36h after the start of the image. I could not determine yet, why it happens. I might also try starting with a clean state directory...

**Comment by ChromoX** [comment]
+1

**Comment by johansmitsnl** [comment]
@gutmensch I'm running also the same version but without any issues so far. Curious what makes this issue appear.

**Comment by Fmstrat** [comment]
If this helps, I had this happen with amavisd when I enabled clamav, spamassassin, and fail2ban. I restarted and it went away.

**Comment by justinvoelker** [comment]
@johansmitsnl Could it be a new container vs. upgraded container? I first pulled and setup this container just a week ago as a brand new setup. Perhaps something inside an existing/older container is allowing the new version to work?

The only environment variables I include in my docker-compose are ONE_DIR=1 and SSL_TYPE=letsencrypt. Everything else is left as default (which should mean clamav, spamassassin, fail2ban, etc. are all disabled).

Also odd that others seem to have the issue with amavisd but mine is with dovecot.

**Comment by Fmstrat** [comment]
@justinvoelker Anything custom in your dovecot config? If one of the braces `{}` isn't closed properly, the 89 error will come up. Even if it's not custom, I'd check it.

**Comment by justinvoelker** [comment]
@Fmstrat Is there a specific config file you are thinking of? Below is the extent of this service in my docker-compose.yml so clearly I'm not setting a custom config. Seemingly, the only way a dovecot config could be malformed would be if it happened automagically when the container starts.

```
image: tvial/docker-mailserver:latest
restart: always
hostname: mail
domainname: example.com
container_name: mail.example.com-mailserver
ports:
  - "25:25"
  - "587:587"
  - "993:993"
volumes:
  - ./mailserver/maildata/:/var/mail
  - ./mailserver/mailstate/:/var/mail-state
  - ./mailserver/config/:/tmp/docker-mailserver/
  - /home/justin/docker/nginx-proxy/certificates/:/etc/letsencrypt/live
environment:
  - ONE_DIR=1
  - SSL_TYPE=letsencrypt
```

**Comment by Fmstrat** [comment]
@justinvoelker Yea, I was thinking of a `./mailserver/config/dovecot.cf` file. Unlikely that's the issue, then. I just know malformed config can cause that.

**Comment by gutmensch** [comment]
Update from my side, pidproxy does not seem to help, looking at the process tree it seems the amavis process was moved from the supervisord process as parent to the initial calling shell as parent and that's why supervisord tries to respawn the process.

1. output - amavisd broken for supervisord (but still working)
```
root@mail:/# supervisorctl status
amavis                           STOPPED   Aug 16 10:13 AM
clamav                           RUNNING   pid 276, uptime 1 day, 1:24:49
cron                             RUNNING   pid 227, uptime 1 day, 1:24:50
dovecot                          RUNNING   pid 234, uptime 1 day, 1:24:50
fail2ban                         STOPPED   Not started
fetchmail                        RUNNING   pid 274, uptime 1 day, 1:24:50
filebeat                         STOPPED   Not started
mailserver                       RUNNING   pid 9, uptime 1 day, 1:24:53
opendkim                         RUNNING   pid 243, uptime 1 day, 1:24:50
opendmarc                        RUNNING   pid 251, uptime 1 day, 1:24:50
postfix                          RUNNING   pid 261, uptime 1 day, 1:24:50
postgrey                         RUNNING   pid 259, uptime 1 day, 1:24:50
rsyslog                          RUNNING   pid 229, uptime 1 day, 1:24:50

root@mail:/# pstree -apc
sh,1 -c supervisord -c /etc/supervisor/supervisord.conf
  |-/usr/sbin/amavi,2003
  |   |-/usr/sbin/amavi,2012
  |   `-/usr/sbin/amavi,2013
  |-master,1099
  |   |-pickup,10841 -l -t fifo -u -c -o content_filter= -o receive_override_options=no_header_body_checks
  |   |-qmgr,1102 -l -t unix -u
  |   `-tlsmgr,1125 -l -t unix -u -c
  `-supervisord,6 /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
      |-bash,261 /usr/local/bin/postfix-wrapper.sh
      |   `-sleep,16946 5
      |-clamd,276 -c /etc/clamav/clamd.conf
      |   `-{clamd},1106
      |-cron,227 -f
      |-dovecot,234 -F -c /etc/dovecot/dovecot.conf
      |   |-anvil,237
      |   |-config,11263
      |   |-imap,13133
      |   |-imap,13373
      |   |-imap-login,13132
      |   |-imap-login,13362
      |   `-log,238
      |-fetchmail,274 -f /etc/fetchmailrc -v --nodetach --daemon 300 -i /var/lib/fetchmail/.fetchmail-UIDL-cache --pidfile /var/run/fetchmail/fetchmail.pid
      |-opendkim,243 -f
      |   `-opendkim,245 -f
      |       |-{opendkim},246
      |       |-{opendkim},247
      |       |-{opendkim},248
      |       |-{opendkim},249
      |       |-{opendkim},250
      |       `-{opendkim},4070
      |-opendmarc,251 -f -p inet:8893@localhost -P /var/run/opendmarc/opendmarc.pid
      |   |-{opendmarc},252
      |   |-{opendmarc},253
      |   |-{opendmarc},254
      |   |-{opendmarc},255
      |   `-{opendmarc},256
      |-postgrey --inet,259
      |-rsyslogd,229 -n
      |   |-{in:imuxsock},230
      |   `-{rs:main Q:Reg},231
      `-start-mailserve,9 /usr/local/bin/start-mailserver.sh
          `-tail,280 -fn 0 /var/log/mail/mail.log
```

The issue started again today on 07:17, interestingly the current running pid is not the initial one, but  one, which was started at the same time. So something must have caused amavisd to completely restart as a subprocess of the shell instead of supervisord

2. output - spawned processes
```
root@stack /home/jazz # docker logs mail | grep spawned | head -n 50
2017-08-15 08:52:15,340 INFO spawned: 'mailserver' with pid 9
  Starting cron2017-08-15 08:52:18,177 INFO spawned: 'cron' with pid 227
  Starting rsyslog 2017-08-15 08:52:18,322 INFO spawned: 'rsyslog' with pid 229
  Starting dovecot services2017-08-15 08:52:18,453 INFO spawned: 'dovecot' with pid 234
  Starting opendkim 2017-08-15 08:52:18,580 INFO spawned: 'opendkim' with pid 243
  Starting opendmarc 2017-08-15 08:52:18,674 INFO spawned: 'opendmarc' with pid 251
  Starting postgrey2017-08-15 08:52:18,768 INFO spawned: 'postgrey' with pid 259
  Starting postfix2017-08-15 08:52:18,868 INFO spawned: 'postfix' with pid 261
  Starting fetchmail2017-08-15 08:52:18,967 INFO spawned: 'fetchmail' with pid 274
  Starting clamav2017-08-15 08:52:19,062 INFO spawned: 'clamav' with pid 276
  Starting amavis2017-08-15 08:52:19,160 INFO spawned: 'amavis' with pid 278
2017-08-16 07:17:13,292 INFO spawned: 'amavis' with pid 2002
2017-08-16 07:17:14,789 INFO spawned: 'amavis' with pid 2014
2017-08-16 07:17:16,346 INFO spawned: 'amavis' with pid 2022
```

3. output - amavis ok
```
root@mail:/# pstree -apc
sh,1 -c supervisord -c /etc/supervisor/supervisord.conf
  |-master,1099
  |   |-anvil,17238 -l -t unix -u -c
  |   |-pickup,10841 -l -t fifo -u -c -o content_filter= -o receive_override_options=no_header_body_checks
  |   |-proxymap,17237 -t unix -u
  |   |-qmgr,1102 -l -t unix -u
  |   |-smtpd,17236 -n smtp -t inet -u -o stress= -s 2
  |   `-tlsmgr,1125 -l -t unix -u -c
  `-supervisord,6 /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
      |-/usr/sbin/amavi,17261
      |   |-/usr/sbin/amavi,17271
      |   `-/usr/sbin/amavi,17272
      |-bash,261 /usr/local/bin/postfix-wrapper.sh
      |   `-sleep,17275 5
      |-clamd,276 -c /etc/clamav/clamd.conf
      |   `-{clamd},1106
      |-cron,227 -f
      |-dovecot,234 -F -c /etc/dovecot/dovecot.conf
      |   |-anvil,237
      |   |-auth,17239
      |   |-config,11263
      |   |-imap,13133
      |   |-imap,13373
      |   |-imap-login,13132
      |   |-imap-login,13362
      |   `-log,238
      |-fetchmail,274 -f /etc/fetchmailrc -v --nodetach --daemon 300 -i /var/lib/fetchmail/.fetchmail-UIDL-cache --pidfile...
      |-opendkim,243 -f
      |   `-opendkim,245 -f
      |       |-{opendkim},246
      |       |-{opendkim},247
      |       |-{opendkim},248
      |       |-{opendkim},249
      |       |-{opendkim},250
      |       `-{opendkim},4070
      |-opendmarc,251 -f -p inet:8893@localhost -P /var/run/opendmarc/opendmarc.pid
      |   |-{opendmarc},252
      |   |-{opendmarc},253
      |   |-{opendmarc},254
      |   |-{opendmarc},255
      |   `-{opendmarc},256
      |-postgrey --inet,259
      |-rsyslogd,229 -n
      |   |-{in:imuxsock},230
      |   `-{rs:main Q:Reg},231
      `-start-mailserve,9 /usr/local/bin/start-mailserver.sh
          `-tail,280 -fn 0 /var/log/mail/mail.log
```

I'm still suspecting some log rotation / SIGHUP handling and looking into the image logrotate now.

**Comment by johansmitsnl** [comment]
I see the same issue on my own server. Investing to here.

**Comment by johansmitsnl** [comment]
Found some interesting information on the bottom of the page https://www.ijs.si/software/amavisd/release-notes.txt
```
/usr/sbin/amavisd-new -P '' foreground

Consider the following amavisd.conf settings when running as a
supervised process:

$pid_file = '';  # can be overridden by a command line option -P ''
$daemonize = 0;  # also implied by a command line argument 'foreground'
$do_syslog = 0;  # or set it to 1 to log to syslog instead of stderr
```

Testing with this change now, but I'm not sure if it does anything different. Also not able to reproduce the issue.

**Comment by johansmitsnl** [comment]
FOUND the cause.
There is a daily cron job /etc/cron.daily/spamasassin
When you run it you get the loop:
```log
mail                     | 2017-08-18 16:58:27,343 INFO exited: amavis (exit status 0; expected)
mail                     | Aug 18 16:58:27 mail postfix/smtpd[2429]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 commands=4
mail                     | Aug 18 16:58:28 mail amavis[2509]: starting. /usr/sbin/amavisd-new at mail.xxx.net amavisd-new-2.10.1 (20141025), Unicode aware, LC_ALL="C"
mail                     | 2017-08-18 16:58:28,178 INFO spawned: 'amavis' with pid 2518
mail                     | 2017-08-18 16:58:28,844 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
```

And there is a post hook in: /etc/spamassassin/sa-update-hooks.d/amavisd-new
It inits a restart and that causes it to detach from supervisor.

Made a PR to fix the issue see #699

**Comment by justinvoelker** [comment]
Awesome. Think that PR would resolve the dovecot issue as well? Seems like it's pretty specific to amavis.

**Comment by johansmitsnl** [comment]
Not sure with dovecot yet.
This is specific for amavis. Dovecot I have not seen it restarting on my mailserver.
You know how to reproduce it?

**Comment by justinvoelker** [comment]
Unfortunately I haven't found a way to force it into happening. But, if I restart my container I probably have a 50/50 chance of dovecot going into this loop. Even when it does start successfully, after a day or two it might hit the issue, seemingly without warning, and takes a container restart or two to get working.

**Comment by VincentGuyader** [comment]
same issue with me.

**Comment by johansmitsnl** [comment]
PR got merged into master, can you all check if it fixes the issue?

**Comment by tomav** [comment]
Latest still building I think. Still need few minutes.

**Comment by tomav** [comment]
Build finished, you can pull `latest`

**Comment by johansmitsnl** [comment]
Now we need to wait for #700 to be merged to fix this ticket completely.

**Comment by justinvoelker** [comment]
The issue persists after pulling the image with #699 included. Looks like another discussion on the topic is taking place at #697 with PR #700 but it isn't merged yet. Not sure if that one will fix the problem, but I won't know until the merge takes place and I can pull that image.

**Comment by tomav** [comment]
Merged, `latest` is currently building.

**Comment by tomav** [comment]
Image built. I let you pull it a confirm that everything is working as expected, ok?
Thank you.

**Comment by justinvoelker** [comment]
Looking good! I restarted the container a dozen times and even rebooted the server half a dozen times. Not a single issue--dovecot started and stayed running each time without issue.

**Comment by tomav** [comment]
Great! And thank @johansmitsnl
