### ISSUE TITLE
Server rejecting email by checktls

### ISSUE THREAD

**Issue by FinnFrotscher** [tomav/docker-mailserver#691]
Ran the setup, creater certificats, added a user. 
Running `docker-compose up` leads to an endless log of `INFO exited: fetchmail (exit status 5; not expected)`. 
The email sent by `checktls` registers, but does not arrive.
And Apple Mail can't authenticate.

I am not sure if those are connected issues. But I assume naïvely that they are.

## the `docker-compose.yml`
```
services:
  mail:
    image: tvial/docker-mailserver:latest
    restart: always
    hostname: mail
    domainname: impact.sx
    container_name: mail
    ports:
    - "25:25"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt/:/etc/letsencrypt
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ENABLE_FETCHMAIL=1
    - SSL_TYPE=letsencrypt
    - ONE_DIR=1
    - DMS_DEBUG=1
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

## the serverlogs

```
...
spawned: 'fetchmail' with pid 1258
success: fetchmail entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
exited: fetchmail (exit status 5; not expected)

mail policyd-spf[1103]: Temperror; identity=helo; client-ip=216.68.85.112; helo=checktls.com; 

envelope-from=test@checktls.com; receiver=finn@impact.sx
spawned: 'fetchmail' with pid 1259
success: fetchmail entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
exited: fetchmail (exit status 5; not expected)
...
```

## the result
```
MX Server | Pref | Answer | Connect | HELO | TLS | Cert | Secure | From | To
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
mail.impact.sx [37.59.109.67] | 1 | OK (107ms) | OK (10,108ms) | OK (104ms) | OK (107ms) | FAIL | OK (10,761ms) | OK (106ms) | FAIL
Average |   | 100% | 100% | 100% | 100% | 0% | 100% | 100% | 0%

```

## the result log
```
[010.655] |   | Cert VALIDATION ERROR(S): self signed certificate
-- | -- | --
[010.655] |   | So email is encrypted but the recipient domain is not verified
[010.655] |   | Cert Hostname DOES NOT VERIFY (mail.impact.sx != 1001c6274ca4)
[010.655] |   | So email is encrypted but the host is not verified
[010.656] | ~~> | EHLO checktls.com
[010.760] | <~~ | 250-mail.impact.sx250-PIPELINING250-SIZE 10240000250-VRFY250-ETRN250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES250-8BITMIME250 DSN
[010.761] |   | TLS successfully started on this server
[010.761] | ~~> | MAIL FROM:<test@checktls.com>
[010.866] | <~~ | 250 2.1.0 Ok
[010.867] |   | Sender is OK
[010.867] | ~~> | RCPT TO:<finn@impact.sx>
[040.870] |   | Read failed (reason: timed out )
[040.870] | <~~ |  
[040.870] |   | Cannot proof email address (reason: RCPT TO rejected)
[040.871] |   | Note: This does not affect the CheckTLS Confidence Factor
[040.871] | ~~> | QUIT
[070.874] |   | Read failed (reason: timed out )
```

**Comment by erunaheru** [comment]
Possibly related: I've noticed that some clients (like Gmail on Android) won't work with just a certificate if there's not a chain included. I may be doing something wrong in how I'm preparing my cert files, but I have a tendency to overthink so I changed the manual certificate section in start-mailserver.sh:

`	"manual" )
		# Lets you manually specify the location of the SSL Certs to use. This gives you some more control over this whole processes (like using kube-lego to generate certs)
		if [ -n "$SSL_CERT_PATH" ] \
		&& [ -n "$SSL_KEY_PATH" ]; then
			notify 'inf' "Configuring certificates using cert $SSL_CERT_PATH and key $SSL_KEY_PATH"
			mkdir -p /etc/postfix/ssl
			cp "$SSL_CERT_PATH" /etc/postfix/ssl/cert
			cp "$SSL_KEY_PATH" /etc/postfix/ssl/key
			chmod 600 /etc/postfix/ssl/cert
			chmod 600 /etc/postfix/ssl/key

			# Postfix configuration
			sed -i -r 's~smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem~smtpd_tls_cert_file=/etc/postfix/ssl/cert~g' /etc/postfix/main.cf
			sed -i -r 's~smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key~smtpd_tls_key_file=/etc/postfix/ssl/key~g' /etc/postfix/main.cf

			# Dovecot configuration
			sed -i -e 's~ssl_cert = </etc/dovecot/dovecot\.pem~ssl_cert = </etc/postfix/ssl/cert~g' /etc/dovecot/conf.d/10-ssl.conf
			sed -i -e 's~ssl_key = </etc/dovecot/private/dovecot\.pem~ssl_key = </etc/postfix/ssl/key~g' /etc/dovecot/conf.d/10-ssl.conf

			if [ -n "$SSL_CA_PATH" ]
			then
				cp $SSL_CA_PATH /etc/postfix/ssl/ca
				chmod 600 /etc/postfix/ssl/ca
				sed -i -e 's~#ssl_ca = ~ssl_ca = </etc/postfix/ssl/ca~g' /etc/dovecot/conf.d/10-ssl.conf					
				sed -i -r 's~#smtpd_tls_CAfile=~smtpd_tls_CAfile=/etc/postfix/ssl/ca~g' /etc/postfix/main.cf
			fi	
			
			notify 'inf' "SSL configured with 'Manual' certificates"
		fi`

**Comment by FinnFrotscher** [comment]
I gave up. bought mailspace

**Comment by Dvalin21** [comment]
Hate to hijack, but I'm having the same issue. Same setup
