### ISSUE TITLE
Changelog not updated

### ISSUE THREAD

**Issue by tbool** [tomav/docker-mailserver#693]
I am still using version 2.1 and would like to upgrade to one of the newer versions. But before doing so I would like to know what changed in each newer version, and what new environment variables can/must/should be set. There is a Changelog on github, but after version 2.0 more than a year ago it does not seem to get updated with new information.

**Comment by tomav** [comment]
Changelog are kept simple and are available here : https://github.com/tomav/docker-mailserver/releases

Except version upgrades, but fixes and added postgrey, nothing new has been released.
A 2.4 will lend soon with improvements made on master branch an not yet tagged.

You can test your upgrade locally and feel free to open an issue if you need help.

**Comment by tbool** [comment]
Hi Thomas, 

Thanks, exactly the info I was looking for. Understand your desire to keep things simple, but while you do have a changelog document, why not keep it up-to-date by simply copying the content of this releases page to it? 
Or get rid it of it if you do not want to maintain the same info on 2 places. 

Best regards, Ton

**Comment by tomav** [comment]
Yep, I think `CHANGELOG.md` will be removed in favor of Github release page.
