### ISSUE TITLE
Alias not working

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#7]
Hi, I am using your mail stack with docker-compose. It works great for smtp, but for receiving emails, I could not get it to work. I get always the message:

An error occurred while sending mail. The mail server responded:  5.1.1 <test@my-domain.com>: Recipient address rejected: User unknown in virtual mailbox table. Please check the message recipient test@my-domain.com and try again.

In my docker-compose, I have tried many aliases configurations, but any of them worked.
Any idea?

**Comment by tomav** [comment]
Hi @citec, thanks for trying this container.

Could you give me the `docker-compose` file you're using?
Perhaps it's the default yml file?

I'll try to reproduce the problem.

Thank you.

**Comment by citec** [comment]
Hi @tomav , thanks for your answer.
Sorry, my bad, I had a DNS problem, not related with any of your code. The container works great, just a filesystem initialization warning when linking the account with thunderbird.
I plan to add a db+web ui container to the mix to store the accounts and aliases and manage them visually. Do you want me to PR here or do you prefer to keep all by env vars as it is now ?

**Comment by tomav** [comment]
@citec , why don't you use Dovecot instead?

**Comment by citec** [comment]
I have currently some servers with postfix+dovecot, using mysql db for storing vmailboxes. I am using your repo cuz it is already done ;) (thanks), but yes, maybe I change to dovecot and clone the config I have on the servers.

**Comment by tomav** [comment]
I made this container beceause most email docker image were using databases and I wanted to keep it simple and make configs portable and easy to deploy.
So, what I suggest is to create another project because your improvement will change the philosophy of this image (event it's probably a good idea).
Thank you.
