### ISSUE TITLE
Docker-compose example file for multiple domains

### ISSUE THREAD

**Issue by kshitizlondon** [tomav/docker-mailserver#70]
It would be great if you can show example code for:

- multiple domain docker-compose.yml file
- account files (to manage users/email addresses on multiple domains)

**Comment by tomav** [comment]
Hi @kshitizlondon, the `docker-compose.yml` file is not multi-domain. There's only one main domain called the [fqdn](https://en.wikipedia.org/wiki/Fully_qualified_domain_name).

Regarding the accounts, have a look to the `accounts.cf` located [here](https://github.com/tomav/docker-mailserver/blob/master/test/accounts.cf). It should answer your question.

Feel free to ask if needed.

**Comment by kshitizlondon** [comment]
Do I have to build the image everytime I update the account.cf file for new user/email address
?

**Comment by kshitizlondon** [comment]
Can you also tell what changes I need to make in domain setting at domain registrars example godaddy.com

**Comment by tomav** [comment]
Nope, use a volume to provide the files and restart the container.

**Comment by tomav** [comment]
Regarding DNS, there's nothing more to do with this image than with any other mail server.
A `MX` record in your DNS zone to tell which IP is the mail server.
After that, you'll probably want to add `SFP` or `DKIM`.
