### ISSUE TITLE
virtual_uid_maps and virtual_gid_maps have no effect

### ISSUE THREAD

**Issue by MIvanchev** [tomav/docker-mailserver#706]
Trying 

```
virtual_uid_maps=static:2222
virtual_gid_maps=static:2222
```

in postfix-main.cf for instance is futile, since the constant 5000 is used quite a lot through the initialization script. Also, `virtual_mailbox_base=/var/mail/vhosts` seems to be ignored.

**Comment by johansmitsnl** [comment]
the uid:gid are not changeable now. It is fixed in the docker build and can not be changed. Why do you want to change it? The email folder lives inside the docker only.

https://github.com/tomav/docker-mailserver/blob/0fe86e796be614af511900caa72a800b02499576/Dockerfile#L134

**Comment by MIvanchev** [comment]
Yes, this was an impulsive act on my side, I didn't really think about why I want to change it. I'll close the issue.
