### ISSUE TITLE
instance for IMAP.domain and instance for SMTP.domain

### ISSUE THREAD

**Issue by stevenmunro** [tomav/docker-mailserver#713]
If I were to do this, can both instances share the same config directory? (for accounts)
and do they need separate mailstate or shared?

**Comment by SnowMB** [comment]
When you want to share anything. Why don't you point both domains to the same server and use just one?

**Comment by stevenmunro** [comment]
> When you want to share anything. Why don't you point both domains to the same server and use just one?

Not particularly helpful.

Are there ENV variables to be passed for specifying the domain and cert for IMAP, and a separate domain and cert for the SMTP?

**Comment by johansmitsnl** [comment]
No they are the same for just one domain. 
You can add more domain names to one certificate of course to split up the names.

**Comment by johansmitsnl** [comment]
Does it solve your answer and can it be closed?

**Comment by johansmitsnl** [comment]
Closing due to no reply
