### ISSUE TITLE
WIKI: Configure Accounts

### ISSUE THREAD

**Issue by Steiniche** [tomav/docker-mailserver#716]
I believe that [configure-accounts](https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts) should contain a statement about the docker container needing a restart the first time multi-domaine is configured.
I have been running with one domain, example.tld, and tried to create another domain, example2.tld, However, the mail server rejected the login until the docker container was restart which prompts the multi domain configuration.

**Comment by johansmitsnl** [comment]
Agreed. Added documentation to the wiki: https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts
