### ISSUE TITLE
Mysql Support

### ISSUE THREAD

**Issue by Fmstrat** [tomav/docker-mailserver#722]
Hi,

I've rolled back my "post script" pull request given commentary about how you guys would like things running. And I've implemented a mysql support branch in my fork with `postfix-mysql` and `dovecot-mysql` that works great with VIMBAdmin (as discussed).

How would you like test cases run? In my environment, I can easily fire up a `docker pull mariadb`, set up some tables, and test. I'm using the add-on method of `dovecot.cf` and `postfix-main.conf` in the config directory to make this happen.

However, I don't know if you're OK with a `docker pull` in the test case. A separate mysql or mariadb container is required to do the test case, though. Here's the overall structure of a sample test case (not a full config, but just tests mysql):

```
root@li1749-39:/data/docker/containers/mail/config# ls -lR
.:
total 24
drwxr-xr-x 2 root root 4096 Sep 20 19:01 dovecot
-rw-r--r-- 1 root root  205 Sep 19 14:35 dovecot.cf
drwxr-xr-x 2 root root 4096 Aug 24 20:39 postfix
-rw-r--r-- 1 root root  718 Sep 20 19:02 postfix-accounts.cf
-rw-r--r-- 1 root root  806 Sep 20 11:49 postfix-main.cf

./dovecot:
total 4
-rw-r--r-- 1 root root 378 Sep 20 19:01 dovecot-sql.conf.ext

./postfix:
total 16
-rw-r--r-- 1 root root 161 Aug 24 20:38 alias_maps.cf
```

```
root@li1749-39:/data/docker/containers/mail/config# cat dovecot.cf 
passdb {
  driver = sql
  args = /tmp/docker-mailserver/dovecot/dovecot-sql.conf.ext
}
userdb {
  driver = prefetch
}
userdb {
  driver = sql
  args = /tmp/docker-mailserver/dovecot/dovecot-sql.conf.ext
}
```

```
root@li1749-39:/data/docker/containers/mail/config# cat dovecot/dovecot-sql.conf.ext 
driver = mysql
default_pass_scheme = CRYPT
connect = host=vimbadmin-mariadb dbname=vimbadmin user=vimbadmin password=*******
password_query = SELECT username AS user, password, homedir AS userdb_home, uid AS userdb_uid, gid AS userdb_gid FROM mailbox WHERE username = '%u'
# For LDA:
user_query = SELECT homedir as home, uid, gid FROM users WHERE username = '%u'
```

```
root@li1749-39:/data/docker/containers/mail/config# cat postfix-main.cf 
virtual_alias_maps = mysql:/tmp/docker-mailserver/postfix/alias_maps.cf
virtual_gid_maps = static:2000
virtual_mailbox_base = /srv/vmail
virtual_minimum_uid = 2000
virtual_uid_maps = static:2000
```

```
root@li1749-39:/data/docker/containers/mail/config# cat postfix/alias_maps.cf 
user = vimbadmin
password = ******
hosts = vimbadmin-mariadb
dbname = vimbadmin
query = SELECT goto FROM alias WHERE address = '%s' AND active = '1'
```

Then I'd need to fire up a container, plus a mariadb container with some sample inserts for a test user, before running the postfix test:

```
docker exec -ti mail-mysql postmap -q user@domain.com mysql:/tmp/docker-mailserver/postfix/postfix-mysql-virtual_alias_maps.cf 
```

And reusing the imap login test to confirm dovecot is using mysql:

```
@test "checking imap: authentication works" {
  run docker exec mail-mysql /bin/sh -c "nc -w 1 0.0.0.0 143 < /tmp/docker-mailserver-test/auth/imap-auth.txt"
  assert_success
}
```

So, how can I incorporate a test using a separate mariaDB container?

**Comment by johansmitsnl** [comment]
I saw you pulled the PR and good to see this issue.
With ldap there is also a supporting docker container that is build and started with seeded data.
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/Makefile#L104-L106

My suggestion is to do this the same with mysql (mariadb) with seeded data to pass the tests.
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/Makefile#L7-L13

I would take these tests as a example to make sure the mysql backend works as expected.
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/test/tests.bats#L1098-L1157

For ldap there are some default files with sane defaults.
https://github.com/tomav/docker-mailserver/blob/master/target/postfix/ldap-users.cf
You can override them with the startup script if needed with the hostname, user, pass.
In ldap this is done in:
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/target/start-mailserver.sh#L524-L585
suggestion to do the same for the needed variable that are needed for mysql.

For me the sane defaults could be based on VIMBAdmin project. It looks great and with a entry in the readme to setup both containers together will make it easy for users to start it.

Thanks for the effort and it is a nice addition to the project!

**Comment by Fmstrat** [comment]
Will do. I have a functional VIMBAdmin setup as a mail relay on linode, so I can just use the configs from there as test items. Once I finish setting up my server and it's 100% complete I'll jump back over here and start this up in my fork.

**Comment by simonbuehler** [comment]
hi, was lookiung for this feature as we have lots of aliases and mail accounts, any news on a merge?

**Comment by unomind** [comment]
any news guys?

**Comment by erik-wramner** [comment]
Well, personally I would vote against this as it goes against the mission statement ("Only configuration files, no SQL database"). In my view it is better suited in a fork that focuses on providing a mail server with a database. That's just me though, I don't know what @tomav thinks.

**Comment by johansmitsnl** [comment]
If you are looking for a docker image with MySQL support you could also check https://github.com/hardware/mailserver

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by keducoop** [comment]
In case that somebody lands here we've just created a [docker image](https://hub.docker.com/repository/docker/kedu/docker-mailserver-mysql) merging [dovecot-mysql](https://github.com/julianhille/docker-mailserver/tree/dovecot-mysql) branch with current [tomav/docker-mailserver](https://github.com/tomav/docker-mailserver), [here](https://github.com/Kedu-SCCL/docker-mailserver-mysql) the code.

Cheers.
