### ISSUE TITLE
Fine tune DKIM

### ISSUE THREAD

**Issue by elcolie** [tomav/docker-mailserver#726]
I have the following report.
permerror (no key)
I added it already in the route53.
![screenshot from 2017-09-26 22-10-52](https://user-images.githubusercontent.com/18206728/30867976-9a4bc32c-a307-11e7-8e1d-f36de203e837.png)
```bash
"v=DKIM1; k=rsa;"
"p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC6DPQl36uUhGdCkgbeop9FQ8pHSXT0yLPxg+l1/Ei9fXlkZydafJM1ag8fY2DZ4CSSzMdQZlkH3pwR1o2371JribWOQJehOOGO8MGUulHKKoQdDp/AzHRP+dM7PjZtQr+pB6u7PWN1Cl+CbhBeQjEC4OghPlXWDBD2MqoVNJoaswIDAQAB"
```
Hope it is safe to expose my key here. Touching config is very scary for me.

```bash
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=elcolie.com; s=mail;

	t=1506438266; bh=fdkeB/A0FkbVP2k4J4pNPoeWH6vqBm9+b0C3OY87Cw8=;

	h=To:From:Subject;

	b=ZLM0EmGZ6B/6lwn53Kjr1241L5U/eIOghDWDduPi9qe6Il33b/lP7PqAD65QtIQHt

	 x8raiLy84eZriF7Dr+gXT5550gzBundIbl17omQ+nEDhurgpJZMkJhAThfeLB6hURy

	 Mn7FM1cvGyQjeMIj0Rb3YK1Jz+x4psVuXtb4O5I0=

Signed-by: sarit@elcolie.com

Expected-Body-Hash: fdkeB/A0FkbVP2k4J4pNPoeWH6vqBm9+b0C3OY87Cw8=



DKIM-Result: permerror (no key)
```

**Reference:**
https://github.com/tomav/docker-mailserver/issues/723#issuecomment-331991462

**Comment by johansmitsnl** [comment]
Your DNS is not setup properly.
Read this section of the WIKI: https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM#dkim-txt-record

**Comment by elcolie** [comment]
@johansmitsnl Never though that I have to do debugging. 
Because I strictly follow the instruction every steps. Here

```bash
$ dig TXT elcolie.com

; <<>> DiG 9.10.3-P4-Debian <<>> TXT elcolie.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39678
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;elcolie.com.			IN	TXT

;; ANSWER SECTION:
elcolie.com.		300	IN	TXT	"v=DKIM1; k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC6DPQl36uUhGdCkgbeop9FQ8pHSXT0yLPxg+l1/Ei9fXlkZydafJM1ag8fY2DZ4CSSzMdQZlkH3pwR1o2371JribWOQJehOOGO8MGUulHKKoQdDp/AzHRP+dM7PjZtQr+pB6u7PWN1Cl+CbhBeQjEC4OghPlXWDBD2MqoVNJoaswIDAQAB"

;; Query time: 120 msec
;; SERVER: 203.144.206.29#53(203.144.206.29)
;; WHEN: Tue Sep 26 23:49:40 +07 2017
;; MSG SIZE  rcvd: 286
```

Test with http://www.appmaildev.com/en/dkim
![screenshot from 2017-09-26 23-53-52](https://user-images.githubusercontent.com/18206728/30872988-fcc82d34-a315-11e7-92ec-4af4029f36c5.png)

**Comment by johansmitsnl** [comment]
@elcolie it is because you overlooked the commands in the wiki...

Your dns entry should be:
```
dig TXT mail._domainkey.elcolie.com
```
but you do not have a dns entry by that name. Read the wiki more carefully and do not skip parts of it.

**Comment by elcolie** [comment]
@johansmitsnl 
Thank you very much.
In the wiki I read it. But misinterpret because smtp works then I was truly believe that config is correct.

![screenshot from 2017-09-27 00-07-35](https://user-images.githubusercontent.com/18206728/30873572-e4e373e8-a317-11e7-8dde-8c77257425e7.png)

![screenshot from 2017-09-27 00-07-59](https://user-images.githubusercontent.com/18206728/30873588-f302f002-a317-11e7-9eb1-221f84da2c3c.png)
