### ISSUE TITLE
Fetchmail "set daemon 60" option not working

### ISSUE THREAD

**Issue by dmcgrandle** [tomav/docker-mailserver#727]
First of all, thank you for the excellent docker mailserver solution.  I had a bit of fun working through issues to make the docker-compose.yml work with a macvlan network, but I now have that up and running.  The mailserver is mostly functional, and I am using fetchmail to retrieve mail from an external server.  

Below is my fetchmail.cf file which was placed in the config/ directory before executing docker-compose up:

```
set daemon 60

poll 'pop.maildomain.com' proto POP3
   user "tester@mcgrandle.com"
   pass "xxxxxxx"
   is "tester@mcgrandle.com"
   ssl
```
However, the daemon continues to poll every 300 seconds, not every 60.  When I enter the container and cat the fetchmailrc config file I see the following:

```
root@mail:/# cat /etc/fetchmailrc
# General options

set daemon 300
set syslog

# Fetch rules

set daemon 60

poll 'pop.maildomain.com' proto POP3
   user "tester@mcgrandle.com"
   pass "xxxxxxx"
   is "tester@mcgrandle.com"
   ssl

root@mail:/#
```

So it looks like having two 'set daemon' options in the config file means the second is ignored, instead of the second option overwriting the first.  Would like to see this fixed.

Thanks!
:D

**Comment by johansmitsnl** [comment]
Currently there is no option to set the deamon refresh time. You could suggest a pull request making it variable.
Are you interested in contributing?

**Comment by dmcgrandle** [comment]
Thanks for the response.  According to the wiki this should have worked:

https://github.com/tomav/docker-mailserver/wiki/Retrieve-emails-from-a-remote-mail-server-(using-builtin-fetchmail)#polling-interval

Looks like the wiki needs to be updated.  :)

Sure, be happy to contribute.  Any links/pointers to get me started?
:D

**Comment by johansmitsnl** [comment]
In the start-mailserver file there is a section to starts the fetchmail service.
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/target/start-mailserver.sh#L1217-L1221

You could manipulate the config file like spamassassin with the new set fetch variable:
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/target/start-mailserver.sh#L989

Defaults are set here:
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/target/start-mailserver.sh#L15

I would suggest to add a test that verifies the change made by the env variable in this test container:
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/Makefile#L79-L85

and add a test like this one but with your changed variable value
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/test/tests.bats#L755-L758

Any questions let us know

**Comment by dmcgrandle** [comment]
I was thinking more along the lines of parsing the user-given config/fetchmail.cf file for the "set daemon" option, and ONLY entering the default of "set daemon 300" if there is not one given in the fetchmail.cf.  Perhaps have two "default" files to choose from applying, one with the option and one without depending on the presence of the setting in the user-given config file.

That would eliminate the need for an ENV variable.  Thoughts?
:D

**Comment by johansmitsnl** [comment]
That will work to. Fine by me.

**Comment by dmcgrandle** [comment]
Ok, pull request submitted.  Since it's my first one on this project please give me feedback, positive or negative.  

I also noticed that with the build process it leaves quite a bit of shrapnel around, preventing doing another 'make' after the first (which completes successfully, all tests passed).  Just wondering if that is normal for this project or should I attempt to capture some detail and potentially enter it as a build issue?

**Comment by dmcgrandle** [comment]
More detail.  Here is what I am referring to as "shrapnel".  This is what changes simply by running make:

```
darren@noah docker-mailserver (fix-fetchmail-poll):~/docker-mailserver$ git diff
error: open("test/config/dovecot-lmtp/userdb"): Permission denied
fatal: cannot hash test/config/dovecot-lmtp/userdb
diff --git a/test/config/dovecot-lmtp/conf.d/10-auth.conf b/test/config/dovecot-lmtp/conf.d/10-auth.conf
index fd51326..338a3df 100644
--- a/test/config/dovecot-lmtp/conf.d/10-auth.conf
+++ b/test/config/dovecot-lmtp/conf.d/10-auth.conf
@@ -121,7 +121,7 @@ auth_mechanisms = plain login

 #!include auth-system.conf.ext
 #!include auth-sql.conf.ext
-######!include auth-ldap.conf.ext
+#######!include auth-ldap.conf.ext
 !include auth-passwdfile.inc
 #!include auth-checkpassword.conf.ext
 #!include auth-vpopmail.conf.ext
diff --git a/test/config/dovecot-lmtp/conf.d/15-lda.conf b/test/config/dovecot-lmtp/conf.d/15-lda.conf
index 5f06098..d9c047c 100644
--- a/test/config/dovecot-lmtp/conf.d/15-lda.conf
+++ b/test/config/dovecot-lmtp/conf.d/15-lda.conf
@@ -8,7 +8,7 @@ postmaster_address = postmaster@domain.com

 # Hostname to use in various parts of sent mails (e.g. in Message-Id) and
 # in LMTP replies. Default is the system's real hostname@domain.
-#hostname =
+hostname = mail.my-domain.com

 # If user is over quota, return with temporary failure instead of
 # bouncing the mail.
diff --git a/test/config/dovecot-lmtp/local.conf b/test/config/dovecot-lmtp/local.conf
index 35279f2..47e7661 100644
--- a/test/config/dovecot-lmtp/local.conf
+++ b/test/config/dovecot-lmtp/local.conf
@@ -1 +1,2 @@
 mail_max_userip_connections = 69
+recipient_delimiter = ~
```

My guess is these files simply need to be added to .gitignore.  But more cleanup than that is clearly needed because if make is run again immediately then here is the result:

```
darren@noah docker-mailserver (fix-fetchmail-poll):~/docker-mailserver$ make
cd test/docker-openldap/ && docker build -f Dockerfile -t ldap --no-cache .
Sending build context to Docker daemon   12.8kB
Step 1/4 : FROM osixia/openldap:1.1.6
 ---> 75935f56eb32
Step 2/4 : MAINTAINER Dennis Stumm <dstumm95@gmail.com>
 ---> Running in 2eef34a64d3e
 ---> 5fefc835eafe
Removing intermediate container 2eef34a64d3e
Step 3/4 : ADD bootstrap /container/service/slapd/assets/config/bootstrap
 ---> 62f2e7e94f1f
Removing intermediate container 70b5bdea1b0c
Step 4/4 : RUN rm /container/service/slapd/assets/config/bootstrap/schema/mmc/mail.schema
 ---> Running in a87418d79bef
 ---> 4885ac67eecf
Removing intermediate container a87418d79bef
Successfully built 4885ac67eecf
Successfully tagged ldap:latest
docker build --no-cache -t tvial/docker-mailserver:testing .
error checking context: 'no permission to read from '/home/darren/docker-mailserver/test/config/dovecot-lmtp/userdb''.
Makefile:8: recipe for target 'build-no-cache' failed
make: *** [build-no-cache] Error 1
```

No big deal really, but I thought I'd point it out.
Regards,
:D

**Comment by johansmitsnl** [comment]
Could you verify my comment on your file on #731 ?
I think it can be solved with less changes.

**Comment by dmcgrandle** [comment]
Ok, I have updated the pull request with the new commit as you suggested.  I tested it on my local system and it works.  Whatever the ENV variable is set to is what is polled - it completely ignores whatever may be put in the config file.  This works for me.

Note - if you merge this change in we should update the wiki to reflect the new variable.

**Comment by johansmitsnl** [comment]
WIKI updated.
https://github.com/tomav/docker-mailserver/wiki/Retrieve-emails-from-a-remote-mail-server-(using-builtin-fetchmail)
