### ISSUE TITLE
Contribution for wiki: SSL configuration when Letsencrypt is handled by Traefik

### ISSUE THREAD

**Issue by mbenedettini** [tomav/docker-mailserver#728]
Hi, this is a mini-guide that could be included within https://github.com/tomav/docker-mailserver/wiki/Configure-SSL. Describes how SSL can be configured when Letsencrypt is handled, on the same host, by [Traefik](https://traefik.io/).

Prerequisite:
You should have a working instance of Traefik with Letsencrypt support and certificate storage should be a json file (for example acme.json). There's a guide at https://docs.traefik.io/user-guide/docker-and-lets-encrypt/. Certificates for your mail domain should be already generated.

The whole idea of this guide is to dump Traefik generated certificates from that `acme.json` file to separate `.crt` and `.key` files that can be used by `docker-mailserver` as described in https://github.com/tomav/docker-mailserver/wiki/Configure-SSL#custom-certificate-files .

1. Download script which dumps certificates from https://github.com/containous/traefik/blob/master/contrib/scripts/dumpcerts.sh to your host. I store everything related to traefik within `/storage/traefik` on the host:

```
/storage/traefik# wget https://raw.githubusercontent.com/containous/traefik/master/contrib/scripts/dumpcerts.sh && chmod +x dumpcerts.sh
```

2. Execute the script, passing the location of your acme.json and where you want certificates dumped (this directory will be later mounted for docker-mailserver):

```
/storage/traefik# ./dumpcerts.sh acme.json /storage/traefik/certs/
writing RSA key
Extracting cert bundle for mail.codexia.io
Extracting private key for mail.codexia.io
```
 
3. At this point you should have the corresponding certificate and key under `/storage/traefik/certs/certs` and `/storage/traefik/certs/private`, let's mount that directory so that `docker-mailserver` can access it. 

If you're using docker compose add a line similar to the following to your `docker-compose.yml` 

```
volumes:
  - /storage/traefik/certs:/certs
```

and set `docker-mailserver` ssl config as manual, providing locations of both certificate and key we've just generated:

```
environment:
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/certs/certs/mail.codexia.io.crt
    - SSL_KEY_PATH=/certs/private/mail.codexia.io.key
```

Restart `docker-mailserver` and it should now use the new certificates. 

A nice improvement would be to dump certificates every 3 months and restart `docker-mailserver` automatically.

**Comment by johansmitsnl** [comment]
I assume you could add a process that verifies that the files have changed and then do a restart of postfix and dovecot.
Are you willing to help by a Pull Request?

**Comment by johansmitsnl** [comment]
it is also related to #656

**Comment by mbenedettini** [comment]
@johansmitsnl yeah, why not. I'll look into it and get back to you.

**Comment by johansmitsnl** [comment]
@tbool that is something I have never tested. But also never had any problems with the certificate also. I have never investigated this behaviour or what it should do.
When I look ate the code a restart will be needed, also when i search the internet [here](https://www.shivering-isles.com/lets-encrypt-free-trusted-certificates-for-postfix-and-dovecot/)  and [here](https://aoeex.com/phile/postfix-dovecot-and-lets-encrypt-certificates/) you need to restart/reload both services.

**Comment by tbool** [comment]
@johansmitsnl think you are right, there is a "check-for-changes.sh" script that runs forever and automatically restarts postfix and dovecot, but it only checks for changes in config files (postfix-accounts.cf, postfix-virtual.cf and postfix-regexp.cf) and not for changes in certificates.

The wiki mentions that in case ssl_type=letsencrypt, after starting the container "You don't have anything else to do. Enjoy.". That is not correct then, you still have to manually restart the container if the certificates are renewed. The same as with ssl_type=manual.

A check on changed certificates shouldn't be too difficult to include in the "check-for-changes.sh" script, is it?

**Comment by johansmitsnl** [comment]
It should be easy indeed.

**Comment by pn2** [comment]
I suggest adding...

```
# location of certificate files
SSL_FILES=$(cat /etc/dovecot/conf.d/10-ssl.conf /etc/postfix/main.cf \
                | egrep '^(smtpd_tls|ssl)_(key|cert)' \
                | sed 's/[^\/]*//' \
                | sort \
                | uniq)

# Update / generate after start
echo "${log_date} Makeing new checksum file."
if [ -f postfix-virtual.cf ]; then
	sha512sum --tag postfix-accounts.cf --tag postfix-virtual.cf $SSL_FILES > chksum
else
	sha512sum --tag postfix-accounts.cf $SSL_FILES > chksum
fi
```

...unless something speaks against this way to change things.

On a side note, I wonder whether this way of checking for changes could not lead to problems in the unlikely case that a change is detected in the very moment the files are being written (and yet incomplete).

**Comment by sulliwane** [comment]
With so many people running on letsencrypt certificates (3 months validity only) I'm surprised to discover that docker-mailserver do not auto-reload on certificate renewal/change? I'm wondering if everybody here is restarting its docker-mailserver every 3 month...? Thanks for your input

**Comment by pn2** [comment]
This code change should do exactly this: 

https://github.com/tomav/docker-mailserver/pull/976

**Comment by SnowMB** [comment]
As long as #976 is not merged I hacked a solution that is based on the solution mentioned by @tbool.

I took the script from [DanielHuisman/traefik-certificate-extractor](https://github.com/DanielHuisman/traefik-certificate-extractor) and added container restarting via the docker API.

Have a look at [SnowMB/traefik-certificate-extractor](https://github.com/SnowMB/traefik-certificate-extractor) and the [docker image](https://hub.docker.com/r/snowmb/traefik-certificate-extractor/).

**Comment by erik-wramner** [comment]
@sulliwane restarting as rarely as once every 3 months would be terrible, it means you are running without security updates. You need to get a new version of the container now and then or you are bound to be vulnerable!

**Comment by Its-Alex** [comment]
Up ?

**Comment by youtous** [comment]
Hi, 
I faced the same usecase then I decided to build a decicated image for renewing certificates from traefik.
[youtous/docker-mailserver-traefik](https://github.com/youtous/docker-mailserver-traefik) handles any storage strategy, traefik version. [docker image](https://hub.docker.com/r/youtous/mailserver-traefik/)

**Comment by aendeavor** [comment]
Can confirm:
> [youtous/docker-mailserver-traefik](https://github.com/youtous/docker-mailserver-traefik) handles [...] storage strategy and (latest) traefik version (v2.2).

Tried it just now with a wildcard certificate from a Let'sEncrypt DNS-01 ACME challenge with Cloudflare. It works pretty much out of the box.

#### Caution

With a wildcard certificate, just the `${DOMAINNAME}` needs to be used:

``` YAML
services:
  mailserver_cert_renewer:
    environment:
      - DOMAINS=${DOMAINNAME}

...

  mailserver:
    labels:
      - mailserver-traefik.renew.domain=${DOMAINNAME}
```

**Comment by erik-wramner** [comment]
@youtous if this is not already in the wiki, would you care to add it? Then we can close the issue. Seems like an excellent solution.

**Comment by youtous** [comment]
https://github.com/tomav/docker-mailserver/wiki/Configure-SSL edited.
It should solve https://github.com/tomav/docker-mailserver/issues/877 too ;)

**Comment by erik-wramner** [comment]
Excellent, thanks @youtous.
