### ISSUE TITLE
It appears postfix-generic is not recognized

### ISSUE THREAD

**Issue by JonasT** [tomav/docker-mailserver#730]
We want to do outgoing address rewriting due to a faulty backend application (which sends from `@localhost.local`), which we would want to do with the `/etc/postfix/generic` file: http://www.postfix.org/generic.5.html

However, it appears a `postfix-generic` in the config folder is not recognized by the container startup script. Is there another way to use this file, or can the startup script be changed so this file works?

**Comment by johansmitsnl** [comment]
This should help you: https://github.com/tomav/docker-mailserver/wiki/Overwrite-Default-Postfix-Configuration

**Comment by JonasT** [comment]
So I guess that means we just have to mount it in manually and there's no way to add it through the container's default config folder?

**Comment by johansmitsnl** [comment]
You have to mount it indeed and place the extra config like in the wiki.

**Comment by JonasT** [comment]
Ok, thanks!
