### ISSUE TITLE
insufficient security

### ISSUE THREAD

**Issue by trytuna** [tomav/docker-mailserver#732]
I do have issues with some of the GMX servers. This is what I get. I contacted GMX already but I also wanted to get you guys informed.

    Oct  2 09:40:03 mail postfix/smtpd[1393]: connect from mout.gmx.net[212.227.15.19]
    Oct  2 09:40:03 mail postfix/smtpd[1393]: warning: TLS library problem: error:1409442F:SSL routines:ssl3_read_bytes:tlsv1 alert insufficient security:s3_pkt.c:1487:SSL alert number 71:
    Oct  2 09:40:03 mail postfix/smtpd[1393]: lost connection after STARTTLS from . mout.gmx.net[212.227.15.19]
    Oct  2 09:40:03 mail postfix/smtpd[1393]: disconnect from mout.gmx.net[212.227.15.19] ehlo=1 starttls=1 commands=2

This server basically gets rejected because of insufficient security. I've created an GMX account to proof it by myself but this time it worked without any issues. I can tell that the email that I've created were sent from another IP address.

Do you guys know what exactly is the problem here?

**Comment by johansmitsnl** [comment]
To me it says that the connecting server does not allow the correct tls level or the ciphers that are used by this project.
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/target/postfix/main.cf#L30-L35
Not sure how to verify this if the test emails you send work.

**Comment by trytuna** [comment]
I've figured it out. This is what happens if the TLSA RR is invalid.
