### ISSUE TITLE
Sudden disconnects

### ISSUE THREAD

**Issue by trytuna** [tomav/docker-mailserver#733]
Hi,

here is another email provider which I have issues with.

    Oct  2 10:46:21 mail postfix/smtpd[2967]: connect from unknown[172.18.0.1]
    Oct  2 10:46:21 mail postfix/smtpd[2967]: disconnect from unknown[172.18.0.1] ehlo=1 starttls=1 quit=1 commands=3
    Oct  2 10:46:21 mail postfix/smtpd[2967]: connect from out1.mail.ruhr-uni-bochum.de[134.147.53.149]
    Oct  2 10:46:21 mail postfix/smtpd[2967]: disconnect from out1.mail.ruhr-uni-bochum.de[134.147.53.149] ehlo=1 starttls=1 quit=1 commands=3

This time its not quite obvious what is failing here. I bet it has something to do with the TLS handshake.

**Comment by johansmitsnl** [comment]
Is this a connection to deliver email or just to check if the port is available?

**Comment by trytuna** [comment]
I've figured it out. This is what happens if the TLSA RR is invalid. Also see #732
