### ISSUE TITLE
zen.spamhaus.org not reachable

### ISSUE THREAD

**Issue by MIvanchev** [tomav/docker-mailserver#737]
Getting a lot of:

warning: <ip address>.zen.spamhaus.org: RBL lookup error: Host or domain name not found. Name service error for name=<ip address>.zen.spamhaus.org type=A: Host not found, try again

Also pinging zen.spamhaus.org fails to locate the host. Perhaps it should be removed from the SpamAssasin setup.

**Comment by johansmitsnl** [comment]
Reading about it seems that it is not a bug or broken server.
Read here more about it: https://www.spamhaus.org/faq/section/DNSBL%20Usage#122
It might be something wrong with your dns resolver?

**Comment by johansmitsnl** [comment]
Is it solved?
If yes how was it solved?

**Comment by MIvanchev** [comment]
Hi, I haven't had the time yet to try it out. However I suspect you are correct after reading the provided URL.  I will let you know ASAP. Sorry for the huge delays, my mind is on a lot of stuff these days.

**Comment by johansmitsnl** [comment]
Thanks for the reply. Just checking in to see if it solved.
