### ISSUE TITLE
Spamassassin typo results in saving data to the wrong location

### ISSUE THREAD

**Issue by aarononeal** [tomav/docker-mailserver#739]
The link created in /var/lib is spelled incorrectly which means the link target never receives any data.

```
lrwxrwxrwx  1 root         root         31 Oct  7 09:09 spamassasin -> /var/mail-state/lib-spamassasin
drwxr-xr-x  3 debian-spamd debian-spamd  3 Oct  5 17:07 spamassassin
```

**Comment by aarononeal** [comment]
See `_misc_save_states()` in `target/start-mailserver.sh` where the wrong name is introduced.

**Comment by johansmitsnl** [comment]
Added a PR #741, waiting tests to complete
