### ISSUE TITLE
setup.sh alias error

### ISSUE THREAD

**Issue by kamuri** [tomav/docker-mailserver#740]
I run in an error when i try to add alias via the setup.sh. All other commands works fine.
This happens on my test server (local works fine) 

Using Fedora 25
Kernel : 4.9.10-200.fc25.x86_64
Docker : Docker version 1.12.6, build ae7d637/1.12.6
Docker-compose: docker-compose version 1.9.0, build 2585387
 

> /usr/bin/docker-current: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"listalias\\\": executable file not found in $PATH\"\n".

**Comment by johansmitsnl** [comment]
What is the command you run?

**Comment by kamuri** [comment]
i run on the host system. 

e.g ./setup.sh alias add test@test.de help@test.de 
e.g ./setup.sh alias del test@test.de help@test.de
e.g ./setup.sh alias list

all of them results in this error.

all other commands works fine and without error.
e.g ./setup.sh email list
e.g ./setup.sh email add test@test.de testpassword

No errors with them and they get insertet in the postfix-accounts.cf

**Comment by johansmitsnl** [comment]
There are some tests to ensure this should work:
https://github.com/tomav/docker-mailserver/blob/0bacac781c08491fd1838bc6718a9a00f4621c04/test/tests.bats#L1049-L1056
You use the latest setup.sh?
Could you debug to pinpoint whats wrong?

**Comment by kamuri** [comment]
Ok i guess i know what happens. 
The setup.sh and the rest is from this repo (master). 

While the setup i used the `docker-compose.yml.dist` as provided. But there is the wrong version of the image.  
`image: tvial/docker-mailserver:2.1` and not the 
`image: tvial/docker-mailserver:latest` 
for this reason the setup.sh download the 2.1 version and was not using the latest. I correct this manually after the process was done. 

But this results in that all the alias files in the `target/bin/addalias;delalias;listalias` are missing. 

I will rebuild my container later. But it should be fixed in the `docker-compose.yml.dist`

**Comment by johansmitsnl** [comment]
Could you make a pull request with the change needed. Happy to merge it

**Comment by kamuri** [comment]
Yes. I do it in with the other pull request or i start a new one?

**Comment by johansmitsnl** [comment]
You can create a new pull request, when it arrives I'll merge it.
Thanks for your effort!
