### ISSUE TITLE
Letsencrypt Multi Domain 

### ISSUE THREAD

**Issue by k1ngf15h3r** [tomav/docker-mailserver#742]
Hi guys, I am sure to searched any part of Wiki, readme and issues but can not find a solution. I added a second domain and login and sending is working finde, but I can not find a way to specify the new cert for the second domain.

Any hints for this?

**Comment by thiesschneider** [comment]
Just add this volume:
      -v /yourcerts:/etc/letsencrypt/live \

**Comment by johansmitsnl** [comment]
With second domain you mean that you want to have a different server name?
You should in that case request a multidomain certificate or with letsencrypt add multiple domains to the certificate.

@thiesschneider how would this solve the issue when the image uses only one certificate name?

**Comment by k1ngf15h3r** [comment]
@johansmitsnl second domain with second mx was my intention but I used same mx for the second domain now because otherwise the rdns would be wrong
