### ISSUE TITLE
Access host e-mails

### ISSUE THREAD

**Issue by jeanlyc** [tomav/docker-mailserver#745]
I am running monitoring services and fail2ban on the dockers host. Here, e.g. faiban2, is configured to send e-mails to the localhost mailbox of the docker host. 
How is it possible to have these host mails accessible by the mailboxes configured in the docker-mailserver?

**Comment by johansmitsnl** [comment]
I would say mounting the right volumes in it. But this is something that is not tested by my knowledge. Why not configure a small MTA that can send emails to a user that exists inside the docker mailserver?
Would seem much simpler and robust to the future.

**Comment by jeanlyc** [comment]
I did test this, however, I was unable to get the ports right. 
The mail container listens to the default mail smtp/imap ports and I cannot bind a local MTA to these ports for sending e-mails.

**Comment by johansmitsnl** [comment]
You only need to send email and you don't need a full mail server. 
Use http://msmtp.sourceforge.net/ for example.

**Comment by jeanlyc** [comment]
Thank you. Is was not able to get things working with postfix, but now with msmtp everything works as expected (by using the docker-mailserver as smtp relay).
To set fail2ban to use mstmp on the docker host, the following link was useful (with some adaptions): [Link](https://unix.stackexchange.com/questions/233866/fail2ban-send-email-with-msmtp)
