### ISSUE TITLE
Logs are full of changedetector (exit status 0; expected)

### ISSUE THREAD

**Issue by sandrodz** [tomav/docker-mailserver#747]
Logs are full of:

> 2017-10-17 12:29:52,923 INFO exited: changedetector (exit status 0; expected)
> 2017-10-17 12:29:53,925 INFO spawned: 'changedetector' with pid 3473
> 2017-10-17 12:29:54,927 INFO success: changedetector entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

<img width="643" alt="screen shot 2017-10-17 at 4 30 23 pm" src="https://user-images.githubusercontent.com/8479569/31664998-8f1c5ece-b358-11e7-9740-e08e38e243fc.png">

Is this normal?

**Comment by johansmitsnl** [comment]
This is not the idea. It should run and keep running like a service. Could you check in /var/log/supervisor the output of the service if there is a log of the cause?

**Comment by sandrodz** [comment]
That was easy! thanks for the pointer.

> Makeing new chksum
> sha512sum: postfix-virtual.cf: No such file or directory
> postfix-virtual.cf is missing! exit!
> Makeing new chksum
> sha512sum: postfix-virtual.cf: No such file or directory
> postfix-virtual.cf is missing! exit!
> Makeing new chksum
> sha512sum: postfix-virtual.cf: No such file or directory
> postfix-virtual.cf is missing! exit!
> Makeing new chksum

touching `postfix-virtual.cf` and errors are gone.

**Comment by johansmitsnl** [comment]
What type of setup do you run?
Send email only or maybe you can post your compose file.

@kamuri your PR #552 initiated this bug, could you assist in this?

**Comment by sandrodz** [comment]
I created the file and error is gone. I think we can close this.

**Comment by johansmitsnl** [comment]
I personally use the ldap version so this script does not affect me.
Want I want to know if it is normal that this file is absent. If it can be absent then we should update the script to be robust for this issue.

**Comment by sandrodz** [comment]
Its first time I'm running this container, so I don't know what is expected. But your right if file doesn't exist it should be created, simple touch suffices.

My workflow was simple, I created a directory, created `.yml` file, added user account via command in docs, and did `docker-compose up -d`. I didn't need aliases so I skipped creating the other file.

**Comment by johansmitsnl** [comment]
Thanks for reporting, we should fix this.

@kamuri could you create a update to make it more robust to run without the alias file?

**Comment by kamuri** [comment]
OK I see where the problem is. I fix it later. I just was not thinking of this case.

**Comment by kamuri** [comment]
Ok cleaned the scrip so far. Should not spam the Logs now. 
Anyway i run in a problem. After deleting the postfix-virtual.cf my script spams i the supervisior logs 
```
sha512sum: postfix-virtual.cf: No such file or directory
sha512sum: WARNING: 1 listed file could not be read
```
The sha512sum build something like this. 

```
SHA512 (postfix-accounts.cf) = 5b35f16fe9f42847e2221bc9d01b815a020373d8b3b22040d5ec08ebbffb6baf038bddf3111b39c84f53e65c12b50caf76dbd4cc397bdd5b5402e78469daa647
SHA512 (postfix-virtual.cf) = 0485fbcbb83d261770ebc8039ef5526c51d095d57628359db055b937916034913dc9a2bdec12c73904baef062ba52d08ad763e1c944b7298d20ffdac95badcdf
```
and this is why i get this error. I dont want to use 2 different files for this. But need in the while loop a detect for this. Just don't know how i could handel this without a second file. ... any suggestions?

**Comment by kamuri** [comment]
Nevermind found the option `--ignore-missing` this solve it.

**Comment by johansmitsnl** [comment]
Merged the pr. Please let us know if it solved it and close if it did.

Thanks for the quick reply of the pr!

**Comment by sandrodz** [comment]
Thanks guys! Your awesome.

**Comment by Yajo** [comment]
This exact same problem happened to me today, should we reopen?

My image is this one:

```
...
            "Image": "sha256:fae753b3a3fe749404e7aeae48cbde4d4c6ee5a143c69dd482fad55811c63e61",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "maintainer": "Thomas VIAL",
                "org.label-schema.description": "A fullstack but simple mailserver (smtp, imap, antispam, antivirus, ssl...)",
                "org.label-schema.name": "docker-mailserver",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://github.com/tomav/docker-mailserver",
                "org.label-schema.vcs-ref": "f69d30f",
                "org.label-schema.vcs-url": "https://github.com/tomav/docker-mailserver",
                "org.label-schema.version": "v6.1.0-204-gf69d30f"
            },
...
```

**Comment by erik-wramner** [comment]
Please post a new issue instead, the old problem was solved. However, normally the local config directory is mounted into `/tmp/docker-mailserver` and should contain a `postfix-accounts.cf` file. Thus you shouldn't need to touch it, it should be there already. If you do post a new issue, please include your compose file and possibly describe why you don't have any accounts.
