### ISSUE TITLE
build from git clone don't work

### ISSUE THREAD

**Issue by kamuri** [tomav/docker-mailserver#749]
When i try to build this from scratch then i run in an error while build it via `docker build`.

```
Step 45 : COPY ./target/check-for-changes.sh ./target/start-mailserver.sh ./target/fail2ban-wrapper.sh ./target/postfix-wrapper.sh ./target/docker-configomat/configomat.sh /usr/local/bin/
lstat target/docker-configomat/configomat.sh: no such file or directory
```

The folder `target/docker-configomat/` is empty when i pull this via `git clone https://github.com/tomav/docker-mailserver` 

Seams not correct, or i make a misstake?

**Comment by johansmitsnl** [comment]
You need to load the submodules as well: `git pull --recurse-submodules`

**Comment by kamuri** [comment]
Ok thx. May im the only one who build this from scratch. 👍

**Comment by Beenhakker** [comment]
https://stackoverflow.com/questions/1030169/easy-way-to-pull-latest-of-all-git-submodules
