### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Vartkat** [tomav/docker-mailserver#750]
Hello,

As a totally newbie to Docker here are my questions.
Since I'm in the process of setting up a complete website on a VPS I'm planning to use VIrtualMin on Ubunutu 16.04.
VirtualMin FAQ says 
"**What if I already installed Apache, Postfic, MySQL, Dovecot, etc. on my system?**
_If you installed from the OS standard repository for your OS, everything should be fine. If you installed from any third party sources, or from source, the installation will fail and things will go badly. The install script cannot accommodate packages installed from non-standard sources. It just isn't that smart._"

Q1- If I use this container to install my mail server how will it be seen by VirtualMin ? Has anyone experienced this kind of config ?
Q2-Do you know this memory footprint of such a bunch of apps installed ?
Q3- If I'm using my mail server as a really with services that already filter email do I still need SpamAssassin, ClamAv, Amavis... Wouldn't it be belt and suspenders ?

Thanks for your help

Regards
V.

**Comment by johansmitsnl** [comment]
A1- Not sure how this would work, I guess Virtual admin expects config files at default location and they aren't with the docker.
A2- 512M without ClamAV and 1G with ClamAV
a3- There are some variable that can turn off and on certain elements, check the readme for this

**Comment by domnoble** [comment]
if you already installed those services, then they are going to cover the ports for the services on the VPS which means when you try to forward the mailserver container ports for IMAP, SMTP etc to the host port there are going to be conflicts, if you install this mailserver and you want it to be seen by virtualmin then i imagine there are going to be some issues with manual configuration of virtualmin, 

my previous configuration was RHEL fedora with cockpit as the web UI, i used this mailserver package for the main services, emails were total manual shell set up, no fancy UI, i did try to experiment a bit with different email admin containers, but i found it was futile and gave up, i set up a separate container running roundcube for a webmail interface and it just worked

currently i am in the middle of trying to setup the same setup on a bunch of VPS running fedora cloud atomic linux kubernetes cluster with a fedora FreeIPA LDAP VPS for the users, its not going well, docker can save you a lot of headaches, but its a pain to set everything up the first time, this is my first time trying to set everything up with LDAP

if you are looking to move toward containers you probably should be running everything via containers, if you want a virtualmin install, install one of the virtualmin docker hub images inside docker.
