### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by oreHGA** [tomav/docker-mailserver#752]
Hi, i've been searching for a proper mail server for my VPS but all of them seem to want have total control of my machine( i.e im not able to have a dynamic web application running  on the mail server)

Q1 - will I be able to use my web server as usual with the docker mail server running 
Q2 - I installed "mail-in-a-box" and i just realized you can't actually uninstall it. I plan on killing the daemon and then using this "docker-mailserver" . Would the  docker-mailserver still work as expected?

Thank you

**Comment by johansmitsnl** [comment]
A1 - You should see docker as a application, yes you can mix applications (and docker)
A2 - "mail-in-a-box" installs packages and configures them. You should check your apt.log (if Debian/Ubuntu) what packages where installed and you can simply remove them.
See the setup script:
https://github.com/mail-in-a-box/mailinabox/blob/cd554cf480b6fc6cb1e2d003ca99ccae9423f650/setup/start.sh#L98-L112

**Comment by oreHGA** [comment]
Thanks for this! It worked as expected!
