### ISSUE TITLE
command mail not work 

### ISSUE THREAD

**Issue by youmoula** [tomav/docker-mailserver#756]
docker:Server Version: 17.09.0-ce
docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
Linux ebz 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

the docker had build , the container mail had run, but the command 'mail' not work.
e.g. the FQDN name is mail.domain.com. 

> docker exec -it mail bash

> mail -vs "Test DKIM" user@mailserver.domain.com

> bash: mail: command not found

when I run 'dpkg-reconfigure postfix' : 

> 
> * Stopping Postfix Mail Transport Agent postfix                         [ OK ]
> 
> Postfix configuration was untouched.  If you need to make changes, edit
> /etc/postfix/main.cf (and others) as needed.  To view Postfix configuration
> values, see postconf(1).
> 
> After modifying main.cf, be sure to run '/etc/init.d/postfix reload'.
> 
> Running newaliases
> postalias: fatal: unsupported dictionary type: texthash. Is the postfix-texthash package installed?

I don't know what's wrong about it ,,  hope the answer of this question..

**Comment by Shemeikka** [comment]
Yes, I have this same problem though I run into this problem when upgrading and building a new image using this docker-mailserver image as a base image.

It seems that the current postfix configuration is not valid or at least will not be valid when postfix is updated. And this breaks everything.

I'm currently trying to get this to work or at least find a work-around.

I encounter this issue using following tags: latest, 2.3, 2.1

@johansmitsnl  Any ideas?

**Comment by johansmitsnl** [comment]
See my answer on: https://github.com/tomav/docker-mailserver/issues/763#issuecomment-343587186

**Comment by johansmitsnl** [comment]
I guess it will work when you run the container with all the env variable and let the startup script fix all the variables.
