### ISSUE TITLE
Account-Names without domain

### ISSUE THREAD

**Issue by nknapp** [tomav/docker-mailserver#757]
I would like to set up a new mailserver using this docker-image and migrate the mail from my old dovecot-server to the new one. My problem is:

* The old dovecot-server was running with "passwd"-accounts, so login worked with just "nils" and not "nils@knappi.org"
* The default pattern for accounts in `docker-mailserver` is `username@domain.org`
* `doveadm backup` can only transfer emails from one server to *exactly* the same account on the remote server.

I'm primarily looking for a way to transfer my mail, but another minor concern is that I would like to not require my users to change their settings. So my question is:

* Is it possible to change the configuration such that the login works with only a username and no `@domain.org` and still use `username@domain.org` as primary email-address.

Great work btw. Took me a while to understand everything, but everything fits together very well for my purposes.

**Comment by dmcgrandle** [comment]
Hi Nils, I haven't tested this but if the requirement is just for the initial data move of the mailboxes, could you temporarily use "user" instead of "login" for the data move, then switch back to "login" to access the mailboxes using IMAP?  Does that "just work"?
Regards,
:D

**Comment by nknapp** [comment]
That might work. For now, I have decided to build a custom docker-image with a modified script. I would like to keep the settings, because my users (well, mostly my family) would otherwise have to change there server settings. I thought this might be interesting for other people as well...

**Comment by johansmitsnl** [comment]
This will work ok if you only have one domain or unique user names across domains.
Therefore I think it is risky to add this to the project, any suggestions on this?

**Comment by nknapp** [comment]
A suggestion would be to only strip the domain name of domains that equal the servers domain.

But, I think I will stick to my patch for now (I only have one domain). If anyone else is interested in this, we can talk about it again.

I'm closing this for now.

**Comment by nknapp** [comment]
As it may be interesting to some... The patch is in the following dockerfile:

```Dockerfile
FROM tvial/docker-mailserver:latest

# SSH is needed to log into the origin server and open a reverse ssh tunnel
ADD doveadm.conf /etc/dovecot/conf.d 
RUN apt-get update && apt-get -y install ssh
# Patch start-mailserver.sh (see https://github.com/tomav/docker-mailserver/issues/757)
RUN sed -i 's_echo "${login}:${pass}:5000:5000::/var/mail/${domain}/${user}::" >> /etc/dovecot/userdb_echo "${user}:${pass}:5000:5000::/var/mail/${domain}/${user}::" >> /etc/dovecot/userdb_' /usr/local/bin/start-mailserver.sh
```

`doveadm.conf` is 

```
service doveadm {
  inet_listener {
    port = 12345
  }
}

doveadm_password = aaaaaaa
```
where `aaaaaaa` must be the same doveadm_password as on the origin server.

I use `ssh -R 23456:localhost:12345 user@origin-server` to create the tunnel. And then `sudo doveadm backup -u mailtest tcp:localhost:23456` to synchronize mails for the user `mailtest`.

**Comment by nknapp** [comment]
I have now noticed that with my change to the start-mailserver file, mails will be rejected

> ```
> RUN sed -i 's_echo "${login}:${pass}:5000:5000::/var/mail/${domain}/${user}::" >> /etc/dovecot/userdb_echo "${user}:${pass}:5000:5000::/var/mail/${domain}/${user}::" >> /etc/dovecot/userdb_' /usr/local/bin/start-mailserver.sh
> ```

The log output of my docker-compose-setup is:

```
mail-test     | Dec  5 22:56:16 mail postfix/smtp[1857]: 52BD8180091E: to=<mailtest@test.knappi.org>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.57, delays=0.21/0.01/0/0.36, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as C02461800986)
mail-test     | Dec  5 22:56:16 mail postfix/qmgr[918]: 52BD8180091E: removed
mail-test     | Dec  5 22:56:16 mail dovecot: lmtp(1865): Connect from local
mail-test     | Dec  5 22:56:16 mail dovecot: auth: passwd-file(mailtest@test.knappi.org): unknown user 
mail-test     | Dec  5 22:56:16 mail postfix/lmtp[1864]: C02461800986: to=<mailtest@test.knappi.org>, relay=mail.test.knappi.org[/var/run/dovecot/lmtp], delay=0.03, delays=0.01/0/0/0.01, dsn=5.1.1, status=bounced (host mail.test.knappi.org[/var/run/dovecot/lmtp] said: 550 5.1.1 <mailtest@test.knappi.org> User doesn't exist: mailtest@test.knappi.org (in reply to RCPT TO command))
```

It seems postfix still wants to verify that the mail-address exists in the dovecot userdb (which I don't fully understand. 
I will probably use my change only for transition to the new server.

**Comment by nknapp** [comment]
I got it now: I added a file `/etc/dovecot/conf.d/11-custom-auth.conf` containing

```
# Tell dovecot that the userdb is in format <user> without <domain>
# This is needed when postfix determines whether a user exists
auth_username_format=%n
```

and used the line from above to remove the domain from `userdb`. Now everything works fine.
It even seems to be possible to copy the password hashes from the old `/etc/shadow` so my users won't have to change any configuration.

**Comment by nknapp** [comment]
The replacement for `start-mailserver.sh` must also be done in `check-for-changes.sh`
