### ISSUE TITLE
Service for changing the password

### ISSUE THREAD

**Issue by nknapp** [tomav/docker-mailserver#758]
I would like to propose the addition of a small web-service that can be called over network to change a users password.

The service might be a single Rest-Resource that takes the username, the old-password and the new password and sets the new password if the old password matches.

The primary goal is to allow the creation of plugins for a web-frontend like  [RainLoop](https://github.com/RainLoop/rainloop-webmail) and [RoundCube](https://github.com/roundcube/roundcubemail/) that enables the user to change her password.

I run the web-frontend in a different docker-container in the same docker-compose file. It is easy to mount the `postfix-accounts.cf` into the web-frontend's container. But in order to verify the old password and generate the new one, the service would need access to dovecot-executables.

There are three solutions to this

* add `dovecot` to the web-frontend's container (feels a bit unstable. The dovecot version should be the same as in the `docker-mailserver`-image).
* expose the docker-socket to the web-frontend's container and use `docker exec` to run the dovecot-commands in the `docker-mailserver`-container (feels like a huge security hole, given that the web-frontend is exposed to the internet.)
* create Rest-service that handles the change and call this service from the web-frontend.

I'm still unsure about the best way to implement such a service. Personally I would have added a NodeJS-service, but this may be overkill for such a simple thing. Since Python is already installed in the image, maybe this should be used to implement such a service.

Would anybody else like to have this as well?

**Comment by johansmitsnl** [comment]
There is a issue on this #557.
It is surely interesting and I would go for a Python variant because it is present already.
Close this ticket as a duplicate and please continue on the other issue.
