### ISSUE TITLE
docker-compose in /tmp?

### ISSUE THREAD

**Issue by florensie** [tomav/docker-mailserver#760]
I'm new to docker and wanted to set up this mail server. Everything went fine except that I don't understand how I have to retain my mail server upon reboot if you put the configs in the /tmp folder. Do I need to make a startup script that copies the configs to that folder?

**Comment by johansmitsnl** [comment]
tmp in the docker is not the real tmp. Everything inside a docker gets lost so no matter where the location is it gets lost.
Therefore you must mount the docker tmp dir to your local system to keep the data persistent:
```yaml
volumes:
    - /home/user/mail/config/:/tmp/docker-mailserver/
```
