### ISSUE TITLE
Message size exceeds fixed limit

### ISSUE THREAD

**Issue by beirdostudio** [tomav/docker-mailserver#764]
Hello,

When I try to send a mail with a 7mb pdf attachment, I get this error on the container's log:
`Message size exceeds fixed limit;`
Any idea where the config for that is?

Thank you.

**Comment by johansmitsnl** [comment]
Check #629

**Comment by beirdostudio** [comment]
Thank you.

**Comment by yogo1212** [comment]
This is currently the top result on google and the link to 'some commit' is frankly not ideal.
So, for the people arriving here:
https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#postfix_message_size_limit

**Comment by mirkomaty** [comment]
I set the 

`POSTFIX_MESSAGE_SIZE_LIMIT=102400000
`
(~100MB) and tried to send a mail to a collegue with about 37 MB. Postfix rejects sending this mail. Is there any other place, where I have to change settings?

POSTFIX_MAILBOX_SIZE_LIMIT is undefined, which means unlimited according to the comment in mailserver.env.

**Comment by FGBxRamel** [comment]
I know this is a bit old, but same here

> I set the
> 
> `POSTFIX_MESSAGE_SIZE_LIMIT=102400000 ` (~100MB) and tried to send a mail to a collegue with about 37 MB. Postfix rejects sending this mail. Is there any other place, where I have to change settings?
> 
> POSTFIX_MAILBOX_SIZE_LIMIT is undefined, which means unlimited according to the comment in mailserver.env.
