### ISSUE TITLE
Not able to connect using Java client

### ISSUE THREAD

**Issue by cloudtestsoftware** [tomav/docker-mailserver#770]
Hello,
I am trying couple of days to setup an email server using AWS and send mail through this server using Java client. I am able to connect using thunderbird from my desk top and able to send IMAP email using port 143.

I have a server which is also in AWS and able to telnet on port 25.  But when I am running a java program to send an email it is has a Lost connection

Nov 30 23:46:57 mail postfix/submission/smtpd[15459]: connect from c-73-252-140-25.hsd1.ca.comcast.net[73.252.140.25]
Nov 30 23:46:57 mail postfix/submission/smtpd[15459]: lost connection after CONNECT from c-73-252-140-25.hsd1.ca.comcast.net[73.252.140.25]
Nov 30 23:46:57 mail postfix/submission/smtpd[15459]: disconnect from c-73-252-140-25.hsd1.ca.comcast.net[73.252.140.25] commands=0/0

I tried both ports 25 and 587 and getting the same output. 

Can anyone please  help me what I need to do?

My Yml file is same as the doc, only I replaced the mail domian.

version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

**Comment by scottstensland** [comment]
I suggest you use the command line tool  `swaks`  to exercise your new  mailserver

```
swaks -server  myserversdomain.com:587 -tls --auth-user myusername  --auth-password pwdhere  --to scottstensland@gmail.com  --from  myusername@myserversdomain.com

```
lookup 
`swaks - Swiss Army Knife SMTP, the all-purpose smtp transaction tester`

**Comment by cloudtestsoftware** [comment]
Below is the output I got

250-PIPELINING
<-  250-SIZE 10240000
<-  250-VRFY
<-  250-ETRN
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250-DSN
<-  250 SMTPUTF8
 -> STARTTLS
<-  220 2.0.0 Ready to start TLS
=== TLS started with cipher TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256
=== TLS no local certificate set
=== TLS peer DN="/CN=e209a254c7b5"
 ~> EHLO srimanta-HP-Pavilion-Notebook

<~  250-PIPELINING
<~  250-SIZE 10240000
<~  250-VRFY
<~  250-ETRN
<~  250-AUTH PLAIN LOGIN
<~  250-AUTH=PLAIN LOGIN
<~  250-ENHANCEDSTATUSCODES
<~  250-8BITMIME
<~  250-DSN
<~  250 SMTPUTF8
 ~> AUTH LOGIN
  235 2.7.0 Authentication successful
 ~> MAIL FROM:<myusername@myserversdomain.com>
<~  250 2.1.0 Ok
 ~> RCPT TO:<scottstensland@gmail.com>
<~  250 2.1.5 Ok
 ~> DATA
<~  354 End data with <CR><LF>.<CR><LF>
 ~> Date: Thu, 30 Nov 2017 16:57:47 -0800
 ~> To: scottstensland@gmail.com
 ~> From: myusername@myserversdomain.com
 ~> Subject: test Thu, 30 Nov 2017 16:57:47 -0800
 ~> X-Mailer: swaks v20130209.0 jetmore.org/john/code/swaks/
 ~> 
 ~> This is a test mailing
 ~> 
 ~> .
<~  250 2.0.0 Ok: queued as 8EF45A1281
 ~> QUIT
<~  221 2.0.0 Bye
=== Connection closed with remote host.

**Comment by cloudtestsoftware** [comment]
But how can I connect using a simple java client with port 25 or 587?

**Comment by cloudtestsoftware** [comment]
I am running this program

public static void main(String[] args) throws AddressException, MessagingException {
	        //Declare recipient's & sender's e-mail id.
	        String destmailid = "myname@gmail.com";
	        String sendrmailid = "no-reply@myserverl.com";	  
	       //Mention user name and password as per your configuration
	        final String uname = "no-reply@myserverl.com";
	        final String pwd = "MyPassword";
	        //We are using relay.jangosmtp.net for sending emails
	        String smtphost = "mail.myserver.com";
	       //Set properties and their values
	        Properties propvls = new Properties();
	        propvls.put("mail.smtp.auth", "true");
	        propvls.put("mail.smtp.starttls.enable", "true");
	        //propvls.put("mail.smtp.EnableSSL.enable","false");
	        propvls.put("mail.smtp.host", smtphost);
	        propvls.put("mail.smtp.port", "587");
	        //Create a Session object & authenticate uid and pwd
	        Session sessionobj = Session.getInstance(propvls,
	           new javax.mail.Authenticator() {
	              protected PasswordAuthentication getPasswordAuthentication() {
	                 return new PasswordAuthentication(uname, pwd);
	  	   }
	           });
	   
	        try {
	  	   //Create MimeMessage object & set values
	  	   Message messageobj = new MimeMessage(sessionobj);
	  	   messageobj.setFrom(new InternetAddress(sendrmailid));
	  	   messageobj.setRecipients(Message.RecipientType.TO,InternetAddress.parse(destmailid));
	  	   messageobj.setSubject("This is test Subject");
	  	   messageobj.setText("Checking sending emails by using JavaMail APIs");
	  	  //Now send the message
	  	   Transport.send(messageobj);
	  	   System.out.println("Your email sent successfully....");
	        } catch (MessagingException exp) {
	           throw new RuntimeException(exp);
	        }
	     }

I am getting below output


Exception in thread "main" java.lang.RuntimeException: javax.mail.SendFailedException: Sending failed;
  nested exception is:
	class javax.mail.MessagingException: 530 5.7.0 Must issue a STARTTLS command first

	at com.bidcrm.data.test.TestPop3.main(TestPop3.java:44)
Caused by: javax.mail.SendFailedException: Sending failed;
  nested exception is:
	class javax.mail.MessagingException: 530 5.7.0 Must issue a STARTTLS command first

	at javax.mail.Transport.send0(Transport.java:218)
	at javax.mail.Transport.send(Transport.java:80)
	at com.bidcrm.data.test.TestPop3.main(TestPop3.java:41)

**Comment by johansmitsnl** [comment]
When you use Gmail as the email server then it work?

**Comment by johansmitsnl** [comment]
You should send email on the 587 port. Port 25 is only for receiving.
Did you solve it?

**Comment by mwlczk** [comment]
@cloudtestsoftware what version of JRE are you using? is it compatible with the cipher list?
