### ISSUE TITLE
SSL/TLS with Thunderbird: connection time out

### ISSUE THREAD

**Issue by alen12345** [tomav/docker-mailserver#771]
I have successfully been using this wonderful image for more than a year now. 

In Thunderbird, I can access my Inbox on port 993 using SSL/TLS; unfortunately, I am obliged to employ port 587 with STARTTLS and not SSL/TLS. The connection is timed out when trying to send an email.

Can you please guide me in the debugging of the problem?

Many thanks in advance to anyone who is willing to help.

AN

**Comment by johansmitsnl** [comment]
Check the log of the container. Most of the time it shows a useful indication what might be wrong.

**Comment by alen12345** [comment]
I would like to add that this behavior is not limited to Thunderbird only, but also to other email clients.

**Comment by johansmitsnl** [comment]
@alen12345 And when you use openssl to connect to your server, it is happy about the certificate?
`openssl s_client -connect imap.gmail.com:993 -crlf`

**Comment by alen12345** [comment]
@johansmitsnl here is the output from the command (no problem in saying that my own domain is _aeetb.com_) enclosed to this message; I think it is rather happy! :)
[openssl-s_client.log](https://github.com/tomav/docker-mailserver/files/1540393/openssl-s_client.log)

Can I give you additional info?

AN

**Comment by alen12345** [comment]
@johansmitsnl solved! I think we should add to the documentation that we need to remove port 587 used for STARTTLS from docker-compose.yml and add port 465 (adding both does not work). 

Thanks again for your time.

AN

**Comment by johansmitsnl** [comment]
I use both without any problems. By not exposing a port does not disable the service behind it or change its function inside a docker. You might changed something else to.
