### ISSUE TITLE
Attempting to add custom certs gives docker-compose error

### ISSUE THREAD

**Issue by TheCraiggers** [tomav/docker-mailserver#772]
I'm attempting to follow the instructions here: https://github.com/tomav/docker-mailserver/wiki/Configure-SSL#custom-certificate-files

When I add those lines into my docker-compose file, I get the following error and it dies immediately:

`ERROR: In file './docker-compose.yml', volume must be a mapping, not an array.`

I assumed from the guide that I was supposed to put those lines on their own, at the end of the file, and not inside one of the containers. Searching around online gives me the impression that what the guide is telling me to do isn't even possible in docker-compose, but maybe that's from older versions?

I'm currently using version 1.16.1, build 6d1ac21 of docker-compose. It's one version behind, but I'm thinking that's not the issue since the instructions I'm following were from 2016.  I just did a docker-compose pull.

Here's the bit I added to the file:
```
volumes:
  - /my/path/to/cert/folder:/tmp/ssl:ro
environment:
  - SSL_TYPE=manual
  - SSL_CERT_PATH=/tmp/ssl/cert.cer
  - SSL_KEY_PATH=/tmp/ssl/key.key
```

**Comment by johansmitsnl** [comment]
Not seeing the error, check docker compose notation because that is giving the error.

**Comment by TheCraiggers** [comment]
I agree that it seems to be the docker compose syntax giving the error. I only opened the issue here because I was thinking the guide may have to be changed.

I'm afraid that I'm pretty new to docker (although I've learned quite a lot from setting this up!) and I'm having trouble finding the error. It goes away if I comment out the new addition of course. One possible cause is invalid alignment / scope in the yaml; I assumed that since this is being used by multiple containers, that it would be by itself, outside of all other entries in the compose file. Is this correct?

**Comment by johansmitsnl** [comment]
There is a online yaml [validator](http://www.yamllint.com/) to test if your yaml is good.

**Comment by Wohlraj** [comment]
can you try adding a trailing slash after "folder"?

```
volumes:
  - /my/path/to/cert/folder/:/tmp/ssl:ro
```

that's the only difference I see with my docker-compose.yml.

**Comment by TheCraiggers** [comment]
Thanks, but I'm still getting the same error about how volume must be a mapping, not a array. Still no idea what it's talking about. Also, I did run it through a YAML validator, and it passed.

Was I correct originally that this belongs at the end of the file? All I can think of is that it belongs under some other section, but it's not working any other place, either.

**Comment by johansmitsnl** [comment]
could you list the files in the /my/path/to/cert/folder/ directory?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
