### ISSUE TITLE
Panic/Error/Fatal: dovecot 2.2.22 core dumped - fixed by using dovecot 2.2.27

### ISSUE THREAD

**Issue by zeezout** [tomav/docker-mailserver#773]
On a IMAP mailbox with 4GB data I constantly get dropped connections with the following errors:

Dec 11 00:14:15 mail dovecot: imap(xxxx@xxxx.xxx): Panic: file mail-index-sync-keywords.c: line 227 (keywords_update_records): assertion failed: (data_offset >= sizeof(struct mail_index_record))
Dec 11 00:14:15 mail dovecot: imap(xxxx@xxxx.xxx): Error: Raw backtrace: /usr/lib/dovecot/libdovecot.so.0(+0x7aee2) [0x7f02b4d8fee2] -> /usr/lib/dovecot/libdovecot.so.0(+0x7afcd) ...
Dec 11 00:14:15 mail dovecot: imap(xxxx@xxxx.xxx): Fatal: master: service(imap): child 1293 killed with signal 6 (core dumped)

Stopping the mailserver, removing the dovecot.* files in the Maildir and restarting did not help. 

The current docker image based on ubuntu:16.04 installs dovecot 2.2.22. After rebuilding the docker image with ubuntu:17.04 which installs dovecot 2.2.27 the problem disappeared.

**Comment by mwlczk** [comment]
Hi, might be resolved with this [PR](https://github.com/tomav/docker-mailserver/pull/784) which switches the base image to debian stretch - i.e. dovecot 2.2.27

**Comment by johansmitsnl** [comment]
Could you retest with the new docker image.
#784 got merged and has a newer version of dovecot.
