### ISSUE TITLE
Cannot connect to LDAP server

### ISSUE THREAD

**Issue by viveksuhanda** [tomav/docker-mailserver#779]
Hi,

When I am trying to send mail to my inbox I am unable to get the mail and when I check the log file I get this error:

Dec 20 06:37:04 mail postfix/pickup[1610]: 490FF4755B: uid=105 from=<root>
Dec 20 06:37:04 mail postfix/cleanup[1614]: warning: dict_ldap_connect: Unable to bind to server ldap://ldap:389 with dn cn=admin,dc=localhost,dc=localdomain: -1 (Can't contact LDAP server)
Dec 20 06:37:04 mail postfix/cleanup[1614]: warning: ldap:/etc/postfix/ldap-aliases.cf lookup error for "vivek.suhanda@gmail.com"
Dec 20 06:37:04 mail postfix/cleanup[1614]: warning: 490FF4755B: virtual_alias_maps map lookup problem for vivek.suhanda@gmail.com -- message not accepted, try again later

This is my modified docker-compose.yml file:

version: '2'

services:
  mail:
    restart: always
    image: dev/mail:latest
    hostname: mail
    domainname: <mydomain>
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./spamassassin:/tmp/spamassassin/
      - ./postfix:/tmp/postfix/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_MANAGESIEVE=1
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SA_KILL=3
      - SSL_TYPE=letsencrypt
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=mail # your ldap container/IP/ServerName
      - LDAP_SEARCH_BASE=dc=ou=<my ou>,dc=<my dc>,dc=<my dc>,dc=<my dc>
      - LDAP_BIND_DN=cn=admin,dc=<my dc>,dc=<my dc>,dc=<my dc>
      - LDAP_BIND_PW=admin
      - LDAP_QUERY_FILTER_USER="(&(mail=%s)(mailEnabled=TRUE))"
      - LDAP_QUERY_FILTER_GROUP="(&(mailGroupMember=%s)(mailEnabled=TRUE))"
      - LDAP_QUERY_FILTER_ALIAS="(&(mailAlias=%s)(mailEnabled=TRUE))"
      - DOVECOT_PASS_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
      - DOVECOT_USER_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=mail
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=<my dc>,dc=<my dc>dc=<my dc>
      - SASLAUTHD_LDAP_PASSWORD=admin
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=<my dc>,dc=<my dc>,dc=<my dc>
      - POSTMASTER_ADDRESS=postmaster@<my domain.com>
      - MAIL_USER=no-reply@<my domain.com>
      - MAIL_PASS=password1324
      - LDAP_QUERY_FILTER_DOMAIN="(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))"

      # >>> Kopano Integration
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
      - POSTFIX_DAGENT=lmtp:kopano:2003
      # <<< Kopano Integration

      - PERMIT_DOCKER=host
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

This is the default docker-compose.yml:

version: '2'

services:
  mail:
    image: dev/mail:latest
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
      - /var/mail/:/var/mail
      - ./spamassassin:/tmp/spamassassin/
      - ./postfix:/tmp/postfix/
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - ENABLE_MANAGESIEVE=1
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SA_KILL=3
      - SSL_TYPE=letsencrypt
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=ldap # your ldap container/IP/ServerName
      - LDAP_SEARCH_BASE=ou=people,dc=localhost,dc=localdomain
      - LDAP_BIND_DN=cn=admin,dc=localhost,dc=localdomain
      - LDAP_BIND_PW=admin
      - LDAP_QUERY_FILTER_USER="(&(mail=%s)(mailEnabled=TRUE))"
      - LDAP_QUERY_FILTER_GROUP="(&(mailGroupMember=%s)(mailEnabled=TRUE))"
      - LDAP_QUERY_FILTER_ALIAS="(&(mailAlias=%s)(mailEnabled=TRUE))"
      - DOVECOT_PASS_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
      - DOVECOT_USER_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=ldap
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=localhost,dc=localdomain
      - SASLAUTHD_LDAP_PASSWORD=admin
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=localhost,dc=localdomain
      - POSTMASTER_ADDRESS=postmaster@localhost.localdomain
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
 
But still I am facing the same above mentioned error.

Also, I have another mail domain so in the default configurations which values should be changed so that I can configure my own domain.

-Vivek Suhanda

**Comment by johansmitsnl** [comment]
You need to link the containers, there is ldap configuration in the wiki available.

**Comment by dolanor** [comment]
@johansmitsnl actually, linking is not encouraged anymore since it was a hacky way in docker to interact between containers.
Now that docker network have DNS resolution, it's way better to put the containers in the same network. By putting the LDAP container also in the same docker-compose will automatically put it in the same docker network, and they will be able to contact each other.

**Comment by johansmitsnl** [comment]
@dolanor Ok, but it might also be wise to declare a depend for the container.
Is it solved?

**Comment by viveksuhanda** [comment]
@johansmitsnl I tried to implement the method given by @dolanor but still facing the same issue. I also tried the steps to configure LDAP according to this link https://help.ubuntu.com/lts/serverguide/openldap-server.html upto the 'Modifying the slapd Configuration Database' step but still facing the same issue.

**Comment by dolanor** [comment]
@viveksuhanda Can you share your docker-compose.yml again with the declaration of the ldap service ?
And please put it into [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by viveksuhanda** [comment]
@dolanor This is the docker-compose.yml file

version: '2'

services:
  mail:
    restart: always
    image: abc/docker-mailserver:latest    
    hostname: x
    domainname: y.z.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./spamassassin:/tmp/spamassassin/
      - ./postfix:/tmp/postfix/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_MANAGESIEVE=1
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SA_KILL=6.31
      - SSL_TYPE=letsencrypt
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      
	  {
	  - ENABLE_LDAP=1
      - LDAP_SERVER_HOST= frosty_stonebraker # your ldap container/IP/ServerName
      - LDAP_SEARCH_BASE=dc=ou=x,dc=y,dc=z,dc=com
      - LDAP_BIND_DN=cn=admin,dc=y,dc=z,dc=com
      - LDAP_BIND_PW=admin
      - LDAP_QUERY_FILTER_USER="(&(mail=%s)(mailEnabled=TRUE))"
      - LDAP_QUERY_FILTER_GROUP="(&(mailGroupMember=%s)(mailEnabled=TRUE))"
      - LDAP_QUERY_FILTER_ALIAS="(&(mailAlias=%s)(mailEnabled=TRUE))"
      }
	  
	  - DOVECOT_PASS_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
      - DOVECOT_USER_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
      
	  {
	  - ENABLE_SASLAUTHD=1
	  - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER= frosty_stonebraker
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=y,dc=z,dc=com
      - SASLAUTHD_LDAP_PASSWORD=admin
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=x,dc=y,dc=z,dc=com
      - POSTMASTER_ADDRESS=postmaster@x.y.z.com
      - MAIL_USER=user@x.y.z.com
      - MAIL_PASS=******
      - LDAP_QUERY_FILTER_DOMAIN="(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))"
	  }
	  
      # >>> Kopano Integration
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
      - POSTFIX_DAGENT=lmtp:kopano:2003
      # <<< Kopano Integration

      - PERMIT_DOCKER=host
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

**Comment by johansmitsnl** [comment]
When you enter the mailserver with bash, can you ping the ldapserver by its hostname? `frosty_stonebraker` or its ip?

**Comment by viveksuhanda** [comment]
Sorry for the delay in reply
I am unable to ping the ldap server by its IP and also getting temporary look up error while sending mails

**Comment by johansmitsnl** [comment]
It sounds like a docker setup issue with the linking.
You can find more here: https://docs.docker.com/network/links/#connect-using-network-port-mapping

**Comment by viveksuhanda** [comment]
I have set the user defined bridge network between the two containers and telnet is working between them. Bur still facing the same issue of temporary look up failure while sending mails. Also in that it says it cannot connect to ldap server.

**Comment by johansmitsnl** [comment]
But now you can ping it from the mail container?

**Comment by johansmitsnl** [comment]
You can also telnet to it inside the mail docker?
```shel
apt update
apt -y install nano
telnet ldap-server-ip 389
Trying 172.16.x.x...
Connected to ldap-server-ip.
Escape character is '^]'.
```

**Comment by viveksuhanda** [comment]
Yes telnet is also working between the two containers.
One query is it mandatory that postfix book schema should be used because the LDAP_QUERY_FILTER'S are desgined according to that schema. But, the openldap container doesn't include that schema.
Also, I included mail entry into the LDAP with inetOrgPerson object class and commented the LDAP_QUERY_FILTER_GROUP and LDAP_QUERY_FILTER_ALIAS in docker-compose.yml but still getting the same error of lookup problem.

**Comment by johansmitsnl** [comment]
I have a docker ldap server that had the postfix book in it: https://hub.docker.com/r/jsmitsnl/docker-openldap-postfix-book/

**Comment by viveksuhanda** [comment]
Tried with this image too but facing the same error of lookup problem. 
One more query how the parameters from the email sending script are passed in the ldap file ?

**Comment by viveksuhanda** [comment]
Also, getting the error of bad search filter. I tried this command inside the ldap container,

ldapsearch -D cn="admin,dc=x,dc=y,dc=z,dc=com" -w **** -b dc=x,dc=y,dc=z,dc=com -s sub "(&(&(mail=user@x.y.z.com)(mailEnabled=TRUE))(&(mailGroupMember=abc_group)(mailEnabled=TRUE))(&(mailAlias=postmaster@x.y.z.com)(mailEnabled=TRUE))(&(|(mail=*@x.y.z.com)(mailAlias=*@x.y.z.com)(mailGroupMember=abc_group))(mailEnabled=TRUE)))"

The above command is able to fetch the values but the same filters applied in the docker-compose.yml file give the error of  bad filter

**Comment by johansmitsnl** [comment]
does this filter end up correctly in the dovecot ldap file or does it differ?

**Comment by viveksuhanda** [comment]
Sorry for replying so late, it ends up properly in the dovecot ldap file 
Still getting the same bad filter error

**Comment by fbartels** [comment]
original issue seems resolved. closing.
