### ISSUE TITLE
Introduce postscreen?! 

### ISSUE THREAD

**Issue by 17Halbe** [tomav/docker-mailserver#780]
Hi there,
what about postscreen? I had it running for quite some time and at least the use of blacklists from different providers repelled almost all attacks on my server. I had around 1 a week. With this server I get several a day.
I would be able to work on a PR next year. 34C3 First! ;)
Anyone interested?

For those who don't know postscreen:
Some more info from the [Postscreen readme](http://www.postfix.org/POSTSCREEN_README.html):

>  Most email is spam, and most spam is sent out by zombies (malware on compromised end-user computers). Wietse expects that the zombie problem will get worse before things improve, if ever. Without a tool like postscreen(8) that keeps the zombies away, Postfix would be spending most of its resources not receiving email.
>The main challenge for postscreen(8) is to make an is-a-zombie decision based on a single measurement. This is necessary because many zombies try to fly under the radar and avoid spamming the same site repeatedly. Once postscreen(8) decides that a client is not-a-zombie, it whitelists the client temporarily to avoid further delays for legitimate mail.
Zombies have challenges too: they have only a limited amount of time to deliver spam before their IP address becomes blacklisted. To speed up spam deliveries, zombies make compromises in their SMTP protocol implementation. For example, they speak before their turn, or they ignore responses from SMTP servers and continue sending mail even when the server tells them to go away.
postscreen(8) uses a variety of measurements to recognize zombies. First, postscreen(8) determines if the remote SMTP client IP address is blacklisted. Second, postscreen(8) looks for protocol compromises that are made to speed up delivery. These are good indicators for making is-a-zombie decisions based on single measurements.
postscreen(8) does not inspect message content. Message content can vary from one delivery to the next, especially with clients that (also) send legitimate email. Content is not a good indicator for making is-a-zombie decisions based on single measurements, and that is the problem that postscreen(8) is focused on. 

-   As the first layer, postscreen(8) blocks connections from zombies and other spambots that are responsible for about 90% of all spam. It is implemented as a single process to make this defense as inexpensive as possible.
-  The second layer implements more complex SMTP-level access checks with Postfix SMTP servers, policy daemons, and Milter applications.
- The third layer performs light-weight content inspection with the Postfix built-in header_checks and body_checks. This can block unacceptable attachments such as executable programs, and worms or viruses with easy-to-recognize signatures.
- The fourth layer provides heavy-weight content inspection with external content filters. Typical examples are Amavisd-new, SpamAssassin, and Milter applications.

CU,

    Alex

**Comment by scottstensland** [comment]
count me in !   sounds super cool

**Comment by 17Halbe** [comment]
So the PR has been sent. 
But, some questions remain, on how to do some things in detail:

## Do we need a whitelist/backlist file?
(http://postfix.cs.utah.edu/postconf.5.html#postscreen_access_list)
        Via introducing an optional config/postfix-access.cidr
        The only permanent whitelisting I could imagine are monitoring services(which might (still?) behave weird/hastely) or blacklisting backup servers(since no traffic should be coming from them anyway)
    Do we need deep inspections? They are desireable, but these tests are expensive: a good client must disconnect after it passes the test, before it can talk to a real Postfix SMTP server. Considered tests are:
        postscreen_bare_newline_enable (http://postfix.cs.utah.edu/postconf.5.html#postscreen_bare_newline_action)
        postscreen_non_smtp_command_enable (http://postfix.cs.utah.edu/postconf.5.html#postscreen_non_smtp_command_action)
        postscreen_pipelining_enable (http://postfix.cs.utah.edu/postconf.5.html#postscreen_pipelining_action)
    Do we need to make the blacklisting via dnsblocking configurable? It's currently set and weighted as follows, where a score of 3 results in blocking, a score of -1 results in whitelisting:
    (*: adds the specified weight to the SMTP client's DNSBL score. Specify a negative number for whitelisting.)
    (http://postfix.cs.utah.edu/postconf.5.html#postscreen_dnsbl_sites)
        zen.spamhaus.org*3
        bl.mailspike.net
        b.barracudacentral.org*2
        bl.spameatingmonkey.net
        bl.spamcop.net
        dnsbl.sorbs.net
        psbl.surriel.com
        list.dnswl.org=127.0.[0..255].0*-2
        list.dnswl.org=127.0.[0..255].1*-3
        list.dnswl.org=127.0.[0..255].[2..3]*-4

## What to do when blacklisting?
 I currently set it to drop. We could
        **ignore**: Ignore the failure of this test. Allow other tests to complete. Repeat this test the next time the client connects. This option is useful for testing and collecting statistics without blocking mail.
        **enforce**: Allow other tests to complete. Reject attempts to deliver mail with a 550 SMTP reply, and log the helo/sender/recipient information. Repeat this test the next time the client connects.
        **drop**: Drop the connection immediately with a 521 SMTP reply. Repeat this test the next time the client connects.

## Drop Postgrey?
In the end I think we could drop postgrey support. Postscreen can replace postgrey in its entirety, while being more selective and not delaying mail. But that requires additional deep inspection options to be activated which in turn delay(soft bounce) incoming mail after their(even successfull) tests. (I would vote against dropping postgrey. That way we would have more granular options for the user.)
