### ISSUE TITLE
Use more than one account error

### ISSUE THREAD

**Issue by huafengchun** [tomav/docker-mailserver#782]
Can I use more than one account?
when I trying to add another account, after add another account then the server is not responding.

What should I do?

**Comment by johansmitsnl** [comment]
Yes you can, see the wiki for setting up accounts.

**Comment by huafengchun** [comment]
Thank you for reply! I use you setup.sh script to add a new account

**Comment by johansmitsnl** [comment]
If it does not exists yes.
