### ISSUE TITLE
Namecheap does not allow more than 1024 bits in the DKIM

### ISSUE THREAD

**Issue by cruisemaniac** [tomav/docker-mailserver#786]
With reference to this: https://www.namecheap.com/support/knowledgebase/article.aspx/317/2237/how-do-i-add-txtspfdkimdmarc-records-for-my-domain

This can be fixed by adding a `-b 1024` parameter to the `generate-dkim-config` and `generate-dkim-domain` scripts.

Is this acceptable? Or is there another way? I'm on namecheap for my domains and I cannot move from there in the near future.

**Comment by johansmitsnl** [comment]
Expanding the 2 scripts to accept the option and add this documentation feels better. Changing defaults may break other users expectations in automatisation.

**Comment by cruisemaniac** [comment]
@johansmitsnl Totally agree with this. Let me dig around and send in a PR. Does that sound fair?

**Comment by johansmitsnl** [comment]
Sounds good

**Comment by johansmitsnl** [comment]
Please add a PR. Will close the issue for now.

**Comment by mwlczk** [comment]
@johansmitsnl @cruisemaniac 
If it comes to namecheap, we don't need any changes in source-code for now. This is an extract from http://www.opendkim.org/opendkim-genkey.8.html:
> (−−bits=n) Specifies the size of the key, in bits, to be generated. The **default is 1024** which is the value recommended by the DKIM specification.

We should be fine with that dkim-key and namecheap (most likely most dns-services).

**Comment by youaresofunny** [comment]
@mwlczk it is not only namecheap problem, got same at yandex and reg.ru
