### ISSUE TITLE
SPF whitelist / ignore when delivered by backup MX

### ISSUE THREAD

**Issue by time4tea** [tomav/docker-mailserver#787]
Love the project - really great!

I use backup email services so I continue to get email when my server is down (e.g. ISP problems). In this case the mail will be delivered to the backup MX and be redelivered to me later. In this case the SPF checks will fail.

Using the python SPF policy there seems to be a possibility of whitelisting the backup MX, or perhaps some other method.

More information is here: http://postfix.1071664.n5.nabble.com/Backup-mx-relay-got-rejected-due-to-SPF-td93693.html

Thanks!

**Comment by cruisemaniac** [comment]
@time4tea Can you show me how to setup a backup MX? Thanks

**Comment by time4tea** [comment]
I don't configure that myself, just buy the service from e.g. dnsmadeeasy, then update DNS MX record to set their mailservers as lower priority MX for your daomain.

**Comment by time4tea** [comment]
I found a possible solution. Looking at http://www.linuxcertif.com/man/5/policyd-spf.conf/

You can add a file into docker-compose.yaml directory: postfix-policyd-spf-python/policyd-spf.conf

```
debugLevel = 1 
TestOnly = 1

HELO_reject = Fail
Mail_From_reject = Fail

PermError_reject = False
TempError_Defer = False

skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1

#just examples
Domain_Whitelist = mx1.mybackupmx.com,mx2.mybackupmx.com

```

Then add line to docker-compose.yml
`- ${PWD}/postfix-policyd-spf/policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf`

**Comment by johansmitsnl** [comment]
Could you add this to the WIKI section?

**Comment by 17Halbe** [comment]
Shouldn't it be possible to just whitelist your backup IP in mynetworks?

Try to add

`mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64 <YOUR BACKUP MX IP>`
to your `config/postfix-main.cf`
(And probably check the output via `postconf -n | grep "mynetworks ="`
See: [Postfix/mynetworks](http://www.postfix.org/postconf.5.html#mynetworks)

Even though your config is working now. Could you probably try if this method works as well?

**Comment by time4tea** [comment]
That would probably mean that all checks are bypassed, but thats not what
you want. It could  mean that any mail sent via the backup server would be
forwarded.... i.e. whoops you made an open relay.

James


On 24 Jan 2018 9:47 am, "17Halbe" <notifications@github.com> wrote:

Shouldn't it be possible to just whitelist your backup IP in mynetworks?

Try to add

mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64 <YOUR BACKUP MX IP>
to your config/postfix-main.cf
(And probably check the output via postconf -n | grep "mynetworks ="
See: Postfix/mynetworks <http://www.postfix.org/postconf.5.html#mynetworks>

Even though your config is working now. Could you probably try if this
method works as well?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tomav/docker-mailserver/issues/787#issuecomment-360076671>,
or mute the thread

**Comment by 17Halbe** [comment]
@time4tea 
you are so right! I feel sorry for even suggesting it! 
So your solution works? 
Could you elaborate a bit on those sections:
```
HELO_reject = Fail
Mail_From_reject = Fail

PermError_reject = False
TempError_Defer = False

skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1
```

**Comment by time4tea** [comment]
No problem.
To be honest, I just copied an example solution and made it work for the docker image. 
The meaning of the various flags should be in the documentation for the python program. I didn't look!

**Comment by 17Halbe** [comment]
Thanks for the honesty! ;) 
I can add this to the wiki or even implement this into the repo, if you can help me a bit with that:

Just to make sure: 
You installed this apt package:
`apt-get install postfix-policyd-spf-python`

you should then somehow require the script to be "mentioned' in the `master.cf` file of postfix, right? Could you please post the output of 
main.cf:
`docker exec mail postconf -n`
and master.cf:
`docker exec mail postconf -M`

Or(and) could you please post the link to your example?
Thanks for your help!

**Comment by time4tea** [comment]
Hi. No i gave full instructions in the earlier post. The package is already installed and configured in the docker image. It's just the comfiguration that needs tweaking to support a backup MX. The docker-compose line simply overlays the existing version of the configuration file with the modified version.

**Comment by 17Halbe** [comment]
Ah, perfect, I'll have a look at that tomorrow.. Thanks!!

**Comment by 17Halbe** [comment]
Done, it's under the SPF page.. Hope that's alright?

**Comment by joewashear007** [comment]
I could be wrong, but I don't think this is in the documentation anymore. It solved an issue I was having with using a mail forward service.

**Comment by georglauterbach** [comment]
@wernerfred could you double-check on @joewashear007 ?

**Comment by wernerfred** [comment]
@joewashear007 here you go: https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/spf/#backup-mx-secondary-mx

This should be the wiki entry mentioned in the earlier comments.
