### ISSUE TITLE
DKIM for a newly added domain requires restart

### ISSUE THREAD

**Issue by sandrodz** [tomav/docker-mailserver#788]
Hi,

For newly generated dkim key container needs to be recreated, otherwise DKIM won't function / e.g. email headers won't show DKIM signature. After recreating containers all work.

I imagine this needs to go in docs/readme, or somehow mitigated.

**Comment by johansmitsnl** [comment]
Added to the wiki documentation: https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM

**Comment by derit** [comment]
how solution if not restart container?
with automatically add dkim without restart required?
