### ISSUE TITLE
SMTP error ever since switch to debian:stretch-slim

### ISSUE THREAD

**Issue by justinvoelker** [tomav/docker-mailserver#790]
I had been using this mailserver image for many months without any issues. I had Windows software and batch scripts sending emails and also PHP scripts using SwiftMailer to send emails from a few websites running on Ubuntu and Alpine linux. It seems that since the switch to debian:stretch-slim my PHP scripts are unable to connect to the mail server to send email. Other connections are working (IMAP connections work, sending email from my Windows scripts works) just not the PHP scripts.

My mail domain (e.g. mail.example.com) hosts a webmail solution using a Let's Encrypt certificate. That same certificate is mounted as a volume inside the mailserver to be used as its certificate since I use that same domain as my mailserver host.

The following errors appear to have started when my mailserver image updated itself to the newest, latest image which contained the switch to debian:stretch-slim.

This is the error I receive inside my web application

```
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

And this is what shows up in the log of the mailserver container
```
Jan 13 06:24:13 mail postfix/submission/smtpd[19607]: SSL_accept error from unknown[123.45.67.89]: -1
Jan 13 06:24:13 mail postfix/submission/smtpd[19607]: warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:1404:
Jan 13 06:24:13 mail postfix/submission/smtpd[19607]: lost connection after STARTTLS from unknown[123.45.67.89]
Jan 13 06:24:13 mail postfix/submission/smtpd[19607]: disconnect from unknown[123.45.67.89] ehlo=1 starttls=0/1 commands=1/2
```

I'm not even sure if this needs to be corrected on the client side or server side at this point. Everything was playing nicely together as of a month ago and today, some clients are still able to connect. Perhaps it's not the fault of the debian:stretch-slim image, but, since this problem cropped up around that time I'm starting here when looking for help finding a solution.

**Comment by mwlczk** [comment]
Hey @justinvoelker ,
I did three things while upgrading:
- updated all the libraries/services to newer versions. Some ciphers might be not accepted by default anymore
- removed all SHA1 ciphers manually from the cipher list of the submission port.
- now the server is presenting the list of ciphers he wants to negotiate about. Before it was the client. This might have lead to a weak cipher being used, we might have forgot to explicitly forbid.

some advices:
- please update your libraries if you can, so they might support the stronger ciphers.
if this does not help use:
- please use the `config/postfix-main.cf` and add the ciphers you may need to the following list:
`tls_high_cipherlist`
 
hope this does help.

**Comment by justinvoelker** [comment]
Thanks for the tips @mwlczk. I created a small PHP script using the newest version of SwiftMailer and the short example from [here](https://swiftmailer.symfony.com/docs/introduction.html) but set the transport as `Swift_SmtpTransport('mail.example.com', 587, 'tls')`. Still no go. I enabled logging in SwiftMailer and this is what it produces:

```
++ Starting Swift_SmtpTransport
<< 220 mail.example.com ESMTP Postfix (Debian)
>> EHLO emailtest.local
<< 250-mail.example.com
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
>> STARTTLS
<< 220 2.0.0 Ready to start TLS
!! Unable to connect with TLS encryption (code: 0)
```

I'm using a pretty basic setup for the mailserver container. Only ports 25, 587, and 993 are forwarded into the container. The Let'sEncrypt certificate directory is mounted as a volume so the mailserver can use the cert for mail.example.com.

Is there any way I can find out what ciphers are different from before the mailserver image was updated? If it the new image is missing a legitimate/secure cipher it should be added. But, if the script library I am using is broken, I would rather not add a bad cipher to my mail server but instead find a new library (or a way to make this one work).

**Comment by mwlczk** [comment]
@justinvoelker , look here
https://github.com/tomav/docker-mailserver/pull/784/commits/3dee443f31dff6525605accf1b702f9a31eb6aa0

**Comment by mwlczk** [comment]
@justinvoelker look at sstok comment here.
https://github.com/swiftmailer/swiftmailer/issues/598

**Comment by justinvoelker** [comment]
@mwlczk you're a life saver. The killer was that SwiftMailer was working with AWS SES. In any event, your link got me around my problem. Bummer that it isn't exactly a great fix, but, at least it's a fix for now. It's still better than dumbing down the mailserver. Thanks again!
