### ISSUE TITLE
where is my mail.log file ? I cannot find  out it

### ISSUE THREAD

**Issue by jzhbiao** [tomav/docker-mailserver#796]
I use centos7 , help me

**Comment by jzhbiao** [comment]
[ALERT] Plaintext authentication not allowed without SSL/TLS, but your client did it anyway. If anyone was listening, the password was exposed.

**Comment by 17Halbe** [comment]
You can get the logs via 
`docker logs mail`
or via the [setup script](https://github.com/tomav/docker-mailserver/wiki/Setup-docker-mailserver-using-the-script-setup.sh)

Your second post about the alert is pretty descriptive, what is your question?

**Comment by jzhbiao** [comment]
Thank you for your reply, your project is good, I seem to solve the problem

**Comment by 17Halbe** [comment]
Thanks, it's not mine though! It's ours I guess! ;) Can be closed.
