### ISSUE TITLE
If set SMTP_ONLY=1, logs output "INFO exited: amavis (exit status 2; expected)" uninterruptedly

### ISSUE THREAD

**Issue by wildtang** [tomav/docker-mailserver#801]
My docker-compose.yml content is 

>version: '2'
>
>services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: somewhere.com
    container_name: mail
    restart: always
    ports:
    - "587:587"
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime
    environment:
    - SMTP_ONLY=1
    - ENABLE_CLAMAV=1
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_FAIL2BAN=0
    - ENABLE_FETCHMAIL=0
    - SSL_TYPE=letsencrypt
    - ONE_DIR=1
    - POSTMASTER_ADDRESS=me@somewhere.com
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
>
>volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

After docker-compose up -d mail, I use docker logs -f mail to see the output logs,
and the log below are being output uninterruptedly.

> 2018-01-09 09:49:37,276 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-01-09 09:49:37,284 INFO exited: amavis (exit status 2; expected)
2018-01-09 09:49:38,287 INFO spawned: 'amavis' with pid 1212

If I SMTP_ONLY to 0 and re-compose the container, It runs OK.

I just need a STMP server, no need IMAP, how can I achieve it?
Or can I limit the box size of every account to a very small size, such as 5M?

My docker host OS is CentOS 7.4 x64, Kernel Version: 3.10.0-693.2.2.el7.x86_64
docker info are:

> Server Version: 17.12.0-ce
WARNING: bridge-nf-call-iptables is disabled
Storage Driver: overlay
WARNING: bridge-nf-call-ip6tables is disabled
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs

Thanks.

**Comment by HyEnd** [comment]
can confirm this on a freshly installed Debian 9 and default configuration (besides SMTP_ONLY=1) 

>Kernel version: 4.9.0-6-amd64

> PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
>NAME="Debian GNU/Linux"
>VERSION_ID="9"
>VERSION="9 (stretch)"
>ID=debian

if you need further information I will try my best :)

**Comment by blackholegalaxy** [comment]
@johansmitsnl @tomav Any information on that? It seems it's impossible to start the docker using SMTP_ONLY without seeing amavis errors everywhere. Using this as a relay, thus no need for any other service than smtp at the moment.

**Comment by mcnilz** [comment]
As workaround I create an empty `/etc/postfix/vhost` file inside the container by mounting it with `-v FULL_PATH_TO_EMPTY_FILE:/etc/postfix/vhost`.

**Comment by johansmitsnl** [comment]
@mcnilz could you provide a PR for this fix?
