### ISSUE TITLE
How to allow users to change own password?

### ISSUE THREAD

**Issue by skorotkiewicz** [tomav/docker-mailserver#808]
Some interaction with POPPASSD would be a great idea for the docker-mailserver.

**Comment by johansmitsnl** [comment]
Could you add a PR?

**Comment by 17Halbe** [comment]
How would you(your users) use it? Website login? Proprietary software? Commandline? It's using the FTP protocol right?
If you wouldn't have to connect to it from the outside world, wouldn't it be easier to just script something which we could also implement into the setup.sh script? 
This can then be utilized via the commandline, and as well via a website-login-form.

**Comment by johansmitsnl** [comment]
@17Halbe multiple options, but the right one that fits all did not appear yet (for me).
Suggestions are welcome.

**Comment by 17Halbe** [comment]
That shouldn't be too difficult... 
What do we need?
- A check if the password for that user is correct
- and we already have a update function to change a users password.

I would leave the php/js coding to the respective admin.. or someone else. ;) I'm neither really good at this kind of stuff, nor am I confident enough to get all security pitfalls convered..

So the user would then login on a website with his user/password combo, we would validate that against the mailserver, and then the website has to take care of legitmitaly allow the user to change the password(again through the setup.sh script)

I don't see any real problems so far.

**Comment by johansmitsnl** [comment]
One of the pitfalls are that you need to gain root rights and that is something you want to be very careful about. Without root your not allowed to changes passwords, but also adding a webserver/webservice to a mailserver sounds strange from a docker perspective.
With a database model (Ldap or MySQL) it seems simpler (safer) then with the setup files.
#557 is indeed a better approach. It needs some plugin writing for some webclients to work and better documentation to be complete.

**Comment by jurekbarth** [comment]
@johansmitsnl can you explain why MySQL is a saver way? Somehow you have to read the passwords/accounts anyway or am i wrong? Of course the root access is not ideal. We could do some kind of polling on one side and only give read access and make changes to another file. Not sure if that makes it any better.
I've also tinkered a litte bit, you can checkout the code here: https://github.com/jurekbarth/mailserver-change-password it's standalone atm. There's no fail2ban implemented which is my biggest concern. Feedback is much appreciated

**Comment by johansmitsnl** [comment]
Safer in the way that you can only access the database information. When you are root you can also access the emails an modify other files on the system.
A separate database gives more separation by default.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
