### ISSUE TITLE
Improve docker image building: reducing layers

### ISSUE THREAD

**Issue by dolanor** [tomav/docker-mailserver#809]
Hi,

First thanks for that great project. Even if I had some issues with my LDAP setup, it is wonderful to exist and work pretty well.
I was wondering if you were open to improve the Dockerfile because it seems it creates a lot of small layers, and maybe we could bundle them up together, without losing readability?

For example, it has multiple ENV commands, but we could bundle them up in 1 to avoid layers just for ENV declaration?
And instead of using multiple COPY, bundle the files in one .tar.gz and ADD it in 1 layer.

**Comment by icebal** [comment]
Also could collapse the run commands into one string, thereby reducing layers even more. Or collapse all of these into a script that can be added and then ran.

**Comment by johansmitsnl** [comment]
Happy to accept a PR. Could you suggest one?

**Comment by dolanor** [comment]
I wanted to talk about it before starting to hack on it :)

The run could also be collapsed, but right now, I think they are pretty well separated. I guess I'll start a PR and we will review it to see how we like it :)

**Comment by Exadra37** [comment]
The most important here is to the RUN commands to be compacted in one if possible because I think this ones would be the ones creating the bigger layers.

Another improvement is that each component of this mail server should have is own Docker Image in order to run as a separated service as per Docker best practices, plus this will allow easy update/upgrade of individual components.

**Comment by johansmitsnl** [comment]
@Exadra37 for seperate services see: #539

**Comment by aendeavor** [comment]
@dolanor is there a PR in the making or has this stalled? If it's the latter, can this be closed?

**Comment by dolanor** [comment]
Haven't figured out how to make time for it yet. So yes, close it for now. I'll reopen it if I can and if I have a PR in the work.
