### ISSUE TITLE
add environment attribute for SMTP relay

### ISSUE THREAD

**Issue by foughtgeoduck** [tomav/docker-mailserver#810]
Hi there, i use this at home and when i need to restart the docker appliance my changes (manually) for the 'relayhost=' option in /etc/postfix/main.cf - get wiped out

my ISP blocks outbound port 25 (except to their own server - which i can relay through)
could someone make a pull request to get the feature added.
EG.
environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - RELAYHOST="smtp.somedomain.com

Also would we be able to change the DNS servers the docker uses aswell ? same as above
       - DNS_SERVER="8.8.8.8,4.2.2.2"

Thanks
Dave

**Comment by johansmitsnl** [comment]
Please read: https://github.com/tomav/docker-mailserver/wiki/Configure-AWS-SES

**Comment by n9yty** [comment]
Not to add noise and confusion, but I am just getting into Docker and looking to hopefully use this awesome project to rebuild a mailserver for a nonprofit... But I read the link you provided and it doesn't seem to answer the original question about being able to specify a relayhost except for Amazon, does it? In the use case I'm looking at, they would route it through their ISP, and I can see other use cases for routing through other internal servers. Perhaps I am just missing something basic?

**Comment by johansmitsnl** [comment]
@n9yty 
You could read the variable like: EXTERNAL_MAIL_RELAY.
My personal opinion about unauthorized mailservers is that it is a security issue indeed.
But I guess when a server is in a tightly monitored and secured network it could be considered save. But adding authentication should not be hard these days.

**Comment by hubermi** [comment]
I use the AWS environment variables to set a relayhost. Just ignore that the env variables contain AWS in its name and set the hostname of your relayserver and user:password pair. Works like a charm in my configuration.

**Comment by dmcgrandle** [comment]
I actually set this in the "postfix-main.cf" file in my config directory and it works just fine.  Here is my directory listing and contents of my postfix-main.cf file:

```
darren@noah mailserver:~/mailserver$ cd config
darren@noah config:~/mailserver/config$ ls -la
drwxrwxr-x 2 darren darren  4096 Feb  7 01:02 .
drwxrwxr-x 4 darren darren  4096 Dec 24 20:47 ..
-rw-r--r-- 1 darren darren   160 Feb  7 01:03 chksum
-rw------- 1 darren darren   515 Dec 24 20:41 fetchmail.cf
-rw-rw-r-- 1 darren darren   568 Feb  7 01:02 postfix-accounts.cf
-rw-rw-r-- 1 darren darren   367 Dec 24 20:41 postfix-main.cf
-rw------- 1 darren darren 12288 Dec 24 20:41 sasl_passwd.db
```

```
darren@noah config:~/mailserver/config$ cat postfix-main.cf
# increase maximum message size
   message_size_limit = 52428800
# set up remote smtp server sasl connections (for outgoing email)
   smtp_sasl_auth_enable = yes
   smtp_tls_security_level = encrypt
   smtp_sasl_tls_security_options = noanonymous
   relayhost = [my.relay.host]
   smtp_sasl_password_maps = hash:/tmp/docker-mailserver/sasl_passwd
```

**Comment by johansmitsnl** [comment]
@hubermi @dmcgrandle shows that it works.
