### ISSUE TITLE
Postfix reject_sender_login_mismatch

### ISSUE THREAD

**Issue by TechnicLab** [tomav/docker-mailserver#811]
Consider using reject_sender_login_mismatch in postfix to prevent users from sending emails from any address.

**Comment by johansmitsnl** [comment]
Could you suggest a PR?

**Comment by TechnicLab** [comment]
I’m happy to but it looks like there are some new configuration needed for current users: http://www.postfix.org/postconf.5.html#smtpd_sender_login_maps, also I’m not sure how to configure this with LDAP.

**Comment by johansmitsnl** [comment]
I think no extra configuration is needed, but if you have a branch I can test it (i use a ldap setup).

**Comment by TechnicLab** [comment]
Ok, I will create it this evening.
