### ISSUE TITLE
Endless restart series of DKIM

### ISSUE THREAD

**Issue by IvanovOleg** [tomav/docker-mailserver#812]
> 2018-02-01 16:20:32,538 INFO success: opendkim entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2018-02-01 16:20:32,544 INFO exited: opendkim (exit status 78; not expected)
> 2018-02-01 16:20:32,545 INFO spawned: 'opendkim' with pid 1671

I run this container on Kubernetes 1.9.1 and attach dkim-related files as a ConfigMap (volume from the container perspective). These files have been generated inside of the container. DKIM accepts them but then goes to the endless restart cycle. I tried to disable clamav, spamassasin, postgrey, fail2ban, but without a success. I also tried to override the hostname, but it didn't help. Is it possible to debug DKIM somehow?

UPD: I tried to use SMTP_ONLY=1, but got Amavis and Dkim restarted.

**Comment by 17Halbe** [comment]
How did you configure Dkim? With the setup.sh script?

Did you enable [Debug Logging](https://github.com/tomav/docker-mailserver#dms_debug)?

**Comment by IvanovOleg** [comment]
Looks like there was a problem with the keyfile.
