### ISSUE TITLE
simplify Configuration

### ISSUE THREAD

**Issue by 17Halbe** [tomav/docker-mailserver#815]
What about moving all configuration options into an .env file?
This is the docker-compose way of configuring environmental variables anyway. See [env-file](https://docs.docker.com/compose/env-file/)

Benefits would be:
- The user wouldn't have to mess around in the compose file itself which we in turn wouldn't have to debug. :+1: 
- It's backward compatible: If one uses his old docker-compose file nothing would change.
- We could explain each variable in the config (.env) file itself.

Sounds cool?

**Comment by johansmitsnl** [comment]
Users can use both at the same time. It could definitely be mentioned in the readme page with a example to.
