### ISSUE TITLE
create sendonly users

### ISSUE THREAD

**Issue by cybertschunk** [tomav/docker-mailserver#816]
hey guys,
I've just setup this mailserver, but couldn't find a way to create sendonly users. Is this feature supported?

**Comment by 17Halbe** [comment]
Is this what you are looking for? #452

It's probably getting implemented as a separate feature, but you could already override the postfix main.cf. 
Consult your local [wiki](https://github.com/tomav/docker-mailserver/wiki/Overwrite-Default-Postfix-Configuration)!

For a start have a look [here](http://www.postfix.org/RESTRICTION_CLASS_README.html)
And you can put your restriction-texthash file in the config folder. It will get mounted in the docker container at /tmp/docker-mailserver/

**Comment by cybertschunk** [comment]
@17Halbe  yeah that was what I meant. Thanks for your advice! Have a nice day
