### ISSUE TITLE
Security and protection

### ISSUE THREAD

**Issue by perarg** [tomav/docker-mailserver#817]
1. How can i control - prevent - secure the mail server of sending blast mails ?

2. Is there any way to check for "attacks" to mail server ? For example multiple tries for login or DoS

**Comment by dragonito** [comment]
Try fail2ban for secure up login

**Comment by perarg** [comment]
Yes, i have fail2ban enabled. It's ok with that.

**Comment by johansmitsnl** [comment]
You should setup your ptr, dkim and spf correctly.
https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM
https://github.com/tomav/docker-mailserver/wiki/Configure-SPF
