### ISSUE TITLE
Adding rancher-compose example to documentation

### ISSUE THREAD

**Issue by dragonito** [tomav/docker-mailserver#818]
Hi there,

is it possible to add a "rancher-compose.yml" example to documentation?

I´m not shure if it´s the same as "docker-compose.yml", perhaps there are just a few changes?

Would be really great!

Robin

**Comment by dragonito** [comment]
Found some links about it:

https://github.com/rancher/rancher-compose

http://rancher.com/docs/rancher/latest/en/cattle/rancher-compose/

**Comment by johansmitsnl** [comment]
You could suggest a PR with a example or write a wiki about it.

**Comment by dragonito** [comment]
I´ve to evaluate it first ;) I will serve my cognitions about it till i got them LOL

**Comment by fbartels** [comment]
If someone with Rancher experience wants to contribute a yml they are free to do so. until then I'll close this issue.

**Comment by salviof** [comment]
Someone?
