### ISSUE TITLE
Every sent mail as junk and what about multiple domains under same mailserver

### ISSUE THREAD

**Issue by perarg** [tomav/docker-mailserver#820]
Hello,

i a fully working mail server. Mails can be sent and can be received. My real problem though is that every email i sent goes to spam or junk folder of other mail servers. I tried gmail.com and hotmail.com. 

I use one main domain for serving mails. Let's say for example, mail.mydomain.com. I have set mx record and txt records v=spf1, v=DKIM. I don't know if the problem is that the domain i use is .tk (i get a free one, just for testing purposes).

In the same server, i would like to add some more domains i use. For example, mydomain2.com and mydomain3.com. What is the proper configuration (maybe for the DNS), so these domains can use with safety the mail server ? When i speak for safety, i mean not to treat these domains as email spoofing (different domain - different mail server domain). Do i have to make new mx records and txt records for every new domain ?

**Comment by mwlczk** [comment]
Most important: you need a PTR record in the dns of your mailservers ISP.

For every domain you need to configure the DNS separately

**Comment by perarg** [comment]
Ok, i see. I have to setup a ptr record for my mail.mydomain.com.

What about the other domains in the same server ?
Will share the same ptr record of the main domain ? If i setup a second domain, secondomain.com, i will create an A record pointing to the same place as mail.mydomain.com. Is this valid ?

So, i have to create a MX record for secondomain.com pointing to mail.mydomain.com ? And create also, txt records for secondomain.com ?

## mydomain.com ##
* txt mydomain.com v=spf1 a ~all
* txt mail._domainkey.mydomain.com v=DKIM1; h=sha256; k=rsa; p=MIIBIjANB...
* mx mydomain.com mail.mydomain.com

## secondomain.com ##
* txt secondomain.com v=spf1 a ~all <--- is this correct for every new added domain ?
* txt mail._domainkey.secondomain.com v=DKIM1; h=sha256; k=rsa; p=MIIBIjANB... <--- _how can i generate another dkim for this domain ? I have created a mail account @secondomain.com and run the `docker run --rm \
  -v "$(pwd)/config":/tmp/docker-mailserver \
  -ti tvial/docker-mailserver:latest generate-dkim-config`. No keys are generated for the second domain, only for the main one._
* mx secondomain.com mail.mydomain.com <--- _pointing to first domain_ ?

**Comment by johansmitsnl** [comment]
Your MX should point to the mailserver name.
Example:
mail.domain.com SERVER
email-1.com MX mail.domain.com
email-2.com MX mail.domain.com
etc..
SPF should point to the mail.domain.com as the allowed sender for both domains.

**Comment by perarg** [comment]
Thank you for reply @johansmitsnl but as DKIM is concerned i didn't get an answer, so i cannot understand why you closed the issue...

Should the command `docker run --rm \ -v "$(pwd)/config":/tmp/docker-mailserver \ -ti tvial/docker-mailserver:latest generate-dkim-config` produce keys for every domain i have setup or only for the mailserver domain ?

**Comment by jurekbarth** [comment]
It should create dkim configs for every domain. Can you login to your seconddomain account?

**Comment by perarg** [comment]
Yes without problem

Στις 7 Φεβ 2018, 12:31 ,και ώρα 12:31 ,Jurek Barth <notifications@github.com> έγραψε:

**Comment by jurekbarth** [comment]
Ok dump question, you're in the right directory while running your command?

**Comment by perarg** [comment]
Yes, in place where docker-compose.yml is located.

**Comment by johansmitsnl** [comment]
See also #869
