### ISSUE TITLE
Spamassassin Bayes Check always scores -1.9

### ISSUE THREAD

**Issue by hubermi** [tomav/docker-mailserver#823]
Hi,
I have a problem with spam recognition. All spamassassin rules work perfect except the bayes test. Every single mail passes with result BAYES_00 and gets -1.9 added to its score which results in many spam mails coming through.

I am training the filter with the  commands from the wiki, and have also trained on a downloaded zip with spam samples.

docker exec  mail sa-learn --dbpath /var/mail-state/lib-amavis/.spamassassin --progress --spam /var/mail/*/*/.Junk/*
docker exec  mail sa-learn --dbpath /var/mail-state/lib-amavis/.spamassassin --progress --ham /var/mail/*/*/cur    

What am I doing wrong? According to search results, this behaviour occurs, when no training data is available. Am I writing the sa-learn results to the wrong path?

**Comment by dmcgrandle** [comment]
How many training emails have you got?  If memory serves it needs a minimum of 2000 (1000 ham and 1000 spam) before it starts taking them into account.

**Comment by hubermi** [comment]
IIRC it was 200 messages, but anyway both limits should not be a problem according to sa-learn --dump magic:
`
0.000          0      83842          0  non-token data: nspam

0.000          0      25674          0  non-token data: nham

0.000          0     148623          0  non-token data: ntokens
`

**Comment by hubermi** [comment]
Just checked, the default limit is 200 spam and 200 ham messages learned. I easily am above that threshold.

I activated debug messages for spamassassin in amavis, here is the output, anybody sees something suspicious?

`
mail    | Feb  8 12:16:50 mail amavis[2156]: SA dbg: config: read file /usr/share/spamassassin/23_bayes.cf
mail    | Feb  8 12:16:51 mail amavis[2156]: SA dbg: bayes: learner_new self=Mail::SpamAssassin::Plugin::Bayes=HASH(0x5d8c558), bayes_store_module=Mail::SpamAssassin::BayesStore::DBM
mail    | Feb  8 12:16:51 mail amavis[2156]: SA dbg: bayes: learner_new: got store=Mail::SpamAssassin::BayesStore::DBM=HASH(0x6266f48)
mail    | Feb  8 12:16:51 mail amavis[2156]: SA dbg: bayes: tie-ing to DB file R/O /var/lib/amavis/.spamassassin/bayes_toks
mail    | Feb  8 12:16:51 mail amavis[2156]: SA dbg: bayes: tie-ing to DB file R/O /var/lib/amavis/.spamassassin/bayes_seen
mail    | Feb  8 12:16:51 mail amavis[2156]: SA dbg: bayes: found bayes db version 3
mail    | Feb  8 12:16:51 mail amavis[2156]: SA dbg: bayes: DB journal sync: last sync: 1518081493
mail    | Feb  8 12:16:54 mail amavis[2156]: SA dbg: bayes: untie-ing
mail    | Feb  8 12:22:43 mail amavis[2161]: (02161-01) SA dbg: bayes: tie-ing to DB file R/O /var/lib/amavis/.spamassassin/bayes_toks
mail    | Feb  8 12:22:43 mail amavis[2161]: (02161-01) SA dbg: bayes: tie-ing to DB file R/O /var/lib/amavis/.spamassassin/bayes_seen
mail    | Feb  8 12:22:43 mail amavis[2161]: (02161-01) SA dbg: bayes: found bayes db version 3
mail    | Feb  8 12:22:43 mail amavis[2161]: (02161-01) SA dbg: bayes: DB journal sync: last sync: 1518092287
mail    | Feb  8 12:22:43 mail amavis[2161]: (02161-01) SA dbg: bayes: corpus size: nspam = 83842, nham = 25703
mail    | Feb  8 12:22:43 mail amavis[2161]: (02161-01) SA dbg: bayes: tokenized body: 958 tokens
mail    | Feb  8 12:22:43 mail amavis[2161]: (02161-01) SA dbg: bayes: tokenized uri: 217 tokens
mail    | Feb  8 12:22:43 mail amavis[2161]: (02161-01) SA dbg: bayes: tokenized invisible: 0 tokens
mail    | Feb  8 12:22:43 mail amavis[2161]: (02161-01) SA dbg: bayes: tokenized header: 116 tokens
mail    | Feb  8 12:22:44 mail amavis[2161]: (02161-01) SA dbg: bayes: score = 5.55111512312578e-17
mail    | Feb  8 12:22:44 mail amavis[2161]: (02161-01) SA dbg: bayes: DB journal sync: last sync: 1518092287
mail    | Feb  8 12:22:44 mail amavis[2161]: (02161-01) SA dbg: bayes: untie-ing

`
Only thing that I see is the db path is different than the one in the wiki. But after checking it out it shows that the directory contents are absolutely equal. Also the nspam an dnham numbers are equal.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
