### ISSUE TITLE
Provide a way to amend main.cf

### ISSUE THREAD

**Issue by exhuma** [tomav/docker-mailserver#824]
On my server I would like to increase the message size limit. But the only way I can do that is by entering the container and manually editing the `main.cf` file.

If I upgrade the container in the future that change will get lost as it's not coming from a volume.

It would be great to have some way to amend the `main.cf` file via a persistent file. I'm sure there are other settings which may make sense  to modify.

**Comment by dmcgrandle** [comment]
Hi exhuma,

This is a pretty common configuration.  See the wiki for more details, but essentially all you have to do is create a "postfix-main.cf" file in your config directory, and in it place this directive:

`# increase maximum message size
   message_size_limit = 52428800`

That is the value I used.  YMMV.  :)

Regards,
:D

**Comment by exhuma** [comment]
Oh great. I did not find this when I was first looking for it (I did not realise there was a wiki). I assume you are talking about [the page titled "Overwrite Default Postfix Configurations"](https://github.com/tomav/docker-mailserver/wiki/Overwrite-Default-Postfix-Configuration)?

A quick follow-up question though: The page is titled "*overwrite*" the config, so, do I copy the existing config completely? Or does it work as an "overlay" (that is, it loads this in addition to the default file)?

**Comment by johansmitsnl** [comment]
Now you have to copy the whole file over. But you might miss features that are added to this file.
I think a easy way is to amend the main file with a extra file in the startup script, if I'm correct postfix overrides the previous value if it is defined twice?

**Comment by dmcgrandle** [comment]
Actually @johansmitsnl when I look at my main.cf file within the container it contains many additional lines, and just appends what I put in, it does not "overwrite" it.  I was careful to only include directives that were not already defined, so my entire config/postfix-main.cf file is quite short.  I posted it in another issue, but for completeness in this thread here is my entire config/postfix-main.cf file again:

```
# increase maximum message size
   message_size_limit = 52428800
# set up remote smtp server sasl connections (for outgoing email)
   smtp_sasl_auth_enable = yes
   smtp_tls_security_level = encrypt
   smtp_sasl_tls_security_options = noanonymous
   relayhost = [my.relay.host]
   smtp_sasl_password_maps = hash:/tmp/docker-mailserver/sasl_passwd
```

Whereas from within the container, here is the entire /etc/postfix/main.cf file (edited for sensitive content) which as you can see is much more extensive:
```
# See /usr/share/postfix/main.cf.dist for a commented, more complete version

smtpd_banner = $myhostname ESMTP $mail_name (Debian)
biff = no
append_dot_mydomain = no
readme_directory = no

# Basic configuration
# myhostname =
alias_maps = texthash:/etc/aliases
alias_database = texthash:/etc/aliases
mydestination =
relayhost = [my.relay.host]
mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64 192.168.x.y/32
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all

# TLS parameters
smtpd_tls_cert_file=/etc/letsencrypt/live/mail.example.com/fullchain.pem
smtpd_tls_key_file=/etc/letsencrypt/live/mail.example.com/privkey.pem
#smtpd_tls_CAfile=
#smtp_tls_CAfile=
smtpd_tls_security_level = may
smtpd_use_tls=yes
smtpd_tls_loglevel = 1
smtp_tls_security_level = encrypt
smtp_tls_loglevel = 1
tls_ssl_options = NO_COMPRESSION
tls_high_cipherlist=ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-CCM8:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256
tls_preempt_cipherlist = yes
smtpd_tls_protocols=!SSLv2,!SSLv3
smtp_tls_protocols=!SSLv2,!SSLv3
smtpd_tls_mandatory_ciphers = high
smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3
smtpd_tls_exclude_ciphers = aNULL, LOW, EXP, MEDIUM, ADH, AECDH, MD5, DSS, ECDSA, CAMELLIA128, 3DES, CAMELLIA256, RSA+AES, eNULL
smtpd_tls_dh1024_param_file = /etc/postfix/dhparams.pem
smtpd_tls_CApath = /etc/ssl/certs
smtp_tls_CApath = /etc/ssl/certs

# Settings to prevent SPAM early
smtpd_helo_required = yes
smtpd_delay_reject = yes
smtpd_helo_restrictions = permit_mynetworks, reject_invalid_helo_hostname, permit
smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf,
    reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net, check_policy_service inet:127.0.0.1:10023
smtpd_client_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, reject_unauth_pipelining
smtpd_sender_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unknown_sender_domain,  reject_sender_login_mismatch
disable_vrfy_command = yes

# Postscreen settings to drop zombies/open relays/spam early
postscreen_dnsbl_action = enforce
postscreen_dnsbl_sites = zen.spamhaus.org*3
	bl.mailspike.net
	b.barracudacentral.org*2
	bl.spameatingmonkey.net
	bl.spamcop.net
	dnsbl.sorbs.net
	psbl.surriel.com
	list.dnswl.org=127.0.[0..255].0*-2
	list.dnswl.org=127.0.[0..255].1*-3
	list.dnswl.org=127.0.[0..255].[2..3]*-4
postscreen_dnsbl_threshold = 3
postscreen_dnsbl_whitelist_threshold = -1
postscreen_greet_action = enforce
postscreen_bare_newline_action = enforce

# SASL
smtpd_sasl_auth_enable = yes
smtpd_sasl_path = /var/spool/postfix/private/auth
smtpd_sasl_type = dovecot

smtpd_sasl_security_options = noanonymous
smtpd_sasl_local_domain = $myhostname
broken_sasl_auth_clients = yes

# Mail directory
virtual_transport = lmtp:unix:/var/run/dovecot/lmtp
virtual_mailbox_domains = /etc/postfix/vhost
virtual_mailbox_maps = texthash:/etc/postfix/vmailbox
virtual_alias_maps = texthash:/etc/postfix/virtual

# Additional option for filtering
content_filter = smtp-amavis:[127.0.0.1]:10024

# Milters used by DKIM
milter_protocol = 6
milter_default_action = accept
dkim_milter = inet:localhost:8891
dmarc_milter = inet:localhost:8893
smtpd_milters = $dkim_milter,$dmarc_milter
non_smtpd_milters = $dkim_milter

# SPF policy settings
policyd-spf_time_limit = 3600

# Remove unwanted headers that reveail our privacy
smtp_header_checks = pcre:/etc/postfix/maps/sender_header_filter.pcre

# postSRSd rules to process spf mail forwarding
sender_canonical_maps = tcp:localhost:10001
sender_canonical_classes = envelope_sender
recipient_canonical_maps = tcp:localhost:10002
recipient_canonical_classes = envelope_recipient,header_recipient
myhostname = mail.example.com
mydomain = example.com
message_size_limit = 52428800
smtp_sasl_auth_enable = yes
smtp_sasl_tls_security_options = noanonymous
smtp_sasl_password_maps = hash:/tmp/docker-mailserver/sasl_passwd
compatibility_level = 2
```

I would have to checkout the code to see exactly where and how the config/postfix-main.cf is parsed and added in to the final /etc/postfix/main.cf within the container, but clearly it is not either a simple "overwrite", nor is it simply appended to the end, as the setting for relayhost for example appears much earlier in the file.

Regards,
:D

**Comment by dmcgrandle** [comment]
@johansmitsnl - we probably should amend the wording on the wiki, since it is misleading when it says "overwrite".
:D

**Comment by dmcgrandle** [comment]
@johansmitsnl - I went ahead and amended the wiki myself.  :)  I borrowed the wording from our section on "overriding the dovecot configuration" since it looks like we use the same logic for that as well, and the word "override" seems more clear than the word "overwrite" which implied we completely replaced the main.cf file which we clearly don't do.  I also threw in the example from this thread of increasing the message size as a common use case for adding to the main.cf config.

Regards,
:D

**Comment by exhuma** [comment]
You guys are awesome for giving feedback this quickly ;)

However, I now created a `postfix-main.cf`, but don't see the changes in the container. Do I have to delete and re-create the container after modifying the file? I was trying to find this in the docs as well without luck :(

**Comment by dmcgrandle** [comment]
Hi exhuma,

Yes, you have to "docker-compose down" and then "docker-compose up -d mail" again.  Updates are made when the container starts up.

Regards,
:D

**Comment by exhuma** [comment]
Cool thanks.

Given that my original question is answered I'll close the ticket.
