### ISSUE TITLE
Why don't we start the test-docker containers with docker-compose?

### ISSUE THREAD

**Issue by 17Halbe** [tomav/docker-mailserver#827]
Is there a reason for not starting all test containers in the Makefile with a docker-compose file?
I was testing quite a lot lately and this testing thing really needs improvement on the time scale! 

The creation of all the docker container alone takes **5(!) minutes of sleep(!)** time. 

I haven't tried to just delete the sleep time, but I guess it's there for a reason! ;)
So any objections on the docker-compose approach? (We get the dependency of docker-compose, but that is probably installed anyway if one uses this repo?!)

Edit: Just tested it locally on my machine. No problems without those sleep timers... Might be Travis related?!

**Comment by johansmitsnl** [comment]
The sleeps where there before I joined the project. To me they are to give Travis time to boot up all the containters.
You could do a test with the compose file, it is much easier to maintain to. If tests pass I'll merge it.

**Comment by jurekbarth** [comment]
Not sure if this is the right place, but for me the docker daemon is crashing all the time while running these tests. I've tested on different machines and also ported the stuff to docker-compose, not much better results. It's faster, but crashing anyway. How do you get these tests running? I've tested on mac and a linux vm. Also i've already tried different versions of docker.

**Comment by 17Halbe** [comment]
I have no problems so far, but I run those tests on a native ubuntu 17.04 Laptop. 
My specs are: 1.8Ghz i7 8550U 8GB Ram.
No Idea if this helps?! 

I tried with a docker compose file, but got stuck on those link parts.. Basically it took too much time and IMHO isn't really worth the effort..
But what about reducing the amount of containers.. That's probably a way to reduce the minimum requirements quite a bit.. 
Or just start those containers needed for a specific test and thereafter remove it right away? 
We could also implement a list of already passed tests which are going to be skipped in the second run..

Any other suggestions?

**Comment by mwlczk** [comment]
@17Halbe, please see #324 as well for test suite considerations.

**Comment by 17Halbe** [comment]
Great! So you're on it? If you need any help, please call in! ;)

**Comment by mwlczk** [comment]
@17Halbe not really, i started 1-2 weeks ago but have very little spare time.
It's a bit of an odyssey to go through all the >160 tests and sort them for "std."/" reusable" and on the other hand "specific" tests.
