### ISSUE TITLE
[Wiki] Missing port mapping 80:80 for certbot authentication

### ISSUE THREAD

**Issue by aterclara** [tomav/docker-mailserver#833]
https://github.com/tomav/docker-mailserver/wiki/Configure-SSL

I was having an issue with this.
I managed to fix it by adding an additional port mapping 80:80

docker run --rm -ti -v $PWD/log/:/var/log/letsencrypt/ -v $PWD/etc/:/etc/letsencrypt/ -p 443:443 -p 80:80 deliverous/certbot certonly --standalone -d mail.domain.tld

Any thoughts?

**Comment by boaorm** [comment]
Hi,

The letsencrypt certbot tls-sni challenge uses port 443 and is disabled due to a [security issue](https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811). HTTP (port 80) or DNS challenge is the way to go until this is resolved!
