### ISSUE TITLE
Delivery monitoring

### ISSUE THREAD

**Issue by zzvara** [tomav/docker-mailserver#839]
Hi,

Please suggest a tool that would monitor delivery from/to this mail server. Unfortunately many services fail within the container, that builds up a Postfix queue. Currently these problems are identified from the logs. Are there any open-source monitoring tools, that the author or others would recommend? It would be a great addition to this stack.

Cheers,
Zoltán

**Comment by akmet** [comment]
Hey,
you mean something like https://linux.die.net/man/1/pflogsumm ?
I am running this as a cron every night and it sends me an email what happend on my mail server

**Comment by zzvara** [comment]
Seems like a useful tool, I will check it out. Are you using this with `tomav:mailserver`?

**Comment by johansmitsnl** [comment]
@akmet could you suggest a PR for this?

**Comment by akmet** [comment]
I am using it currently on my host but I think it would be much better when it is inside the docker. Over the next week I should have enough time for that! :)

What do you guys would prefer:
An env variable like DAILY_SUMM and then every night a summery is send to postmaster or a SUMM_USER mail account? Using cron with @daily and output yesterdays Summery?

**Comment by akmet** [comment]
@johansmitsnl I could not found any mail client. Wasn't it just not needed in the past or is there an agreement to use other methods? I have not worked this much with mail servers in the past and maybe just dont really understand enough whats going on 😆

**Comment by johansmitsnl** [comment]
You could add to the `apt-install` the package: `bsd-mailx`
Somewhere here:
https://github.com/tomav/docker-mailserver/blob/253c8faef61c3544ddb006c291105b02dd8febc3/Dockerfile#L20-L22

**Comment by akmet** [comment]
@johansmitsnl could you close this?
