### ISSUE TITLE
Unable to connect to AWS ELB

### ISSUE THREAD

**Issue by viveksuhanda** [tomav/docker-mailserver#841]
Hi,

I have created the mail server using AWS cloud. In that I am using two VMs which has the mail server docker image configured on it with LDAP server disabled.  Now the scenario is there is another test VM which runs a python script which request to ELB which in turn communicates to two mail servers.
Below is the image illustrating the scenario:
![smtp](https://user-images.githubusercontent.com/12969978/36197537-05dff634-119a-11e8-822a-515c9bfaa7c3.png)

For testing purpose I have configured only one VM with the mail server with ELB and test VM. In this I have registered the elastic IP with the domain in route 53 by creating A, MX and PTR record. I am using Classic ELB but the server VM is unable to connect to the ELB. 

This is the /etc/log/mail/mail.log file

Feb 14 09:52:39 sendmail postfix/smtpd[27658]: connect from ip-x-x-x-x.ec2.internal[x.x.x.x]
Feb 14 09:52:39 sendmail postfix/smtpd[27658]: lost connection after CONNECT from ip-x-x-x-x.ec2.internal[x.x.x.x]
Feb 14 09:52:39 sendmail postfix/smtpd[27658]: disconnect from ip-x-x-x-x.ec2.internal[x.x.x.x] commands=0/0
Feb 14 09:52:43 sendmail postfix/smtpd[27658]: connect from ip-y-y-y-y.ec2.internal[y.y.y.y]
Feb 14 09:52:43 sendmail postfix/smtpd[27658]: lost connection after CONNECT from ip-y-y-y-y.ec2.internal[y.y.y.y]
Feb 14 09:52:43 sendmail postfix/smtpd[27658]: disconnect from ip-y-y-y-y.ec2.internal[y.y.y.y] commands=0/0

I tried to add Proxy Protocol Header according to this link: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html
From this I was able to get the ELB IP address but nothing helped in the resolution of the issue.

Also, I tried the methods mentioned in this link: https://www.sysarchitects.com/solved-postfix-lost-connection-after-ehlo-rhel7 
But again nothing happened.

I also tried assigning the elastic IP of server to the ELB and implemented a network ELB in this case but facing the same issue.

**Comment by johansmitsnl** [comment]
Make sure you use a clasic loadbalancer in TCP mode.
Also the LB should be sticky (not sure how they call it in TCP mode)
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-listener-config.html#using-elb-tcp-layer4

**Comment by viveksuhanda** [comment]
Sticky session is not available for TCP protocol in AWS Classic ELB

**Comment by johansmitsnl** [comment]
But you are using it in TCP mode?

**Comment by viveksuhanda** [comment]
Yes I am using it in TCP mode
I was able to connect with classic ELB by putting the Public and Private IPs in the main.cf mynetworks part
But I have an issue when I try to implement the same configuration with network ELB, in that I have assigned elastic IP to subnet and when I try to run the python script I get the same error that it get disconnected from the IP and the test VM gives me the error of Relay access denied

**Comment by johansmitsnl** [comment]
@viveksuhanda did you solve it?

**Comment by viveksuhanda** [comment]
@johansmitsnl Actually in the earlier solution by putting private and public IP of classic ELB in mynetworks part of main.cf the issue was classic ELB changes it IPs after several interval of time
Hence, I tried putting the both the subnet's private address in which the VM are located  in mynetworks part of main.cf and I was able to send mail 
This same I have to test it with network load balancer
