### ISSUE TITLE
Make SRS_EXCLUDE_DOMAINS a configurable option

### ISSUE THREAD

**Issue by acch** [tomav/docker-mailserver#842]
I've properly set up SPF and SRS. My mailserver is used to relay messages to different relayhosts (using  `sender_dependent_relayhost_maps`) and postsrsd properly rewrites the envelope sender address to something like "srs0=xxx=yy=example.com=alice@example.net" when doing so.

This works fine for most of the relayhosts, but *some* relayhosts do not accept such rewritten envelope sender addresses. Thus, I need to add the following variable in order to exclude such domains from the SRS rewriting:

```
target/postsrsd/postsrsd:
  ...
  SRS_EXCLUDE_DOMAINS=example.com
  ...
```

It would be great to add an environment variable so that such excluded domains could be controlled from my `docker-compose.yml` right away.

**Comment by johansmitsnl** [comment]
Can you suggest a PR?

**Comment by acch** [comment]
Not yet. I need to get my head around how `start-mailserver.sh` works... Hope to be able to spend some time on this on the weekend.

I wanted to evaluate if this is, in general, something that's useful for others? Does that qualify for a sensible feature?

**Comment by johansmitsnl** [comment]
It does to me.

**Comment by acch** [comment]
Created PR #849 with a potential fix. Let me know if I'm missing something...
