### ISSUE TITLE
Error in default configuration

### ISSUE THREAD

**Issue by Tygore** [tomav/docker-mailserver#844]
Hello,
Standard settings. Changed only in .env:
hostname: mail
domainname: mycooldomain.com

I can not receive and send mail. In the logs of the server writes:
`

- Feb 16 11:03:54 mail postfix/postscreen[12994]: CONNECT from [172.21.0.1]:54410 to [172.21.0.2]:25
- Feb 16 11:03:54 mail postfix/postscreen[12994]: PASS OLD [172.21.0.1]:54410
- Feb 16 11:03:54 mail postfix/smtpd[13007]: error: open database /tmp/docker-mailserver/postfix-send-access.cf: No such file or directory
- Feb 16 11:03:54 mail postfix/smtpd[13007]: error: open database /tmp/docker-mailserver/postfix-receive-access.cf: No such file or directory
- Feb 16 11:03:54 mail postfix/smtpd[13007]: connect from unknown[172.21.0.1]
- Feb 16 11:03:54 mail postfix/smtpd[13007]: Anonymous TLS connection established from unknown[172.21.0.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
- Feb 16 11:03:54 mail postfix/smtpd[13007]: warning: texthash:/tmp/docker-mailserver/postfix-send-access.cf is unavailable. open database /tmp/docker-mailserver/postfix-send-access.cf: No such f
- ile or directory
- Feb 16 11:03:54 mail postfix/smtpd[13007]: warning: texthash:/tmp/docker-mailserver/postfix-send-access.cf: table lookup problem
- Feb 16 11:03:54 mail postfix/smtpd[13007]: NOQUEUE: reject: RCPT from unknown[172.21.0.1]: 451 4.3.5 <xxxx@gmail.com>: Sender address rejected: Server configuration error; from=<xxxx@gmail.com> to=<tygore@mycooldomain.com> proto=ESMTP helo=<mail-lf0-x232.google.com>
- Feb 16 11:03:54 mail postfix/smtpd[13007]: disconnect from unknown[172.21.0.1] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=5/7
- Feb 16 11:06:20 mail postfix/postscreen[13505]: CONNECT from [172.21.0.1]:54416 to [172.21.0.2]:25

`

My DNS: 
mail		300	MX	10	mail.mycooldomain.com
mail			A	xx.162.187.xx

What could be the problem?

**Comment by mmarchand** [comment]
had the same since last night, you need to create 2 empty files in your config/ directory :  
postfix-send-access.cf
postfix-receive-access.cf
this will make it work
it probably needs a real fix though

**Comment by Tygore** [comment]
@mmarchand 4 hours googling, and you fixed the problem for 2 lines :)
I'll continue to test further, but it seems like the letters are sent now and come :)

**Comment by 17Halbe** [comment]
Thanks for reporting. I introduced that problem. PR is testing right now.

**Comment by Starbix** [comment]
@mmarchand Thank you 😄

**Comment by dmcgrandle** [comment]
Ran into the same issue last night when watchtower upgraded to the latest build.  @mmarchand thank you.
:D

**Comment by johansmitsnl** [comment]
Should be fixed in: #846
