### ISSUE TITLE
Option to select recipient_delimiter in dovecot and postfix 

### ISSUE THREAD

**Issue by pn2** [tomav/docker-mailserver#850]
This is a wish for feature extention.

I think that it would be great if one could change the recipient delimiter used for subaddressing and sorting to IMAP folders using sieve. Default delimiter is '+', but many web forms unfortunately do not allow for '+' in email addresses although it is a perfectly legal character. Changing it to '-', '_', or '.' often solves the problem.

The files requiring changes would be, for dovecot:

```
/etc/dovecot/conf.d/90-sieve.conf:83:#recipient_delimiter = +
/etc/dovecot/conf.d/15-lda.conf:32:#recipient_delimiter = +
```

...and for postfix:

```
/etc/postfix/main.cf:16:recipient_delimiter = +
```

I guess the implementation could be done with additional 'sed' commands in the setup functions.

**Comment by johansmitsnl** [comment]
Checkout: https://github.com/tomav/docker-mailserver/wiki/Configure-Aliases#address-tags-as-an-alternative
