### ISSUE TITLE
Wrong domain name in postsrsd config

### ISSUE THREAD

**Issue by mherfurt** [tomav/docker-mailserver#852]
Hi,
thanks for your excellent work with docker-mailserver!
Quite recently, some changes were introduced, that broke my setup. It took me some time to figure out, why some mailservers were rejecting my mails with the errorcode 554 "Sender address rejected: Domain not found (in reply to RCPT TO command)". The reason for this is, that the file /etc/defaults/postsrsd contains the local domain of my bare-metal CoreOS cluster, which is not resolvable outside my network.
From what I learned so far, the domain-name is derived from the hostname, which is not using the correct domain. 

Since I am using the OVERRIDE_HOSTNAME environment variable, it would be great, if the postsrsd configuration would also use the name set in this variable.

Thank you,
Martin

**Comment by johansmitsnl** [comment]
@17Halbe could you check this?

**Comment by 17Halbe** [comment]
First of all try if this would help: https://github.com/tomav/docker-mailserver/issues/844#issuecomment-366208862
It might be easier than you think. ;) If that's the case, a update is on the way.
If it's actually the sender rewriting scheme daemon, I would need some more information, since to my knowledge there hasn't been a change to the OVERRIDE_HOSTNAME implementation recently nor to postsrsd. 
Could you provide a log output after a failed send attempt?

**Comment by mherfurt** [comment]
I added the files postfix-send-access.cf and postfix-receive-access.cf yesterday... after seeing the deamon complain about their absence in the logs. IMHO the described postsrsd issue is not related.

When postsrsd is running (in my case with the option '-d coreos.local', the receiving mailserver bounces back mails due to the header generated by postsrsd. The bounce reads as follows:
```
This is the mail system at host mail.mydomain.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<account@receiver.com>: host mx.receiver.com[1.2.3.4] said: 554 5.1.8
    <srs0=llwm=fi=mydomain.com=myaccount@coreos.local>: Sender address
    rejected: Domain not found (in reply to RCPT TO command)
```
After manually editing /etc/defaul/postsrsd in order to replace `SRS_DOMAIN=coreos.local` with `SRS_DOMAIN=mydomain.com` and restarting the postsrsd process, the issue with sending to account@receiver.com disappears.

I am sorry for not including a log. Not every receiving mailserver reacts to this misconfiguration in this way - which makes it even harder to spot.

**Comment by 17Halbe** [comment]
I‘m still curious why it worked before?! Any idea? 
Would you like to provide a pull request?

**Comment by mherfurt** [comment]
I am still curious as well. Since I am not pulling every single image, the issue was maybe introduced a longer time ago. Or maybe the issue existed already in earlier versions of my mailserver and I just did not notice the problems.
I am sorry for not being able to provide a pull request for this.

**Comment by 17Halbe** [comment]
No problem. I'll see if I can trace down, why and what has changed tomorrow..

**Comment by 17Halbe** [comment]
Ok, took me some time..
Can you have a look at  #849 and if this would fix your issue as well?
(It didn't for me)
Otherwise the "bug" got introduced here: #814
Quick workaround would be to delete those lines in the `/etc/postfix/main.cf`:
```
sender_canonical_maps = tcp:localhost:10001
sender_canonical_classes = envelope_sender
recipient_canonical_maps = tcp:localhost:10002
recipient_canonical_classes = envelope_recipient,header_recipient
```
(Command would be something like this: `docker exec mail sed -i /sender_canonical_/# sender_canonical_/g` and `docker exec mail sed -i /recipient_canonical_/# recipient_canonical_/g` and thereafter reload postfix: `docker exec mail service postfix reload`)

This is a bug and has to be fixed

**Comment by alexanderkjeldaas** [comment]
I'll just chime in and say that with a dog standard docker setup, I also had to remove those 4 lines to make it work.

They also removed this stream of warnings:
```
Mar  3 20:30:41 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
Mar  3 20:30:42 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
Mar  3 20:30:43 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
Mar  3 20:30:44 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
Mar  3 20:30:45 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
Mar  3 20:30:46 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
Mar  3 20:30:47 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
Mar  3 20:30:48 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
Mar  3 20:30:49 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
Mar  3 20:30:50 e174f068ae91 postfix/cleanup[10909]: warning: connect to TCP map localhost:10001: Cannot assign requested address
```

**Comment by 17Halbe** [comment]
Thanks for reporting!
