### ISSUE TITLE
iOS 9 devices cannot send mails using SMTP

### ISSUE THREAD

**Issue by kortenkamp** [tomav/docker-mailserver#856]
The new cipher list introduced in #784 makes it impossible for iOS 9 based devices to send mail via SMTP. This is particularly bad for devices that cannot be upgraded to newer iOS versions.

Actually I found in the commit messages of #784 a note that the new cipher list should be checked. 

This issue comes with a fix (sorry for not committing the patch as well). Just add the cipher `ECDHE-RSA-AES256-SHA` to the list of ciphers in main.cf:
```
tls_high_cipherlist=ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-CCM8:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:ECDHE-RSA-AES256-SHA
```

This will enable mail sending for old iPads and iPhones again.

**Comment by mwlczk** [comment]
could you please use postfix-main.cf to overwrite this one setting? 
I am going to implement a setting/switch for this TLS settings, but didn't have time so far to finish it.

**Comment by mwlczk** [comment]
@kortenkamp PR #831 is supposed to fix your problem. still needs to be merged/fixed though.

**Comment by johansmitsnl** [comment]
The PR is merged now. You can lower the the TLS level: https://github.com/tomav/docker-mailserver#tls_level
