### ISSUE TITLE
DKIM with LDAP accounts

### ISSUE THREAD

**Issue by dolanor** [tomav/docker-mailserver#858]
Hi, I followed the tutorial in the wiki and it didn't generate anything from my current configuration using LDAP.
Digging deeper, I checked the script and saw it didn't check for LDAP accounts.
I will try to add this and make a PR if you can confirm my initial intuition.

Side question, does the regexp mail alias work with LDAP too? Is it possible to make it work?

**Comment by johansmitsnl** [comment]
Mail alias should work.
The generator also takes a domain argument.
https://github.com/tomav/docker-mailserver/blob/c36e878d76827fc7062558f1edada05d7ba38880/target/bin/generate-dkim-domain#L6

But auto detection of the ldap would be nice.

**Comment by dolanor** [comment]
Oh! Fine!
I'm gonna use the domain script directly. Thanks!
