### ISSUE TITLE
Docker images are not building

### ISSUE THREAD

**Issue by 17Halbe** [tomav/docker-mailserver#859]
Docker image hasn't been build since [2018-02-15T23:06:01.690Z](https://hub.docker.com/r/tvial/docker-mailserver/builds/). 
Anything I could help with?

**Comment by johansmitsnl** [comment]
I asked @tomav to check this, I don't have access to the docker managment of this project.

**Comment by 17Halbe** [comment]
Thanks, let's hope for the best then! :)

**Comment by johansmitsnl** [comment]
There where errors but it is build now.

**Comment by 17Halbe** [comment]
Ok, well I got it with the latest Docker build from yesterday.. ¯\_(ツ)_/¯ 

...von unnerwegs...
