### ISSUE TITLE
Not being considered spam by outlook.com/hotmail.com

### ISSUE THREAD

**Issue by dolanor** [tomav/docker-mailserver#861]
Hi,

Thanks to this image, I'm finally not considered as spam by gmail thanks to SPF (which was the big blocker).
And I hoped by configuring the DKIM, I would be good with outlook.com .
Since a lot of my client love to use those exchange servers and now with office365, everything is on it, it's really bad for business to be considered as spam. Especially when my clients get me out of the spam folder, and no matter what, I still go back to it (without fishy links or images, etc)

Have someone in this community achieved that?

**Comment by dolanor** [comment]
Well I did, I have SPF, DKIM and DMARC set and verified, and still, I arrive in spam for office365/hotmail/livemail users.
So I don't know what's wrong, what's left to configure.

**Comment by mwlczk** [comment]
Microsoft Servers are very strict about allowed servers. It looks more like they are working with a white list instead of blacklist. 
I had to validate my server with ms-servers. Follow the instructions from the bounced e-mail.

**Comment by johansmitsnl** [comment]
@mwlczk said is true. I personally use this site http://www.appmaildev.com/en/dkim to test the setup. If all ok your setup is good.

**Comment by 42wim** [comment]
@mwlczk what validation did you have to do ? My mails don't get bounced, they just get accepted but appear in the spam filter of the users. (SPF, DKIM and DMARC enabled)

It seems like the only way to get sorta on the whitelist is to pay for it:
https://returnpath.com/solutions/email-deliverability-optimization/ip-certification/

http://mail.live.com/mail/troubleshooting.aspx for more info

**Comment by mwlczk** [comment]
Hi @42wim and @dolanor, my mails have been bounced with this message:
> <info@example.com>: host
    example.mail.protection.outlook.com[SOM.EIP.STR.ING] said: 550
    5.7.606 Access denied, banned sending IP [MY.SER.VER.IP]. To request
    removal from this list please visit https://sender.office.com/ and follow
    the directions. For more information please go to
    http://go.microsoft.com/fwlink/?LinkID=526655 (AS16012609) (in reply to
    RCPT TO command)
Hope this solves some of your problems.
To figure out if my server is configured correctly I used this service, it was really helpful:
https://www.mail-tester.com/

**Comment by dolanor** [comment]
Ok, I tried your email tester @johansmitsnl , I'm actually listed on spamrats because my whole IP range is blacklisted… Yeah. I will try to get it delisted, but it seems it will require some work.

Thank you!

The whole rest is good.

**Comment by dolanor** [comment]
Just an update.

Instead of getting delisted, I was wondering if I could use one of my Failover IP address that could be clean. I had one that wasn't listed, so I used it.
Problem was, that the mail was still sent through the same main IP address. I had to add some iptables rules to make it work. Following moby/moby#30053 I found [tozd/docker-external-ip](https://github.com/tozd/docker-external-ip) which works for this use case.
But now I'm getting bounced instead of getting into the junk :( .
So now, I'm gonna use @mwlczk input with the https://sender.office.com service and see how it goes.

And I guess I will still try to delist my original IP address from spamrats.

**Comment by andihit** [comment]
> But now I'm getting bounced instead of getting into the junk :( .

The blacklisted IP gets your mails into the spam folder, and the clean IP gets your mails bounced?

My IP isn't on any blacklist, and mail-tester.com and appmaildev.com/en/dkim didn't show any problems, but still my mail also gets into the junk folder. I asked the Outlook.com Deliverability Support Team, but they told me everything is fine with the IP and the mail is flagged as spam due to their proprietary SmartScreen® Filter (a mail with identical content from gmail gets through).

So, is anybody able to deliver mails to @outlook.com inboxes without paid certification?

**Comment by johansmitsnl** [comment]
@andihit outook.com/hotmail.com etc.. flags my calendar invites as spam but emails not. They are very picky but why is always the question.

**Comment by andihit** [comment]
@johansmitsnl: from the first mail on, or did you have to train microsofts junk filter by marking lots of messages as non-junk?

The only "unusual" config I have is that my mailservers hostname (and rDNS entry) is different from the `From:` header. But all domains have the correct DNS entries (checked with mail-tester.com and appmaildev.com/en/dkim), so theoretically this shouldn't be an issue. When I disable SRS the `smtp.mailfrom` also matches the `header.from`, but still no success.

**Comment by johansmitsnl** [comment]
I never got hold of why it is not working. If someone can tell me please do, spend already to much time on them (Microsoft).

**Comment by kstaikov** [comment]
Why was this issue closed? FWIW my emails to my office 365 work email silently go to Quarantine. When I inspect the headers from microsoft, no matter what they have a Spam Confidence Level of 5, which is automatically flagging the email as spam. SPF, DKIM, DMARC are all set up, not on any spam or block lists, etc. It's just for personal mail, not doing marketing or anything of the sort. So paying for 3rd party whitelist is not realistic.

**Comment by johansmitsnl** [comment]
@kstaikov could you debug this and check why emails end up in Quarantine?
My guess it is not related to this project, but if you can make a PR with the change that allows email to pass O365 please do so.

**Comment by frantiseksimorda** [comment]
Hi, same here and now 3-4 years later. DKIM, DMARC and SPF all setup correctly. Is there really no way to send emails to Micro$oft services?

**Comment by ontheair81** [comment]
Had the same problem and solved it. You can have a look [here](https://github.com/docker-mailserver/docker-mailserver/discussions/2433).
