### ISSUE TITLE
Following Let's encrypt need clarification on mount step

### ISSUE THREAD

**Issue by pepmadon** [tomav/docker-mailserver#865]
Let's encrypt (recommended)

To enable Let's Encrypt on your mail server, you have to:

    get your certificate using letsencrypt client
    add an environment variable SSL_TYPE with value letsencrypt (see docker-compose.yml.dist)
    mount your whole letsencrypt folder to /etc/letsencrypt
    the certs folder name located in letsencrypt/live/ must be the fqdn of your container responding to the hostname command. The full qualified domain name (fqdn) inside the docker container is build combining the hostname and domainname values of the docker-compose file, e. g.: hostname: mail; domainname: myserver.tld; fqdn: mail.myserver.tld

You don't have anything else to do. Enjoy.

get your certificate using letsencrypt client 

Step

1) sudo certbot --apache certonly
2) mail.nameofdomain.com
3) On host cert is created 
     /etc/letsencrypt/mail.nameofdomain.com

4) docker-compose.yml environment I added 
    SSL_TYPE=letsencrypt

The problem I am having is with the step mount??

"mount your whole letsencrypt folder to /etc/letsencrypt"

???

**Comment by boaorm** [comment]
Hi,

In docker-compose.yml:
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/

Hope this works for you :)

**Comment by pepmadon** [comment]
I had that without the   :ro I assume its READ ONLY.
It worked Thanks so much!
