### ISSUE TITLE
ufw does not work as expected

### ISSUE THREAD

**Issue by boaorm** [tomav/docker-mailserver#867]
Hi,

I noticed that the mailserver ports were opened although they had been closed by ufw:

[https://askubuntu.com/questions/652556/uncomplicated-firewall-ufw-is-not-blocking-anything-when-using-docker](https://askubuntu.com/questions/652556/uncomplicated-firewall-ufw-is-not-blocking-anything-when-using-docker)

Possible quick fix: Can we bind to localhost 127.0.0.1 instead of all interfaces 0.0.0.0?

**Comment by johansmitsnl** [comment]
Don't expose the ports isn't an option?

**Comment by boaorm** [comment]
I guess it depends on the hosting provider. If this isn't easy to fix I'd label this as low priority.

In my case the hosting provider has an external firewall but all internal customers can still access one another. So ufw would be a nice extra security feature, eg. limiting imap access to specific IPs.

According to the link: the ports are opened directly in iptables and therefore ufw is bypassed.

**Comment by johansmitsnl** [comment]
This is not related to the project but with docker itself.
Read https://docs.docker.com/network/iptables/#restrict-connections-to-the-docker-daemon and especially 
**Prevent Docker from manipulating iptables**

You can always decide to not map all ports public
https://github.com/tomav/docker-mailserver/blob/2687469f38715c34a8a006bc90a40d3b2c18fe3e/docker-compose.yml.dist#L8-L12

**Comment by boaorm** [comment]
Alright thanks!

So basically binding to localhost/127.0.0.1 would actually not be a fix since mailserver wouldn't be reachable from the internet.

```
Prevent Docker from manipulating iptables

To prevent Docker from manipulating the iptables policies at all, set the iptables key to false in /etc/docker/daemon.json. This is inappropriate for most users, because the iptables policies then need to be managed by hand.
```

The docker networking infrastructure would probably need more than a few simple ufw lines. I'm gonna leave this be :)

**Comment by johansmitsnl** [comment]
Please check #628 and join in when your changing your ufw. Maybe you solved this already?
