### ISSUE TITLE
multiple domains under same mailserver

### ISSUE THREAD

**Issue by pepmadon** [tomav/docker-mailserver#869]
I am able to run the docker mailserver with one domain, certs and DKIM.
After seeing this closed issue https://github.com/tomav/docker-mailserver/issues/820 I am still unsure how to configure the docker mail-server with two domains
Using DigitalOcean I have one droplet with two domains and two separate DNS panels so I am able to 
configure separate records for each domain. 
-------------------------------------------------------------
domain
gyyyy.com
MX | gyyyy.com |    mail.gyyyy.com.   
MX | mail.gyyyy.com.gyyyy.com  |  138.xxx.xx.01 
A  | gyyyy.com   | 138.xxx.xx.01
etc...
---------------------------------------------------------------
domain
gzzzz.com
MX | gzzzz.com |    mail.gzzzz.com.   
MX | mail.gzzzz.com.gzzzz.com  |  138.xxx.xx.01 
A  | gzzzz.com   | 138.xxx.xx.01
etc...
----------------------------------------------------------------

The docker mailserver container runs fqdn mail.gyyyy.com

How should I set MX records so the two domains are able to access the mailserver mail.gyyyy.com?

**Comment by johansmitsnl** [comment]
Both MX records and spf txt records should be the same as the primary domain of the server.

DKIM needs to be uniq for each domain.

**Comment by pepmadon** [comment]
Thanks seems to work now!
 
spf txt record to both domains: 
Added the following to domain 1
TXT | @ | "v=spf1 a include:_spf.gyyyy.com ~all"

And domain 2 now looks like this now,  note( dropped MX | mail.gzzzz.com.gzzzz.com | 138.xxx.xx.01)
gzzzz.com
TXT | @ | "v=spf1 a include:_spf.gyyyy.com ~all"
MX | gzzzz.com | mail.gyyy.com.
A | gzzzz.com | 138.xxx.xx.01
etc...
