### ISSUE TITLE
Sieve filters

### ISSUE THREAD

**Issue by echo511** [tomav/docker-mailserver#87]
Is it a desired to-do? Or is it off-topic for this project?

**Comment by tomav** [comment]
Hi @echo511, what do you mean?
I'm not an expert but we already have amavis and spamassassin.
Let me know.

**Comment by echo511** [comment]
Well, that's for eliminating the unwanted. Sieve is for mail ordering based on user specific rules. For example move mail marked as spam by spamassassin to Junk folder etc.

Look here: http://wiki2.dovecot.org/Pigeonhole/Sieve/Examples

**Comment by echo511** [comment]
Ok, it may not be possible to set up Courier-Sieve, no support from Courier. Maby move to Dovecot instead? I'll look into it. Let me know if Sieve-Dovecot sounds good to you. If so I'll send a pull.

**Comment by tomav** [comment]
If we can keep the root concept of using only versionable configuration( no *sql database), why not.
I'm just wondering if dovecot allows to do that.

**Comment by echo511** [comment]
By default it uses system accounts but can be configured to use userfile or sql or whatever. So no problem

**Comment by 00angus** [comment]
Dear all, still a work in progress but we have dovecot in v2 :)
We can now add sieve. Someone interested?

**Comment by stonemaster** [comment]
I've always configured my dovecot server to enable Sieve by uncommenting the file following line in `/etc/dovecot/90-sieve.conf`:

`
sieve = file:~/sieve;active=~/.dovecot.sieve
`

That will look for a `~/.dovecot.sieve` in the user's home directory and enable appropriate sieve rules. 

Is there anything more comfortable or elegant needed? For me something like this would be enough given it is possible to configure the **dovecot.sieve** file to the `/var/mail/%d/%u` directory structure.

**Comment by tomav** [comment]
If you want to PR something, feel free to do it :-) Just add necessary tests.

**Comment by tomav** [comment]
Do it on v2 of course.

**Comment by stonemaster** [comment]
Okay I'll have a look :-) And yes v2 of course.
