### ISSUE TITLE
This Docker container doesn't works for me...

### ISSUE THREAD

**Issue by pirmax** [tomav/docker-mailserver#873]
I have a fresh installation of Debian 9 and I have installed this docker container.

> docker pull tvial/docker-mailserver:latest
> 
> curl -o setup.sh https://raw.githubusercontent.com/tomav/docker-mailserver/master/setup.sh; chmod a+x ./setup.sh
> 
> curl -o docker-compose.yml https://raw.githubusercontent.com/tomav/docker-mailserver/master/docker-compose.yml.dist
> 
> curl -o .env https://raw.githubusercontent.com/tomav/docker-mailserver/master/.env.dist
> 
> ./setup.sh email add <email> [<password>]
> 
> ./setup.sh config dkim
> 
> docker-compose up -d mail

But, when I access to my domain, the page doesn't start : **ERR_CONNECTION_REFUSED**

Could you help me please?

**Comment by 17Halbe** [comment]
You are trying to access the domain how? With a Webbrowser? Thunderbird? Telnet? What program is issuing the error message? What is the output of `docker-compose up`? What port are you connecting to?

**Comment by pirmax** [comment]
They is my logs of container: https://pastebin.com/raw/MxVsNURs

I try to access to mail.domain.tld. But I get this Google Chrome error: **ERR_CONNECTION_REFUSED**

**Comment by 17Halbe** [comment]
Thanks.
This is a mail server. It doesn't have a web interface. You can connect to it via a client (Thunderbird, Smartphone mail app, etc) 
See [FAQ](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-configure-my-email-client)

Additionally did you edit the .env file to your needs?

**Comment by pirmax** [comment]
Oh okay, I think is webmail interface... I not know read :)

**Comment by 17Halbe** [comment]
So this can be closed, right?

**Comment by tomav** [comment]
Hi @pirmax, just saw your tweet. Github is obviously the best place to get support.
@17Halbe is right, this is a mailserver, not a webmail (which can be plugged on top of this project).
