### ISSUE TITLE
Traefik certificate support?

### ISSUE THREAD

**Issue by mathuin** [tomav/docker-mailserver#877]
https://docs.traefik.io/configuration/acme/#storage

Traefik stores its certs in a JSON file.  Is there any interest in supporting these certs?  Previously my cert generation tool wrote to files so I could use manual, this is ... different. :-)

**Comment by mathuin** [comment]
https://github.com/containous/traefik/blob/master/contrib/scripts/dumpcerts.sh

This script provides the logic necessary to extract certificates and private keys.  It looks like "a simple matter of `jq`" -- if the domain is known (which it should be) the individual cert/key combination can be extracted into memory as if it were being read from a file.

**Comment by r3pek** [comment]
Interest, yes :) I'd rather have traefik manage all my certificates (including the mailserver one), then to have just one container to do the mail server one ;)

**Comment by mathuin** [comment]
Right now, my workaround is to run an instance of `nginxdemos/hello` on https at my mail hostname, then I run a modified version of `dumpcerts.sh` to extract the certificate and key which I then copy into the location that this software expects, then I restart the mail server.

Suggested rough user documentation to use the change:
* Set up HTTPS web host for the mail domain to cause Traefik to generate a certificate
* Set `SSL_TYPE` to `traefik`
* Mount Traefik ACME volume to `/opt/traefik/acme/`

What the code should do:
* Monitor `/opt/traefik/acme/acme.json` for changes.
* When changes detected, extract the cert and key for the mail domain.
* If this cert and key is different than the current key, copy it into place "somewhere", then restart Postfix.

It would be good to decide on a value of "somewhere" (`/opt/traefik/acme/certs/mail.domain.org.crt` and `/opt/traefik/acme/private/mail.domain.org.key` are reasonable based on `dumpcerts.sh`), and also to confirm whether any other services use SSL and may need restarting.

I'm not sure how to write good tests for this feature, nor have I yet looked into how to restart Postfix from within the container, but the rest looks pretty reasonable.

I considered an alternative solution which would have involved setting `SSL_TYPE` to `manual` and a separate container which would run every so often via cron to perform the above tasks.  The real issue here is restarting the container from outside, something which I'm not sure how to automate properly.

Is there anything missing from the change description?

**Comment by r3pek** [comment]
You're implying that traefik and mailserver run on the same node right? ;)

**Comment by pn2** [comment]
This should solve the issue: https://github.com/tomav/docker-mailserver/pull/976

You just need, in addition, to detect changes in the acme.json file updated by traefik and extract the .pem files so that the change is "seen" by docker-mailserver.

**Comment by Its-Alex** [comment]
Up ?

**Comment by erik-wramner** [comment]
See #728 and https://github.com/tomav/docker-mailserver/wiki/Configure-SSL.
