### ISSUE TITLE
Correct way of removing unused accounts

### ISSUE THREAD

**Issue by vedtam** [tomav/docker-mailserver#878]
Hi,

Thanks for this wonderful docker image.

I would like to remove some of the unused accounts and wondering if all I have to do is to remove the account from the `postfix-accounts.cf` and log into the container to delete its folder from `/var/mail/myaccount.com` as well?

Or is there maybe another way?
Thanks.

**Comment by 17Halbe** [comment]
If you got aliases set up you could also delete those in the respective file. Except that, your actions would be enough, yes.
You could also use the [setup script](https://github.com/tomav/docker-mailserver/wiki/Setup-docker-mailserver-using-the-script-setup.sh) but as I just realized this wouldn't delete the maildir itself nor the aliases but only remove the user.
Probable Enhancement?! Would you like to contribute?

**Comment by vedtam** [comment]
Hi @17Halbe,

Thanks for the suggestion. My bash knowledge is rather scarce, but I would like to help and contribute if I can.

**Comment by 17Halbe** [comment]
No problem, thanks for the idea! :+1:
