### ISSUE TITLE
open relay

### ISSUE THREAD

**Issue by NikolaMandic** [tomav/docker-mailserver#88]
this things starts an open relay by default right?

**Comment by tomav** [comment]
Nope, you need an account to use it as smtp.

**Comment by NikolaMandic** [comment]
but if I run it does it accept all from local networks. I had it tested for open relay here http://www.mailradar.com/openrelay/ and it showed some tests failing
also my provider gave me a notice I must have done something wrong.
Can you please tell me can you think of a setup this might be an open relay by default?

**Comment by tomav** [comment]
Checking my server with your URL... I'll let you know.

**Comment by tomav** [comment]
All tested completed! No relays accepted by remote host!

Could you tell me which test said your server is an open relay?

**Comment by NikolaMandic** [comment]
hm not sure. now it is working for me. Thanks for the project it is great. 
Also I ran it without NETCAP maybe that did something

**Comment by tomav** [comment]
Happy to hear you like it.
Regarding `NETCAP`, it works without, but `fail2ban` won't be able to ban IPs.
