### ISSUE TITLE
FEATURE REQUEST: Adding /var/lib/dovecot to mailstate

### ISSUE THREAD

**Issue by baxerus** [tomav/docker-mailserver#887]
The folder /var/lib/dovecot should be added to the mailstate, so that ssl-parameters.dat doesn't have to be recreated everytime the service is recreated by docker-compose.

The folder has only to be added target/start-mailserver.sh

Best regards

Benedict

**Comment by johansmitsnl** [comment]
Could you add a PR?

**Comment by baxerus** [comment]
Have done so 😉 
A one liner
