### ISSUE TITLE
mail server users + google apps users

### ISSUE THREAD

**Issue by xXcoronaXx** [tomav/docker-mailserver#888]
Hi, i'm trying yo setup a second mail server to create not importants mail account for free.

With my actual configuration i can send email from mailserver to @gmail but not to my own domain. I mean to my google app users. Google apps users can send emails to mailserver users but they can`t respond.

This is the error:

This is the mail system at host mail.XXXX.es.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

The mail system

<antonio@XXXX.es>: host mail.XXXX.es[/var/run/dovecot/lmtp] said: 550
   5.1.1 <antonio@XXXX.es> User doesn't exist: antonio@XXXX.es (in
   reply to RCPT TO command)
Reporting-MTA: dns; mail.XXXX.es
X-Postfix-Queue-ID: 45A64FE6
X-Postfix-Sender: rfc822; test@XXXX.es
Arrival-Date: Thu,  8 Mar 2018 17:46:27 +0000 (UTC)

Final-Recipient: rfc822; antonio@XXXX.es
Original-Recipient: rfc822;antonio@XXXX.es
Action: failed
Status: 5.1.1
Remote-MTA: dns; mail.XXXX.es
Diagnostic-Code: smtp; 550 5.1.1 <antonio@XXXX.es> User doesn't exist:
   antonio@XXXX.es

De: test <test@XXXX.es>
Asunto: sfsa
Fecha: 8 de marzo de 2018, 18:46:26 CET
Para: Antonio Acevedo <antonio@XXXX.es>

adfasdf
so... some help?

**Comment by xXcoronaXx** [comment]
if i set this POSTFIX_DAGENT=lmtps:inet:smtp-relay.gmail.com:25

i got warning: connect to transport private/lmtps: No such file or directory and dsn=4.3.0, status=deferred (mail transport unavailable)

**Comment by johansmitsnl** [comment]
You can use this variable for a email relay with authentication: https://github.com/tomav/docker-mailserver/wiki/Configure-AWS-SES

**Comment by xXcoronaXx** [comment]
Do you mean ? something like this?
    - AWS_SES_HOST=smtp-relay.gmail.com
    - AWS_SES_USERPASS=user@XXXX.es:gmailpassword

That is for Amazon i want to send my emails through google.

**Comment by johansmitsnl** [comment]
yes like that. The variable has the amazon name but can be used for any relay host.

**Comment by xXcoronaXx** [comment]
Thanks that works, but i still getting the error " User doesn't exist:" when i try to send email from mailserver user to a GoogleApps user. :/

**Comment by johansmitsnl** [comment]
Looks like wrong credentials or the from email does not match.
When you use the same smtp credentials in your email client they work?

**Comment by xXcoronaXx** [comment]
The credential works in Gmail. I think maybe there are a missing configuration in the Google Apps panel.

it only fails when i send an email from an user from the email server to a Google apps user from the same domain.

**Comment by xXcoronaXx** [comment]
i'm still with the same problem. There is a way to relay ALL the email to the relay server?

**Comment by johansmitsnl** [comment]
A new PR entered this week. See the wiki: https://github.com/tomav/docker-mailserver/wiki/Configure-Relay-Hosts

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
