### ISSUE TITLE
Configuring email works on a machine, not on the other

### ISSUE THREAD

**Issue by nicklayb** [tomav/docker-mailserver#889]
I know it maybe not related to the container but it's weird.

I've configured an email address on a machine using Thunderbird and it works perfectly and instantly as expected.

I tried the same configuration, on another machine, same Thunderbird version and now it hangs and it ends by an error that thunderbird could not find parameters for server.

In the container's log I have the following error :
```
warning: TLS library problem: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:974
```

It works on four machine, only one causes error.

Any advice or idea?

Thank you!

**Comment by johansmitsnl** [comment]
Incorrect ssl certificate with the hostname?

**Comment by nicklayb** [comment]
I’m not sure why it would matter only on one system, my Airmail macbook, airmail mac mini, two windows terminal server would work on thunderbird but not one physical host... that’s where I’m lost

**Comment by johansmitsnl** [comment]
You could check the https://github.com/tomav/docker-mailserver#tls_level if your client supports the latest versions.

**Comment by nicklayb** [comment]
It works! 
I add the environment `- TSL_LEVEL=${TLS_LEVER}` to `docker-compose.yml` and added `TLS_LEVEL=intermediate` to the `.env` file

Everything is alright! Thank you!
