### ISSUE TITLE
Custom non-letsencrypt certificate

### ISSUE THREAD

**Issue by emazzotta** [tomav/docker-mailserver#89]
I'd like to have an easy way to use my own certificate (that already contains the key and is the only file needed) which is signed by a real CA and is a non-letsencrypt certificate.

**Comment by emazzotta** [comment]
Untested, but this should do the trick:
https://github.com/tomav/docker-mailserver/pull/90

**Comment by tomav** [comment]
Hi @emazzotta, I'll merge as soon you can confirme it works as expected.
Also, if there are integration can may check everything is working correctly, please add them.
We have currently 45+ tests.

Thank you.

**Comment by emazzotta** [comment]
I was able to verify, that the code within my if-statement works as expected. 

However, I'm having issues exercising the flow that uses the DMS_SSL variable. This issue persists for "cutom" as well as for your "self-signed" option. Meaning, inside the container I can verify that the DMS_SSL variable is set correctly, but the operations are not executed (I don't even see `echo "Adding $(hostname) SSL certificate"` in the logs).

Any ideas what the issue could be?

**Comment by tomav** [comment]
echo "Adding $(hostname) SSL certificate"

This part is inside a if statement, so you probably don't match your requirements.
Try to put another `echo` just after line 142

**Comment by emazzotta** [comment]
Yes, I figured the same :) 

I do see echo's before and after the switch cases for DMS_SSL so I probably really don't match the if-statement. However when I open bash inside the docker container and run:

`[ -e "/tmp/postfix/ssl/$(hostname)-full.pem" ]; echo $?`

I get `0`

Any advice?

**Comment by tomav** [comment]
I suppose you got `0` because `/tmp/postfix/ssl/FQDN-full.pem` exists :-)
I don't have it and it returns `1`.
Tried on an existing file I get `0`.

	root@mail:/# ls -la /tmp/postfix/ssl/
	total 36
	drwxr-xr-x 3 1000 1000 4096 Nov  9 14:08 .
	drwxr-xr-x 3 1000 1000 4096 Feb 27 16:24 ..
	drwxr-xr-x 4 1000 1000 4096 Nov  9 14:08 demoCA
	-rw-r--r-- 1 1000 1000 4562 Nov  9 14:08 FQDN-cert.pem
	-rw-r--r-- 1 1000 1000 6266 Nov  9 14:08 FQDN-combined.pem
	-rw-r--r-- 1 1000 1000 1704 Nov  9 14:08 FQDN-key.pem
	-rw-r--r-- 1 1000 1000 1009 Nov  9 14:08 FQDN-req.pem

	root@mail:/# [ -e "/tmp/postfix/ssl/$(hostname)-full.pem" ]; echo $?
	1

	root@mail:/# [ -e "/tmp/postfix/ssl/$(hostname)-req.pem" ]; echo $?
	0

**Comment by emazzotta** [comment]
That's exactly my point! :)

I have the file: `/tmp/postfix/ssl/$(hostname)-full.pem` 
Therefore the if-statement `if [ -e "/tmp/postfix/ssl/$(hostname)-full.pem" ]; then` 
Should be true and I should have `Adding $(hostname) SSL certificate` in the logs.

See: https://github.com/emazzotta/docker-mailserver/commit/6bd5c5015af895f98ef38c50778b0519074dd9d4

This is not happening though.

**Comment by tomav** [comment]
Could you paste here all the things you see between your docker start command and the last line of log (start it in foreground). Thank you.

**Comment by emazzotta** [comment]
Nevermind, my mistake, I thought if I built my fork of your repo with my change on dockerhub, I'd have my change integrated, but for some reason, dockerhub built your repo instead of my own (with my dockerhub account). If you accept the pull request it should be all good :)

**Comment by tomav** [comment]
Good new!
Bt why can't you test before I merge on master. Not really safe, no? ;-)

You can add your fork on your docker hub account or just test locally with an email client.
Think about integration tests.

Thanks.

**Comment by emazzotta** [comment]
Yes, you're obviously right, something weird happened, I opened a pull request, but the code change was not reflected in my fork. My bad. That's why my docker build didn't contain the change and I had issues testing it. Will test as soon as docker finished building.

**Comment by tomav** [comment]
Thanks @emazzotta

**Comment by emazzotta** [comment]
Tested and works flawlessly!

**Comment by tomav** [comment]
Merged.

**Comment by tomav** [comment]
Thank you @emazzotta.
If you find a way to ass integration test or this part of the code, feel free to PR.
