### ISSUE TITLE
Align Docker HUB image with stable branch?

### ISSUE THREAD

**Issue by Fmstrat** [tomav/docker-mailserver#895]
This isn't an actual issue, but I noticed that https://hub.docker.com/r/tvial/docker-mailserver/builds/ seems to be updating with every commit that is run on the master branch.

Is this your actual intent? A single failed commit could cause issues for anyone running production off the main HUB image. Should this be aligned to the stable branch (perhaps on the next stable release)?

**Comment by akmet** [comment]
Please have a look here #864 
We are working on it and hope that we have proper release channels soon.

**Comment by johansmitsnl** [comment]
Closing it in favour of #864.
There is a [stable](https://hub.docker.com/r/tvial/docker-mailserver/tags/) branch/tag on the hub available.
Working on the tags for versions.

**Comment by dmcgrandle** [comment]
Just tried switching to :stable, but getting the following errors:

Mar 13 00:26:29 mail dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
Mar 13 00:26:29 mail dovecot: lmtp: Fatal: master: service(lmtp): child 1568 killed with signal 9
Mar 13 00:26:59 mail dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
Mar 13 00:26:59 mail dovecot: lmtp: Fatal: master: service(lmtp): child 1686 killed with signal 9

Switched back to :latest and all is good again.  Will wait until I hear :stable is stable.  ;)
:D

**Comment by Fmstrat** [comment]
As a note, I switched to stable from latest on the HUB and it worked fine for me.

@dmcgrandle Perhaps try:
```
docker-compose stop mail
docker rm mail
docker-compose up -d mail
```
To clear the system? That's what I did and it worked for me.

**Comment by johansmitsnl** [comment]
@dmcgrandle the stable branch was working at the time. Sure that the state directory is not "dirty" for older config/packages?

**Comment by julianhille** [comment]
I created a docker some time ago for my branch here: https://hub.docker.com/r/namekku/docker-mailserver/builds/ currently sick so will need some more days for #804

**Comment by dmcgrandle** [comment]
@johansmitsnl I just tried again and this time it worked without incident.  Must have been a transient issue, as I did exactly the same thing I did last time but now it works.
@Fmstrat - I did the docker-compose down and up just as you wrote them, "docker rm mail" returns an error that there is no such process because docker-compose removes it cleanly.

Thanks all,
:D
