### ISSUE TITLE
Accounts.cf file example

### ISSUE THREAD

**Issue by dy0nysos** [tomav/docker-mailserver#9]
Hello,
First of all, thank you for your work. I was able to run the smtp server and the imap server very fast.
I just had some trouble with the virtual.db map. I had to touch a new virtual file and postmap it.

But I was a bit confused with accounts.cf file, because there is not example of it in this project, and the documentation is still based on the previous account management with the env vars.

Could you update your documentation and put an example file ?
Thank you !

**Comment by tomav** [comment]
Hi @dy0nysos,

The `accounts.cf` template file is available in `postfix/` folder.
https://github.com/tomav/docker-mailserver/tree/master/postfix

Try with it to see if your problem is not related to that.
I'll let you close it if it's ok, otherwise I'll have a closer look.

**Comment by dy0nysos** [comment]
Hi @tomav 
My bad, I didn't see this folder.
But the documentation isn't that clear about this file; Could you do something ?

About the virtual.db problem, I don't know where it comes from. I'll try to start a new container to see if the problem still occurs. If it's still buggy, i'll open a new issue

**Comment by tomav** [comment]
Let me know if it's ok.

**Comment by citec** [comment]
Hi, 
I am using this in the accounts.cf:
teste@testemail.com|aaa123
and using the whole email 'teste@testemail.com' as user and aaa123 as password in my email client. However, I am getting wrong username and password error message in my email client. 
So my question is what am I doing wrong? must the password be encrypted somehow, or just plaintext as I use it?

Log of the server on test:
mail_1 | Jan 21 09:32:36 mail imapd: Connection, ip=[::ffff:189.76.136.83]
mail_1 | Jan 21 09:32:37 mail imapd: Disconnected, ip=[::ffff:189.76.136.83], time=1

**Comment by tomav** [comment]
With the latest image, plaintext is supported.
