### ISSUE TITLE
Unexpected prefix added to the from-address

### ISSUE THREAD

**Issue by vincentcox** [tomav/docker-mailserver#902]
content `.env`:
```
HOSTNAME=domain.be
DOMAINNAME=domain.be
CONTAINER_NAME=mail
OVERRIDE_HOSTNAME=domain.be
...
```

When issuing the following command to send a test-email:
```
swaks -f test@domain.be --server 127.0.0.1:587 -tlsos --auth-user test@domain.be -body "Dit bericht is van vincent" -t my-email@gmail.com
```

I see in the logs:
```
Mar 15 10:52:33 domain postfix/qmgr[967]: 5DD061C16F0: from=<srs0=0zwz=gf=domain.be=test@be.domain.be>, size=1029, nrcpt=1 (queue active)
```
Note the "test@be.domain.be", which should be "test@domain.be".
The email will get in the spam (or even sent) because there are no DNS records for "be.domain.be". 

Any idea what is causing this?

**Comment by 17Halbe** [comment]
Are you using ldap?
Do you know when this started?

Just a wild guess, but since your domain is being rewritten,you could give this a try: https://github.com/tomav/docker-mailserver/issues/852#issuecomment-368348831 (Remember to switch spamassassin off or clean the cash after reloading postfix, otherwise your mail will still be regarded as spam.)

**Comment by vincentcox** [comment]
I am not using LDAP (I don't have changed any settings in the `.env`file, so I assume it's disabled)

It's a fresh install, with no changes in the config except the `.env` as indicated in the first post. 

I am looking into the issue you mentioned, but I am not sure what I should change in my config-file. Can you elaborate? 

Thanks already for the help, much appreciated.

**Comment by vincentcox** [comment]
I assume that you mean `/etc/postfix/main.cf`, but where is the file located? Just create a `main.cf` file in the `config` folder?

**Comment by akmet** [comment]
You can override postfix main.cf by editing config/postfix-main.cf

**Comment by vincentcox** [comment]
What content should I put in the file to try this? @akmet, thanks for the help, much appreciated!

**Comment by akmet** [comment]
Just that @17Halbe posted at #892

**Comment by vincentcox** [comment]
I think I located the issue: in my **hostname** was a dot: `my-domain.be`, which somehow created this bug. The hostname shouldn't be the same as the domain-name .

I would like to thank all you guys for the help!

**Comment by vincentcox** [comment]
![image](https://user-images.githubusercontent.com/9286611/37513500-8a1267b6-2905-11e8-97ff-4f4fd38dd44d.png)
whoop whoop! 😄
