### ISSUE TITLE
Consider not using spamhaus dns blacklist

### ISSUE THREAD

**Issue by TechnicLab** [tomav/docker-mailserver#903]
https://www.ripoffreport.com/reports/spamhaus/internet/spamhaus-spamhausorg-scam-tax-evasion-and-money-laundering-internet-1179782
https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fhabrahabr.ru%2Fpost%2F141231%2Fhttp%3A%2F%2F 
https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fhabrahabr.ru%2Fpost%2F313316%2F

**Comment by 17Halbe** [comment]
[Statement from Spamhaus](https://www.spamhaus.org/organization/statement/013/popular-spammer-myths-about-spamhaus)
I allways thought of Ripoff Reports as a gripe site.. ;) I couldn't find that much information about the site itself. They are in business for quite a while though. And their business model is apparently online defamation and getting payed for removing that content from their site. Even Google tried to delist them.(See [here](https://searchengineland.com/ripoff-report-subverting-google-take-downs-273440))
In my experience, Spamhaus was always one of the more trustable and reliable sites, but that doesn't mean, that they are "good guys". ;) 
The Ripoff Report article was the only third party report regarding that issue, I could find. The other two stories are fierce, but also only private reports from those affected. I'd rather hear both sides of a story! ;)
So without further "evidence" I would vote for leaving spamhaus in the lookup tables. If one wants to remove it, just overwrite it in postfix-main.cf. What do you think?

**Comment by johansmitsnl** [comment]
The articles are from several years ago.
Do you have personal experience it bad or harmful?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, open a PR based on the current master branch so we can review it.

**Comment by gheatza85** [comment]
Do not use Spamhaus, there are opensource alternatives
