### ISSUE TITLE
Exclude local-originating mails from spam filtering

### ISSUE THREAD

**Issue by jholster** [tomav/docker-mailserver#904]
It would be nice if locally sent emails were excluded from spam filtering by default (e.g. system notifications for root etc). I'm not sure how this should be implemented, can we trust e.g. the 'received' headers to figure out if the mail originates from our server?

**Comment by 17Halbe** [comment]
Who is denying it? Spamassassin or postscreen? Can you provide a log of the denial? What is your [permit_docker](https://github.com/tomav/docker-mailserver#permit_docker) setting? You are sending from where? (From inside the mailserver container/another docker container/ host system?)

**Comment by kortenkamp** [comment]
Hi,
I think I am running into the same problem. A user is denied sending emails whenever he is connected through a network that is blacklisted – although he tries to authenticate correctly. I am not sure whether there is some other configuration problem, and I am not sure how to test this better, but maybe someone else can see what's going on? Here's the relevant log.

```
mail    | May 10 12:08:22 mail postfix/postscreen[3115]: CONNECT from [88.130.48.213]:28199 to [172.19.0.2]:25
mail    | May 10 12:08:22 mail postfix/dnsblog[3333]: addr 88.130.48.213 listed by domain dnsbl.sorbs.net as 127.0.0.10
mail    | May 10 12:08:22 mail postfix/dnsblog[3334]: addr 88.130.48.213 listed by domain b.barracudacentral.org as 127.0.0.2
mail    | May 10 12:08:28 mail postfix/postscreen[3115]: DNSBL rank 3 for [88.130.48.213]:28199
mail    | May 10 12:08:29 mail postfix/tlsproxy[5135]: CONNECT from [88.130.48.213]:28199
mail    | May 10 12:08:29 mail postfix/tlsproxy[5135]: Anonymous TLS connection established from [88.130.48.213]:28199: TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits)
mail    | May 10 12:08:29 mail postfix/postscreen[3115]: DISCONNECT [88.130.48.213]:28199
mail    | May 10 12:08:29 mail postfix/tlsproxy[5135]: DISCONNECT [88.130.48.213]:28199
```

Ulli

**Comment by johansmitsnl** [comment]
He should not use port 25 for sending emails. Use 587 and it should be fine.

**Comment by kortenkamp** [comment]
Thanks, that worked!
