### ISSUE TITLE
Password with spaces is stripped to first word

### ISSUE THREAD

**Issue by Myiyk** [tomav/docker-mailserver#908]
With ./setup.sh you cannot save password with spaces.
Bug is with creation of new email and update. Both will save only first word as password.

## Expected Behavior

Saved password will be same as I write to command.

## Actual Behavior

If password contains space, only first word is saved as password.

## Steps to Reproduce

1. `./setup.sh email update somemail@example.com "super secrete password"`
2. Try login with "super secrete password", it doesn't work
3. Login will works only with password "super"

## Your Environment

* Mailserver version used: Latest, with lastest setup.sh from master
* Docker version used: 17.05.0-ce, build 89658be

**Comment by 17Halbe** [comment]
Thanks for reporting!
