### ISSUE TITLE
"setup.sh alias del" removes entire alias and not just a single recipient

### ISSUE THREAD

**Issue by capi** [tomav/docker-mailserver#909]
Thanks for this great project.
When I was playing around with aliases, I noticed, that the "setup.sh alias del" does not work as I would expect it. It seems, that it doesn't care about the given target at all and will remove the entire alias

## Context
```
# ./setup.sh alias add test@test.com recipient1@other.com
# ./setup.sh alias add test@test.com recipient2@other.com
# ./setup.sh alias list | grep test@test.com
test@test.com recipient1@other.com,recipient2@other.com
# ./setup.sh alias del test@test.com recipient2@other.com
# ./setup.sh alias list | grep test@test.com
```

## Expected Behavior
I expected the alias to remain with just `recipient1@other.com`.

## Actual Behavior
The entire alias has been removed.

**Comment by 17Halbe** [comment]
Thanks a lot for your report!
I just checked the code and I really don't know how this should have worked in the first place. So it's confirmed.
Additionally your case wasn't tested for, so thanks for the additional test case! :+1: 
PR is testing right now.
