### ISSUE TITLE
How do I use this with Apple Mail?

### ISSUE THREAD

**Issue by playent** [tomav/docker-mailserver#91]
Usually, I set up DNS records to get this to work. Need a little guidance here. Also, how can I review logs?

**Comment by tomav** [comment]
Hi @playent, its works exactly as another mail server regarding DNS.
Add a `MX` entry that points to your mail server IP. That's all.
The way to do that depends on the way you manage your DNS server (locally using zone file, or using the web interface of your DNS provider like Godaddy, Gandy...)

For the logs, here it's like every docker container: `docker logs -f mail`

If you're new to docker, I recommend to have a look to the [docker documentation](https://docs.docker.com/) which is really easy to understand.

Let me know if you have other questions.

Hope this helps.
