### ISSUE TITLE
opendmarc[122]: ignoring connection from 

### ISSUE THREAD

**Issue by SeanFacer** [tomav/docker-mailserver#911]
Im trying tos send emails from my application and getting bounced. I am able to send via the docker-mailserver container just not via any of the other containers within the network. 

Belo is the error message I am receiving.

mail_1       | Mar 19 14:57:18 mail postfix/submission/smtpd[1151]: connect from irec_php-fpm_1.irec_default[172.24.0.5]
mail_1       | Mar 19 14:57:18 mail opendmarc[123]: ignoring connection from irec_php-fpm_1.irec_default
mail_1       | Mar 19 14:57:18 mail postfix/submission/smtpd[1151]: disconnect from irec_php-fpm_1.irec_default[172.24.0.5] ehlo=0/1 quit=1 commands=1/2

config
HOSTNAME=mail
DOMAINNAME=irecordtime.co.uk
CONTAINER_NAME=irec_mail
PERMIT_DOCKER=network
ENABLE_FAIL2BAN=0
ENABLE_SRS=0
SPOOF_PROTECTION=1

**Comment by johansmitsnl** [comment]
You need to send email on 587 port and not through 25.
See https://github.com/tomav/docker-mailserver#exposed-ports

**Comment by SeanFacer** [comment]
I am using port 587

.env

HOSTNAME=mail
DOMAINNAME=irecordtime.co.uk
CONTAINER_NAME=irec_mail
OVERRIDE_HOSTNAME=irecordtime.co.uk
DMS_DEBUG=1
ONE_DIR=0
POSTMASTER_ADDRESS=
PERMIT_DOCKER=network
TLS_LEVEL=modern
SPOOF_PROTECTION=1
ENABLE_SRS=0
ENABLE_POP3=
ENABLE_CLAMAV=0
ENABLE_FAIL2BAN=0
ENABLE_MANAGESIEVE=
POSTSCREEN_ACTION=enforce
SMTP_ONLY=
SSL_TYPE=
VIRUSMAILS_DELETE_DELAY=
ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
POSTFIX_DAGENT=
REPORT_RECIPIENT=0
REPORT_INTERVAL=daily
ENABLE_SPAMASSASSIN=0
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=6.31
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
ENABLE_LDAP=
LDAP_START_TLS=
LDAP_SERVER_HOST=
LDAP_SEARCH_BASE=
LDAP_BIND_DN=
LDAP_BIND_PW=
LDAP_QUERY_FILTER_USER=
LDAP_QUERY_FILTER_GROUP=
LDAP_QUERY_FILTER_ALIAS=
DOVECOT_TLS=
DOVECOT_USER_FILTER=
DOVECOT_PASS_FILTER=
ENABLE_POSTGREY=0
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_TEXT=Delayed by postgrey
ENABLE_SASLAUTHD=0
SASLAUTHD_MECHANISMS=
SASLAUTHD_MECH_OPTIONS=
SASLAUTHD_LDAP_SERVER=
SASLAUTHD_LDAP_SSL=
SASLAUTHD_LDAP_BIND_DN=
SASLAUTHD_LDAP_PASSWORD=
SASLAUTHD_LDAP_SEARCH_BASE=
SASLAUTHD_LDAP_FILTER=
SASL_PASSWD=
SRS_EXCLUDE_DOMAINS=
SRS_SECRET=

docker-compose
mail:
    build: ./build/mail
    hostname: mail
    domainname: irecordtime.co.uk
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    environment:
      - DMS_DEBUG=${DMS_DEBUG}
      - ENABLE_CLAMAV=${ENABLE_CLAMAV}
      - ONE_DIR=${ONE_DIR}
      - ENABLE_POP3=${ENABLE_POP3}
      - ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
      - ENABLE_MANAGESIEVE=${ENABLE_MANAGESIEVE}
      - OVERRIDE_HOSTNAME=${OVERRIDE_HOSTNAME}
      - POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS}
      - POSTSCREEN_ACTION=${POSTSCREEN_ACTION}
      - REPORT_RECIPIENT=${REPORT_RECIPIENT}
      - REPORT_INTERVAL=${REPORT_INTERVAL}
      - SMTP_ONLY=${SMTP_ONLY}
      - SSL_TYPE=${SSL_TYPE}
      - TLS_LEVEL=${TLS_LEVEL}
      - SPOOF_PROTECTION=${SPOOF_PROTECTION}
      - ENABLE_SRS=${ENABLE_SRS}
      - PERMIT_DOCKER=${PERMIT_DOCKER}
      - VIRUSMAILS_DELETE_DELAY=${VIRUSMAILS_DELETE_DELAY}
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=${ENABLE_POSTFIX_VIRTUAL_TRANSPORT}
      - POSTFIX_DAGENT=${POSTFIX_DAGENT}
      - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
      - SA_TAG=${SA_TAG}
      - SA_TAG2=${SA_TAG2}
      - SA_KILL=${SA_KILL}
      - SA_SPAM_SUBJECT=${SA_SPAM_SUBJECT}
      - ENABLE_FETCHMAIL=${ENABLE_FETCHMAIL}
      - FETCHMAIL_POLL=${FETCHMAIL_POLL}
      - ENABLE_LDAP=${ENABLE_LDAP}
      - LDAP_START_TLS=${LDAP_START_TLS}
      - LDAP_SERVER_HOST=${LDAP_SERVER_HOST}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PW=${LDAP_BIND_PW}
      - LDAP_QUERY_FILTER_USER=${LDAP_QUERY_FILTER_USER}
      - LDAP_QUERY_FILTER_GROUP=${LDAP_QUERY_FILTER_GROUP}
      - LDAP_QUERY_FILTER_ALIAS=${LDAP_QUERY_FILTER_ALIAS}
      - DOVECOT_TLS=${DOVECOT_TLS}
      - DOVECOT_USER_FILTER=${DOVECOT_USER_FILTER}
      - DOVECOT_PASS_FILTER=${DOVECOT_PASS_FILTER}
      - ENABLE_POSTGREY=${ENABLE_POSTGREY}
      - POSTGREY_DELAY=${POSTGREY_DELAY}
      - POSTGREY_MAX_AGE=${POSTGREY_MAX_AGE}
      - POSTGREY_TEXT=${POSTGREY_TEXT}
      - ENABLE_SASLAUTHD=${ENABLE_SASLAUTHD}
      - SASLAUTHD_MECHANISMS=${SASLAUTHD_MECHANISMS}
      - SASLAUTHD_MECH_OPTIONS=${SASLAUTHD_MECH_OPTIONS}
      - SASLAUTHD_LDAP_SERVER=${SASLAUTHD_LDAP_SERVER}
      - SASLAUTHD_LDAP_SSL=${SASLAUTHD_LDAP_SSL}
      - SASLAUTHD_LDAP_BIND_DN=${SASLAUTHD_LDAP_BIND_DN}
      - SASLAUTHD_LDAP_PASSWORD=${SASLAUTHD_LDAP_PASSWORD}
      - SASLAUTHD_LDAP_SEARCH_BASE=${SASLAUTHD_LDAP_SEARCH_BASE}
      - SASLAUTHD_LDAP_FILTER=${SASLAUTHD_LDAP_FILTER}
      - SASL_PASSWD=${SASL_PASSWD}
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./config/:/tmp/docker-mailserver/

**Comment by SeanFacer** [comment]
May have used 25 while messing around / trying to debug and see if I got any different results.

Codeignitor config

$config = Array(
            'protocol' => 'smtp',
            // 'smtp_host'=> '172.24.0.7',
            'smtp_host'=> 'mail',
            // 'smtp_port'=> '465',
            'smtp_port'=> '587',
            'mailtype' => 'html',
            'charset'  => 'utf-8',
            'newline'  => "\r\n"
        );

        $this->load->library('email', $config);

**Comment by johansmitsnl** [comment]
And?

**Comment by SeanFacer** [comment]
and it still doesnt work :0

**Comment by johansmitsnl** [comment]
and when you use a normal email client?

**Comment by elietheocari** [comment]
Hi there, same issue here.
I try sending emails from a PHP app, using SSL protocol and port 465.

Here is what I get.

`Mar 22 15:38:27 mail postfix/smtps/smtpd[2992]: connect from md-forum-prod.docker_default[172.18.0.2]
Mar 22 15:38:27 mail postfix/smtps/smtpd[2992]: Anonymous TLS connection established from md-forum-prod.docker_default[172.18.0.2]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Mar 22 15:38:27 mail opendmarc[258]: ignoring connection from md-forum-prod.docker_default
Mar 22 15:38:27 mail postfix/smtps/smtpd[2992]: lost connection after CONNECT from md-forum-prod.docker_default[172.18.0.2]
Mar 22 15:38:27 mail postfix/smtps/smtpd[2992]: disconnect from md-forum-prod.docker_default[172.18.0.2] commands=0/0`

Same result on port 587 (except for the second log line, "Anonymous TLS connection established...", which does not appear).

I will let you know if I find something.

**Comment by elietheocari** [comment]
Well, I ended up using plain text authentication on port 25.
As this is one of my containers getting in touch with the mail server on the same host, I guess that this should not be a problem... should it?

**Comment by dashohoxha** [comment]
You have `SSL_TYPE=` which means that SSL is disabled. Without SSL certificates you cannot use SSL connections (ports 587 and 465).

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
