### ISSUE TITLE
Domain name being doubled in bounce address

### ISSUE THREAD

**Issue by nicklayb** [tomav/docker-mailserver#912]
My bounce address domain is always doubled up

## Context
When I' sending email, the 
```
Received-SPF: neutral (google.com: 24.xxx.xxx.xx is neither permitted nor denied by best guess record for domain of srs0=2yi9=gj=armquebec.com=nboisvert@armquebec.com.armquebec.com) client-ip=24.xxx.xxx.xx;
Authentication-Results: mx.google.com;
       dkim=temperror (no key for signature) header.i=@armquebec.com header.s=mail header.b=YNRBa48y;
       spf=neutral (google.com: 24.xxx.xxx.xx is neither permitted nor denied by best guess record for domain of srs0=2yi9=gj=armquebec.com=nboisvert@armquebec.com.armquebec.com) smtp.mailfrom=srs0=2yi9=gj=armquebec.com=nboisvert@armquebec.com.armquebec.com
Mime-Version: 1.0
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=armquebec.com; s=mail; t=1521489463; bh=wVewh0qp5LDswhJsX9gvx+V0ZNrIZvATYGNQFxnrMRE=; h=To:From:Subject; b=YNRBa48yQjtJHM0R2EnKOQRf0+JsujQe+mHmbQzyVYoDjEKJPuEtevTVp0eFbf8bj
	 YnhUsAmttLhkPuvp5bSeBJiMn/iKeeenw8WKFLZvVyZogSgI2z+j3VKdFCQeapjiXW
	 gt2XBb/IOKPO1MNP4SoVsSt3E9nxMJ9ySd94DfkSkMjTfjdgenw2oeCnUSjZ2VcrXY
	 v/tEGgKrsa+AKmkBgg0xPD0utxoW6a1n1FDDBbFjArCPabWO7rgilEdUnU2aYr4PCh
	 Oxc36pXUfm8LMFl5gTd7tuzg9b2cKqDwGWrXhusIt8QghgqEj7Ff3sLv/rOXmjlpt0
	 Qq6ByRfE4V8ow==
To: Nicolas Boisvert <nboisvert@armcanada.ca>
From: Nicolas Boisvert <nboisvert@armquebec.com>
Subject: TEST
Date: Mon, 19 Mar 2018 15:57:43 -0400
Importance: normal
X-Priority: 3
Content-Type: multipart/alternative; boundary="_B22959EB-4415-41FA-8791-6C7886C7194E_"
Message-Id: <20180319195743.309441800A7A@mail.armquebec.com>

--_B22959EB-4415-41FA-8791-6C7886C7194E_
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"
```

I know that the SFP is not yet set but the domain is doubled up the line : 
Received-SPF: neutral (google.com: 24.xxx.xxx.xx is neither permitted nor denied by best guess record for domain of srs0=2yi9=gj=armquebec.com=nboisvert@**armquebec.com.armquebec.com**) client-ip=24.xxx.xxx.xx;

Users I'm trying to email are not recieving my mails.

## Expected Behavior
Honestly I'm not sure what to expect, but I think it should be only the address of the send which is nboisvert@armquebec.com

## Actual Behavior
It writes nboisvert@armquebec.com.armquebec.com

## Your Environment
* Amount of RAM available:~3gb
* Mailserver version used: latest
* Docker version used: 17.12.1-ce
* Environment settings relevant to the config:
```
HOSTNAME=mail
DOMAINNAME=armquebec.com
CONTAINER_NAME=mail
OVERRIDE_HOSTNAME=mail.armquebec.com
```

I'm new to mail servers and got to have this setup as soon as possible!

Thank you guys!

**Comment by 17Halbe** [comment]
From when is your docker image? There was a issue with SRS which got fixed yesterday. Could you try rebuilding your docker image?
I guess you tried without OVERRIDE_HOSTNAME, right?

**Comment by nicklayb** [comment]
Right on it! Did a clean pull of the latest image and everything is as expected!

The `OVERRIDE_HOSTNAME` was required for let's encrypt certificates
