### ISSUE TITLE
Sending mails from server using sSMTP

### ISSUE THREAD

**Issue by jpmaas** [tomav/docker-mailserver#917]
Hello everyone,

first of all, thank you so much for this project! It spared me of hours of configuring this server myself 👍 

I'm currently trying to send mails from command line using `ssmtp` and `mailutils` over the docker-mailserver to my private mail (relevant updates with monitoring etc. just some basic stuff). Testing it with Thunderbird from my home computer sending mails works perfectly.

Still, I can not manage to do so using the `mail` command. I followed the README.md as close as possible, set up the required user and generated the DKIM keys. Also, I am using the default configuration with let's encrypt certificates, but sending mails using `mail` always ends with the following server logs:
```
Mar 24 13:04:13 mail postfix/submission/smtpd[8276]: connect from my.server.name[some ip]
Mar 24 13:04:13 mail postfix/submission/smtpd[8276]: SSL_accept error from my.server.name[some ip]: -1
Mar 24 13:04:13 mail postfix/submission/smtpd[8276]: warning: TLS library problem: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:974:
Mar 24 13:04:13 mail postfix/submission/smtpd[8276]: lost connection after STARTTLS from my.server.name[some ip]
Mar 24 13:04:13 mail postfix/submission/smtpd[8276]: disconnect from my.server.name[some ip] ehlo=1 starttls=0/1 commands=1/2
```

sSMTP always logs the following:
```
Mar 24 13:49:00 hostname sSMTP[22555]: Cannot open mail.my.server.name:587
Mar 24 13:51:51 hostname sSMTP[23148]: Creating SSL connection to host
Mar 24 13:51:51 hostname sSMTP[23148]: SSL connection using (null)
```

My sSMTP config:
```
#
# Config file for sSMTP sendmail
#
# The person who gets all mail for userids < 1000
# Make this empty to disable rewriting.
root=noreply@my.server.name

# The place where the mail goes. The actual machine name is required no
# MX records are consulted. Commonly mailhosts are named mail.domain.com
mailhub=mail.my.server.name:587

# Where will the mail seem to come from?
#rewriteDomain=

# The full hostname
hostname=my.server.name

# Are users allowed to set their own From: address?
# YES - Allow the user to specify their own From: address
# NO - Use the system generated From: address
FromLineOverride=YES

UseSTARTTLS=YES

AuthUser=noreply@my.server.name
AuthPass=[some password]
```

I also updated the revaliases accordingly, but I'm obviously still missing some important piece...

I hope you guys can provide some insights :)

Best regards,
JP

**Comment by akmet** [comment]
You could change your tls_level to intermediate. Please have a look at the readme for more details, currently on mobile.

**Comment by jpmaas** [comment]
Just tried that, still the same behaviour unfortunately :(

**Comment by mwlczk** [comment]
@jpmaas there is a little bug in processing the TLS_LEVEL. It works for SMTP and forr IMAP/POP. But fails to switch for SMTPD (submission daemon on ports 465 and 587).
I provided a PR #916. Until this is merged you could use config/postfix-main.cf to ovveride smtpd_mandatory_protocols and allow TLSv1 and tlsv1.1

But the best would be to use submission clients which are capable of TLSv1.2

**Comment by johansmitsnl** [comment]
#916 just got merged.

**Comment by jpmaas** [comment]
I just tested, it now works like a charm :) thank you very much, I'll close this one.
