### ISSUE TITLE
[Question] Persistence of mails

### ISSUE THREAD

**Issue by andymel123** [tomav/docker-mailserver#918]
I'm new to docker but it was really beautifully easy to setup your mail server image.
I just don't understand how the persistence works. I can see the mail data in /var/mail inside the docker image but not on the host machine. Nevertheless when I remove the image and compose it again, the old mails are still there.

The way I tested persistence:
- connected a mail client and sent/received some test mails
- removed the docker container
- composed up a new container
- connected another mail client on another device (to be sure old mails are coming from the server)...old mails exist

I wanted to add auto-backup scripts to the /var/mail folder on the host machine but as the folder is empty...

I just 

- pulled the image and the 3 files (setup.sh, docker-compose.yml and .env).
- added a test email address (and tested as written above)
- I think the only file I changed was .env but nothing sounds like it could cause changes for persistence (HOSTNAME, DOMAINNAME, POSTMASTER_ADDRESS, SPOOF_PROTECTION=1, ENABLE_CLAMAV=1, letsencrypt, VIRUSMAILS_DELETE_DELAY=30, REPORT_RECIPIENT=1, ENABLE_SPAMASSASSIN=1)

Host: Debian 9

Docker:
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:21 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:15:56 2018
  OS/Arch:      linux/amd64
  Experimental: false

I pretty sure this is a dumb question but I haven't found any answer in your wiki or the issues

**Comment by akmet** [comment]
Docker is a container environment and therefore the /var/mail folder inside the docker container is not equal to your hosts /var/mail folder.

There is a nice article over the volumes topic here: https://docs.docker.com/storage/volumes/

To come back to your initial problem: You could use docker commit or docker export for backup the mail folders

**Comment by andymel123** [comment]
Oh, I thought the "maildata:/var/mail" in combination with "maildata: driver: local" means it is stored on the hosts local file system

Thanks...I will have a look at export/commit and read the article you mentioned! :)
