### ISSUE TITLE
Multi-domain Mailgun configuration

### ISSUE THREAD

**Issue by crazystick** [tomav/docker-mailserver#922]
The AWS SES settings work well for a single domain using [Mailgun](https://www.mailgun.com/) to relay email. However for a multi-domain setup it isn't quite enough, as we want to authenticate as different users depending on the sender's domain.

The configuration is described well in [this forum post][1].

From looking at the code, it looks like this will need code adding in `start-mailserver.sh#_setup_dovecot_local_user()` and in `check-for-changes,sh` and a new function along the lines of `start-mailserver.sh#_setup_postfix_relay_amazon_ses()`

I'm happy to have a go at this so here's my plan:
* maintain another file postfix-sasl-password.cf to provide the multiple username passwords
* add extra env variables:
  * `MULTI_DOMAIN_RELAY_HOST`
  * `MULTI_DOMAIN_RELAY_PORT`
  * `MULTI_DOMAIN_RELAY_DEFAULT_USER`
  * `MULTI_DOMAIN_RELAY_DEFAULT_PASSWORD`
* update `relayhost_map` file at startup and on changes
* (bonus) add a function to setup.sh which creates/updates `postfix-sasl-password.cf`

A couple of thoughts/questions:
1. Relay passwords will be stored in plain text in `config/postfix-sasl-password.cf` (I guess it's not really worse than the current solution which needs the password in the docker-compose.yml or in .env)
2. `MULTI_DOMAIN_RELAY_HOST` and `AWS_SES_HOST` can't both be true - can this merely be documented in README?

[1]: https://community.rackspace.com/products/f/email-products-forum/3897/how-to-setup-postfix-with-a-mailgun-smtp-relay-when-using-multiple-domains

**Comment by johansmitsnl** [comment]
@crazystick The SES is not sufficiënt indeed and it causes a lot of confusion for users. Love to see a PR for this.

1. The password can be unencrypted indeed.
2. If you could make a backwards merge by using the old variable into the new ones if set. The new one should have priority and we should and can depreciate the old variables with explanation with it.

The plan looks good to me.

**Comment by dmcgrandle** [comment]
Great PR idea!  I’ve been holding off on implementing multiple domains using this container, and runnning multiple containers instead due to these limitations.  I actually have quite different requirements for the different domains: one needs a smart relay host and the other does not.  One is IPv6 only, the other is IPv4, although I could live with the requirement that both be mixed.  Would like to see a configuration that allowed this.

**Comment by dmcgrandle** [comment]
One more difference, though I’m not certain it would matter.  One domain receives emails directly and the other pulls emails in from elsewhere using Fetchmail.

**Comment by crazystick** [comment]
WIP - still need to add code to `check-for-changes.sh` and to `setup.sh` but that is working for my use-case (sending for multiple domains via Mailgun with different username/passwords for each). I also verified that it will support sending for some domains via Mailgun and others via Sendgrid. @dmcgrandle does that work for you? I haven't tested direct delivery for some domains.

**Comment by dmcgrandle** [comment]
I will need one domain delivering directly and one through a relayhost.  About to be on vacation for a while, happy to test when I return.

**Comment by crazystick** [comment]
[Wiki](https://github.com/tomav/docker-mailserver/wiki/Configure-Relay-Hosts) is updated.

@dmcgrandle I'm hopeful that this will work for you - see the wiki page, specifically the exclude-domain command of setup.sh. I can't really test it since I'm running on Google Compute engine which doesn't allow outgoing connections on port 25. If it doesn't work, probably best to open a new issue, feel free to tag me in it.
