### ISSUE TITLE
Daily error mail: duplicate log entry for /var/log/mail/mail.log 

### ISSUE THREAD

**Issue by Starbix** [tomav/docker-mailserver#925]
## Context

I get a daily email that says that there's a duplicate entry.

I think this happens because there's `/var/log/mail/mail.log` in both `/etc/logrotate.d/maillog` and `/etc/logrotate.d/rsyslog`
## Expected Behavior

No error mails.

## Actual Behavior
I get a daily mail with the following content:

```
/etc/cron.daily/logrotate: 
error: rsyslog:13 duplicate log entry for /var/log/mail/mail.log 
```

## Possible Fix

Removing either `/etc/logrotate.d/maillog` or the `mail.log` entry in `/etc/logrotate.d/rsyslog`
## Steps to Reproduce

1. Happens automatically

## Your Environment

* Amount of RAM available: 72 GB
* Mailserver version used: latest (as of 31.3.18)
* Docker version used: 
```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:13:43 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:20:43 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

* Environment settings relevant to the config: All mails to unknown accounts get redirected to the admin.

**Comment by akmet** [comment]
Will have a look at it later, but it should not exists in rsyslog..
removing the /maillog would cause that no mail is sent

**Comment by 17Halbe** [comment]
I had the same error once. But I thought the build process had a hickup. 
I just confirmed it. It's a bug.
This is the line where the mail.log logrotate setting should get removed: 
https://github.com/tomav/docker-mailserver/blob/2e06228b101b4deff794686e3cb997e458eb3d3b/Dockerfile#L201
That's step 43 during the build process.
The sed command should be following the next line. Basically switch line 201 with 202.
