### ISSUE TITLE
dkim-setup create two keys in mail.txt, which is the correct one? Is this correct?

### ISSUE THREAD

**Issue by helmutundarnold** [tomav/docker-mailserver#929]
# Context
running the following command from console:
`docker run --rm -v /opt/ckb/ckb1/mailserver/mail12/config:/tmp/docker-mailserver -ti tvial/docker-mailserver:latest generate-dkim-config 1048
`
I get a mail.txt with two keys

```
cat config/opendkim/keys/christuskirche.net/mail.txt
mail._domainkey	IN	TXT	( "v=DKIM1; h=sha256; k=rsa; "
	  "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwsMW/RjjEs7FfDvjSrJDl29mcfeyuKdBFyQDg7EXeKR30Fg+LjWVY06jm79C6GU4fDuA8GTSB9cPCzNE/hQ5bQ9PzR/qU3zcGyQl3RO5m0CmGR3kA/kqpwqiznfj94A+9F2jus1xB3P8X5FkPrgIKcct9b0jqeQJizOKAKaccjsAIWdC4JRqU3/UE8rXQslKn1YoALWiQEOtiX"
	  "bYWL/xICncrlHqs/8RFu/me0hSbRbtnRk624nmAGIhqENietvZgdplrsM5kpZJi1jlDA+UcbZGq4HP7kszUXLFICTfTNwK/tF+aBpXf7h4vT42cT2R+9Jct+6Cwy4mB/LFHIfpvQIDAQAB" )  ; ----- DKIM key mail for example.net

```

## Expected Behavior

I would expect that I get an output similar to the one the the description with one key

## Actual Behavior

I get two keys

## Steps to Reproduce

1. install mailserver 
2.run ....generate-dkim-config 1048

BTW: run ....generate-dkim-config without 1048 produce the same output.

## Your Environment

* Amount of RAM available: 16GB
* Mailserver version used: lasted
* Docker version used: 17.12.0-ce
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by mwlczk** [comment]
Hi, it is one key. Because of UDP packet size it is split. You need to concatenate both strings to have the full dkim public key

**Comment by helmutundarnold** [comment]
Thank you for the very quick answer. This issue can be solved.
