### ISSUE TITLE
Letsencrypt

### ISSUE THREAD

**Issue by scher200** [tomav/docker-mailserver#93]
I get an error on line 129 from /usr/local/bin/start-mailserver.sh
the line looks like:
`
cat "/etc/letsencrypt/live/$(hostname)/cert.pem" "/etc/letsencrypt/live/$(hostname)/chain.pem"  "/etc/letsencrypt/live/$(hostname)/privkey.pem" > "/etc/letsencrypt/live/$(hostname)/combined.pem"
`
and it is pretty clear why, the directory does not exist at all.

do i need to mount these directories myself?

**Comment by tomav** [comment]
I experienced the same issue yesterday but didn't get time to dig into.
The normal use case is to provide `cert.pem`, `chain.pem`, `privkey.pem` and combined is auto-generated on startup and overwritten if exists.

**Comment by tomav** [comment]
And we need to add a test on that part.

**Comment by tomav** [comment]
@scher200 I think the problem was my files. Everything works as expected.
Could you confirm that providing `cert.pem`, `chain.pem`, `privkey.pem`, the `combined.pem` is generated correctly?

**Comment by tomav** [comment]
Confirmed, I know what's the problem. `combined` can't be created if `live/` symlink are absolute. Changing them to relive works as expected.

        cert.pem -> ../../archive/domain.com/cert1.pem
	chain.pem -> ../../archive/domain.com/chain1.pem
	combined.pem
	fullchain.pem -> ../../archive/domain.com/fullchain1.pem
	privkey.pem -> ../../archive/domain.com/privkey1.pem

**Comment by scher200** [comment]
@tomav I am not so sure where to find this live/ symlink ..
Or has it something todo with the mounted files in my docker-compose file:
`
mail:
  image: tvial/docker-mailserver
  hostname: mail
  domainname: mydomain___.com
  cap_add:
    - NET_ADMIN
  ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
  volumes:
    - ./spamassassin:/tmp/spamassassin/
    - ./postfix:/tmp/postfix/
  environment:
    VIRTUAL_HOST: mail.mydomain___.com
    DMS_SSL: letsencrypt
`

**Comment by tomav** [comment]
Usually, with LE, `live/mail.domain.com/*` certificates are symlinked to `archive/mail.domain.com/*` folder.

**Comment by tomav** [comment]
On my host, here is the result of `tree .` from `docker-mailserver/letsencrypt/`

[15:26:14] letsencrypt [git:master*] $ tree .
	.
	├── etc
	│   ├── accounts
	│   ├── archive
	│   │   ├── mail.domain.com
	│   │   │   ├── cert1.pem
	│   │   │   ├── chain1.pem
	│   │   │   ├── fullchain1.pem
	│   │   │   └── privkey1.pem
	│   ├── csr
	│   ├── dhparams.pem
	│   ├── html
	│   ├── keys
	│   ├── live
	│   │   ├── mail.domain.com
	│   │   │   ├── cert.pem -> ../../archive/mail.domain.com/cert1.pem
	│   │   │   ├── chain.pem -> ../../archive/mail.domain.com/chain1.pem
	│   │   │   ├── combined.pem
	│   │   │   ├── fullchain.pem -> ../../archive/mail.domain.com/fullchain1.pem
	│   │   │   └── privkey.pem -> ../../archive/mail.domain.com/privkey1.pem
	│   └── renewal
	│       ├── domain.com.conf
	└── lib

**Comment by tomav** [comment]
Closed due to inactivity.
