### ISSUE TITLE
VIRUSMAILS_DELETE_DELAY is unset

### ISSUE THREAD

**Issue by crazystick** [tomav/docker-mailserver#932]
According to README, VIRUSMAILS_DELETE_DELAY defaults to 7 if unset.

[This line][1] perhaps doesn't do what was intended?

Eventually you get this output from cron: 
```
find: invalid argument `+' to `-mtime'
Try 'find --help' for more information.
```

[1]: https://github.com/tomav/docker-mailserver/blob/31c40ce271f6268e4daac36b6aa3f8ff44843e2a/target/start-mailserver.sh#L1229

**Comment by 17Halbe** [comment]
Good find! Thank you!
Did you set `VIRUSMAILS_DELETE_DELAY` during the container start? Or did you use the .env file? 
If you did, I found the bug! ;)
So if you somehow touched(and not set) the variable when starting the container it gets set to nothing. If you just omit it at all, the variable should be at its default value. (It has been set during the build process)
Just want to make sure, before fixing.

**Comment by crazystick** [comment]
Yes - I'm using the .env file
