### ISSUE TITLE
I would like to have pflogsumm and mailutils added to the base-image.

### ISSUE THREAD

**Issue by helmutundarnold** [tomav/docker-mailserver#933]
Currently I have to add this packet after each container-creation  manually.
## Context

commands would be
```
apt-get update -y
apt-get install pflogsumm mailtuils
```
## Expected Behavior

pflogsumm and mail are available on commandline.

## Actual Behavior

not available
## Possible Fix

```
apt-get update -y
apt-get install pflogsumm mailtuils
```
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by akmet** [comment]
Plogsumm **is** in the image. Could you try to pull the newest version? What version are you using?

**Comment by 17Halbe** [comment]
pflogsumm is part of this image: See [REPORT_RECIPIENT](https://github.com/tomav/docker-mailserver#report_recipient)
What do you need mailtuils for?

**Comment by helmutundarnold** [comment]
Sorry for confusion ..... YES pflogsumm is in the image just tested right now. 

With the mailutils package I can send an email of pflogsumm to our admin-group using "email"  commandline tool. Is there possibly another way?

**Comment by 17Halbe** [comment]
If you just need the pflogsumm report being sent then it's already there. Just specify the recipient in REPORT_RECIPIENT.
Otherwise there is sendmail. For an example have a look here: https://github.com/tomav/docker-mailserver/blob/f540f8e9c3ac0980364219c2946151abf149fc90/target/bin/postfix-summary#L18

**Comment by helmutundarnold** [comment]
Great ..... your example helps me, so I can leave without mailutils. 
Thanks for your quick help.
