### ISSUE TITLE
default value for POSTMASTER_ADDRESS

### ISSUE THREAD

**Issue by crazystick** [tomav/docker-mailserver#938]
This might not be a bug, but I read the documentation and thought that an empty value for POSTMASTER_ADDRESS would lead to the value `postmaster@${DOMAINNAME}`
Actually it is literally as the documentation says: `postmaster@domain.com` - see [here][1]
I think it would be more logical to have the default be an actual useful address.

[1]: https://github.com/tomav/docker-mailserver/blob/137d623171daaf9f1219f96ca20d04b9c587d13e/target/start-mailserver.sh#L26

**Comment by 17Halbe** [comment]
Agreed, would you like to contribute?

**Comment by crazystick** [comment]
Sure - will do.
