### ISSUE TITLE
hostname/domainname override tests don't actually test anything

### ISSUE THREAD

**Issue by crazystick** [tomav/docker-mailserver#939]
The actual hostname and the override hostname for the container `mail_override_hostname` are equal, so all those tests are going to pass whether or not the hostname override feature works!

**Comment by johansmitsnl** [comment]
Could you provide a PR for changing the tests?

**Comment by crazystick** [comment]
You want me to separate PR #940 into two separate ones?

**Comment by johansmitsnl** [comment]
No not needed, just did not see your PR yet. It just got merged, thnx for the contribution!
