### ISSUE TITLE
lets encrypt ssl stupid question time

### ISSUE THREAD

**Issue by Dynamite874** [tomav/docker-mailserver#94]
Hiya. 

I generated my cert with the cert-only command with letsencrypt and left it in the /etc/letsencrypt/live folder.

Whenever I run the SSL test I get the following back
```

root@cg-docker1:~/mail# docker exec mail_mail_1 openssl s_client -connect 0.0.0.0:25 -starttls smtp -CApath /etc/ssl/certs/
140645256402592:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
CONNECTED(00000003)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 331 bytes and written 330 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE

```

Is thats enough info for someone to work out where I have been stupid and gone wrong ?

**Comment by tomav** [comment]
Hi @Dynamite874, are you sure your LE certs a correctly mounted?
Can I see your folder setup and `docker-compose.yml` file?
Thank you.

**Comment by tomav** [comment]
Here is my test using your command:

    $ docker exec mail openssl s_client -connect 0.0.0.0:25 -starttls smtp -CApath /etc/ssl/certs/
    depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
    verify return:1
    depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X1
    verify return:1
    depth=0 CN = domain.com
    verify return:1
    CONNECTED(00000003)
    ---
    Certificate chain
     0 s:/CN=domain.com
       i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X1
     1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X1
       i:/O=Digital Signature Trust Co./CN=DST Root CA X3
    ---
    Server certificate
    -----BEGIN CERTIFICATE-----
    MIIF
    ...
    ==
    -----END CERTIFICATE-----
    subject=/CN=domain.com
    issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X1
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 3316 bytes and written 456 bytes
    ---
    New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
    Server public key is 2048 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : ECDHE-RSA-AES256-GCM-SHA384
        Session-ID: 28429B71D7EDB42EFED18E93E2B6604CDB48957D1D979241F9D4F665D51E5EE2
        Session-ID-ctx:
        Master-Key: 6C23219EA467BBE1FC8D76AE3A9E7805A7AA29D031AE43F38465DD1E008D86178F690FA7EF88C6402A53F7EA01814BE1
        Key-Arg   : None
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        Start Time: 1457010017
        Timeout   : 300 (sec)
        Verify return code: 0 (ok)
    ---
    250 DSN
    DONE

**Comment by Dynamite874** [comment]
Not sure what you mean by correctly mounted that may be the issue :).

`root@cg-docker1:~/mail# nano docker-compose.yml
  GNU nano 2.2.6                                                               File: docker-compose.yml

maildata:
  image: ubuntu
  volumes:
    - /var/mail
  command: /bin/true

mail:
  image: "tvial/docker-mailserver"
  hostname: mail
  domainname: clevergirls.tv
  volumes_from:
   - maildata
  ports:
  - "25:25"
  - "143:143"
  - "587:587"
  - "993:993"
  volumes:
  - ./spamassassin:/tmp/spamassassin/
  - ./postfix:/tmp/postfix/
  - ./opendkim/keys:/etc/opendkim/keys
  - ./letsencrypt/etc:/etc/letsencrypt
  environment:
  - DMS_SSL=letsencrypt
  - ENABLE_POP3=1








`

**Comment by tomav** [comment]
I am getting this from google

What is Google usage here?

**Comment by Dynamite874** [comment]
Google is what I am using to connect to the server. So the mail client, I
am assuming the errors google is giving me is due to the config I have for
the mail server.

Sorry for not being clear about that.

--
Will Wright
will@willsworkspace.co.uk
http://willsworkspace.co.uk
--

**Comment by Dynamite874** [comment]
This might not be a issue with the mailserver anymore, seem to be having a
issue with my server MX records :). You should be able to close this now.
Thanks for the help.

--
Will Wright
will@willsworkspace.co.uk
http://willsworkspace.co.uk
--

**Comment by tomav** [comment]
Or perhaps Google is waiting for special SSL ciphers... Let's close this issue since not directly related to features provided by the image.
But feel free to contribute if needed.
