### ISSUE TITLE
How to remove zen.spamhaus.org in least destructive way

### ISSUE THREAD

**Issue by andymel123** [tomav/docker-mailserver#941]
I have to remove zen.spamhaus.org because the DNS servers I'm using are blocked because of too much queries.

Maybe you can give me some advise how to remove it in the least destructive way.

1. If I add a postscreen_dnsbl_sites and a smtpd_recipient_restrictions entry to my config/postfix-main.cf  without the zen.spamhaus.org parts I guess it will simply override the entries from the main.cf right? So if you improve it in future updates I will not see the difference. Any "less destructive" way of doing it?

2. Should I change the weighting of the other entries in postscreen_dnsbl_sites if I remove spamhaus?

Thx for you advise!

**Comment by 17Halbe** [comment]
Nr. 1 would be the way to go. For changes check the [release page](https://github.com/tomav/docker-mailserver/releases)
Though I don't think that every single config line change will be noted there.
You could always manually check after an update if something has changed, I know that its tedious, but I guess one has to die one death! ;)
There would be several ways to do so:
- you could just have a look [here](https://github.com/tomav/docker-mailserver/blob/a564cca0e55feba40e273a5419d4c9a864460bf6/target/postfix/main.cf#L54) or 
- start your server once with your `postfix-main.cf` entries disabled or 
- I think the nicest way: check with your new image: `docker run --rm tvial/docker-mailserver:latest cat /etc/postfix/main.cf | diff config/postfix-main.cf -` (Replace latest with stable, regarding your image choice)
- I'm sure there are a couple more ways to check for those changes.

Does that solve your question?

**Comment by mborko** [comment]
I've written a simple bash script:
```bash
#!/bin/bash
sed -i 's/zen\.spamhaus\.org\*3//' /etc/postfix/main.cf 
sed -i 's/reject_rbl_client\ zen\.spamhaus\.org,\ //' /etc/postfix/main.cf
```
and put it into ``./config/fix.sh`` where you can execute it with ``docker exec mail bash -c '/tmp/docker-mailserver/fix.sh'``

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
