### ISSUE TITLE
Restrict authenticated senders to mynetworks only

### ISSUE THREAD

**Issue by time4tea** [tomav/docker-mailserver#944]
More of an FYI than an issue really, could be added to docs?

If you use the given setup then senders on the internet can use AUTH commands to guess any users password. Once they have that then they will be able to use the server as a proxy.
If you want only people in your network to be able to authenticate, you can do the following:

in config/postfix-main.cf, add:
`smtpd_discard_ehlo_keyword_address_maps = cidr:/etc/postfix/esmtp_access`

in docker-compose.yml, add:
`    - ${PWD}/etc_postfix/esmtp_access:/etc/postfix/esmtp_access:ro`

add new file etc_postfix/esmtp_access
```
# Allow DSN/AUTH requests from local subnet only
192.168.0.0/16      silent-discard
0.0.0.0/0           silent-discard, dsn, auth
::/0                silent-discard, dsn, auth
```

**Comment by 17Halbe** [comment]
Thanks! That's a nice addition! 
If you like you could add that to the wiki!

Though the attacker would have to wait 6 seconds after the ehlo command(if I remember correctly) before he could try one password . If he would speak too fast, postscreen would block him. However, if you got fail2ban enabled, three failed login attempts from the same IP would ban that IP as well. So I hope this attack vector should be unlikely.

**Comment by time4tea** [comment]
It is very likely. Fail2ban by default blocks for 10 mins. I can see remote
servers doing auth attempts every 12 mins. Raising the ban and search
times... the attackers change their patterns to match.
You only need a single user with a weak password.

James

**Comment by 17Halbe** [comment]
Oh, ok, I don't have those. Just random ones. That's strange. Did you consider, that you are specifically targeted? 
If you look at the common rainbowtables, they have around 1-1000 trillion ASCII entries. So if you are trying let's say just the most 1000 common passwords it would take you on average more than 4 days to find a valid one. I always thought the common way to transform a server into a zombie one was in probing for malconfigured servers. But honestly, who am i to know! ;) So thanks again!

**Comment by yura8** [comment]
Would this prevent usage of SMTP relays such as SES and Mailgun? I suppose specific ranges could be added into the etc_postfix/esmtp_access file but companies may not announce those or change without a warning.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
