### ISSUE TITLE
DKIM Question: Is it possible to switch off DKIM?

### ISSUE THREAD

**Issue by helmutundarnold** [tomav/docker-mailserver#946]
Is there a CONFIG VAR to switch DKIM off?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by johansmitsnl** [comment]
If you don't generate a DKIM key it does not sign it.
Never tested this though.

**Comment by helmutundarnold** [comment]
Thanks that works. I did:

- stopped docker container
- rm -rf config/opendkim
- docker rm <container>
- recreate the container
