### ISSUE TITLE
Local System User Mail Delivery Issues 

### ISSUE THREAD

**Issue by pfmsny** [tomav/docker-mailserver#947]
My setup is as follows, mail.maildomain.com, this domain does not have MX or any deliverable mailboxes, it is just a mail server for other virtual domains. This servers local mail (root@) appears to have delivery issues its trying to send mail to a hostname and domain name that do not accept mail, in addition to being the external hostname and domain name of the mail server itself. I added a .forward file in the /root/ directory. The address is an external email address that exists and is deliverable from the internet. Will this solve my issues? The host machine does not have postfix or any mail packages installed, it is all running in this docker container. What are opinions at a possible solution if what I did is in-sufficent?

Any feedback would be greatly appreciated. 

/etc/hosts
internetaddressofmailserver mail.mailserverdomain.com
127.0.0.1 mail.mailserverdomain.com localhost.localdomain localhost
127.0.0.1 mail

Log: 
mail postfix/smtpd[29932]: connect from unknown[172.20.0.1]
Apr 11 04:00:03 mail docker-compose[1438]: mail    | Apr 11 04:00:02 mail postfix/smtp[29921]: warning: host mail.mymailserverdomain.com[internetaddressofmailserver]:25 greeted me with my own hostname mail.mymailserverdomain.com
Apr 11 04:00:03 mail docker-compose[1438]: mail    | Apr 11 04:00:02 mail postfix/smtp[29921]: warning: host mail.mymailserverdomain.com[internetaddressofmailserver]:25 replied to HELO/EHLO with my own hostname mail.mymailserverdomain.com
Apr 11 04:00:03 mail docker-compose[1438]: mail    | Apr 11 04:00:02 mail postfix/smtp[29921]: B36AA3E80D: to=<root@mail.mymailserverdomain.com>, orig_to=<root>, relay=mail.mymailserverdomain.com[internetaddressofmailserver]:25, delay=0.65, delays=0.05/0.02/0.58/0, dsn=5.4.6, status=bounced (mail for mail.mymailserverdomain.com loops back to myself)
Apr 11 04:00:03 mail docker-compose[1438]: mail    | Apr 11 04:00:02 mail postfix/smtpd[29932]: disconnect from unknown[172.20.0.1] ehlo=1 quit=1 commands=2 00:00

**Comment by akmet** [comment]
http://postfix.1071664.n5.nabble.com/dnsblog-lookup-error-questions-td52034.html

I got the same errors. Not sure what public DNS my mailserver is using at the moment. Will have a look at it later and will report :)

**Comment by crazystick** [comment]
To clarify - are you trying to have mail delivered from host to container, or trying to get the mail for root dlivered in the container (that's mainly cron output I think). If it's the latter, I'm working on a solution for it - as far as I can tell you need to configure /etc/aliases and use a hash: instead of texthash: database, and configure `mydestination` in main.cf

**Comment by pfmsny** [comment]
crazystick, I am actually unsure, "mail" "sandmail" and postfix are not installed on the host so I am assuming the attempts by root@ and amavis@ so far have been in the container. Can you shed some light on what the best to solve this would be?

**Comment by crazystick** [comment]
I have some questions of my own related to this, @johansmitsnl can you provide some input here.

To make this work, the following steps are necessary:

1. Postfix needs to accept mail for local machine => add `mydestination = $myhostname, localhost.$mydomain, localhost` in `main.cf`
2. Root needs a valid alias in `/etc/aliases` => add `root: valid-user@domain.com` in `/etc/aliases`
3. texthash doesn't work for /etc/aliases => run `postalias /etc/aliases` and `s/texthash/hash` in `main.cf`
4. In case you wanted to use the postmaster@domain.com as your root user (quite reasonable) then add either a virtual mapping or regex mapping for postmaster@domain.com -> valid-user@domain.com 

My question is whether there is a good reason why these seemingly sensible defaults aren't in the base image, as that is quite a few hoops to jump through. I would suggest that 1, 2 & 3 can be the default out of the box, and the user only has to set the exising `POSTMASTER_ADDRESS` env var to a valid user, or else map postmaster@domain.com to a valid user by existing methods.
