### ISSUE TITLE
CI is not reliable (?)

### ISSUE THREAD

**Issue by callmemagnus** [tomav/docker-mailserver#950]
Still while investigating my broken builds, I see that the builds running on Travis are unreliable.

I believe that this is related to the amount of processing needed to start the containers completely. I see that this has probably already been an issue in the past when I see all the "sleep" commands present in the Makefile and in some tests.

The following screen show illustrates it at best:
![image](https://user-images.githubusercontent.com/232478/38782930-897199d6-40fb-11e8-8861-fc43aaaf8544.png)
Source: https://travis-ci.org/callmemagnus/docker-mailserver/branches

Both branches are the same. "Patch-1" is the source of my PR and its build did not trigger on your repo (?).

I am pretty convinced that the result of the builds are dependent on the availability and power of Travis build slave.

**Comment by johansmitsnl** [comment]
What you see is true. They are sometimes unreliable depending on the time the build is created.
However when you investigate the errors it is mostly test 6 that fails.
This can be improved by detecting if the images are running and available and then send the test data for processing and then again wait if this data is processed.

Any suggestions?

**Comment by callmemagnus** [comment]
I didn't look into all the details of the build.
As far as I can see it is the `dovecot/ssl-param` that requires a lot of CPU time, with current make I have 3-4 at the same time on my laptop.

It seems that the container is able to receive the test data but not to process it. Which breaks some tests (?)

Open questions:

# Are all the containers needed for the tests?
# Are all the containers to be started upfront? Would it be possible to do start image run specific tests for that image, then go to next tests.

I agree that the detection of "readyness" is probably a good idea. Maybe embed a script in the image that would tell based on several criteria whether the "boot" process is finished for a given container.

I see these "checks":

* presence of ssl-param in `ps` is a no-go
* `netstat` should list all listening ports
* maybe do a local "telnet" to see the response of a given service (?)

**Comment by johansmitsnl** [comment]
Now there a clear steps that it goes trough for each combination.

1. build
2. start the different configurations
3. Put in test data for each configuration
4. Test if it worked correctly

This can be separated in several tests #945 can have a advantage in development time and also in test stability.

With `nc` you can also probe ports. But the SSL generation for Dovecot starts to listen on the port and accepts a connection but keeps it in hold until it is ready with the SSL generation.
Not sure how to test if it is fully running.

**Comment by callmemagnus** [comment]
I'm trying something like this in the Makefile just after the list of docker run...

```
#!/bin/bash

function is_container_ready () {
  local container=$1
  docker container logs $container | grep "SSL parameters regeneration completed"
}

function wait_on_container () {
  local container=$1
  echo -n "Waiting on $container"
  while true
  do
    result=$(is_container_ready $container)
    if [ $? == 0 ]
    then
      break
    fi
    echo -n .
    sleep 1
  done
  echo "... ready"
}

list=$(docker container ls --format="{{.Names}}\t{{.Image}}" | \
  grep '^mail' | \
  grep -v smtponly | \
  grep docker-mailserver | awk '{print $1}')

for i in $list;
do
  wait_on_container $i
done
```

Just after the containers are started

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
