### ISSUE TITLE
container eating emails by removing domain from username

### ISSUE THREAD

**Issue by Josh5** [tomav/docker-mailserver#968]
when sending emails, it looks like postfix is removing the message because it cannot match the username. There is something wrong. Works fine in stable branch

LOGS:
```
May  3 03:33:13 lkm postfix/qmgr[1013]: 6BBA44037FC: removed
May  3 03:33:13 lkm postfix/local[1057]: 99288403AAE: to=<****@****.co.nz>, relay=local, delay=0.02, delays=0.01/0/0/0.01, dsn=5.1.1, status=bounced (unknown user: "****")
May  3 03:33:13 lkm postfix/cleanup[1056]: 9C67D403AAF: message-id=<20180503033313.9C67D403AAF@*****.co.nz>
May  3 03:33:13 lkm postfix/bounce[1058]: 99288403AAE: sender non-delivery notification: 9C67D403AAF
May  3 03:33:13 lkm postfix/qmgr[1013]: 9C67D403AAF: from=<>, size=3524, nrcpt=1 (queue active)
May  3 03:33:13 lkm postfix/trivial-rewrite[1051]: warning: do not list domain *****.co.nz in BOTH mydestination and virtual_mailbox_domains
May  3 03:33:13 lkm postfix/qmgr[1013]: 99288403AAE: removed
May  3 03:33:13 lkm postfix/local[1057]: 9C67D403AAF: to=<****@****.co.nz>, relay=local, delay=0.02, delays=0.01/0/0/0.01, dsn=5.1.1, status=bounced (unknown user: "****")
May  3 03:33:13 lkm postfix/qmgr[1013]: 9C67D403AAF: removed
```

If you need more info, I cannot help out. 
Just thought I'd dump this here in-case you had not seen it. Close this if it isn't helpful.

**Comment by OneOfOne** [comment]
This is a huge issue.

**Comment by troojaan** [comment]
same issue here!

**Comment by johansmitsnl** [comment]
Could anyone you debug and provide a PR to fix it?

**Comment by a-cher** [comment]
It seems postfix tries to use local delivery mechanism instead of virtual transport for domain and, therefore, it searches usernames in local recipient tables (/etc/passwd and etc) instead dovecot user tables
In my case, it is because of the hostname for mail host matches the mail domain.
my domain is ABC.COM
I have mailboxes info@ABC.COM, user1@ABC.COM, etc
and MX host for my domain is ABC.COM too (not mail.ABC.com as usual)
according to default postfix configuration 
`mydestination = $myhostname, ....`
it corresponds to
`mydestination = ABC.COM, ....`
but virtual_mailbox_domains contains ABC.COM too
and you can see warnings in logs: 
warning: do not list domain *****.co.nz in BOTH mydestination and virtual_mailbox_domains

There are several ways to fix this. But I'm not advanced postfix administrator and I have no time for deep investigation
I just removed $myhostname from mydestination 
`mydestination = $myhostname, localhost.$mydomain, localhost`
replace to
`mydestination = localhost.$mydomain, localhost`

You can do it by creating file postfix-main.cf in configuration dir with content:
`mydestination = localhost.$mydomain, localhost`

And it works for me.

**Comment by barrer** [comment]
@a-cher 
You are right!
[http://www.postfix.org/ADDRESS_CLASS_README.html#virtual_mailbox_class](http://www.postfix.org/ADDRESS_CLASS_README.html#virtual_mailbox_class)
```
The virtual mailbox domain class.

Purpose: final delivery for hosted domains where each recipient address can have its own mailbox, and where users do not need to have a UNIX system account. A virtual mailbox example is given in the VIRTUAL_README file.

Domain names are listed with the virtual_mailbox_domains parameter. The default value is $virtual_mailbox_maps for Postfix 1.1 compatibility.

Valid recipient addresses are listed with the virtual_mailbox_maps parameter. The Postfix SMTP server rejects invalid recipients with "User unknown in virtual mailbox table". If this parameter value is empty, the Postfix SMTP server accepts all recipients for domains listed in $virtual_mailbox_domains.

The mail delivery transport is specified with the virtual_transport parameter. The default value is virtual for delivery with the virtual(8) delivery agent.
```

[http://www.postfix.org/postconf.5.html#mydestination](http://www.postfix.org/postconf.5.html#mydestination)
```
The list of domains that are delivered via the $local_transport mail delivery transport. By default this is the Postfix local(8) delivery agent which looks up all recipients in /etc/passwd and /etc/aliases. The SMTP server validates recipient addresses with $local_recipient_maps and rejects non-existent recipients. See also the local domain class in the ADDRESS_CLASS_README file.
```

This project replaces the UNIX system account with a virtual account. So your email domain name (FQDN) cannot appear in the `mydestination=`configuration value.

Your solution not only solves the warning message problem (`warning: do not list domain *****.co.nz in BOTH mydestination and virtual_mailbox_domains`), but also solves the problem that the same domain name mailboxes cannot be sent to each other.

Thank you very much!

**Comment by evaryont** [comment]
Postfix as it's configured in this container is generally expected to host email off of a sub-domain, not the root domain. And if people using a subdomain include this fix, it'll break their set ups as well.

There needs to be a check/warning if $HOSTNAME and $DOMAINNAME are the same. Possibly make the configuration even smarter and not include $HOSTNAME in mydestination if that's the case.

**Comment by Stephan500** [comment]
So is it correct that the most basic setup (having just one domain) is not configurable? It sounds strange for a "simple" mailserver. Any chance this is fixed soon?

**Comment by erik-wramner** [comment]
Please note that this issue is closed and from 2018. I haven't read all the posts, but docker-mailserver works quite well with a single domain. If you run into issues please post a new issue with configuration details and logs.

**Comment by Stephan500** [comment]
This very issue is still open. And my logs show the same as in the original post. There are workarounds described (like using a sub-domain). But those don't work for me. If necessary I could create a new issue, but I consider it as a duplicate.  
evaryont mentioned that "Postfix as it's configured in this container is generally expected to host email off of a sub-domain, not the root domain."

**Comment by erik-wramner** [comment]
Sorry, I saw the closed icon above but it was for a linked issue. As for the problem itself I wish people would stop using the term sub-domain when they mean host. Postfix as configured is meant to host mail for one or more domains and is expected to run on a host referenced by DNS MX records. The normal notation for a host is hostname.example.com, not example.com which is just the domain.

It is possible to use docker-mailserver with the mail server host being just the domain (example.com) and there are some more recent issues with solutions if that is what you are after? I'll see if I can dig them up.

**Comment by erik-wramner** [comment]
In fact the solution is higher up in the thread:

> I just removed $myhostname from mydestination
> `mydestination = $myhostname, localhost.$mydomain, localhost`
>
> You can do it by creating file postfix-main.cf in configuration dir with content:
> `mydestination = localhost.$mydomain, localhost`

We should make that a FAQ or possibly automate it in the start script. I just don't know if it has unforeseen consequences. There are several other users who have solve the problem that way recently, though. Anyway, try it!

**Comment by Stephan500** [comment]
> 
> It is possible to use docker-mailserver with the mail server host being just the domain (example.com) and there are some more recent issues with solutions if that is what you are after? I'll see if I can dig them up.

Yes, in my case hostname = domain name. That's perfectly legal and as I said the most basic config. I feel not very comfortable removing $myhostname. The general problem is that postfix would serve host mailadresses as virtual. But maybe that's the only chance with a container solution. Some clarificaton in the Wiki/README would be good anyway.

Thanks for taking the time!

**Comment by erik-wramner** [comment]
> But maybe that's the only chance with a container solution

Forget about the container and focus on Postfix and Dovecot. If you have another solution that works with them and that we can implement without breaking things for other users I'm all ears. If not you can either use the approach above or (if you control the DNS) add a host name that points to the same address as the domain and use that host name as MX record and host. Users can still connect to the bare domain (my users do) as it has the same address.

**Comment by erik-wramner** [comment]
Updated README and FAQ, https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#can-i-use-nakedbare-domains-no-host-name.

**Comment by nsk7even** [comment]
I fell into this trap as well and wanted to fix it the right way (specify correct mail server name).

Maybe I missed something, but it only worked for me, using the **OVERRIDE_HOSTNAME** parameter in the _env-mailserver_ file.

First, I tried only setting **HOSTNAME** in the _.env_ file, but this didn't had an effect.

Just FYI, if you are as dense as me... :)

**Comment by suprematis** [comment]
@nsk7even allowed me to run my mail server with that comment.  It is the most sensible solution to launch a proper mail server in seconds!!! Awesome!!!
