### ISSUE TITLE
daily summary mail counts mails twice

### ISSUE THREAD

**Issue by andreasgerstmayr** [tomav/docker-mailserver#969]
The daily summary mail counts all mails twice.

Example log of a mail sent to hotmail:
```
May 02 22:56:18 XXX docker[32360]: May  2 20:56:17 XXX postfix/smtp[17742]: XXX: to=<XXX@hotmail.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=3.5, delays=1.2/0.01/0/2.3, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as XXXX)
May 02 22:56:21 XXX docker[32360]: May  2 20:56:21 XXX postfix/smtp[17753]: XXX: to=<XXX@hotmail.com>, relay=hotmail-com.olc.protection.outlook.com[104.47.42.33]:25, delay=3.8, delays=0.03/0.02/1.6/2.2, dsn=2.6.0, status=sent (250 2.6.0 <XXX@XXX> [InternalId=XXX, Hostname=BY2NAM03HT036.eop-NAM03.prod.protection.outlook.com] 475703 bytes in 1.317, 352.479 KB/sec Queued mail for delivery)
```

i.e. at first it is relayed to `127.0.0.1` and then to the destination server (in this case hotmail).
Same for incoming mails.

I guess this is because all mails received by postfix are forwarded to amavis and then received again by postfix if they are clean?
Is there anything I can do to get correct statistics?

**Comment by johansmitsnl** [comment]
Can it be because of an alias?

**Comment by andihit** [comment]
I have configured aliases, but also mails directly to an account are counted twice, and it doesn't explain that sent mails are also counted twice.

I just took a look at the code of pflogsumm, and it does search the log file for `status=sent`. Postfix is configured with `content_filter = smtp-amavis:[127.0.0.1]:10024` (forward mails to amavis) and receives filtered mails at `127.0.0.1:10025`.

So imho everybody should experience the same issue.

Steps to reproduce:
* send a mail to e.g. mail-tester.com (a domain you haven't sent any mails today)
* run `/usr/sbin/pflogsumm /var/log/mail/mail.log --problems-first`

You'll see 2 sent messages to this domain.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
