### ISSUE TITLE
rspamd support?

### ISSUE THREAD

**Issue by LeoWinterDE** [tomav/docker-mailserver#975]
Has anyone tested the integration with [rspamd](https://rspamd.com/)?

**Comment by klausenbusk** [comment]
For what it worth, I think we can reduce the moving parts a "lot" by switching to rspamd ([opendkim](https://rspamd.com/doc/modules/dkim_signing.html), [postgrey](https://rspamd.com/doc/modules/greylisting.html), [postscreen maybe?](https://forums.zimbra.org/viewtopic.php?t=62443), amavis)

**Comment by johansmitsnl** [comment]
@klausenbusk could you add the pro's and con's of this switch? And if all are 👍could you add a PR?

**Comment by denji** [comment]
[Spamassassin](https://spamassassin.apache.org/) | [Rspamd](https://rspamd.com/)
-- | --
[OpenDKIM](http://www.opendkim.org/) | [Rspamd DKIM](https://rspamd.com/doc/modules/dkim.html) and [DKIM signing module](https://rspamd.com/doc/modules/dkim_signing.html)
[OpenDMARC](https://dmarc.org/) | [Rspamd DMARC module](https://rspamd.com/doc/modules/dmarc.html)
[Postgrey](https://postgrey.schweikert.ch/) | [Rspamd Greylisting module](https://rspamd.com/doc/modules/greylisting.html)
[Gross](https://code.google.com/archive/p/gross/) | [Rspamd Greylisting module](https://rspamd.com/doc/modules/greylisting.html)
[Amavisd](https://www.ijs.si/software/amavisd/) | [Rspamd proxy worker](https://rspamd.com/doc/workers/rspamd_proxy.html)

Zeyple catches email from the postfix queue, then encrypts it if a corresponding recipient's GPG public key is found. Finally, it puts it back into the queue.
* https://infertux.com/labs/zeyple/
* https://github.com/infertux/zeyple

ARC standard: https://rspamd.com/doc/modules/arc.html
* http://arc-spec.org/
* https://datatracker.ietf.org/doc/draft-ietf-dmarc-arc-usage/
* https://dmarc.org/presentations/ARC-Overview-2016Q2-v03.pdf
* https://blog.returnpath.com/how-to-explain-authenticated-received-chain-arc-in-plain-english-2/

**Comment by DuncanvR** [comment]
+1 for Zeyple as mentioned by @denji -- though I'm not sure that automatically comes with rspamd. Perhaps a separate issue for that would be appropriate?

**Comment by mindrunner** [comment]
Has there been any work on this recently?

**Comment by aendeavor** [comment]
This is interesting. What's the current status?

**Comment by mindrunner** [comment]
I don't think there has been any work on this recently

**Comment by aendeavor** [comment]
I guess you're right @mindrunner, which is a shame. What do you think how much time would be needed to research and implement this? Is that worth it?

**Comment by erik-wramner** [comment]
I looked at this a long time ago and came to the conclusion that it would mean a lot of work plus a lot of testing to make this switch. Perhaps it is better (sounds good but I have no personal experience), but it sounds risky. If we do this we should also consider downstream projects and custom changes people have done. Not that we need to support everything, but I like that we finally support ARM. It would be a pity to break that.

**Comment by aendeavor** [comment]
I'm totally with you there @erik-wramner. I'll close this off, seeing this has stalled. If this (large) project will be picked by someone else, please open a new issue related this this topic.

**Comment by Nytelife26** [comment]
I came here to ask this very thing. If anyone else would be willing to help, I am willing to lead such a task, given that I intend to use `rspamd` in the setup for my organization.

**Comment by georglauterbach** [comment]
> I came here to ask this very thing. If anyone else would be willing to help, I am willing to lead such a task, given that I intend to use `rspamd` in the setup for my organization.

Please open a new tracking issue so people can see it at the top of the issue list (I will ten label it appropriately). You can then mark the maintainers and moderators team to ask. Maybe some other interested people join you :)

**Comment by georglauterbach** [comment]
@Nytelife26 @LeoWinterDE Rspamd is now on `:edge` and will be published on stable with the upcoming v12.0.0.
