### ISSUE TITLE
mydestination went from empty to "$myhostname, localhost.$mydomain, localhost"

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tomav/docker-mailserver#978]
I don't know if this is a bug or not, but I used the docker image from

2018-03-08 and updated to the 2018-05-22 image.

This updated postfix from 3.1.6 to 3.1.8

I'm not receiving any mail for my virtual email users anymore.

What I see is that:

```
--- etc/postfix/main.cf    2018-03-08 10:49:49.000000000 +0100
+++ etc/postfix/main.cf    2018-05-22 23:50:56.000000000 +0200
@@ -7,9 +7,9 @@

 # Basic configuration
 # myhostname =
-alias_maps = texthash:/etc/aliases
-alias_database = texthash:/etc/aliases
-mydestination =
+alias_maps = hash:/etc/aliases
+alias_database = hash:/etc/aliases
+mydestination = $myhostname, localhost.$mydomain, localhost
 relayhost =
```

Clearing `mydestination`  fixes virtual domains for me.  I'm not sure if this is a regression or not, but at least my setup broke.

**Comment by crazystick** [comment]
Is it working for you now? The change was deliberate to fix #947 - the mydestination parameter is required for that. 

This should not affect delivery of your virtual users. All your virtual domains should be populated into /etc/postfix/vhosts - you can check with `./setup.sh debug login "cat /etc/postfix/vhost"`

See also http://www.postfix.org/VIRTUAL_README.html

**Comment by alexanderkjeldaas** [comment]
I'm putting it back in my build scripts now.  This is my build:
```
FROM tvial/docker-mailserver:latest

# Bug https://github.com/tomav/docker-mailserver/issues/852
RUN perl -pi -e 's,sender_canonical_,#sender_canonical_,g;s,recipient_canonical_,#recipient_canonical_,g' /etc/postfix/main.cf
# Fix dovecot: imap-login: Maximum number of connections from user+IP exceeded
RUN perl -pi -e 's,#mail_max_userip_connections = 10,mail_max_userip_connections = 10000,g' /etc/dovecot/conf.d/20-imap.conf
# Clear  default mydestination = $myhostname, localhost.$mydomain, localhost
# otherwise the virtual hosts won't work.
# see https://github.com/tomav/docker-mailserver/issues/978
RUN perl -pi -e 's,mydestination =.*,mydestination =,g' /etc/postfix/main.cf
```

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
