### ISSUE TITLE
TLS options for LDAP

### ISSUE THREAD

**Issue by tailtwo** [tomav/docker-mailserver#979]
## Context
In order to use this container with my LDAP server, I have to use TLS with SASLauth and Dovecot. Unfortunately, I don't see any envvar that would allow me to set the desired options.

## Expected Behavior
`- SASLAUTHD_LDAP_START_TLS=yes` set `ldap_start_tls: yes` in `/etc/saslauthd.conf`
`- SASLAUTHD_LDAP_TLS_CHECK_PEER=no` set `ldap_tls_check_peer: no` in `/etc/saslauthd.conf`
`- DOVECOT_TLS_REQUIRE_CERT=never` set `tls_require_cert = never` in `/etc/dovecot/dovecot-ldap.conf.ext`

Generally, I would like to be able to use more ldap envvars without mounting a file in the container (I'm using Kubernetes and it's not very practical), like those :
https://blog.sys4.de/cyrus-sasl-saslauthdconf-man-page-en.html
http://ftp.ics.uci.edu/pub/centos0/ics-custom-build/BUILD/dovecot-1.1.7/doc/dovecot-ldap-example.conf

## Possible Fix
Add more envvars to configure LDAP for dovecot and salsauth.

**Comment by johansmitsnl** [comment]
It is merged
