### ISSUE TITLE
Clarification of README required

### ISSUE THREAD

**Issue by StrayLightning** [tomav/docker-mailserver#982]
The README.md currently contains the following:

    Create a docker-compose environment:
    Edit the .env to your liking. Adapt this file with your FQDN.
    Install docker-compose in the version 1.6 or higher.

Followed by:

    Create your mail accounts:
    ./setup.sh email add <user@domain> [<password>]

The setup.sh script requires that the Docker container be running, but there doesn't appear to be anything that has started the container at that point.  What am I missing?

**Comment by shangshun2013** [comment]
I hava the problem too。please give a easy installer

**Comment by StrayLightning** [comment]
The problem preventing me starting the container was apparently an SMTP service already running on the machine.  However, the README does still seem to be back-to-front.  Do you need to start the container running, then configure email addresses and DKIM, and then restart the container to pick up the new configuration?

I am not able to create email addresses because I'm running into permissions errors, and I think this is SELinux (c.f. issue #753.)

When I get something running I'll prepare a PR with changes to the README.

**Comment by StrayLightning** [comment]
The failure to create email addresses was indeed due to SELinux.  Copying the updated configuration from issue #753 into the docker-compose.yml and recreating the container has now allowed me to create an email address.

**Comment by shangshun2013** [comment]
i failured ,and i don't know why ............ if you are success,can you give me a  detail steps for me ? email:1102184755@qq.com. come from CHINA'thinks.................

**Comment by erik-wramner** [comment]
Closing as problem was solved in June 2018.
