### ISSUE TITLE
/etc/aliases overwritten start-mailserver.sh:766

### ISSUE THREAD

**Issue by dannymk** [tomav/docker-mailserver#988]
## Context

I need to add more aliases to the /etc/aliases file but no matter what I do I can't.
I can always use my own start-mailserver.sh script but really don't want to.

## Expected Behavior

You should append to `echo "root: ${POSTMASTER_ADDRESS}" >> /etc/aliases"`
instead of overwritting

## Possible Fix

echo "root: ${POSTMASTER_ADDRESS}" >> /etc/aliases"

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by dannymk** [comment]
Fixed by reading documentation as well as http://www.postfix.org/VIRTUAL_README.html and the start-mailserver.sh script.

**Comment by dannymk** [comment]
Spoke too soon.  This is still an issue.
We need to use the pipe to script function as in:

`some-email-alias: "|/usr/local/bin/processMail.sh"`

**Comment by johansmitsnl** [comment]
Did you check the wiki: https://github.com/tomav/docker-mailserver/wiki/Configure-Aliases ?

**Comment by johansmitsnl** [comment]
Not sure what the example was. When I check my config I can see that the postmaster address is in the aliases file for root.

**Comment by johansmitsnl** [comment]
you need an extra alias for a system user?

**Comment by dannymk** [comment]
OK, an alias of this type passes the entire contents of the email to the above mentioned script via STDIN.  It is a standard practice.  Not sure how else to explain this.

**Comment by dannymk** [comment]
PR can mean so many things.  Do you meal a pull request?

**Comment by johansmitsnl** [comment]
Yes a Pull Request.

**Comment by peter-hartmann** [comment]
For a quick fix perhaps map the aliases files as a volume, e.g.: 
1. Create a copy of /etc/aliases outside of the container:
```
docker exec -it mail cat /etc/aliases > config/postfix-aliases.cf
```
2. Map it back into the container as a readonly ```:ro``` volume by adding this to docker-compose.yaml:
```
    volumes:
    - ./config/postfix-aliases.cf:/etc/aliases/:ro
```
3. To apply those changes run:
```
docker up -d mail
```
4. To apply subsequent changes to the aliases file run newaliases inside the container:
```
docker exec -it mail newaliases
```

**Comment by peter-hartmann** [comment]
Can anybody tell why PR  #1065 fails building?
