### ISSUE TITLE
forward, alias, mailing list

### ISSUE THREAD

**Issue by kopax** [tomav/docker-mailserver#99]
Hi want to create aliases for every email.

tom.soyer@compay.tld => tsr@company.tld

Is it possible to have multiple alias ?

tsr@company.tld => job@company.tld

I also want to be able to create mailing list, for example : 

job@company.tld => tsr@company.tld, lvm@company.tld

Is it possible to forward to multiple mail ? If yes, should I use one line by forward are is there a sweeter syntax ?

**Comment by tomav** [comment]
Just try in the `virtual` file. I think it's out of the box in postfix.

**Comment by tomav** [comment]
http://www.postfix.org/VIRTUAL_README.html#forwarding

**Comment by kopax** [comment]
It work. Thanks ;)

**Comment by george-angel** [comment]
Sorry to post on old Issue, has any resolved the issue of duplicate emails with virtual postfix approach?

https://serverfault.com/questions/112958/postfix-aliases-and-duplicate-e-mails-how-to-fix describes the issue really well.
