### ISSUE TITLE
fuse volume permission denied

### ISSUE THREAD

**Issue by derit** [tomav/docker-mailserver#991]
i have a fuse volume in docker using https://github.com/vieux/docker-volume-sshfs
when i receive email i have a permission problem, how to fix it?

note:
i using fuse with docker plugin and fuse sshfs  

error logs:
Jun 14 09:29:26 72d59c8123 postfix/smtp[1125]: 285C0285A22: to=<test@test.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=1.6, delays=0.58/0.01/0.01/0.98, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 7DDD8285A2D)
Jun 14 09:29:26 72d59c8123 postfix/qmgr[1016]: 285C0285A22: removed
Jun 14 09:29:45 72d59c8123 dovecot: ssl-params: SSL parameters regeneration completed
Jun 14 09:29:45 72d59c8123 dovecot: lmtp(1134): Connect from local
Jun 14 09:29:45 72d59c8123 dovecot: lmtp(1134, test@test.com): Error: User initialization failed: Namespace '': stat(/var/mail/test.com/test) failed: Permission denied (euid=5000(docker) egid=5000(docker) stat(/var/mail/test.com/test) failed: Permission denied, dir owned by 0:0 mode=0755)
Jun 14 09:29:45 72d59c8123 dovecot: lmtp(1134): Disconnect from local: Successful quit
Jun 14 09:29:45 72d59c8123 postfix/lmtp[1133]: 7DDD8285A2D: to=<test@test.com>, relay=72d59c8123.test.com[/var/run/dovecot/lmtp], delay=19, delays=0.01/0.01/19/0, dsn=4.3.0, status=deferred (host 72d59c8123.test.com[/var/run/dovecot/lmtp] said: 451 4.3.0 <test@test.com> Temporary internal error (in reply to end of DATA command))

**Comment by johansmitsnl** [comment]
Not sure this will work properly. You need to be able to create files with the uid 5000

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
