### ISSUE TITLE
additional postfix header_checks

### ISSUE THREAD

**Issue by millerjason** [tomav/docker-mailserver#999]
## Context

docker-mailserver is presently using postfix's header_checks via the configuration file target/postfix/sender_header_filter.pcre.  I would like to add support for extending this file to include additional user header check directives (such as regex rejects) in the user configuration directory.

## Expected Behavior

This is working as expected, but see possible fix for improved functionality.

## Actual Behavior

This is not user configurable.

## Possible Fix

One potential solution would be to append the user's config/postfix-header_checks.cf file to follow the existing target/postfix/sender_header_filter.pcre.  Or if postfix supports multiple checks, include both in the processing rules.  I am open to how this could be solved and willing to submit a PR for it.

## Steps to Reproduce

1. Start docker-mailserver
2.
3.
4.

## Your Environment

* Amount of RAM available: 16GB
* Mailserver version used: docker-mailserver
* Docker version used: 18.03.1-ce
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by johansmitsnl** [comment]
Could you provide a PR for this?
